### ISSUE TITLE
support for Google App Engine modules

### ISSUE THREAD

**Issue by sasxa** [DonJayamanne/pythonVSCode#1]
Hi, 
first of all, thanks for making this!

Is there any configuration or settings for this extension? 

I'm getting `unable to import ...` errors when importing gae modules. Any suggestions how to make them available to the linter and in code-completion?

I have gae installed in:

    c:\dev\gcloud\google-cloud-sdk\platform\google_appengine\

**Comment by DonJayamanne** [comment]
Hi Sasxa, the latest version support a number of configuration options. I will try it at my end. Can you send me a sample of the code used. Is it falling over at the import statement? The next version Wil have a few more configuration options and more  logging. I will test your changes.

**Comment by DonJayamanne** [comment]
I think I may have identified the issue. Will be able to test It out on Wednesday, hopefully I will have a fix before the end of the week.

**Comment by sasxa** [comment]
If I write simple python file:

    import logging
    import webapp2

..'Go to Definition' for `logging` takes me to correct location:

    C:\dev\python\lib\logging

but it doesn't work on `webapp2`...

**Comment by DonJayamanne** [comment]
Hi, I believe I have identified the issue. Thanks for the sample code. Please  give me a day or two and I will get back with an update on the status.

**Comment by DonJayamanne** [comment]
Hi, the new version should fix this issue.
You can now add custom paths into the settings (user/workspace) file as follows (FYI as this is an array, you can include multiple paths):
"python.autoComplete.extraPaths": ["c:\\dev\\gcloud\\google-cloud-sdk\\platform\\google_appengine"]

Please test this and let me know how it goes.
I have tested it with the Google App Engine on both windows 8 64 bit and a Mac.

**Comment by sasxa** [comment]
I've managed to make it work:
```
  "python.autoComplete.extraPaths": [
    "c:\\dev\\gcloud\\google-cloud-sdk\\platform\\google_appengine\\lib\\webapp2-2.5.2",
    "c:\\dev\\gcloud\\google-cloud-sdk\\platform\\google_appengine\\lib\\endpoints-1.0\\endpoints",
    // "c:\\dev\\gcloud\\google-cloud-sdk\\platform\\google_appengine\\lib",
    "c:\\dev\\gcloud\\google-cloud-sdk\\lib"
  ]
```
Since `~\google_appengine\lib` isn't python module I had to add each folder separately, but that's OK (; `~\gcloud\google-cloud-sdk\lib` is a python module, and it has some common libraries cloud platform uses. Others that aren't there, I can add manually.

**Comment by sasxa** [comment]
I also noticed an issue with `pylint` - it gives `E0401: Unable to import 'webapp2'` error. Is it possible to use `extraPaths` for pylint too?

**Comment by Pcoric** [comment]
I am a little confused with where to add the code snippets posted above. I am having similar issues with my project. More specifically, where is the (user/workspace) file mentioned above.

**Comment by DonJayamanne** [comment]
Add the following seeing to settings.json. 
```json
"python.autoComplete.extraPaths": ["c:\dev\gcloud\google-cloud-sdk\platform\google_appengine"]
```
