### ISSUE TITLE
How to load pylint plugin?

### ISSUE THREAD

**Issue by Botong** [DonJayamanne/pythonVSCode#10]
Hi, thanks for fixing the last issue.

Another question I have found is that pylint does not recognize some class member or method in Django. I have found that there is a pylint plugin developed for Django that will fix the false alarm. 
This is the [article](https://blog.landscape.io/using-pylint-on-django-projects-with-pylint-django.html).

Could you add the command or a setting to enable this plugin? 
Thank you

**Comment by DonJayamanne** [comment]
Could you try configuring the path to pylint in the config as follows:
pylint --load-plugins pylint_django 

I haven't tried this, but technically this should work.
I will give it a go sometime  during the weekend, and if it doesn't work I'll add this into the list of things to do.

**Comment by Botong** [comment]
I did the setting override but it did not work.

// Path to Pylint, you can use a custom version of pylint by modifying this
setting to include the full path.
"python.linting.pylintPath": "pylint --load-plugins pylint_django",

Tested in terminal that the command is working. Could you take a look at
this once you have time? thank you very much

Thanks


2016-02-04 19:29 GMT+08:00 DonJayamanne <notifications@github.com>:

**Comment by Botong** [comment]
One more question to ask.
I am fairly new to Django and I am trying to add a custom auto-complete
module that can do the Django auto complete for me.
I saw you have a setting that can include custom auto-complete library so
do you know any good ones? Any suggestion? Which is the one that you used
for the general python auto-complete feature? Does it have an
extension-like library that supports Django?

Thank you so much, really appreciate your help.

2016-02-05 8:01 GMT+08:00 Botong Sui <suiyxfx@gmail.com>:

**Comment by Botong** [comment]
Humm, I just realized that I was actually under a virtual environment in
which I installed the pylint extension so the recommendation that you gave
actually works, so this is a false alarm, sorry for the inconvenience

2016-02-05 11:40 GMT+08:00 Botong Sui <suiyxfx@gmail.com>:

**Comment by DonJayamanne** [comment]
Great, i'll close the issue in that case. 
Thanks for confirming

**Comment by DonJayamanne** [comment]
HI Botong, did you manage to manage to get auto complete working for DJango. 
It works for me out of the box.
If it is installed in a virtual environment, try setting the path to the location of django package.
I am looking to add support for virtual environments as well.

**Comment by Botong** [comment]
Did you just add the path to Django to the extra path setting?

2016-02-07 14:13 GMT+08:00 DonJayamanne <notifications@github.com>:

**Comment by DonJayamanne** [comment]
I did absolutely, nothing. What is your environment like? Is it a visual env? Mac or pc? Python 27 or 35
