### ISSUE TITLE
Press ENTER after typed the word fully, will wrap the line.

### ISSUE THREAD

**Issue by Mohanson** [DonJayamanne/pythonVSCode#1002]
## Environment data
VS Code version: 1.12.2
Python Extension version: 0.6.4
Python Version: 3.6
OS and version: windows

I found something wrong when I upgraded to 0.6.4. When I key like "import nump[y]" and then key ENTER, 
The code autocompleted as the "import numpy". but when I key "import numpy" and then key ENTER, I got a line "import numpy" and an extra new line.

**Comment by DonJayamanne** [comment]
>but when I key "import numpy" and then key ENTER, I got a line "import numpy" and an extra new line.

Yes, that's correct, thats by design. You are not selecting anything at this stage, you have typed in what you need.
