### ISSUE TITLE
<DOCTYPE html> error

### ISSUE THREAD

**Issue by arun-siv** [DonJayamanne/pythonVSCode#1003]
## Environment data
VS Code version:  1.12.2
Python Extension version:  0.6.4
Python Version:   3.5
OS and version:    windows 10

## Actual behavior
I have to give the url for the jupyter notebook ( localserver)  to make it work
## Expected  behavior
It should automatically pick up the existing jupyter notebook or start a new one when running the sell
## Steps to reproduce:  
-  
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
"python.venvPath": "d:\\Tools\\ipython"
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
 I am getting the following error message in the terminal if I try to run the cell 
[W 21:45:13.674 NotebookApp] 404 GET /%20/api/kernelspecs?1496765713642 (127.0.0.1) 28.00ms referer=None

```

**Comment by imsedim** [comment]
Probably this is same as https://github.com/DonJayamanne/vscodeJupyter/issues/55
Should be fixed after the extension is updated.

**Comment by DonJayamanne** [comment]
Closing in favor of issue in DonJayamanne/vscodeJupyter#55
