### ISSUE TITLE
Running tests while discovery is in progress hangs test runner

### ISSUE THREAD

**Issue by szastupov** [DonJayamanne/pythonVSCode#1004]
## Environment data
VS Code version:  1.12.2
Python Extension version:  0.6.4
Python Version:   3.6
OS and version:    macOS 10.12.5

## Actual behavior
When I click on "Run Test" lens while (re)discovery is still in process, spinner turns to "Running tests" but nothing happens and it stays like that forever, without being able to kill or restart process.
Note that If I wait enough for discovery to complete, it works fine.

## Expected  behavior
Test should either run successfully or at least disallow running tests until discovery is complete.

## Steps to reproduce:  
-  Open a project with a lot of tests
-  Edit one, click save and while the spinner shows "Discovering tests" run any test via code lens

## Settings  

Your settings.json:   
```json
{
    "python.pythonPath": "${workspaceRoot}/venv/bin/python3",
    "python.unitTest.pyTestArgs": [
        "-vs",
        "--disable-pytest-warnings",
        "--reuse-db",
        "backend"
    ],
    "python.unitTest.pyTestEnabled": true
}
```   
## Logs
Output from ```Python``` output panel  
Console is clear.
Output from ```Console window``` (Help->Developer Tools menu)
Console is clear.

**Comment by porglezomp** [comment]
Ah, this is what's happening for me! Thanks for this report so I know what to avoid doing!

**Comment by DonJayamanne** [comment]
This has been fixed in the latest release. Apologies for the delay.
