### ISSUE TITLE
Console output not working when Python's time.sleep() is used within a loop

### ISSUE THREAD

**Issue by michelkaporin** [DonJayamanne/pythonVSCode#1005]
**From @amtopel in https://github.com/Microsoft/vscode/issues/28157#issue-234079917:**

- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.4|
|cpptools|ms-vscode|0.11.4|;

---

Steps to Reproduce:

1. Run the following Python script within VS Code:

```
import time
for x in range(10):
    print(time.time())
    time.sleep(5)
```

The time will not be printed to the output window.  But when the script is executed outside of VS Code, in a command line, the time will be properly printed at the beginning of each loop.

_Copied from original issue: https://github.com/Microsoft/vscode/issues/28157_

**Comment by cprogrammer1994** [comment]
what happens if you flush the stdout:

```
import sys

...

# your print goes here
sys.stdout.flush()
```

**Comment by amtopel** [comment]
Yep, that does solve the problem.

**Comment by cprogrammer1994** [comment]
Not sure what happens with the buffering when the native terminal window is used.

**Comment by underyx** [comment]
@amtopel you should be able to set `PYTHONUNBUFFERED=1` to disable output buffering, which would consist of adding `"env": {"PYTHONUNBUFFERED": "1"},` to the launch configuration.
