### ISSUE TITLE
cv2/cv has no member - Homebrew OpenCV wrappers

### ISSUE THREAD

**Issue by pushbuttons** [DonJayamanne/pythonVSCode#1007]
## Environment data
VS Code version:  1.13.0
Python Extension version:  0.6.4
Python Version:   2.7.13
OS and version:    OSX 10.12.5

## Notes

import cv2
print cv2
<module 'cv2' from '/usr/local/opt/opencv3/lib/python2.7/site-packages/cv2.so'>

## Actual behavior
 Module cv2 has no member  - import cv2
 Module cv has no member - import cv2 as cv

## Expected  behavior
intellisense

Your settings.json:   
{
    "python.pythonPath": "python",
    "python.linting.enabled": true,
    "python.linting.pylintEnabled": true,
    "python.linting.pep8Enabled": true,
    "python.autoComplete.extraPaths": [
        "/usr/local/lib/python2.7/site-packages",
        "/usr/local/Cellar/opencv3/HEAD-08c6ffa",
        "/usr/local/Cellar/opencv3/HEAD-08c6ffa/lib",
        "/usr/local/opt/opencv3/lib/python2.7/site-packages",
        "usr/local/opt/opencv3/lib/python2.7/site-packages/cv2.so"
    ],
    "python.linting.pylintArgs": [
        // "--extension-pkg-whitelist=cv2"
    ]
}

Mouse hover over module/function ie cv2.imread() displays function arguments and doc string

<img width="529" alt="screen shot 2017-06-09 at 10 08 12 pm" src="https://user-images.githubusercontent.com/10497206/26974763-37a8fc1e-4d60-11e7-9d26-e541fbfb6a47.png">

**Comment by DonJayamanne** [comment]
Looks like you have Opencv installed in a different python environment (```/usr/local/opt/opencv3/lib/python2.7```).
You'll need to point ```python.pythonPath``` to that particular environment.

**Comment by zhangcaocao** [comment]
https://github.com/AtomLinter/linter-pylint/issues/44
