### ISSUE TITLE
Debugger Not Pausing

### ISSUE THREAD

**Issue by adplax18** [DonJayamanne/pythonVSCode#1009]
## Environment data
VS Code version:  1.13
Python Extension version:  0.6.4
Python Version:   3.5
OS and version:    Linux Ubuntu Budgie 17.04

## Actual behavior
Debugging is not hitting breakpoints, and the stopOnEntry also is not functioning
## Expected  behavior
Execution would pause on F5 based on breakpoint and/or settings
## Steps to reproduce:  
-  place breakpoint in any file with settings as below
-  attempt to debug file (I was using F5)

## Settings  
Your launch.json (if dealing with debugger issues):  
```{
    "version": "0.2.0",
    "configurations": [

        {
                "name": "Python",
                "type": "python",
                "request": "launch",
                "stopOnEntry": true,
                "program": "${file}",
                "console": "none",
                "pythonPath": "${config:python.pythonPath}",
                "debugOptions": [
                    "WaitOnAbnormalExit",
                    "WaitOnNormalExit",
                    "RedirectOutput"
                ],
                "env":{"name" : "value"}
        }
    ]
}
```   
Your settings.json:   
```// Place your settings in this file to overwrite default and user settings.
{
    "python.pythonPath": "/home/alan/Documents/PythonProjects/DataScience/bin/python3.5",
    "python.autoComplete.extraPaths": [
        "/home/alan/Documents/PythonProjects/DataScience/lib/python3.5",
        "/home/alan/Documents/PythonProjects/DataScience/lib/python3.5/site-packages"
    ]
}
```   
## Logs
Output from ```Python``` output panel  
```
hello world
[50 68]
```
(was using the numpy test example)
Output from ```Console window``` (Help->Developer Tools menu)
-None

**Comment by ehinkle27** [comment]
I second this issue had the same problem. Also could not see variable values

**Comment by jorwoods** [comment]
Same issue as two people above.

**Comment by nerminkekic** [comment]
I am also have the same issue with debugger.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#128
