### ISSUE TITLE
Automatically add import statement

### ISSUE THREAD

**Issue by lfrodrigues** [DonJayamanne/pythonVSCode#101]
A very useful feature of some IDEs (eg: pycharm) is automatically adding the import for a symbol. 

If I have:
```
class ApplicationForm(ModelForm):
```
place the cursor in ModelForm and do ALT+ENTER (in Mac) I get a list where import the symbol from.

I could not find how to do this in vscode, it is possible?

**Comment by DonJayamanne** [comment]
Hi, unfortunately this isn't supported.

**Comment by lfrodrigues** [comment]
Hey,

What do you mean? That vscode does not have support for this feature? 
Can you point me to documentation where I can see how this could be implemented?

**Comment by lfrodrigues** [comment]
@DonJayamanne Apparently there is support in vscode for this, see: Microsoft/vscode#6524 

Since the infrastructure code is there it is only needed to find a way to search for symbols and add import. I'm not sure how much time I'll have to work on this but I think issue should be reopened so everyone is aware it is possible.
