### ISSUE TITLE
Change indentation size for Pylint

### ISSUE THREAD

**Issue by 1st** [DonJayamanne/pythonVSCode#1015]
Hello.

I set a setting `"editor.tabSize": 2,` but pythonVSCode doesn't recognize this settings. I see the error message from the `pylint` about wrong indentation, something like this:

```
[pylint] W0311:Bad indentation. Found 6 spaces, expected 12
```

Tried to find the proper option to pass to the `"python.linting.pylintArgs": []` but found nothing. Can you please let me know how to push `pylint` to check syntax based on the two-space indentation instead of four? Also it will be good to use the`editor.tabSize` setting in the `pythonVSCode` to pass through to the `pylint`.

Thanks.

**Comment by DonJayamanne** [comment]
Pylint is a separate python package. You will need to configure pylint using the relevant configuration files.

**Comment by 1st** [comment]
But it adds complexity. In each my project I need to add a file with config fot pylint and other libs? It's unreal if I have 10 projects.

In Sublime I change indentation size and it automatically pass this parameter to the pylint. I need nothing to configure. I know that it's extra work that you need to do to initialize the pylint with the correct parameters- but I think that it worth it.

PS. I don't know which parameter I need to pass to pylint as a custom argument to change the indentation size. Can you help with it?

**Comment by egabrum** [comment]
@1st I include a pylintrc file in the root of my workspace with these lines:
```
# String used as indentation unit. This is usually "    " (4 spaces) or "\t" (1
# tab).
indent-string='   '

# Number of spaces of indent required inside a hanging  or continued line.
indent-after-paren=3
```

**Comment by 1st** [comment]
I finally decided to execute command `pylint --long-help` to configure this option myself.

It's what I found there:
```
    --indent-string=<string>
                        String used as indentation unit. This is usually "
                        " (4 spaces) or "\t" (1 tab). [current: '    ']
```

@DonJayamanne can you please adopt this option to the current side of indentation that set by the configuration option `editor.tabSize`? It will be fine to pass this automatically to the `pylint` linter as a mandatory option.

Currently I solved my problem with 2 spaces in my project with this configuration option:

```
"python.linting.pylintArgs": [
    "--indent-string=\"  \""
]
```

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#130
