### ISSUE TITLE
Epytext docstring formats are not displayed nicely in docstring hover pop-up

### ISSUE THREAD

**Issue by egabrum** [DonJayamanne/pythonVSCode#1021]
## Environment data
VS Code version:  1.13.0
Python Extension version:  0.6.5
Python Version:   2.7.13
OS and version:    W7

## Actual behavior
When you hover over a function call in your code, you get a small pop-up showing you the docstring of that function. Function signature is formatted nicely, but elements such as parameter and/or return value names and types - as formatted according to [**Epytext** ](http://epydoc.sourceforge.net/index.html)- are shown in raw text form. The CR+LF are not displayed properly.

Similar to issue #821 

## Expected  behavior
Docstrings using the above format should be formatted nicely. At least, the CR+LF should be shown as expected.

Using different colors/formatting for the @tags would be nice too, but I guess that falls outside the scope of this extension.
## Steps to reproduce:  
-  Hover over the definition of this function. See how it displays the docstring and compare to other IDEs (e.g. Eclipse)
```
def x_intercept(m, b):
    """
    @summary:
      Return the x intercept of the line M{y=m*x+b}.  The X{x intercept}
      of a line is the point at which it crosses the x axis (M{y=0}).
    @param m: The slope of the line.
    @param b: The y intercept of the line.  The X{y intercept} of a
              line is the point at which it crosses the y axis (M{x=0}).
    @return:  the x intercept of the line M{y=m*x+b}.
    """
    return -b/m
```

VSCode:
![vscode](https://user-images.githubusercontent.com/1711744/27099558-2f9c0700-5030-11e7-858e-eaedbc433d42.png)
Eclipse:
![eclipse](https://user-images.githubusercontent.com/1711744/27099562-33f502ca-5030-11e7-9187-bbfb9ef64053.jpg)

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#132
