### ISSUE TITLE
Cannot scroll in the preview of declarations (Ctrl+hover)

### ISSUE THREAD

**Issue by egabrum** [DonJayamanne/pythonVSCode#1022]
## Environment data
VS Code version:  1.13.0
Python Extension version:  0.6.5
Python Version:   2.7.13
OS and version:    W7

## Actual behavior
As described [here](https://code.visualstudio.com/docs/editor/editingevolved#_go-to-definition),  if you press Ctrl and hover over a symbol, a preview of the declaration will appear.

However, even though the pop-up has a scroll bar, the user cannot scroll in it to read the bottom of the docstring if it is long enough. As soon as you move the mouse, the pop-up is gone.

## Expected  behavior
Not sure whether this is a VSCode issue or an extension issue... but I'd expect to be able to scroll on the pop-up preview for symbols with long docstrings.

Somewhat related to issue #1021

## Steps to reproduce:  
-  Hover over the definition of this function. Try to scroll down to see the hidden part of the docstring.
```
def x_intercept(m, b):
    """
    @summary:
      Return the x intercept of the line M{y=m*x+b}.  The X{x intercept}
      of a line is the point at which it crosses the x axis (M{y=0}).
    @param m: The slope of the line.
    @param b: The y intercept of the line.  The X{y intercept} of a
              line is the point at which it crosses the y axis (M{x=0}).
    @keyword p: A description of the keyword parameter p.
    @keyword a: A description of the keyword parameter a.
    @keyword b: A description of the keyword parameter b.
    @keyword c: A description of the keyword parameter c.
    @keyword d: A description of the keyword parameter d.
    @keyword e: A description of the keyword parameter e.
    @return:  the x intercept of the line M{y=m*x+b}.
    """
    return -b/m

a = x_intercept(m, b)
``` 

![2017-06-13_12-33-36](https://user-images.githubusercontent.com/1711744/27100931-a5086282-5034-11e7-9940-8be141365d9e.jpg)

**Comment by DonJayamanne** [comment]
Please reopen if the problem persists, as I believe this has been resolved in VS Code.

**Comment by egabrum** [comment]
@DonJayamanne  I'm on VSC 1.16.1 and I see to change. The issue persists.

**Comment by EnosisShawon** [comment]
@DonJayamanne Facing this issue in version 1.17.1
