### ISSUE TITLE
Enter debug mode from a "set_trace" style call in python script

### ISSUE THREAD

**Issue by mrvkino** [DonJayamanne/pythonVSCode#1024]
I have some python script used in a testing environment and I would like to enter the VSCode debug mode by calling a "set_trace" style command. This would allow me to easily test the code in the context (directory, environment, makefile variable values, etc..) it was called in.

This would have behaviour similar to the pdb.set_trace(). Do you know if there is a way of doing this now or could be added?

**Comment by DonJayamanne** [comment]
Apologies for never getting back to you on this. Unfortunately this isn't supported.
