### ISSUE TITLE
unittest framework no test discovered

### ISSUE THREAD

**Issue by tomaspaseka** [DonJayamanne/pythonVSCode#1028]
## Environment data
VS Code version:  
1.13.1
Python Extension version:  
0.6.5
Python Version:   
3.6.1
OS and version:    
Windows 10 1703
## Actual behavior
No tests are discovered, error message in output windows:
```
Traceback (most recent call last):
   File "<string>", line 3, in <module>
   File "C:\python3\lib\unittest\loader.py", line 338, in discover
     raise ImportError('Start directory is not importable: %r' % start_dir)
 ImportError: Start directory is not importable: '.\tests'
```

Project file structure:
```
+---lib
 \---tests
        some_test.py
        __init__.py 
```

some_test.py:
```
import unittest

class DummyTest(unittest.TestCase):
    def test_dummy(self):
        None
```

## Expected  behavior
Tests are discovered properly.

## Steps to reproduce:  
-  
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
`{
    "python.unitTest.unittestArgs": [
        "-v",
        "-s",
        ".\\tests",
        "-p",
        "*_test.py"
    ],
    "python.unitTest.unittestEnabled": true
}
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by ItsPavan** [comment]
@DonJayamanne Any update on the above bug,i encountered something similar but on python2.7
Please find the code below ,here i'm using htmltestrunner:
import pdb
import unittest
import HTMLTestRunner
from appium import webdriver


desired_caps = {}

desired_caps['platformName'] = 'Android'
desired_caps['platformVersion'] = '7.1.1'
desired_caps['deviceName'] = 'emulator-5554'
desired_caps['appPackage'] = 'shah.darsahan.myclient'
desired_caps['appActivity'] = 'shah.darsahan.myclient.LauncherActivity'
desired_caps['appWaitActivity'] = 'shah.darsahan.myclient.LoginActivity'
desired_caps['app'] = 'C:\\Users\\PKumar\\Downloads\\Mentorbot .apk'
pdb.set_trace()

class MentorBotTest(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)

    def login(self,):
        self.driver.find_element_by_id("shah.darsahan.myclient:id/name_txt").send_keys("Man")
        self.driver.find_element_by_id("shah.darsahan.myclient:id/num_txt").send_keys("8553207267")
        self.driver.find_element_by_id("shah.darsahan.myclient:id/email_txt").send_keys("pbh@planktonsolutions.com")
        self.driver.find_element_by_id("shah.darsahan.myclient:id/proceed_btn").click()
        self.driver.find_element_by_id("shah.darsahan.myclient:id/etOTP").send_keys("123456")
        self.driver.find_element_by_id("shah.darsahan.myclient:id/bSubmitOTP").click()
        self.driver.find_element_by_id("shah.darsahan.myclient:id/startTest").click()
        self.driver.find_element_by_id("com.android.packageinstaller:id/permission_allow_button").click()

    def tearDown(self):
        # close the browser window
        self.driver.quit()

if __name__ == '__main__':
    HTMLTestRunner.main()

output:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Unit Test Report</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>

<style type="text/css" media="screen">
body        { font-family: verdana, arial, helvetica, sans-serif; font-size: 80%; }
table       { font-size: 100%; }
pre         { }

/* -- heading ---------------------------------------------------------------------- */
h1 {
        font-size: 16pt;
        color: gray;
}
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}

.heading .attribute {
    margin-top: 1ex;
    margin-bottom: 0;
}

.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}

/* -- css div popup ------------------------------------------------------------------------ */
a.popup_link {
}

a.popup_link:hover {
    color: red;
}

.popup_window {
    display: none;
    position: relative;
    left: 0px;
    top: 0px;
    /*border: solid #627173 1px; */
    padding: 10px;
    background-color: #E6E6D6;
    font-family: "Lucida Console", "Courier New", Courier, monospace;
    text-align: left;
    font-size: 8pt;
    width: 500px;
}

}
/* -- report ------------------------------------------------------------------------ */
#show_detail_line {
    margin-top: 3ex;
    margin-bottom: 1ex;
}
#result_table {
    width: 80%;
    border-collapse: collapse;
    border: 1px solid #777;
}
#header_row {
    font-weight: bold;
    color: white;
    background-color: #777;
}
#result_table td {
    border: 1px solid #777;
    padding: 2px;
}
#total_row  { font-weight: bold; }
.passClass  { background-color: #6c6; }
.failClass  { background-color: #c60; }
.errorClass { background-color: #c00; }
.passCase   { color: #6c6; }
.failCase   { color: #c60; font-weight: bold; }
.errorCase  { color: #c00; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }


/* -- ending ---------------------------------------------------------------------- */
#ending {
}

</style>

</head>
<body>
<script language="javascript" type="text/javascript"></script>

<div class='heading'>
<h1>Unit Test Report</h1>
<p class='attribute'><strong>Start Time:</strong> 2017-10-25 14:57:34</p>
<p class='attribute'><strong>Duration:</strong> 0:00:00</p>
<p class='attribute'><strong>Status:</strong> none</p>

<p class='description'></p>
</div>



<p id='show_detail_line'>Show
<a href='javascript:showCase(0)'>Summary</a>
<a href='javascript:showCase(1)'>Failed</a>
<a href='javascript:showCase(2)'>All</a>
</p>
<table id='result_table'>
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row'>
    <td>Test Group/Test case</td>
    <td>Count</td>
    <td>Pass</td>
    <td>Fail</td>
    <td>Error</td>
    <td>View</td>
</tr>

<tr id='total_row'>
    <td>Total</td>
    <td>0</td>
    <td>0</td>
    <td>0</td>
    <td>0</td>
    <td>&nbsp;</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>

</body>
</html>

Time Elapsed: 0:00:00

**Comment by DonJayamanne** [comment]
@ItsPavan looks like your error is different. Please provide a complete code sample and please make it very simple so I can test this at my end. Haven't tested htmltest runner hence cannot say it is supported.

**Comment by DonJayamanne** [comment]
@tomaspaseka are you still experiencing this issue. I'd like to help you getting this sorted out.

**Comment by ItsPavan** [comment]
@DonJayamanne even without htmltestrunner it does'nt work.
Below is the complete code.

import pdb
import unittest,time,os
#import HTMLTestRunner
from appium import webdriver
from time import sleep

class MentorBotTest(unittest.TestCase):
    def setUp(self):
        desired_caps = {}
        desired_caps['platformName'] = 'Android'
        desired_caps['platformVersion'] = '7.1.1'
        desired_caps['deviceName'] = 'emulator-5554'
        desired_caps['appPackage'] = 'shah.darsahan.myclient'
        desired_caps['appActivity'] = 'shah.darsahan.myclient.LauncherActivity'
        desired_caps['appWaitActivity'] = 'shah.darsahan.myclient.LoginActivity'
        desired_caps['app'] = 'C:\\Users\\PKumar\\Downloads\\Mentorbot .apk'
        self.driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)

    def tearDown(self):
        # close the browser window
        self.driver.quit()

    def login(self):
        self.driver.implicitly_wait(30)
        time.sleep(5)
        self.driver.find_element_by_id("shah.darsahan.myclient:id/name_txt").send_keys("Man")
        self.driver.find_element_by_id("shah.darsahan.myclient:id/num_txt").send_keys("8553207267")
        self.driver.find_element_by_id("shah.darsahan.myclient:id/email_txt").send_keys("pbh@planktonsolutions.com")
        self.driver.find_element_by_id("shah.darsahan.myclient:id/proceed_btn").click()
        self.driver.find_element_by_id("shah.darsahan.myclient:id/etOTP").send_keys("123456")
        self.driver.find_element_by_id("shah.darsahan.myclient:id/bSubmitOTP").click()
        self.driver.find_element_by_id("shah.darsahan.myclient:id/startTest").click()
        self.driver.find_element_by_id("com.android.packageinstaller:id/permission_allow_button").click()


if __name__ == '__main__':
    suite = unittest.TestLoader().loadTestsFromTestCase(MentorBotTest)
    unittest.TextTestRunner(verbosity=2).run(suite)

Output:
C:\Python27>python MentorBot.py

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

**Comment by DonJayamanne** [comment]
Your file needs to be renamed to line up with the parameters you have configured. It is looking for files ending with _test.py. also try changing the path to './tests' instead of '.\\tests'.

**Comment by DonJayamanne** [comment]
Please create a separate issue when you have managed to get the tests working outside vscode but still failing on vscode
