### ISSUE TITLE
flake8 doesn't seem to run

### ISSUE THREAD

**Issue by rspeer** [DonJayamanne/pythonVSCode#103]
This plugin advertises that it can run linters such as `flake8` automatically. Is there something I need to do manually to make flake8 start running on a file? So far, nothing is happening, and there doesn't seem to be a way to manually trigger it or to see any errors that would prevent it from running.

I am running Python in a virtualenv. The virtualenv has flake8 installed, and flake8 works at the command line.

My User/settings.json contains:

```json
{
    "python.pythonPath": "/home/rspeer/.virtualenvs/lum3/bin/python3",
    "python.linting.enabled": true,
    "python.linting.flake8Enabled": true,
    "python.linting.pylintEnabled": false
}
```

**Comment by rspeer** [comment]
More details that may help: I'm using Ubuntu 14.04, and my virtualenv uses Python 3.5.0.

**Comment by rspeer** [comment]
I installed python3-flake8 as a system-wide package, and it started working, but this means it's clearly not using the flake8 package that's installed in my virtualenv.

I assume the system version is checking for Python 3.4 syntax instead of Python 3.5, so this is still suboptimal.

If it were using my pythonPath, it could run `/home/rspeer/.virtualenvs/lum3/bin/python3 -m flake8` and get the correct version. The fact that I had to install it system-wide implies to me that it's just looking for a `flake8` command in some list of paths.

**Comment by DonJayamanne** [comment]
You need to configure the path to flake8 in the config.
(FYI - by default it looks for flake8 in your current system path).

```json
{
    "python.pythonPath": "/home/rspeer/.virtualenvs/lum3/bin/python3",
    "python.linting.enabled": true,
    "python.linting.flake8Path": "flake8"
    "python.linting.flake8Enabled": true,
    "python.linting.pylintEnabled": false
}
```
