### ISSUE TITLE
Does not show code completion for python3 cv2 library

### ISSUE THREAD

**Issue by nojvek** [DonJayamanne/pythonVSCode#1030]
## Environment data
VS Code version:  
Python Extension version:  0.6.5
Python Version:   python 3.6
OS and version:    Mac OSX

## Actual behavior
Always stuck at "Loading...". How do I fix this?

![image](https://user-images.githubusercontent.com/1018196/27256433-62498fd8-5369-11e7-9e60-12127314c57b.png)

## Expected  behavior
Excellent code completion for opencv2

## Steps to reproduce:  
-  Install python3
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
    "python.pythonPath": "/usr/local/bin/python3",
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
@nojvek  apologies for the delay in getting back to you. I have tested this and can confirm that it works as expected. Please reopen the issue if the problem persists.
Oh yes, you'll probably need to wait around 1-2 seconds for the intellisense to show up. It was quite slow on my machine. Must have to do with the number of entries listed (1730 members listed)

**Comment by nojvek** [comment]
Yeah it seems the newer python extension magically made it worked. 

Let me know if there is a place I can donate for making this wonderful extension. I use it every single day
