### ISSUE TITLE
Docstrings don't render doctest examples correctly

### ISSUE THREAD

**Issue by porglezomp** [DonJayamanne/pythonVSCode#1036]
## Environment data
VS Code version:  1.13.1
Python Extension version:  0.6.5
Python Version:   2.7.13
OS and version:    Windows 7

## Actual behavior

A docstring like
```python
"""
Some text

>>> example_code
"""
```
it renders as:

Some text

>>> example_code

## Expected  behavior
It should render as:

Some text
```python
>>> example_code
```

## Steps to reproduce:  
- Write a function definition with a docstring containing a doctest block

**Comment by DonJayamanne** [comment]
Fixed in latest release
