### ISSUE TITLE
About Autocomplete/Intellisense

### ISSUE THREAD

**Issue by Tsumaranai** [DonJayamanne/pythonVSCode#1038]
## Environment data
VS Code version:  1.131
Python Extension version:  0.6.5
Python Version:   3.6
OS and version:    win7

## Actual behavior
fp = open(filepath, 'r')
fp.  when I type '.'  extension can list the fp's attributes like redlines and so on;
but
mymd5 = hashlib.md5()
mymd5. when I type '.' extension cannot list mymd5's  attributes like update, hexdigest etc.
## Expected  behavior

when typing '.' , extension can list attributes of value to choose
## Steps to reproduce:  
-  
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
Apologies for the delay in getting back to you on this issue.
Unfortunately I'm using a 3rd party package to provide the intellisense capabilities, and it doesn't seem to work on that package. Please report it there.
Here's the link to the repo [Python Jedi](https://github.com/davidhalter/jedi)

**Comment by Tsumaranai** [comment]
OK, I will report this issue to them. Thanks for your reply.
