### ISSUE TITLE
VS code  remote debug connect fail.

### ISSUE THREAD

**Issue by AwayQuEM** [DonJayamanne/pythonVSCode#1039]
## Environment data
VS Code version:  1.13.1 on Mac
Python Extension version:  0.6.5 on mac
Python Version:   3.5.2
OS and version:  OS X 10.12.5  
ptvsd version:3.0.0 on Mac

## Actual behavior
I still got `'Debug adapter process has terminated unexpectedly'` with ptvsd==3.0.0

## Steps to reproduce:  

* run test.py
* then run debug in vscode

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
{
    "version": "0.2.0",
    "configurations": [
         {
            "name": "Attach (Remote Debug)",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "secret": "secet",
            "port": 8010,
            "host": "localhost",
            "remoteRoot": "${workspaceRoot}"
        }
    ]
}
```   
Your settings.json:   
```json
{
    "python.pythonPath": "/Users/away/wanjia/test_remote_debug/venv/bin/python",
    "python.autoComplete.extraPaths": [
        "/Users/away/wanjia/test_remote_debug/venv/lib/python3.5/site-packages"
    ],
    "python.linting.enabled": false
}
```   
## Logs
Output from ```Console window``` (Help->Developer Tools menu)
```

messageService.ts:125 Debug adapter process has terminated unexpectedly
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
g.onServerExit @ rawDebugSession.ts:517
(anonymous) @ rawDebugSession.ts:431
emitTwo @ events.js:111
emit @ events.js:191
__dirname.ChildProcess._handle.onexit @ internal/child_process.js:215

```

## Code
```python
import ptvsd

address = ('0.0.0.0', 8010)
ptvsd.enable_attach('secret', address)
ptvsd.wait_for_attach()
print('connected')

```

**Comment by papaiatis** [comment]
Same problem here.

**Comment by joenot443** [comment]
Have had the same issue for several weeks now, would really like to see a fix.

**Comment by DonJayamanne** [comment]
Please could each of you confirm that you have PTVSD version 3.0.0 installed and not the latest version of PTVSD.

**Comment by papaiatis** [comment]
I had 3.1.0 installed. Downgraded, but did not help. Still getting the "Debug adapter process has terminated unexpectedly" message.
Note that I have a REST API to run with `gunicorn`, that I'd like to debug with this.

**Comment by asierralozano** [comment]
Same issue here. Using PTVSD 3.0.0 too

**Comment by commagere** [comment]
I'm seeing this exact issue as well - even with the "hello_world" test app.
This is using latest versions of each component (with the exception of ptvsd v3.0.0)

VS Code version: 1.14.2 
Python Extension version: 0.6.9 
Python Version: 2.7.10
OS and version: OS X 10.12.6
ptvsd version:3.0.0

**Comment by marcosfede** [comment]
Same here, using ptvsd 3.0.0. Devtools shows `TypeError: Cannot read property 'Threads' of undefined`

**Comment by Petezah** [comment]
Same.  ptvsd 3.0.0 also.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#133
