### ISSUE TITLE
High CPU Usage and spamming processes related to the extension

### ISSUE THREAD

**Issue by kwiesmueller** [DonJayamanne/pythonVSCode#1044]
## Environment data
VS Code version:  1.13.1
Python Extension version: 0.6.5
Python Version:  2.7, 3.5
OS and version:   macOS Sierra

## Actual behavior
After some time of idling with a vscode window having a python project open there were strange processes running crazy.
Those were:
```
bash /usr/local/opt/pyenv/libexec/pyenv-exec python completion.py preview
bash /usr/local/opt/pyenv/libexec/pyenv-exec python -c import sys;print(sys.executable)
bash /usr/local/opt/pyenv/libexec/pyenv-exec python
```
These processes were spamming and stopping and starting while using about 50% CPU Power over all cores... This resulted in a barely usable mac.
Killing vscode did not help in any way, closing all apps neither. I am not using bash but zsh and fish so manual starting was not the case.
 
## Expected  behavior
Everyhting else, but at least I would expect the processes to stop when closing vscode

## Settings  
Your settings.json:   
```json
// Place your settings in this file to overwrite the default settings
{
    "terminal.integrated.fontFamily": "Meslo LG M DZ for Powerline",
    "terminal.external.osxExec": "iTerm2.app",
    "git.confirmSync": false,
    "vsicons.dontShowNewVersionMessage": true,
    "workbench.iconTheme": "vs-seti",
    "sync.gist": "xxx",
    "sync.lastUpload": "2017-03-08T21:06:35.553Z",
    "sync.autoDownload": false,
    "sync.autoUpload": false,
    "sync.lastDownload": "",
    "sync.forceDownload": false,
    "sync.anonymousGist": false,
    "todohighlight.keywords": [
        {
            "text": "BUG:",
            "color": "#000",
            "backgroundColor": "#DD2C00",
            "overviewRulerColor": "#DD2C00"
        },
        {
            "text": "WARN:",
            "color": "#000",
            "backgroundColor": "#ffad4f",
            "overviewRulerColor": "#DD2C00"
        },
        "REVIEW:",
        {
            "text": "NOTE:",
            "color": "#000",
            "backgroundColor": "white",
            "overviewRulerColor": "grey"
        },
        {
            "text": "TODO:",
            "color": "#000",
            "backgroundColor": "#0091EA"
        }
    ],
    "todohighlight.defaultStyle": {
        "color": "#000",
        "backgroundColor": "#0091EA"
    },
    "terminal.integrated.shell.osx": "/usr/local/bin/zsh",
    "workbench.activityBar.visible": false,
    "files.associations": {
        "*.html": "html"
    },
    "window.zoomLevel": 0,
    "sync.host": "",
    "sync.pathPrefix": "",
    "python.venvPath": "~/.pyenv",
    "vsicons.projectDetection.autoReload": true,
    "window.nativeTabs": false,
    "go.gopath": "/Users/xxx/go",
    "debug.openExplorerOnEnd": true,
    "extensions.ignoreRecommendations": false,
    "editor.minimap.enabled": false,
    "go.liveErrors": {
        "enabled": true,
        "delay": 500
    }
}
```   
## Logs
Output from ```Python``` output panel  
```
none
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
none
```

**Comment by DonJayamanne** [comment]
The only long running prices would be the one running the Jedi library, others shut down almost immediately.  Will look into this once again.

**Comment by DonJayamanne** [comment]
Is this still an issue, please reopen if it is

**Comment by mmaroti** [comment]
This is still an issue for me on all recent version of VSCode and phytonVSCode on ubuntu 16.04 and 17.04. I can almost reliably trigger this when editing code containing GNURadio. I could not find any way to control or disable intellisense or whatever feature is triggering this. Indeed, I suspect that jedi is causing the problem, the .cache/jedi directory is 6.2 GB. The solution for me would be to have an option to disable jedi alltogether from pythonVSCode.

**Comment by DonJayamanne** [comment]
Please report new issues on the Microsoft fork, we'll look into them in there. https://github.com/Microsoft/vscode-python
