### ISSUE TITLE
Various built-in vscode functions not working

### ISSUE THREAD

**Issue by agdfoster** [DonJayamanne/pythonVSCode#1045]
Anyone else having this issue? It's not just the shortcuts, if I activate the command from the cmd p palette it also does nothing or throws an error. I've also checked that they are still bound to the right keys and tried turning my macro tool off, but like I said they also don't work activating them from the palette.
Specifically:
cmd click (go to definition) does nothing find all references - nothing run python file in terminal - "command 'python.execInTerminal' not found"
I think there are others but I forget, the definition finding ones are the biggest hit as I use those dozens of times a day.
I've tried searching all over the internet!
Thanks
Alex
	•	VSCode Version: Code 1.13.1 (379d2ef, 2017-06-14T18:13:05.928Z)
	•	OS Version: Darwin x64 16.6.0
	•	Extensions:
Extension
Author
Version
beautify
HookyQR
1.1.1
regex
chrmarti
0.1.0
python-snippets
cstrap
0.0.5
vscode-eslint
dbaeumer
1.2.11
githistory
donjayamanne
0.2.0
python
donjayamanne
0.6.5
file-icons
file-icons
1.0.3
Python-autopep8
himanoa
1.0.2
vscode-JS-CSS-HTML-formatter
lonefy
0.2.3
MagicPython
magicstack
1.0.10
prettify-json
mohsen1
0.0.3
unittest-switcher
takas-ho
0.1.3
python
tht13
0.2.3
python-extended-snippets
tushortz
0.0.1
code-navigation
vikas
0.2.0
prettify-selected-json
vthiery
1.0.2

Steps to Reproduce:
	1.

**Comment by hobbsd** [comment]
I'm experiencing the same issues on Windows 7 and 10 with VSCode 1.13.1. I wasn't sure if the problem was with VSCode or the Python extension.

**Comment by agdfoster** [comment]
Still have this problem,

the biggest issue is not being able to get click-through to source and not getting the tool tips, without it I'm even considering switching IDE as it's so valuable :(

Any help would be greatly appreciated!

Alex

**Comment by agdfoster** [comment]
It's with the python extension for me as all functionality works for other languages.

**Comment by agdfoster** [comment]
I have also tried re-installing vscode

**Comment by DonJayamanne** [comment]
You seem to have a tonne of extensions installed, Please could you uninstall all of them, and try to install just the Python (my) extension and give it a go.  
Oh yes, as soon as its installed, first open a Python file (don't try launching a command, first open a python file)

**Comment by hobbsd** [comment]
This problem appears to be fixed in the latest version (0.6.7). Thanks!
