### ISSUE TITLE
How to install it in VSCode?

### ISSUE THREAD

**Issue by bansalvks** [DonJayamanne/pythonVSCode#105]
I am very new to vscode
Please guide noobs like me to how to install it and configure it step by step

Many thanks and pardon me for my ignorance.

**Comment by jddde** [comment]
Launch VS Code Quick Open (Ctrl+P), paste the following command, and type enter.
ext install python

**Comment by johndpope-karhoo** [comment]
this should be on readme.

**Comment by DonJayamanne** [comment]
This is documented on the marketplace page https://marketplace.visualstudio.com/items?itemName=donjayamanne.python
