### ISSUE TITLE
how to get the git module?

### ISSUE THREAD

**Issue by stgran** [DonJayamanne/pythonVSCode#1053]
## When I try to import git on VSC through Python, nothing comes up
Is there a way to download the git module as an extension or some other way so I can import the git module?

**Comment by brettcannon** [comment]
What do you mean by "git module"? There's not git module on PyPI. If you're looking for a module to access a git repository then do a search for something like [python git] you will find projects like [GitPython](https://github.com/gitpython-developers/GitPython).
