### ISSUE TITLE
Feature Request: Symbol to know you are overwriting parent class method

### ISSUE THREAD

**Issue by levin-ilya** [DonJayamanne/pythonVSCode#1058]
## Environment data
VS Code version:  
Python Extension version:  
Python Version:   
OS and version:    

## Actual behavior
if you type 'def setUp' there is no symbol to let you know you've overwritten a method
## Steps to reproduce:  
-  
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
Such a feature will have to be implemented in the python Jedi library as that's whats being used for the l analysis of the python code . Please propose it in the repo for that project.
