### ISSUE TITLE
Linting errors in imports

### ISSUE THREAD

**Issue by 1st** [DonJayamanne/pythonVSCode#1059]
*I use latest version of VS Code and Python VS Code plugin.*

I found an issue: **Module is imported, but linter thinks that it can't be imported**.

How to reproduce:
* I set the path to the virtual env's `python`, like this `"python.pythonPath": "~/.virtualenvs/myproject/bin/python"`
* in virtual env I have installed `django` via pip
* opened my Django project and see an error in the line `from django.views.generic.edit import FormView`
* when I hover on that line over the `FormView` word - I see that linter tells that it's impossible to import smth, but VS Code shows definition of the imported module/class/etc

```
[pylint] E0401:Unable to import 'django.views.generic.edit'
class FormView(**kwargs)
A view for displaying a form, and rendering a template response.
```

**Comment by 1st** [comment]
As all in this World - it's a solution comes to my brain. **Found solution!**

I set the path to `pylint` for my local (workspace) settings and it becomes work as expected.

```json
{
    "python.linting.pylintPath": "~/.virtualenvs/myproject/bin/pylint"
}
```

@DonJayamanne please loo on my #1060 and if you will apply my idea, then you can auto-fill all paths from the virtual env automatically, including `python`, `pylint`, `pep8` and others. If you will need my help - I'm always ready to help you.

Best,
Anton

**Comment by DonJayamanne** [comment]
Related to https://github.com/DonJayamanne/pythonVSCode/issues/923
