### ISSUE TITLE
How to use virtual envs?

### ISSUE THREAD

**Issue by 1st** [DonJayamanne/pythonVSCode#1060]
I see that it's a settings variable named `"python.venvPath"` and I set it to `"~/.virtualenvs"` (where I have few virtual envs).

Question: **How to tell VS Code to use the proper virtual env?**

I see that it should be something like this:
* set `"python.venvPath": "~/.virtualenvs"` in a global settings
* set `"python.venvName": "myproject"` in my workspace (local) settings
* the Python VS Code plugin will fill the python path in the next way: `"python.pythonPath": "~/.virtualenvs/myproject/bin/python"` based on two settings from above.

Also I found that it's possible to create an `.env` file inside the workspace directory. I created one, pushed the `myproject` in it - but nothing happens. Maybe I misunderstood this property.

Need your help.
Thanks.
Anton

**Comment by 1st** [comment]
@DonJayamanne please look on the #1059 description to find what problem I have faced and how implementation of the mentioned improvement can solve problems with usage of libs from the virtual env.

**Comment by LordAmit** [comment]
Hi,
I was just going through issues and found this one.
I have set the `"python.venvPath"` to "~/.virtualenvs" like you.
You can use it like this:
press F1 / ctrl+shift+P, and then type "workspace interpreter".
There, you should be  able to see list of available interpreters from the virtual environments you created.

**Comment by DonJayamanne** [comment]
@LordAmit thanks

**Comment by appleyuchi** [comment]
but this operation don't take effect under ubuntu

**Comment by appleyuchi** [comment]
@DonJayamanne

**Comment by vladox** [comment]
@LordAmit  "workspace interpreter" doesn't seems to be present anymore (VS Code 1.18.1), only Python: Select interpreter.
