### ISSUE TITLE
How to override package.json configuration

### ISSUE THREAD

**Issue by evbo** [DonJayamanne/pythonVSCode#1061]
Is there a way to override settings in?:
https://github.com/DonJayamanne/pythonVSCode/blob/master/package.json

Whenever I make changes to package.json, the next time vscode updates this extension they get lost. Is it possible to define user settings overrides that do not involve manual changes directly on package.json?

The change I manaully add to package.json is quite small but drastically improve my workflow as I rely heavily on the editor context menu for running tests:

```
"menus": {
			"editor/context": [
				{
					"when": "resourceLangId == python",
					"command": "python.runCurrentTestFile",
					"group": "Python"
				},
...
```

That config change simply allows me to run all tests in a file that I click on.

**Comment by DonJayamanne** [comment]
Nope, unfortunately these are part of the extension. I've added this into the extension and it will be available in the next release.
