### ISSUE TITLE
Debug: Run in External Terminal Returns Error Message on Exit

### ISSUE THREAD

**Issue by jakinov** [DonJayamanne/pythonVSCode#1067]
## Environment data
VS Code version:  1.13.1
Python Extension version:  0.6.7
Python Version:   2.7.10
OS and version:  Win 10 Creators Update

## Actual behavior
Close external terminal/console after program run (either click Stop on VS Code, X on window or any key on "press any key to continue". Get error message "Debug adapter process has terminated unexpectedly". Reproducible on two different Win10 machines.

![image](http://i.imgur.com/pvNZIeM.gif)

## Expected  behavior
No error message.

## Steps to reproduce:  
-  Default launch config. Run any app in debugger in external terminal.
-  Close terminal

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
default config
```   
Your settings.json:   
```json
default settings
```   
## Logs
Output from ```Python``` output panel  
```
Nothing Relevant
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
Debug adapter process has terminated unexpectedly
e.doShow @ messageService.ts:125

```

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#136
