### ISSUE TITLE
Extension crashes immediately on VSCode startup

### ISSUE THREAD

**Issue by IDT-kcrook** [DonJayamanne/pythonVSCode#1071]
## Environment data
VS Code version:  1.13.1
Python Extension version:  0.6.7
Python Version:   3.6.1
OS and version: Windows 10 Enterprise v.1703 Build: 15063.413

## Actual behavior
Immediately on restart after install, Visual Studio shows "Error: Extension host terminated unexpectedly. Please reload the window to recover" On reload, the same exact thing occurs. I've tried installing it, updating, reinstalling on multiple versions of VS Studio with no luck.

## Expected  behavior
Don't crash? 👍 

## Steps to reproduce:  
-  Install extension
-  Restart
-  bingo

**Comment by DonJayamanne** [comment]
Do you get this error when installing other extensions?  
Can you go into developer tools and read the contents of the error console and provide that.

**Comment by IDT-kcrook** [comment]
I do not get this error with other extensions, and get the error even when it is the only extension enabled. 

`index.js:41 [uncaught exception]: Error: write EPIPE
onError @ index.js:41
index.js:44 Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at Socket._writeGeneric (net.js:715:26)
    at Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at Socket.Writable.write (_stream_writable.js:245:11)
    at Socket.write (net.js:661:40)
    at Immediate.<anonymous> (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:181332)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
onError @ index.js:44
events.js:160 Uncaught Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at Socket._writeGeneric (net.js:715:26)
    at Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at Socket.Writable.write (_stream_writable.js:245:11)
    at Socket.write (net.js:661:40)
    at Immediate.<anonymous> (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:181332)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
messageService.ts:125 Extension host terminated unexpectedly. Please reload the window to recover.
e.doShow @ messageService.ts:125
extensionHost.ts:332 Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
d.onExit @ extensionHost.ts:332`

**Comment by fysp11** [comment]
I was facing this error and I fixed by removing a worng Python Path from Windows PATH enviroments.

**Comment by DonJayamanne** [comment]
@IDT-kcrook are you still experiencing this issue? Please reopen if you are.

**Comment by IDT-kcrook** [comment]
It doesn't appear as though I can reopen this issue because a repository collaborator closed it. Yes, I am still experiencing this problem.

When I saw @fysp11 's comment I went through and did the following:

> checked my env variables and made sure they were correct
> went into the configuration for the Python extension in VS Code's settings and checked them
> fiddled with giving python.path different absolute paths to Python36 and Python27
> even tried giving it the name of the environment variable name right of the console for kicks
> Disabled linting
> Reloaded, Disabled, Reloaded, Enabled the extension and VS Code multiple times

I confirmed this with a co-worker: he has a Macbook and experiences the same exact problem. This is not a windows-only issue. 😄 

For a workaround now I've been using Visual Studio 2015 with the python extension. On an unrelated note, Visual Studio 2015 is the only IDE that I've been able to get to actually **stop** and display variable values when I put in breakpoints. VS Code and PyCharm don't seem to stop at breakpoints (but I may just be inexperienced with other IDEs). 😀

**Comment by yatahaze** [comment]
Same problem here.

**Comment by DonJayamanne** [comment]
Hi everyone, this repo is no longer maintained. Please file all your issues on the corresponding Microsoft repo (you can find the link in the marketplace).
We now have more than just one (me) developer working on this extension. Hopefully we can help you get over your issues.
