### ISSUE TITLE
OSError: Too Many Open Files

### ISSUE THREAD

**Issue by gregflynn** [DonJayamanne/pythonVSCode#1072]
## Environment data
VS Code version:  1.13.1
Python Extension version:  0.6.7
Python Version:   3.6.1
OS and version:    Arch Linux

I know this screams a system issue, but I'm not seeing this issue in other applications and shutting down my docker containers to reduce the number of open file descriptors didn't have any effect. Suggestions are welcome to help debug the issue.

## Actual behavior
Autocomplete shows `Loading...` when autocompleting python code

## Expected  behavior
Autocomplete/intellisense dropdown

## Steps to reproduce:  
-  Seems to be after a few hours writing python, this pops up on my laptop
-  pressing `.` or `ctrl+space` in a python file produces the traceback again
- Restarting VS Code restores expected behavior for some time

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
[Extension Host] Error (stderr) Traceback (most recent call last):
  File "completion.py", line 631, in watch
    with RedirectStdout():
  File "completion.py", line 19, in __enter__
    oldstdout_fno = self.oldstdout_fno = os.dup(sys.stdout.fileno())
OSError: [Errno 24] Too many open files
```

**Comment by gregflynn** [comment]
`ctrl+shift+P` => `Reload Window` resolves the issue temporarily like restarting VS Code

**Comment by gregflynn** [comment]
updated to `4.11.9-1-ARCH #1` kernel, still happens, reload window workaround still works.

Have also reproduced this after awhile on 2 computers now

**Comment by dannystaple** [comment]
Closing the referenced issue as a duplicate - this looks like the same error to me.  It's on Windows 8, Python 2.7 - so the OS is not the common factor.

Greg what extensions do you have present in your loadout? I thought disabling the git extensions helped - but that could just have been the restart.

**Comment by dannystaple** [comment]
Also noteworthy - you mentioned docker containers, I do have Vagrant VM's around.

**Comment by gregflynn** [comment]
@dannystaple I've had it happen with docker containers down the whole time, and I don't get the error from other processes. I'm running python 3.6.1 everywhere, so the issue doesn't relate to OS or python version either.

I've started poking around at the extension code to see if I can have an `ah-ha!` moment, but I'm not familiar with the specifics here.

**Comment by gregflynn** [comment]
Sorry @dannystaple I completely glossed over your suggestion that it could be another extension causing the issue, though I think that's unlikely but here's my list:
```
Atom Keymap
Beautify
Docker
final-newline
git blame
git history
Jinja
pgsql
Python
python-snippets
settings-sync
vscode-icons
```

**Comment by dannystaple** [comment]
In that list - the ones I had in common, and disabled (on a whim I suppose) were git blame and git history.

**Comment by gregflynn** [comment]
I rarely use those two, so I'll give it a shot tomorrow, for science

**Comment by gregflynn** [comment]
@dannystaple Got around to testing this fully on the latest VS code 14.1 and still run into this error

**Comment by Crazy-Owl** [comment]
I, too, encounter this issue on Linux 64 bit with VS Code 1.14.1. Had to restart, thanks for the "reload" workaround. Maybe I can provide any info for debugging purposes?

**Comment by Halolegend94** [comment]
Is the title says, there are too many open files. I read the discussion and I didnt see this pointed out, so I will add the following.
A process can have a limited number of opened file descriptor. So, genuinely asking, it is really necessary for the application to have all the files open? Can't it open, read and then close?
I am not familiar with the programming language, otherwise I would have searched for a solution myself.

I hope this will be resolved.

**Comment by stestqa** [comment]
I'm seeing this multiple times a day. Also running Arch Linux, but without most of the extensions listed above. My VS Code is 1.14.2.

[Extension Host] stderr jediProxy
[Extension Host] Error (stderr) Traceback (most recent call last):
  File "completion.py", line 675, in watch
  File "completion.py", line 19, in __enter__
OSError: [Errno 24] Too many open files

$ ps aux | grep python
<username>     1735  0.0  0.1  76248 17364 ?        S    09:03   0:00 python completion.py preview
<username>     1736  1.1  1.4 304024 243076 ?       S    09:03   1:32 python completion.py preview

$ lsof -p 1736 | wc -l
1057

$ lsof -p 1736 
...
python  1736 <username>    0u  unix 0xffff8803a5be7000      0t0   25420 type=STREAM
etc.

(there are a lot of these!)

$ ulimit -n
1024

There's your problem. Something (jedi? vscode?) is opening a lot of streams and not closing them.

I'll try raising the ulimit as a workaround...

**Comment by DonJayamanne** [comment]
Will be fixed in https://github.com/DonJayamanne/pythonVSCode/pull/1118

**Comment by gregflynn** [comment]
Perfect, thanks @DonJayamanne and especially @Halolegend94 for the fix.

I'll close once I pull the update and just confirm.

**Comment by gregflynn** [comment]
Sorry for the delay on this, I just applied the patch locally, will close end of day if i don't run into the problem again.

**Comment by Jeyanthinath** [comment]
@DonJayamanne can you please relase a version ASAP, once it is tested.

Because I facing this issues twice a day and I need to restart by vscode to fix this.

**Comment by Halolegend94** [comment]
@Jeyanthinath you can add the line of code yourself on your local copy, as I did. Search the extensions folder, usually in ~/.vscode

**Comment by DonJayamanne** [comment]
Will release tonight, sorry guys. Give me around an hour

**Comment by Jeyanthinath** [comment]
@DonJayamanne :+1: 

@Halolegend94 , thanks for the heads up man

**Comment by DonJayamanne** [comment]
New version has been released
