### ISSUE TITLE
is plotly supposed to work?

### ISSUE THREAD

**Issue by Maoni0** [DonJayamanne/pythonVSCode#1073]
I am trying to use plotly in vscode/Jupyter extension and the charting doesn't seem to work at all. Would this be a new feature request? Thanks.

**Comment by minjeejang** [comment]
I have the same issue, with the following message: 

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/vscodeJupyter#76
