### ISSUE TITLE
.env file enviroment variables e.g. PYTHONPATH not loaded in unit test

### ISSUE THREAD

**Issue by pervlad** [DonJayamanne/pythonVSCode#1074]
## Environment data
VS Code version:  
Version 1.13.1
Python Extension version: 
Version 0.6.7 (02 July 2017) 
Python Version: 
3.6
OS and version:    
Ubuntu 14.04 

## Actual behavior
When running unittest (with or without debuging) adittional environment variable PYTHONPATH from .env file is not present in sys.paths variable thus
import from packages and modules on that path can not be performed resulting in import error exception.
 
## Expected  behavior
Expecting same behavior as when running python debug or run: environment variables from .env file to be loaded e.g. additional PYTHONPATH to be present in sys.path variable
## Steps to reproduce:  
- create .env file put PYTHONPATH pointing to some dir containig modules e.g. 
   PYTHONPATH  = ../mymodules  or  PYTHONPATH  = ../
-  import ../mymodules/mymodule.py in unittest

## Settings  
.env file 
```bash
  PYTHONPATH  = ../
```
Your launch.json (if dealing with debugger issues):  
```json
...
       {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
...
```   
Your settings.json:   
```json
{
      "editor.fontSize": 16,   
      "python.pythonPath": "${workspaceRoot}/../env/bin/python", 
      "python.autoComplete.extraPaths": ["{workspaceRoot}/../mymodules"],
      "python.venvPath": "${workspaceRoot}",
      "python.unitTest.unittestEnabled": true,
      "python.unitTest.unittestArgs": [
            "-v",
            "-s",
            "${workspaceRoot}/tests",
            "-p",
            "test*.py"
      ]
}
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by pervlad** [comment]
Actually .env variables are not loaded when lunching standard python launch configuration without debugging too.

**Comment by tdbear** [comment]
Still not fixed.
