### ISSUE TITLE
Function declaration is displayed in the docstring if the parameters start on a new line

### ISSUE THREAD

**Issue by porglezomp** [DonJayamanne/pythonVSCode#1075]
## Environment data
VS Code version:  1.13.1
Python Extension version:  0.6.7
Python Version:   2.7.13
OS and version:    Windows 7

## Actual behavior

If a function declaration is long enough, and you decide to break lines by putting the newline immediately after the parenthesis, then the text of the function declaration appears inside the docstring help in addition to displaying normally above it.
![bad](https://user-images.githubusercontent.com/1690225/27974302-6ad17720-632b-11e7-82ae-679046d509c1.png)

## Expected  behavior

It should display the same as a single-line declaration, or one that has a line-break after a later parameter:
![good](https://user-images.githubusercontent.com/1690225/27974348-ac2fb560-632b-11e7-9525-9db9d2f65450.png)

## Steps to reproduce:  
-  Write a function and put a line-break after the open parenthesis in the declaration

For example:

```python
def some_function_with_a_very_long_name(
        put, params, on, a, new, line):
    """
    And have a docstring here.
    """
    pass
```

**Comment by DonJayamanne** [comment]
Please reopen if the problem persists

**Comment by porglezomp** [comment]
Looks good to me now, thanks!
