### ISSUE TITLE
python extension auto create .vscode folder when I open my project, how can I forbid this

### ISSUE THREAD

**Issue by BrillanceZhang** [DonJayamanne/pythonVSCode#1076]
## Environment data
VS Code version:  1.13.1
Python Extension version:  0.6.7
Python Version:   2.7.13
OS and version:    windows7

## Steps to reproduce:  
-  
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/DonJayamanne/pythonVSCode/issues/1096
