### ISSUE TITLE
Intellisense gets stuck in Loading

### ISSUE THREAD

**Issue by dannystaple** [DonJayamanne/pythonVSCode#1078]
## Environment data
VS Code version:  Version 1.13.1
Python Extension version:  0.6.7
Python Version:   2.7
OS and version:    Windows 8

## Actual behavior

If I have just opened a project in VScode, Intellisense/autocompletion will be working fine, perhaps a little while to catch up. 

As I carry on working, the function stops working, will no longer automatically suggest stuff, and if summoned using the keyboard shortcut will be stuck loading.

Related features - hover docs, ctrl-click through to code, also do not work. closing and reopening vscode seems to fix it.

Disabling some of the other extensions (Git history, git blame) also seems to fix it, but that may just be that it needs time to reach this state again.

## Expected  behavior

Autocomplete/sense just continues working.

## Steps to reproduce:  
-  Open VSCode with a project
-  Work for a while in it.
- Attempt to use intellisense features.

## Settings  

Your settings.json (project):   
```json
{
    "python.autoComplete.extraPaths": [
        "./Common",
        "./FakeStormApi"
    ],
    "gitlens.codeLens.enabled": false,
    "python.pythonPath": "c:/python27/python.exe"
}
```   

User settings file 
```json
{
    "git.confirmSync": false,
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "**/*.pyc": true,
        "**/.idea": true,
        "**/.vagrant": true,
        "**/*.bak": true,
        "tags": true
    }
,
"python.terminal.executeInFileDir": true,
"python.linting.pep8Args": [
    "--ignore=E501"
],
"window.zoomLevel": 0,
"files.eol": "\n",
"window.menuBarVisibility": "default",
"gitlens.codeLens.recentChange.enabled":false,
"gitlens.codeLens.authors.enabled": false,
"terminal.integrated.scrollback": 5000,
"spellchecker.language": "en_GB-ise",
"python.workspaceSymbols.tagFilePath": "${workspaceRoot}/tags",
"python.linting.pep8Enabled": true,
"python.linting.flake8Enabled": false,
"python.linting.pep8CategorySeverity.E": "Hint",
"python.linting.pep8CategorySeverity.W": "Hint"
}
```

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
[Extension Host] ---------------------------
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293[Extension Host] stderr jediProxy
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293[Extension Host] Error (stderr) Traceback (most recent call last):
  File "completion.py", line 631, in watch
    with RedirectStdout():
  File "completion.py", line 15, in __init__
    self._new_stdout = new_stdout or open(os.devnull, 'w')
IOError: [Errno 24] Too many open files: 'nul'
```

**Comment by gregflynn** [comment]
Looks like a dupe of #1072

guess it's not just me 😄

**Comment by dannystaple** [comment]
Closing the dupe.
