### ISSUE TITLE
Decorator @classmethod doesn't allow to get correct docstring

### ISSUE THREAD

**Issue by 1st** [DonJayamanne/pythonVSCode#1080]
I have a class that has a method that decorated by a `@classmethod` decorator. When I'm trying to get information about the method - it shows next:

```
def _method(*args, **kwargs)
```

I expect to see the documentation string instead of this unhelpful text.

## Example of code

```python
class X(object):
    @classmethod
    def aaa(cls):
        """Some doc string."""
        return "Something useful"

x = X.aaa()  # Navigate a mouse pointer over the "aaa" to see a c=doc string.
# Actually it's no docstring, but some unhelpful data from the decorator.
```

When the decorator is removed - it shows the correct helpful text.

```
def aaa(cls)
Some doc string.
```

Can you please improve it to produce helpful docstring messages for such case?

Thank you,
Anton

**Comment by DonJayamanne** [comment]
Please reopen if the problem persists

**Comment by mellertson** [comment]
I'm running into this exact same issue.  What was the resolution?
