### ISSUE TITLE
Rename Symbol Fails 50% of the Time

### ISSUE THREAD

**Issue by claytoncarney** [DonJayamanne/pythonVSCode#1081]
#### Screencast of Issue
[RenameSymbol.mp4](https://mega.nz/#!AtpiwQDK!409C2BOTTKrRmLWeky5L60TqpWze3JDozFCQm0e_Xg8)

## Environment data
VS Code version:  1.14.0
Python Extension version:  0.6.7
Python Version:   3.6
OS and version:    Windows 10 Home 64-bit

## Actual behavior
Every other time, Rename Symbol fails
## Expected  behavior
Should work every time (it did previously)
## Steps to reproduce:  
- test.py
```py
var_one = 1
var_two = var_one + 1
var_three = var_two + 1
```
- right-click on var_one
- select Rename Symbol
- enter varOne
- nothing happens
- right-click on var_one again
- select Rename Symbol
- enter varOne
- symbol is renamed

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
// Place your settings in this file to overwrite the default settings
{
    "workbench.editor.enablePreview": false,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false,
    "files.exclude": {
        "**/.git": true,
        "**/.gitignore": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "**/*.pyc": true,
        "**/*.sln": true,
        "**/*.pyproj": true
    }
,
"window.zoomLevel": 0,
"cssfmt.indent": 2,
"editor.wordWrap": "off",
"editor.rulers": [
    80,
    120
],
"html.format.wrapLineLength": 0,
"editor.minimap.enabled": false,
"eslint.options": {
    "configFile": "D:/Users/Clayton/Code/.eslint.json"
}
}
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
Sorry, rename failed to execute.
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
(anonymous) @ rename.ts:166
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_chainedError @ winjs.base.raw.js:1031
n @ winjs.base.raw.js:736
then @ winjs.base.raw.js:1436
enter @ winjs.base.raw.js:747
_run @ winjs.base.raw.js:1068
_setCompleteValue @ winjs.base.raw.js:1052
g @ winjs.base.raw.js:1170
enter @ winjs.base.raw.js:852
_run @ winjs.base.raw.js:1068
_completed @ winjs.base.raw.js:1036
then @ winjs.base.raw.js:1566
enter @ winjs.base.raw.js:747
_run @ winjs.base.raw.js:1068
_setCompleteValue @ winjs.base.raw.js:1052
g @ winjs.base.raw.js:1170
enter @ winjs.base.raw.js:852
_run @ winjs.base.raw.js:1068
_completed @ winjs.base.raw.js:1036
g @ winjs.base.raw.js:1170
enter @ winjs.base.raw.js:852
_run @ winjs.base.raw.js:1068
_completed @ winjs.base.raw.js:1036
(anonymous) @ async.ts:353
done @ winjs.base.raw.js:1524
g @ winjs.base.raw.js:1180
enter @ winjs.base.raw.js:852
_run @ winjs.base.raw.js:1068
_completed @ winjs.base.raw.js:1036
e.resolveOk @ ipcRemoteCom.ts:98
f @ ipcRemoteCom.ts:207
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```
this error appears in the console most, but not every time it fails

#### Notes
- issue manifested sometime in the last month
- have tried disabling all other extensions; problem persists
- sometimes receive warning in VS Code: 'no result'
- sometimes receive error in VS Code:  'sorry rename failed to execute'
- sometimes receive error in VS Code like 'files have changed in meantime'

**Comment by claytoncarney** [comment]
Also observe that when the rename fails, unsaved changes to the file are being save. Again, this was not happening previously.

**Comment by bendruitt** [comment]
This is issue has been around for at least 6 months for me, and is getting worse, not better (refactor fails more often than 50%). I have experienced the issue on up-to-date vscode clients on Mac and Windows.

**Comment by DonJayamanne** [comment]
Hi guys, sorry for not looking into this issue. I've been busy with other issues. This will change soon, please hang in there.

**Comment by peabnuts123** [comment]
I've +1'd this but to be honest i've actually noticed this is not strictly limited to working in Python or having this extension installed, so you might find the issue goes deeper than your extension.

**Comment by DonJayamanne** [comment]
Closing in favor of https://github.com/DonJayamanne/pythonVSCode/issues/824
