### ISSUE TITLE
No autocomplete/intellisense for new variables created in async functions

### ISSUE THREAD

**Issue by applearound** [DonJayamanne/pythonVSCode#1084]
## Environment data
VS Code version:  1.14.1
Python Extension version:  0.6.7
Python Version:  3.6.1
OS and version:  Windows 10 Professional 1703

## Actual behavior
Define an async function.
Define some variables in the function.
Try to use them below but no autocomplete for them.
And the variables outside the function work fine.

Like:
![2017-07-15_05-08-58](https://user-images.githubusercontent.com/12757496/28231067-1c75627a-691c-11e7-8fe6-40949333a16d.gif)

## Logs
VS Code doesn't show any error logs.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#140
