### ISSUE TITLE
Local Help File Set-up Documentation

### ISSUE THREAD

**Issue by headkase** [DonJayamanne/pythonVSCode#1086]
In the Wiki documentation under miscellaneous there is talk about "local help" (offline documentation) support.  However it is only mentioned in a bullet point and I am unable to find any documentation whatsoever about how to configure this option to use it.

If I'm just blind then please point me the way.

**Comment by headkase** [comment]
I notice now that local help isn't mentioned on the front page of the Wiki linked at the top of this page but it is discussed under Miscellaneous Features in this link:

https://donjayamanne.github.io/pythonVSCodeDocs/

So it may have been a feature that was planned but then later dropped.  I don't know, there is no documentation.

Thank you though for your time and effort creating this project - I really appreciate it.

**Comment by DonJayamanne** [comment]
@headkase  Fixed

**Comment by headkase** [comment]
I'm sorry.  I still don't see where the documentation to set up "local help" is.  However, it is your prerogative  to close a thread.  Again, my thanks for the extension - it's great.

**Comment by headkase** [comment]
This issue is resolved. 

Bring up the command palette with Control + Shift + P.
Enter "Python: Help" and press enter.
Help now appears in a window.  It is the documentation for the plugin and not the documentation that ships with Python itself.

Thank you DonJayamanne.

Also, in the change log in Visual Studio Code you listed this issue as 10860 instead of 1086.
