### ISSUE TITLE
Memory leak completion.py on debian 9

### ISSUE THREAD

**Issue by ivancandelas** [DonJayamanne/pythonVSCode#1088]
## Environment data
VS Code version:  1.14.1
Python Extension version:  0.6.7
Python Version:  2.7.13
OS and version:    Debian 9 Stretch

## Actual behavior
editing a python code when typing a python object the extension runs "completion.py preview" that has a memory leak with 3grb or more of RAM consumption
## Expected  behavior
the editor shows the object methods/properties without the memory leak

## Steps to reproduce:  
-  Open a python source with the extension enabled 
-  type a property/method of a class

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
This has been resolve. Please reopen if you believe it persists.
