### ISSUE TITLE
Environment variables are not available in python

### ISSUE THREAD

**Issue by szilvaa** [DonJayamanne/pythonVSCode#109]
Steps to repro on Mac:
1. Open terminal
2. Set an environment variable say 'foo'
3. Launch code .\
4. Debug some python script that looks for 'foo'. 

result: foo is not present
expect: foo should be present due to environment variable inheritance

**Comment by xqliu** [comment]
You may find this https://github.com/DonJayamanne/pythonVSCode/issues/77 useful.

**Comment by szilvaa** [comment]
Thanks! Using env in launch.json is a viable workaround in many situations but it is a workaround. The environment variables should be inherited. The fact that this is the 3rd bug on this issue is an indication that this is common problem for people.

**Comment by DonJayamanne** [comment]
From what I can understand GUI applications do not inherit the shell environment variables (at least not in a Mac environment). I have tested environment variables on a PC and it works as expected. This leads me to believe this is either an issue with VSCode (highly unlikey) or the way GUI applications inherit shell variables (most likely based on my research).

http://superuser.com/questions/476752/setting-environment-variables-in-os-x-for-gui-applications
https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPRuntimeConfig/Articles/EnvironmentVars.html

**Comment by DonJayamanne** [comment]
This is an issue in the extension and is being investigated.
