### ISSUE TITLE
Iterator without values when debugging

### ISSUE THREAD

**Issue by carlosbira** [DonJayamanne/pythonVSCode#1091]
## Environment data
VS Code version:  1.13.1 (1.13.1)
Python Extension version:  0.6.7
Python Version:   3.6
OS and version:  Mac OS 10.12.5

## Actual behavior
When debugging the result of a mysql.connector cursor, after executing the query to retrieve database data, although the internal variables of the cursor display that there were rows in it, the iterator does not return any content (row) at the for loop, skipping it completely since it returns behaves like an empty cursor. When same come is executed outside VS debug environment it works as expected, executing the for loop with the content that was supposed to bring same result when debugging.

## Expected  behavior
It should bring the content of each row at each iteration.  

## Steps to reproduce:
        <import mysql.connector>
        .....

        cursor = connCRM.cursor(buffered=True)
        cursor.execute("SELECT name, title FROM <table> WHERE name = %s", ("content",))
        n = 0

        for (name, title) in cursor:
            print(name)
            print(title)
            n += 1
-  
at the for loop it is skiped. If I use the other possible way, that would be though the use of fetchone(), nothing is returned from cursor. 

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by hjw2015** [comment]
+1

Works well if called with Ctrl+F5 also inside VS Code. No result returned from cursor if executed step-by-step.

**Comment by yaoliyc** [comment]
+1

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#143
