### ISSUE TITLE
import problem about python

### ISSUE THREAD

**Issue by chrmarti** [DonJayamanne/pythonVSCode#1092]
_From @HopeCollector on July 16, 2017 1:31_

- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:08:57.197Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-new-file|dku|3.1.0
python|don|0.6.7
auto-close-tag|for|0.4.3
code-runner|for|0.6.26
vscode-emacs|hir|0.1.1
vscode-clang|mit|0.2.2
cpptools|ms-|0.12.0
org-mode|too|0.1.3
cmake|twx|0.0.17
cmake-tools|vec|0.10.1

---

Steps to Reproduce:

1. create a virtualenv
2. use pip to install some packages (such as bs4)
3. create a sample .py file
4. import the packages you just installed
![p1](https://user-images.githubusercontent.com/20982951/28243760-e110e126-6a08-11e7-8e7f-d9313959d56d.jpeg)
5. select the python interpreter in the virtualenv (you can add it setting your `python.pythonPath`)
![p3](https://user-images.githubusercontent.com/20982951/28243777-70b1c32c-6a09-11e7-9289-319036bfb6ac.jpeg)
6. debug it
7. the program will enter the imp.py
![p2](https://user-images.githubusercontent.com/20982951/28243759-e0fda9a8-6a08-11e7-886c-b4e20f8def0f.jpeg)

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#30789_

**Comment by chrmarti** [comment]
_From @HopeCollector on July 16, 2017 1:32_

Sorry my English is a little strange😅

**Comment by chrmarti** [comment]
_From @circler3 on July 16, 2017 3:9_

I am sorry that I cannot reproduce the issue on win10.
I have a settings.json of
```json
{
    "python.pythonPath": "d:/myproject/env/scripts/python.exe"
}
```
and the result
![qq 20170716111146](https://user-images.githubusercontent.com/11972977/28244245-9576e3f0-6a17-11e7-937d-a1c9d429778b.png)
Moreover, I suggest that you could use  *"python.venvPath": "",* in the settings.json to make the use of virtualenv instead of modifying the *pythonPath* setting.
*Python: Select Workspace Interpreter* in the Command Palette will give you the access to custom virtualenvs.

**Comment by chrmarti** [comment]
_From @HopeCollector on July 16, 2017 6:7_

@circler3    Thank you for your suggestion, I can find my virtualenv through _Python : Select Workspace  Interpreter_ now 
But I still cannot get off this problem
When I use python interpreter which is in vitualenv, the problem will came out

**Comment by chrmarti** [comment]
_From @HopeCollector on July 16, 2017 6:38_

@circler3 I just found that python2.7 will work fun, but when you use python3.6 in virtualenv the problem will come out

**Comment by chrmarti** [comment]
_From @circler3 on July 16, 2017 7:24_

@HopeCollector I am using a official build of python 3.6.1. Vitualenv was installed by pip3. 
Maybe there are problems in the extensions since I have only installed the *python* extension. Besides, can you debug python 3 file without the virtualenv being activated?

**Comment by chrmarti** [comment]
_From @HopeCollector on July 16, 2017 13:23_

@circler3 It works perfect

**Comment by chrmarti** [comment]
_From @HopeCollector on July 17, 2017 5:29_

After many test and read some docs, I understand [how python import a module](https://docs.python.org/3/reference/import.html), and what will happen[ if I import module](https://leemendelowitz.github.io/blog/how-does-python-find-packages.html). But all of these seems not help. 
When I debug a python file with python3 in virtualenv python seems to create a new module whose name is `__main__`
 I did some [google search](https://www.google.com/search?q=why+python+create+a+__main__+module+at+first&oq=why+python+create+a+__main__+module+at+first&aqs=chrome..69i57.13814j0j7&sourceid=chrome&ie=UTF-8) but failed, I can find any thing useful

**Comment by chrmarti** [comment]
_From @circler3 on July 17, 2017 6:3_

I'm afraid that I can't help since I am not able to reproduce the problem. 
FYI. **\___main\___** is always the start module's *\___name\___* property whether you are using a virtualenv or not.

**Comment by skyjur** [comment]
I think either of these is happening:
1) module in question was installed in different python environment that vscode was configured to
2) there isn't any error at all, debugger stops at first line (because of `"stopOnEntry": true` in launch.json), and if we click "step-into" we get into `imp.py`, and this could be misunderstood as error

**Comment by skyjur** [comment]
Also, would be good to see `launch.json` config, it is possible that different python interpreter was set in `launch.json` config.

**Comment by leesoh** [comment]
I have the same problem, default `launch.json`, chose python from the "Choose Workspace Interpreter" option.

Modules are present in the venv. Didn't click step into. F5 > breakpoint in `imp.py`

**Comment by ArtFlag** [comment]
I have the same issue. It happened since I installed Python 3.6...

**Comment by kevinlong206** [comment]
Trying to run a tiny piece code python code with F5. Trying to do this using a virtualenv reference python 3.6.2 . 


my code is only:

def func(**kwargs):
    print(kwargs)

func(a=1, b=42)



When I hit F5 the linter jumps into imp.py also. Not sure why.

Get many linter errors:

![screen shot 2017-09-14 at 9 28 35 pm](https://user-images.githubusercontent.com/1462345/30466583-b912963c-9993-11e7-9c65-275915b626b3.png)


in my settings:

    "python.venvPath": "~/code/python-virtualenvs/",
    "python.pythonPath": "~/code/python-virtualenvs/kevin-py3.6/bin/python",


in launch.json:
"configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },

**Comment by DonJayamanne** [comment]
@kevinlong206 sorry but this doesn't make sense. Are you trying to debug or edit files?

**Comment by kevinlong206** [comment]
@DonJayamanne I was just trying to use the python debugger for the first time. I started with a very trivial piece of example code and when I ran, the debuger stopped on a python library file, imp.py . Seemed related to this issue. Any python snippet I tried to debug would similarly jump to this same line of the same file.

**Comment by savovs** [comment]
Got the same problem when debugging files. Only happens when I Select Workspace Interpreter to a pipenv Python 3 environment. Works fine with Python 2 environments.

**Comment by DonJayamanne** [comment]
@savovs 
This means you do not have the necessary package available in your Python 3 environment.

**Comment by leesoh** [comment]
I have the same issue when debugging `print('hello world')`.

**Comment by kevinlong206** [comment]
@DonJayamanne "This means you do not have the necessary package available in your Python 3 environment."  which package?

**Comment by DonJayamanne** [comment]
@kevinlong206 , oops, sorry, read the wrong message. The problem you are having is with the debugger. At the moment, the debugger issues have been put on hold as the PTVS team (@ Microsoft) are making some serious changes to the debugger.

**Comment by sbromberger** [comment]
Just FYI, I'm running into this same problem (imp.py line 56), but the suggested workaround (F5) brings me to `sre_parse.py` line 166:
```
        return self.data[index]
```
repeated F5s just bring me back here with an `IndexError` exception noted in the `Variables/Exception` window: "Type: IndexError, Description: list index out of range"

This is VSCode 1.19 on OSX 10.12.6, Python 0.9.1, Jupyter 1.1.4. I am using virtualenv if that matters, and my code is linting cleanly.

**Comment by jaimeabm** [comment]
**I had the problem that the code was stopping in the _imp.py_.**

I don't know if this works for you but worked for me,

1. Set stopOnEntry equal to false:

`"stopOnEntry": false,`

2. Select the launch settings for django and the virtual environment indicated in the launch settings

![image](https://user-images.githubusercontent.com/17678510/34911298-1581f426-f885-11e7-8d85-41b9b8002c4c.png)

3. The virtual environment indicated in the launch settings must have the equal path when selecting the interpreter:

`
            "name": "Python: Django",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "/Users/Jaime/.virtualenvs/ENV_REST/bin/python",
            "program": "${workspaceFolder}/backend/manage.py",
            "cwd": "${workspaceFolder}",
            "args": [
                "runserver",
                "--noreload",
                "--nothreading"
            ],
            "env": {},
            "envFile": "${workspaceFolder}/backend/.env",
            "debugOptions": [
                "RedirectOutput",
                "DjangoDebugging"
            ]
        }`

**Comment by Kogam22** [comment]
@DonJayamanne 

I don't use virtual env.
Just pip install my modules, and use them. When run from terminal directly, scripts work fine.
But VSCode clearly does not detect any modules.

**Says :**
```
[Running] /usr/bin/python "/home/adam/Code/wwcopy/Code.py"
Traceback (most recent call last):
  File "/home/adam/Code/wwcopy/Code.py", line 9, in <module>
    import cfscrape
ImportError: No module named cfscrape

[Done] exited with code=1 in 4.892 seconds
```

**launch.json :** 
```
//Why Is There So Much Inside Here 
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}"
        },
        {
            "name": "Python: Attach",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceFolder}",
            "remoteRoot": "${workspaceFolder}",
            "port": 3000,
            "secret": "my_secret",
            "host": "localhost"
        },
        {
            "name": "Python: Terminal (integrated)",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        },
        {
            "name": "Python: Terminal (external)",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "externalTerminal"
        },
        {
            "name": "Python: Django",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/manage.py",
            "args": [
                "runserver",
                "--noreload",
                "--nothreading"
            ],
            "debugOptions": [
                "RedirectOutput",
                "Django"
            ]
        },
        {
            "name": "Python: Flask (0.11.x or later)",
            "type": "python",
            "request": "launch",
            "module": "flask",
            "env": {
                "FLASK_APP": "${workspaceFolder}/app.py"
            },
            "args": [
                "run",
                "--no-debugger",
                "--no-reload"
            ]
        },
        {
            "name": "Python: Module",
            "type": "python",
            "request": "launch",
            "module": "module.name"
        },
        {
            "name": "Python: Pyramid",
            "type": "python",
            "request": "launch",
            "args": [
                "${workspaceFolder}/development.ini"
            ],
            "debugOptions": [
                "RedirectOutput",
                "Pyramid"
            ]
        },
        {
            "name": "Python: Watson",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/console.py",
            "args": [
                "dev",
                "runserver",
                "--noreload=True"
            ]
        },
        {
            "name": "Python: All debug Options",
            "type": "python",
            "request": "launch",
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "module": "module.name",
            "env": {
                "VAR1": "1",
                "VAR2": "2"
            },
            "envFile": "${workspaceFolder}/.env",
            "args": [
                "arg1",
                "arg2"
            ],
            "debugOptions": [
                "RedirectOutput"
            ]
        }
    ]
}
```

**settings.json :**
```
{
    "python.pythonPath": "/usr/bin/python3",
    "python.formatting.provider": "yapf"
}
```
