### ISSUE TITLE
Small typos in "Debugging" wiki page

### ISSUE THREAD

**Issue by fxlv** [DonJayamanne/pythonVSCode#1093]
There's one small typo on  [Debugging](https://github.com/DonJayamanne/pythonVSCode/wiki/Debugging#program) Page "program" section:

> This setting points to the fully **aualified** path of the python program to be debugged.

"aualified"  should be: "qualified"

Then couple of lines down:

> Entering the name of the Python file is also supported. However you need to ensure the file name is fully qualitified path. You have two options:

"qualitified " should be "qualified "

As I saw no way to edit it myself, creating this issue to you guys.

**Comment by DonJayamanne** [comment]
Fixed, thanks
