### ISSUE TITLE
don't create .vscode subdirectory where I opened vscode

### ISSUE THREAD

**Issue by bialix** [DonJayamanne/pythonVSCode#1096]
## Environment data
VS Code version:  Code 1.14.1 (2648980, 2017-07-13T19:18:47.188Z)
Python Extension version:  0.6.7
Python Version:   3.3
OS and version:    Windows 7

## Actual behavior
After last updates VS Code started to create .vscode folder every time I open it from command line, I don't want this junk everywhere I work with Code. And there was no such behavior before.

## Expected  behavior
Don't create .vscode unless asked.

## Steps to reproduce:  
-  open VSCode using following command:
```
code .
```

- Open or activate tab with python file

- Check the directory with command
```
C:\\some\\path>dir /b
.vscode
...
```

- When I disable Python extension - there is no such directory created.

- If I don't open python files - there is no such directory created.

## Settings  
Only really related to Python extension settings I have

Your settings.json:   
```json

    "python.pythonPath": "D:/python/3.3-64/python.exe",

    // Whether to lint Python files.
    "python.linting.enabled": false,
```

**Comment by bialix** [comment]
The most annoying thing about this issue: the directory .vscode is empty. There is nothing inside.

**Comment by s-trooper** [comment]
i found the source of problem here [generator.ts](https://github.com/DonJayamanne/pythonVSCode/blob/master/src/client/workspaceSymbols/generator.ts#L48) maybe one can fix it. btw it is the same issue as there https://github.com/DonJayamanne/pythonVSCode/issues/1076

**Comment by MarekLew** [comment]
Try for global settings(USER SETTINGS) set `python.workspaceSymbols.enabled` as `false`.
```
{
"python.workspaceSymbols.enabled" : false
}
```

If that helps , problem is _generated/not generated_ ctags

**Comment by JGH1000** [comment]
Found 20 .vscode folders in multiple directories..

**Comment by DonJayamanne** [comment]
Yes please disable the setting:
```json
{
"python.workspaceSymbols.enabled" : false
}
```

**Comment by bialix** [comment]
Please, automatically disable this settings by default! This is not user fault that you need something they don't have, but creating **empty** directory is **wrong**! I don't see any rationale for this annoying behavior.
