### ISSUE TITLE
ctag generate problem

### ISSUE THREAD

**Issue by MarekLew** [DonJayamanne/pythonVSCode#1097]
## Environment data
VS Code version:  1.14.1
Python Extension version:  0.6.7
Python Version:  2.7.13
OS and version: Microsoft Windows 10 Home ,10.0.15063 Compile 15063
ctag Version:
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jul  9 2009, 17:05:35
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +win32, +regex, +internal-sort

## Actual behavior
ctag not generate when `optionsFile` have space
## Expected  behavior
generate ctag when path have space
## Steps to reproduce:  
-  generate ctag `Python: Build Workspace symbols`
-  return in console
 ctags.exe: cannot open option file ""C:\Users\User with space\\.vscode\extensions\donjayamanne.python-0.6.7\resources\ctagOptions"" : Invalid argument

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
 ctags.exe: cannot open option file ""C:\Users\User with space\.vscode\extensions\donjayamanne.python-0.6.7\resources\ctagOptions"" : Invalid argument
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

In this moment I replace 

```
@generator.js line 29
- const optionsFile = this.optionsFile.indexOf(' ') > 0 ? `"${this.optionsFile}"` : this.optionsFile;
+ const optionsFile = this.optionsFile;
```
and its work fine, ctag generated.

**Comment by MarekLew** [comment]
In my computer on windows 10 `child_process.spawn` work correct without adding quotes to parameter with space

**Comment by MarekLew** [comment]
Same problem:
```
OS and version: Ubuntu 16.04 LTS
Python Extension version: 0.6.9
Python: 2.7.12

VSC Version 1.14.0
Commit b8cd5b9556d8b70ea560d35b903422363f6c5c40
Date 2017-07-10T20:36:40.018Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
```

For `child_process.spawn` `args` parameters do not need quotes, when space is inside.

**Comment by MarekLew** [comment]
```
VS Code version: 1.14.2
Python Extension version: 0.6.9
Python Version: 2.7.12
OS and version: Ubuntu 14.04 LTS
ctag Version: Exuberant Ctags 5.9~svn20110310, Copyright (C) 1996-2009 Darren Hiebert
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex

```
After delete quotes ctags generated but not sorted.

```
sort: cannot read: space/.vscode/tags: No such file or directory
ctags: cannot sort tag file : No such file or directory
```

**Comment by MarekLew** [comment]
Version 1.16.1
Python Extension version: 0.6.7
OS and version: Ubuntu 14.04 LTS

the same problem.

https://github.com/DonJayamanne/pythonVSCode/pull/1213 don`t fixed this.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#146
