### ISSUE TITLE
It failed to install pylint

### ISSUE THREAD

**Issue by hanbaobao2005** [DonJayamanne/pythonVSCode#1098]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.6.7
prettify-json|moh|0.0.3
cpptools|ms-|0.12.0
PowerShell|ms-|1.4.1
---

Steps to Reproduce:
1. Click 'Install' when it pop up the prompt for pylint installation.
![image](https://user-images.githubusercontent.com/1937472/28308818-fe098bfc-6bd9-11e7-8986-ead3223378d5.png)
The command failed to execute because lack of '&'
![image](https://user-images.githubusercontent.com/1937472/28308847-175c1598-6bda-11e7-9755-3faeccce4dd8.png)

Reproduces without extensions: No

I have reported this bug: https://github.com/Microsoft/vscode/issues/30893 .

**Comment by DonJayamanne** [comment]
Where is the & missing. Please confirm you are able you install pylint from the command line.

**Comment by DonJayamanne** [comment]
Please ensure your command window is set to CMD (standard command window) instead of PowerShell. Currently this won't work under PowerShell

**Comment by DonJayamanne** [comment]
Will look into adding support for PowerShell terminals

**Comment by hanbaobao2005** [comment]
@DonJayamanne  I am using default terminal: Powershell, and I make it work after add '&' at the beginning of the command.

**Comment by Kaba2** [comment]
I have also hit this bug. Pushing the install button attempts to run:

    "C:\Program Files (x86)\Python36-32\python" -m pip install pylint

which in Powershell seems not to be a valid command. The solution is to write

    &("C:\Program Files (x86)\Python36-32\python") -m pip install pylint

**Comment by DonJayamanne** [comment]
Personal note: Run commands via node and print output to a python output window.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#147
