### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by dmartincevic** [DonJayamanne/pythonVSCode#11]
Nothing happens on extension install -> ext install python. There is no error or success message. Extension is not showing in installed list. Other extensions are installed without problems. Windows Event log has no entries that would indicate source of problems. 
OS: Windows 8.1.

**Comment by dmartincevic** [comment]
It works fine after restarting the System. 
Just wanted to say that for debugging, type property in configurations should be "python" and not "python_windows" as it is shown in read me file.

`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python (Windows)",
            "type": "python",
`

**Comment by DonJayamanne** [comment]
Will update that, thanks
