### ISSUE TITLE
Add Auto-completion Support for PEP 526

### ISSUE THREAD

**Issue by vwxyzjn** [DonJayamanne/pythonVSCode#1101]
Please consider add auto-completion support for [PEP 526: Syntax for variable annotations](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep526) as the current version of pythonVSCode does not provide auto-completion for PEP 526 style variable (see screenshot below). 

This is a good feature to have because, in my opinion, the variable annotation of PEP 526 is much better than that of PEP 484. An example could look like this

```python
PEP_484_style = "hello world" # type: str
PEP_526_style: str = "hello world"
```
Both declaration are valid in Python 3.6 and PEP 526 feels more natural to use. 

## Environment data
VS Code version:  1.15.0-insider
Python Extension version:  
Python Version:   3.6
OS and version:    Windows 10

## Actual behavior
Auto-completion failed when I used PEP 526 variable annotations. 

![19](https://user-images.githubusercontent.com/5555347/28346434-20b4a748-6bff-11e7-8985-ac69ed70f75b.png)
## Expected  behavior
Expect auto-completion to work like it did with PEP 484 variable annotations. 

![18](https://user-images.githubusercontent.com/5555347/28346650-5627eac4-6c00-11e7-96e3-7590d0171df9.png)

## Steps to reproduce:  
Simply use the script
```python
PEP_484_style = "hello world" # type: str
PEP_526_style: str = "hello world"
```
and try to use the auto-completion

## Settings  
Your settings.json:   
```json
{
    "workbench.colorTheme": "Solarized Light"
}
```

**Comment by vwxyzjn** [comment]
I checked out the pythonVSCode repo and it seemed that it used Jedi as a server for parsing auto-completion. Fortunately, Jedi has already implemented PEP 526 in its parsing. Please check out this link:
https://github.com/davidhalter/jedi/commit/3f09f3a30432dacdc224a2f819a458a8218e3723

**Comment by vwxyzjn** [comment]
After experimenting, the auto-completion seemed to be working:

![21](https://user-images.githubusercontent.com/5555347/28350220-6a0c4516-6c15-11e7-8662-213e4d494dda.png)

**Comment by vwxyzjn** [comment]
Commit has been merged.

**Comment by SantjagoCorkez** [comment]
Doesn't handle PEP 526 still

![screenshot_20170907_142512](https://user-images.githubusercontent.com/9654644/30161266-7fc712a6-93d8-11e7-8e45-3f877ecb8c9c.png)

Ext version: 0.7.0
VSCode OSS: Version 1.15.1
Commit 41abd21afdf7424c89319ee7cb0445cc6f376959

Interpreter: 3.6.1 (virtualenv)

**Comment by vwxyzjn** [comment]
@SantjagoCorkez Did you update python extension to the latest version?

Mine works.

![image](https://user-images.githubusercontent.com/5555347/30253538-7f5448b4-9655-11e7-8d28-d1e48a8bc4fc.png)

**Comment by SantjagoCorkez** [comment]
> Did you update python extension to the latest version?

At the moment of my report the extension was just installed. I thought VSCode installs the latest version available at the moment.

But I've just checked. Mine is `0.7.0` which is the latest available here on GitHub.

**Comment by SantjagoCorkez** [comment]
Seems strange but now I've started VSCode and it shows the popup as on your shot. Though it fails to show correct hint for an element in that deque (PEP 526).

```
from collections import deque
from typing import Deque

class B:
    def __init__(self):
        self.a = 1
        self.b = 2

class A:
    my_var: Deque[B]

    def __init__(self):
        self.my_var = deque()
        pass
    

    def fun(self):
        a = self.my_var.pop()
        a.  # here a class B instance's hint should be shown


```

**Comment by vwxyzjn** [comment]
@SantjagoCorkez That seems to be an issue with [Jedi](http://jedi.readthedocs.io/en/latest/), the underlying auto-completion library for PythonVSCode.

Notice this branch only enables PEP 526 style variable to be recognized by Jedi, but the actual auto-completion is handled by Jedi.
