### ISSUE TITLE
0.6.8 does not find flake8

### ISSUE THREAD

**Issue by zgoda** [DonJayamanne/pythonVSCode#1105]
After upgrade to 0.6.8 systemwide installed flake8 is not used if project has configured separate python interpreter (eg. from virtualenv). I had to install it in venv to make linting work again.

```
$ which flake8
/usr/bin/flake8
$ workon rms
[rms] $ which flake8
/home/jarek/v/rms/bin/flake8
[rms] $ echo $WORKON_HOME
/home/jarek/v
```

My workspace settings.json:

```json
{
    "python.pythonPath": "/home/jarek/v/rms/bin/python"
}
```

**Comment by DonJayamanne** [comment]
Yes that's right. The New version will require you to have flake 8 in the environment bring used. This is to ensure the linters return the right errors, sometimes false positives are returned.

**Comment by DonJayamanne** [comment]
@zgoda oh yes if you still want to use the system wide flake, then put in the fully qualified path to flake in settings
