### ISSUE TITLE
pep8Path setting is not working

### ISSUE THREAD

**Issue by alessandrodimarco** [DonJayamanne/pythonVSCode#1106]
## Environment data
VS Code version:  1.14.2
Python Extension version:  0.6.8
Python Version:   3.5.2
OS and version:  macOS 10.12.5 

## Actual behavior
Vscode can't find linter set in the path `python.linting.pep8Path`.

## Expected  behavior
Linter should use value set in `python.linting.pep8Path` i.e. pycodestyle.

## Steps to reproduce: 
- `pip install pycodestyle`
-  Set pep8 linting settings
   -  `"python.pythonPath": "/Users/USER/.pyenv/versions/VIRTUALENV/bin/python",`
   -  `"python.linting.pep8Path": "pycodestyle"`
   -  `"python.linting.pep8Enabled": true`
- Create test file with pep8 warning

## Logs
Output from ```Python``` output panel  
```
Linting with pep8 failed.
You could either install the 'pep8' linter or turn it off in setings.json via "python.linting.pep8Enabled = false".
Error: Command failed: /Users/USER/.pyenv/versions/VIRTUALENV/bin/python -m pep8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s
/Users/USER/path/to/test.py
/Users/USER/.pyenv/versions/VIRTUALENV/bin/python: No module named pep8
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
Linter pep8 is not installed     messageService.ts:125
```

**Comment by DonJayamanne** [comment]
Will fix this tonight

**Comment by joedborg** [comment]
+1 started with update to code on MacOS and Linux

**Comment by DonJayamanne** [comment]
@joedborg please describe your issue.

**Comment by DonJayamanne** [comment]
Have you installed pep8 using the prompts? What is your setup?

**Comment by joedborg** [comment]
Linux wise, here is my config:

```json
{
    "editor.fontSize": 16,
    "editor.fontFamily": "Source Code Pro Semibold",
    "editor.fontLigatures": true,
    "editor.renderWhitespace": "all",

    "files.autoSave": "afterDelay",
    "workbench.colorTheme": "One Dark Pro",

    "python.linting.pylintEnabled": true,
    "python.linting.pylintPath": "/home/joe/.linuxbrew/bin/pylint",
    "python.linting.flake8Enabled": true,
    "python.linting.flake8Path": "/home/joe/.linuxbrew/bin/flake8"
}
```
Both those exes are there and working.  But I constantly get `Linter flake8 is not installed` and `Linter pylint is not installed`

This was working fine until update to VSCode 1.14.1.  

Same story with the MacOS instance too.

**Comment by joedborg** [comment]
Also just tried this with 1.14.2 and the issue persists.

I wont install via prompt because I do not touch system Python.

**Comment by jerivas** [comment]
Can confirm. VS Code says `flake8` is not installed even though it is and the path has been set (in both user and workspace settings):

```json
"python.linting.enabled": true,
"python.linting.flake8Enabled": true,
"python.linting.flake8Path": "C:\\Python36\\Scripts\\flake8.exe",
"python.linting.pylintEnabled": false,
````

**Comment by leorochael** [comment]
I think I have a related issue:

`pylint` and `flake8` started complaining about not being istalled in my setup since I the `0.6.8` release I believe.

Opening the output window (`View: Toggle Output`) I see the following messages:

```
Linting with pylint failed.
You could either install the 'pylint' linter or turn it off in setings.json via "python.linting.pylintEnabled = false".
Error: Command failed: /home/me/myvitualenv/bin/python2.7 -m pylint --msg-template='{line},{column},{category},{msg_id}:{msg}' --reports=n --output-format=text /home/me/myvitualenv/some/path/myfile.py
/home/leonardo/Workspace/ybpbuildout/bin/python2.7: No module named pylint

Linting with flake8 failed.
You could either install the 'flake8' linter or turn it off in setings.json via "python.linting.flake8Enabled = false".
Error: Command failed: /home/me/myvitualenv/bin/python2.7 -m flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s /home/me/myvitualenv/some/path/myfile.py
/home/leonardo/Workspace/ybpbuildout/bin/python2.7: No module named flake8
```

It explains why I'm getting the failures:

In my environment, `pylint` and `flake8` are available on `$PATH`, but are not installed in the virtualenv for the Python at `/home/me/myvitualenv/bin/python2.7`

The result is that a call to `pylint` or `flake8` would work, but `python -m pylint` or `python -m flake8` would not.

I would rather not install `pylint` and `flake8` in the virtualenv for my project, it doesn't depend directly on them.

For reference, here is my Workspace config:

```
{
"python.pythonPath": "${workspaceRoot}/bin/python2.7",
"python.linting.flake8Enabled": true,
"xmlTools.splitXmlnsOnFormat": false
}
```

My user config has no python or linting custom settings, so not relevant.

Changing the workspace settings to mention the path to `pylint` and `flake8` directly seems to have no effect and I keep getting the exact same failures in the output console as above. I.e. adding the lines below to the workspace settings (which were copied from the default settings) had no effect:

```
"python.linting.pylintPath": "${workspaceRoot}/bin/pylint",
"python.linting.flake8Path": "${workspaceRoot}/bin/flake8",
```

**Comment by leorochael** [comment]
As a workaround, I opened this file:

    $HOME/.vscode/extensions/donjayamanne.python-0.6.8/out/client/common/installer.js

And edited lines like this (lines # 50 to 60):

    exports.ProductExecutableAndArgs.set(Product.pylint, { executable: 'python', args: ['-m', 'pylint'] });

To look like this:

    exports.ProductExecutableAndArgs.set(Product.pylint, { executable: 'pylint', args: [] });

On Windows, the same file would be at:

    %USERPROFILE%\.vscode\extensions\donjayamanne.python-0.6.8\out\client\common\installer.js

**Comment by DonJayamanne** [comment]
@alessandrodimarco @ joedborg @jerivas @leorochael
new version has been published with a fix.

**Comment by joedborg** [comment]
Many thanks @DonJayamanne.  Have you got a beer fund?

**Comment by DonJayamanne** [comment]
I can start one, provided there won't be any deductions for issues opened..

**Comment by leorochael** [comment]
@DonJayamanne,  5fafae1 fixed the issue where, when one specifies `python.linting.pylintPath` it was not being respected, but it doesn't fix the issue where `pylint` is in the path, but not installed in the Python (virtual) environment that is in the path.

I created a new issue for this, though: #1116
