### ISSUE TITLE
Feature Request: "Add Package"

### ISSUE THREAD

**Issue by sivy** [DonJayamanne/pythonVSCode#1109]
## Environment data
VS Code version:  1.14
Python Extension version: 0.6.8 
Python Version:  2.7
OS and version: OS X, 10.10   

## Desired  behavior

1. Right-click on a folder in the sidebar
2. Select "Add package"
3. Creates a new folder waiting to be named, *prepopulated with an `__init__.py`*

Alternatively:

1. Cmd-Shift-P, "Create package" or "Create package with path..."
2. Type in a dot-path "new.package.path"
3. Folder structure with `__init__.py` files in place is created.

This would save a lot of annoying steps, especially in newer projects.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#150
