### ISSUE TITLE
Empty brackets filled in during autocompletion

### ISSUE THREAD

**Issue by GreenJoey** [DonJayamanne/pythonVSCode#1110]
## Environment data
VS Code version:  1.14.0
Python Extension version:  0.6.9 (22 July '17)
Python Version:   3.6.1
OS and version:    Ubuntu 17.04

## Actual behavior

Whenever I use auto-complete to complete a function a empty `{{}}` is put inside the function's parenthesis

#### During the auto-completion
![Extension suggesting completion](https://user-images.githubusercontent.com/19374280/28488822-774691e2-6ed0-11e7-8bb7-660000cc1aa0.png)
#### This happens after I press **Enter** or **Tab**
![After I pressed **Enter**, this happens](https://user-images.githubusercontent.com/19374280/28488816-468bc266-6ed0-11e7-9d9b-c9bd6843b5e3.png)
#### Whereas this should have happened
![But this should have happened isn't it?](https://user-images.githubusercontent.com/19374280/28488828-b91d8b5c-6ed0-11e7-8a2e-7b949fa507f7.png)

## Steps to reproduce:  
I don't know how to reproduce. This problem existed when I installed this extension. All I can offer is the config I made for this extension
```json
{
    "python.pythonPath": "/usr/bin/python3.6",
    "python.formatting.formatOnSave": true,
    "python.autoComplete.addBrackets": true,
    "python.terminal.executeInFileDir": true
}
```

**Comment by DonJayamanne** [comment]
>This problem existed when I installed this extension. 

Please uninstall this extension and confirm the problem exists.

**Comment by GreenJoey** [comment]
After uninstalling it, auto-completion is gone but the problem doesn't happens (tested using a basic user-defined class)

**Comment by niyanchun** [comment]
Ihave the same problem, it will add "{{}}"in function...

**Comment by GreenJoey** [comment]
Hey, the update hasn't came yet!

**Comment by DonJayamanne** [comment]
No it hasn't, please wait
