### ISSUE TITLE
Linting with Prospector produces a module error

### ISSUE THREAD

**Issue by mylincode** [DonJayamanne/pythonVSCode#1111]
## Environment data
VS Code version:  1.14.2
Python Extension version:  0.6.9
Python Version:   3.6.2
OS and version:    macOS Sierra 10.12.5

## Actual behavior
When using Prospector as the active linter, it produces an error at the top of the file with a message along the lines of:

    [prospector - pylint] fatal:No module named <full path to file being linted>

I can reproduce this in the terminal if I invoke Prospector with the full path to the file, but not if I use a relative path from the file's containing directory.

## Expected  behavior
Having no such error at the top of every file being linted.

## Steps to reproduce:  
Described above under "Actual Behavior".

## Logs
No output from the ```Python``` output panel.

No output from ```Console window```.

**Comment by RoscoP** [comment]
I also have issues running prospector (with current and previous versions).  I get this in the Output window 'Python' tab.
```
Linting with prospector failed.
You could either install the 'prospector' linter or turn it off in setings.json via "python.linting.prospectorEnabled = false".
Error: Command failed: <PROJPATH>\venv\scripts\python.exe -m prospector --absolute-paths --output-format=json <PROJPATH>\somefile.py
<PROJPATH>\venv\scripts\python.exe: No module named prospector.__main__; 'prospector' is a package and cannot be directly executed
```
I have installed prospector into my virtualenv of my project.  Running the command from a stand alone terminal produces the same error.  If I call `prospector.exe` or `python <PROJPATH>\venv\Lib\site-packages\propspector\run.py` directly with the same arguments it works fine. 
Settings:
```
{
    "python.linting.prospectorEnabled": true,
    "python.linting.pylintEnabled": false
}
```
- VS Code version: 1.14.2
- Python Extension version: 0.7.0
- Python Version: 2.7.13
- OS and version: Windows 10 (10.0.14393)

**Comment by chocoelho** [comment]
I'm having this problem as well and updating prospector/setting `prospectorPath` variable did not solve it. I noticed that the file path(looking for the message) the linter is looking for is indeed invalid:
```
file: 'file:///home/chocoelho/Projects/altlegal-api/trademarks/helpers/uspto/creators.py'
severity: 'Error'
message: 'fatal:No module named home/chocoelho/Projects/altlegal-api/trademarks/helpers/uspto/creators.py'
at: '1,1'
source: 'prospector - pylint'
```
The same doesn't happen when running prospector from terminal, so I think is something related to the configuration in this package.

**Comment by chocoelho** [comment]
Ignore what I said before, it IS a problem with prospector. I just tried it out passing the absolute file path as an argument, and it threw this error message too.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#151

**Comment by rekaut** [comment]
I had added to the user setting and while the value of prosepectorEnagled is true, it will asking for the dev model of the print, by changing the value to false will no more red under line in print command.  
def print(value, ..., sep, end, file, flush)
Prints the values to a stream, or to sys.stdout by default. Optional keyword arguments: file: a file-like object (stream); defaults to the current sys.stdout. sep: string inserted between values, default a space. end: string appended after the last value, default a newline. flush: whether to forcibly flush the stream.
in setting:
{
"python.autoComplete.addBrackets": true,
"python.linting.prospectorEnabled": false,
}
