### ISSUE TITLE
Issue while Debugging

### ISSUE THREAD

**Issue by weinand** [DonJayamanne/pythonVSCode#1112]
_From @racterub on July 22, 2017 16:55_

- VSCode Version:1.14.2
- OS Version:Windows 10 build 1703

Steps to Reproduce:

1.Into Debug Mode
2.While running python through `import` command, is will also step info module's function.

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#31261_

**Comment by racterub** [comment]
typo: 'step info' -> 'step into'

**Comment by DonJayamanne** [comment]
> Reproduces without extensions: Yes

If this is the case, then this isn't related to the python extension. 
Please reopen the issue if the problem persists.
