### ISSUE TITLE
Pylint, Flake8, etc., have to be installed in the default Python.

### ISSUE THREAD

**Issue by leorochael** [DonJayamanne/pythonVSCode#1116]
## Environment data
VS Code version:  1.14.2
Python Extension version:  0.6.9
Python Version:   2.7.6
OS and version:    Ubuntu 14.04

## Actual behavior

Since 0.6.8, `pylint` and `flake8` started complaining about not being installed in my setup.

In my environment, `pylint` and `flake8` are available on `$PATH`, but are not installed in the virtualenv for the Python at `/home/me/myvitualenv/bin/python2.7`

The result is that a shell to `pylint` or `flake8` would work, but `python -m pylint` or `python -m flake8` would not.

I would rather not install `pylint` and `flake8` in the virtualenv for my project, it doesn't depend directly on them and I don't want to pollute the set of packages in the virtualenv.

For reference, here is my Workspace config:

```
{
"python.pythonPath": "${workspaceRoot}/bin/python2.7",
"python.linting.flake8Enabled": true,
"xmlTools.splitXmlnsOnFormat": false
}
```

My user config has no python or linting custom settings, so not relevant.

Since 0.6.9 (5fafae1), a workaround is to change the workspace settings to mention the path to `pylint`/`flake8`, etc., directly:

```
"python.linting.pylintPath": "path/to/bin/pylint",
"python.linting.flake8Path": "path/to/bin/flake8",
```
## Expected  behavior

Since the default setting of `python.linting.pylintPath` and `python.linting.pylintArgs` are `pylint` and `[]`, respectively, instead of `python` and `['-m', 'pylint']`, then the expectation is that simply providing `pylint` or `flake8` on the path should be enough to make them work.

At the very least the error message should be changed from:

 - `Linter pylint is not installed`

To:

 - `Linter pylint is not installed in the default Python, Check the output log` with a button to open the log.

Then explain in the output log how to run `pylint`/etc. from path instead of as a Python module.

Ideally, there should be a way to specify that `pylint` should be run from the path instead of as a module of the default Python, even if this setting is not on by default (I know, adding another setting sucks, but if there should not be another setting, I'd rather the default be to run `pylint`/`flake8`/etc. from the path rather than from the respective Python module, though I can understand if you think it should be the other way around and don't add anything else).

## Steps to reproduce:  
-  Create an empty virtualenv but don't activate it
-  Install `pylint` outside of the virtualenv, but in the path (e.g. `apt-get install pylint` or `pip install --user pylint` or, my favorite, `pipsi install pylint`)
- Activate the virtualenv
- Check that you can run `pylint`, but that it doesn't belong to the virtualenv
- Start `code`
- Change and save a Python file
- Get the error message `Linter pylint is not installed`.

## Logs
Output from ```Python``` output panel  
```
Linting with pylint failed.
You could either install the 'pylint' linter or turn it off in setings.json via "python.linting.pylintEnabled = false".
Error: Command failed: /home/me/myvitualenv/bin/python2.7 -m pylint --msg-template='{line},{column},{category},{msg_id}:{msg}' --reports=n --output-format=text /home/me/myvitualenv/some/path/myfile.py
/home/leonardo/Workspace/ybpbuildout/bin/python2.7: No module named pylint

Linting with flake8 failed.
You could either install the 'flake8' linter or turn it off in setings.json via "python.linting.flake8Enabled = false".
Error: Command failed: /home/me/myvitualenv/bin/python2.7 -m flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s /home/me/myvitualenv/some/path/myfile.py
/home/leonardo/Workspace/ybpbuildout/bin/python2.7: No module named flake8
```

Output from ```Console window``` (`Help->Toggle Developer Tools` menu)
```
Linter pylint is not installed
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
(anonymous) @ mainThreadMessageService.ts:64
n.Class.derive._oncancel @ winjs.base.raw.js:1641
t.showMessage @ mainThreadMessageService.ts:34
t.$showMessage @ mainThreadMessageService.ts:28
e.handle @ abstractThreadService.ts:34
s @ ipcRemoteCom.ts:275
f @ ipcRemoteCom.ts:231
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

**Comment by leorochael** [comment]
This is somewhat related to #1106, but different.

There the issue there was that the custom settings for linter paths were not being respected.

The issue here is that the default configuration used to work for linters on the path but not on the virtualenv (or whatever the default python on the path is), and now they don't.

The "settings" workaround specified above would work in users preferences for a single global linter, and in workspace preferences for a custom linter per workspace, but if your setup is like mine and you already had a $PATH setting per workspace before starting `code` that included path to different linters per workspace, a more "permanent" workaround that doesn't require editing the settings for each workspace is as follows:

Open the file:

    $HOME/.vscode/extensions/donjayamanne.python-0.6.9/out/client/common/installer.js

And edit lines like this (lines # 50 to 60):

    exports.ProductExecutableAndArgs.set(Product.pylint, { executable: 'python', args: ['-m', 'pylint'] });

To look like this:

    exports.ProductExecutableAndArgs.set(Product.pylint, { executable: 'pylint', args: [] });

On Windows, the same file would be at:

    %USERPROFILE%\.vscode\extensions\donjayamanne.python-0.6.9\out\client\common\installer.js

**Comment by obambrough** [comment]
Python Version: 2.6.9
OS: Ubuntu 16.04

I have a slightly different issue (I see 'flake8 is a package and cannot be directly executed' in the Python output panel) but I think it's the same issue. My environment is slightly different, both Python 2.6 and flake8 are installed in the virtual environment so the Python extension is finding flake8 but flake8 can't be executed via 'python -m flake8' (does this work with Python 2.7 or 3?)

We share settings.json so I'd rather not configure paths, so my work-around, after reviewing commit [5fafae1](https://github.com/DonJayamanne/pythonVSCode/commit/5fafae1b4efd754eed8f188950555a1afba9fd44), is to set a flake8 argument which then circumvents the running of flake8 via 'python -m'. 
e.g. `"python.linting.flake8Args": ["--show-source"]`

**Comment by leorochael** [comment]
> I have a slightly different issue (I see 'flake8 is a package and cannot be directly executed' in the Python output panel) but I think it's the same issue. My environment is slightly different, both Python 2.6 and flake8 are installed in the virtual environment so the Python extension is finding flake8 but flake8 can't be executed via `python -m flake8`

@obambrough, your case indeed seems to be related to mine, with a twist: Python 2.6 doesn't know how to run "python packages" with `python -m`, only "python modules", and flake8 is distributed as a python package, not a python module. By adding `flake8Args` to your config, you're making the extension not pick it's default of running `python -m flake8` when the flake8 path is `flake8` and `flake8Args` is empty, running instead `flake8 <...other args...>` as it's configured.

> (does this work with Python 2.7 or 3?)

[Yes it does](https://stackoverflow.com/a/9407178/1273938). For Python 2.6 you'd have to do:

 - `python -m flake8.__main__`

**Comment by leorochael** [comment]
> Related, if not the same issue: #716

@fredrikaverpil, It's certainly related.

In the end, there is a conflict between:

 1. Locating `pylint`, `flake8`, etc... by their presence of  the O.S. `$PATH`

and:

 2. Locating `pylint`, `flake8`, etc... by their presence as modules/packages in the configured Python, running them as `['python', '-m', '<linter>', ...]`

In some cases, the right thing is to do one, in some cases, it's the other, and always doing only one of them is bound to break the setup for some people.

This Python vs.code extension is choosing between doing one or the other depending on the settings `"python.linting.<linter>Args"` or `"python.linting.<linter>Path"` (`<linter>` being `pylint`, `flake8`, etc.). If these settings are set to their default values it's doing 2, if not, it's doing 1.

In part this happens because doing 2 requires messing with the arguments (prepending `['-m', <linter>]` to them, while also changing the command path to be `python`). But then there is no way of explicitly requesting the behavior in 1 without messing with the defaults, even when the defaults would have been perfectly fine for doing 1.

Also, if one wants the behavior in 2, but wants to explicitly pass extra arguments to the linter, the only way to do so is to change both `"python.linting.<linter>Path"` to `python` and `"python.linting.<linter>Args"` to `['-m', <linter>, '--my-extra-args', ...]`.

IMHO, this behavior of the Python vs.code extension is too implicit ([Explicit is better than implicit](https://www.python.org/dev/peps/pep-0020/)), but I can understand the desire not to add another setting (for each linter!) just for selecting between behaviors 1 or 2.

I also understand that the current default behavior is likely to be the correct one in most cases.

So I'd like to propose this change:

1. select a special character that, if present as the first char of `"python.linting.<linter>Path"`, means that the rest of the value is the name of the linter module that should be executed with the default python (`"python.pythonPath"`), and that `['-m', <linter>]` should be prepended to the value of `"python.linting.<linter>Args"`. Something like

  - `"python.linting.flake8Path": ':flake8'`

This char should not be a valid python identifier char, and perhaps should not be a valid (or likely) path char either. [Some good options here](https://stackoverflow.com/a/31976060/1273938).

2. To preserve the current behavior of doing 2 by default, change the default value of `"python.linting.<linter>Path"` to be `<special-char><linter>`, e.g. `:flake8` like in the example above.

Someone who wants to do 2, but is running Python 2.6 like @obambrough, can do for example:

  - `"python.linting.flake8Path": ':flake8.__main__'`

In this proposal, if the user wants to do 2 with a python that is different than the one on `"python.pythonPath"`, they'd have to customize both `"python.linting.<linter>Path"` to their desired Python and `"python.linting.<linter>Args"` to start with `['-m', <linter>]`, but this is something they would have to do currently anyway.

@DonJayamanne, what do you think?
