### ISSUE TITLE
Cannot disable Python formatOnSave while editor formatOnSave is enabled

### ISSUE THREAD

**Issue by bjudson** [DonJayamanne/pythonVSCode#1117]
## Environment data
VS Code version:  1.14.2
Python Extension version:  0.6.9
Python Version: 2.7.10
OS and version:  Mac OS X 10.12.4

## Actual behavior
Cannot disable `python.formatting.formatOnSave` while `editor.formatOnSave` is enabled.

## Expected  behavior
`python.formatting.formatOnSave` preference should override `editor.formatOnSave` preference.

## Steps to reproduce:  
-  Put the following into user settings:
```
  "editor.formatOnSave": true,
  "python.formatting.formatOnSave": false
```
-  Save a Python file. It will attempt to run the formatter, and show an error if a formatter isn't installed.

**Comment by kabrau** [comment]
Hi, I love this extension
But, now, dont update and dont install the last version 0.6.9
Error: **end of central directory record signature not found**

Visual Studio Code Version: 1.14.0  Date 2017-07-10T18:36:31
Shell 1.6.6
Node 7.4.0
Windows 10 version 1703

**Comment by DonJayamanne** [comment]
@kabrau You might want to describe this issue before you ask everyone not to install the extension, there are a number of people using this without any issues.

>Error: end of central directory record signature not found

**Comment by bjudson** [comment]
I'm not seeing the issue @kabrau described, everything is working great for me except the minor formatOnSave preference issue. Seems completely unrelated.

**Comment by kabrau** [comment]
I'm sorry, I did not mean to offend you, I deleted the comment with my problem.
I'll wait until it solves itself.

**Comment by DonJayamanne** [comment]
Not offended, but if there is an issue you need to describe it clearly, before making sweeping statements. 
So please describe your issue and I'll try to help.

**Comment by bjudson** [comment]
To flesh this issue out a little, **the use case is**: I have JavaScript and Python in the same project. I want to user Prettier for JavaScript, but I'm not happy with the Python code formatting options at this point.

**The problem is**: if either `editor.formatOnSave` or `python.formatting.formatOnSave` is set to `true`, the plugin will enable Python formatting. The default for both is `false`. The default config is simply merged with explicit user/workspace config. Therefore, the plugin can't tell if I enabled `editor.formatOnSave` and _explicitly disabled_ `python.formatting.formatOnSave`, or if I just left the default in place, expecting that `editor.formatOnSave` would enable it for me.

**The simplest solution for my use case** would be to ignore `editor.formatOnSave`, and make users enable Python formatting explicitly. But that might not be ideal for other users. 

**More complex solution** would be to implement a way to distinguish between default config and user config of the same value. If user has explicitly disabled Python formatting, that should override the global `editor.formatOnSave`. 

Also going to open an issue with Prettier plugin, to add a formatOnSave option.

**Comment by bjudson** [comment]
I'm closing this issue, because I just learned about language-specific settings in VSCode. In my case all I needed was:
```
{
  "editor.formatOnSave": false,
  "[javascriptreact]": {
      "editor.formatOnSave": true
  }
}
```
