### ISSUE TITLE
Auto Indent by indentation rules

### ISSUE THREAD

**Issue by rebornix** [DonJayamanne/pythonVSCode#1119]
## Environment data
VS Code version:  1.14
Python Extension version:  Latest 
Python Version:  Any
OS and version:    macOS

We implemented auto indent by bringing indentation rules (which was originally invented by TextMate https://manual.macromates.com/en/appendix). It would be great if we add this feature to Python extension. A good starting point is Atom's [Python Indentation Rules](https://github.com/atom/language-python/blob/master/settings/language-python.cson) but note it has some [potential issues](https://github.com/atom/language-python/issues?q=is%3Aopen+is%3Aissue+label%3Aauto-indent)

**Comment by jarshwah** [comment]
I believe https://github.com/DonJayamanne/pythonVSCode/issues/1087 might be related

**Comment by gandhis1** [comment]
Don tried this before if I recall, but I don't remember what the issues he encountered were. Will see if I can dig up the issue number
