### ISSUE TITLE
Suppress pylint output from console / don't erase console contents on pylint run

### ISSUE THREAD

**Issue by dlorch** [DonJayamanne/pythonVSCode#112]
I write console-based applications. Every time pylint runs, it overwrites the console output. If pylint has no  errors, the console window just goes blank and erases output from my application. Is there a way to either suppress pylint output from the console (it is available in the editor window anyway) or to redirect pylint output to another window (e.g. the "tasks" window)?

**Comment by DonJayamanne** [comment]
Good idea, i'll consider re-directing linting messages to the tasks window, possibly based on a config setting.

**Comment by dlorch** [comment]
Very cool, thank you!
