### ISSUE TITLE
"Pylint not installed" error can be misleading

### ISSUE THREAD

**Issue by azinman** [DonJayamanne/pythonVSCode#1120]
When a plugin for pylint isn't installed, but pylint _is_ installed, the error message and its recovery methodology falsely reports the problem as not finding pylint instead of the error initializing it given its missing plugin dependency.

## Environment data
VS Code version:  1.14.2
Python Extension version:  0.6.9
Python Version:   2.7.12
OS and version:    Mac OS X 10.12.5

## Actual behavior
When saving a file / activating pylint, given the message "Linter pylint is not installed". Clicking install activates pip, which reports that all dependencies have already been installed and satisfied.

## Expected  behavior
pylint to run, and if a plugin is missing for install to prompt installing said plugin (or otherwise give a message that doesn't indicate that the plugin is the missing dependency, or that it had trouble starting pylint which was installed).

## Steps to reproduce:  
- pip install pylint
- Configure the VS plugin to use pylint
- Add the pylint_django plugin to the configuration, but actually install it via pip.

## Logs
Output from ```Console window``` (Help->Developer Tools menu)
I had to modify the source to print this out, but eventually it lead to the actual issue:
```
Error: Command failed: <my virtualenv path>/bin/pylint --load-plugins pylint_django --msg-template='{line},{column},{category},{msg_id}:{msg}' --reports=n --output-format=text <some path to a file>.py
Traceback (most recent call last):
  File "<my virtualenv path>/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "<my virtualenv path>/lib/python2.7/site-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "<my virtualenv path>/lib/python2.7/site-packages/pylint/lint.py", line 1222, in __init__
    linter.load_plugin_modules(self._plugins)
  File "<my virtualenv path>/lib/python2.7/site-packages/pylint/lint.py", line 468, in load_plugin_modules
    module = modutils.load_module_from_name(modname)
  File "<my virtualenv path>/lib/python2.7/site-packages/astroid/modutils.py", line 190, in load_module_from_name
    return load_module_from_modpath(dotted_name.split('.'), path, use_sys)
  File "<my virtualenv path>/lib/python2.7/site-packages/astroid/modutils.py", line 232, in load_module_from_modpath
    mp_file, mp_filename, mp_desc = imp.find_module(part, path)
ImportError: No module named pylint_django

    at ChildProcess.exithandler (child_process.js:223:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by DonJayamanne** [comment]
What's your pythonpath in your workspace settings.json.   
what are your settings for pylint in the settings.  
Are you using a virtual environment?

**Comment by guilatrova** [comment]
@DonJayamanne  I'm getting same error here.

Selected pythonpath (virtualenv) through command "Select workspace interpreter"
My settings:
`{
    "python.pythonPath": "c:/Users/[PATH]/venv/scripts/python.exe",        
    "python.linting.pylintArgs": [
        "--load-plugins",
        "pylint_django"
    ]
}`
using virtual environment

Windows 10
pylint 1.7.1,
astroid 1.5.2
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
pylint-django 0.7.2

**Comment by yultide** [comment]
@DonJayamanne I'm getting same error on Mac also.

When I try to install pip, it's using the incorrect python in my settings.

> % python -m pip install pylint
> /usr/bin/python: No module named pip

In my settings I explcitly set my python executable but it is ignored
"python.pythonPath": "/usr/local/bin/python",

**Comment by DonJayamanne** [comment]
@guilatrova, the new version requires you to have the modules installed in your selected environment. Looks like you do not have pylint installed in your (selected) python environment.

Why the change. Simple modules such as pylint look for modules relative to the python environment they are installed in. So if you use pylint installed in global namespace then it will complain about modules not being available (linter errors). (scenario, you have a module in your private python environment and not in global).

I could however provide an option to use either the local or global version of pylint (& other linters)

**Comment by DonJayamanne** [comment]
@yultide you'll need to install pip

**Comment by yultide** [comment]
@DonJayamanne yes, pip is already installed.  I figured out a workaround for me.  I had to set an alias for python in my .bash_profile

> alias python=/usr/local/bin/python3

Do you know why it's not running the version of python in my vscode settings?

**Comment by DonJayamanne** [comment]
personal note: TODO - check if linter is installed before displaying the error.

**Comment by i90rr** [comment]
Hi all,

I just stumbled upon this issue but in my case `"python.pythonPath": "/usr/local/bin/python3",` works as expected.

OS: macOS Sierra 10.12.6
pylint 1.7.4, 
astroid 1.5.3
Python 3.6.2 (default, Jul 17 2017, 16:44:45) _installed via Homebrew_

HTH!
