### ISSUE TITLE
file object is not writing to disk using the write

### ISSUE THREAD

**Issue by larsoleruben** [DonJayamanne/pythonVSCode#1125]
## Environment data
VS Code version:  1.14.2
Python Extension version:  0.6.9 (22 July 2017)
Python Version:   3.6
OS and version:    Windows 8.1

## Actual behavior
This will not write to the file during debugging
<snippet>
myFile = open('c:/temp/test.txt', 'w')
a = myFile.write('ddsdsdsds\n')
print(a)
myFile.close
</snippet>
This correctly writes to the file during debugging
<snippet>
with open('c:/temp/test.txt', 'w') as outfile:
    a=outfile.write("sdsdsdsdsd\n")
    print(a)
</snippet>

## Expected  behavior
The above code should both write to the file. also during debugging
## Steps to reproduce:  
Excute above
-  
If the script is executed from the console, both methods works
Also the code works nomally in Visual Studio, and also Visual Studio Code for Mac.
Only win 8.1 seems to have a problem.

## Logs
Output from ```Python``` output panel  
Nothing
```   
Output from ```Console window``` (Help->Developer Tools menu)
Nothing
```

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#153
