### ISSUE TITLE
Caching all functions for intellisense

### ISSUE THREAD

**Issue by duytrung** [DonJayamanne/pythonVSCode#1128]
Just a silly question: How to enable caching all function for intellisense?

I found similar functionality in Pycharm when it autoupdate and cache all functions for the programming step.

Thank you!

## Environment data
VS Code version:  1.14.2
Python Extension version:  1.0
Python Version:   3.6.2 
OS and version:    windows 10 home
## Actual behavior
no intellisense for functions/methods when pressing tab
## Expected  behavior
press tab to display the available methods.

**Comment by DonJayamanne** [comment]
The library used (Jedi) generally performs the necessary caching.
