### ISSUE TITLE
"Go to Python Object" can't find objects

### ISSUE THREAD

**Issue by marspe** [DonJayamanne/pythonVSCode#1129]
## Environment data
VS Code version: 1.14.2
Python Extension version: 0.6.9
Python Version: 2.7.11
OS and version: macOS 10.12.5

## Actual behavior
When searching class name existing in my project I am getting "Definition not found for 'User'"
## Expected  behavior
"User" class should be in the results.
## Steps to reproduce:  
-  CMD + Shift + P
-  search for "Go to Python Object" command

**Comment by DonJayamanne** [comment]
Try using ```Search Workspace Symbols```.
Go to Python Object works for packages.
