### ISSUE TITLE
[request] alternative way of displaying docstrings when inline view of them does not fit on one screen

### ISSUE THREAD

**Issue by JobLeonard** [DonJayamanne/pythonVSCode#113]
This isn't really the plugin's fault - numpy's documentation is just that extensive - but it is still somewhat annoying:

![screenshot from 2016-05-06 15-14-57](https://cloud.githubusercontent.com/assets/259840/15074174/e761ec2c-139d-11e6-80a7-1b5f92e9ecb1.png)

(don't be deceived by the selection, my cursor is hovering over `sum`)

Of course the current solution is to just google `numpy sum` to [find the documentation](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.sum.html), which works. Still, compared to a functional in-line documentation or even something like *right click -> open documentation to the side*, that takes me out of the flow of programming.

**Comment by DonJayamanne** [comment]
Good idea, thanks.

**Comment by DonJayamanne** [comment]
Resolved in latest build
