### ISSUE TITLE
F5 debugger for Python does not pick up the fact it's Python3!

### ISSUE THREAD

**Issue by weinand** [DonJayamanne/pythonVSCode#1130]
_From @programmin1 on July 29, 2017 6:28_

- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:26:08.116Z)
- OS Version: Linux x64 4.10.0-28-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.6.9

---

Steps to Reproduce:

1. Run this simple script ("./test.py") and it will fail, showing that it correctly is trying python3:
```
#! /usr/bin/env python3
print( "hello" )
import urllib2
print( "success")

```
2. Press F5 and note it is not stopping, not actually debugging in python3 despite the first line pointing to python3!

_Copied from original issue: Microsoft/vscode#31698_

**Comment by duxbuse** [comment]
I even changed the user setting to use the python launcher version of the shell and when "start with out debugger" or "run python file in terminal" it recognizes the shebang. But pressing F5 for some reason still ignores the different python path.

**Comment by DonJayamanne** [comment]
This is a known issue, currently you need to manually define the python interpreter.
