### ISSUE TITLE
Debugger spuriously stops on exceptions when pythonPath contains ../

### ISSUE THREAD

**Issue by zneak** [DonJayamanne/pythonVSCode#1136]
## Environment data
VS Code version:  Version 1.14.2 (1.14.2)
Python Extension version:  0.6.9
Python Version:   Python 2.7.10
OS and version:    macOS Sierra 10.12.4

## Steps to reproduce:  

- Create a virtual env anywhere and activate it.
- Create a "src" directory in the virtual env directory.
- Create a Python script inside src whose content is `import argparse`
- Open the "src" folder in Visual Studio Code to make it a workspace
- Set `python.pythonPath` to `${workspaceRoot}/../bin/python`
- Enable the "Uncaught Exceptions" breakpoint
- Open the Python script in Code and start debugging it with the default launch command, and continue from the initial breakpoint

## Expected  behavior

The script terminates immediately.

## Actual behavior

The debugger spuriously stops multiple times inside of `re` support scripts for index errors.

## Logs
Output from ```Python``` output panel: (empty)   
Output from ```Console window``` (Help->Developer Tools menu): (empty)

## Workaround

It works great when you don't use .. in the pythonPath setting (for instance, by specifying an absolute path).

**Comment by DonJayamanne** [comment]
TODO: Try and resolve ".."

**Comment by DonJayamanne** [comment]
@zneak I'm unable to replicate this issue. Please could you provide the sample code.

**Comment by zneak** [comment]
Will a zipped workspace do?

**Comment by DonJayamanne** [comment]
Yes please

**Comment by zneak** [comment]
Unzip [pythonVSCode-issue1136.zip](https://github.com/DonJayamanne/pythonVSCode/files/1301992/pythonVSCode-issue1136.zip) in /tmp (virtualenvs are path-sensitive). I'm mostly repeating what I already said, but here goes.

**Before you run the binaries** in the zip file, you need to know that for some reason, the code signature on the Python executable included in the virtualenv is **incorrect**. I have not investigated the situation yet. `virtualenv` created it that way.

The virtualenv was created with these commands:

```bash
$ cd /tmp
$ virtualenv pythonVSCode-issue1136
New python executable in /private/tmp/pythonVSCode-issue1136/bin/python
Installing setuptools, pip, wheel...done.
$ mkdir pythonVSCode-issue1136/src
```

Machine software version info:

```bash
$ sw_vers -productVersion
10.12.6
$ python --version
Python 2.7.10
$ virtualenv --version
15.1.0
```

(this should be the stock Python install on macOS)

Then I opened the src directory with Visual Studio Code as a workspace, and created the "main.py" file (contains `import argparse` only), and created .vscode/settings.json (contains only `{"python.pythonPath": "${workspaceRoot}/../bin/python"}`).

Hit F5 on `main.py`, then enable the "Uncaught Exceptions" breakpoint, then hit Continue. The debugger stops at /private/tmp/pythonVSCode-issue1136/lib/python2.7/sre_parse.py:144, "IndexError, list index out of range".

The issue goes away if you replace `python.pythonPath` with `/tmp/pythonVSCode-issue1136/bin/python`.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#154

**Comment by leszekeljasz** [comment]
@DonJayamanne I'm experiencing a very similar issue without using `../` anywhere in the path, but I use virtualenvs. Debugging is impossible when breaking on `Uncaught Exception` is enabled - debugger keeps breaking inside `re` module. I'm not sure if I should open a separate bug report?

Super simple to reproduce, just set the interpreter to the venv's one and start debugging:

```
#!/Users/leszek/code/python-venvs/testenv/bin/python
# -*- coding: UTF-8 -*-

import json

foo = "bar"
print mistake     # should break here
print foo
```
Instead of breaking on 7th line, it breaks inside `re`, which is used by `json` imported on 4th line.
```
@mbp:~$ virtualenv --version
15.1.0

@mbp:~$ . code/python-venvs/testenv/bin/activate

(testenv) @mbp:~$ which python
/Users/leszek/code/python-venvs/testenv/bin/python

(testenv) @mbp:~$ python --version
Python 2.7.14
```

If I use `/usr/local/bin/python2` as my interpreter, it's working great, same python version:
```
(testenv) @mbp:~$ deactivate

@mbp:~$ which python2
/usr/local/bin/python2

@mbp:~$ python2 --version
Python 2.7.14
```

VSCode Version 1.19.1 (1.19.1)

I'm on MacOS. Please let me know if I should open a separate bug report... I feel like this might be related...

Thanks,
Leszek

**Comment by DonJayamanne** [comment]
@leszekeljasz please create a separate (new) issue on the Microsoft repo. The extension is now maintained in the Microsoft fork. I'll look into your issue from there.

**Comment by leszekeljasz** [comment]
Thank you @DonJayamanne for such a quick reply, I just created the bug report: https://github.com/Microsoft/vscode-python/issues/490
