### ISSUE TITLE
Debugger does not stop for uncaught Python exceptions raised from native code

### ISSUE THREAD

**Issue by zneak** [DonJayamanne/pythonVSCode#1137]
## Environment data
VS Code version:  Version 1.14.2 (1.14.2)
Python Extension version:  0.6.9
Python Version:   Python 2.7.10
OS and version:    macOS Sierra 10.12.4

## Actual behavior

The debugger does not stop when an uncaught exception is raised from native code, even if the breakpoint on "uncaught exceptions" is set.

## Expected  behavior

The debugger should probably stop wherever looks the most appropriate (probably on the most recent Python stack frame).

## Steps to reproduce:  
-  Install Cython
-  Create an "ext.pyx" file that only contains `raise KeyError("oopsie")`
- [Build extension with Cython](http://cython.readthedocs.io/en/latest/src/quickstart/build.html#building-a-cython-module-using-distutils), then copy the shared object to a place that you can easily import it from (like the source folder)
- From VS Code, create and run a Python script that imports said extension

## Logs
Output from ```Python``` output panel: (traceback ...)  
Output from ```Console window``` (Help->Developer Tools menu): (empty)

**Comment by zneak** [comment]
Looks like the debugging support comes from IPython. Let me know if I should see help there instead.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#155
