### ISSUE TITLE
How to write a code snippet generating current time?

### ISSUE THREAD

**Issue by Kongsea** [DonJayamanne/pythonVSCode#1138]
## Environment data
VS Code version:  1.14
Python Extension version:  0.7
Python Version:   2.7
OS and version:    Ubuntu 14.04

I want to write a code snippet used to write the time when I write the code.
For example, I define a code snippet named timeit, and then when I write timeit, it will generate:

> write on 2017.8.4

However, I dont know how to generate the current time. Please give me some advice. Thank you.

**Comment by DonJayamanne** [comment]
Sorry, but I am not aware of any way this can be done in vscode. Also you might want to raise this question on the vscode repo.
