### ISSUE TITLE
Feature Request: Automatic Environment Activation in Terminal

### ISSUE THREAD

**Issue by threecgreen** [DonJayamanne/pythonVSCode#1139]
## Current behavior
Every time I open the built-in terminal in VSCode, I have to remember to activate the project's Python environment.

## Expected behavior
I'd like ```$ source activate my_env``` for conda or ```$ source bin/activate``` for virtualenv to run at VSCode terminal startup if I have selected an Python interpreter other than the system default.

**Comment by smcstewart** [comment]
So, if you have a local `.vscode/settings.json` with the `python.venvPath` set, then the terminal could automatically source it. I'd +1 that.

**Comment by DonJayamanne** [comment]
You can use the command, 'Python REPL'.
Unfortunately there is no easy to change the external terminal.

**Comment by MatthewGieger** [comment]
@smcstewart were you referring to an external terminal or the integrated vscode terminal?

**Comment by smcstewart** [comment]
@MatthewGieger Yeah, the integrated vscode terminal. The external terminal makes no sense and I can manage that myself. However, if I'm inside an existing Python project, when I open the integrated terminal, it'd be great to automatically source the virtualenv. I thought this was what @threecgreen was getting at.

**Comment by MatthewGieger** [comment]
@smcstewart  Yes, agreed. I think that was indeed what @threecgreen  was getting at. 

@DonJayamanne Do you know if this has been implemented in any way? Also, what do you mean about using the "Python REPL" command? Could you give a quick example?

**Comment by fourierserious** [comment]
In User/Workspace Settings, I use

    "terminal.integrated.shellArgs.linux": [
        "--rcfile", "/home/jacob/miniconda3/envs/vscode/etc/bash.bashrc"
    ]

with the following in my bash.bashrc

    source /home/jacob/.bashrc
    source /home/jacob/miniconda3/bin/activate vscode

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#383
