### ISSUE TITLE
How to run Python script?

### ISSUE THREAD

**Issue by klonuo** [DonJayamanne/pythonVSCode#114]
So, I have two opened Python scripts (in "Working files", w/o adding each script folder in vscode).

When I type "python" in the palette, I just see actions for sorting imports and running unit tests.
When I type "run" I see:

- `Debug:Run`, which after execution complains:
> Command 'Debug: Run' is not enabled in the current context.

- `Tasks: Configure task runner`, which after execution complains:
> Tasks are only available on a workspace folder.

I guess this must be possible, just I cant see it, right?

**Comment by DonJayamanne** [comment]
Sorry, but this isn't possible. The scripts need to belong to the working folder and the launch.json file needs to be configured accordingly.
