### ISSUE TITLE
Run Isort when formatOnSave is on

### ISSUE THREAD

**Issue by eMerzh** [DonJayamanne/pythonVSCode#1140]
Hi, 
many many thanks for this extension, it's really great.
I use format on save and been pretty happy about it.
But I also wanted to do Isort on save, could it be possible to add both of the tools or smth ?

Thanks a lot

**Comment by DonJayamanne** [comment]
Unfortunately, not at this stage. Will look into this later as a feature request.

**Comment by eMerzh** [comment]
Thanks a lot :)

i'll follow the updates ;)

**Comment by threaz** [comment]
Is there any other way to run your `sort imports` command on save? I mean using some kind of hook etc.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#156
