### ISSUE TITLE
Feature request: dict auto completion

### ISSUE THREAD

**Issue by thernstig** [DonJayamanne/pythonVSCode#1145]
## Environment data
VS Code version: 1.14.2
Python Extension version: 0.7.0 (3 August 2017)
Python Version: 3.6.1
OS and version: Windows 10 Home, Version 1703, OS-version 15063.483

## Actual behavior
When pressing ctrl+space on a defined dict, no suggestions are shown for the keys in the dict.

## Expected  behavior
If I use a defined dict in my file I want it to suggest the keys to select automatically.

Here is an example of what I mean:

![dict_auto_complete](https://user-images.githubusercontent.com/30827238/29113653-f1b88b4a-7cf1-11e7-8f21-17a039343360.png)

**Comment by gandhis1** [comment]
You should post this in the Jedi repository. What I can tell you is that Jedi and even IPython are static code analyzers, not evaulators. What you are asking for requires static code evaluation which is extremely hard to come by in Python. Unlikely it will be possible.

**Comment by DonJayamanne** [comment]
Agreed, please raise this as a feature request in the [Jedi repository](https://github.com/davidhalter/jedi)

**Comment by thernstig** [comment]
Appreciate the quick response. I have raised this issue here:
https://github.com/davidhalter/jedi/issues/951
