### ISSUE TITLE
Linter stopped working

### ISSUE THREAD

**Issue by janhancic** [DonJayamanne/pythonVSCode#1146]
## Environment data
VS Code version:  1.15.0-insider Commit 2c3e2c291c515619f64e7c9cddf14c565b7f3d92
Python Extension version:  0.7.0
Python Version: 3.5.2
OS and version: Ubuntu 16.04

## Actual behavior
Nothing happens when my code has lint errors

## Expected  behavior
I should get lint warnings/errors as usuall

## Steps to reproduce:  
n/n

## Logs
Output from ```Python``` output panel  
```
no output
```   

Output from ```Console window``` (Help->Developer Tools menu)
```
no output
```

The linter literally stopped working overnight. I checked my workspace settings and my user settings and I definitely have the flake8 linter enabled.
Unfortunately this is similar #838 in that there's really no useful output anywhere, it just doesn't work. Except this time it's not a sneaky setting :)

**Comment by fredrikaverpil** [comment]
I just came here to check if someone else had issues with their linter, as I just noticed nothing is being linted anymore.

I'm testing this on both today's insider and vscode v1.14.2 with pythonVSCode 0.7.0.

Here's my linting setup:

```json
    "python.pythonPath": "C:/Users/iruser/.conda/envs/pythondev_35/python.exe",
    "python.linting.pylintPath": "C:/Users/iruser/.conda/envs/pythondev_35/Scripts/pylint.exe",
    "python.linting.pep8Path": "C:/Users/iruser/.conda/envs/pythondev_35/Scripts/pep8.exe",
    "python.formatting.autopep8Path": "C:/Users/iruser/.conda/envs/pythondev_35/Scripts/autopep8.exe",
    "python.formatting.yapfPath": "C:/Users/iruser/.conda/envs/pythondev_35/Scripts/yapf.exe",

    // Python, general
    "python.linting.pylintEnabled": true,
    "python.linting.flake8Enabled": false,
    "python.linting.pep8Enabled": true,
    "python.linting.lintOnTextChange": true,
    // "python.formatting.provider": "autopep8",
    "python.formatting.provider": "yapf",
    "python.formatting.yapfArgs": [
        "--style",
        "{based_on_style: chromium, indent_width: 4}"
    ],
```

All the paths to `python.exe`, `pylint.exe` etc works just fine when executed in Powershell.

After having uninstalled pythonVSCode and re-installed it again, pep8 linting started working. But pylint doesn't work.

Also, before the uninstall/re-install I noticed my right-click menu didn't show the "Go to definition" and pythonVSCode related menus. Odd.

**Comment by janhancic** [comment]
Reinstalling doesn't fix the issue for me.

**Comment by DonJayamanne** [comment]
Will look into this asap.

**Comment by DonJayamanne** [comment]
@janhancic 
Does your workspace settings.json contain any python specific settings (settings beginning with "python")?  
Similarly does your user settings.json contain any python specific settings?  
If so, please provide just those details.

**Comment by DonJayamanne** [comment]
@fredrikaverpil
Please could you disable all linters except for pylint and test the linting?  
Also, check the output of the ```python``` output log. There should be something there.  
Finally if there's nothing there, please go into ```Help->Toggle Developer Tools``` and let me know what errors (red) are displayed in the ```Console``` window.

FYI - This works without any issues on my windows PC using the same setup.

**Comment by fredrikaverpil** [comment]
@DonJayamanne ok, will try now. I forgot to mention that I also have a settings.json in my current project:

```json
{
"python.pythonPath": "${workspaceRoot}/../../../skalman/condaenvs/skalman_standalone_py35/",
"python.linting.pylintArgs": ["--disable=E0611", "--init-hook=~/skalman/condaenvs/skalman_standalone_py35/Lib/site-packages", "--init-hook=~/skalman/condaenvs/skalman_standalone_py35/lib/python3.5/site-packages"],

    "python.autoComplete.extraPaths": [
        // Maya 2017, OS X,
        //

        "/Applications/Autodesk/maya2017/Maya.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python27.zip",
        "/Applications/Autodesk/maya2017/Maya.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python2.7",
        "/Applications/Autodesk/maya2017/Maya.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python2.7/plat-darwin",
        "/Applications/Autodesk/maya2017/Maya.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python2.7/plat-mac",
        "/Applications/Autodesk/maya2017/Maya.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python2.7/plat-mac/lib-scriptpackages",
        "/Applications/Autodesk/maya2017/Maya.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python2.7/lib-tk",
        "/Applications/Autodesk/maya2017/Maya.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python2.7/lib-old",
        "/Applications/Autodesk/maya2017/Maya.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python2.7/lib-dynload",

        "/Applications/Autodesk/maya2017/Maya.app/Contents/Frameworks/Python.framework/Versions/Current/lib",
        "/Applications/Autodesk/maya2017/Maya.app/Contents/Frameworks/Python.framework/Versions/Current/bin",
        "/Applications/Autodesk/maya2017/Maya.app/Contents/Frameworks/Python.framework/Versions/Current/Python",

        // Classes
        "/Applications/Autodesk/Maya2017/devkit/other/pymel/extras/completion/py",
        "/Applications/Autodesk/maya2017/Maya.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python2.7/site-packages"

        ]

}
```

**Comment by fredrikaverpil** [comment]
Seems like linting works fine when I don't use my settings.json file...

**Comment by fredrikaverpil** [comment]
Ah...

```
##########Linting Output - pylint##########

Traceback (most recent call last):
  File "c:\users\iruser\.conda\envs\pythondev_35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\iruser\.conda\envs\pythondev_35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\iruser\.conda\envs\pythondev_35\Scripts\pylint.exe\__main__.py", line 9, in <module>
  File "c:\users\iruser\.conda\envs\pythondev_35\lib\site-packages\pylint\__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "c:\users\iruser\.conda\envs\pythondev_35\lib\site-packages\pylint\lint.py", line 1148, in __init__
    'load-plugins': (self.cb_add_plugins, True),
  File "c:\users\iruser\.conda\envs\pythondev_35\lib\site-packages\pylint\lint.py", line 1100, in preprocess_options
    cb(option, val)
  File "c:\users\iruser\.conda\envs\pythondev_35\lib\site-packages\pylint\lint.py", line 1361, in cb_init_hook
    exec(value) # pylint: disable=exec-used
  File "<string>", line 1
    ~/skalman/condaenvs/skalman_standalone_py35/Lib/site-packages
     ^
SyntaxError: invalid syntax
```

**Comment by janhancic** [comment]
@DonJayamanne I've only got python related settings in my workspace settings:

```
"python.pythonPath": "/usr/bin/python3.5",
  "python.linting.pylintEnabled": false,
  "python.linting.flake8Enabled": true,
```

**Comment by fredrikaverpil** [comment]
@DonJayamanne So all of a sudden, it seems this line is no longer valid in my project's settings.json:

```
"python.linting.pylintArgs": ["--disable=E0611", "--init-hook=~/skalman/condaenvs/skalman_standalone_py35/Lib/site-packages", "--init-hook=~/skalman/condaenvs/skalman_standalone_py35/lib/python3.5/site-packages"],
```

I tried the following with the same kind of error as posted previously. The path exists.

```
"python.linting.pylintArgs": ["--disable=E0611", "--init-hook=C:/Users/iruser/skalman/condaenvs/skalman_standalone_py35/Lib/site-packages"],
```

```
"python.linting.pylintArgs": ["--disable=E0611", "--init-hook=C:\\Users\\iruser\\skalman\\condaenvs\\skalman_standalone_py35\\Lib\\site-packages"],
```


Changing it into the following, pylint now works fine again:

```
"python.linting.pylintArgs": ["--disable=E0611"],
```

It was _ages ago_ I added in those pylint args. There must be some other issue also affecting @janhancic which indirectly triggers this issue too...?

**Comment by DonJayamanne** [comment]
@janhancic
Please could you confirm there are no errors logged in the ```Python``` output channel.  
Finally if there's nothing there, please go into Help->Toggle Developer Tools and let me know what errors (red) are displayed in the Console window.

**Comment by janhancic** [comment]
I get this in the python output:

```
##########Linting Output - flake8##########
"pycodestyle" requested unknown parameters causing 'FileProcessor' object has no attribute 'previous_unindented_logical_line'
```

**Comment by DonJayamanne** [comment]
Looks like this is an issue with Flake8 and PydocStyle.
Please check this and similar threads:
https://gitlab.com/pycqa/flake8/issues/246  
https://gitlab.com/pycqa/flake8/issues/248

**Comment by janhancic** [comment]
Amazing, thanks, and sorry, I should have done more digging before opening an issue here.

**Comment by DonJayamanne** [comment]
That's alright, problem solved that's what's important, doesn't matter how we got there.
