### ISSUE TITLE
vscode python program output is not expected

### ISSUE THREAD

**Issue by CHENGWEI001** [DonJayamanne/pythonVSCode#115]
VSCode Version:1.00
OS Version:Windowns7 64bt
Steps to Reproduce:

in below file , executing test.py in :
[testpy.zip](https://github.com/DonJayamanne/pythonVSCode/files/254070/testpy.zip)

assuming there is a line change between "hello"s, for example , if I run in command window, or other python IDE, I would see output like this : expected_output
![expected_output](https://cloud.githubusercontent.com/assets/13721617/15099896/f0edd4c4-1517-11e6-897e-e4fe75287d30.PNG)

However , if I run this test.py in vscode python , I can't see empty lines between "hello"s , wondering any thing I missing in the setting file?
Best Regards
Jack

**Comment by DonJayamanne** [comment]
Hi, I have just tried this on Windows 8 64 bit and it works as expected.
Please could you ensure you have the latest version (not sure if this makes any difference) 
Also what version of Python are you using?

**Comment by CHENGWEI001** [comment]
Thx for your prompt response , I just tried another Windowns 8 64 bit machine , I see the same output , basically there is no breakline between "hello"s in output window , so in your side , you don't see this ?
![image](https://cloud.githubusercontent.com/assets/13721617/15102611/4827a2cc-1556-11e6-8c7b-ca98a4d693d7.png)

Best Regards
Jack

**Comment by go2sh** [comment]
I have the same issue. Also spaces will be trimmed.

**Comment by go2sh** [comment]
LGTM

**Comment by DonJayamanne** [comment]
Thanks

**Comment by go2sh** [comment]
@DonJayamanne Thank you for fixing it. :)
