### ISSUE TITLE
Also run pip/conda as appropriate based on requirements.txt/environment.yml file existing in the workspace

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#1150]

**Comment by brettcannon** [comment]
So here is my thought of what a "create environment" command could do ...

1. Choose an interpreter 
    1. If one already selected, great! 
    2. Otherwise prompt user to select an interpreter 
2. Anaconda 
    1. Create environment: `conda create –name $ENV –yes –file environment.yml` 
        - Should we match on *.yml and prompt to disambiguate? 
    2. Create activated terminal 
        - Windows: `activate $ENV` 
        - UNIX: `source activate $ENV` 
3. Pip 
    1. Create environment 
        - Python < 3.3: `virtualenv --python $PYTHON $ENV` 
        - Python >= 3.3: `python3 –m venv $ENV` 
    2. Create activated terminal 
        - PS 
        - Cmd.exe 
        - Bash 
        - csh 
        - fish 
    3. Install dependencies 
        1. If multiple matches for *requirements*.txt, prompt user to choose 
        2. In activated terminal: `pip install –upgrade –r $REQUIREMENTS` 
4. Make the created environment the selected interpreter for the project


IOW, simplify the following down to a command with at most 2 prompts (environment name and requirements/environment file):
```shell
$ python3 –m venv env 
$ source env/bin/activate 
$ pip install –r requirements.txt 
```
- End up with an activated terminal
- Set the interpreter for the project set to the newly-created environment.

Not sure if this is common enough to warrant implementing, though. Would this be useful in a teaching environment with heterogeneous OSs where people might mess up one of these steps? Or in that instance do we just say "use a shell script" if they are all on the same kind of system or "just explain what you're doing" when it's a mixed set of OSs?

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#160
