### ISSUE TITLE
RFE - List installed, third-party packages in the Explorer View (with ability to add/remove/update, etc)

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#1153]
- Ability to detect packages installed while vs code is running
- Ability to detect packages installed but not listed in requirements & vice versa

**Comment by JGH1000** [comment]
As in python packages like in PyCharm? Wow.. As long as it works with conda and pip will be amazing.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#163
