### ISSUE TITLE
Cwd setting ignored for the purposes of PYTHONPATH

### ISSUE THREAD

**Issue by zneak** [DonJayamanne/pythonVSCode#1156]
## Environment data
VS Code version: 1.14.2 (1.14.2)  
Python Extension version: 0.7.0  
Python Version: 2.7.10  
OS and version: macOS 10.12.4  

When trying to run a project with a structure in which the main script isn't at the root of the project, Python's `sys.path` only includes the directory of the script that is being debugged, not the current working directory. This can prevent imports from working correctly.

You can add the entire project using the `PYTHONPATH` environment variable, but doing so comes with major debugging downsides: you apparently cannot step through files not prefixed with the first entry of `sys.path`.

## Steps to reproduce:  
-  Create Python project in VS Code
-  Create the following directory structure:
    - a/b.py: `print "hello world"`
    - b/c.py: `import a.b`
- Create a launch configuration that launches "b/c.py" (with its absolute path)
- It will fail to find the `a.b` module.
- Add `${workspaceRoot}` to your `PYTHONPATH` environment variable
- `a.b` can now be found, but it won't be possible to step through it in the debugger (presumably because it looks like library code to it).
- Changing the "cwd" setting to `${workspaceRoot}` has no effect on `sys.path`.

## Logs
Output from ```Python``` output panel: none
Output from ```Console window``` (Help->Developer Tools menu): none

**Comment by DonJayamanne** [comment]
How have you added the workspace path to pythonpath Env variable?
Please provide your launch.json.

**Comment by zneak** [comment]
This turns out to be shoddily reported. I have made another workspace with the same launch.json and settings.json and the test structure that I suggested, and it works just fine. I have no idea what's wrong with my actual project.

Symptoms remain:

* I can put breakpoints in my code and they're hit correctly
* I can't pause execution (it just keeps running)
* I can't step over code (it does the same as continuing)

It's about 10x slower than running it regularly, which I think can be attributed to the debugger, but I don't really know. Because of that (my program already takes about 3 minutes to complete), I'll fall back to pdb, so if I'm a unique case, you can probably close this issue.
