### ISSUE TITLE
[Enhancement] PyCharm-like "where am I in the hierarchy?" feature

### ISSUE THREAD

**Issue by marmistrz** [DonJayamanne/pythonVSCode#1158]
There's a really handy feature (they only one from PyCharm I'm missing). If I'm in a deeply nested block, PyCharm will tell me that 
```
for i in list:
  # very
  # long
  # code
  if condition:
      # more 
      # long
      # code
      while...: 
  while....:
       if...:
```
that the current cursor position is positioned in hierarchy that way: 
` for i in list | if condition | while ... `

Is it within the scope of this extension to provide such capabilities? I can imagine this being useful in different languages than Python but I know this from PyCharm. 

I suggested this in the main vscode issue tracker too.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#164
