### ISSUE TITLE
Feature request: individual launch support

### ISSUE THREAD

**Issue by nlmalc** [DonJayamanne/pythonVSCode#1161]
Maybe this is a documentation issue (and my lack of understanding), or maybe it's an actual feature request: how do I work with multiple Python scripts in different folders? Can launch.json be configured for different scripts with regards to the command line parameters to invoke them with, and (excepting my previous feature request) can it also be configured to use different versions of Python with different scripts?

## Environment data
VS Code version:  Version 1.15.0 (1.15.0)

Python Extension version:  
Python Version:   2.7.10 and 3.6.2
OS and version:   macOS 10.12.6

**Comment by DonJayamanne** [comment]
Yes, this is possible, just edit your launch.json file with different entries for each file.
