### ISSUE TITLE
The 'Details' page for the extension just tries to load forever

### ISSUE THREAD

**Issue by Eldaw** [DonJayamanne/pythonVSCode#1162]
Currently, clicking on the extension 'Python 0.7.0' in the list of extensions, the pane on the right tries forever to load the content for the Details page.

**Comment by DonJayamanne** [comment]
Does it work for other extension?  
This functionality is not part of the extension, buy party of vscode itself.

**Comment by Eldaw** [comment]
Yes, it was working fine for all other extensions at the time. Only the Python extension was affected. But it's working now. It must have been a temporary outage of whatever resource is serving up the contents of the Details page.
