### ISSUE TITLE
"Run selection/line in Python terminal" does not copy the code into the terminal from the start of the selection

### ISSUE THREAD

**Issue by dalyIsaac** [DonJayamanne/pythonVSCode#1163]
## Environment data
VS Code version:  1.15.0
Python Extension version:  0.7.0
Python Version:   3.6.1
OS and version:    Windows 10 (OS Build 16257.1) Pro

## Actual behavior
After selecting an area of code and the option to "Run selection/line in Python terminal", code is copied into the terminal, **but not from the start of the selection**.
![2017-08-12_12-32-43](https://user-images.githubusercontent.com/17995621/29236217-bdd57a74-7f5b-11e7-93ba-73f3b88eaec1.gif)
Repeatedly trying to "Run selection/line in Python terminal", after closing the terminal each time results in the code copied into the terminal starting at different points each time. 
![2017-08-12_12-42-08](https://user-images.githubusercontent.com/17995621/29236235-04326d38-7f5c-11e7-8223-26b29fe0e647.gif)
## Expected  behavior
All the code is copied into the Python terminal
## Steps to reproduce:  
-  Select some code
-  Right click
- Click "Run selection/line in Python terminal"

## Logs
Output from ```Python``` output panel  
N/A
Output from ```Console window``` (Help->Developer Tools menu)
N/A

**Comment by dalyIsaac** [comment]
This only occurs when the integrated shell is set to Powershell. If it's set to cmd.exe, it doesn't occur

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#174
