### ISSUE TITLE
[QUESTION] Coloring Django templates / Jinja

### ISSUE THREAD

**Issue by ajitid** [DonJayamanne/pythonVSCode#1165]
Does this extension provides coloring to Django templates and/or Jinja2? If yes, how?

**Comment by canarduck** [comment]
No it doesn't, but you could use [Jinja](https://marketplace.visualstudio.com/items?itemName=wholroyd.jinja) and [Django Template](https://marketplace.visualstudio.com/items?itemName=bibhasdn.django-html).

**Comment by DonJayamanne** [comment]
Thats correct.
An alternative is to install the extension [Python Extension Pack](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python-extension-pack).  
Its meant to contain some of the most popular VS Code extensions for Python development.
