### ISSUE TITLE
Howto "activate" local pyenv?

### ISSUE THREAD

**Issue by dakky** [DonJayamanne/pythonVSCode#1166]
## Environment data
VS Code version:  1.14
Python Extension version:  0.7.0
Python Version:   3.6.2
OS and version:    OSX

## Actual behavior
I created a project specific virtualenv in my workspace/venv/ (```python -m venv venv```)
vscode is configured to use this one:

settings.json:
```
{
  "python.pythonPath": "$workspaceRoot/venv/bin/python"
}
```
vscode asks to install pylint but does this to the GLOBAL pip modules and therefore does NOT detect the "locally" installed modules:
```
file: 'file:///Users/username/devzone/project/app/__init__.py'
severity: 'Fehler'
message: 'E0401:Unable to import 'flask''
at: '1,1'
source: 'pylint'
```

## Expected  behavior
there should be a possibility to "activate" the local virtualenv (```source venv/bin/activate```)

**Comment by wonbyte** [comment]
+1

**Comment by DonJayamanne** [comment]
Please confirm your virtual environment is "$workspaceRoot/venv/bin/python"

> vscode asks to install pylint but does this to the GLOBAL pip modules 

That's not true, The latest version of the extension will install pylint into your configured python environment. 
It uses the command python -m pip install pylint, where python will be replaced with the python interpreter configured.

Please confirm you have the latest version of the extension.

Also confirm you have sold installed in your virtual environment. Try running pylint manually.

**Comment by DonJayamanne** [comment]
Please reopen if it persists
