### ISSUE TITLE
visual results run off page

### ISSUE THREAD

**Issue by Goddard** [DonJayamanne/pythonVSCode#1170]
The visual results returned run off the page.  It seems a white container is in the results section, but images break out of the container and run off to the right.

**Comment by DonJayamanne** [comment]
What are you referring to?

**Comment by DonJayamanne** [comment]
Also please provide some screen samples of the issue.

**Comment by JGH1000** [comment]
Sounds like the issue reported some time ago for Jupyter plugin:
https://github.com/DonJayamanne/vscodeJupyter/issues/49

**Comment by DonJayamanne** [comment]
Closing this issue, will look into this in the Jupyter plugin
