### ISSUE TITLE
Still - very long usage of vscode make suggestion to lag sometime

### ISSUE THREAD

**Issue by Jeyanthinath** [DonJayamanne/pythonVSCode#1171]
1. use vscode python for verylong time without closing 
2. some time even the system is slow still the suggesstion while using `ctrl+space` is lagging and keep on loading 

It not occuring me for past two days.

Initial issue tracker for this same [#1072](https://github.com/DonJayamanne/pythonVSCode/issues/1072)

note: it is not occuring oftenly, but It happening very rarely

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#166
