### ISSUE TITLE
Missing typing tokens

### ISSUE THREAD

**Issue by iddan** [DonJayamanne/pythonVSCode#1172]
## Environment data
VS Code version:  1.15.1
Python Extension version:  0.7.0
Python Version:  Python 3.6.2
OS and version: macOS Sierra 10.12.5

## Actual behavior
Token type of typings is Other

## Expected  behavior
Token type of typings to be types

## Steps to reproduce:  
-  Add typings to a python code
-  Inspect TM Scopes

**Comment by DonJayamanne** [comment]
Sorry, but this doesn't make sense. Please could you be a bit more specific with some examples.

**Comment by iddan** [comment]
Token type is always Other:
<img width="372" alt="screen shot 2017-08-20 at 15 24 10" src="https://user-images.githubusercontent.com/12671072/29494847-b3fa4460-85bb-11e7-8268-6e388e26e0d8.png">
<img width="516" alt="screen shot 2017-08-20 at 15 24 27" src="https://user-images.githubusercontent.com/12671072/29494848-b3fd2a40-85bb-11e7-8198-36fd8c17c3bb.png">


<img width="511" alt="screen shot 2017-08-20 at 15 22 41" src="https://user-images.githubusercontent.com/12671072/29494833-7a67aeae-85bb-11e7-9a01-b78e4f3debe1.png">

**Comment by DonJayamanne** [comment]
Hi, looks like you're referring to syntax highlighting.
This isn't part of the extension, please report this on the [MagicPython](https://github.com/MagicStack/MagicPython) extension. They are the authors of the syntax highlighting (though they have a separate extension, they highlithing is used by vscode).
