### ISSUE TITLE
How to show tip for `from xxxx import ???`

### ISSUE THREAD

**Issue by eromoe** [DonJayamanne/pythonVSCode#1173]
## Environment data
VS Code version:  latest
Python Extension version: latest  
Python Version:   python 2.7
OS and version:   win7 x64

## Expected  behavior

After I enter `from sklearn.naive_bayes import ` , shows classes and functions I can import .

**Comment by jarshwah** [comment]
This works for me in my projects with different imports. I do have to hit `ctrl + space` to open the autocomplete helper though.

**Comment by eromoe** [comment]
`ctrl + space` has been taken by `Input Method` , change the shortcut solved that
