### ISSUE TITLE
Documentation request: WSL config instructions

### ISSUE THREAD

**Issue by tmcdonnell87** [DonJayamanne/pythonVSCode#1174]
## Environment data
VS Code version:  N/A
Python Extension version:  N/A
Python Version:   N/A
OS and version:    N/A

## Actual behavior
It appears with https://github.com/DonJayamanne/pythonVSCode/pull/1049 we finally have support for using VSCode with Windows Subsystem for Linux (WSL). This is excellent. That said, there is no official documentation about special configuration necessary to do so. From the PR, it appears a few batch files are necessary; however, it is not clear exactly what must be done for common use cases, such as:

- virtual environments
-- be able to run python/pylint with multiple projects open in different windows
- ipython notebooks

## Expected  behavior
Basic documentation necessary configuration, either in a WSL-specific section, or called out (searchable?) within the relevant feature settings where extra configuration is required.

**Comment by DonJayamanne** [comment]
Closing in favor of https://github.com/DonJayamanne/pythonVSCode/issues/534 (to add proper support for WSL)
