### ISSUE TITLE
Unexpected behavior of conditional break

### ISSUE THREAD

**Issue by prandelicious** [DonJayamanne/pythonVSCode#1175]
_From @prandelicious on August 23, 2017 4:26_

- VSCode Version: 1.16.0-insider
- OS Version: Windows 8.1 64-bit

Steps to Reproduce:

1. Create a Python for loop using enumerate():
```
values = ['Testing1', 'Testing2', 'Testing3']
for index, value in enumerate(values):
    test = index
    print(test, value)
```
2. Create a conditional break in line after `for index...` with value `index = 1`. Expected behavior is to break when the value of `index` is equal to 1. It breaks/stops at `index = 0`

_Copied from original issue: Microsoft/vscode#33001_

**Comment by prandelicious** [comment]
_From @weinand on August 23, 2017 8:31_

Please move this issue to the Python extension you are using. You can use this tool: https://github-issue-mover.appspot.com

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#167
