### ISSUE TITLE
Cursor moves to beginning of line automatically disrespecting current indentation

### ISSUE THREAD

**Issue by swarnendubiswas** [DonJayamanne/pythonVSCode#1177]
## Environment data
VS Code version:  15.1
Python Extension version:  0.7.0
Python Version:  3.5.4
OS and version: CentOS 7   

## Actual behavior
Typing enter to go to a new line, causes the cursor to automatically move to the beginning of the line disrespecting the current indentation. 

## Expected  behavior
Cursor should stay at the desired indentation.

## Steps to reproduce:  
-  Hit enter from an indented code block.
-  

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
Please provide more information with examples

**Comment by swarnendubiswas** [comment]
Please see the following picture: Say the cursor is at the end of line 155. When I press enter, I would expect the cursor to be at the desired column in line 156. The column numbers are not visible, but the desired column in this context is below the first occurrence of character 'm' (from line 155).

What happens is that the cursor stays at the desired column for about a second, and then moves to the beginning of line 156 (i.e., extreme left). This is annoying since one has to manually readjust the indent.

![screenshot from 2017-08-24 09-46-52](https://user-images.githubusercontent.com/7343807/29681346-041326d8-88cd-11e7-8619-257b2757398f.png)

Does this help?

**Comment by gandhis1** [comment]
I don't experience this. Can you provide a small source file where the issue occurs?

**Comment by swarnendubiswas** [comment]
@gandhis1 I tried disabling all my Code customizations. For me, it seems adding `"editor.formatOnSave": true` is triggering the issue. Could you try it out?

**Comment by DonJayamanne** [comment]
@swarnendubiswas unfortunately I too don't experience this issue on my Mac and Windows. 
Please confirm you are still experiencing this issue.

**Comment by swarnendubiswas** [comment]
Actually I was testing this only yesterday. Visual Studio Code with extensions disabled works fine, but I still face the issue with the Python extension. Here is my related config:

```
    "python.formatting.formatOnSave": true,
    "python.formatting.provider": "yapf",
    "python.formatting.yapfArgs": [
        "--style",
        "{based_on_style: google, column_limit:120}"
    ],
    "python.pythonPath": "/workspace/sbiswas/software/Python-3.5.4/build/bin/python3",
    "python.autoComplete.addBrackets": true,
    "python.linting.enabled": true,
    "python.linting.lintOnSave": true,
    "python.linting.flake8Enabled": true,
    "python.linting.pylintEnabled": false,
    "python.linting.pep8Enabled": false,
    "python.linting.pydocstyleEnabled": false,
    "python.venvPath": "/workspace/sbiswas/tmp/.virtualenvs",
```
Could it be related to the formatter? I will test it out disabling the formatters.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#168
