### ISSUE TITLE
No linting, possibly ctags/xcode error

### ISSUE THREAD

**Issue by cmac4603** [DonJayamanne/pythonVSCode#1178]
## Environment data
VS Code version: Version 1.15.1 (1.15.1) 
Python Extension version:  0.7.0
Python Version:   
OS and version:  Mac OS X 10.11.4  

## Actual behavior
I'm unable to see any linting/pep8/pep257 errors
## Expected  behavior
Notification of the above

## Steps to reproduce:  
-  
-  

## Logs
Output from ```Python``` output panel  
```
----------Generating Tags----------
ctags --options=/Users/cmacrae/.vscode-insiders/extensions/donjayamanne.python-0.7.0/resources/ctagOptions --languages=Python --exclude=**/site-packages/** -o /Users/cmacrae/Documents/1.Code/.vscode/tags .
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ctags: illegal option -- -
usage: ctags [-BFadtuwvx] [-f tagsfile] file ...
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
index.js:26 renderer did not receive lazyEnv in time
(anonymous) @ index.js:26
extensionHost.ts:383 [Extension Host] vscode-icons is active!
extensionHost.ts:383 [Extension Host] Sync : Connected with user : 'cmac4603'
extensionHost.ts:383 [Extension Host] Sync : File Path For Summary Page : /Users/cmacrae/Library/Application Support/Code - Insiders/User/syncSummary.txt
```

**Comment by DonJayamanne** [comment]
@cmac4603 
- What version of Python are you using? 
- Do you have a virtual env? 
- Have you disabled any of the linters? (check both, your User and Workspace settings files)

**Comment by DonJayamanne** [comment]
Please reopen if it persists, along with requested info.

**Comment by gilmoreg** [comment]
I have this issue as well. Not sure if the two are related but I am also not getting any linting and have the same ctags error.
VSCode output for Python:
```
----------Generating Tags----------
ctags --options=/Users/grayson/.vscode/extensions/donjayamanne.python-0.7.0/resources/ctagOptions --languages=Python --exclude=**/site-packages/** -o /Users/grayson/Projects/legocollector/server/.vscode/tags .
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ctags: illegal option -- -
usage: ctags [-BFadtuwvx] [-f tagsfile] file ...
```

I am not running a virtualenv. I have experimented with changing the pep8 path to no avail.
Current vscode config:
```
{
    "python.linting.pep8Enabled": true,
    "python.linting.pylintEnabled": false,
    "python.linting.pep8Path": "pycodestyle"
}
```
The issues were the same when pep8Path was set to default.
