### ISSUE TITLE
Linting hover information not showing up

### ISSUE THREAD

**Issue by prandelicious** [DonJayamanne/pythonVSCode#1179]
## Environment data
VS Code version:  **1.16.0-insider (Commit 936fc3fdd9e5a47c5a626eec1ed5d81cead82d08)**
Python Extension version:  **0.7.0**
Python Version:  **Python 3.6.2 :: Continuum Analytics, Inc.**
OS and version:  **Windows 10 Creators Update**

## Actual behavior
The pylint issue is not displayed when hovering over text with squiggly lines.

## Expected  behavior
Pylint issue is displayed when hovering over text with squiggly lines.

## Steps to reproduce:  
-  Install pylint
-  Create code that is non-PEP8 compliant to produce text with squiggly lines beneath

## Logs
Output from ```Python``` output panel  
```
##########Linting Output - pylint##########
************* Module find_images_mp
8,0,warning,W0611:Unused pprint imported from pprint as pp
------------------------------------------------------------------
Your code has been rated at 9.57/10 (previous run: 9.57/10, +0.00)
No config file found, using default configuration
```   
![snip_20170824215754](https://user-images.githubusercontent.com/5356451/29670400-1d912884-8919-11e7-9322-2caed3b75362.png)

**Comment by TiemenSch** [comment]
This could just as well be an error from using a VSCode insider build. I'm running 1.15.1 and that's working just fine. 

Would you mind checking whether it persists on the regular build?

**Comment by prandelicious** [comment]
Yes, I agree with you. It was fixed on a subsequent build.
