### ISSUE TITLE
Not support "Run" mode

### ISSUE THREAD

**Issue by perfectspr** [DonJayamanne/pythonVSCode#118]
> In  addition to debugging a program, VS Code supports running the program. The Run action is triggered with Ctrl+F5 and uses the currently selected launch configuration. Many of the launch configuration attributes are supported in 'Run' mode. VS Code maintains a debug session while the program is running and pressing the Stop button terminates the program.

> Please note: The Run action is always available, but a debugger extension has to 'opt-in' in order to support 'Run'. If a debugger extension has not been updated, 'Run' will fall back to 'Debug' (the built-in Node.js Debug and Mono Debug already support 'Run').

**Comment by DonJayamanne** [comment]
Suggestions for #183

**Comment by DonJayamanne** [comment]
@perfectspr , apologies for the delay in implementing this very simple feature. this will be in the next release.
