### ISSUE TITLE
Run Selection/Line in Python Terminal does not execute w/ IPython

### ISSUE THREAD

**Issue by ruben-aghayan** [DonJayamanne/pythonVSCode#1180]
## Environment data
VS Code version:  1.15.1
Python Extension version:  0.7.0
Python Version:   3.6.2
IPython Version: 6.1.0
OS and version:     Windows 10 Enterprise 1703

## Actual behavior
Pastes selected line(s) into IPython but does not run them. There is a new line at the end of the pasted text.

![image](https://user-images.githubusercontent.com/29712301/29735551-796a8e30-89ae-11e7-9bcb-984b8909e1fd.png)

Observed ouptut from highlighting line or leaving cursor on line and issuing Run Selection/Line in Python Terminal command when IPython is default interpreter

## Expected  behavior
To run selected line(s) 

## Steps to reproduce:  
-  Set IPython default interpreter
-  Issue Run Selection/Line command

**Comment by TiemenSch** [comment]
What happens if you add a new line at the end of your file?

**Comment by ruben-aghayan** [comment]
Hi Tiemen,

When I add a new line at the end of the file, it is also pasted into IPython, but the code is not run. 
Also, I want to confirm your finding that this only occurs for sending a selection or a line, not for running the file.

Running line by line is an important part of workflow in cases like Data Science. It also makes the most of some of the interactive features in IPython.

**Comment by DonJayamanne** [comment]
Possibly related to https://github.com/DonJayamanne/pythonVSCode/issues/1180

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#169
