### ISSUE TITLE
Django debugger not work

### ISSUE THREAD

**Issue by SwagVervindil** [DonJayamanne/pythonVSCode#1181]
# **Environment data**

VS Code version: 1.15.1
Python Extension version: 0.7.0 (3 August 2017)
Python Version: 3.6.0
OS and version: Windows 10

# **Actual behavior**

When I start debug my code break when I want get request.data:
django.http.request.RawPostDataException: You cannot access body after reading from request's data stream
And server return 500 HttpCode
![log](https://user-images.githubusercontent.com/28733519/29752605-b558f792-8b61-11e7-924b-a81254f9432c.PNG)
If I set reakpoint before request.data  i have this errors, bit if set after all work fine
# **Expected behavior**
To run next line. I check in pycharm and this code work fine.

# **Code**

![capture](https://user-images.githubusercontent.com/28733519/29752632-624628d0-8b62-11e7-9f8b-03c4401327e0.PNG)

I use djangorestframework version: 3.5.4

# **launch.json**

    {
      "name": "Django",
      "type": "python",
      "request": "launch",
      "stopOnEntry": false,
      "pythonPath": "${config:python.pythonPath}",
      "program": "${workspaceRoot}/manage",
      "cwd": "${workspaceRoot}",
      "console": "none",
      "args": [
        "runserver",
        "--noreload",
        "0.0.0.0:8000"
      ],
      "exceptionHandling": {
          "ignore": ["ImportError"]
      },
      "env": {
        "DJANGO_SETTINGS_MODULE": "settings.dev"
      },
      "debugOptions": [
        "WaitOnAbnormalExit",
        "WaitOnNormalExit",
        "RedirectOutput",
        "DjangoDebugging"
      ]
    }

**Comment by DonJayamanne** [comment]
@SwagVervindil The PTVS team is in the middle of some major changes to their debugger. As soon as they are done with that work i'll look into this. Apologies for the delay.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#170
