### ISSUE TITLE
PythonVScode extension doesn`t seem to implement jedi properly - the extension cannot locate the correct symbol definition

### ISSUE THREAD

**Issue by circlecrystal** [DonJayamanne/pythonVSCode#1182]
1. In other editors' implementations of jedi can lookup the user defined object, and find the method definition (csv_handle has the writerow() and writerows() methods, and they do show up in some other editor):

![other](https://user-images.githubusercontent.com/5665980/29759472-ac0c3ce8-8bee-11e7-98a6-dfb328ac6e2c.gif)

2. The vscode python extension implementation of jedi cannot lookup any method which belong to the object of some object of some imported class (label_handle has the writerow() and writerows() methods, but they do not show up in vscode. Instead, vscode show the incorrect methods which don`t actually belong to label_handle object):

![vscode](https://user-images.githubusercontent.com/5665980/29759494-e36c28ba-8bee-11e7-8848-8877ff4ab491.gif)

(* The imported class in the above and below showcase is with the Python standard library.)

3. The vscode python extension implementation of jedi cannot even lookup any user defined MACRO value (it shows the data type instead, which is pretty much useless for us):

![vscode 2](https://user-images.githubusercontent.com/5665980/29759632-037b35aa-8bf0-11e7-9808-730d4e652fd3.gif)

As I also investigated this issue a lot, I found it is not the problem of jedi itself. It is vscode python extension does not use the jedi as correctly as it should.

That`s why we have this problem haunting many of us python programmers who are using this extension right now.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#171
