### ISSUE TITLE
Linting fails on bigger files

### ISSUE THREAD

**Issue by JGH1000** [DonJayamanne/pythonVSCode#1183]
I have noticed constant problems with linters (pylama or pylint) when I have a bit larger and even slightly complicated file. When I open a short script (couple of lines) the linting works without a problem, but when I open an 80 lines code, the linter often fails.

I tested both pylint and pylama in the terminal and they work without a problem. A bit slow at times but they work. Is there any built-in mechanism to drop the linting requests when it is taking a bit longer? I cannot think of any other reason the build in linter plugins break so often.

Many thanks for looking into this.

**Comment by DonJayamanne** [comment]
Are you still experiencing this issue.
80 lines of code is very very small, you shouldn't have any issues with such a small file.

**Comment by JGH1000** [comment]
I reinstalled Python, all linters and VSCode and it seems to work fine now. The only tiny thing is that after opening VSCode the python files that were previously used are not linted until a change is made.

Thanks for following up. Out of curiosity, is there any plan to switching to a python language server?

**Comment by DonJayamanne** [comment]
@JGH1000 
> Out of curiosity, is there any plan to switching to a python language server?

Curious, why?

**Comment by JGH1000** [comment]
Seems that everyone is slowly moving towards it  - Atom just introduced Atom IDE that build upon it and VSCode was the place where it development started.

https://code.visualstudio.com/blogs/2016/06/27/common-language-protocol

There is a package created for Python by Palantir although it will take some time to cover everything offered by pythonVSCode. Just wondering!
