### ISSUE TITLE
Allow to setup env variables specific to tests.

### ISSUE THREAD

**Issue by eMerzh** [DonJayamanne/pythonVSCode#1184]
Hi thanks for your project 👍 , 

in my app i use Env var to select the configuration.
So to select the correct configuration in the test i was looking for a way to put Env variable via vscode or smth.

**Comment by DonJayamanne** [comment]
you can create a file named ```.env``` in the root directory an defined your environment variables in there. That should work (I've just tested it).

Here are the instructions:
1. Create ```.env``` file in root directory  
2. Add variables as follows
```
VARIABLE1=VALUE1
VARIABLE2=VALUE2
```
3. These variables are now available in your unit tests 
```python
os.getenv("VARIABLE1")
```

**Comment by eMerzh** [comment]
Thanks for your reply :)

but with this method i can't make the distinction between tests and dev env ? or can i ?

**Comment by DonJayamanne** [comment]
>but with this method i can't make the distinction between tests and dev env ? or can i ?

No you can't.

**Comment by eMerzh** [comment]
ok :/ that was the whole point of this issue....

**Comment by DonJayamanne** [comment]
Will look into this. 
Personal note (look at settings specific a to test files/folder)
https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs#do-i-need-to-do-anything

**Comment by eMerzh** [comment]
@DonJayamanne no problem... probably my fault too not being explicit enough...

Thank you for your help :)

**Comment by DonJayamanne** [comment]
To be looked at when #1228 has been completed

**Comment by eMerzh** [comment]
@DonJayamanne  are you sure you linked the correct issue ? 🤔

**Comment by asfaltboy** [comment]
@DonJayamanne I'm sorely missing this feature. Would a PR for this be appreciated? I'm new to VSCode extension development, but it seems by looking at the code, this could be relatively simple to fix. This is what I had in mind:

1. Allow [`config.envFile` to be a dictionary of values][1], where keys are mapped to different environment files (e.g `.env`, `.envTest`, etc...)
2. Accept custom env file key [in `getCustomeEnvVars`][2].
3. Allow [`execPythonFile `][3] to be passed an optional env file key.
4. Have [`runTest` call `execPythonFile`][4] with the env file key for test.

Alternatively, we could also hard-code the two settings (envFile and testEnvFile) and call `execPythonFile` with something like `test: 1`. But I like the flexibility if we were to have additional environments in mind, like a separate env for debugging, etc.

Please let me know if you'd like to see this sort of change, or you have something else in mind.

[1]: https://github.com/DonJayamanne/pythonVSCode/blob/c69a724e4938426c831e9303e597767e9064db15/src/client/debugger/configProviders/simpleProvider.ts#L48
[2]: https://github.com/DonJayamanne/pythonVSCode/blob/be9e53553854838a62c9f7aadbaac2f15b11dfad/src/client/common/utils.ts#L364
[3]: https://github.com/DonJayamanne/pythonVSCode/blob/be9e53553854838a62c9f7aadbaac2f15b11dfad/src/client/common/utils.ts#L113
[4]: https://github.com/DonJayamanne/pythonVSCode/blob/be9e53553854838a62c9f7aadbaac2f15b11dfad/src/client/unittests/pytest/runner.ts#L54

**Comment by DonJayamanne** [comment]
@asfaltboy Next month VS Code will be releasing a new feature which would allow opening multiple folders in the same workspace, this would allow you to have different settings for different folders (provided they are opened as workspaces). I believe this would give you what you need.

I.e. lets wait for around 2 weeks untill the next release of VS Code and catch up then.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#172
