### ISSUE TITLE
Optional cwd before running tests

### ISSUE THREAD

**Issue by cryptomaniac512** [DonJayamanne/pythonVSCode#1185]
I have a project in which the python code is in the `src` directory and there is also `pytest.ini.`
When I try to run tests, `rootdir` is installed in the root of the project and `pitest` can not see the config.

Now I solve the problem by specifying `-c ${workspaceRoot}/src/pytest.ini`, but this does not work if I run a specific test, in which case the command is generated as
`/home/user/env/bin/python /home/user/env/bin/py.test src/app/tests/unit/tests_module.py::TestClass --c --junitxml=/tmp/tmp-10682gl5jcdH3EgD2.xml`
and pytest will fail.

Sorry for my bad English.

**Comment by DonJayamanne** [comment]
You can provide custom arguments in settings.json for pytest (pytest.args).

**Comment by cryptomaniac512** [comment]
`pytest` can not change the working directory itself. 
As I wrote above, if I explicitly specify the configuration file for it, this will cause an error when running individual tests.
