### ISSUE TITLE
The python virtual environment selected don‘t take effect after "select workspace interpreter" in ubuntu

### ISSUE THREAD

**Issue by appleyuchi** [DonJayamanne/pythonVSCode#1186]
## Environment data
VS Code version:  1.15.1
Python Extension version:  0.7.0 
Python Version:  3.5.2 
OS and version:    Ubuntu16.04

## Actual behavior
Python virtual environment did not take effect after select workspace interpreter  
## Expected  behavior
python 3.5

## Steps to reproduce:  
1、launch from   terminal:code
2、ctrl+shift+p=>select workspace interpreter，and choose“/home/appleyuchi/.virtualenvs/python2.7/bin/python”
3、reload
4、run the following code：
import sys  
print(sys.prefix)  
print(sys.executable)  
5、the result is：
[Running] python "/home/appleyuchi/PycharmProjects/csdn_blog_codes/hello.py"
/usr
/usr/bin/python

## Logs
Output from ```Python``` output panel  ：

[Running] python "/home/appleyuchi/PycharmProjects/csdn_blog_codes/hello.py"
/usr
/usr/bin/python

Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by appleyuchi** [comment]
I down load all from
https://github.com/DonJayamanne/pythonVSCode
and 
npm install
which doesn't fix above,please help ,Thank you very much.

**Comment by appleyuchi** [comment]
Also ,I have tried to edit python.Pythonpath and python.venvPath and then reload ,all of them don't take effect,my system is :
Linux Ubuntu16 4.8.0-36-generic #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#173
