### ISSUE TITLE
Extension host terminated unexpectedly. Please reload the window to recover.

### ISSUE THREAD

**Issue by alexandrudima** [DonJayamanne/pythonVSCode#1187]
Moved from https://github.com/Microsoft/vscode/issues/33504
From @johnashu 

---

- VSCode Version: 1.15.1
- OS Version: windows 10

Steps to Reproduce:

1. install python linting : https://github.com/DonJayamanne/pythonVSCode
2.

Reproduces without extensions: No

THe following extension:
https://github.com/DonJayamanne/pythonVSCode

returns the Errors:

Extension host terminated unexpectedly. Please reload the window to recover.
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
t.onExit @ extensionHost.ts:378
(anonymous) @ extensionHost.ts:196
emitTwo @ events.js:106
emit @ events.js:191
__dirname.ChildProcess._handle.onexit @ internal/child_process.js:215
extensionHost.ts:386 Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
t.onExit @ extensionHost.ts:386
(anonymous) @ extensionHost.ts:196
emitTwo @ events.js:106
emit @ events.js:191
__dirname.ChildProcess._handle.onexit @ internal/child_process.js:215

**Comment by DonJayamanne** [comment]
@johnashu
I am unable to replicate this at my end.
Please uninstall the extension and reinstall it.
Do you have the 64 but version of the extension installed?

Do you have a python file open when you get this error?
What's the output in the Python output panel?

Finally please could you go into Help-> Developer Tools
Let me know what does we displayed in the console window.

**Comment by johnashu** [comment]
@DonJayamanne 

Please uninstall the extension and reinstall it.
>>> I have tried many times..

Do you have the 64 but version of the extension installed?
>>> I am not sure but Iam running the 64 bit version of code.
>>> How can I find this out?

Do you have a python file open when you get this error?
>>> Yes, only when I open or activate a python file

What's the output in the Python output panel?
>>> Apologies but I am unsure where you mean.

Finally please could you go into Help-> Developer Tools
Let me know what does we displayed in the console window.
>>>

e._assertNoCtrlAlt @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28 Extension host terminated unexpectedly. Please reload the window to recover.
e.doShow @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29 Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
t.onExit @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29

**Comment by johnashu** [comment]
@DonJayamanne 

Thanks for helping.. I am totally lost without this plugin!!

**Comment by johnashu** [comment]
@DonJayamanne 

Update:

I uninstalled 64bit VSC and installed 32bit VSC.

I am now returned a different set of errors:

Extension host terminated unexpectedly. Please reload the window to recover.
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
t.onExit @ extensionHost.ts:378
(anonymous) @ extensionHost.ts:196
emitTwo @ events.js:106
emit @ events.js:191
__dirname.ChildProcess._handle.onexit @ internal/child_process.js:215
extensionHost.ts:386 Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
t.onExit @ extensionHost.ts:386
(anonymous) @ extensionHost.ts:196
emitTwo @ events.js:106
emit @ events.js:191
__dirname.ChildProcess._handle.onexit @ internal/child_process.js:215

**Comment by johnashu** [comment]
UPDATE:
I uninstalled EVERY extension I had installed and it appears to be working fine again..
I am in the process of adding them back in as i go (sorry but I really needed to work)

You can Close this off and when I re-find the culprit I shall open a new issue.
