### ISSUE TITLE
No IntelliSense suggestions for numpy (and other?) variables

### ISSUE THREAD

**Issue by vvug** [DonJayamanne/pythonVSCode#1189]
## Environment data
VS Code version:  1.15.1
Python Extension version: 0.7.0
Python Version: 3.6
OS and version: Debian GNU/Linux

## Actual behavior

Take this trivial code:

```
#!/usr/bin/env python3

import numpy
import datetime as dt

test_date = dt.datetime(2000, 11, 11)

test_np = numpy.array([1,2,3])

print(x[1])
```

If I write `test_date.` I get the suggestions for the datetime object, while if I type `test_np.` I get no suggestions. If I force it with `ctrl+space` I still get no suggestions.

The `numpy` module is installed system wide. If I "Run Python File in Terminal" it works:

```
~ $ python3 /tmp/test.py
2
~ $
```

This is not done in a VirtualEnv, `python3-numpy` is installed system-wide.

## Expected  behavior

Suggestions are given for the numpy array.

## Logs
Output from ```Python``` output panel  

(not sure what it is)

Output from ```Console window``` (Help->Developer Tools menu): none

**Comment by vvug** [comment]
I now have some more details. If I create an array like this:
```
arr = numpy.array([1,2,3])
```
then I get no suggestions when typing `arr.`. But if I create an array like this
```
arr = numpy.ndarray([1,2,3])
```
then I get the suggestions for it! The relevant point here is both lines create the same type of object (a `ndarray`): `numpy.array` is just a convenience function to create an `ndarray`.  From the docstring of `numpy.ndarray`:

> Arrays should be constructed using `array`, `zeros` or `empty` ... The parameters given here refer to a low-level method (`ndarray(...)`) for instantiating an array.

and indeed creating an ndarray `numpy.zeros()` gives an object for which the suggestions do not work. But, again, if it is created (identical) with `numpy.ndarray()` then the suggestions *do* work.

**Comment by paride** [comment]
I also observe this behavior. Apparently plain python is able to give produce suggestions:
```
$ python3
Python 3.5.4 (default, Aug 31 2017, 12:22:39) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> a = numpy.zeros(2)
>>> a.m<Tab><Tab>
a.max(   a.mean(  a.min(   
```
while within VSCode no suggestion is given for a `ndarray` created with `numpy.zeros()`. Suggestions are given for a `ndarray` created with `numpy.ndarray()` (which should not be called directly).

I can reproduce this on a clean install of VSCode where I removed `~/.vscode` and `~/.config/Code` and installed only the Python extension (v0.7.0).

```
$ code --version
1.15.1
41abd21afdf7424c89319ee7cb0445cc6f376959
```

**Comment by xanderberkein** [comment]
Not sure if this is the same problem, but I also had some issues with IntelliSense recently, where IntelliSense completely stopped functioning in my Python code. Uninstalling and reinstalling of the Python extension fixed the problem for me.

**Comment by DonJayamanne** [comment]
Currently the [Jedi](https://github.com/davidhalter/jedi) package is being used to provide the intellisense.

**Comment by vvug** [comment]
But ipython (which uses jedi) is able to give suggestions in the example I provided. I don't think you can just dismiss the issue like this.

Did you try to reproduce the issue?

**Comment by gandhis1** [comment]
IPython is a REPL and has access to everything. It's not a good test of Jedi, you should use the Jedi.script API to check.
