### ISSUE TITLE
how to input character when debuging?

### ISSUE THREAD

**Issue by abc100m** [DonJayamanne/pythonVSCode#119]
xx = raw_input('please input:')
print xx

how to input ?

**Comment by DonJayamanne** [comment]
Unfortunately this isn't supported by vs code. 
What you could however do is try remote debugging (on your local machine). Fire up your application, then attach to the local process. Hopefully that will work.

**Comment by DonJayamanne** [comment]
Sorry, this is possible, just use the python launch configuration "python console app" when debugging.

**Comment by DonJayamanne** [comment]
https://github.com/DonJayamanne/pythonVSCode/wiki/Debugging

**Comment by abc100m** [comment]
get it

thanks
