### ISSUE TITLE
press 'step over', but the debugger did not respond

### ISSUE THREAD

**Issue by uli2k** [DonJayamanne/pythonVSCode#1193]
## Environment data
VS Code version:  1.15.1
Python Extension version:  0.7.0
Python Version:   2.7
OS and version:    ubuntu 16.04 desktop 32bit

## Actual behavior
python code:

print 'hello'
print 'hello'
print 'hello'
print 'hello'

debug launch.json:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
    ]
}

press 'step over', but the debugger did not respond.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#175
