### ISSUE TITLE
Ability to use ${env:} variables when specifying mypy and pylint path? 

### ISSUE THREAD

**Issue by breathe** [DonJayamanne/pythonVSCode#1195]
## Environment data
VS Code version:  
Python Extension version:  
Python Version:   
OS and version:    

## Actual behavior

This doesn't work:
```
  "python.pythonPath": "${env:HOME}/anaconda3/envs/dev/bin/python",
  "python.linting.pylintPath": "${env:HOME}/anaconda3/envs/dev/bin/pylint",
  "python.linting.mypyPath": "${env:HOME}/anaconda3/envs/dev/bin/mypy"
```

But this does:

```
  "python.pythonPath": "${env:HOME}/anaconda3/envs/dev/bin/python",
  "python.linting.pylintPath": "/Users/bcohen/anaconda3/envs/dev/bin/pylint",
  "python.linting.mypyPath": "/Users/bcohen/anaconda3/envs/dev/bin/mypy"
```

## Expected  behavior

I could use ${env:HOME} and do this setup portably and it would work for any developer who installed anaconda3 to the default location and setup a conda environment named 'dev' (which in my context, includes mypy and pylint amongst other things) ...

## Logs

Tries to install mypy and pylint

Output from ```Console window``` (Help->Developer Tools menu)

```
Linting with pylint failed.
You could either install the 'pylint' linter or turn it off in setings.json via "python.linting.pylintEnabled = false".
Error: spawn /Users/bcohen/software/masslight/conversational_assistants/${env:HOME}/anaconda3/envs/dev/bin/pylint ENOENT

Linting with mypy failed.
You could either install the 'mypy' linter or turn it off in setings.json via "python.linting.mypyEnabled = false".
Error: spawn ${env:HOME}/anaconda3/envs/dev/bin/mypy ENOENT
```

**Comment by DonJayamanne** [comment]
will look into this.
FYI you don't need to specify the paths of pylint and mypy manually (removing those should work).

**Comment by breathe** [comment]
> FYI you don't need to specify the paths of pylint and mypy manually (removing those should work). 

Maybe its not worth it -- but I was thinking to try and consolidate installation/versioning of these tools into a single conda environment -- where the versions of the dependencies needed by the project code lives.  This way people don't get the prompt to install mypy/pylint the first time they open vscode.

I checked and this doesn't work -- for me though.  I'm guessing I need to wait for the next pythonVSCode  release?

Thanks!!

**Comment by DonJayamanne** [comment]
https://github.com/DonJayamanne/pythonVSCode/commit/ea4271a7af4aa56b6d0196563333e0e003ac783a
