### ISSUE TITLE
Linter pep8 and pylint is not installed errors

### ISSUE THREAD

**Issue by roblourens** [DonJayamanne/pythonVSCode#1197]
_From @cryst10 on September 8, 2017 3:43_

- VSCode Version:  1.16.0
- OS Version: MacOS Sierra
- Python version: 3.6
- pip: 3
- virtualenv: 3
- extension: https://github.com/DonJayamanne/pythonVSCode/wiki

I am working in a virtualenv, I have my settings.json file like the below:

```
{
  "python.pythonPath": "python",
  "python.linting.pylintEnabled": true,
  "python.linting.pylintPath": "pylint",
  "python.linting.pep8Enabled": true
}
```
I have installed both pylint and pep8 in my virtualenv but keep getting those noisy error alerts in vscode `Linter pep8 is not installed` or `Linter pylint is not installed`, I am using this extension https://github.com/DonJayamanne/pythonVSCode/wiki.
 

_Copied from original issue: Microsoft/vscode#33988_

**Comment by DonJayamanne** [comment]
Please ensure the following setting points to the fully qualified path to your virtual env python
```json
"python.pythonPath": "<path to virtualenv>/python",
```

**Comment by PlugaruT** [comment]
I am getting this error too even if I have set the python path in the workspace settings.

**Comment by DonJayamanne** [comment]
@PlugaruT It is most likely that you do not have the linters installed in the environment you have configured in workspace settings.

**Comment by PlugaruT** [comment]
@DonJayamanne  I have this linters installed in the venv.

**Comment by DonJayamanne** [comment]
Please could you provide the error displayed in the ```Python``` output panel. 
Also, please go into ```Developer Tools``` and go into the ```Console``` window and let me know what errors/warnings are displayed there.

**Comment by PlugaruT** [comment]
@DonJayamanne opening output panel for Python helped me to install some packages that I missed and were used by `pylint`. Thanks.

**Comment by fixmycode** [comment]
@DonJayamanne  This is my output every time I save:


```
Linter pylint is not installed     messageService.ts:126
  | e.doShow | @ | messageService.ts:126
-- | -- | -- | --
  | e.show | @ | messageService.ts:105
  | e._showMessage | @ | mainThreadMessageService.ts:72
  | n.Class.derive._oncancel | @ | winjs.base.raw.js:1641
  | e._showMessage | @ | mainThreadMessageService.ts:42
  | e.$showMessage | @ | mainThreadMessageService.ts:36
  | e.invoke | @ | abstractThreadService.ts:41
  | e._invokeHandler | @ | rpcProtocol.ts:109
  | e._receiveOneMessage | @ | rpcProtocol.ts:96
  | (anonymous) | @ | rpcProtocol.ts:32
  | (anonymous) | @ | rpcProtocol.ts:157
  | e.invoke | @ | callbackList.ts:36
  | e.fire | @ | event.ts:123
  | (anonymous) | @ | ipc.net.ts:82
  | emitOne | @ | events.js:96
  | emit | @ | events.js:191
  | readableAddChunk | @ | _stream_readable.js:178
  | Readable.push | @ | _stream_readable.js:136
  | onread | @ | net.js:560

```

**Comment by zelenyjan** [comment]
@fixmycode try this:
`"python.linting.pylintArgs": [
        "--load-plugins=pylint_django"
    ]`

and be sure you have installed pylint-django
