### ISSUE TITLE
Allow to set up environnement variables for tests

### ISSUE THREAD

**Issue by eMerzh** [DonJayamanne/pythonVSCode#1199]
## Environment data
VS Code version:  1.16.0 

Hi, 
i was using vscode to launch my tests , and it's really cool
but to setup my tests i need to put some env variable, but i don't think it's possible already.

Thanks a lot

**Comment by jflam** [comment]
Dupe of #1184

**Comment by eMerzh** [comment]
:man_facepalming:   dup of myself,
sorry about that (thx @jflam )
