### ISSUE TITLE
Related to Issue#2

### ISSUE THREAD

**Issue by YouGovGit** [DonJayamanne/pythonVSCode#12]
I am getting the same error it is saying that it can not find the __init__py
The instructions are a bit sparse, Apart from installing the extension and pressing F5 should I be doing something else? Also, I used Anaconda to install python (it is on the PATH though) would this make a difference and if so, what would I need to do to resolve it (Windows 8.1 install). This is such a cool extension it would be great if you could help me out.

**Comment by YouGovGit** [comment]
I changed the __init__.py to ${file} this seems to have allowed the debugger to 'work', but now I get another error: copy.Error, un(shallow)copyable object of type <type 'Element'>. I am attempting a simple print statement

**Comment by YouGovGit** [comment]
Sorry to keep answering my own questions, but this seems to be relevant to the errors I am seeing:
http://stackoverflow.com/questions/20532621/pandas-import-error-when-debugging-using-pvts

It does actually execute if I continue

**Comment by DonJayamanne** [comment]
Hi thanks for the feed back, I will update the read me with more details, and will try to incorporate this feature of ignoring these exceptions.

**Comment by DonJayamanne** [comment]
Documentation has been updated and the default program has been set to ${file}
