### ISSUE TITLE
Formatter yapf is not installed

### ISSUE THREAD

**Issue by nicksay** [DonJayamanne/pythonVSCode#1202]
## Environment data
VS Code version:  1.14.2
Python Extension version:  0.7.0
Python Version:   3.6.1
OS and version:    macOS 10.12.6

## Actual behavior
Formatting causes a "Formatter yapf is not installed" error to be displayed.

## Expected  behavior
Formatting should work.

## Steps to reproduce:  
-  pyenv install 3.6.1
-  pyenv global 3.6.1
-  pip install yapf
-  Update settings to "python.formatting.provider": "yapf",

## Logs
Output from ```Python``` output panel  
```
(none)
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
messageService.ts:125 Formatter yapf is not installed
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
(anonymous) @ mainThreadMessageService.ts:64
n.Class.derive._oncancel @ winjs.base.raw.js:1641
t.showMessage @ mainThreadMessageService.ts:34
t.$showMessage @ mainThreadMessageService.ts:28
e.handle @ abstractThreadService.ts:34
s @ ipcRemoteCom.ts:275
f @ ipcRemoteCom.ts:231
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

**Comment by nicksay** [comment]
Note that all of the following succeed in the integrated terminal:
* python
* yapf
* python -m yapf

**Comment by DonJayamanne** [comment]
what's the path to your python interpreter in your workspace settings file?

**Comment by nicksay** [comment]
It's the default

**Comment by DonJayamanne** [comment]
Please could you double check the output panel (this is the output window on the bottom).
There are a couple of tabs, ```Problems | Output | Debug Console | Terminal```
I'd like you to click ```Output``` and form the dropdown select ```Python```
There must be something in the output window

**Comment by nicksay** [comment]
I've finally figured out how to repro.

Normally, this works as expected, but you can repro by:

- Launch VS Code
- Open a project/file
- Choose [Apple Menu] > Restart...
- Ensure "Reopen windows when logging in" is checked
- Restart

When VS Code automatically reopens after restart, formatting and linting fail:
```
Formatting with yapf failed.
You could either install the 'yapf' formatter, turn it off or use another formatter.
Error: spawn yapf ENOENT
```
and
```
Linting with pylint failed.
You could either install the 'pylint' linter or turn it off in setings.json via "python.linting.pylintEnabled = false".
Error: Command failed: /usr/bin/python -m pylint --msg-template='{line},{column},{category},{msg_id}:{msg}' --reports=n --output-format=text /Users/nicksay/Desktop/test.py
/usr/bin/python: No module named pylint
```

Quitting/reopening VS Code fixes the problem.

**Comment by DonJayamanne** [comment]
Thanks, will try this on the mac

**Comment by DonJayamanne** [comment]
@nicksay I've tried this at my end and am unable to replicate this at my end.  
Are you able to replicate this consistently?  
Its an odd issue, and may have something to do with the environment setup being activated immediately after login.
The following error indicates that pylint isn't available, please confirm this is the correct path to your python environment.
```
/usr/bin/python -m pylint --msg-template='{line},{column},{category},{msg_id}:{msg}' --reports=n --output-format=text /Users/nicksay/Desktop/test.py
/usr/bin/python: No module named pylint
```

**Comment by nicksay** [comment]
Apologies for the delay here;  it does seem that this is something unusual with environment setup specifically around auto-starting the app after reboot.

For posterity, the path to my python environment is:
```
$ type -a python
python is /Users/nicksay/.pyenv/shims/python
python is /usr/bin/python
```

This problem doesn't come up very often, and when it does, it's an easy work around, so if there's nothing obvious for you to do and this is an isolated issue, closing seems right.
