### ISSUE TITLE
Intellisense is not working

### ISSUE THREAD

**Issue by mashiroplanc** [DonJayamanne/pythonVSCode#1204]
## Environment data
VS Code version:  1.15.1
Python Extension version:  0.7.0
Python Version:   3.6.2
OS and version:    Window 10 Education ver 1703 build 15063.540

## Actual behavior
![5](https://user-images.githubusercontent.com/30903885/30292698-5849db1e-9761-11e7-9172-3a406b21418b.gif)

## My setting
![image 001](https://user-images.githubusercontent.com/30903885/30292703-5e0797d0-9761-11e7-8283-af0d3b741008.png)

**Comment by xanderberkein** [comment]
I had the same problem today. Uninstalling and reinstalling the Python extension (with a reload in between) fixed this problem for me.

**Comment by mashiroplanc** [comment]
Thanks, after I reinstalled as you said, it fixed.
