### ISSUE TITLE
Linting "on text change" not working, only upon saving

### ISSUE THREAD

**Issue by marnovo** [DonJayamanne/pythonVSCode#1205]
## Environment data
VS Code version:  `1.16.0`
Python Extension version:  `0.7.0`
Python Version:   `3.6.0`
OS and version:    `macOS Sierra 10.12.6 (16G29)`

## Actual behavior
Linting using pep8 or flake8 doesn't work _on text change_, only upon saving, even though set as:
`"python.linting.lintOnTextChange": true`

## Expected  behavior
Linting would happen as you type and change the document while the following option is on:
`"python.linting.lintOnTextChange": true`

## Steps to reproduce:  
-  Install extension
-  Install linters
-  Open and Python file and start typing
-  Tried reinstalling and disabling/enabling again plugin and settings

## Logs
Output from ```Python``` output panel  
```
Nothing meaningful
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
Nothing meaningful
```

**Comment by DonJayamanne** [comment]
Unfortunately this is a feature that isn't supported at this stage. The only way to get this working is if you enable "autoSave".

**Comment by berzhy** [comment]
What do you mean by "isn't supported"? Why do you have this setting in config then?

**Comment by DonJayamanne** [comment]
This will be removed. It was added incorrectly.

**Comment by DoronCohen** [comment]
This confuses me. if this is a requested feature that is blocked on something why close it?. I can't use autosave because that will trigger other things I use. Is there anything avoiding this feature to be implemented? I can see some settings like:

    "php.validate.run": "onSave",
   "editor.formatOnType": false,

doesn't that mean it's possible?

**Comment by Xenya0815** [comment]
Will that feature supported sometime?

**Comment by DoronCohen** [comment]
I dropped this package because of this.

**Comment by marnovo** [comment]
See: https://github.com/Microsoft/vscode-python/issues/408

**Comment by DoronCohen** [comment]
@mikevaleriano went back to Sublime. and trying to learn Vim. VScode was very nice at first but had some small issues that made me very uncomfortable.

**Comment by goodside** [comment]
Could you please consider reopening this issue, or perhaps explain why the proposed change is undesirable/impossible? This is a major quality-of-life issue for VSCode's Python support, especially considering that red/green underlines are left on the screen but **underlining the wrong words** when the user has made a code change but hasn't yet saved.

If there's just something blocking, why close as a wont-fix instead of leaving an open issue? Other VSCode language extensions lint on text change without any problems, so it seems unlikely that there's truly no way to do it.

**Comment by marnovo** [comment]
@goodside @digicase, Python linting on change is now available on VSCode if you override this default setting:

From: https://github.com/Microsoft/vscode-python/issues/408#issuecomment-401620185
> you might want to try out the new language server, it has support for live linting.
Add the setting `python.jediEnabled: false` in `settings.json`

This will download the MS Python Language Server (see the status bar):

<img width="468" alt="screen shot 2018-11-08 at 2 42 48 pm" src="https://user-images.githubusercontent.com/15906764/48205621-cff96000-e36c-11e8-8a57-09586d8eb111.png">

And from what I remember you don't even need to restart the editor for linting on change to be working.

**Comment by mikevaleriano** [comment]
@marnovo The MS Python Language Server does check the code during typing, but the linter(s) you activate in your settings still only work on save. Tested with pylint (which doesn't work at all when MS-PLS is enabled) and flake8 (this still works, but only on save).

So unless I'm doing something wrong (which is **_very_** likely, I'm just starting out with Python) it makes little difference using MS-PLS or not, your custom linters will still only work on save, and that is the main issue. I use eslint with vscode, and linting during typing is something you get very used to.

VSCode: 1.29.1
Python: 3.7.1
Flake8: 3.6.0
OS: Windows 10 64-bit

**Comment by marnovo** [comment]
@mikevaleriano actually on a second glance I believe you are correct, it just happened that for the workspace that I was testing this with I had autosave enabled. Trying with my default workspace the issue of no flake8 linting on type still persists. `[Python]` error/warnings happen as you type, but `[flake8]` only upon save.
