### ISSUE TITLE
Can't debug django app in virtualenv on Mac OS X

### ISSUE THREAD

**Issue by holyoaks** [DonJayamanne/pythonVSCode#121]
So I've searched the issues here, especially looking at #69 , but not having any luck. I can start the debug process no problem, but I keep getting errors when I try to start it up. Django is installed in the virtualenv, and I can run the server outside of Visual Studio code.

My settings.json file:

`{
    "python.pythonPath": "/Users/shawn/Virtual18/bin/python"
}`

I've tried the launch.json both with and without specifying the "pythonPath" option in the Django debug configuration. When I run it with the pythonPath option I get:

`IndexError, list index out of range` in sre.parse.py at line 144. 

When I run it without the "pythonPath" option I get 

`ImportError, No module named django.core.management
Traceback (most recent call last):
File "/Users/shawn/sdcgis/manage.py", line 8, in <module>
from django.core.management import execute_from_command_line
ImportError: No module named django.core.management`

Any suggestions? Thank you!

**Comment by DonJayamanne** [comment]
Can you confirm that you are using the django configuration from the launch.json  for debugging.

If not, then Please could you paste your launch.json. Thanks

**Comment by holyoaks** [comment]
I can confirm I'm using the django configuration. My launch.json is attached. I've tried adding the "pythonPath" option as "/Users/shawn/Virtual18/bin/python" in all three launch configurations. Thanks for building this and your quick response.
[launch.txt](https://github.com/DonJayamanne/pythonVSCode/files/260338/launch.txt)

**Comment by lzantal** [comment]
@holyoaks did you figure it out? I got my debug running perfect after I added pythonPath to the Django debug section. Make sure you set the absolute path for it.

**Comment by DonJayamanne** [comment]
@holyoaks , i've had a look at the launch.txt file, and you haven't configured the pythonPath in there. 
That will be the issue.

**Comment by holyoaks** [comment]
Thanks both of you, but as I mentioned in my original issue, I've tried it both with AND without the pythonPath and get different issues each way. Without the pythonPath it doesn't find Django, as expected, but when I run it with the pythonPath I get IndexError, list out of range. I'm setting the absolute path for it.

**Comment by holyoaks** [comment]
I tried changing from /Users/shawn/Virtual18/bin/python to ~/Virtual18/bin/python, and now I get "spawn ~/Virtual18/bin/python ENOENT" and the debugger never launches. When I stop the debugger VS crashes. How is it that I'm having such a hard time with this?

**Comment by DonJayamanne** [comment]
Please  use the fully qualified path in launch.json and then post the json file with the error displayed here.

**Comment by DonJayamanne** [comment]
Please ensure you are using the django debug configuration. Try deleting the launch.json file and recreating it and use the django configuration for debugging. (Setting where name is django in launch.json)

**Comment by lzantal** [comment]
I have a feeling you have an issue with your django project. Activate virtualenv in the terminal and run manage.py runserver and make sure it runs without any errors.

**Comment by holyoaks** [comment]
@lzantal That was my first thought too, but no, activating the virtualenv and running Django's debug server runs perfectly. I'll try @DonJayamanne suggestion of recreating the launch.json file.

**Comment by holyoaks** [comment]
No joy. I deleted the launch.json file, then used Code to recreate it. I added the pythonPath to the django debug config section and tried debugging. Identical error I've received before, IndexError, list index out of range. I attached a screen shot showing the error and call stack as well as the newly created launch.json file. I'm not terribly familiar with Code; is there a logging function that I could use to provide more information? Again, thanks for both of your help with this.

[launch.txt](https://github.com/DonJayamanne/pythonVSCode/files/280614/launch.txt)

<img width="1261" alt="screen shot 2016-05-24 at 5 04 01 pm" src="https://cloud.githubusercontent.com/assets/5797525/15521469/999a456a-21d1-11e6-9885-fb21fffa66c7.png">

**Comment by DonJayamanne** [comment]
Hi @holyoaks, have you managed to get this working. Sorry, but I'm unable to replicate this at my end.
If it still persists, please could you try running a simple Django program such as the one in #87?
Hopefully we can narrow down the issue.

**Comment by DonJayamanne** [comment]
Closing this issue. Please reopen if the issue persists.
