### ISSUE TITLE
Can't step into code that is defined in a lib (virtual environment)

### ISSUE THREAD

**Issue by thiagorabelo** [DonJayamanne/pythonVSCode#1210]
## Environment data
VS Code version:  1.15.1
Python Extension version:  0.7.0
Python Version:   3.5.2 (in a virtual environment)
OS and version:    Kubuntu 16.04.3 LTS

## Actual behavior
Can't step into line when this line is in a lib (at least in Django).

![visual_code_python](https://user-images.githubusercontent.com/12281303/30394219-d16c9620-9898-11e7-8ab7-91b77088ee8d.gif)

In this example instead of debugger enter in code definition of "get_object_or_404" in file "django/shortcut.py", in folder "site-package" of virtual environment, it jumps to "_pq_fetch_tuples" method on line 796 in Cursor class in file "psycopg2cffi/_impl/cursor.py" in "site-package" folder of virtual environment.

In same way, instead step into "render" function in "django/shotcuts.py", jumps to function "urlparse" in "/usr/lib/python3.5/urllib/parse.py" at line 301.

## Expected  behavior
Enter the appropriate function.

![visual_code_python_2](https://user-images.githubusercontent.com/12281303/30399224-5c7bf2be-98a9-11e7-8882-547fe4559300.gif)

## Steps to reproduce:  
-  While debugging some block of code, step into a function or method defined in some lib.
-  

## Logs
Output from ```Python``` output panel  
Empty   

Output from ```Console window``` (Help->Developer Tools menu)
Empty

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#177
