### ISSUE TITLE
Every time restarting the debugger, debug console shows one more output in a iteration

### ISSUE THREAD

**Issue by ChenTanyi** [DonJayamanne/pythonVSCode#1214]
## Environment data
VS Code version:  1.16.0
Python Extension version:  0.7.0
Python Version:  2.7.13 in windows and 3.6.2 or 2.7.13 in docker
OS and version:  windows 10

## Actual behavior

The debug console would add one by one every time restarting the debugger.

![python-debug](https://user-images.githubusercontent.com/15213781/30470239-7aab1796-9a26-11e7-98fb-95587d10218a.gif)

In the example, I attach the debugger to a process running in a docker container. Every time I restart the attach debugger, the debug console would print one more `Hello` in an iteration. I think it may create another process and it doesn't kill the previous one.

## Expected  behavior

The `Hello` should be printed once in an iteration.

## Steps to reproduce:  

source code: https://github.com/ChenTanyi/python-debug-docker

All steps are showed in README file of the source code.

I run the docker container built from python image(3.62 for latest or 2.7.13 for 2.7) and attach it with vs code debugger.

## Logs
Output from ```Python``` output panel  
None

Output from ```Console window``` (Help->Developer Tools menu)
None

**Comment by ChenTanyi** [comment]
I have tested the python debugger in VS, and I found this bug again. So I think it may not be due to your extension, but due to the ptvsd package. So I open an issue in the PTVS repository and tell you about it.

**Comment by DonJayamanne** [comment]
Closing as this is an upstream issue https://github.com/Microsoft/PTVS/issues/3073
