### ISSUE TITLE
can‘t formating my code

### ISSUE THREAD

**Issue by Vendetter** [DonJayamanne/pythonVSCode#122]
hey，guys。there is a problem with my vs ，I can't format my code with autopep8，when I click format code ,The vs alert "**There was an error in formatting the document. View the Python output window for details**."
There is my configuration setting:
    "python.linting.lintOnTextChange": true,
    "python.formatting.formatOnSave": true,
    "python.pythonPath": "F:/Program Files/python3.5/python.exe",
    "python.linting.pep8Enabled": true,
    "python.linting.pep8Path": "F:/Program Files/python3.5/Scripts/pep8.exe",
    "python.formatting.provider": "autopep8",
    "python.formatting.autopep8Path": "F:/Program Files/python3.5/Scripts/autopep8.exe"
what should I do? I'm so sorry,I'm a chinese man and my english is not good.

**Comment by DonJayamanne** [comment]
What's logged in your output Window.

**Comment by Vendetter** [comment]
hello again，thinks a lot，there is no issue。I replaced the python path，it's ok
