### ISSUE TITLE
Go to definition not working when a  function's default arguments includes one or more numbers with underscores

### ISSUE THREAD

**Issue by ajmichaels** [DonJayamanne/pythonVSCode#1220]
## Environment data
VS Code version:  1.6.1
Python Extension version:  0.7.0
Python Version:   3.6.2
OS and version:    OSX 10.11.6

## Actual behavior

Go to definition doesn't work when a function's default arguments includes one or more numbers with underscores

## Expected  behavior

A number having underscores should not affect go to definition.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#180
