### ISSUE TITLE
The intellisense is not work in this case

### ISSUE THREAD

**Issue by zhoudotnet** [DonJayamanne/pythonVSCode#1223]
## Environment data
VS Code version:  1.15
Python Extension version:  0.7
Python Version:   3.6
OS and version:    win10

## Actual behavior
I created 2 files: a.py and b.py.
b.py：
def Speak(self, id):
    pass

a.py:
import b
c1 = 1   # type: b
c2: b = 1

In a.py file, the pythonVSCode plugin can not identify c1, and there are no intellisense for c1. But the pythonVSCode plugin can identify c2, there are intellisense information for c2.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#181
