### ISSUE TITLE
Test discovery not taking multi-path workspaces into consideration

### ISSUE THREAD

**Issue by darkvertex** [DonJayamanne/pythonVSCode#1226]
## Environment data
VS Code version:  Version 1.17.0-insider
Python Extension version:  0.7.0
Python Version: 2.7.5
OS and version: CentOS Linux release 7.4.1708 (Core)

## Actual behavior
Discovering tests only runs for the first path of a multi-path workspace.

## Expected  behavior
It should discover tests for each path in my workspace if there is more than one. I would expect it would run my testing framework once per workspace path.

## Steps to reproduce:  
-  Using the "insiders" build, make a new multi-path workspace. My .code-workspace looks a bit like this:
```
{
	"folders": [
		{
			"path": "/path/to/folderA"
		},
		{
			"path": "/path/to/folderB"
		}
	],
	"settings": {
		"python.pythonPath": "/bin/python2.7"
	}
}
```
- Put some dummy tests in a /tests folder in the root of the second path ("folderB" in my example above.)
- Run "Discover All Unit Tests" and check the "Python Test Log" output. It will have only scanned the first path in the workspace.

**Comment by darkvertex** [comment]
A workaround I'm using at the moment is to configure a `pytest.ini` with explicit paths to both roots. Not ideal, but works for now.

**Comment by brettcannon** [comment]
Multi-root workspaces aren't supported quite yet. That work is being tracked in #1228 .

**Comment by DonJayamanne** [comment]
Closing in favor of #1228
