### ISSUE TITLE
Intellisense is wrong with staticmethod

### ISSUE THREAD

**Issue by seanmars** [DonJayamanne/pythonVSCode#1227]
## Environment data
VS Code version:  1.16.1
Python Extension version:  0.7.0
Python Version:   3.5
OS and version:    Windows 10

## Actual behavior
The first argument will determine as the class not the given type. 

## Expected  behavior
The first argument can determine as the given type.

## Steps to reproduce:  
-  create a class include staticmethod.
-  using the intellisense with the first argument in that staticmethod.

## Example
https://gist.github.com/seanmars/f4db30cab21e2d3ec45e350cf9ed0909

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#182
