### ISSUE TITLE
Be able to disable pylint globally from alert banner

### ISSUE THREAD

**Issue by brettcannon** [DonJayamanne/pythonVSCode#1229]
When you open a new workspace that doesn't have pylint installed, the extension prompts you to either install pylint, disable the prompt, or simply close it. Unfortunately the disablement of pylint is local to the workspace and not globally. It would be great to have a way to turn off the prompting globally in your settings. Bonus points if the global disablement still allows the usage of pylint if it happens to be installed later (i.e. just disable the banner, not the ability to use the pylint integration).

/cc @lmazuel

**Comment by DonJayamanne** [comment]
You ask, & I deliver https://github.com/DonJayamanne/pythonVSCode/issues/1207

> Bonus points if the global disablement still allows the usage of pylint if it happens to be installed later (i.e. just disable the banner, not the ability to use the pylint integration).

Will look into this.

**Comment by lmazuel** [comment]
For instance git in VSCode has a parameter:
```json
 "git.ignoreLimitWarning": true
```
This does remove Git support of course, but just stop talking about limit. Would be nice to have `pylintIgnoreWarning` that just decide that I don't care about the warning, but I care about pylint if it's there.

**Comment by DonJayamanne** [comment]
Ok, the solution i implemented was to disable the linter globally. I'll change the behavior to disable the prompt.
