### ISSUE TITLE
Extension Host has Closed Unexpectedly 

### ISSUE THREAD

**Issue by computerwiz160** [DonJayamanne/pythonVSCode#1231]
## Environment data
VS Code version: 1.16.1
Python Extension version: 0.7.0
Python Version: 3.6.2
OS and version: Windows 10

## Actual behavior
Python crashes extension host

## Expected  behavior
Python does not crash extension host

## Steps to reproduce:  
-  Have Python Installed
-  That's it

## Logs
Output from ```Python``` output panel  
(Not quite sure how to find this because the extension host crashes)

Output from ```Console window``` (Help->Developer Tools menu)
https://gyazo.com/d9c8fb69453afdc518b180909e230e39

**Comment by DonJayamanne** [comment]
Please could you disable the python extension and test this.

**Comment by computerwiz160** [comment]
New logs when disabling python
https://gyazo.com/725f38a402daf4e7658a550015e77f18

**Comment by computerwiz160** [comment]
It's been 2 days, can someone help me???????

**Comment by DonJayamanne** [comment]
1. Please could you uninstall the extension and reinstalling it.
 
Unfortunately you seem to be the only one who is experiencing this issue. 
Do you have any other python extensions installed, how about removing other python extensions if there are any. 

2. Rather than taking a screenshot of the logs, please could you copy the log output and send this. FYI - you can upload files directly here (there's no need to upload the images into some other site).

3. Open a terminal window and type in the command ```python``` and let me know what you get.

4. When does VS Code crash? Is it when you open a Python file? 
Please describe the exact steps and the state of vs code (e.g. folder and file opened). 

5. Does VS Code crash even when you do not have a workspace folder opened?

**Comment by computerwiz160** [comment]
1. Have uninstalled, reinstalled, still getting error.

2. /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28 Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
e._onExtensionHostCrashed @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28 Extension host terminated unexpectedly.
e.doShow @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28

(I hope that's what you mean, when I try and upload the .log files I get an error because the file is too large)

3. Python 3.6.2 (v3.6.2:5fd33b5, Jul 8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits", or "license" for more information.
>>>

4. It's when I open a python file. I have a test folder on my desktop and a python folder inside it. When opening the python file itself is when I get the error. 

5. No, only when I have a python file loaded in a tab in vscode. If I have a file tree open it doesn't crash, only when I actually double click the python file it does.

**Comment by computerwiz160** [comment]
It's been a week, has anyone found out what the problem is?

**Comment by DonJayamanne** [comment]
@computerwiz160 
Hi sorry, for the delay. Unfortunately I haven't been able to replicate this. 
Do you have any other Python extensions installed. Please could you try disabling all other extensions and just enabling this Python extension.

**Comment by computerwiz160** [comment]
Over this past week week I have done a complete uninstall of VS Code, python, and anything that could have possibly caused it and reinstalled VS Code and Python.

As of right now, I only have the python extension installed.

**Comment by DonJayamanne** [comment]
Hmm, this isn't looking good. 
I'll go back and try to replicate this on a fresh install of widows 10.
I'll also try to build a version of the extension for you with some additional debugging statements in there.

**Comment by computerwiz160** [comment]
Okay, thank you so much!

**Comment by DonJayamanne** [comment]
@computerwiz160 Please install the latest version of the extension and let me know how this goes.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#184
