### ISSUE TITLE
Return type not showing on Intellisense

### ISSUE THREAD

**Issue by alchermd** [DonJayamanne/pythonVSCode#1234]
## Environment data
VS Code version:  1.16.1
Python Extension version:  0.7.0
Python Version:   3.5
OS and version:    Linux Mint 18.2

## Actual behavior
![](https://i.imgur.com/bj2U335.png)

The `-> str` part is not shown as defined in the function prototype `baz` at module `bar`.

## Expected  behavior

![](https://i.imgur.com/HqbbElJ.png)

Shouldn't it work the same way as above? Or I'm missing something obvious about type hinting? :smile:

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#185
