### ISSUE TITLE
Linter pylint is not installed

### ISSUE THREAD

**Issue by Githelang** [DonJayamanne/pythonVSCode#1235]
## Environment data
VS Code version:  1.16.1
Python Extension version:  0.7.0
Python Version:   2.7.12, 3.5.2
OS and version:    Windows 10

## Actual behavior
Install pylint in bash terminal, redirect pylint path to "python.linting.pylintPath": "C:/Users/Helan/AppData/Local/lxss/home/helang/.local/lib/python2.7/site-packages/pylint". Error pop up still.
## Expected  behavior
Debug and linting in linux environment under windows 10
## Steps to reproduce:  
-  
-  

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
You should point it to the pylint executable. Else just remove the setting and point python Path in settings to the python interpretor , I think that would be ```"C:/Users/Helan/AppData/Local/lxss/home/helang/.local/lib/python2.7/Scripts/python.exe```
