### ISSUE TITLE
Autocomplete not working for Autodesk Maya 2018

### ISSUE THREAD

**Issue by monkeez** [DonJayamanne/pythonVSCode#1236]
## Environment data
VS Code version: 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a)
Python Extension version: 0.7.0
Python Version: 2.7.11 (Maya's custom version, mayapy.exe)
OS and version: Windows 10

My settings.json:
```
{
    "editor.acceptSuggestionOnEnter": "off",
    "editor.fontFamily": "Fira Mono, Consolas, 'Courier New', monospace",
    "python.autoComplete.extraPaths": [
        "C:/Program Files/Autodesk/Maya2018/devkit/other/pymel/extras/completion/py"
    ],
    "python.pythonPath": "C:/Program Files/Autodesk/Maya2018/bin/mayapy.exe"
}
```

## Actual behavior

Autocomplete is not using the extraPaths as there are modules that already exist with the same names in the interpreter's site-packages directory.

![image](https://user-images.githubusercontent.com/5214414/30781251-fd250b0c-a15e-11e7-8551-cac2c06c2f1b.png)

## Expected  behavior

I don't mean to be rude by comparing this to other editors, but it's the easiest way to show what should be happening.

In PyCharm it is possible to remove the site-packages directory from the mayapy.exe interpreter and use the extra paths provided for code completion. Is it possible to get this kind of functionality in pythonVSCode?

![image](https://user-images.githubusercontent.com/5214414/30781263-26f60f44-a15f-11e7-9ecb-474b29c4cdf4.png)

Whereas in Sublime with the Anaconda package, it works if you set the interpreter to mayapy.exe and add the completion directory to the extra paths. I suppose it's using the extra paths before the site-packages, or it's able to use both at the same time without conflict.

![image](https://user-images.githubusercontent.com/5214414/30781352-eca93fe4-a160-11e7-91cc-86040203ef1e.png)

## Steps to reproduce:  
n/a

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by monkeez** [comment]
After researching the Anaconda extension for Sublime I realised they also use Jedi for their completion engine. So it's strange that after setting up pythonVSCode and Anaconda to point to the same interpreter and extra paths that pythonVSCode isn't producing all the completion options that Anaconda is.

I don't know if this information helps?

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#186
