### ISSUE TITLE
Rename symbol misses symbols in formatted strings f"{foo}"

### ISSUE THREAD

**Issue by sdwarwick** [DonJayamanne/pythonVSCode#1237]
## Environment data
VS Code version:  1.16.1
Python Extension version:  0.7.0
Python Version:   3.6
OS and version:    windows 10

## Actual behavior

rename/refactor symbols completely misses symbols inside formatted text strings
f"{name}"

name is not found or changed

## Expected  behavior

clear from above

## Steps to reproduce:  
-  
-  

## Logs
Output from ```Python``` output panel  

no output
```
```   
Output from ```Console window``` (Help->Developer Tools menu)

no output
```
```

**Comment by kodalipraveen** [comment]
This issue is also seen in **Mac OS**
VSCode - **1.17.1**
Python Extension - **0.7.0**

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#187
