### ISSUE TITLE
How to make "stopOnEntry": false  default ?

### ISSUE THREAD

**Issue by eromoe** [DonJayamanne/pythonVSCode#1239]
Hi, 

 I already bear this for several month(because I almost did not use vscode to debug) ， sorry but I just hate this stopOnEntry behavior.

Today I search for it, and understand  every time vscode open a project will auto gen a config with `"stopOnEntry": true`.  How do I force vscode use `stopOnEntry: false`, without edit the config file ??

**Comment by DonJayamanne** [comment]
Unfortunately that's the default behavior.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#188
