### ISSUE TITLE
Not renaming a variable in sequence assignment

### ISSUE THREAD

**Issue by alexb5dh** [DonJayamanne/pythonVSCode#124]
Consider the following bit of code:

```python
var1, var2 = 1, 2
print var1, var2
```

Renaming `var1` or `var2` when selected in the second line works as expected.
However, trying to rename any of them after selecting in the first line yields no result.

**Comment by DonJayamanne** [comment]
Hi, apologies for the delay. I have been able to replicate this issue and will look into this soon.

**Comment by DonJayamanne** [comment]
Closing this issue as this is an issue in the jedi library being used.
