### ISSUE TITLE
Can't exclude variables from ctags

### ISSUE THREAD

**Issue by grantmcconnaughey** [DonJayamanne/pythonVSCode#1242]
## Environment data
VS Code version:  1.16.1
Python Extension version:  0.7.0
Python Version:   3.6.2
OS and version:    macOS Sierra

## Actual behavior

Adding `--python-kinds=-iv` to `~/.ctags`, `{workspace}/.ctags`, and `~/.vscode/extensions/donjayamanne.python-0.7.0/resources/ctagOptions` will not exclude variables from symbol search.

## Expected  behavior

The module variables should be hidden from search.

## Steps to reproduce:  
-  Search workspace symbols for a module-level variable like `logger` (from `logger = logging.getLogger(__name__)` or something)
-  Notice that many instances of `logger` appear

## Logs
Output from ```Python``` output panel  
```
----------Generating Tags----------
ctags --options=/Users/grant/.vscode/extensions/donjayamanne.python-0.7.0/resources/ctagOptions --languages=Python --exclude=**/site-packages/** --exclude=.venv/** --exclude=tests/** --exclude=*.egg-info/** -o /Users/grant/git/myproject/.vscode/tags .
```   

Output from ```Console window``` (Help->Developer Tools menu)
Nothing

**Comment by DonJayamanne** [comment]
Does it work for you if you generate the tags file manually?

**Comment by DonJayamanne** [comment]
Please use https://github.com/universal-ctags/ctags instead (this is a known bug)
https://stackoverflow.com/questions/46203565/exuberant-ctags-ignores-python-kinds-option

**Comment by grantmcconnaughey** [comment]
I installed universal ctags with Homebrew and that fixed it. Thank you!
