### ISSUE TITLE
run python file in terminal and run selection in terminal both use python terminal  

### ISSUE THREAD

**Issue by shelper** [DonJayamanne/pythonVSCode#1246]
## Environment data
VS Code version:  1.16.1
Python Extension version:  0.7.0
Python Version:   3.5
OS and version:    windows 7 pro

## Actual behavior
"run python file in terminal" and "run selection in terminal" both use python terminal , thus "run selection"works as it is just python expression in python shell but "run python file" failed as python shell does not run executable such as "python.exe"
## Expected  behavior
"run python file in terminal" should use python shell and "run selection in terminal" should use system shell 

## Steps to reproduce:  
-  
-  

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```
![image](https://user-images.githubusercontent.com/546163/30931606-26066d00-a393-11e7-8647-7838a79598c6.png)

**Comment by DonJayamanne** [comment]
Related to https://github.com/DonJayamanne/pythonVSCode/issues/419
