### ISSUE TITLE
JSON schema for .condarc and environment.yml files

### ISSUE THREAD

**Issue by brettcannon** [DonJayamanne/pythonVSCode#1248]
The [most popular YAML editor](https://marketplace.visualstudio.com/items?itemName=adamvoss.yaml) will do validation of YAML files using JSON schemas. Providing schemas for `.condarc` and `environment.yml` should cover the major config formats for Anaconda.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#189
