### ISSUE TITLE
too-long doc string in hover window is out of bounds

### ISSUE THREAD

**Issue by SLAPaper** [DonJayamanne/pythonVSCode#125]
- VSCode Verson: 1.10
- OS Version: Windows 10 (Build 14342)

When the mouse hover above some object with a too-long doc string, the hover window may extend out of bounds and leave some content unreadable. Show as below:

![hierarchicalpy - visual studio code_2016-5-14_2-12-0_no-00](https://cloud.githubusercontent.com/assets/7543632/15257524/46480b82-1979-11e6-9882-cd80bd22e3bd.png)

At this time, I have to `Alt-F12` to check out what I'm looking for.

Is there anyway to add a scroll bar to the hover window? Or even just show the top several lines of the doc string may be better, because the general description is often at the beginning, rather than the end.

Thanks!

**Comment by DonJayamanne** [comment]
Sorry but this is how vs code deals with large text. Closing as it is similar to #113
