### ISSUE TITLE
Debug error when finished running code in integrated/external terminal

### ISSUE THREAD

**Issue by JasonGoemaat** [DonJayamanne/pythonVSCode#1250]
## Environment data
VS Code version:  1.17.0-insider
Python Extension version:  0.7.0
Python Version:   3.6.2
OS and version:    Windows 10

## Actual behavior
Program debugs in terminal (either integrated or external) and a prompt not in the source appears when the program is finished:

    Press any key to continue . . .

After pressing a key, either A) External terminal closes or B) Integrated terminal returns to the command prompt.  At the same time an error pops up at the top of the visual studio code window that I have to close:

    [Error] Debug adapter process has terminated unexpectedly
    

## Expected  behavior

After program has finished and I press a key, no error message is displayed

## Steps to reproduce:  
-  Create sample python file, i.e. "print('Hello, world')"
-  Debug the file using either the external or integrated terminals

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
Debug adapter process has terminated unexpectedly          messageService.ts:125
    e.doShow                               @messageService.ts:125
    e.show                                 @rawDebugSession.ts:104
    _.onServerExit                         @rawDebugSession.ts:526
    (anonymous)                            @rawDebugSession.ts:440
    emitTwo                                @events.js:111
    emit                                   @events.js:194
    __dirname.ChildProcess._handle.onexit  @internal/child_process.js:215

```

**Comment by DonJayamanne** [comment]
> prompt not in the source appears when the program is finished:

What do you mean by the above statement.

Does the debug window display the text ```Hello, world```

**Comment by General-Gouda** [comment]
I am also getting the same error after every debug session. See attached GIF for demonstration.

VS Code version: 1.17.2
Python Extension version: 0.7.0
Python Version: 3.6.2
OS and version: Windows 10 Creators Update v10.0.15063

![image](https://user-images.githubusercontent.com/16738800/31780374-8818af3a-b4c3-11e7-8fbd-b38700253de6.png)

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#191

**Comment by MinMengbin** [comment]
Error: Debug adapter process has terminated unexpectedly (exit code: null)

Linux: Ubuntu 16.04
Code: Version: 1.28.2
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:20:56.183Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

debug.log

3:06:53 pm, 18/10/2018
Started @ Thu Oct 18 2018 15:06:53 GMT+1030 (ACDT)
From Client:
Content-Length: 313

{"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"python","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-gb"},"type":"request","seq":1}
To Client:
Content-Length: 687

{"seq":1,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsExceptionInfoRequest":true,"supportsConfigurationDoneRequest":true,"supportsConditionalBreakpoints":true,"supportsSetVariable":true,"supportsExceptionOptions":true,"supportsEvaluateForHovers":true,"supportsModulesRequest":true,"supportsValueFormattingOptions":true,"supportsHitConditionalBreakpoints":true,"supportsSetExpression":true,"supportsLogPoints":true,"supportTerminateDebuggee":true,"supportsCompletionsRequest":true,"exceptionBreakpointFilters":[{"filter":"raised","label":"Raised Exceptions","default":false},{"filter":"uncaught","label":"Uncaught Exceptions","default":true}]}}
From Client:
Content-Length: 588

{"command":"launch","arguments":{"name":"Python: Current File (Integrated Terminal)","type":"python","request":"launch","program":"/home/robotin/Documents/Visual Studio/python_code_ws/pyrun.py","console":"integratedTerminal","stopOnEntry":true,"logToFile":true,"pythonPath":"/usr/bin/python3","cwd":"/home/robotin/Documents/Visual Studio/python_code_ws","envFile":"/home/robotin/Documents/Visual Studio/python_code_ws/.env","internalConsoleOptions":"neverOpen","debugOptions":["StopOnEntry","RedirectOutput"],"__sessionId":"ed86d1c4-f44a-47de-94b4-6905b966e88e"},"type":"request","seq":2}
To Client:
Content-Length: 440

{"command":"runInTerminal","arguments":{"kind":"integrated","title":"Python Debug Console","cwd":"/home/robotin/Documents/Visual Studio/python_code_ws","args":["/usr/bin/python3","/home/robotin/.vscode/extensions/ms-python.python-2018.9.0/pythonFiles/experimental/ptvsd_launcher.py","35145","/home/robotin/Documents/Visual Studio/python_code_ws/pyrun.py"],"env":{"PYTHONIOENCODING":"UTF-8","PYTHONUNBUFFERED":"1"}},"type":"request","seq":2}
From Client:
Content-Length: 94

{"type":"response","seq":3,"command":"runInTerminal","request_seq":2,"success":true,"body":{}}
