### ISSUE TITLE
Unable to install pylint behind SSL proxy

### ISSUE THREAD

**Issue by jamiewalters** [DonJayamanne/pythonVSCode#1251]
## Environment data
VS Code version: 1.16.1 
Python Extension version:  0.7.0
Python Version:   3-5-1
OS and version:    CentOS7

## Actual behavior
Can not install pylint from within vscode where it is required to add --trusted-host, this is useful in corporate environments where there an SSL proxy server.
## Expected  behavior
Should install or be able to accept a configuration for additional pip arguments.
## Steps to reproduce:  
-  
-  

## Logs
Output from ```Python``` output panel  

Output from ```Console window``` (Help->Developer Tools menu)
/opt/rh/rh-python35/root/usr/bin/python -m pip install pylint
[dev@localhost ~]$ /opt/rh/rh-python35/root/usr/bin/python -m pip install pylint
Collecting pylint
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9a546a7ef0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pylint/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9a546a7748>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pylint/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9a546a7a90>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pylint/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9a546a7978>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pylint/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9a546a7588>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pylint/
  Could not find a version that satisfies the requirement pylint (from versions: )
No matching distribution found for pylint

**Comment by brettcannon** [comment]
You can also install pylint manually, and as long as it can be imported by the Python interpreter you have set up for VS Code to use it will also work. Because of that I don't think the automatic install when clicking the install button from the banner needs to be more complicated for this specific use-case. What do you think @DonJayamanne ?

**Comment by DonJayamanne** [comment]
Agreed. The whole purpose of displaying the installation process to the user is so they could run it manually if things don't work as expected, and this is one of those instances.

You could try a more generic solution (https://stackoverflow.com/questions/45337029/pip-conf-not-paying-attention-to-trusted-host).

Closing as this is an environment issue.
