### ISSUE TITLE
Autoformatting formats HTML files

### ISSUE THREAD

**Issue by testvinder** [DonJayamanne/pythonVSCode#1252]
## Environment data
VS Code version:  1.16.1
Python Extension version:  0.7.0
Python Version:  3.6.1
OS and version: Windows 10

## Actual behavior
Auto formatting formats HTML files, not just .py files
## Expected  behavior
I expect formatting to only autoformat .py files.
## Steps to reproduce:  
I happens if I set add the following to settings:
"editor.formatOnSave": true,
"python.formatting.provider": "autopep8",
-

**Comment by DonJayamanne** [comment]
use ```pythonSettings.formatting.formatOnSave``` instead.
