### ISSUE TITLE
r

### ISSUE THREAD

**Issue by sillygoose4u** [DonJayamanne/pythonVSCode#1254]
## Environment data
VS Code version:  
Python Extension version:  
Python Version:   
OS and version:    

## Steps to reproduce:  
-  
-  

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
@sillygoose4u please provide more information an reopen the issue.
