### ISSUE TITLE
Cannot attach to running module. +question about embedding

### ISSUE THREAD

**Issue by qpIlIpp** [DonJayamanne/pythonVSCode#1256]
## Environment data
VS version:   vs prof 2015, 14.0.25431.01 up3.
Python tools for visual  studio: 2.2.50113.00
Python Version:   python-3.5.2. Win32 on both machines
OS and version:   winserver2012.r2 + win10 enterprise

## Actual behavior
cannot attach to remote python

## Expected  behavior
attach is successful 

## Steps to reproduce:  
I have 2 windows machines. Visual studio 2015 + pyt tools is installed on winserv machine. Python 3.5.2 is installed on both machines.
first of all, python asks me to upgrade pip (python -m pip install --upgrade pip) (see log) on both machines, after that ptvsd version is "ptvsd-3.2.1.dist-info"
I created pytyhon project, which contains code from https://docs.microsoft.com/en-us/visualstudio/python/debugging-cross-platform-remote , copy script on the second machine and started from "python.exe" console (just "import my" command), so it has started and I tried to attach from the first machine.
Firewalls are turned off on both machines. All info about the environment is in the header.
I got exception "remote server at tcp://aaaaaaaa@ip:5678/ is not a Python Tools for Visual Studio remote debugging server, or its version is not supported". After I clicked cancel I got "unable to connect to '..'. Operation not supported, Unknown error: 0x80004005."
So I have the same python on both machines, the same modules, the same ptvsd versions on both win machines, have turned off firewalls, but still cannot connect. What am I doing wrong?

In addition, I want to know: I have written my own c++ app, which is using python C API (py_init, py_invoke etc), am I able to debug with ptvsd my custom C++ application, which is using CPython C API?

## Logs
cmd installation:
c:\Python>python -m pip install --upgrade pip
Collecting pip
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
    100% |################################| 1.3MB 706kB/s
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Uninstalling pip-8.1.1:
      Successfully uninstalled pip-8.1.1
Successfully installed pip-9.0.1

c:\Python>pip3 install ptvsd
Requirement already satisfied: ptvsd in c:\python\python35-32\lib\site-packages

**Comment by DonJayamanne** [comment]
The latest version of PTVSD is not supported by this extension. Please revert to the older version 3.0.0.

**Comment by qpIlIpp** [comment]
Ok, thnx. But what's about second part of question about embedding?

**Comment by DonJayamanne** [comment]
@qpIlIpp 
My sincerest apologies, this is NOT an issue related to Visual Studio **Code** (cross platform editor), you are using the big brother PTVS (Visual Studio 2015 Pro for Windows).

I'll move this issue soon, please disregard my previous comments.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/PTVS#3094
