### ISSUE TITLE
Improvements to interpreter switching

### ISSUE THREAD

**Issue by Kavakuo** [DonJayamanne/pythonVSCode#1260]
## Actual behavior
Trying to switch the interpreter with the menu action _"Python: Select Workspace Interpreter"_ when **no** workspace is opened, an error appears which says _"Please open a workspace to select the Python Interpreter"_.

## Expected  behavior
Switching the interpreter should always be possible, whether a workspace is opened or not. When no workspace is opened, it should change the `python.pythonPath` settings in the user-settings, because editing this by hand is very frustrating. And because there already is a very nice UI for switching interpreters, it would be very sad if we can only use this in workspaces. 

When a workspace is opened, everything should work as before by setting the workspace specific settings without touching the user-settings.

With this feature it will be easy to debug and run quick and dirty standalone python scripts with your desired interpreter. I think many people have not always a dedicated folder that could represent a workspace for small scripts and sometimes it is very handy to switch quickly between python 2 und 3 or to a virtual environment with some libraries installed.

## Steps to reproduce:  
- Open a single python file in VSCode  
- Try to switch the interpreter with the _"Python: Select Workspace Interpreter"_ action in from the menu.

This is already implemented in #1257. If you want to try it, go for it. @DonJayamanne mentioned he has some concerns about this feature. Maybe I oversee any side effects this would have. I'm interested in your opinions.

**Comment by DonJayamanne** [comment]
Agreed, would it be possible to create a separate PR for this instead of merging two separate issues into a single PR. Thanks.

Also, please change the variable from ```configurationTarget ``` to ```global```.

**Comment by Kavakuo** [comment]
Ok, I will do this tomorrow. Should I rename the option from "Python: Select Workspace Interpreter" to "Python: Select Interpreter", too?

**Comment by DonJayamanne** [comment]
Yes please
