### ISSUE TITLE
Shebang detection

### ISSUE THREAD

**Issue by Kavakuo** [DonJayamanne/pythonVSCode#1261]
Switching an interpreter is sometimes necessary in the python world. So to start a python script you have to specify the whole path of your interpreter. If you use virtual enviroments this could be very complicated. To avoid this you can insert a Shebang at the top of the file. The line starts with `#!` followed by the path of your interpreter. After that you have to apply execution permissions for this file. Then it is possible to execute the python file with the right interpreter without specifying the complete path at every run.

## Actual behavior
Open a python file with shebang inside VSCode. Nothing happens the python interpreter is not changed, you have to edit the user settings and set the `python.pythonPath` to the interpreter specified in the shebang.

## Expected  behavior
When opening the file, the user should be prompt that the current python interpreter is another than the interpreter in the shebang. The user should have the option to change the interpreter right away. After that VSCode would run and debug this script with the correct interpreter, so you don't need to edit the settings file by hand.
In addition the check, if the selected interpreter is still the right one, happens every time the user saves the file (you might run the file at next).

## Steps to reproduce
- Open a python file with shebang inside VSCode. 

## Some kind of problems
This works great without a workspace opened. But what should happen when a workspace is open and the shebang interpreter in a python file inside this workspace is another than the specified interpreter for this workspace?
I think to prompt (and warn) the user that the interpreter is different could prevent some errors in deployment.

## Demo
![gif](https://dsh.re/45c5e)

This is already implemented in #1257. If you want to try it, go for it. @DonJayamanne mentioned he has some concerns about this feature. Maybe I oversee any side effects this would have. I'm interested in your opinions.

**Comment by DonJayamanne** [comment]
1. Is the option 'Don't ask again' a global setting, works pace setting or specific to each file?  
Personally I believe this should be a global setting.  

2. Also, how about removing the command ```Set Interpreter to Shebang``, and instead we add a ```Code Lens``` just above the shebang in the python file.  
This way, the user would know immediately that they can change the interpreter when a ```Code Lens``` with the text ```Change Interpreter to Shebang```` (or the like) is displayed.

(FYI - Code lens is the little hyplink that appears over the method names and the like).
With this option in place, even if the prompt is disabled, the feature is still accessible via this ```code lens```. 

@Kavakuo @brettcannon @gandhis1 @symbioticKid @robodair (would very much appreciate your input on this).

**Comment by brettcannon** [comment]
I could see reading the shebang to choose an interpreter if none is already selected, but I wouldn't want to be prompted if I already had one chosen. If I have a virtual environment set up and then I open a file with a default shebang I really don't want to be bothered with a prompt asking if I want to switch.

And I do like Don's lens idea since that's unobtrusive while still getting the desired functionality, but I don't know how often that will be needed. I guess I can view this as a last-ditch effort to try and select an interpreter if one isn't already specified or found. As to whether the selection is automatic or provided through a lens I don't know.

**Comment by Kavakuo** [comment]
1. 'Don't ask again' is a global setting. It sets the `python.disableShebangDetection` option in the user settings file to true. After that it will never prompts you again.
2. `Code Lens` sounds great, I will look into this. It doesn't look that complicated to implement.

@brettcannon I get your point. Maybe it should ignore shebangs to default interpreters and only prompt if the shebang interpreter is inside a virtual environment? Because in this case the chance is high that running the script with another interpreter than the specified one will fail.

**Comment by brettcannon** [comment]
RE: "don't ask again": I don't want to be asked to begin with. 😉 

So my thinking is that if you bothered to set an interpreter then you know what you want (plus "explicit is better than implicit" 😄 ). I'm basically viewing this feature request as "I'm too lazy to select or type in the path", which means I want to minimize the impact on everyone else who wasn't "lazy".

I think the code lens is probably the best compromise here if the overhead of maintaining it isn't too high.

**Comment by DonJayamanne** [comment]
I guess we're all in agreement that we drop the prompt.

What about the command from the command pallet? I don't see the need for this if the code lens is available.

**Comment by brettcannon** [comment]
@DonJayamanne agreed

**Comment by Kavakuo** [comment]
I think your point works as long as you work inside workspaces. But if you open a single python file inside VSCode without a workspace, the interpreter is set to the one specified inside the user settings. In this case your explicit setting is the interpreter specified in the shebang.

But I agree, code lens is a great compromise 😉 Is it possible to disable code lens globally for all extensions? I'm relatively new to VSCode. If so, I think it would have a justification, otherwise not.

**Comment by DonJayamanne** [comment]
I don't think anyone would disable code lenses, don't need to worry about that. To answer your question, I don't know if it can be done.

**Comment by Kavakuo** [comment]
I just looked into the settings. It seems that you can set `editor.codeLens` to `false` to disable it. But yeah, I think we don't need the command inside the command pallet.

I will try to implement the code lens thing tomorrow.

**Comment by Kavakuo** [comment]
Done. The CodeLense is labeled with "Set interpreter to shebang". I don't know if that's the best solution, maybe you have other ideas.

The CodeLense refreshes when the configuration changes and disappears, if the selected interpreter and the shebang interpreter are equal.

**Comment by brettcannon** [comment]
Maybe the code lens could set "Set as interpreter"? The context of being attached to the shebang should hopefully make it obvious what you're choosing.

**Comment by Kavakuo** [comment]
Changed this in the last commit. Unittests are also included. If you need something else before merging, just let me know.
