### ISSUE TITLE
auto completion for custom modules 

### ISSUE THREAD

**Issue by cg-cnu** [DonJayamanne/pythonVSCode#1265]
## Environment data
VS Code version:  1.16.1
Python Extension version:  0.7.0
Python Version:   3.5.1
OS and version:    windows 10

I am trying to get the auto completion working for a custom module `bpy` used in [blender](blender.org)

## Actual behavior

Not able to get auto completion working;

I edited settings as mentioned in this [article](https://donjayamanne.github.io/pythonVSCodeDocs/docs/troubleshooting_intellisense/)

![image](https://user-images.githubusercontent.com/2767425/31113118-49fbc79a-a835-11e7-97a1-d4dd2428dfa1.png)

As you can see in the image; I was able to get auto completion for `bpy.` but not after `bpy.context.`
You can see the auto completion for `context` in a blender shell for the `bpy` module.

## Expected  behavior
Provide autocomplete 

## Steps to reproduce:  
-  Download [blender](https://www.blender.org/download/).
- Setup workspace settings as shown in the image. 
- Try importing bpy and setup autocomplete.

**Comment by munrocket** [comment]
I have same problem with part of package ccxt
'''
import ccxt.async as ccxt
ccxt.<intellisense>
'''
Code like this not provide intellisense/autocomplection

**Comment by munrocket** [comment]
I have same problem with part of package ccxt
```
import ccxt.async as ccxt
ccxt.<intellisense>
```
Code like this not provide intellisense/autocomplection

**Comment by cg-cnu** [comment]
Hey guys! 
Intellisense is working fine for the custom modules I have written but not with the ones provided by blender. I am trying to get down and debug this one. Should I look into anything specific ? Is there anything the module should or shouldn't do to get the intellisense working ?

**Comment by DonJayamanne** [comment]
Hi @cg-cnu, I haven't looked into this yet. Will check this out. At this stage no, pointers.
FYI - I'm using [Jedi](http://jedi.readthedocs.io/en/latest/) to provide intellisense within the extension.
It would be easier to test the library with custom paths. if it works there, then its most certainly a bug in the extension.

**Comment by cg-cnu** [comment]
@DonJayamanne So, I got some help from the blender community. Found this [fake bpy module](https://github.com/nutti/fake-bpy-module) and pointing the `autocomplete.extrapaths` to it gave a dummy auto completion. So, I assume the issue is with the module not the addon. Let me know if I can give any more details 😄

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#194
