### ISSUE TITLE
Set multiple values manually for python.pythonPath

### ISSUE THREAD

**Issue by jmagosta** [DonJayamanne/pythonVSCode#1268]
## Environment data
VS Code version:  1.16.1
Python Extension version:  0.7.0
OS: Wndows 10

## Actual behavior

An array with multiple values in the user settings for `python.pythonPath` are not recognized by the plugin.  The value it expects is a string.   Only one value is shown. 

## Expected  behavior

Show multiple paths in the dropdown to be able select active python interpreter among more than one choice . 

## Steps to reproduce:  

- The `user settings` include this json;
```
          "python.pythonPath": "C:\\Users\\myhome\\AppData\\Local\\amlworkbench\\Python; C:\\Program Files\\Microsoft\\R Server\\PYTHON_SERVER"
```   

- Running` Python: Select Workspace Interpreter` shows a previously cached value. 

Either the array is not parsed properly, or the choices for Select Workspace Interpreter are not updated from the json

**Comment by DonJayamanne** [comment]
PythonPath only supports a single value. Not multiple.
Currently there's no way to configure the list displayed in ```Python: Select Workspace Interpreter```.
The next version will have a few more entries displayed in this list (https://github.com/DonJayamanne/pythonVSCode/issues/1147)
