### ISSUE TITLE
Add command line argument option to run in terminal

### ISSUE THREAD

**Issue by jmagosta** [DonJayamanne/pythonVSCode#1269]
## Actual behavior

`run python file in terminal` has no option to set command line arguments.  The workaround is to let the launch return an error, then edit the command line in the terminal to include the arguments. 

## Expected  behavior

Have an command that sets the command line arguments, possibly by adding an entry to
the configurations array in `launch.json`

**Comment by DonJayamanne** [comment]
@jmagosta can you not use the debug option:
Here's 
1. Create a launch.json file (this gets created when you try to debug a program)
2. Add a new entry into the json file as follows:
```json
        {
            "name": "Python program with Args",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ],
            "args": [
                "1","A", "B"
            ]
        },
```

This gives you the option of debugging as well.
At this stage I'm reluctant to add custom arguments when running via a terminal, as the debug option (with the setting ```stopOnEntry:false``` will serve the same purpose.

**Comment by DonJayamanne** [comment]
Ooops, close accidentally

**Comment by DonJayamanne** [comment]
@jmagosta have you managed to try the suggested approach.

**Comment by jmagosta** [comment]
Don -  Works nicely, thanks.   Do you know if anyone has thoughts about exposing a tool for launch.json settings?

**Comment by brettcannon** [comment]
Beyond the JSON schema support that VS Code provides there's nothing I know of. And knowing how the VS Code team prefers to just let people edit JSON directly I don't see any official `launch.json` tool coming about.
