### ISSUE TITLE
Afdd "pythonPath": "/usr/bin/python3" to launch.json and cannot start debugging

### ISSUE THREAD

**Issue by dynorphin** [DonJayamanne/pythonVSCode#127]

**Comment by dynorphin** [comment]
is add not afdd

**Comment by DonJayamanne** [comment]
What's the error you are getting?

**Comment by dynorphin** [comment]
Nothing,just print "canceled"

**Comment by DonJayamanne** [comment]
Does it print this message or is it displayed in a little message box (top)

**Comment by DonJayamanne** [comment]
What is the code you are trying to debug? 
Have you tried debugging something as simple as a print statement.

**Comment by dynorphin** [comment]
Yes!I just write "import sys;"

**Comment by DonJayamanne** [comment]
Hi, i'm looking into there. There are a few issues related to the debuggers that i'm looking at.

**Comment by DonJayamanne** [comment]
Hi @dynorphin , please could you upload or paste the contents of your launch.json file?
Thanks

**Comment by dynorphin** [comment]
Oh! I am so sorry about I have no time these days, I formatted the system just now! So I will make my best to rewrite  it. ^_^"
`` 
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Debug",
			"type": "gdb",
			"request": "launch",
			"target": "${file}.o",
			"cwd": "${workspaceRoot}",
                        "preLaunchTask": "g++"
		}
	]
}
``
and here is the tasks.json
``
{
    "version": "0.1.0",
    "command": "g++",
    "args": ["-g", "${file}", "-o", "${file}.o"],
    "problemMatcher": {
        "owner": "cpp",
        "fileLocation": ["relative", "${workspaceRoot}"],
        "pattern": {
            "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
            "file": 1,
            "line": 2,
            "column": 3,
            "severity": 4,
            "message": 5
        }
    }
}
``
I copy these json from a blog, it works well on windows 10 but here is some problem in Ubuntu gnome 16.04.By the way, I could only have the error feedback when I using GDB. Not like the default debug setting when using node.js, python. Such as watch point ,breakpoint, single step mode.

**Comment by DonJayamanne** [comment]
Hi @dynorphin , yes that config is wrong and it isn't using the Python debugger, it is using gdb. Please delete the launch.json and re-generate it by selecting the "Python" debug configuration when attempting to debug. Thanks for checking it out.
