### ISSUE TITLE
How to setup linting using Ubuntu Bash on Windows 10?

### ISSUE THREAD

**Issue by batatop** [DonJayamanne/pythonVSCode#1279]
Hi,

I'm using VSCode with Ubuntu Bash on Windows 10. Everything works except linting. It gives an error which is: "Linter pylint is not installed.". I think the problem is caused by the location of pylint. However, I couldn't find the solution. I would appreciate any help. Thank you.

**Comment by DonJayamanne** [comment]
Unfortunately this isn't completely supported yet. Closing in favor of #534 
https://github.com/DonJayamanne/pythonVSCode/issues/534

**Comment by DonJayamanne** [comment]
Currently this isn't supported Closing in favor of #534 
https://github.com/DonJayamanne/pythonVSCode/issues/534

**Comment by batatop** [comment]
Thank you for your response.
