### ISSUE TITLE
Add interactive -i to launch python console app

### ISSUE THREAD

**Issue by fdanny** [DonJayamanne/pythonVSCode#128]
I'm able to debug using the Python console app and works to execute a script and debug. I want the ability to launch console app in interactive mode. I would like to interact in debug mode so I can step into different parts of my code. 

I'm not sure if this is supported but I couldn't figure how to pass -i to python. I didn't see an option in debugOptions.

**Comment by DonJayamanne** [comment]
Hi debugging of python console apps in an interactive mode is supported on windows. 
Debugging interactive console apps is supported on windows in the current version.
The next version (hopefully in a day or so) will add support for Macs too.
Hope that helps you.

**Comment by fdanny** [comment]
Cool. I'm developing on Windows but currently my app starts, executes and exits. How do I enable interactive mode on Windows with a console app?

**Comment by DonJayamanne** [comment]
1. If you want to ensure the program breaks when running then set a breakpoint and/or configure it to break when it starts
2. If you want to capture input via console apps in python then use the raw_input function.
