### ISSUE TITLE
Intellisense 

### ISSUE THREAD

**Issue by IlanHindy** [DonJayamanne/pythonVSCode#1283]
## Environment data
VS Code version: September 2017 
Python Extension version: 0.70 
Python Version: 3.6  
OS and version: windows 10  15063.632  

## Actual behavior
I managed to run debugger 
I am working from anaconda 
It seems that the editor does not recognize intellisense meens:
when I type a module name and print . it does not know how to continue (give a list of classes etc.)
when I type a name of a method I expect it will give me a list of the parameters
when I get a list for auto complete It:
gives me a list which is not context related (all the words possible)
no icons that says whether the auto complete is a method variable  class etc.
PyLint does not recognize the classes/modules etc..

## Expected  behavior
See above

## Steps to reproduce:  

1. Install anaconda
2. Create a new anaconda environment
3. install VS code
4. install python extension
5. (I also tried to install code runner after I did not get the expected results)
6. enter anaconda terminal
7. activate the anaconda environment
8. activate vs code on code files
My setting.jason:
```
{
      "python.pythonPath": "C:/Users/IlanH/Anaconda3/envs/${env:CONDA_DEFAULT_ENV}/python",         
      "python.linting.pylintEnabled": true,
}

```
```
My launch.jason
`
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
    
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            //"program": "${file}",
            //"program": "C:\\ArtificialIntelligence\\ArtificialIntelligence\\Python\\Projects VS Code\\ArtificialIntelligence_\\ArtificialInteligence\\ArtificialIntelligence.py",
            "program": "${workspaceRoot}\\ArtificialInteligence\\ArtificialIntelligence.py",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }
    ]
}`
`

-  
-  

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
Please could you provide a code sample? 
the description you have provided is quite vague, as intellisense does work for anaconda.

**Comment by IlanHindy** [comment]
[Create documentation.txt](https://github.com/DonJayamanne/pythonVSCode/files/1366747/Create.documentation.txt)
of course the original file extension is py
another thing I discovered (I am quit new in vs code so it might be nothing) is that if I choose 
the command : 
Python:Build Workspace Symbols
I get the following error:
ENOENT: no such file or directory, mkdir 'C:\Program Files\Microsoft VS Code\"c:\ArtificialIntelligence\ArtificialIntelligence\Python\Projects VS Code\ArtificialIntelligence_\.vscode' 
where my working directory is : 
"c:\ArtificialIntelligence\ArtificialIntelligence\Python\Projects VS Code\ArtificialIntelligence_\.vscode' 
Hope this will help
Thanks,
Ilan

**Comment by DonJayamanne** [comment]
What is the code sample and what line number is it not working at, please help me to help you. The file contains a lot of other stuff in there.

**Comment by IlanHindy** [comment]
I will tell you what I expected. (I saw it works in one of the videos)
1. As you saw I use PyQt5 so if I type 'Q' I expect to see all the possible classes in PyQt5 (at lease the ones
 that begins with 'Q')
2. If I write the name of a class and then . I expect to see all the members of the class
3. Pylint does not recognize the PyOt classes and the modules and the classes (under the class name there is the error line and the error says 'E602 Undefined variable ...' 
4. In the auto complete there is a list of all the names I used in the application and it not context sensitive (for example if I type 'self. ' and then 'a' It gives me all the names in the project that begins with a
5. I the auto complete list there are no relevant icons at the left of the name (so I can distinguish between method variable etc..
6. There is also the error for loading symbols that I told you about in the prev comment

for example in the code I sent you In line 34 there is a definition of QApplication the pylint says it is not recognized variable
 

![error](https://user-images.githubusercontent.com/20102357/31325417-95a6725a-acc5-11e7-8375-12f4e2f7d831.png)

**Comment by IlanHindy** [comment]
I accidently closed the issue can you reopen It

**Comment by DonJayamanne** [comment]
Please ensure PyQt is install is installed in the python environment you are using. 
Ensure the python environment is configured in your workspace settings (settings.json).

**Comment by IlanHindy** [comment]
I know that the PyQt is installed (Otherwise I would have not been able to run the code)

My setting.jason is:
`{
     "python.pythonPath": "C:/Users/IlanH/Anaconda3/envs/${env:CONDA_DEFAULT_ENV}/python",         
     "python.linting.pylintEnabled": true,
}`

**Comment by DonJayamanne** [comment]
>I know that the PyQt is installed (Otherwise I would have not been able to run the code)

I wanted to ensure it was installed in the python environment you have configured vscode to look at.

**Comment by IlanHindy** [comment]
is my setting.Jason correct or do I have to add something to it?
please refer also to the problem that occurs when I try to use the command: 
Python:Build Workspace Symbols
I get the following error:
ENOENT: no such file or directory, mkdir 'C:\Program Files\Microsoft VS Code"c:\ArtificialIntelligence\ArtificialIntelligence\Python\Projects VS Code\ArtificialIntelligence_.vscode'
where my working directory is :
"c:\ArtificialIntelligence\ArtificialIntelligence\Python\Projects VS Code\ArtificialIntelligence_.vscode'
thanks 
Ilan

**Comment by riverar** [comment]
Can you verify changing `from [lib] import *` to `import [lib]` fixes the issue? (Obviously, you need to update your code sample.) Not saying it's a proper fix but I noticed things behave with this configuration.

**Comment by riverar** [comment]
Intellisense is extremely problematic, in fact I've never had it working properly in VSCode since the inception of the extension. Extremely frustrating, and probably not even directly your bug.

https://github.com/DonJayamanne/pythonVSCode/issues?q=is%3Aissue+is%3Aopen+label%3AIntellisense

**Comment by IlanHindy** [comment]
I understand that but the problem is that I have no intellisense at all that leads me to the assumption that there is a parameter or something not set in my environment

**Comment by IlanHindy** [comment]
I solved the problem
I one is using anaconda he has to (in this order): 
1. enter anaconda
2. enter the environment
3. install python extention
4. activate the command : Python:Select workspace interpreter
5. then It would give him the right anaconda environment to select from
(Note that I think it's a bug in the implementation of the command : 
If there is anaconda it should give an opotunity to select from all anaconda environments
or at least give a warning about that)
Thank you all for the help
Ilan
