### ISSUE TITLE
"Debug Test (Multiple)" does not work

### ISSUE THREAD

**Issue by cryptomaniac512** [DonJayamanne/pythonVSCode#1284]
## Environment data
VS Code version:  1.17.0
Python Extension version:  0.7.0
Python Version:   3.6
OS and version:    Linux 4.12.13

I have a parametrized `pytest` function and breakpoint inside it. Above the function there is a "button" `Debug Test (Multiple)"

## Actual behavior
When I press `Debug Test (Multiple)`, I'm asked to select a test case, then the test is performed

## Expected  behavior
When I press `Debug Test (Multiple)`, I'm asked to select a test case, then the debug session begins

## Steps to reproduce:  
- 
```
@pytest.mark.parametrize("param", [
    "param0",
    "param1",
    "param2",
])
def test_something(param: str):
    assert param  # set brealpoint here
```
-  run `Debug Test (Multiple)` (link above the function)

**Comment by DonJayamanne** [comment]
just to be clear, the problem is, the test is run without attaching the debugger.
