### ISSUE TITLE
remote debug error

### ISSUE THREAD

**Issue by naeco2005** [DonJayamanne/pythonVSCode#1286]
when i remote debug a python script with VS code, i always see the below error:
```
TypeError, __init__() missing 2 required positional arguments: 'old_out' and 'is_stdout'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: __init__() missing 2 required positional arguments: 'old_out' and 'is_stdout'
Error in sys.excepthook:
Traceback (most recent call last):
  File "D:\Neutron\main\src\Lib64\Debug_Build\Debug\Python\lib\site-packages\ptvsd\visualstudio_py_debugger.py", line 2288, in _excepthook
    do_wait()
  File "D:\Neutron\main\src\Lib64\Debug_Build\Debug\Python\lib\site-packages\ptvsd\visualstudio_py_debugger.py", line 2413, in do_wait
    sys.__stdout__.write('Press any key to continue . . . ')
AttributeError: 'NoneType' object has no attribute 'write'
```
i don't know what happens. can you tell if there is something wrong?

Thanks, 
-Neil

**Comment by DonJayamanne** [comment]
Please ensure you have version 3.0.0 of ptvsd.

**Comment by naeco2005** [comment]
Yes, i am using ptvsd 3.0.0.

**Comment by DonJayamanne** [comment]
Please could you provide a sample code you are using to replicate this issue.

**Comment by naeco2005** [comment]
Hi, 

My software is developed with C++ and QT (for UI). We embed a python process inside. When the Python process is initialized, we redirect stdout and stderr with the following codes:

import sys
class CatchOutput:
def init(self):
self.value = ''
def write(self, txt):
self.value += txt
def flush(self):
pass
catchOutput = CatchOutput()
sys.stdout = catchOutput

import sys
class CatchOutErr:
def init(self):
self.value = ''
def write(self, txt):
self.value += txt
catchOutErr = CatchOutErr()
sys.stderr = catchOutErr

i assume my issues are due to the above redirection. i also tried to derive CatchOutput and CatchOutErr from _DebuggerOutput in PTVSD, i also see the issue. 

Do you know the possible reason? how to resolve this issue?

Thanks, 
-Neil

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#198
