### ISSUE TITLE
be able to use ExtensionContext.storagePath as ctags storage location

### ISSUE THREAD

**Issue by joelhock** [DonJayamanne/pythonVSCode#1287]
Our project's .vscode directory is under source control, and although `.vscode/tags` could be added to our `.gitignore` file, it seems that storage for the ctags output naturally belongs in `ExtensionContext.storagePath`.  I know you can change the location also via the `python.workspaceSymbols.tagFilePath` setting, but there is no variable substitution that resolves to the storagePath; maybe adding a new variable substitution for that is the easiest way to allow for this.

**Comment by DonJayamanne** [comment]
Agreed

**Comment by DonJayamanne** [comment]
Closing as this won't work for multiple workspaces or multi-root environments.
