### ISSUE TITLE
Extension with Prospector linting gives false positives

### ISSUE THREAD

**Issue by zersiax** [DonJayamanne/pythonVSCode#1289]
## Environment data
VS Code version: Latest Insider as of now 
Python Extension version:   Latest version available in Marketplace
Python Version:    3.6
OS and version:     Windows 10 build 16299

## Actual behavior
In my problems view, I'm seeing errors about "no module named" followed by the path to the current file I'm in, e.g., c:\users\name\project\app\views.py). However, this code runs fine using the same Python context and gives no such errors.

## Expected  behavior
I shouldn't see these errors since they aren't errors.
## Steps to reproduce:  
-  (going to list everything I did, not sure what parts are relevant)

1. Create a new Django project in the home folder of WSL (Windows Subsystem for Linux).
2. Realize you can't reach that filesystem from Vs Code and copy the folder to your Windows home folder, e.g. c:\users\name\dev\.
3. Open the project in Visual Studio Code. Note that we're not using a virtual environment. One was created, but in WSL so it would be Linux-based and probably not useful to the Windows host. It is, however, present in the copied folder in my case, although it is not being used. Autopep8, prospector and Django 1.11 are installed to the global context using pip.
4. Open any given file, settings.py is fine.
5. At this point, I am already getting this error by Prospector about no module name ....../settings.py.
6. I tried feeding --uses django into the ProspectorArgs array in settings.json but this didn't fix the issue.

-

**Comment by DonJayamanne** [comment]
Unfortulately WSL isn't supported at this stage.
https://github.com/DonJayamanne/pythonVSCode/issues/534

**Comment by DonJayamanne** [comment]
Hopefully this will be resolved soon. Please follow the #534 for updates.

**Comment by zersiax** [comment]
@DonJayamanne From step 2 in my reproduce steps, WSL is completely out of the picture, so I don't think this is a WSL issue?

**Comment by DonJayamanne** [comment]
What's the path to your python virtual environment?
Please ensure this is configured in your workspace settings (settings.json), i.e. the setting ```python.pythonPath``` needs to point to the python interpreter you are working on.

**Comment by zersiax** [comment]
Python I'm working on is my Windows OS's global python install, which is added to the OS PATH environment variable. Wouldn't the extension pick it up at that point?

**Comment by DonJayamanne** [comment]
Yes it would.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#199
