### ISSUE TITLE
Error: NotImplementedError, cannot determine number of cpus

### ISSUE THREAD

**Issue by MichaelT0** [DonJayamanne/pythonVSCode#129]
I try to import sklearn package but received an error.

`from sklearn.tree import DecisionTreeRegressor`

Error message:
`NotImplementedError, cannot determine number of cpus`

The same code works on jupyter ipython well.

Many thanks

**Comment by DonJayamanne** [comment]
fixed in latest version

**Comment by Fluel** [comment]
I have the same problem, sklearn 0.19.1 installed but I try to execute via http/cgi the .py script and I do it locally with apache/XAMPP. If I run it from the console all goes ok.. while thru webpage/ajax/cgi it reports the error. It's really strange, any suggestion?
