### ISSUE TITLE
Allow user defined launch.json

### ISSUE THREAD

**Issue by eromoe** [DonJayamanne/pythonVSCode#1292]
Hi,

Is there anyway to create a user defined launch.json ?
I want to add `Pytest` to launch.json,  but I have to manually add that piece to each project. 

If allow user defined launch.json,  https://github.com/DonJayamanne/pythonVSCode/issues/1239  can be solved too.

feature would be:
1.  user defined launch.json
2.  a setting parameter :  overwrite current project's launch.json  to newest , when user defined launch.json changed (or current vscode is focused)

**Comment by DonJayamanne** [comment]
Currently this is defined in the extension, however the new VS Code API may allow for this.

**Comment by brettcannon** [comment]
I think VS Code needs to add support for this instead of us since it's a general feature and not language-specific.
