### ISSUE TITLE
Please, allow settings "python.files.eol" to force specific line-endings for new python files

### ISSUE THREAD

**Issue by bialix** [DonJayamanne/pythonVSCode#1293]
Is it possible for your extension to actually override VS Code settings 

"files.eol": xxx

to use something specific for new python files? Please?

E.g. I'm working on Windows and want all my new python files to be LF, but setting this globally for all files types is a bit overkill.

**Comment by brettcannon** [comment]
I think this would be better served as a feature request on VS Code to allow the "files.eol" setting to be acceptable in a language section, i.e. under `"[python]"` since this isn't specific to Python the language to languages in general.
