### ISSUE TITLE
Is there any way to setup multiple version pylints for same project

### ISSUE THREAD

**Issue by Jeyanthinath** [DonJayamanne/pythonVSCode#1294]
## Environment data
VS Code version:  1.17.0-insider
Python Extension version:  0.7.0
Python Version:   
OS and version:    Ubuntu 16.10

## Requirement 
I am working on a project with multiple python version support, it would be better , if there is an Option to enable multiple pylint for the vscode ?

**Comment by DonJayamanne** [comment]
Unfortunately no, this isn't supported. I haven't come across a setup where one would use multiple versions of linters instead of one for the same project.
Just out of curiosity, why multiple versions?

**Comment by Jeyanthinath** [comment]
I am working on a project with a multi version python compatibility of both python2 and python3. So I thought having two linters will solve this problem.

Otherwise if there is a linter for both python2&3 compatible, that also will help me out

**Comment by brettcannon** [comment]
PyLint will _lint_ both Python 2 and 3 code if that's what you're asking. If you're wondering if PyLint can be _run_ by both Python 2 & 3 then the answer is still yes.

I'm going to close this request as "wontfix" since the need isn't quite there to warrant that much complexity in the extension.
