### ISSUE TITLE
Intellisense missing documentation for built-in function

### ISSUE THREAD

**Issue by wgj** [DonJayamanne/pythonVSCode#1295]
## Environment data
VS Code version:  Version 1.17.1 (1.17.1)
Python Extension version:  0.7.0
Python Version:   Python 3.6.2
OS and version:   macOS 10.12.6

## Actual behavior
<img width="530" alt="screen shot 2017-10-10 at 2 01 41 pm" src="https://user-images.githubusercontent.com/463564/31410483-966ec440-adc3-11e7-8537-5523fd2cd0c9.png">

## Expected  behavior
Intellisense window with Python online help similar to:
<img width="682" alt="screen shot 2017-10-10 at 2 02 37 pm" src="https://user-images.githubusercontent.com/463564/31410544-c4e7bdae-adc3-11e7-826f-3eb97a71abf4.png">

## Steps to reproduce:  
As you're typing `open` on line 2, observe that Intellisense has replaced documentation for built-in function `open()` with `None`.
``` test.py
def test:
    open()
```

## Logs
Output from ```Python``` output panel  
```
----------Generating Tags----------
ctags --options=/Users/wgjohnson/.vscode/extensions/donjayamanne.python-0.7.0/resources/ctagOptions --languages=Python --exclude=**/site-packages/** -o /Users/wgjohnson/Workspace/ucla/DGSOMAWS/networking/.vscode/tags .
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ctags: illegal option -- -
usage: ctags [-BFadtuwvx] [-f tagsfile] file ...
```   

Output from ```Console window``` (Help->Developer Tools menu)
```
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28 Overwriting filename <<config>> to now point to mime <<text/x-ssh_config>>
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28

```

**Comment by brettcannon** [comment]
For both completion and hover I'm getting the proper results. Can you reproduce @DonJayamanne ?

**Comment by DonJayamanne** [comment]
Works fine for me too.
I believe the default interpreter ```python``` is being used on your mac (which would be Python 2.7).
Looks like you're using the ```python3``` interpreter.
Please change your workspace settings as follows:
```json
"python.pythonPath" : "python3"
```

More information can be found here https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version

**Comment by wgj** [comment]
Ah, I assumed that was in settings.json and not a workspace setting. Sorry for the inconvenience.
