### ISSUE TITLE
Add ability to opt out of Telemetry reporting

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#1296]

**Comment by DonJayamanne** [comment]
@brettcannon 
This has been resolved in https://github.com/DonJayamanne/pythonVSCode/pull/1297
Currently the extension is using the same setting that VS Code uses to turn off telemetry. 
In hind sight, this may not be the best approach, I believe we should have our own setting and advertise this on the readme.

**Comment by brettcannon** [comment]
There's no reason we can't have both.

**Comment by DonJayamanne** [comment]
Why both? 
One more thing, when looking at done of three most popular extensions (including msft), they don't seem to have the ability to opt out of the telemetry!
