### ISSUE TITLE
Python background process hangs computer

### ISSUE THREAD

**Issue by ricardovsilva** [DonJayamanne/pythonVSCode#1301]
## Environment data
VS Code version:  1.17.0-1507160143
Python Extension version:  0.7.0
Python Version:   3.5.3
OS and version: Ubuntu 16.04
### Computer specs
Model: Aspire E5-574G (Aspire E5-574G_100C_1.14)
CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
RAM: DDR3 8GB

## Actual behavior
After open VSCode with a python project, a python process is started in background. That process slowly increase it's usage of memory and cpu. After near 10 minutes, this python process is near to 100% of CPU and RAM usage, then Ubuntu just freezes.
I opened project, then started top on terminal to monitor CPU and memory usage.

**Comment by ricardovsilva** [comment]
@DonJayamanne why is that issue closed? Was that solved?

**Comment by tzachshabtay** [comment]
@DonJayamanne I'm also getting this critical issue. Computer hangs on ubuntu.
Repeating @ricardovsilva 's question, why was this closed?

It used 32GB (100%) of computer's memory before shutting down. 
Ran "ps -Ao pid,cmd,rss --sort rss" and saw that the criminal is the script: completion.py

Besides finding and fixing the leak, can you also limit the memory usage of your scripts so it at least wouldn't hang the computer?

Thanks.

**Comment by DonJayamanne** [comment]
Sorry, duplicate of https://github.com/Microsoft/vscode-python/issues/263
The extension is now maintained on the Microsoft repo.
