### ISSUE TITLE
Sort Import Error when source file path contain unicode characters.

### ISSUE THREAD

**Issue by AZLisme** [DonJayamanne/pythonVSCode#1303]
## Environment data
VS Code version:  1.17.1
Python Extension version:  0.7.0
Python Version:  3.6.2
OS and version:    macOS High Sierra 10.13

## Actual behavior

When I try to "Sort Import" a python source file under a path with unicode character like `/Users/azlisme/Desktop/临时文件/gaosan/course.py`, I got an error says:

```
Error: Command failed: python3 "/Users/azlisme/.vscode/extensions/donjayamanne.python-0.7.0/pythonFiles/sortImports.py" "/Users/azlisme/Desktop/临时文件/gaosan/course.py" --diff 
Traceback (most recent call last):
  File "/Users/azlisme/.vscode/extensions/donjayamanne.python-0.7.0/pythonFiles/sortImports.py", line 2, in <module>
    isort.main.main()
  File "/Users/azlisme/.vscode/extensions/donjayamanne.python-0.7.0/pythonFiles/isort/main.py", line 275, in main
    sort_attempt = SortImports(file_name, **arguments)
  File "/Users/azlisme/.vscode/extensions/donjayamanne.python-0.7.0/pythonFiles/isort/isort.py", line 186, in __init__
    self._show_diff(file_contents)
  File "/Users/azlisme/.vscode/extensions/donjayamanne.python-0.7.0/pythonFiles/isort/isort.py", line 214, in _show_diff
    sys.stdout.write(line)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 27-30: ordinal not in range(128)
```

## Expected  behavior

I expect sort import functions well with files under unicode path

## Steps to reproduce:  
-  Make a unicode path, e.g `mkdir 测试 && cd 测试`
-  create a python file, `touch test.py`
- open that dir with vscode, and locate that python file, then run command `Python Refactor: Sort Imports`.

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by brettcannon** [comment]
Since the extension is using the latest release of isort, is this an upstream bug?

**Comment by DonJayamanne** [comment]
Currently I'm passing the file name as a command line arg to isort, and that's where the problem lies (passing unicode characters via command line).  
Another solution is to programatically use isort to perform the sorting (and then getting around the issue of passing unicode characters)...

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#201
