### ISSUE TITLE
enable ctrl+enter keyboard shortcut for >Python: Run Selection/Line in Python Terminal

### ISSUE THREAD

**Issue by myusrn** [DonJayamanne/pythonVSCode#1305]
## Environment data
VS Code version:  1.17.1
Python Extension version:  0.7.0
Python Version:  anaconda3
OS and version:  win10 fall creators update, 1709 16299.15

## Actual behavior
To run line the cursor is currently on, or selected set of lines, in *.R source file in python terminal i currently have to use f1 [ or ctrl+shift+p ] and select "Python: Run Selected/Line in Python Terminal" option.

## Expected  behavior
Place cursor on *.py source file line, or select set of lines, i want to execute in currently open python terminal, or launch one if none currently open, and be able to use ctrl+enter to execute that line in terminal, an advance cursor to next line so i can repeat keyboard shortcut to advance through file a line at a time. This is similar to how python ide code execution is supported in vs17 python. Along these same lines i didn't find any f1 [ or ctrl+shift+p ] | Python: command that would simply open the first, or a new terminal for me.  This would be nice2have as alternative to executing an irrelevant line of code to get one created or dropping into new powershell terminal and entering command & "C:/Program Files/Anaconda3/python.exe".

## Steps to reproduce:  
-  
-  

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by brettcannon** [comment]
@DonJayamanne would this be a case where the extension provided out-of-the-box keybindings? Or do we point people to https://code.visualstudio.com/docs/getstarted/keybindings to set up their own keybindings?

**Comment by DonJayamanne** [comment]
@brettcannon , yes, thats correct.
@myusrn Please check the above link and add a shortcut to the relevant command (should be easy to find it).  
```
Run Selection/Line in Python Terminal   
python.execSelectionInTerminal  
```

**Comment by myusrn** [comment]
I was able to use keyboard shortcuts settings for the "Run Selection/Line in Python Terminal" ==
python.execSelectionInTerminal command and enable ctrl+enter keyboard shortcut.  Doing so however doesn't provide the experience you get in vs17 python, and R ide experiences, where ctrl+enter executes current selection/line and then moves cursor to next line so you can ctrl+enter yourself through a source file one line at a time.

**Comment by DonJayamanne** [comment]
Got it, you are after the ability to advance to the next line.

**Comment by DonJayamanne** [comment]
FYI - Not sure if this solves the problem, but there's another extension that might be able to help you. 
Its the [Jupyter extension](https://marketplace.visualstudio.com/items?itemName=donjayamanne.jupyter), that has the ability to execute a cell (cells are identified with comments such as ```# %%```)  code and the next. (have a look at the screen samples)

FYI - It doesn't send anything to a terminal, it runs the code in a kernel and displays the output on the right side in a separate pane.

**Comment by unode** [comment]
This is closed but for future reference (I landed here looking for this behavior), the extension [multi-commands](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command) can provide this:

```
    "multiCommand.commands": [
        {
            "command": "multiCommand.runSelectedTextAndDown",
            "sequence": [
                "workbench.action.terminal.runSelectedText",
                "cursorDown"
            ]
        },
    ],
```

and then bind `multiCommand.runSelectedTextAndDown`.

You can also use `python.execSelectionInTerminal` instead of `workbench.action.terminal.runSelectedText` and make the binding specific to `python`.

**Comment by myusrn** [comment]
@unode sounds like that multi-commands extension is a variation on the following interim work around I've been using to enable ctrl+enter execute current line and cursor down to next line shortcut.

to enable multiple steps use ctrl+, or ctrl+p | settings.json -> settings.json, to add following
```
    "macros": { // requires macros extension by publisher:"geddski" 
        "pythonExecSelectionAndCursorDown": [
            "python.execSelectionInTerminal", 
            //"vscode.window.activeTextEditor.show()",
            "cursorDown" 
        ]
    },

```
and ctrl+k & ctrl+s | edit keybindigs.json or ctrl+p | keybindings.json -> keybindings.json to add
```
    {
        "key": "ctrl+enter",
        "command": "macros.pythonExecSelectionAndCursorDown",
        "when": "editorTextFocus && editorLangId == 'python'"
    },
```
