### ISSUE TITLE
Is it possible to locate Python path over samba remotely?

### ISSUE THREAD

**Issue by Fenslett** [DonJayamanne/pythonVSCode#131]
Hi, I'm just wondering if there is a way to load python interpreter remotely.
Since I have no choice but to build a project remotely, tried to make use of your plugin over samba, but couldn't configure in ![a suggested way](https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version):
```json
"python.PythonPath": "Z:/.python/bin/python3"
```
I assume the extension failed to find the appropriate path to Python, so set the path in ![an another way](https://github.com/DonJayamanne/pythonVSCode/wiki/Autocomplete-Intellisense) as follows:

```json
"python.autoComplete.extraPaths": [
	"Z:/.python/",
	"Z:/.python/bin",
	"Z:/.python/bin/python3",
	"Z:/.python/lib",
	"Z:/.python/lib/python3.5"
],
```
However, I still have trouble getting intellisense to work. 

The following image is the list of Python installation directory. 

![image 1](http://i.imgur.com/PksPJjB.png)

**Comment by DonJayamanne** [comment]
Hi sorry but loading of remote python interpreters isn't supported at this stage.

**Comment by DonJayamanne** [comment]
Suggestions for #183
