### ISSUE TITLE
Bug about the wrong variable value

### ISSUE THREAD

**Issue by titaneric** [DonJayamanne/pythonVSCode#1310]
## Environment data
VS Code version:  1.17.1
Python Extension version:  0.7.0
Python Version:   3.6.3
OS and version:    Win 10 / Ubuntu 16.04

Hi, I use this extension to implement the algorithm on the textbook and the C++ STL in Python.
I write set container which is implemented by red black tree and referenced the set module in C++.
It's odd that the **self.__it** in **self.__iter__( )** doesn't change the value in the debug mode. More preciously, the **self__it** doesn't change to next red-black node. 

However, I write a print function to print the key in the **self__it** just under the **self.__it** iteration and execute the code. Indeed, the key just fills my expectation like the normal red-black tree set.   

Below is my code about the set, my RB_tree and node code should be fine and pass my test data.
But if there is needing more information, please reference [https://github.com/titaneric/Algorithm](url) under the Data_structure directory.

**RB_set.py**:
```python
    from RB_tree import RB_Tree
    from node.RB_treeNode import RB_TreeNode


    class RB_set:
        def __init__(self):
            self.__map = RB_Tree()
            self.__it = self.__map.nil

        def __len__(self):
            return self.__map.size

        def __contains__(self, k):
            node = self.__map.tree_search(k)
            return node != self.__map.nil

        def __iter__(self):
            self.__it= self.__map.begin()
            return self

        def __next__(self):
            if self.__it != self.__map.end():
                result = self.__it.key
                self.__it = self.__map.tree_successor(self.__it)
                # print(self.__it.key) # It is expected to change to next tree node. The line is where I set the breakpoint.
                return result
            else:
                raise StopIteration

        def add(self, k):
            node = self.__map.tree_search(k)
            if node == self.__map.nil:
                self.__map.tree_insert(RB_TreeNode(k))


    if __name__ == "__main__":
        k_list = [1, 34, 2, 5, 1]
        my_set = RB_set()
        for k in k_list:
            my_set.add(k)

        for s in my_set:
            print(s)
```        

## Actual behavior
The **self.__it** should move to next tree node in the iteration, but it remains the same which the key is 1.
## Expected  behavior
The **self.__i**t should change to 2, 5 and 34 during iteration.
## My debug execution:  
-  Set break point in the line 24
-  Observe the **self.__it** value

The problem was found in the Win 10, but it remains the same in the Ubuntu 16.04. So I guess it may be the bug in the extension.

**Comment by DonJayamanne** [comment]
@titaneric I've tried running the code outside the extension and the results are the same.  
I.e. I don't see how this could be an issue with the extension at this stage as the results are the same irrespective.  
Please could you confirm this.

**Comment by titaneric** [comment]
Hi, @DonJayamanne. 
I catch some screenshot here. Please observe the **key** in **self.__iter**.
First iteration in debug mode:
<img width="692" alt="first_iter" src="https://user-images.githubusercontent.com/12388235/32051621-f16cb1ba-ba87-11e7-91ba-fa0c628e4382.PNG">
Second iteration in debug mode:
<img width="691" alt="second_iter" src="https://user-images.githubusercontent.com/12388235/32051623-f68c83be-ba87-11e7-96aa-547aa93ddec8.PNG">
Expected output in RB_set.py:
<img width="349" alt="expected" src="https://user-images.githubusercontent.com/12388235/32051627-fb22ee0e-ba87-11e7-9a10-40036e57437a.PNG">
You can see that there is no differences between first and second iteration. However, the output here change the **self.__iter** during every iteration.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#202
