### ISSUE TITLE
[Feature request] Auto-enable virtual environment in terminal

### ISSUE THREAD

**Issue by BenjaVR** [DonJayamanne/pythonVSCode#1323]
Copied from #183:

Not sure if this is possible, but automatically enabling the virtual environment you use for a project if you open an integrated terminal would be really nice. Just like PyCharm does.

**Comment by technoiswatchingyou** [comment]
+1

**Comment by DonJayamanne** [comment]
@BenjaVR unfortunately I dont' believe this is possible, at least not within the extension. You might want to raise this as a feature request in the VS Code repo.

**Comment by DrecDroid** [comment]
Could it be possible to open it from the command palette?

**Comment by NOhs** [comment]
Or could the interpreter selection send a command to the integrated terminal that activates (or deactivates) the selected venv?
