### ISSUE TITLE
Setting to prevent automatic extra newline when splitting braces?

### ISSUE THREAD

**Issue by jkyeung** [DonJayamanne/pythonVSCode#1324]
(Migrated from #183)

Is there a way to have automatic brace completion active but disable the automatic extra newline when pressing Enter? For example, if I have this (with the cursor shown as `|`):

    foo = (|)

And I press Enter, I get this:

    foo = (
        |
    )

Is there some setting so that I have this instead:

    foo = (
        |)

I apologize if this should be a VS Code issue, rather than an issue with this extension. (But I kind of dread posting an issue there, because its tracker is swamped.) But of course best of all would be if this already exists and someone can just point me to it. :)

**Comment by DonJayamanne** [comment]
Please could you disable the Python extension and confirm the issue persists.

**Comment by jkyeung** [comment]
Yes, this behavior (extra newline automatically inserted) occurs with or without your extension. It even occurs with bracket autocompletion off, and it even occurs in plain text mode.

If there isn't some setting to control this within the base VS Code, I was thinking maybe your extension could have a way to override the standard behavior.

**Comment by DonJayamanne** [comment]
If this occurs without the extension, then you'll need to raise this issue on the vscode repo. Sorry, but I don't think making changes to override sick behaviour world be the solution.
