### ISSUE TITLE
Django app behaves differently when debugging

### ISSUE THREAD

**Issue by albertinix** [DonJayamanne/pythonVSCode#1327]
## Environment data
VS Code version:  1.17.2
Python Extension version:  0.7.0
Python Version:   3.6.0
OS and version:    Windows 7 64-bit

## Actual behavior
I have a Django app, with a view and a form.
The interesting part is here: 
````
loginForm = LoginForm(request.POST or None)
````

If I set a breakpoint at that line and then skip over it (with F10), then the loginForm object will not be bound (the is_bound property of the form is false).
If however I set the breakpoint one line after that, the loginForm object will be bound.

This is just one example. It happens multiple times over various objects and functions: if I set the breakpoint at one line when calling a function, the result will be "a" (not expected), while if I set the breakpoint after that line, the result is the expected "b".

The debugger seems, in some cases, to introduce some kind of mistakes in code execution.

P.S.: I checked the same app in PyCharm Community and it behaves as it should, debugger or no debugger.

**Comment by albertinix** [comment]
At a glance, this might be also linked to [https://github.com/DonJayamanne/pythonVSCode/issues/1310](https://github.com/DonJayamanne/pythonVSCode/issues/1310)

**Comment by DonJayamanne** [comment]
@albertinix checked #1310, I doubt that's related to this issue.  
Just a heads up, the PTVS (Python for Visual Studio) team are currently in the middle of some major re-engineering to debugger (the same debugger I'm using in this extension), and I expect this issue to be resolved soon.

Will look into this and keep you posted.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#204
