### ISSUE TITLE
django ORM objects  error tips

### ISSUE THREAD

**Issue by coladou** [DonJayamanne/pythonVSCode#133]
Class 'Article' has no 'objects' member: no-member

**Comment by coladou** [comment]
For example:  Article.objects.filter(pk=1)

**Comment by DonJayamanne** [comment]
Hi, does it work when not debugging?

**Comment by coladou** [comment]
Works fine,  but editor prompt error

**Comment by coladou** [comment]
DUP with : https://github.com/DonJayamanne/pythonVSCode/issues/88
