### ISSUE TITLE
debug in python class

### ISSUE THREAD

**Issue by CAIJUNYI** [DonJayamanne/pythonVSCode#1330]
## Environment data
VS Code version:  1.17.2
Python Extension version:  0.7.0
Python Version:   3.6.3
OS and version:    Win10

## Actual behavior
The private properties or private variables (start with two leading underscore) in a method cannot be seen when debugging in python class. Neither prompt when hovering on those private properites or private variables nor items in the Local window.

## Expected  behavior
The private properties or private variables (start with two leading underscore) in a method can be seen when debugging in python class

## Steps to reproduce:  
1. Write a python class with some private properties that start with two leading underscore.
2. When debugging in that python class, no tip or local list for those private properties.
3. Is it possible to add this feature for debugging in python class?
![class_debug](https://user-images.githubusercontent.com/10704251/31801267-8483d2ee-b579-11e7-8eba-ca3acc80bed8.png)

**Comment by DonJayamanne** [comment]
You'd see them under ```arguments```, Have a look at the members of ```self``` under arguments.
others are local variables and not members of self.
