### ISSUE TITLE
method reference when debug python

### ISSUE THREAD

**Issue by CAIJUNYI** [DonJayamanne/pythonVSCode#1331]
## Environment data
VS Code version: 1.17.2
Python Extension version: 0.7.0
Python Version: 3.6.3
OS and version: Win10

## Actual behavior
no reference for methods of a class instance
## Expected  behavior
reference for methods of a class instance
## Steps to reproduce:  
1. Write a class with public property and method.
2. In another file: create an instance of that class; call one of its method.
3. Actually, it will succeed, and when we are coding, the python plugin provides auto-complete.
4. But in debug mode, we cannot find the reference to that method when we press F12, and only the properties of that class are available.
![python_debug](https://user-images.githubusercontent.com/10704251/31801404-936ffe80-b57a-11e7-9fe8-1e512aadfbd5.png)

**Comment by DonJayamanne** [comment]
> But in debug mode, we cannot find the reference to that method when we press F12, and only the properties of that class are available.

Does this exact same operation work in non-debug mode (i.e. in the same file for the same method)?

Please could you upload a sample code that I could test at my end.

**Comment by CAIJUNYI** [comment]
here is the demo
[test.zip](https://github.com/DonJayamanne/pythonVSCode/files/1417086/test.zip)

**Comment by DonJayamanne** [comment]
Does this exact same operation work in non-debug mode (i.e. in the same file for the same method)?

**Comment by CAIJUNYI** [comment]
Yes, the method reference does not work in non-debug mode. In this example,  `params.test()` in the `Ref` class `__init__` method cannot be referenced, neither in debug mode nor in non-debug mode.

**Comment by DonJayamanne** [comment]
I wouldn't expect intellisense to work for the example you have provided, as there's not type information to determine the memebers. 
Also, currently I'm using the Jedi library to provide the intelliense capabitlities. Will look  into updating that. Closing this issue for now.
