### ISSUE TITLE
Python files not using the correct formatter.

### ISSUE THREAD

**Issue by devvpm** [DonJayamanne/pythonVSCode#1332]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.7.2
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
python|don|0.7.0
gitlens|eam|5.7.1
EditorConfig|Edi|0.11.0
tslint|eg2|1.0.11
php-debug|fel|1.11.1
php-intellisense|fel|1.5.2
php-pack|fel|1.0.1
output-colorizer|IBM|0.1.2
phpcs|ika|0.7.0
php-symbols|lin|2.1.0
ftp-sync|luk|0.3.3
gitignore|mic|1.0.1
team|ms-|1.122.0
indent-rainbow|ode|0.7.2
Ruby|reb|0.15.0

---

My settings look like this 

```
{
    "window.zoomLevel": 1,
    "terminal.integrated.shell.windows": "C:\\windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "workbench.activityBar.visible": true,
    "team.showWelcomeMessage": false,
    "editor.multiCursorModifier": "ctrlCmd",
    "gitlens.gitExplorer.files.layout": "auto",
    "python.formatting.formatOnSave": true,
    "python.formatting.provider": "autopep8",
    "python.formatting.autopep8Path": "autopep8"
}

```

While formatting the document, it says formatting with yapf and not autopep8. 
Further, It is not formatting the document instead it just shows problems in the document. ie, It just shows the problems in the 'Problems' tab but doesn't fix them.

Reproduces without extensions: Yes/No
![problems](https://user-images.githubusercontent.com/1164077/31812725-8ddccdd6-b5b6-11e7-8c0d-ef0227a2e6d4.png)

**Comment by DonJayamanne** [comment]
> While formatting the document, it says formatting with yapf and not autopep8.

Please could you provide a screen sample of this message.
