### ISSUE TITLE
Pylint serch path

### ISSUE THREAD

**Issue by IlanHindy** [DonJayamanne/pythonVSCode#1333]
## Environment data
VS Code version:1.17.2  
Python Extension version:0.7.0  
Python Version: 3.6  
OS and version:  windows 10  

## Actual behavior
I use python from Anaconda
My code is not in the Anaconda env
Pylint identifies the libraries that are in the anaconda env
Pylint does not identify My files (meens when there is an import it gives error E0401 Unable to import...) 
Does that meens that I have to insert my project to anaconda as well ?
Or is there another way to tell pylint which pathes to search ?

## Steps to reproduce:  
-  
-  

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by IlanHindy** [comment]
Hellow,
I will explain in detail what I think is the problem
My project (which is located out of the anaconda env) has sub directories
When I import a file from another directory Pylint says that it cannot import
When I import a file from the same directory or from the anaconda env Pylint says it can importThanks for your help
Ilan

**Comment by DonJayamanne** [comment]
>When I import a file from another directory Pylint says that it cannot import
Does this work in command line (when using pylint)?

**Comment by IlanHindy** [comment]
I run pylint on one of the modules (see results in attached file)
It did not give the import error
(The way I access the files in the program is by programmatically setting the sys.path at the beginning
of the program. I assume that in the VS code the Pylint when it comes to analize a module does not know these pathes)
[pylintlog.txt](https://github.com/DonJayamanne/pythonVSCode/files/1405992/pylintlog.txt)

Ilan

**Comment by IlanHindy** [comment]
I am sorry,
The file of the log I gave you does not do imports from another directory
I run pylint in the terminal on a file that does import from
[pylintLog1.txt](https://github.com/DonJayamanne/pythonVSCode/files/1406065/pylintLog1.txt)
 another directory and the import error exist

**Comment by DonJayamanne** [comment]
If you're having import errors when running pylint from the terminal window, then this isn't an issue with the extension. Hence closing this issue.  
You can configure the paths using PYTHONPATH (try setting them in the .env file located in the root directory of your project). Anyways, as mentioned this isn't an issue with the extension, I'd suggest you first try to resolve it outside of the extension (via terminal).
