### ISSUE TITLE
__init__() error and NoneType error when attach the ptvsd

### ISSUE THREAD

**Issue by naeco2005** [DonJayamanne/pythonVSCode#1334]
Hi,

My program is a C++ software which UI is developed with QT. We embed a Python process inside. When Python process is initialized, we redirect stdout and stderr with following codes:
```python
import sys
class CatchOutput:
    def init(self):
        self.value = ''
    def write(self, txt):
        self.value += txt
    def flush(self):
        pass
catchOutput = CatchOutput()
sys.stdout = catchOutput
```
```python
import sys
class CatchOutErr:
    def init(self):
        self.value = ''
    def write(self, txt):
        self.value += txt
catchOutErr = CatchOutErr()
sys.stderr = catchOutErr
```
Once my program starts, i will call `ptvsd::enable_attach` and then call `ptvsd.wait_for_attach()` waiting for attachment.

when i begin to attach my program with PythonVSCode, i always see the following issues:
```
Traceback (most recent call last):
File "", line 1, in 
TypeError: init() missing 2 required positional arguments: 'old_out' and 'is_stdout'
Error in sys.excepthook:
Traceback (most recent call last):
File "D:\Neutron\main\src\Lib64\Debug_Build\Debug\Python\lib\site-packages\ptvsd\visualstudio_py_debugger.py", line 2288, in _excepthook
do_wait()
File "D:\Neutron\main\src\Lib64\Debug_Build\Debug\Python\lib\site-packages\ptvsd\visualstudio_py_debugger.py", line 2413, in do_wait
sys.stdout.write('Press any key to continue . . . ')
AttributeError: 'NoneType' object has no attribute 'write'
```
Original exception was:
```
Traceback (most recent call last):
File "", line 1, in 
TypeError: init() missing 2 required positional arguments: 'old_out' and 'is_stdout'
KeyError: '__main__D%3A%2FNeutron%2Fmain%2Fsrc%2FLib64%2FDebug_Build%2FDebug%2FPython%2FSamples%2FSpurGear%2FSpurGear_py'
Error in sys.excepthook:
Traceback (most recent call last):
File "D:\Neutron\main\src\Lib64\Debug_Build\Debug\Python\lib\site-packages\ptvsd\visualstudio_py_debugger.py", line 2288, in _excepthook
do_wait()
File "D:\Neutron\main\src\Lib64\Debug_Build\Debug\Python\lib\site-packages\ptvsd\visualstudio_py_debugger.py", line 2413, in do_wait
sys.stdout.write('Press any key to continue . . . ')
AttributeError: 'NoneType' object has no attribute 'write'
```
i don't know what the root cause is? How to resolve this issue? The PTVSD version i am using is 3.0.0.

Thanks for the help,
-Neil

**Comment by DonJayamanne** [comment]
What's the OS and python version?

**Comment by naeco2005** [comment]
I am working on Windows 10. The Python version is 3.5.3.

**Comment by brettcannon** [comment]
@naeco2005 could you verify that the Markdown cleanup of your example is accurate? If so then I think there is an error in your code as naming a method `init()` doesn't do anything in Python.

I also wouldn't use a custom class to capture `stdout` and `stderr` but instead use `io.StringIO`. There's also no need to call `sys.stdout` directly since `print()` will do that for you. And lastly, if you want to wait for input, then use `input()`.

**Comment by naeco2005** [comment]
Thanks @brettcannon. it should be __init__, not init, i made a bad copy. 

i rewrote the code to use StringIO and fixed some other issues, now it works fine. Thanks for the help. 

-Neil
