### ISSUE TITLE
Explicitly set which IP debugger binds to

### ISSUE THREAD

**Issue by ragerin** [DonJayamanne/pythonVSCode#1335]
## Environment data
VS Code version:  1.17.1
Python Extension version:  0.7.0
Python Version:   3.6.2
OS and version:    Windows 8.1 Enterprise x64

## Actual behavior
When attempting to launch the debug server, I receive the following error:
`There was an error in starting the debug server. Error = {"code":"EACCES","errno":"EACCES","syscall":"listen","address":"::"}`
**I'm behind restrictive corporate Firewall, which I suspect limits the ability to launch the debug server.**
I am generally unable to run any servers that binds to `0.0.0.0`, but I am able to bind explicitly to `127.0.0.1` without any issue (tested with NodeJS).

**Can I somehow configure which IP address (and port) the Python debugger attempts to bind to?**

**Comment by DonJayamanne** [comment]
Unfortunately there's no option at this stage to configure this.
However you can work around this limitation by using the ```Attach``` debugger option.

https://github.com/DonJayamanne/pythonVSCode/wiki/Debugging:-Remote-Debuging  

Basically, you're launching the application in debug mode and then attaching to it using a specific IP and port. 

Please let me know if that solution works (it should).

**Comment by ragerin** [comment]
Sadly, I get a `ECONNREFUSED` and experience the same issues as specified in #1039 - tested with ptvsd 3.0.0 and latest 3.2.1.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#205
