### ISSUE TITLE
Pep8 linting does not work as text changes

### ISSUE THREAD

**Issue by MFairley** [DonJayamanne/pythonVSCode#134]
I've set `"python.linting.lintOnTextChange": true` however, pep8 messages only appear when I save the file. If I modify part of the document such that a message should appear, no message appears until I save the file. My understanding is that the message should appear immediately as I am typing. Thanks.

**Comment by DonJayamanne** [comment]
You are absolutely right. Not sure why I put that setting there, must have gotten confused with lint on save, or I perhaps i had the intention to enable such a feature. Thanks for identifying the issue, will fix it soon.

**Comment by DonJayamanne** [comment]
I don't think i can enable linting on text change, instead i'll have to update the documentation/wifi indicating this isn't supported.
FYI - i won't remove the setting, as this will cause plenty of user settings to throw exceptions complaining about an invalid setting.

**Comment by DonJayamanne** [comment]
@MFairley , I'll be working on this issue some time soon. 
Until then there's a work around. You could configure VS Code to automatically save changes to the file.
This would in turn trigger the save event resulting in the linter kicking in.

Yes, this isn't the best solution, but a possible short term solution for linting as you type.

**Comment by DonJayamanne** [comment]
Suggestions for #183

**Comment by robintw** [comment]
I see this is now shown as crossed out in #183 - does this mean it has been implemented? I've enabled the option, but it doesn't seem to do anything.

**Comment by DonJayamanne** [comment]
@robintw , closing this as the current solution is to turn on auto save.
Will update the Wiki accordingly.

**Comment by DonJayamanne** [comment]
[updated wiki](https://github.com/DonJayamanne/pythonVSCode/wiki/Linting#lint-as-you-type)

**Comment by hungys** [comment]
@DonJayamanne `"python.linting.lintOnTextChange": true` still doesn't work when auto save is disabled. Is this due to API limitation? Perhaps like the plugin cannot listen to text changed event?

**Comment by ihabunek** [comment]
A real implementation of `lintOnTextChange` would be very nice. Auto save is not a solution when working with Django server and similar apps which watch for file changes and reload. Auto save causes them to reload constantly, which leads to performance issues.

**Comment by HawiCaesar** [comment]
Yes @DonJayamanne, "python.linting.lintOnTextChange": true does not work even when auto save is turned off...What could be the issue?

**Comment by stlaz** [comment]
@DonJayamanne Would you kindly reopen this issue? I don't think turning auto-save on is a proper way for pep8 checks to be triggered. I admit I do not know the `code` project backend but if there's no other way to do this, they should _really_ add it.
Linting as you type has worked in Atom ever since I remember, I would really like to try and switch to Code but I won't until this is done properly.
@DonJayamanne if you could maybe explain some technical details about why there's no other way but auto-save to do this (if you've got spare time, ofc), that would be awesome.
Thanks in advance!

**Comment by aelsibaie** [comment]
A "short term solution" was implemented; this issue should be reopened.

**Comment by kav2k** [comment]
In addition, one thing the commit linked did not fix is `python.linting.lintOnTextChange` still _appearing in the default configuration_, with no indication it's unimplemented. This leads to user confusion.
