### ISSUE TITLE
problem of enum class auto-complete

### ISSUE THREAD

**Issue by CAIJUNYI** [DonJayamanne/pythonVSCode#1340]
## Environment data
VS Code version: 1.17.2
Python Extension version: 0.7.0
Python Version: 3.6.3
OS and version: Win10

## Actual behavior
no tooltip for the members of Enum class under the condition below

## Expected  behavior
pop-up auto-complete for the members of Enum class

## Steps to reproduce:  
```
"""problem of enum class auto-complete"""
# -*- coding: utf-8 -*-
from enum import Enum, unique


@unique
class TaskConfParams(Enum):
    project_name = 0
    project_path = 1
    data_path = 2
    output_path = 3
    scenarios_path = 4


@unique
class TaskParams(Enum):
    task_conf = TaskConfParams


def main():
    task_conf = TaskParams.task_conf.value
    task_conf.


if __name__ == '__main__':
    main()
```

![enum](https://user-images.githubusercontent.com/10704251/32037317-5eb3cd98-ba57-11e7-8bcc-0611cef415f3.png)

**Comment by gandhis1** [comment]
What font/theme are you using, it looks really nice

**Comment by CAIJUNYI** [comment]
Aha, it is the Material Theme and Roboto Mono for Powerline font.

**Comment by DonJayamanne** [comment]
@CAIJUNYI works for me. 
Will investigate this further.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#207
