### ISSUE TITLE
CTRL+R (Symbol browser) Stopped working without reason

### ISSUE THREAD

**Issue by JustDevZero** [DonJayamanne/pythonVSCode#1347]
## Environment data
VS Code version:  Version 1.18.0-insider
Commit: 509630ffe3fabf2e1f49b416bb83f5ff0877b042
Python Extension version:  0.7.0
Python Version: 
python2.7 --version
Python 2.7.14 (which is the one I want)

python --version
Python 3.6.2 (which is the default os system)

OS and version:    Arch Linux (Rolling Release, updated)

## Actual behavior

AFAIK Ctags file is correctly generated, but CTRL+R is not showing any symbol.

## Expected  behavior

Explore against the symbols of the file.

## Steps to reproduce:  
-  Open any Python file
-  Press CTRL+R
- Wait until it says "No symbols found"

## Logs
Output from ```Python``` output panel  
```
##########Linting Output - pylint##########
130,0,convention,C0301:Line too long (104/100)
139,0,convention,C0301:Line too long (104/100)
391,0,convention,C0301:Line too long (131/100)
400,0,convention,C0301:Line too long (113/100)
401,0,convention,C0301:Line too long (109/100)
402,0,convention,C0301:Line too long (107/100)
408,0,convention,C0301:Line too long (107/100)
416,0,convention,C0301:Line too long (115/100)
------------------------------------------------------------------
Your code has been rated at 0.90/10 (previous run: 0.90/10, +0.00)

No config file found, using default configuration
```

Output from ```Console window``` (Help->Developer Tools menu)
```
2raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
```

**Comment by DonJayamanne** [comment]
Sorry, but what command does ```Press CTRL+R``` invoke.
Is this ```Go to symbol in file``` or ```Go to symbol in workspace```.
Also, please could you provide a screen sample of the message ```No symbols found```

**Comment by JustDevZero** [comment]
Hi there again,

AFAIK the CTRL+R is trying to invoke the `Go to symbol in file`.

On the other hand, here I attach a gif with that section of the screen, I attach it as a gif, so you can see how it responds.

Which I found weirder, is that the `Go to symbol in workspace` is working.

![deepin-screen-recorder_select area_20171031141645](https://user-images.githubusercontent.com/172759/32227515-ef9dd32e-be4b-11e7-925a-5e7e84ca5f16.gif)

**Comment by DonJayamanne** [comment]
Have you configured your workspace/user settings to ensure it points to Python2.7 (the one you want)?   
Please could you upload the code for the above file?  
Does the feature ```Go to symbol in file``` work for other files or does it not work at all?

**Comment by Tantalus13A98B5F** [comment]
i've got the same issue. i've made sure that the `tags` file has been generated, and `python.pythonPath` points to the right installation, however the `go to symbol in file` does not work. it works for other files, e.g. markdown. also `go to definition` cannot be used, while intellisense is working all right.

**Comment by JustDevZero** [comment]
As @Tantalus13A98B5F described.

I've made sure the tags are generated, and the python.pythonPath is ok, it works with Markdown, ruby, etc... but not here in python. Also tried to disable every linter/stuff non-python related but still :(

As for your questions, @DonJayamanne for now the config is like this:

As for the settings, here are they
[settings.json.txt](https://github.com/DonJayamanne/pythonVSCode/files/1437068/settings.json.txt)
 attached as a json.

**Comment by Tantalus13A98B5F** [comment]
Well. I looked into the code today. I'm using `jedi 0.11.0`, which is just incompatible with the current extentsion:
The error occurred in `pythonFiles/completion.py`.
In `JediCompletion._extract_range`, it goes:
```python
if jedi.__version__ in ('0.9.0', '0.10.0'):
    return self._extract_range_jedi_0_9_0(definition)
else:
    return self._extract_range_jedi_0_10_1(definition)
```
The fallback behavior uses the following module:
```python
from jedi.parser.python import parse
```
However, it doesn't exists there for `jedi 0.11.0`

**Comment by Tantalus13A98B5F** [comment]
I just switched to the `preview` version of `jedi` in the repo. The `symbolProvider` still provides no results, though the previous problem is gone.

**Comment by Tantalus13A98B5F** [comment]
@JustDevZero maybe you should check the version of your `jedi`, and it's ok if `python.jediPath` is not configured.
@DonJayamanne the current code cannot work with `jedi 0.11`.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#208
