### ISSUE TITLE
configuration for python source files in subfolder

### ISSUE THREAD

**Issue by kannix** [DonJayamanne/pythonVSCode#1348]
i have a project where all of our code is in a `src` subfolder. how do i configure vs code and this plugin to correctly handle that?

**Comment by DonJayamanne** [comment]
You could just open the src folder vscode

**Comment by kannix** [comment]
But i need to edit the whole project ;)
Think about the project like something with this data structure (stolen from https://drivendata.github.io/cookiecutter-data-science/#directory-structure)

```
├── LICENSE
├── Makefile           <- Makefile with commands like `make data` or `make train`
├── README.md          <- The top-level README for developers using this project.
├── data
│   ├── external       <- Data from third party sources.
│   ├── interim        <- Intermediate data that has been transformed.
│   ├── processed      <- The final, canonical data sets for modeling.
│   └── raw            <- The original, immutable data dump.
│
├── docs               <- A default Sphinx project; see sphinx-doc.org for details
│
├── models             <- Trained and serialized models, model predictions, or model summaries
│
├── notebooks          <- Jupyter notebooks. Naming convention is a number (for ordering),
│                         the creator's initials, and a short `-` delimited description, e.g.
│                         `1.0-jqp-initial-data-exploration`.
│
├── references         <- Data dictionaries, manuals, and all other explanatory materials.
│
├── reports            <- Generated analysis as HTML, PDF, LaTeX, etc.
│   └── figures        <- Generated graphics and figures to be used in reporting
│
├── requirements.txt   <- The requirements file for reproducing the analysis environment, e.g.
│                         generated with `pip freeze > requirements.txt`
│
├── src                <- Source code for use in this project.
│   ├── __init__.py    <- Makes src a Python module
│   │
│   ├── data           <- Scripts to download or generate data
│   │   └── make_dataset.py
│   │
│   ├── features       <- Scripts to turn raw data into features for modeling
│   │   └── build_features.py
│   │
│   ├── models         <- Scripts to train models and then use trained models to make
│   │   │                 predictions
│   │   ├── predict_model.py
│   │   └── train_model.py
│   │
│   └── visualization  <- Scripts to create exploratory and results oriented visualizations
│       └── visualize.py
│
└── tox.ini            <- tox file with settings for running tox; see tox.testrun.org
```

**Comment by DonJayamanne** [comment]
Why not open the soucre directory itself. It should still work.
Have you come across any problems in opening the root folder?

**Comment by kannix** [comment]
> Why not open the soucre directory itself. It should still work.

What do you mean with this? Open it in a separate VS Code window?
I don't do it because i have to work on all files within that project

> Have you come across any problems in opening the root folder?

one of the problems is that pylint fails on all imports (i guess because it searches from the project root folder)  
another one is running a cell with jupyter doesn't work (most likely because it runs from project root, too)

**Comment by DonJayamanne** [comment]
>one of the problems is that pylint fails on all imports (i guess because it searches from the project root folder)

Ok, now that makes sense. It would be easier to let me know what you have tried and what fails. As I have no idea of the context.

Here's the solution, you can change how pylint searches for files, by changing the PYTHONPATH environment variable.

Here are the details:
- Create a file named ```.env``` in the root directory  
- Add an environment variable for ```PYTHONPATH``` and set the path to what you need so pylint and other python programs can locate your files  
- You might need to restart vs code after making changes to this ```.env``` file (separate issue has been filed to resolve this)  

This should fix it

**Comment by kannix** [comment]
Could you point me to a documentation about that `.env` file? Is this a pythonVSCode feature or a Visual Studio Code one? I tried multiple paths (relative and full) and different syntax for this and it didn't work at all

**Comment by DonJayamanne** [comment]
It's a python vscode feature. Sorry I haven't documented this yet.

**Comment by kannix** [comment]
okay maybe i made an obvious error:
i created a file called `.env` in the project root with content like this:
`PYTHONPATH=/Users/kannix/theprojectroot/src`
and I'm using MacOS

**Comment by DonJayamanne** [comment]
Here's what we can do to confirm this:
1. Create a temporary python file named ```x.py``` some where within your project
2. Add the following code:
```python
import os
print(os.getEnv("PYTHONPATH", "NONE"))
```
3. Debug the above file
It should print the value for PYTHONPATH with the value you have provided in it (along with the standard PYTHONPATH value).

4. If this doesn't work, please restart VS Code and try once again.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#209
