### ISSUE TITLE
envFile not loaded

### ISSUE THREAD

**Issue by catherinedevlin** [DonJayamanne/pythonVSCode#1349]
## Environment data
VS Code version:  

Version 1.17.2 (1.17.2)

b813d12980308015bcd2b3a2f6efa5c810c33ba5

Python Extension version:  0.7.0
Python Version:   
'2.7.12 (default, Jun 29 2016, 14:05:02) \n[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]'

Got identical result with Python 3.6.0 

OS and version:   MacOS Sierra 10.12.6 (16G29)

## Actual behavior

environment variables in envFile not being run 

## Expected  behavior

environment variables from envFile available to Python
## Steps to reproduce:  
- In `.env` in workspace root folder: `export THE_THING=a_thing`
- Write `do_the_thing.py`:
```
import os

x = os.getenv('THE_THING')
print('The thing is:')
print(x)
```
- Use unmodified `launch.json` (also attached, just to be on the safe side)
-  Debug attached `do_the_thing.py` with "Python" configuration

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
The thing is:
None
```

**Comment by catherinedevlin** [comment]
[launch.json.txt](https://github.com/DonJayamanne/pythonVSCode/files/1423116/launch.json.txt)

**Comment by catherinedevlin** [comment]
1. I see now that the launch.json I attached had two entries for "Python".  However, fixing that didn't change anything.

2. I tried using `"env": {"THE_THING": "a_thing"},`, with the same (i.e., no) result.

**Comment by DonJayamanne** [comment]
1. Do not use the words ```export``` in the ```.env``` file. Just the following contents in the ```.env``` file is sufficient:
```
THE_THING=a_thing
```

2. Please restart VS Code after the changes.
(could be related https://github.com/DonJayamanne/pythonVSCode/issues/1230)

**Comment by catherinedevlin** [comment]
That fixed it!  Thank you!

For future reference, is there a place I could have been looking where I would have seen an error message in loading launch.json?

**Comment by DonJayamanne** [comment]
Unfortunately there are no errors life's for this.
