### ISSUE TITLE
docstring for function with decorators display the doc for the decorator not the the function

### ISSUE THREAD

**Issue by tangorboyz** [DonJayamanne/pythonVSCode#1352]
## Environment data
VS Code version:  1.18.0-insider
Python Extension version:  
Python Version:   0.7.0
OS and version:    Ubuntu 16.04
![image](https://user-images.githubusercontent.com/8751130/32143042-71bc6470-bcde-11e7-9341-c588056d0f0a.png)

## Actual behavior
When hover over a function with decorators like `@properties` display the the doc for `@properties`
## Expected  behavior
It should only display the doc for the function.
As you can see at picture above, `is_authenticated` is decorated with `@properties`. But when hover over on `is_authenticated`, the doc for `@properties` is displayed.

**Comment by tangorboyz** [comment]
Another info: if we type the object method with decorators, the doc for the decorators is displayed.
However if we access it directly from it's class, the actual doc for that method is displayed. Example
`User.is_authenticated()`, hovering over would display the doc for the `is_authenticated` itself.
But if initialize an object of that class like `user = User(username='username')`, and `user.is_authenticated()`, would display the doc for `@property`.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#210
