### ISSUE TITLE
The workspace path does not support with whitespace

### ISSUE THREAD

**Issue by diuming** [DonJayamanne/pythonVSCode#1356]
## Environment data
VS Code version:  1.17.2
Python Extension version:  0.7.0
Python Version:   2.7
OS and version:    Mac

## Steps to reproduce:  
-  
-  

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
>Steps to reproduce:

**Comment by DonJayamanne** [comment]
Please fill in the blanks
