### ISSUE TITLE
"stopOnEntry: false" not working as expected when set in the settings.json launch option (with no workspace)

### ISSUE THREAD

**Issue by deltaz0** [DonJayamanne/pythonVSCode#1358]
## Environment data
VS Code version:  1.17.2 
Python Extension version:  0.7.0
Python Version:   2.7.13
OS and version:   Win10 64 10.0.15063

I have a single python file open in VSCode with no open folder/workspace, with `"stopOnEntry": false` under the `"launch: {}` option in settings.json.

## Actual behavior
I press F5 on the python file, and the debugger stops on the first line.

## Expected  behavior
I press F5 and the debugger should not stop on the first line.

## Steps to reproduce:  
Python file open in the VScode with no open folder/workspace.
My settings.json contains the following:
```
"launch": {
      "version": "0.2.0",
      "configurations": [
          {
              "name": "Python",
              "type": "python",
              "request": "launch",
              "stopOnEntry": false,
              "pythonPath": "${config:python.pythonPath}",
              "program": "${file}",
              "cwd": "${workspaceRoot}",
              "env": {},
              "envFile": "${workspaceRoot}/.env",
              "debugOptions": [
                  "WaitOnAbnormalExit",
                  "WaitOnNormalExit",
                  "RedirectOutput"
              ]
          }
        ]
    },
```
I'll note that if I do open the file's containing folder into VSCode as a workspace, and then go into the launch.json file and change stopOnEntry to false in the corresponding configuration, it behaves as expected and will not stop on the first line when the debugger is started.

What I would like to do is disable the stop-on-first-line behavior for all python files when a workspace is not open. I figured the `launch: {}` option available in settings.json [referenced here](https://code.visualstudio.com/docs/editor/debugging) would allow me to do this, but it is not working. I'm not sure if this is a bug or expected behavior. If it is expected behavior, is there another way to accomplish this? Thanks.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#211
