### ISSUE TITLE
Syntax Highlighting doesn't honor string literals that end in a backslash

### ISSUE THREAD

**Issue by markdall** [DonJayamanne/pythonVSCode#136]
VSCode's Python syntax highlighting seems to be confused when you put an r in front of a double-quoted string. This in turn tends to confuse _me_. 

`currentIterationDirectory = self.TOK + r"\" + self.TESTNICKNAME + r"\" outerLoopIterator`

At this point it's probably easier to just show what I mean: 

![vscode_python_highlighting_bug](https://cloud.githubusercontent.com/assets/238194/15442399/c3c3dc82-1e95-11e6-8ad6-897176a8a467.png)

(Edited to add: I should note that for my purposes at least the three lines of code in the picture do the same thing.)

Expected result: Using r"\" causes the \ to be treated like a literal \ instead of the start to a control character and thus doesn't invalidate the second double-quote. (This is how python behaves.)

Actual result: The second double-quote is treated as though it has been escaped, is ignored as far as whether the string has been opened or closed, and then things get confusing. 

Release of VSCode I'm using:
Version 1.1.1
Commit def9e32467ad6e4f48787d38caf190acbfee5880
Date 2016-05-13T13:29:20.776Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

**Comment by DonJayamanne** [comment]
Hi this extension doesn't support syntax highlighting, you might want too try the extension magic python.

**Comment by markdall** [comment]
My mistake, sorry. I suppose I need to report it to VSCode's repo directly. Sorry for the inconvenience!
