### ISSUE TITLE
HEX numbers is in two different colors

### ISSUE THREAD

**Issue by Fiskelord** [DonJayamanne/pythonVSCode#1363]
## Environment data
VS Code version:  1.17.2
Python Extension version:  0.7.0
Python Version:  Python 3.6.3
OS and version:  Ubuntu Linux 17.10

## Actual behavior
When writing numbers as hex (0x1234), the '0x' part is one color, the '1234' part is another color

## Expected  behavior
0x1234 being the same color

## Steps to reproduce:  
-  Write a number in hex inside a python file

## Logs
Not relevant

## Note
I am not sure if this is an issue with the python plugin or with VS Code itself, but as far as i can google it would seems like the colors are controlled from the plugin.
Please do correct me if i am wrong.

**Comment by DonJayamanne** [comment]
Please try disabling the extension to reproduce the issue.

**Comment by Fiskelord** [comment]
Alright, the plugin has nothing to do with the colors, i will take it to the devs of VS Code. Sorry for wasting your time!

**Comment by DonJayamanne** [comment]
@Fiskelord no problem at all, glad I could be of some assistance.
