### ISSUE TITLE
Auto completion of triple quote """

### ISSUE THREAD

**Issue by CAIJUNYI** [DonJayamanne/pythonVSCode#1364]
## Environment data
VS Code version: 1.17.2
Python Extension version: 0.7.0
Python Version: 3.6.3
OS and version: Win10

## Actual behavior
1. Type """ on a new line
2. Observe that """ autocompletes to """" with the cursor between the third and forth ".
## Expected  behavior
Looking forward to getting the result of """cursor"""

Is it possible ?

**Comment by DonJayamanne** [comment]
Please could you disable the extension and confirm the issue still exists.

**Comment by CAIJUNYI** [comment]
Sorry, the description of the second behavoir was wrong. Actually, type " three times, it will be """, and there is no auto-completion. Is it possible to provide this feature ?

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#212
