### ISSUE TITLE
Toggled terminal within VSCode disappears when resizing window

### ISSUE THREAD

**Issue by alexandreday** [DonJayamanne/pythonVSCode#1367]
## Environment data
VS Code version:   1.17.2
Python Extension version:  0.7.0
Python Version:   3.5
OS and version:    OSX 10.13 (High Sierra)

## Actual behavior
Toggled terminal within VSCode has a bug.
When resizing terminal within VSCode, causes the terminal to disappear.
By "disappear" I mean that the command line prompt is no longer available.

## Steps to reproduce:  
-  Resize VSCode window and terminal window. The bug is not always present.
-  By "disappear" I mean that the command line prompt is no longer available. 

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
@alexandreday Moved to VS Code as this isn't an issue with the extension.
