### ISSUE TITLE
Attaching Debugger to Remote Docker Container Running Jupyter Server Hangs

### ISSUE THREAD

**Issue by cratter49** [DonJayamanne/pythonVSCode#1369]
## Environment data
VS Code version:  1.18.0-insider
Python Extension version:  ptvsd (3.2.1)
Python Version: 3.4.3
OS and version: Mac OSX 10.11.6

The remote server is running a custom version of Jupyter that uses iPython on a Docker container on an image that is based on Ubuntu 14.04.

## Actual behavior
Start remote program (startProgram-Docker.sh), start the debugger, and then the debugger infinitely hangs. 

However, when I shutdown the remote server the following message pops up in an error dialog within VS Code: "Debug adapter process has terminated unexpectedly"...this must mean that the debugger becomes attached correct? 

## Expected  behavior
Start remote program (startProgram-Docker.sh), start the debugger, and then the debugger should hit a breakpoint I set in a Python script that exists in the remoteRoot and I know executes upon server startup.

## Steps to reproduce:  

1. Add the following launch configuration to launch.json:
```
        {
            "name": "Attach to DSWB Instace (Remote Debug)",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "/home/ubuntu/notebook_server", // directories exist here which contain more directories and files in multiple languages, including Python, used to run the server
            "port": 8443, // VBox forwards this port so it can be accessed locally
            "secret": "my_secret",
            "host":"hostname.com" // hostname.com equates to the Docker machine's IP
        }
```

2. Execute the startProgram-Docker.sh mentioned above to start up the server remotely.

3. Launch the debugger

4. Nothing happens

## Logs
Output from ```Python``` output panel  
```
Nothing
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
Debug adapter process has terminated unexpectedly
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
_.onServerExit @ rawDebugSession.ts:535
(anonymous) @ rawDebugSession.ts:449
emitTwo @ events.js:111
emit @ events.js:194
__dirname.ChildProcess._handle.onexit @ internal/child_process.js:215
```

**Comment by cratter49** [comment]
@DonJayamanne?

**Comment by DonJayamanne** [comment]
Please use ptvsd 3.0.0

**Comment by DonJayamanne** [comment]
Let me know how that goes. Also, debugging Jupiter kernels are not supported.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#214
