### ISSUE TITLE
Please add a setup linter's run directory

### ISSUE THREAD

**Issue by Derik117** [DonJayamanne/pythonVSCode#1370]
Hi! 
I was same problem with pylint(I think this problem have all other linters) - no way to change linter run directory for project.

Example.
I have example project with that structure
```
├── .git
├── .gitignore
├── README.md
├── requirements.txt
├── src
├──── main.py
└──── my_class.py
```

main.py
`from my_class import MyClass # on this line linter throw error because it expects something like from src.my_class import MyClass `

my_class.py
```
class MyClass:
    pass
```

My project was created for run from `src` folder. But by default linter was running from project root directory and I can't find way to change it.

May you add this functionality, please?

**Comment by DonJayamanne** [comment]
1. Please create a file named ```.env``` in your root directory
2. Add the following entry:
```
PYTHONPATH=./src
```
3. Restart VS Code
4. Try running the tests now

**Comment by Derik117** [comment]
It work, thanks!
