### ISSUE TITLE
autopep8 not working in ubuntu 17.10

### ISSUE THREAD

**Issue by JensMadsen** [DonJayamanne/pythonVSCode#1371]
## Environment data
VS Code version:  Version 1.17.2
Python Extension version:  
Python Version:   Python 3.6.3
OS and version:    ubuntu 17.10

## Actual behavior
format document -> error message "Formatter yapf is not installed" or "Formatter autopep8 is not installed" -> after installation 
```
/usr/bin/python -m pip install autopep8
Collecting autopep8
Collecting pycodestyle>=2.3 (from autopep8)
Using cached pycodestyle-2.3.1-py2.py3-none-any.whl
Installing collected packages: pycodestyle, autopep8
Successfully installed autopep8-1.3.3 pycodestyle-2.3.1

```
still does not work. I have removed vs code and installed i again. Still no luck

## Steps to reproduce:  
-  
-  

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by brettcannon** [comment]
Have you verified that `/usr/bin/python` is what VS Code is picking up as your interpreter? Have you explicitly specified that as the path to your Python interpreter in your settings?

**Comment by JensMadsen** [comment]
I use anaconda. Typing python the terminal gets me the wanted anaconda installation. I have followed your suggestion and changed the `python.Pythonpath' to the locationof the anaconda python installation but with no luck. It worked for me before I upgraded my ubuntu from 17.04 to 17.10

**Comment by brettcannon** [comment]
Last thing to test is a file in a workspace that consists of:
```python
import autopep8
```
And then run **Run Python File in terminal**. If that raises an exception then `autopep8` didn't get installed properly. If it passes then there's an issue in the extension.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#215

**Comment by shashank10021997** [comment]
Python Version: Python 3.6.3
OS and version: ubuntu 17.10
autopep8 is not working.i also import autopep8 and ran in terminal and still not working

**Comment by DonJayamanne** [comment]
@shashank10021997
Please create issues in the Microsoft fork, we'll look into issues from there.
