### ISSUE TITLE
Requires mandatory "--python-version" settings in mypy setup

### ISSUE THREAD

**Issue by sametmax** [DonJayamanne/pythonVSCode#1376]
## Environment data
VS Code version:  1.17.2
Python Extension version:  latest to this date
Python Version:  any
OS and version:    

## Actual behavior

Mypy checks the code against the version of Python it's installed in.

## Expected  behavior

My checks the code against the version of Python the code is written in.

More details here: https://github.com/python/mypy/issues/4222#issuecomment-342916300

## Steps to reproduce:  
-  Install mypy with "python3.5 -m pip install"
-  Setup and use vscode with mypy normally

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#217
