### ISSUE TITLE
Vscode doesnot stop at break point during debugging

### ISSUE THREAD

**Issue by sathisz** [DonJayamanne/pythonVSCode#1377]
## Environment data
VS Code version:  1.18
Python Extension version:  latest
Python Version:   3.4.3
OS and version: Linux Mint 18.1

## Actual behavior
No action performed

## Expected  behavior
Stops at the break point when it hits

## Steps to reproduce:  
-  
-  

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#218
