### ISSUE TITLE
What causes extension host terminated unexpectedly. Code:  3221226505  Signal:  null

### ISSUE THREAD

**Issue by Zedonboy** [DonJayamanne/pythonVSCode#1386]
I dont know why i still keep getting this error.
i have installed insider.
i have disabled git. 
Honestly this error, changes my emotion if use VScode in the mourning
## Environment data
VS Code version:  1.18.0
Python Extension version:  0.8.0
Python Version:   3.6
OS and version:    win10 creators

## Steps to reproduce:  
-  
-  

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
Please check if there are any errors looked in console window.
Please try reinstalling the extension.

**Comment by Zedonboy** [comment]
I have done everything from removing git, reinstalling Vscode, reinstalling python, even trying to reverse enginneer, by changing the implementation of e.onExtensionCrash() function.

Someone said its segmentation fault, i stupidly download 32bit. still say the same.
am think of getting the source customize it for myself.
sometimes i feel why are my own things different. Everybody video games install fine, but mine always error.

@DonJayamanne  doing a good job, trying to attend to me. i have followed all issues and their proposed solutions, done all of 'em. I want to know the causes

**Comment by DonJayamanne** [comment]
@Zedonboy Please could you try the steps in here https://github.com/Microsoft/vscode-python/issues/342#issuecomment-360573536 and upload the log file.
FYI - The extension is now published under Microsoft.
Please raise all future issues in the Microsoft repo, i'll look into the issues from there.
