### ISSUE TITLE
Wiki suggestion: vscode-ipynb-py-convert python module for jupyter vscode

### ISSUE THREAD

**Issue by nojvek** [DonJayamanne/pythonVSCode#1387]
I was trying to figure out how to make a PR for wiki but couldn't figure out so made a PR.

I really like the jupyter support provided by the plugin. While working on the udacity courses, they use jupyter notebook but I'm not a big fan of the editor in jupyter. So I made a python module that converts from .ipynb to .py and .py to .ipynb files. I would like to add a link to the module to https://github.com/DonJayamanne/pythonVSCode/wiki/Jupyter-(IPython)

The jupyter notebook cells become `# %% <content>`  in .py files which can be run inside vscode. '

In essence this allows one to run jupyter notebooks inside vscode by doing a `python -m vscode-ipynb-py-convert examples/plot.ipynb examples/plot.py` 

See https://github.com/nojvek/vscode-ipynb-py-converter

**Comment by DonJayamanne** [comment]
Closing this issue as the Jupyter functionality will be removed in a future version, as all of that functionality has been moved into a separate extension (https://marketplace.visualstudio.com/items?itemName=donjayamanne.jupyter).

**Comment by nojvek** [comment]
What's the repo for that extension? Does it have a wiki?

**Comment by DonJayamanne** [comment]
All of the information is on the Market place.
