### ISSUE TITLE
Error: "No tests ran, please check the configuration settings for the tests."

### ISSUE THREAD

**Issue by garytyler** [DonJayamanne/pythonVSCode#1388]
I am getting error message "No tests ran, please check the configuration settings for the tests."
![capture3](https://user-images.githubusercontent.com/15917021/33537262-b9463b0c-d888-11e7-9173-9010ab775e69.PNG)

The tests run fine in command line: 
![capture2](https://user-images.githubusercontent.com/15917021/33537246-9e9cd39c-d888-11e7-997f-ebba76e5a0ff.PNG)

Here is the sample code I am using:
![capture4](https://user-images.githubusercontent.com/15917021/33537250-a6c85744-d888-11e7-8b4a-4f45cc75e775.PNG)

Here are my settings:
![capture](https://user-images.githubusercontent.com/15917021/33537272-c2617f8a-d888-11e7-94a9-af5ede50e303.PNG)

I have looked through what little docs I could find and am out of ideas.

**Comment by DonJayamanne** [comment]
Please create the issue on the official Microsoft Repo, the extension is no longer maintain in this repo.
