### ISSUE TITLE
Failed to find python unit tests

### ISSUE THREAD

**Issue by ehuang3** [DonJayamanne/pythonVSCode#1389]
## Environment data
VS Code version:  1.18.1
Python Extension version:  0.8.0
Python Version:   2.7.6
OS and version:    Ubuntu 16.04

## Actual behavior

Fails to find unit-tests with the error. No longer prompts me to pick unit test frame work and test regex.

## Expected  behavior

Finds unittests.

## Steps to reproduce:  
-   My tests are located in the directory \<tests\>

> .
> ├── \<package\>
> │   ├── \_\_init__.py
> │   ├── \<tests\>

-  

## Logs
Output from ```Python``` output panel  
```
Test Discovery failed: 
Command failed: python -c import unittest
loader = unittest.TestLoader()
suites = loader.discover("./deep2d", pattern="test*.py")
print("start") #Don't remove this line
for suite in suites._tests:
    for cls in suite._tests:
        try:
            for m in cls._tests:
                print(m.id())
        except:
            pass
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
console.ts:123 [Extension Host] rejected promise not handled within 1 second
t.log @ console.ts:123
shell.ts:459 Command failed: python -c import unittest
loader = unittest.TestLoader()
suites = loader.discover("./deep2d", pattern="test*.py")
print("start") #Don't remove this line
for suite in suites._tests:
    for cls in suite._tests:
        try:
            for m in cls._tests:
                print(m.id())
        except:
            pass
```

**Comment by DonJayamanne** [comment]
1. What are the contents of your workspace settings `settings.json`?
2. Are you able to run the test from the command prompt from the root directory? 
If so, please provide the command line used.

**Comment by DonJayamanne** [comment]
Please add issues on the new Microsoft repo, that's where the extension is maintained.
https://github.com/Microsoft/vscode-python
