### ISSUE TITLE
"python.pythonPath" overrides not taken into account

### ISSUE THREAD

**Issue by p0la** [DonJayamanne/pythonVSCode#139]
Hello, on a mac, default python is 2.7.1 (preinstalled by apple). 
Trying to override the `"python.pythonPath"` variable with something like `"/Library/Frameworks/Python.framework/Versions/3.4/bin/python3"` doesn't seem to have any impact: 

```python
import sys 
print(sys.version)
```
returns: 
```
2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
```

**Comment by p0la** [comment]
I tried to figure out where the information of my path override was lost but couldn't. As a temporary fix I have overriden the `pythonPath` variable in `~/.vscode/extensions/donjayamanne.python-0.3.7/out/client/debugger/DebugClients/LocalDebugClient.js:149`. 
Will try to investigate further when I have more time.

**Comment by DonJayamanne** [comment]
Have you set this path in the launch.json file, instead of the settings file?

**Comment by p0la** [comment]
Thanks for the prompt reply. I'm not sure I understand your question. 
My launch.json looks like this: 
```json
"configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${file}",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        +....   
 ]        
```
Am I supposed to add a `"python.pythonPath"` in there ? 

What I did was to add 
```json
{
    "python.pythonPath": "/Library/Frameworks/Python.framework/Versions/3.4/bin/python3",
}
```
in the `settings.json` in my project folder as well as in `~/Library/Application Support/Code/User/settings.json`.

**Comment by DonJayamanne** [comment]
Yes you need to set the path in the launch.json file as well.

**Comment by andresgottlieb** [comment]
@DonJayamanne should we do this for every project or is there a way to set a pythonPath as default for new launch.json files?

**Comment by DonJayamanne** [comment]
Unfortunately the launch.json needs to be configured in every project. In a future release of vs code (hopefully end of July), this won't be necessary.

**Comment by andresgottlieb** [comment]
Thanks
