### ISSUE TITLE
Flask_script with venv debug does not working

### ISSUE THREAD

**Issue by Sabutobi** [DonJayamanne/pythonVSCode#1398]
## Environment data
VS Code version:   1.20.1
Python Extension version:  2018.1 (01 Feb 2018)
Python Version:   3.6
OS and version:    Ubuntu 16.04

## Actual behavior
ModuleNotFoundError, No module named 'flask_script'
NOTE: if I'll try to run from terminal:
`source ./venv/bin/activate`
`python manage.py runserver --port 50000 --host some.valid.ho.st`
All dependencies are working as expected
## Expected  behavior
Enable debug and breakpoints. Dependencies imported as expected.
## Steps to reproduce:  
-  Add this object launch.json :
`{
            "name": "Somename",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${workspaceFolder}/venv/bin/python3.6",
            "program": "${workspaceFolder}/manage.py",
            "cwd": "${workspaceFolder}",
            "env": {},
            "envFile": "${workspaceFolder}/.env",
            "console": "integratedTerminal",
            "args": [
                "runserver",
                "--port",
                "50000",
                "--host",
                "somevalidHost"
            ],
            "debugOptions": [
                "RedirectOutput"
            ]
        },`
-  Add this workspace settings:
`{
    "python.linting.pylintArgs": [
        "--load-plugins",
        "pylint_flake8"
    ],
    "python.linting.enabled": true,
    "python.linting.lintOnSave": true,
    "python.linting.pylintEnabled": true,
    "editor.formatOnSave": true,
    "python.linting.pylintPath": "pylint",
    "python.formatting.provider": "autopep8",
    "python.linting.flake8Path": "flake8",
    "python.linting.flake8Enabled": true,
    "editor.rulers": [
        120
    ],
    "python.terminal.activateEnvironments": false,
    "python.unitTest.pyTestEnabled": false,
    "python.pythonPath": "${workspaceFolder}/venv/bin/python3.6"
}`
- add this .env file:
`PYTHONPATH=/full/path/to/folder/venv/bin/python3.6`
## Logs
Output from ```Python``` output panel  
None output from Python. From integratedTerminal:
```

`cd /home/path/to/folder ; env "PYTHONPATH=/home/path/to/folder/venv/bin/python3.6" "PYTHONIOENCODING=UTF-8" "PYTHONUNBUFFERED=1" /home/path/to/folder/venv/bin/python3.6 /home/user/.vscode/extensions/ms-python.python-2018.1.0/pythonFiles/PythonTools/visualstudio_py_launcher.py /home/user/Documents/project_folder 42923 34806ad9-833a-4524-8cd6-18ca4aa74f14 DUMMYVALUE /home/user/path/tofolder/manage.py runserver --port 50000 --host some.valid.ho.st 
Traceback (most recent call last):
  File "/home/path/to/folder/manage.py", line 7, in <module>
    from flask_script import Command, Manager, Option, Server, Shell
ModuleNotFoundError: No module named 'flask_script'`

```   
Output from ```Console window``` (Help->Developer Tools menu)
```
Developer Tools / console is empty
```

**Comment by DonJayamanne** [comment]
This setting in is invalid. PYTHONPATH should point to a directory not to the interpreter. Either way this setting is not necessary in this case. Please check the python docs to learn about PYTHONPATH variable. 
Once fixed, please try again

**Comment by DonJayamanne** [comment]
Please report issues on the Microsoft repo.

**Comment by Sabutobi** [comment]
.env file has been deleted. Same issue.

**Comment by Sabutobi** [comment]
Please report issues on the Microsoft repo.
- Done. Thanks for attention
