### ISSUE TITLE
Where is  a sample settings.json?

### ISSUE THREAD

**Issue by coladou** [DonJayamanne/pythonVSCode#14]

**Comment by coladou** [comment]
That's a wonderful plugs. But where is a sample settings.json...

**Comment by DonJayamanne** [comment]
Hi, I agree there the documentation is quite appalling. I adv currently working on updating the documentation. I will release a new build some time early next week. Just trying to finish up the documentation.

**Comment by coladou** [comment]
That's great! @DonJayamanne

**Comment by DonJayamanne** [comment]
document has been updated along with the new release
