### ISSUE TITLE
Extension host terminated unexpectedly. Code:  3221225477 

### ISSUE THREAD

**Issue by Keltah** [DonJayamanne/pythonVSCode#1401]
It's the same error for weeks, no update has solved the problem. I have reinstalled the extension several times, I have even reinstalled Visual Code Studio several times. I checked it out and it's the only extension that causes the problem. I am no longer what to do apart, it is not even possible to close the notification. I open Visual Code Studio and the error appears.

## Environment data
VS Code version: 1.20.1
Python Extension version: 2018.1.0
Python Version: 3.6
OS and version: Windows 10

## Logs
![screenshot_9](https://user-images.githubusercontent.com/4116753/36490209-106d7ac0-1728-11e8-9a0b-243c15be7c2a.png)

**Comment by MikhailArkhipov** [comment]
Please open issues in https://github.com/Microsoft/vscode-python, this fork is not actively monitored.
