### ISSUE TITLE
I can not debug python code

### ISSUE THREAD

**Issue by maraal** [DonJayamanne/pythonVSCode#1406]
## Environment data

- VS Code version: 1.21.1
- Extension version (available under the Extensions sidebar): 2018.2.1
- OS and version: macOS Sierra (10.12.6)
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.4
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A(not tried in virtual environment)

## Actual behavior

When I press F5 or manually asks to debug, an error occurs:

> Traceback (most recent call last):
>   File "/Users/afonso/.vscode/extensions/ms-python.python-2018.2.1/pythonFiles/PythonTools/visualstudio_py_launcher.py", line 91, in <module>
> 

## Expected  behavior

Debug my code.

## Steps to reproduce:
1. Open a .py file
2. Press F5 or Satart Debugging 

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
##########Linting Output - pylint##########
No config file found, using default configuration

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

##########Linting Output - pylint##########
No config file found, using default configuration

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`)

```
[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.
```

**Comment by DonJayamanne** [comment]
Please report issues on the Microsoft repo.
Also provide the full error message, you have only provided the stack Trace and not the error message.
