### ISSUE TITLE
Lint (pylint, flake8) fail when file accessed is under directory path containing spaces

### ISSUE THREAD

**Issue by PhilMacKay** [DonJayamanne/pythonVSCode#1407]
## Environment data

- VS Code version: 1.21.1
- Extension version (available under the Extensions sidebar): 2018.3.0
- OS and version: Windows 10 Pro version 1709
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.4
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: PyLint 1.8.3

## Actual behavior

When PyLint is run on a path containing a whitespace, PyLint fails to find the python script being analysed, finding the following problem: `[pylint] F0001:No module named "c:/Path With Space/script.py"`

## Expected  behavior

When running pylint from the terminal, the correct behaviour happens:
```
No config file found, using default configuration
************* Module ProcessInPython
C:106, 0: Exactly one space required after comma
[...]
------------------------------------------------------------------
Your code has been rated at 5.78/10 (previous run: 9.63/10, -3.85)
```

## Steps to reproduce:
1. Open any python script located in a folder with a whitespace
2. run linting (F1, then ">Python: Run Linting")
3. Look at the output from the Python terminal

## Logs

```
##########Linting Output - pylint##########
No config file found, using default configuration
************* Module "c:/Path With Space/script.py"
1,0,fatal,F0001:No module named "c:/Path With Space/script.py"

```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`)

```
No output, even with verbose level
```

**Comment by DonJayamanne** [comment]
This has been fixed in the latest update.
