### ISSUE TITLE
Having trouble reading the stack trace in the results when using a dark background

### ISSUE THREAD

**Issue by toddljones** [DonJayamanne/pythonVSCode#1412]
Having trouble reading the stack trace in the results when using a dark background

![image](https://user-images.githubusercontent.com/9160245/41436014-1b28fcfc-6fe6-11e8-9561-481be8df5390.png)

**Comment by DonJayamanne** [comment]
This is the wrong repo, please file issues against the Jupyter Extension repo on Gihub
