### ISSUE TITLE
VSCode shows wrong python version for venv virtual environments

### ISSUE THREAD

**Issue by kazaamjt** [DonJayamanne/pythonVSCode#1417]
## Environment data

- VS Code version: 1.24.1
- Extension version (available under the Extensions sidebar): 2018.6.0
- OS and version: Windows 10 - 1803
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.6
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
- Relevant/affected Python packages and their versions: N/A

This is a new computer, so I just downloaded the latest stable version of python. (3.7.0)
However, this resulted in some bugs when using pylint and the like, so I uninstalled it and installed 3.6.6 instead.
I do not currently have python 3.7.0 installed anymore.

## Actual behavior

When selecting what env to use, vscode correctly displays 3.6.6 as my default python version but the virtual environment (generated with said python 3.6.6) displays as 3.7.0.
Just to be sure I ran ´.\venv\Scripts\python.exe --version´ which returned `Python 3.6.6`.
I also checked `.\venv\pyvenv.cfg` for it's version and again: `version = 3.6.6`

## Expected  behavior

The virtual environment should display version 3.6.6 instead of 3.7.0

## Steps to reproduce:
I wish I could tell you how to reproduce this, but I haven't been able to get rid of it, so I have no idea what might have caused it.

**Comment by DonJayamanne** [comment]
Please create an issue if the Microsoft repo.
