### ISSUE TITLE
Arguments are lost in the launcher

### ISSUE THREAD

**Issue by Meithal** [DonJayamanne/pythonVSCode#1421]
Hello,

The script here says 

https://github.com/DonJayamanne/pythonVSCode/blob/master/pythonFiles/PythonTools/visualstudio_py_launcher.py#L52

`# 7. Script arguments.`

But I see nowhere in that file how those arguments are used, it feels like they are lost when you del sys at line 86 and indeed the script behaves oddly because of that I believe.

Regards

**Comment by DonJayamanne** [comment]
Please report issues on the microsoft repo.
Also, please provide information on the actual problem.
I.e. what's the problem you are experiencing.
