### ISSUE TITLE
Support pylintrc files for pylint

### ISSUE THREAD

**Issue by baumatron** [DonJayamanne/pythonVSCode#146]
Thanks for a great tool!

One of the features I've thought would be helpful is if there were support for a pylintrc file for the built-in pylint support.

**Comment by DonJayamanne** [comment]
Great idea, makes a lot of sense. Will do.

**Comment by DonJayamanne** [comment]
Done, Just place the pymintrc file in the workspace root and it should work.
In fact this has always worked.
