### ISSUE TITLE
ImportError, cannot import name '_fileobject' or 'winreg' with Boto3

### ISSUE THREAD

**Issue by CarmenAPuccio** [DonJayamanne/pythonVSCode#147]
I'm getting an ImportError when Debugging with Boto3. I originally opened an issue over on the Boto3 page but they seem to think it's actually an issue with pythonVSCode

https://github.com/boto/boto3/issues/667

Simple script for an example after setting up your environment for Python3

from future import print_function # Python 2/3 compatibility
import sys
import boto3
import json
from botocore.exceptions import ClientError

File: /usr/local/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/contrib
import OpenSSL.SSL
from pyasn1.codec.der import decoder as der_decoder
from pyasn1.type import univ, constraint
from socket import _fileobject, timeout

File: /usr/local/lib/python3.5/site-packages/dateutil/tz/win.py
import datetime
import struct

from six.moves import winreg

Results in:
ImportError, cannot import name '_fileobject'
ImportError, cannot import name 'winreg'

**Comment by DonJayamanne** [comment]
Hi please could you confirm you have configured the python path setting in the launch.json file and that this works when running outside vs code?

**Comment by CarmenAPuccio** [comment]
Correct. It works with no issue outside vs code. Interestingly enough, you can build it in code and it'll run fine. It just errors on debug.

Here is the launch.json, settings.json and tasks.json
Launch.json:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${file}",
            "pythonPath": "/usr/local/bin/python3",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Python Console App",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${file}",
            "externalConsole": true,
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
        {
            "name": "Django",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${workspaceRoot}/manage.py",
            "args": [
                "runserver",
                "--noreload"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "DjangoDebugging"
            ]
        },
        {
            "name": "Watson",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${workspaceRoot}/console.py",
            "args": [
                "dev",
                "runserver",
                "--noreload=True"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }
    ]
}

Settings.json:
// Place your settings in this file to overwrite default and user settings.
{
    "python.pythonPath":  "/usr/local/bin/python3"
}

Tasks.json:
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "/usr/local/bin/python3",
    "isShellCommand": true,
    "args": ["${file}"],
    "showOutput": "always"
}

**Comment by DonJayamanne** [comment]
Thanks, I'll look into this soon.

**Comment by DonJayamanne** [comment]
Hi @CarmenAPuccio, are you still experiencing this issue?

**Comment by CarmenAPuccio** [comment]
I just updated to the latest version of the extension and the latest version of Visual Studio Code and I am not seeing it anymore when I debug an boto3 script. Did you fix it?

**Comment by DonJayamanne** [comment]
There have been plenty of fixes since you reported this issue. It is possible one of those fixes resolved your issue. 
I'll close this issue, if you still encounter the issue, then please do re-open the issue.

**Comment by wulftone** [comment]
This still exists!  I am encountering it now with python3 and vscode
