### ISSUE TITLE
Debugger does not kill process

### ISSUE THREAD

**Issue by hedin** [DonJayamanne/pythonVSCode#15]
It seems that debugger does not kill process that uses wsgiref's _serve_forever()_ loop. Neither when you press Stop nor when you close VSCode.

**Comment by DonJayamanne** [comment]
The new release should resolve this issue, please test and let me know.

**Comment by hedin** [comment]
I'm sorry for my late reply. But I can't test it because of #23

**Comment by hedin** [comment]
It works now. Thanks!

**Comment by DonJayamanne** [comment]
Phew, so it's ok that I closed the issue. Thanks for confirming it's I closed it fearing that you had moved on and wouldn't be checking this out any more.
