### ISSUE TITLE
Autocomplete for arguments with default values with same name adds default value

### ISSUE THREAD

**Issue by bigonazzi** [DonJayamanne/pythonVSCode#153]
When I create a specialized function and pass along an existing parameter with a default,  autocomplete suggests name + default value instead of just the name of the argument. In the example below it should suggest "silent" instead of "silent=True":

![image](https://cloud.githubusercontent.com/assets/4755/16020880/d40ba584-3164-11e6-8618-d432aae291db.png)

**Comment by DonJayamanne** [comment]
Closing as this is the same as #71

**Comment by DonJayamanne** [comment]
Suggestion for #183
