### ISSUE TITLE
Django debug stopped working after VSCode update

### ISSUE THREAD

**Issue by lzantal** [DonJayamanne/pythonVSCode#155]
Hi,

I have updated VSCode to the latest version as well as Python extension.
Now I can not debug django project. It worked perfect before.
When I run the same project I get the following message in the terminal when a breakpoint should be hit
```
command.breakpoint.hit
```
Also the break point turns into a gray circle and on hover it says "unverified breakpoint"

**Comment by DonJayamanne** [comment]
Hi @lzantal, nothing has changed in VS Code with regards to django debugging. 
Can you try removing the breakpoints, next debug the django project. Once it has loaded then try adding the breakpoints.
Also, please ensure you are using the django debug configuration.

**Comment by lzantal** [comment]
@DonJayamanne add breakpoints while the debug session is running? I tried it and it does not get triggered. I am on Mac btw. 
I am going to try it with another project as well, but all my projects setup the same way.

**Comment by lzantal** [comment]
Tried it with 2 other projects, it takes a very long time to start up and break points are not triggered. When I select my breakpoints in the Debug view at the bottom it shows them in gray and says "unverified breakpoint". This is the latest VSCode 1.2.0
I will update on the Linux machine and see if it's only issue on the mac.

**Comment by DonJayamanne** [comment]
Please could you try something as simple as the following django sample?
Try adding a breakpoint to the index (line ```return HttpResponse('Powered by Django') ```
```python
import sys

from django.conf import settings
from django.conf.urls import patterns
from django.http import HttpResponse
from django.core.management import execute_from_command_line

settings.configure(
    DEBUG=True,
    SECRET_KEY='placerandomsecretkeyhere',
    ROOT_URLCONF=sys.modules[__name__],
)

def index(request):
    return HttpResponse('Powered by Django')

urlpatterns = patterns('', 
    (r'^$', index),
)

if __name__ == "__main__":
    execute_from_command_line(sys.argv)
```

**Comment by DonJayamanne** [comment]
@lzantal , any luck?

**Comment by lzantal** [comment]
Sorry! Work got in the way. Just tried it and it works. But when I set it next to the function it just skips it.
No biggie, I just have to move my breakpoints below the function declarations. Doing that in my projects it works as well.

Thank you for your help!!

**Comment by DonJayamanne** [comment]
Thanks for checking this out.

**Comment by Kurara** [comment]
For me it's not working. This morning it was working now SUDDENLY (without updating) it is not. My configuration:

            "name": "Django",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${workspaceRoot}/manage.py",
            "cwd": "${workspaceRoot}",
            "args": [
                "runserver",
                "--noreload",
                "--settings",
                "settings.local",
                "0.0.0.0:8000"
            ],
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "DjangoDebugging"
            ]

(althought it sais that `debugOptions` is not allowed )
What happend is that it stops in the breakpoint for a second, then it jumps ALWAYS to:
`    execute_from_command_line(sys.argv)
`
