### ISSUE TITLE
"error: release unlocked lock" from visualstudio_py_debugger.py while debugging

### ISSUE THREAD

**Issue by PeterLakov** [DonJayamanne/pythonVSCode#16]
I am debugging a Python script, which at some point has 2 threads (probably since it includes the web driver). At some point, the script fails with the error below.

This is a pretty urgent issue as it reproduces fairly consistently.

Error:

Traceback (most recent call last):
  File "/Users/PeterLakov/.vscode/extensions/donjayamanne.python-0.2.4/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1627, in loop
    cmd()
  File "/Users/PeterLakov/.vscode/extensions/donjayamanne.python-0.2.4/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1899, in command_execute_code
    thread.run_on_thread(text, cur_frame, eid, frame_kind, repr_kind)
  File "/Users/PeterLakov/.vscode/extensions/donjayamanne.python-0.2.4/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1227, in run_on_thread
    self.schedule_work(lambda : self.run_locally(text, cur_frame, execution_id, frame_kind, repr_kind))
  File "/Users/PeterLakov/.vscode/extensions/donjayamanne.python-0.2.4/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1219, in schedule_work
    self.unblock()
  File "/Users/PeterLakov/.vscode/extensions/donjayamanne.python-0.2.4/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1215, in unblock
    self._block_lock.release()
error: release unlocked lock

I installed the build on 1/12/2016, around 12:20pm US Eastern Standard Time. The latest commit was 1ba3257123a9f5ec7c5d867f79e039b35620b001

A quick look at the code in visualstudio_py_debugger.py shows that in this callstack a lock is acquired in run_on_thread() for self._block_starting_lock, but released in unblock() for self._block_lock - not sure if these two are synchronized somewhere in between or that's causing the issue.

**Comment by DonJayamanne** [comment]
Hi Peter, I will be releasing a new version sometime  next week around Monday or Tuesday. I have fixed an issue when debugging multiple threads. Hopefully that will fix your issue. If it isn't resolved we'll them have to look into this separately.

**Comment by DonJayamanne** [comment]
Oh wait, you have tried the latest build, hmmm. Let me have a look at this and get back to you. In the mean time is it possible to upload the sample code so I could test it at my end?

**Comment by PeterLakov** [comment]
Hi Don,

 

Thanks a lot for the quick response – it’s very cool  that you are replying and looking with urgency at issues.

 

Regarding the two responses you sent – on the latest build – I was using the latest build as of the time I submitted the bug. But if you have a newer build that will fix some issues, it might potentially fix mine too – I’ll keep an eye for updates on Tuesday/Wednesday, and if I see one, I’ll install it and rerun the code.

 

Regarding sending you a repro of the problem – the code that is having the problem is a corporate owned code (and it’s a fairly big codebase which I don’t have much experience with), so I can’t easily send you a repro script. I’ll take a look on Tuesday at whether I can simplify the code to the point where it’s trivial and doesn’t include any corporate IP and send you a repro that way.

 

Best,

Peter

 

 

 <https://github.com/DonJayamanne> 

Owner

 <https://github.com/DonJayamanne> DonJayamanne commented 2 days ago <https://github.com/DonJayamanne/pythonVSCode/issues/16#issuecomment-183511217> 

Hi Peter, I will be releasing a new version sometime next week around Monday or Tuesday. I have fixed an issue when debugging multiple threads. Hopefully that will fix your issue. If it isn't resolved we'll them have to look into this separately.

 <https://github.com/DonJayamanne> 

Owner

 <https://github.com/DonJayamanne> DonJayamanne commented 2 days ago <https://github.com/DonJayamanne/pythonVSCode/issues/16#issuecomment-183512321> 

Oh wait, you have tried the latest build, hmmm. Let me have a look at this and get back to you. In the mean time is it possible to upload the sample code so I could test it at my end?

**Comment by DonJayamanne** [comment]
I have uploaded a new version, please install the new version and let me know how it goes.

**Comment by PeterLakov** [comment]
I updated to version 0.2.8 just 30 minutes ago and rerun my script, but it fails in the same way, with the same callstack - just the line numbers are slightly different due to the changes in visualstudio_py_debugger.py.
 
From: lakov@hotmail.com
To: reply@reply.github.com
Subject: RE: [pythonVSCode] "error: release unlocked lock" from visualstudio_py_debugger.py while debugging (#16)
Date: Sun, 14 Feb 2016 15:13:55 -0500

Hi Don, Thanks a lot for the quick response – it’s very cool  that you are replying and looking with urgency at issues. Regarding the two responses you sent – on the latest build – I was using the latest build as of the time I submitted the bug. But if you have a newer build that will fix some issues, it might potentially fix mine too – I’ll keep an eye for updates on Tuesday/Wednesday, and if I see one, I’ll install it and rerun the code. Regarding sending you a repro of the problem – the code that is having the problem is a corporate owned code (and it’s a fairly big codebase which I don’t have much experience with), so I can’t easily send you a repro script. I’ll take a look on Tuesday at whether I can simplify the code to the point where it’s trivial and doesn’t include any corporate IP and send you a repro that way. Best,Peter  OwnerDonJayamanne commented 2 days agoHi Peter, I will be releasing a new version sometime next week around Monday or Tuesday. I have fixed an issue when debugging multiple threads. Hopefully that will fix your issue. If it isn't resolved we'll them have to look into this separately.OwnerDonJayamanne commented 2 days agoOh wait, you have tried the latest build, hmmm. Let me have a look at this and get back to you. In the mean time is it possible to upload the sample code so I could test it at my end?   From: DonJayamanne [mailto:notifications@github.com] 
Sent: Friday, February 12, 2016 5:28 PM
To: DonJayamanne/pythonVSCode <pythonVSCode@noreply.github.com>
Cc: PeterLakov <lakov@hotmail.com>
Subject: Re: [pythonVSCode] "error: release unlocked lock" from visualstudio_py_debugger.py while debugging (#16) Hi Peter, I will be releasing a new version sometime next week around Monday or Tuesday. I have fixed an issue when debugging multiple threads. Hopefully that will fix your issue. If it isn't resolved we'll them have to look into this separately.

**Comment by PeterLakov** [comment]
I tried putting breakpoints on the lines from the failing callstack, but those didn't get hit when I was running my code. I suppose that's not the right way to debug the plugin...
 
Do you have some instructions for how to debug the plugin, so I can try to identify why the error occurs? That might be easier than creating a demo script.
 
Thanks.
 
From: lakov@hotmail.com
To: reply@reply.github.com
Subject: RE: [pythonVSCode] "error: release unlocked lock" from visualstudio_py_debugger.py while debugging (#16)
Date: Tue, 16 Feb 2016 09:45:10 -0500




I updated to version 0.2.8 just 30 minutes ago and rerun my script, but it fails in the same way, with the same callstack - just the line numbers are slightly different due to the changes in visualstudio_py_debugger.py.
 
From: lakov@hotmail.com
To: reply@reply.github.com
Subject: RE: [pythonVSCode] "error: release unlocked lock" from visualstudio_py_debugger.py while debugging (#16)
Date: Sun, 14 Feb 2016 15:13:55 -0500

Hi Don, Thanks a lot for the quick response – it’s very cool  that you are replying and looking with urgency at issues. Regarding the two responses you sent – on the latest build – I was using the latest build as of the time I submitted the bug. But if you have a newer build that will fix some issues, it might potentially fix mine too – I’ll keep an eye for updates on Tuesday/Wednesday, and if I see one, I’ll install it and rerun the code. Regarding sending you a repro of the problem – the code that is having the problem is a corporate owned code (and it’s a fairly big codebase which I don’t have much experience with), so I can’t easily send you a repro script. I’ll take a look on Tuesday at whether I can simplify the code to the point where it’s trivial and doesn’t include any corporate IP and send you a repro that way. Best,Peter  OwnerDonJayamanne commented 2 days agoHi Peter, I will be releasing a new version sometime next week around Monday or Tuesday. I have fixed an issue when debugging multiple threads. Hopefully that will fix your issue. If it isn't resolved we'll them have to look into this separately.OwnerDonJayamanne commented 2 days agoOh wait, you have tried the latest build, hmmm. Let me have a look at this and get back to you. In the mean time is it possible to upload the sample code so I could test it at my end?   From: DonJayamanne [mailto:notifications@github.com] 
Sent: Friday, February 12, 2016 5:28 PM
To: DonJayamanne/pythonVSCode <pythonVSCode@noreply.github.com>
Cc: PeterLakov <lakov@hotmail.com>
Subject: Re: [pythonVSCode] "error: release unlocked lock" from visualstudio_py_debugger.py while debugging (#16) Hi Peter, I will be releasing a new version sometime next week around Monday or Tuesday. I have fixed an issue when debugging multiple threads. Hopefully that will fix your issue. If it isn't resolved we'll them have to look into this separately.

**Comment by DonJayamanne** [comment]
I will update the documentation (wiki) with instructions on debugging the extension

**Comment by DonJayamanne** [comment]
Sorry, totally forgot about this. here are the instructions for debugging the extension: https://github.com/DonJayamanne/pythonVSCode/wiki/Contribution

Are you still facing the same issues?

**Comment by DonJayamanne** [comment]
I'll be closing this issue unless you are still facing this issue.
Thanks

**Comment by PeterLakov** [comment]
Don,
Sorry for the slow response. I didn't get a chance yet to work with the scripts that exhibited the problem. I'll try to find them shortly and will ping you if I can get the problem to repro.
Thanks,Peter

Date: Fri, 11 Mar 2016 01:49:46 -0800

**Comment by hakangs** [comment]
Don,

OS : Ubuntu-14.04
VC : 1.3.1
extension version : 0.3.21

I am still facing this issue :

`pyProc.stderr: Traceback (most recent call last):
  File "/home/hakanm/.vscode/extensions/donjayamanne.python-0.3.21/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1646, in loop
pyProc.stderr:     cmd()
  File "/home/hakanm/.vscode/extensions/donjayamanne.python-0.3.21/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1918, in command_execute_code
pyProc.stderr:     thread.run_on_thread(text, cur_frame, eid, frame_kind, repr_kind)
  File "/home/hakanm/.vscode/extensions/donjayamanne.python-0.3.21/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1246, in run_on_thread
    self.schedule_work(lambda : self.run_locally(text, cur_frame, execution_id, frame_kind, repr_kind))
  File "/home/hakanm/.vscode/extensions/donjayamanne.python-0.3.21/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1238, in schedule_work
    self.unblock()
  File "/home/hakanm/.vscode/extensions/donjayamanne.python-0.3.21/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1234, in unblock
    self._block_lock.release()
error: release unlocked lock
Traceback (most recent call last):
  File "/home/hakanm/.vscode/extensions/donjayamanne.python-0.3.21/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1646, in loop
    cmd()
  File "/home/hakanm/.vscode/extensions/donjayamanne.python-0.3.21/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1918, in command_execute_code
    thread.run_on_thread(text, cur_frame, eid, frame_kind, repr_kind)
  File "/home/hakanm/.vscode/extensions/donjayamanne.python-0.3.21/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1246, in run_on_thread
    self.schedule_work(lambda : self.run_locally(text, cur_frame, execution_id, frame_kind, repr_kind))
  File "/home/hakanm/.vscode/extensions/donjayamanne.python-0.3.21/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1238, in schedule_work
    self.unblock()
  File "/home/hakanm/.vscode/extensions/donjayamanne.python-0.3.21/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1234, in unblock
    self._block_lock.release()
error: release unlocked lock`

**Comment by DonJayamanne** [comment]
@hakangs , Please could you provide the steps too reproduce the issue.

**Comment by hakangs** [comment]
Sure,

I am running this :

`import scrapy
from selenium import webdriver

class ProductSpider(scrapy.Spider):
    name = "product_spider"
    allowed_domains = ['ebay.com']
    start_urls = ['http://www.ebay.com/sch/i.html?_odkw=books&_osacat=0&_trksid=p2045573.m570.l1313.TR0.TRC0.Xpython&_nkw=python&_sacat=0&_from=R40']

    def __init__(self):
        self.driver = webdriver.Chrome()
        print("__init__...")

    def parse(self, response):
        self.driver.get(response.url)

        while True:
            next = self.driver.find_element_by_xpath('//td[@class="pagn-next"]/a')

            try:
                next.click()
                print("clicked...")
                # get the data and write it to scrapy items
            except Exception as e:
				print("[ERROR] " + e.__class__.__name__ + ": " + str(e))
				break

        self.driver.close()`

With this launch.json:

`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Python Console App",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "externalConsole": true,
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
        {
            "name": "Django",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${workspaceRoot}/manage.py",
            "args": [
                "runserver",
                "--noreload"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "DjangoDebugging"
            ]
        },
        {
            "name": "Watson",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${workspaceRoot}/console.py",
            "args": [
                "dev",
                "runserver",
                "--noreload=True"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Attach",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "${workspaceRoot}",
            "port": 3000,
            "secret": "my_secret",
            "host": "localhost"
        }
    ]
}`
