### ISSUE TITLE
ss

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#1616]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1.

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local | Remote | N/A
-   **Extension version:** 20YY.MM.#####-xxx
-   **VS Code version:** #.##
-   **Setting python.jediEnabled:** true | false
-   **Setting python.languageServer:** Jedi | Microsoft | None
-   **Python and/or Anaconda version:** #.#.#
-   **OS:** Windows | Mac | Linux (distro):
-   **Virtual environment:** conda | venv | virtualenv | N/A | ...

## Python Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by rchiodo** [comment]
Was this generated?

**Comment by DonJayamanne** [comment]
oh shoot, sorry
