### ISSUE TITLE
Auto generate docstring

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#165]

**Comment by DonJayamanne** [comment]
Suggestions for #183

**Comment by diazgilberto** [comment]
Is this feature working yet? If so, I can't find in VSC how to make it work.

**Comment by mcepl** [comment]
PyCharm has it, so when I function defined, it gives me at least this:
![new_docstring](https://cloud.githubusercontent.com/assets/198999/24057392/82b31f06-0b47-11e7-8dcc-3ebfc9cb8013.png)

**Comment by changkun** [comment]
looking forward for this feature..

**Comment by robodair** [comment]
@DonJayamanne I'd like to have a crack at this, at the moment I'm fixing unit tests on master.

Any pointers on where to start? I'm new to vscode extensions.

**Comment by DonJayamanne** [comment]
@robodair have a look at the following. My suggestion is to first get it working as a stand alone JavaScript piece of code, then try to plug into vscode using typescript. 
https://packagecontrol.io/packages/AutoDocstring

**Comment by DonJayamanne** [comment]
If you need a some more info, let know and I'll try to put something together.

**Comment by robodair** [comment]
Javascript really doesn't seem like the tool for the job here, I feel like I'm fighting with it constantly just to extract arguments (albeit with regex) and there's no way I'm writing a python parser.

I'm thinking of doing something similar to what you've done with Jedi - so I can call out to some python code to actually work out the docstrings and just tie it into the extension more loosely, possibly adapt or generalise SublimeAutoDocstring to support both VSCode and Sublime.

Any reason that's a Bad Thing<sup>TM</sup>?

**Comment by gandhis1** [comment]
That's how the entire extension is designed. None of the syntactical components are in JS. It's all Python components.

**Comment by robodair** [comment]
Neat, I'll work on adding this as a completion provider then.

**Comment by Marcos-Barranquero** [comment]
Would be awesome.

**Comment by Odame** [comment]
Looking forward to this feature

**Comment by edward-agarwala** [comment]
@robodair, Are you still working on this?

**Comment by robodair** [comment]
@edward-agarwala Yes, but Uni has gone back for me and we switched to pycharm at work so I've had no time or motivation to get further quickly I'm afraid.

The python module I'm building is here: https://github.com/robodair/pydocstring

**Comment by AZaugg** [comment]
@DonJayamanne I had a crack at this, azaugg/vscode-python-docstring did you want to take a look, if your happy i can try integrate it into your extensions.

Full disclosure, its pretty basic

**Comment by robodair** [comment]
Made some progress, got something that works, though there may be a few bugs in the docstring formatting.

Not sure how to go about making sure the pydocstring module is installed, ideally I'd like a warning similar to the missing pylint or formatter ones.

This is what it looks like so far:
![docstring](https://user-images.githubusercontent.com/8318231/30513613-89591a76-9b49-11e7-916e-8a19a886fc8b.gif)

**Comment by robodair** [comment]
@DonJayamanne what do you think about going further with this?

I was intending to keep maintaining pydocstring separately and have it be used the same way as pylint, but it might be easier to just take snapshots of the code and include them in the pythonVScode repo every so often?

I've also used the jediProxy to get this working instead of creating another proxy... Which might be not so good of an idea?

**Comment by mcepl** [comment]
@robodair Is there some template or something where I could set what strings and which format parameters are generated?

**Comment by robodair** [comment]
Currently no - it's only formatting google style docstrings because that's what I use.

However, the plan is to have multiple modules under `pydocstring.formatters` (currently there is only `google`) and accept a string parameter when `pydocstring.generate_docstring()` is called, to select which one to use, so we could provide a setting from vscode like `"python.docstringFormat": "numpy"`

**Comment by mcepl** [comment]
I would like to get the one shown in https://github.com/DonJayamanne/pythonVSCode/issues/165#issuecomment-287434730 which I believe is closest to the Pythonic standard, isn't it?

**Comment by robodair** [comment]
Yes that is reST style, default for Sphinx. I'll look at writing a formatter for it when I've sorted out proper integration with vscode.

It's easy to add it to pydocstring, but because I'm just piggybacking on the jediProxy right now to get it working with the extension there's not a place for me to add the preference to send it to pydocstring, without adding some sort of arbitrary object to `ICommand`.

I think that might feel a bit hacked-on, so I'd like @DonJayamanne's or someone else who's familiar with the extension to comment on how the integration of this should work. Possibly adding something more generic than jediProxy that supports some more arbitrary payload would be useful in future (or converting jediProxy to something more generic).

**Comment by DonJayamanne** [comment]
@robodair 
Apologies for the delay. I've had a look at the code and that looks great. Is there any way you could some how make use of the https://github.com/dadadel/pyment library? 
That seems to support various formats.

**Comment by robodair** [comment]
@DonJayamanne I'll take a look - could be great for getting docstring conversion as well as formatting working quicker than I expected.

Is tacking it onto jediProxy ok or would it be better to work on a more elegant solution?

**Comment by DonJayamanne** [comment]
@robodair I'd suggest executing it in a separate python process and capturing the output in stdout (this way the new python process is shortlived and the functionality is self contained).
Let me know if you need any help in setting this up. Have a look at how the formatting and other python files are launched from nodejs in the extension.

**Comment by robodair** [comment]
@DonJayamanne so set up a separate proxy?
Can do - Help would be appreciated because I haven't dealt with that much, but I have read through it and should be able to hack through it without help, might just take a bit longer.

**Comment by DonJayamanne** [comment]
@robodair You might also want to have a look at https://github.com/KristoforMaynard/SublimeAutoDocstring.
Personally I prefer using the AST parser as opposed to string (regex) parsing.  
Or try using Jedi to get the defintion of a function and then use those details to build the documentation.

> Can do - Help would be appreciated because I haven't dealt 

For now, just tack onto the jedi proxy, this way you can focus on the python code.

**Comment by robodair** [comment]
@DonJayamanne the reason I avoided AST is that I wanted it to be able to generate python3 docstrings using python2 - Seemed easier to do with regex, which I modified from SublimeAutoDocstring.
I was hoping to avoid external dependencies but perhaps you're right and I should use jedi instead.

**Comment by robodair** [comment]
I was just looking at pyment - it's GPL v3, so I don't think I can use it from pydocstring and pythonVSCode because they're MIT.

**Comment by robodair** [comment]
I've modified jediproxy to allow a formatter to be specified in settings, there's still an exception thrown if an invalid formatter is specified, and there's no prompt about installing pydocstring.

**Comment by DonJayamanne** [comment]
> I was hoping to avoid external dependencies but perhaps you're right and I should use jedi instead.

Are we using Jedi. Personally I still prefer to use some form of AST?

**Comment by robodair** [comment]
Currently I'm using neither - ast on python 2 won't handle python3 code and vice versa. I suppose I could just assume that the version of python used is the one that the code is for, but then it's not really compatible with both. I figured regex works well enough for the task.

**Comment by mcepl** [comment]
I wonder whether https://github.com/davidhalter/jedi/issues/630 would be relevant discussion here.

**Comment by robodair** [comment]
@mcepl Intriguing.

Meanwhile I've created basic formatters for reST and numpy styles so you should be able to get the style you want. 
https://github.com/robodair/pydocstring/commit/ac3de4a5e8e431a00c73d640443c185d8c6aa6ae

**Comment by robodair** [comment]
Parso looks like it can do the job - but for now so can regex, and I've already written the regex.

Unless there's something that must be done with a parser right now there's no reason it can't be swapped out later, if necessary.

As it stands I think the only thing that would make this not useful right now is the lack of messages/errors when pydocstring is not available, which is more to do with changes to the extension which I'm less familiar with but doesn't seem hard to add.

**Comment by DonJayamanne** [comment]
@brettcannon what do you think about the approach taken by @robodair (using regex).
Personally I'm more inclined to use an ast parsing approach.

**Comment by brettcannon** [comment]
I'm inclined to agree with the AST approach since it's less brittle. It also helps future-proof it if anything changes in syntax or semantics from comments. Lastly, using parso will make maintenance easier long-term as there is a project around parso where everyone can collectively contribute while the regexes are limited to just this extension.

**Comment by DonJayamanne** [comment]
@robodair At the moment I'm included to proceed with an ast approach. Hope you can make the necessary changes. Thanks for your effort.

**Comment by robodair** [comment]
I'll work on it :)

**Comment by DonJayamanne** [comment]
@robodair as mentioned, Please feel free to focus just on the python code using the jedi approach. I can help with the integration. Thanks

@brettcannon any suggestions/recommendations/pointers for @robodair before he gets too far into this work.

**Comment by brettcannon** [comment]
No specific pointers from me other than when in doubt follow [PEP 8](https://www.python.org/dev/peps/pep-0008/)/[PEP 257](https://www.python.org/dev/peps/pep-0257/).

**Comment by zjyExcelsior** [comment]
Looking forward to this feature。。。@DonJayamanne

**Comment by brettcannon** [comment]
One thing I should mention is that if parso doesn't work in terms of typing info (I don't see why it won't, though), there is also [typed_ast](https://github.com/python/typed_ast) from the mypy project.

**Comment by DonJayamanne** [comment]
oooh, neat package

**Comment by sztomi** [comment]
To all commenters: please consider that there is a number of people this issue, because we are interested in updates about how the feature is going, and most of us are getting email notifications.

**Comment by technoiswatchingyou** [comment]
I'm for docstring stuff too!

**Comment by DonJayamanne** [comment]
Closing in favor of https://github.com/Microsoft/vscode-python/issues/165

**Comment by mcepl** [comment]
> Closing in favor of https://github.com/Microsoft/vscode-python/issues/165

@DonJayamanne is it a private repository or what? For me this link leads to 404 page.

**Comment by DonJayamanne** [comment]
Oops, closed the wrong one. I'm in the process of moving the issues to the Microsoft repo.
Thanks for picking that up.

**Comment by DonJayamanne** [comment]
Closing in favor of https://github.com/Microsoft/vscode-python/issues/131

**Comment by NilsJPWerner** [comment]
Hey just in case anyone is still looking for a solution, I put together this extension a little while back and only just got round to publishing it: https://github.com/NilsJPWerner/autoDocstring 

While it's still not finished it does support tabbing and auto generation for kwargs, decorators, returns and errors.

![Example](https://github.com/NilsJPWerner/autoDocstring/blob/master/generate_docstring.gif?raw=true)
