### ISSUE TITLE
Linting with pylint failed.

### ISSUE THREAD

**Issue by YorkZz** [DonJayamanne/pythonVSCode#167]
What should I do with "Linting with pylint failed. If not installed please turn if off in settings. View Python output for details." I've installed pylint.

**Comment by DonJayamanne** [comment]
Please have a look at the python output window and let me know what is in it.

**Comment by DonJayamanne** [comment]
@YorkZz , have you had any luck with this issue?

**Comment by rampage644** [comment]
Here is what i get with same error:
```
Formatting with ${this.Id} failed. Please install the formatter or turn it off.
Error: Invalid patch mode "\" in:  No newline at end of file
```

**Comment by daakarsh** [comment]
Error: spawn pylint ENOENT
this is the output i get for "Linting with pylint failed. Please install the linter or turn it off."

**Comment by DonJayamanne** [comment]
Please install pylint

**Comment by guijianchou** [comment]
Any Python Version require for Pylint ? 2.7 or 3.5

**Comment by DonJayamanne** [comment]
If using python 2.7, then install pylint for that version, similarly pylint for 3.5 if using python 3.5. You need to use the right version of pip.

**Comment by guijianchou** [comment]
thx a lot
