### ISSUE TITLE
Visual Studio Code - stopOnEntry does not work with python

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#168]
http://stackoverflow.com/questions/37385371/visual-studio-code-stoponentry-does-not-work-with-python

>I've try to use VSCode for my python development. Everything works fine, but i have one problem. The stopOnEntry debug settings seems not working.

>At the moment my program always stops on the first line of the program if i hit F5, so i have to hit F5 again to run my entire program.

**Comment by tonka3000** [comment]
@DonJayamanne thx for opening this issue, i wasn't sure if it is a bug or not.

**Comment by andersea** [comment]
That is odd. It works for me.

I am starting a flask app with the following start script (on Windows):

    if __name__ == '__main__':
        from os import environ
        from random import randint
        HOST = environ.get('SERVER_HOST', 'localhost')
        try:
            PORT = int(environ.get('SERVER_PORT', randint(49152,65535)))
        except ValueError:
            PORT = 5555
    
        from myApp import app
        from livereload import Server
        server = Server(app.wsgi_app)
        server.serve(host=HOST, port=PORT, open_url_delay=1)

I run this in a venv using this launch.json:

        {
            "name": "Flask",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${workspaceRoot}/venv/Scripts/python.exe",
            "program": "${workspaceRoot}/runserver.py",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ],
            "env": {
                "FLASK_DEBUG": "1"
            }
        },

As you can see in this image, it stops on the first line, without a breakpoint.

![stopOnEntry](http://i.imgur.com/VfSihd5.png)

The weird thing is, if I set stopOnEntry to false, then I can't use breakpoints inside the startup script (runserver.py). If I set it to true, then I can do it, but it stops on the first line first.

**Comment by andersea** [comment]
If I insert `sleep(1)` at the top of my runserver.py script, breakpoints will work in the code below the sleep call.

    from time import sleep
    sleep(1)
    ## Breakpoints will work from this point on..
    if __name__ == '__main__':
        from os import environ
        from random import randint
        HOST = environ.get('SERVER_HOST', 'localhost')
        try:
            PORT = int(environ.get('SERVER_PORT', randint(49152,65535)))
        except ValueError:
            PORT = 5555
    
        from pyEjd import app
        from livereload import Server
        # app.run(HOST,PORT)
        server = Server(app.wsgi_app)
        server.serve(host=HOST, port=PORT, open_url_delay=1)

**Comment by DonJayamanne** [comment]
@andersea , i've tested this and am unable to replicate this. Please could you post the rest of the code (or at least a cut down version of it). Thanks

**Comment by DonJayamanne** [comment]
Never mind, managed to replicate it with some other simple code:
```python
import sys
print sys.version
print sys.executable
print sys.path
```

**Comment by DonJayamanne** [comment]
@andersea @tonka3000 fixed.

**Comment by mydiva** [comment]
Hi Don,
I have installed latest extension on windows 7. Still not able to stop execution at breakpoint. Can you please provide any help if possible?
launch.json entry:
"version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "pythonPath":"${config.python.pythonPath}", 
            "request": "launch",
            "stopOnEntry": true,
            "externalConsole":false,
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ],
            "env": {"name":"value"}
        },
