### ISSUE TITLE
Intellisense not working for python modules in Anaconda

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#169]
http://stackoverflow.com/questions/36390815/how-to-enable-intellisense-for-python-in-visual-studio-code-with-anaconda3

>However, outside of the core python packages (like "math") intellisense is not working. I've tried to set up the extra environment variable as described in the link, but that didn't work either.

>After this I re-crated an anaconda environment, just in case. Each anaconda environment basically operates as a separate python install and has the modules like "scipy" etc under Lib/site-packages to properly be able to reference them.

**Comment by jakeargent** [comment]
Hello Don, I remembered today that I was going to write here about intellisense behavior.

I updated python extension just now, and checked whether there was any suggestions for `from mat`.

![mat sense](https://cloud.githubusercontent.com/assets/18471520/16356293/704dc3ee-3adb-11e6-8860-e289b9d13770.jpg)
As you can see the only module seen is `math`.

As before, when I hover over `matplotlib`, `matplotlib.pyplot` or `plt` in `import matplotlib.pyplot as plt` the tooltip is stuck at "Loading...".

When I do a similer thing, with `from numpy import linspace as lns`, what happens is `numpy` has a tooltip that says "numpy", `linspace` has several lines of code, and `lns` gets stuck at "Loading...".

At each instance I hovered for about 10 - 15 seconds.

With `import numpy as np`, `np` is stuck with "Loading..." but if I use the shorthand `np`, after the dot there are suggestions. There's no such thing with `matplotlib.pyplot`.

I also tried `import matplotlib as mtp`, and alas, no luck there either. Both tooltips are stuck, and `mtp` doesn't give me any suggestions.

**Comment by DonJayamanne** [comment]
Hi @jakeargent please could you upload your settings.json.
Also, please could you test the code With matplotlib and let me know how whether it works.
one last  question are u using a virtual env.

**Comment by jakeargent** [comment]
Apparently I cannot upload that file type, so here's the code in settings.json:

`// Place your settings in this file to overwrite the default settings
{
	
	// Controls the font size.
	"editor.fontSize": 18,
	
	// Controls the rendering size of tabs in characters. Accepted values: "auto", 2, 4, 6, etc. If set to "auto", the value will be guessed when a file is opened.
	"editor.tabSize": 4,
	
	// Controls after how many characters the editor will wrap to the next line. Setting this to 0 turns on viewport width wrapping
	"editor.wrappingColumn": 80
}`

I'm not using a virtual environment. If you're asking whether the code runs correctly, it does. There's no import error or the like and I can see the graphs that I make without issue.

**Comment by DonJayamanne** [comment]
posh yes What is your os?

**Comment by jakeargent** [comment]
It's windows 10. Although I have the same problem with Linux Mint 17.3

**Comment by DonJayamanne** [comment]
Hi @jakeargent , please could you configure the path to the anaconda python interpreter (executable) in the settings.json in "python.pythonPat" (that should fix it).
Here's [the link](https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version#python-version-used-for-intellisense-autocomplete-linting-formatting-etc)

If it doesn't work, then please let me know the path to your anaconda python executable.

**Comment by jakeargent** [comment]
My active environment is in "C:\Users\Jake\Anaconda3\envs\dataanalysis\python.exe"

I've added this to the settings file, but nothing changed. Linter is still complaining that matplotlib cannot be found, but codes requiring it run just fine.

**Comment by DonJayamanne** [comment]
You need to ensure you have installed pylint against the python version in anaconda . See this [link](https://github.com/DonJayamanne/pythonVSCode/wiki/Troubleshooting-Linting).

**Comment by jakeargent** [comment]
Thanks for the link, pylint now works without fuss.

In that link it's suggested to open VS Code from the terminal to inherit changes, which I've done and... now I'm getting suggestions with `plt.` as expected.

I suppose changing PythonPath worked, but didn't take effect without opening from the console first.

Thanks for the help.

**Comment by DonJayamanne** [comment]
Hi @jakeargent, thats odd. You won't have to start VS code from the terminal to inherit the python environment settings if you have configured it in settings.json.

Please could you try it out once again. Please give it around 5-10 seconds for the intellisense to pickup the libraries and build a local cache.
FYI - this will be improved in a subsequent build.

**Comment by jakeargent** [comment]
When I use the shortcut on Start, intellisense works. `plt` is correctly picked up as pyplot and `plt.` gives the suggestions it should.

Linter acts funny again though.

**Comment by DonJayamanne** [comment]
Hi, I have identified why the linter wouldn't be working on windows. This has been fixed and will be available in the next release.
For now, please launch VS code by activating the relevant python environment and then launching VS Code form the command window as you have done. Thanks for your help.
FYI - I hope to release a new version within a day.
