### ISSUE TITLE
suggestion: choose python2 or python3 by !#/usr/bin/env python2/3

### ISSUE THREAD

**Issue by meritozh** [DonJayamanne/pythonVSCode#17]
Currently,i must modify `python.pythonPath` in `setting.json`. It is tiring if i have both python2 and python3 project. Please add this feature.

BYW, thanks your working for this extension.

**Comment by DonJayamanne** [comment]
I will look into this. I believe I have a solution, sort of.
The problem is when debugging i'm launching a custom python script file which in turn executes the code in the actual script file. I.e. the python interpreter has already loaded even before it gets a chance to inspect the shebang. My solution is to copy the first line from the file being debugged and insert this into my custom file... Dirty, but I guess that's the only way shebang will work.
Will check this out and let you know.

**Comment by DonJayamanne** [comment]
FYI - I haven't forgotten about this, been busy with travel and other work. I am currently testing this fix.

**Comment by michael4reynolds** [comment]
Will the fix include the ability to choose a virtual environment for debugging session?

**Comment by DonJayamanne** [comment]
Unfortunately that is some time away.

**Comment by DonJayamanne** [comment]
Please try the latest build. Oh yes this only works on Windows at this stage and you need to set the pythonPath to "py.exe", I will update the docs later next week.
And support for virtual envs is in development

**Comment by meritozh** [comment]
@DonJayamanne I'm a OS X user. You mean this feature can just works on Windows currently? Not support OS X? (i can't test it now)

**Comment by DonJayamanne** [comment]
That's right, it will only work on Windows at this stage. Getting it working on osx is much more difficult, with permission issues as well. Adding support for virtual environments is much easier for all OS.

**Comment by meritozh** [comment]
I have read source code from #28 about how to implement reading `virtualenv` to set `pythonPath`. How about just create a new private function like `getshebang()` before `getVirtualenvPath()` to read first line from *.py file if this line begin with `#!/usr/bin/env`? Also this function must skip all comments and blank lines before.

Though it is too ugly...

**Comment by DonJayamanne** [comment]
Hmmm sounds good. My plan is to add support to virtual env. The user will select a virtual env  from a list, and then the debugger will invoke the appropriate python executable from the selected environment path. The change you are referring to has been removed due to other issues (basically it doesn't work). Please hang in there, hopefully I will have it fixed before the end of next week.

**Comment by DonJayamanne** [comment]
Have been spending some time on this, unfortunately I am having trouble passing information to the debugger. If the user selects a virtual environment, I can get the IDE to check this and use that for linting and the sorts, however passing this information onto the debugger is not possible - not to my knowledge.

The only (dirty) solution I have is to save the selection into some file and read that during debugging. However this has its own problems, if for instance the user had settings in the launch.json, does the selection override the settings etc...

I.e. this is still a work in progress.

**Comment by dynorphin** [comment]
额，这里讲的是不是说python2和3并存的问题啊，怎么解决啊，我英语不太好 QAQ
Is here talking about the problem of both python2 and python3 that how to select one to use? I'm using Ubuntu gnome 16.04. I'm using python3. But many system programs depend on python2. It's no use to write "python.pythonPath": "/usr/bin/python3" in setting.json. So how can I do?

**Comment by DonJayamanne** [comment]
Sorry but i don't quite understand your question.

**Comment by dynorphin** [comment]
eh...don't understand my text of English?

**Comment by DonJayamanne** [comment]
I didn't understand your question.

**Comment by dynorphin** [comment]
In short,how to use command "python" to link python 2.7 and use python3 in Vscode. thanks:)

**Comment by dynorphin** [comment]
my English is so bad I'm sorry about it!

**Comment by DonJayamanne** [comment]
That's alright. You can use anything you want as long a you configure it in the settings file. So add you mentioned earlier you can configure it as follows:
"python.pythonPath": "/usr/bin/python3"

You could configure this in your user settings file, this way you don't have to configure it everytime.
