### ISSUE TITLE
yapf - nothing to do -> empty file

### ISSUE THREAD

**Issue by 3kwa** [DonJayamanne/pythonVSCode#171]
When there is nothing yapf thinks need to be changed and formatting on save is enabled, the file becomes empty!

It does not happen with autopep8.

Was going to try to figure out why and submit a PR but too many new things to learn before I can hope to achieve that sadly.

That being said I fixed the problem by manually editing the javascript shipped with the extension in baseFormatter.js

`                    if (formattedText === "") {
                        return resolve([]);
                    }`

Since it is relatively bad figured I would create an issue.

**Comment by 3kwa** [comment]
Awesome!

I tried running the extension in Debug mode but couldn't get the formater to work so resorted to using vsce to package and install locally.

There has to be a better way but it is only my first day looking at VS Code.

Thanks again.

**Comment by DonJayamanne** [comment]
Cheers
