### ISSUE TITLE
remote autocomplete

### ISSUE THREAD

**Issue by ograycode** [DonJayamanne/pythonVSCode#179]
I develop primarily using docker, and because of that have few libraries installed directly on the machine. Is there any way to have autocomplete look at a remote install? Perhaps by doing something along of the lines of `docker-compose run web cat /python/lib`?

I got remote debug working, which is one of the best features 👍

**Comment by DonJayamanne** [comment]
Unfortunately this isn't supported at this stage. However it is something that is being considered to be worked on.
I'll be closing this is as it is a duplicate of #123

**Comment by DonJayamanne** [comment]
Suggestions for #183

**Comment by dsimandl** [comment]
Another 👍 for autocomplete to look at a remote install.  Out of curiosity @ograycode how did you get remote debug working?  I'm also primarily using docker (locally) for my dev work

**Comment by DonJayamanne** [comment]
@dsimandl you can find instructions on setting up remote debugging [here](https://github.com/DonJayamanne/pythonVSCode/wiki/Debugging:-Remote-Debuging)
