### ISSUE TITLE
Extend docstring display to include return annotation

### ISSUE THREAD

**Issue by flyinactor91** [DonJayamanne/pythonVSCode#180]
Python3 supports function annotations like:
def addOne(num: int) -> int:

Currently, the docstring display on function hover would only display:
addOne(num: int)

It can also be more complicated as shown in PEP 3107.
https://www.python.org/dev/peps/pep-3107/

**Comment by DonJayamanne** [comment]
Closing as this is an issue specific to the Jedi library used.
I would have raised on issue on that github repo, however this is a known issue:

[Supported Python Features](https://github.com/davidhalter/jedi/blob/c0242cf5be21e801eb00b7750b49c97f2f3c783c/docs/docs/features.rst#id6)
>function annotations (py3k feature, are ignored right now, but being parsed. I don't know what to do with them.)
