### ISSUE TITLE
Linting with pylint failed. Please install the linter or turn it off.

### ISSUE THREAD

**Issue by bialix** [DonJayamanne/pythonVSCode#185]
I started to get this issue yesterday when your Python extension asked me to update it. It's quite irritating. Especially because I **did not** enable any linters.

I have pyflake on my machine. Is it somehow related?

OS Windows 7. I have several pythons installed here.

**Comment by mwadden** [comment]
Same here... just started yesterday after updating. I also tried updating pylint to see if it would help but it didn't.

Running OS X 10.10.5 w/ python 2.7.10 and VS Code 1.2.1.

**Comment by lzantal** [comment]
Yep, I can confirm this as well. After updating the extension I am getting this error.
Here is the output in the terminal:
Error: spawn pylint ENOENT

**Comment by DonJayamanne** [comment]
I am very sorry about this. Please could you @bialix, @mwadden and @lzantal send me a copy of your settings.json files. Thanks

**Comment by DonJayamanne** [comment]
By the way, @lzantal what Lindsey is it complaining about, and sis the linter work in the past, as in did you receive linter messages (messages  about  syntax errors in code) before the update?

**Comment by lzantal** [comment]
@DonJayamanne yes I did. It worked fine this morning, then updated it and not it complains every time I save the file.

**Comment by lzantal** [comment]
Here is my settings.json file. It's a super simple django project. Tested it with plain python and same error.
```
// Place your settings in this file to overwrite default and user settings.
{
    "files.exclude": {
        "**/.hg": true,
        "**/.git": true,
        "**/.svn": true,
        "**/.DS_Store": true,
        "**/*.pyc": true
    },
    // project paths
    "python.pythonPath": "/Users/laszlo/pyvenvs/defaultproj/bin/python",
    "python.autoComplete.extraPaths": ["/Users/laszlo/dev/defaultproj/djproj/djproj/apps","/Users/laszlo/pyvenvs/defaultproj/lib/python2.7","/Users/laszlo/pyvenvs/defaultproj/lib/python2.7/site-packages"]
}
```

**Comment by lzantal** [comment]
Oh no, the Unverified Breakpoint issue is back now. I was debugging before the update just fine so it must be related somehow.

**Comment by DonJayamanne** [comment]
Finally, please let me know what OS and python versions your are using (,if any virtual envs)
As a temporary solution please turn off linting in settings.json "python.linting..."

Once again, I am very sorry about this issue.

**Comment by lzantal** [comment]
OSX 10.11.5
VSCode 1.2.1
Python 2.7, default mac install

Oh please, thank you for this great tool 👍

**Comment by DonJayamanne** [comment]
Hmmm, no changes to breakpoints!

**Comment by DonJayamanne** [comment]
Hi @lzantal, please could you confirm you have pylint installed. If not Please could you install it against your virtual env , and the restart vs code and test.

**Comment by DonJayamanne** [comment]
@mwadden , please could you upload the contents of your settings.json.
And could you test running pylint from the terminal window and let me know whether it works.
Just open a terminal window and run the following command:
```
pytlint --version
```

**Comment by DonJayamanne** [comment]
@bialix , does installing Pylint fix the issue? Please could you try that. Thanks

**Comment by bialix** [comment]
@DonJayamanne I don't really need linter, sorry. I've switched it off, but anyway I don't think your plugin with default settings should wine about linter.

Here is my settings (after I've switched off):

```
{
    // Controls whether the editor should render whitespace characters
    "editor.renderWhitespace": true,

    // Columns at which to show vertical rulers
    "editor.rulers": [80, 100, 120],

    // The default end of line character.
    "files.eol": "\n",

    // Configure glob patterns for excluding files and folders.
    "files.exclude": {
        "**/fte.dsk": true,
        "**/__pycache__": true
    },
    
    "python.pythonPath": "D:/python/3.3-64/python.exe",

        // Whether to lint Python files.
    "python.linting.enabled": false
}
```

**Comment by mwadden** [comment]
Here's my config: 
```
{
    "editor.tabSize": 2,
    "files.watcherExclude": {
		"**/.git/objects/**": true,
		"**/node_modules/**": true,
        "**/tmp/**": true,
        "**/bower_components/**": true
	},
    "search.exclude": {
		"**/node_modules": true,
        "**/bower_components/**": true,
        "**/tmp": true
	},
    "explorer.workingFiles.dynamicHeight": false,
    "python.pythonPath": "/usr/bin/python",

    "html.format.indentHandlebars": true
}
```

Pylint output: 
```
$ pylint --version
No config file found, using default configuration
pylint 1.5.6, 
astroid 1.4.6
Python 2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
```

I also removed and reinstalled pylint again and so far I haven't received any error messages (it's only been about 20 mins though). I'll let you know if it changes.

**Comment by DonJayamanne** [comment]
Hi everyone, this has been fixed in the latest version. Please let me know how this goes.

**Comment by flyinactor91** [comment]
Now receiving this output error message rather than the pylint notification previously mentioned

> Linting with pylint failed.
> You could either install the 'pylint' linter or turn it off in setings.json via "python.linting.pylintEnabled = false".
> Error: spawn pylint ENOENT

I'm sure that this has to do with pylint not being installed. Does this get installed along with the addon? If so, updating from an older version does not handle the dependency.

OSX 10.11.5
Python 3.5.1

**Comment by DonJayamanne** [comment]
Hi @flyinactor91, you will need to install pylint.

**Comment by DonJayamanne** [comment]
Closing this issue as the new update doesn't display the messages. The next version will not even display the output window.

**Comment by trinitybest** [comment]
Hi all,
open the workspace settings file and add this line
"python.linting.pylintEnabled": false
reference: http://stackoverflow.com/questions/40626429/windows-10-visual-studio-code-removing-pylint
Cheers,
Dean
