### ISSUE TITLE
Remote Interpreter

### ISSUE THREAD

**Issue by nffdiogosilva** [DonJayamanne/pythonVSCode#186]
Hi there,

I know this feature request is already in the roadmap, but I would like to emphasise its importance.

Nowadays there are many tools (Docker, Vagrant), to allow us to have a distributed dev environment with ease. I believe this is very important in a world where agile development is more and more a standard.

Please, give max priority to this feature =)

Regards,
Nuno.

**Comment by DonJayamanne** [comment]
Hi @nffdiogosilva , thanks for the suggestion. 
I believe this is something that we'd be working on soon, if not next.
As this is a duplicate item (#123, #183), i will be closing it for now.
Also, I have sent you an email with a few questions.

Once again, thanks and keep such suggestions coming.
