### ISSUE TITLE
use wildcard for intellisense path

### ISSUE THREAD

**Issue by symbioticKid** [DonJayamanne/pythonVSCode#189]
Currently, every single directory and sub-directory path needs to be specified in settings.json for it to be picked up by intellisense. This gets particularly cumbersome when building on top of existing libraries.

Would be great to just specify a top level directory and all the subsequent sub-directories be picked up by intellisense.

```
"python.autoComplete.extraPaths": [
        "C:/vscode/dir-A",
        "C:/vscode/dir-A/dir-B",
        "C:/vscode/dir-A/dir-B/dir-C",
        "C:/vscode/dir-A/dir-B/dir-D",
        "C:/vscode/dir-E",
        "C:/vscode/dir-E/dir-F",
    ]
```

Would be great to just do the below - and have all the remaining sub-directories picked up by intellisense.

```
"python.autoComplete.extraPaths": [
        "C:/vscode/*"
    ]
```

**Comment by DonJayamanne** [comment]
I like the idea, however.
Are these directories under the workspace (project folder)?
Also what kind of libraries (Packages) do you have in such a folder structure?

**Comment by symbioticKid** [comment]
_Are these directories under the workspace (project folder)?_
Currently yes, but that's since i'm moving files to a common directory to avoid typing out a new path in settings.json.

_Also what kind of libraries (Packages) do you have in such a folder structure?_
A bunch of in house python libraries.

**Comment by martinfiers** [comment]
I like the question.

I was thinking even one step further: why do we even have to edit python.autoComplete.extraPaths; at all? Could it for example be based on whatever modules are recognized by the interpreter (packages from site-package + PYTHONPATH)?

For example; if you are inside a working environment with a certain Python executable and some development packages inside your PYTHONPATH: wouldn't it be nice if intellisense picks these up automatically? If you consider this as a separate feature I can make a new issue out of this or add it to the feature requests.

**Comment by DonJayamanne** [comment]
Closing as there haven't been too many up-votes for this feature.
