### ISSUE TITLE
Performance improvement of linters

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#190]
Display results of the linters as they arrive rather than waiting for all linters to complete.
When working on large files, pylint could be a little slow.

**Comment by NguyenDanPhuong** [comment]
I'm new to VS Code, TypeScript and Node.js. I've investigated this issue and come up with child_process.spawn() (instead of execFile) so stdout returns as they arrive. But current code using Promises and resolve only run first time. I tried to use callback (I think it bad) but wonder if there's any way to do better?

**Comment by DonJayamanne** [comment]
First, thanks for looking to contribute to this repo.
The requirement here is to ensure the response for each linter is display separately without having to wait for all the linters to return.
If you look at the line [Promise.all](https://github.com/DonJayamanne/pythonVSCode/blob/master/src/client/providers/lintProvider.ts#L117), here we're waiting for all linters to finish and then display the results. It is possible Flake8 runs in a fraction of a second and Pylint takes around 2-3 seconds to complete. 

So really what needs to be done is, this code needs to be re-factored and Promise.All needs to be removed.

**Comment by jabooth** [comment]
@DonJayamanne @NguyenDanPhuong might see if I can fix this, if it still needs doing?

**Comment by DonJayamanne** [comment]
@jabooth , be my guest. If you want you can also have a look at #261

**Comment by jabooth** [comment]
@DonJayamanne awesome. I'll plug away at this, #261 and #257 (improvements) if I get chance next few days.

**Comment by DonJayamanne** [comment]
Fix will be in the next build, thank @jabooth
