### ISSUE TITLE
Add syntax highlight for "and" "or" "not" "is" "in"

### ISSUE THREAD

**Issue by CHEN-Zhihan** [DonJayamanne/pythonVSCode#191]
#183

**Comment by DonJayamanne** [comment]
Good let's keep this open

**Comment by DonJayamanne** [comment]
@CHEN-Zhihan , currently syntax highlighting isn't supported by this extension.
Syntax highlighting is part of VS Code.
You could however install an extension named [Machig Python](https://marketplace.visualstudio.com/items?itemName=magicstack.MagicPython) which provides better syntax highlighting for Python code.

**Comment by neilsustc** [comment]
> You could however install an extension named Magic Python which provides better syntax highlighting for Python code.

I didn't know about this until today. 😂 (I didn't know it is a syntax highlighter according to its name 'Magic Python')
It could be better to add it to the README.md.

**Comment by neilsustc** [comment]
Eh, it seems that the keyword `in` is still not highlighted with MagicPython installed.
I noticed that there is a post from vscode team [Optimizations in Syntax Highlighting](http://code.visualstudio.com/blogs/2017/02/08/syntax-highlighting-optimizations) (TL;DR TextMate themes will look **more** like their authors intended in VS Code 1.9).
So is it a vscode issue? or a MagicPython issue?

**Comment by DonJayamanne** [comment]
Syntax highlighting isn't an issue of this extension. You should raise such questions in either vscode or magic python repo. If you have magic python installed then it's an issue with magic python.

**Comment by neilsustc** [comment]
👌

**Comment by gandhis1** [comment]
This is similar to #556 and #290. The conclusion essentially was that with the default VS Code theme you are generally out of luck. This is one of the reasons I ended up making the switch to Monokai, I recommend it.
