### ISSUE TITLE
Add support for folding python docstrings

### ISSUE THREAD

**Issue by ScenK** [DonJayamanne/pythonVSCode#192]
Could it possible to add this feature for which will be great helpful.

Description:
1. Ability to fold specific docstrings block.
2. Configurable auto folding all docstrings blocks on load.

i.e.

![687474703a2f2f662e636c2e6c792f6974656d732f334f3172336833673134316a30713154313430722f53637265656e25323053686f74253230323031332d30342d3136253230617425323031312e30322e3133253230414d2e706e67](https://cloud.githubusercontent.com/assets/2987542/16471401/0abd2274-3e8f-11e6-932a-2362978d1f18.png)

**Comment by ScenK** [comment]
Suggestions for #183

**Comment by NguyenDanPhuong** [comment]
VSCode does not allow the extension/language to participate in determining what folds. See Microsoft/vscode#3422
