### ISSUE TITLE
Intellisense for Pandas in Visual studio code with python extension using anaconda distribution

### ISSUE THREAD

**Issue by amotupal** [DonJayamanne/pythonVSCode#193]
Intenllisense is not working with pandas in anaconda distribution. Can you look at this issue once?

Thanks.

**Comment by DonJayamanne** [comment]
@amotupal have you configured the path to the python (anaconda version) park in your settings file?

**Comment by DonJayamanne** [comment]
@amotupal , any progress on this.

**Comment by fquivira** [comment]
@DonJayamanne, I've been able to partially replicate this. Intellisense is working with pandas for me, but there is no autocomplete or help tooltip for pandas variables. For example, if I have the following code:

`df = pandas.read_csv(args.fileName, usecols=['timestamp'])`
`periods = df.diff()`
`periods.hist()`

then hovering over `read_csv` will show me the help and doing `pandas.` will show me the autocomplete window. However, hovering over the the `diff` or the `hist` functions will not show me the help tooltip. It will get stuck in `loading ...`. Is that expected behavior? I can even replicate this across other packages like matplotlib.

I'm using Anaconda3 and VS Code 1.3.0

**Comment by ralexx** [comment]
Similar problem with Anaconda 1.4/VS Code 1.3 but now resolved. In my case I had failed to follow @DonJayamanne 's documentation for [Intellisense in virtualenvs](https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version#virtual-environments).

In lieu of a PR to the wiki would you consider adding the following snippet to https://github.com/DonJayamanne/pythonVSCode/wiki/Troubleshooting-Intellisense-Autocompletion ?

----

**Cause: VS Code was not launched from the active virtual environment**   
The path to the custom modules is set when a virtual environment is activated.  
Solution: [Launch VS Code from a Terminal/Command window with the correct virtual environment activated](https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version#option-2-activate-the-virtual-environment-from-your-terminalcommand-window-and-then-launch-vs-code)     

```
(venv) ter@minal:~$ code .
```

**Comment by fquivira** [comment]
@ralexx, I followed the documentation and I'm not using virtual environments (only the default root Anaconda). I tried activating the root environment, launching vscode, but the problem persists :(

**Comment by DonJayamanne** [comment]
@fquivira , have you configured the path to the python executable in settings.json?
Please could you upload the contents of settings.json?

**Comment by DonJayamanne** [comment]
@ralexx , the Wiki has been updated. Thanks for the suggestion.

**Comment by fquivira** [comment]
@DonJayamanne, here is my settings.json. As mentioned before, I don't have virtual environments since I'm using the anaconda's root.
```
// Place your settings in this file to overwrite the default settings
{
    "matlab.mlintpath": "C:\\Program Files\\MATLAB\\R2010b\\bin\\win64\\mlint.exe",
    "files.associations": {"*.m": "matlab"},
    "cmake.cmakePath": "C:\\Program Files (x86)\\CMake\\bin\\cmake",
    "python.pythonPath": "C:\\Anaconda3\\python.exe",
    "files.insertFinalNewline": true,
    "editor.fontSize": 14,
    "editor.roundedSelection": false,
    "explorer.openEditors.visible": 0,
    "trailing-spaces.trimOnSave": true,
    "files.exclude": {
        "**/.git": true,
        "**/.DS_Store": true,
        ".vscode": true,
        "**/__pycache__": true,
        "**/**/*.pyc": true
    }
}
```

**Comment by ralexx** [comment]
@fquivira , sorry to hijack your issue. I can also replicate this.

![msg](https://cloud.githubusercontent.com/assets/6756310/16886496/9a75e1ac-4a89-11e6-8423-cceca3a448d9.png)

@DonJayamanne , is this related to the`jedi` version used in Anaconda? E.G. My Anaconda is using `jedi 0.9.0`.

**Comment by fquivira** [comment]
@ralexx, no problem as I hijacked this issue myself. 

If it helps, I also have VS 2015 with PTVS installed and I run into a similar issue. Some variables don't show autocomplete at all:
![intellisense_problem](https://cloud.githubusercontent.com/assets/1800870/16886888/d35ccb8c-4aa4-11e6-8f0b-78de16080be4.png)
Moreover, some modules like numpy don't show everything. For example, the `zeros` function doesn't show up:
![intellisense_problem_2](https://cloud.githubusercontent.com/assets/1800870/16886911/ed28cf7a-4aa4-11e6-9f89-4bc3090b3e98.png)
I don't know if the intellisense module in VS Code and VS 2015 are related at all, but I'd figure I'd check.

**Comment by DonJayamanne** [comment]
I will look into this asap.

**Comment by DonJayamanne** [comment]
Hi, the problem is with the Jedi library. I will raise this issue in that repo.

**Comment by amotupal** [comment]
Sorry for such a late reply. Yes path in my settings is correct.
when I type a dataframe, I don't get intellisense for dataseries in the dataframe.

**Comment by feliperyan** [comment]
Using Python 3.6 on Windows 10. Path in settings, pylint working, can't get any intellisense at all - just shows loading...

**Comment by grantmcdade** [comment]
@feliperyan I have the same problem. Trying to use Django and only have what is needed for that. @DonJayamanne please let me know what I can try.

**Comment by GiuseppeLaurenza** [comment]
There are any news? I have the same problem on macOS Sierra and vsc

**Comment by grantmcdade** [comment]
@GiuseppeLaurenza no I have not heard anything.

**Comment by ArunNairID** [comment]
any updates ?

**Comment by akshayvenkatesha** [comment]
@DonJayamanne  do you know which version of jedi has fix ? 
i have installed jedi-0.10.2 and still facing the same issue

**Comment by jsabena** [comment]
I had the same issue with opencv/python/vscode. Setting "python.linting.pylintEnabled": to false in settings.json solves the problem with autocompletion. Of course, you lose pylint. Please answer if this works in your environment. (Mine is Linux/Python 3.5/Anaconda/VsCode1.12/Jedi 0.10.2)

**Comment by FireNero** [comment]
@jsabena Thanks! Your solution helped me on Windows10x64/Python3.6/VsCode1.15.1

**Comment by vchatterji** [comment]
Adding the following as a workspace settings can help with Pylint errors. You can white-list the modules for which you see pylint not recognizing the module's functions. 
```
"python.linting.pylintArgs": [
        "--extension-pkg-whitelist=numpy,..."
]
```

**Comment by speedmancs** [comment]
any updates ? I'm using VSO 1.21.1/python3.5.2/Python extension 2018.3.1 with a venv environment and still seeing this issue.

As for the jedi library, I tried to pip install it with the version 0.11.1 and seems not working as well.

**Comment by speedmancs** [comment]
I read through the [related issue ](https://github.com/davidhalter/jedi/issues/372)of jedi from where I found much discussion about how hard it is to do the static analysis right for numpy/matplotlib/pandas. It's as easy as ipython as it's always after the statement is executed in the REPL.
