### ISSUE TITLE
Python input problem

### ISSUE THREAD

**Issue by joaomoreno** [DonJayamanne/pythonVSCode#196]
_From @wnsrl56 on July 5, 2016 17:58_

- VSCode Version: 1.2.1
- OS Version: window 10 64bit 

Steps to Reproduce: 

when i used python extension.
1. using input function  . there is no response in program
2. this is my code

```python
print('input your number')

limit = int(input())

while limit < input: 
        limit = limit +1
        print(limit)
```

_Copied from original issue: Microsoft/vscode#8765_

**Comment by DonJayamanne** [comment]
@wnsrl56 Please confirm you have used the "Python Console App" debug configuration.
Using the standard "Python" debug configuration will not work as the debug output window in VS Code doesn't accept input. The "Python Console App" configuration launches an external terminal window that supports accepting input.

**Comment by DonJayamanne** [comment]
@wnsrl56  have you managed to resolve this issue?

**Comment by wnsrl56** [comment]
yes, thank you for your comment.

2016-07-14 10:35 GMT+09:00 Don Jayamanne <notifications@github.com>:

**Comment by DonJayamanne** [comment]
Documentation can be found [here on the Wiki](https://github.com/DonJayamanne/pythonVSCode/wiki/Capture-User-Input-via-input-raw_input)

**Comment by fredyang** [comment]
it did work once a while, but most of the time it doesn't work. This is the error I saw.

    x = input('Please enter anything')
    print(x)


  File "\<string\>", line 1, in\ <module\>
  NameError: name 'jhjhj' is not defined

**Comment by brettcannon** [comment]
@fredyang I'm assuming you're using Python 2, which means that is expected Python semantics; you probably wanted to use `raw_input()` instead of `input()`.

**Comment by fredyang** [comment]
@brettcannon You are right, just set

   "python.pythonPath": "python3"

in user settings file, it works now.
