### ISSUE TITLE
The package seems to be incomplete on the Visual Studio Market Place

### ISSUE THREAD

**Issue by frecio231** [DonJayamanne/pythonVSCode#2]
When you install from VSCode it says that it is missing package.json
![bug py](https://cloud.githubusercontent.com/assets/11915036/12528643/63ed6ef8-c162-11e5-9fb2-98731f49b8d5.png)

**Comment by DonJayamanne** [comment]
Hi, I just tried installing it on both Windows 8 and Mac, and was able to do so without any issues. I.e. I can't replicate it.  Please could you test it once again and let me know. I will test this on a Windows 10 pc later tomorrow out the day after. Thanks

**Comment by frecio231** [comment]
the addon seems to be working now, I don't know what happen because I desinstalled and reinstalled 3 times before publish this.

**Comment by YouGovGit** [comment]
I am getting the same error it is saying that it can not find the __init__py
The instructions are a bit sparse, Apart from installing the extension and pressing F5 should I be doing something else? Also, I used Anaconda to install python (it is on the PATH though) would this make a difference and if so, what would I need to do to resolve it (Windows 8.1 install)
