### ISSUE TITLE
Read from stdin

### ISSUE THREAD

**Issue by NoneGiven** [DonJayamanne/pythonVSCode#20]
Is it possible to use VS Code's debug console to send to stdin when the program is requesting it with `input()` or a similar function? That's definitely a major weakness of VS Code for debugging and it would be great if extensions could solve it.

**Comment by DonJayamanne** [comment]
Unfortunately no. If however you are using Windows, then you can debug the program as a console app, by initializing the setting "externalConsole" too true. This will easily in the display of the console Window allowing you to input data into the program. Support for launching the terminal widow in Mac is on the way
