### ISSUE TITLE
Pylint convention error messages are not displayed anymore

### ISSUE THREAD

**Issue by bbenoist** [DonJayamanne/pythonVSCode#200]
Hi,

After updating the extension and reloading vscode, pylint convention error messages are not displayed anymore in the editor (was previously green).

They appear in the Python output panel but no underline 😢

**Comment by bbenoist** [comment]
Little precision, errors are working. Only convention messages are not displayed.

**Comment by DonJayamanne** [comment]
Please could you send the output errors.

**Comment by bbenoist** [comment]
Here is a screenshot with some use-cases:

![image](https://cloud.githubusercontent.com/assets/2091902/16687390/a285a312-4518-11e6-856a-498a325c667b.png)

And here is the corresponding code in-case you want to use it for your tests:

```python
def function_with_missing_docstring():
  print 'No warning above :-/'


def function_with_line_too_long():
  line_too_long = 'This line is way toooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo long'

line_too_long = 'This line is way toooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo long and has an invalid constant name.'
```

Also, it must be noticed that the vscode extensions output panel is empty.

**Comment by DonJayamanne** [comment]
@bbenoist , convention messages won't be displayed in green.
Convention messages are displayed as hints (and don't display any green or red lines).
This is how it has always behaved.

If you want the convention messages to be displayed with the green squiggly lines, then you could configure the extension as follows:

1. Open your settings file (user settings if you want this change globally applied)   
2. Add the following setting and re-test

```json
"python.linting.pylintCategorySeverity.convention": "Information"
```

Once done, you'll get the green squiggly lines for convention messages.

**Comment by bbenoist** [comment]
OK, thanks for the information. I can't explain why this level of information was displayed before...

**Comment by DonJayamanne** [comment]
It is possible you saw those messages along with other information/warming messages
