### ISSUE TITLE
[PEP-484] Type hint

### ISSUE THREAD

**Issue by Cologler** [DonJayamanne/pythonVSCode#201]
enable auto-completion for **type hint** [PEP-484](https://www.python.org/dev/peps/pep-0484/).

**Comment by Cologler** [comment]
same as **Function Annotations** [PEP 3107](https://www.python.org/dev/peps/pep-3107/)

**Comment by DonJayamanne** [comment]
Bug in jedi library [#742](https://github.com/davidhalter/jedi/issues/742)

**Comment by DonJayamanne** [comment]
Closing as this is an upstream issue (in Jedi)

**Comment by Cologler** [comment]
I already use jedi dev branch. Thanks. :+1:

**Comment by DonJayamanne** [comment]
@Cologler , have you had any issues using the dev branch of Jedi?

**Comment by Cologler** [comment]
@DonJayamanne No.

**Comment by jkryanchou** [comment]
Awesome Job
