### ISSUE TITLE
debug console can't show if print string

### ISSUE THREAD

**Issue by daaoling** [DonJayamanne/pythonVSCode#202]
debug console can't show if print string ? why ?is there something wrong

**Comment by DonJayamanne** [comment]
@daaoling , I've tested this in python 2.7 and 3.5 and it works as expected.
Please could you upload the sample code.
Also, does printing other characters work for you?

**Comment by DonJayamanne** [comment]
@daaoling , any progress?

**Comment by DonJayamanne** [comment]
Please re-open if the issue persists
