### ISSUE TITLE
print not work when debuging

### ISSUE THREAD

**Issue by abc100m** [DonJayamanne/pythonVSCode#204]
while debuging, in DEBUG CONSOLE window
=========================================
a = 'aaaaa' 
None

b = u'长城'
None

a
'aaaaa'

b
u'\u957f\u57ce'

print a
None

print b
None

==========================
print  a
print b

Those two commands shows nothing which  caused hard to see unicode variable.   
While in VSTS,  I can use print to see unicode variable

**Comment by abc100m** [comment]
windows 7 Winpython 2.7.10 64bit

VSCode version 1.3
pythonVSCode : the lasted version

**Comment by DonJayamanne** [comment]
Please could you upload the code.

**Comment by DonJayamanne** [comment]
@abc100m , I've tested this on a Mac and it works as expected. I'll test this on Windows 10 (as I don't have a Windows 7 or 8).

**Comment by abc100m** [comment]
I see.  pythonVSCode have 3 debug mode:
Python
Python Console App
Django

when use "Python" debug mode,  print works well. 

when use "Python Console App",  print will be showed in the _python  console winow_, so DEBUG CONSOLE will show nothing.   

**Note:  when use "Python Console App" mode,  _python console window_ can show  ASCII characters like 'goooood',  but unicode  like u'长城' are not support yet (shows garbiage characters)**, this maybe is a new issue

**Comment by DonJayamanne** [comment]
@abc100m , please could you try the following code (ensure to place the encoding at the top of the file [PEP 263](https://www.python.org/dev/peps/pep-0263/)

```python
 # -*- coding: utf-8 -*-

a = 'aaaaa' 
print(a)
b = u'长城'
print(b)
```

Here's the output (as expected), in both debug modes "Python" and "Python Console App":
```
aaaaa
长城
```

**Comment by abc100m** [comment]
![image](https://cloud.githubusercontent.com/assets/4769764/16803225/cfc27094-4937-11e6-920e-263a93490685.png)

Please see the picture.  Maybe there is something wrong with Locale Setting? But my VSTS works well, so I guess this is the issue of pythonVscode

**Comment by abc100m** [comment]
![image](https://cloud.githubusercontent.com/assets/4769764/16803354/8bf1e59c-4938-11e6-9015-5e91ad4e64c3.png)

this picture shows pythonVSCode works in "Python" mode

**Comment by DonJayamanne** [comment]
Can you try running the python script file from the command prompt without using VS Code.
Just go into your command window and type the following code:
```
python a.py
```

**Comment by abc100m** [comment]
![image](https://cloud.githubusercontent.com/assets/4769764/16825679/5005a7c8-49a9-11e6-80b2-143c4c762f49.png)

python is ok

**Comment by DonJayamanne** [comment]
thanks

**Comment by DonJayamanne** [comment]
@abc100m , please could you try this issue once again (in the latest version) but using the new 'integrated terminal' debugging option.
Please delete your ```.vscode\launch.json``` file and create a new one.

**Comment by abc100m** [comment]
@DonJayamanne  thanks for the new version

 the new 'integrated terminal' debugging option not work yet, but this issue is been clear. 

![image](https://cloud.githubusercontent.com/assets/4769764/18387428/33d15554-76cf-11e6-84eb-92fb1766837d.png)

 The environment variable **PYTHONIOENCODING** default set to **utf-8** but my  WINDOWS 7 except it to **gbk**

so, if there is a way to changed **PYTHONIOENCODING** to **gbk**,  or even better if pythonVSCode can detect Windows'  default charset

**Comment by abc100m** [comment]
great work! I see **raw_input** works now in "integrated terminal"

**Comment by abc100m** [comment]
I see _pythonVSCode_ set  environment viable PYTHONIOENCODING to utf-8 if we don't have the PYTHONIOENCODING setting.

After set a environment virable **PYTHONIOENCODING**  to **gbk**,  this issue was fixed

hope this solution will help someone

**Comment by DonJayamanne** [comment]
@abc100m Please could you upload you're changes to the launch.json (that would deliberately helps others).

Thanks

**Comment by abc100m** [comment]
I have not changed anything in launch.json, but I just defined a environment variable which named **PYTHONIOENCODING**, and it's value is "**gbk**"

Here is a tutorial about how to setup environment variable  on Windows http://www.computerhope.com/issues/ch000549.htm
https://kb.wisc.edu/cae/page.php?id=24500

**Comment by abc100m** [comment]
it works if I change launch.json like this:

```json
        {
            "name": "Integrated Terminal/Console",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "console": "integratedTerminal",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]

//add  begin
            ,"env": {
                "PYTHONIOENCODING": "gbk"
            }
//add end

        }
```

**Comment by DonJayamanne** [comment]
@abc100m, thanks a lot
