### ISSUE TITLE
Incomplete formatting

### ISSUE THREAD

**Issue by isvoboda** [DonJayamanne/pythonVSCode#205]
I use VS Code (1.3.0) with PythonVSCode extension (0.3.16) on Xubuntu 14.04. While my workspace configuration looks like this:
```
{
    "python.linting.enabled": true,
    "python.linting.pylintEnabled": true,
    "python.formatting.provider": "autopep8",
    "python.formatting.formatOnSave": true
}
```
I have to make a small change several times to a python source document  and repeatedly save it to force the formatting to be completely done. Most often this can be seen when formatting C0303: Trailing whitespace (pylint) - when I delete some of the trailing whitespace and save the document some of the remaining trailing whitespace are removed but not all at once. The same problem emerged with formatting the brackets i.e. add/delete whitespace if necessary.

It works as expected if I use the autopep8 from bash.

**Comment by DonJayamanne** [comment]
Please could you upload a sample code for me to have a look?
Also what version of Python are you using?

**Comment by isvoboda** [comment]
- The Python I am using is 2.7.6
- autopep8 is 0.9.1

The formatting-example.zip doc is attached, it has several pylint warnings and messages. There are some trailing whitespaces on line 82. If I remove one of them and save the doc it makes some formatting, but the remaining trailing whitespaces are not deleted and also the brackets on line 78 are not touched.

[formatting-example.zip](https://github.com/DonJayamanne/pythonVSCode/files/357234/formatting-example.zip)

**Comment by DonJayamanne** [comment]
Thanks, I am able to replicate the issue at my end. I'll look into this.

**Comment by isvoboda** [comment]
My thanks to you for your great PythonVSCode extension!

**Comment by DonJayamanne** [comment]
I take that back, I'm unable to replicate the issue. Though I have managed to replicate something similar with yapf.

**Comment by isvoboda** [comment]
Well, with the settings mentioned above, when I remove the whitespace at the line 84 and save the doc I get this in the Output view (Python):

```
##########Linting Output - pylint##########************* Module vis_layer
63,0,warning,W0311:Bad indentation. Found 12 spaces, expected 8
64,0,warning,W0311:Bad indentation. Found 16 spaces, expected 12
77,0,convention,C0303:Trailing whitespace
80,0,convention,C0326:Exactly one space required after comma
            img = value.transpose(1,2, 0) / self.norm # [y x z]
                                   ^
84,0,convention,C0303:Trailing whitespace
86,0,convention,C0303:Trailing whitespace
8,0,fatal,F0401:Unable to import 'caffe'
10,0,fatal,F0401:Unable to import 'cv2'
12,0,convention,C0103:Invalid constant name "module_logger"
15,0,warning,W0232:Class has no __init__ method
37,4,convention,C0111:Missing method docstring
37,28,warning,W0613:Unused argument 'top'
37,20,warning,W0613:Unused argument 'bottom'
62,4,convention,C0111:Missing method docstring
62,22,warning,W0613:Unused argument 'bottom'
66,4,convention,C0111:Missing method docstring
74,4,convention,C0111:Missing method docstring
74,28,warning,W0613:Unused argument 'propagate_down'
78,4,convention,C0111:Missing method docstring
45,12,warning,W0201:Attribute 'scale' defined outside __init__
38,8,warning,W0201:Attribute 'dict_param' defined outside __init__
60,12,warning,W0201:Attribute 'name' defined outside __init__
55,12,warning,W0201:Attribute 'norm' defined outside __init__
50,12,warning,W0201:Attribute 'mean' defined outside __init__
7,0,warning,W0611:Unused import np

##########Linting Output - pylint##########************* Module vis_layer
63,0,warning,W0311:Bad indentation. Found 12 spaces, expected 8
64,0,warning,W0311:Bad indentation. Found 16 spaces, expected 12
77,0,convention,C0303:Trailing whitespace
80,0,convention,C0326:Exactly one space required after comma
            img = value.transpose(1,2, 0) / self.norm # [y x z]
                                   ^
84,0,convention,C0303:Trailing whitespace
86,0,convention,C0303:Trailing whitespace
8,0,fatal,F0401:Unable to import 'caffe'
10,0,fatal,F0401:Unable to import 'cv2'
12,0,convention,C0103:Invalid constant name "module_logger"
15,0,warning,W0232:Class has no __init__ method
37,4,convention,C0111:Missing method docstring
37,28,warning,W0613:Unused argument 'top'
37,20,warning,W0613:Unused argument 'bottom'
62,4,convention,C0111:Missing method docstring
62,22,warning,W0613:Unused argument 'bottom'
66,4,convention,C0111:Missing method docstring
74,4,convention,C0111:Missing method docstring
74,28,warning,W0613:Unused argument 'propagate_down'
78,4,convention,C0111:Missing method docstring
45,12,warning,W0201:Attribute 'scale' defined outside __init__
38,8,warning,W0201:Attribute 'dict_param' defined outside __init__
60,12,warning,W0201:Attribute 'name' defined outside __init__
55,12,warning,W0201:Attribute 'norm' defined outside __init__
50,12,warning,W0201:Attribute 'mean' defined outside __init__
7,0,warning,W0611:Unused import np
```

Unfortunately the formatting is done only partially, for example the C0326 at line 80 remains until next change and next save.

I also do not know why the output appears two times?

**Comment by DonJayamanne** [comment]
The message for the linting appears twice because of the two changes made. One is the change you made, the other is the change made by the auto-formatting. Now that you mentioned it, i think the two instances of the linters should probably be reduced to one instance.

**Comment by DonJayamanne** [comment]
@isvoboda, I have fixed the issue and the fix will be in the next release.
