### ISSUE TITLE
auto-completion didn't work on relative import 

### ISSUE THREAD

**Issue by Cologler** [DonJayamanne/pythonVSCode#207]
``` py
from . import ? # didn't work
from .YYY import ? # work
```

**Comment by DonJayamanne** [comment]
Please could you paste your code and explain what doesn't work?

**Comment by Cologler** [comment]
Auto-completion did not display `import` in list if only `.` after `from`:

![](https://i.imgur.com/4oJXtpX.png)

And: Is possible to display all public class & function when type a writespace after `import`?

**Comment by DonJayamanne** [comment]
@Cologler , after typing the "import" keyword you will get auto completion.
<img width="424" alt="screen shot 2016-07-18 at 16 19 11" src="https://cloud.githubusercontent.com/assets/1948812/16907072/6edea2fa-4d03-11e6-91f5-0e8bead7cd0f.png">
