### ISSUE TITLE
Pyqt-program condn't display icon in toolbar in VSCode

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#209]
Raised by @drongh _Original issue Microsoft/vscode/issues/9125_
>- VSCode Version: 1.3
>- OS Version: win10

>I use vscode to running pyqt program, but there are no icons on the toolbar. Pyqt program is OK in pycharm. If any help, I would be appreciated.

>Thanks for you reply.
>The extension name is python wrote by Don Jayamanne.
>The pyqt-program project has a .py file and a icon directory. In the icon-directory, there are many icons which are used in toolbar. When running the pyqt-program, there are no icons in toolbar, but the buttons can be clicked.

**Comment by DonJayamanne** [comment]
@drongh, I have tested this and it works as expected.
Can you confirm your icons get displayed when you run the program from the terminal window?

```python
import sys
from PyQt4 import QtGui


class Example(QtGui.QMainWindow):
    
    def __init__(self):
        super(Example, self).__init__()
        
        self.initUI()
        
        
    def initUI(self):               
        
        exitAction = QtGui.QAction(QtGui.QIcon('images/red.png'), 'Exit', self)
        exitAction.setShortcut('Ctrl+Q')
        exitAction.triggered.connect(QtGui.qApp.quit)
        
        self.toolbar = self.addToolBar('Exit')
        self.toolbar.addAction(exitAction)
        
        self.setGeometry(300, 300, 300, 200)
        self.setWindowTitle('Toolbar')    
        self.show()
        
        
def main():
    
    app = QtGui.QApplication(sys.argv)
    ex = Example()
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()
```

**Comment by drongh** [comment]
@DonJayamanne, it can be displayed correctly in the terminal.
The pyqt-program is here. https://github.com/drongh/Writer-Tutorial

**Comment by DonJayamanne** [comment]
If you are using the tasks.json file, then you aren't using the extension.
Where is the file located with respect to the workspace root (project folder)?

I have tested the code using the above technique as well and it works.
I believe the problem is you haven't set the paths properly.

**Comment by drongh** [comment]
Thanks. 
You are right.
