### ISSUE TITLE
Can support alignment brackets?

### ISSUE THREAD

**Issue by yuan1238y** [DonJayamanne/pythonVSCode#210]
Current:
```
def test(arg):
    return arg.filter_by(host="xx",
    other="xx")
```
I hope:
```
def test(arg):
    return arg.filter_by(host="xx",
                         other="xx")
```

Sorry, english too bad!

**Comment by DonJayamanne** [comment]
@yuan1238y you will need to use a formatter for this, something like yapf or autopep8.
The extension supports these formatters ([check here](https://github.com/DonJayamanne/pythonVSCode/wiki/Formatting)), and you'll need to configure the formatter (which ever you choose to use) using the corresponding configuration settings.
Details for yapf can be found [here](https://github.com/google/yapf)
Details for autopep8 can be found [here](https://github.com/hhatto/autopep8)

**Comment by yuan1238y** [comment]
Thanks!
