### ISSUE TITLE
pytest and py.test

### ISSUE THREAD

**Issue by mbergkvist** [DonJayamanne/pythonVSCode#211]
`pylint` installs a `pytest` script (through the [logilab-common](https://www.logilab.org/project/logilab-common) package), and `pytest` installs a `py.test` script. The default value for `"python.unitTest.pyTestPath"` is `pytest` which confused me and it took some time to find out why my test cases were not executed as expected...

Since `logilab.common.pytest` is deprecated, I assume default value for `"python.unitTest.pyTestPath"` should be `py.test`.

**Comment by DonJayamanne** [comment]
You're right, thanks.

**Comment by DonJayamanne** [comment]
Fix will available in the next build
