### ISSUE TITLE
Code highlight is wrong

### ISSUE THREAD

**Issue by drongh** [DonJayamanne/pythonVSCode#212]
- VSCode Version: 1.3.1
- OS Version: win10
- Extension：python

Steps to Reproduce:

1.  open VSCode
2.  input some python codes, then select the single `Qt` word, but the `Qt` of `PyQt4.QtCore`  is also highlighted.
```python
from PyQt4 import QtGui, QtCore
from PyQt4.QtCore import Qt
```
It could be a bug I think.

**Comment by DonJayamanne** [comment]
Unfortunately this extension doesn't support syntax highlighting. You might want too install the extension Magic Python for syntax highlighting.
