### ISSUE TITLE
Debugging Google app engine

### ISSUE THREAD

**Issue by cricque** [DonJayamanne/pythonVSCode#213]
- Debugging a flask application works fine
- When converted to a Google app engine application (with the python appengine sdk and python 2.7.12) debugging does not work
The application launches in debug mode, but by the time you get to the real code, debug points just stop working. While when i run outside of gae this works

Is there a workaround or some extra settings for required for the debugger to work for Google App Engine projects

**Comment by DonJayamanne** [comment]
@cricque , how are you launching the application from vs code?
What's the start up program?

**Comment by cricque** [comment]
"configurations": [
		{
			"name": "Python",
			"type": "python",
			"request": "launch",
			"stopOnEntry": true,
			"externalConsole":false,
			"python.pythonPath": "/home/cricque/.virtualenvs/py27/bin/python -b",
			"program": "/opt/google_appengine/dev_appserver.py",
			"debugOptions": [
				"WaitOnAbnormalExit",
				"WaitOnNormalExit",
				"RedirectOutput"
			],
            "args": ["--port=8181", "--host=0.0.0.0", "${workspaceRoot}/."]
		},


I always launch VS Code from after I activated my virtual environment

**Comment by DonJayamanne** [comment]
Hi, I haven't got a google app engine env setup, and don't know much about it. I'll look into this later.
In the mean time could you try the following setting (this might work):
```json
 "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "DjangoDebugging"
],
"args": [
                "--port=8181", "--host=0.0.0.0", "${workspaceRoot}/.",
                "--noreload"
            ],
```

If that doesn't work, then I guess the only temporary option would be to go with remote debugging, that will definitely work ([instructions can be found here](https://github.com/DonJayamanne/pythonVSCode/issues/65#issuecomment-209684285))

**Comment by cricque** [comment]
That did not work with adding DjangoDebugging

The debugger actually launches and goes to the first line in dev_appserver.py
But all breakpoints in all my files instantly get greyed  once the process starts

Anyway it is not such a big issue, tought i just mention it. If it eventually gets fixed it would be nice

A big thanks already for the great work

**Comment by zjaml** [comment]
Hi, I'm experiencing a similar issue. 
Just couldn't get debugging working for GAE.
My config looks like below:

```
{
      "name": "gae",
      "type": "python",
      "request": "launch",
      "stopOnEntry": false,
      "args": ["--port=7000", "--host=127.0.0.1",
        "--admin_port=8001", "${workspaceRoot}/src/gae"],
      "pythonPath": "C:/Python27/python.exe",
      "program": "C:/Program Files (x86)/Google/google_appengine/dev_appserver.py",
      "debugOptions": [
        "WaitOnAbnormalExit",
        "WaitOnNormalExit",
        "RedirectOutput",
        "DjangoDebugging"
      ],
      "externalConsole": false
    },
```

When the debugger starts, it stops at a .py file in google app engine source. throws an error `AttributeError, 'Request' object has no attribute '__members__'`

Can you point me where I'm doing it wrong?  Many thanks!

**Comment by DonJayamanne** [comment]
Will look into this tomorrow. sorry guys.

**Comment by zjaml** [comment]
Thank you so much! Would be great if I can debug this way.

**Comment by DonJayamanne** [comment]
@cricque , @zjaml , good news guys. I've managed to get it working on OSX.
I'll update the wiki instructions and let you know once done.

**Comment by zjaml** [comment]
@DonJayamanne that's great. I'll check it out!
Thank you so much!

**Comment by DonJayamanne** [comment]
@zjaml , the wiki hasn't been updated yet, will let you know once done.

**Comment by DonJayamanne** [comment]
@zjaml , @cricque , here you go guys, [Instructions for debugging Google App Engine](https://github.com/DonJayamanne/pythonVSCode/wiki/Debugging:-Google-App-Engine)

**Comment by zjaml** [comment]
@DonJayamanne Awesome man, great work and much appreciated!
Will check it out soon.

**Comment by zjaml** [comment]
@DonJayamanne I finally made it work!! I'm so excited!
Thank you for so much patience, you are so brilliant knowledgeable and kind!

**Comment by DonJayamanne** [comment]
@zjaml , thanks and glad I could help.
Feedback, requests and pull requests are always welcome to make this a better product.
