### ISSUE TITLE
launch.json pythonPath from settings.json pythonPath

### ISSUE THREAD

**Issue by TurboTim** [DonJayamanne/pythonVSCode#214]
Hi,

Great plugin, your work has really paid off.

Just wondering though, it doesn't seem like the '~' works in launch configuration pythonPaths (where it does in settings.json) and I was wondering why the launch.json default pythonPath is not inherited from the one set in settings.json?

Thanks
Tim

**Comment by DonJayamanne** [comment]
I will have a look at ~.
As for defaulting the path from settings.json, this will (hopefully) be fixed in the next release of Vs code (done changes are required in the Vs code app top make this possible).

**Comment by DonJayamanne** [comment]
@TurboTim , this is now available in the latest release.
The default value for pythonPath in launch.json is now: ```pythonPath:"${config.python.pythonPath}"```.

With this syntax the launch.json is merely referencing the value in the settings.json
