### ISSUE TITLE
Intellisense Doe not Detect for instantiated objects

### ISSUE THREAD

**Issue by selfcommit** [DonJayamanne/pythonVSCode#218]
When using an imported lib, I expect behavior like:
![image](https://cloud.githubusercontent.com/assets/1029030/16960000/a062f652-4db5-11e6-8de0-e3e340673ed8.png)

However, when using the instantiated version of that same imported lib:
![image](https://cloud.githubusercontent.com/assets/1029030/16960032/b9a8d316-4db5-11e6-8a40-a60387df2622.png)

As you can see, 'g' is the same as GoogleTools.GoogleTools... just the instantiated version. 

It would be preferable to continue to see the methods / properties of g, the same way as in the first image.

**Comment by selfcommit** [comment]
As I'm looking at this - it seems to work as expected with other Python libs

![image](https://cloud.githubusercontent.com/assets/1029030/16960321/f9c45ad2-4db6-11e6-8054-8d7fbe9d9bdc.png)

Perhaps the issue is that duplicate name of class and lib in my example, or that Intellisense is set to a limited depth

**Comment by DonJayamanne** [comment]
@selfcommit , please could you send me the link to this GoogleTools package.

**Comment by selfcommit** [comment]
@DonJayamanne  I believe the issue is related to how the Google tools lib was created (it's internal tool)

Should be safe to close this issue.
