### ISSUE TITLE
Syntax highlighter partially works

### ISSUE THREAD

**Issue by erezak** [DonJayamanne/pythonVSCode#22]
A clean install of pythonVSCode 0.2.8
class, def keywords and others aren't highlighted.
import, for example, is highlighted.

![pythonvscode](https://cloud.githubusercontent.com/assets/406695/13099111/cf5dde28-d537-11e5-8121-659c85b5bb5d.png)

**Comment by DonJayamanne** [comment]
This extension didn't highlight any keywords. That functionality is not offered by this extension.
For highlighting, please try the following extension on top on my extension:

https://marketplace.visualstudio.com/items?itemName=magicstack.MagicPython

**Comment by erezak** [comment]
Thank you. Will try it :) Is this what you're using in the screenshots?
