### ISSUE TITLE
Specify what versions of Python must be supported to contribute

### ISSUE THREAD

**Issue by brettcannon** [DonJayamanne/pythonVSCode#221]
https://github.com/DonJayamanne/pythonVSCode/wiki/Contribution doesn't specify what versions of Python the extension's code must work under. E.g. does Python 2.6 need to be supported?

**Comment by DonJayamanne** [comment]
Will update this section with more information within the next hour or two.  thanks for picking that up

**Comment by DonJayamanne** [comment]
Done
