### ISSUE TITLE
Debugging python in module mode ?

### ISSUE THREAD

**Issue by christopheblin** [DonJayamanne/pythonVSCode#222]
Hi,

I think that I am asking a stupid question but I do not manage to make it work on my own or with the help of "the internet" so maybe this is not stupid ;)

How do you debug a python script that is launched with the -m option of the python interpreter ?

For example :

    python -m Module.path.script_without_py_extension  myarg1

Thanks for any help

**Comment by DonJayamanne** [comment]
@christopheblin , if you want to debug it using VS Code, then don't use the command line option.
Just use VS Code:  
1. Open the file to be debugged  
2. Configure your arguments in the launch.json file
3. Start debugging

**Comment by christopheblin** [comment]
Thanks for answering @DonJayamanne 

The problem is that this is not working : the relative imports that are used in the code are not resolved (I suppose because the python is not invoked with -m option)

Here is an example where import sys works but the relative import fails

insert_first_gtfs.py

    import sys
    from ...Utilities.sqlutils import SqlServer

launch.json

    {
        "version": "0.2.0",
        "configurations": [
            {
                "name": "Python",
                "type": "python",
                "request": "launch",
                "stopOnEntry": true,
                "program": "${file}",
                "cwd": "${workspaceRoot}/..",
                "args": ["arg1"],
                "debugOptions": [
                    "WaitOnAbnormalExit",
                    "WaitOnNormalExit",
                    "RedirectOutput"
                ]
            }
        ]
    }

error

    Traceback (most recent call last):
      File "c:\Repos\MAP_ETL\PTETL\Mixer\launchers\insert_first_gtfs.py", line 11, in <module>
        from ...Utilities.sqlutils import SqlServer
    ValueError: Attempted relative import in non-package
