### ISSUE TITLE
Auto-complete does not pick up strings

### ISSUE THREAD

**Issue by nchammas** [DonJayamanne/pythonVSCode#223]
When I enable this plugin, auto-complete stops picking up strings.

For example:

```python
code = "DFF26"
another_code = "D
```

Right after hitting `D`, VS Code normally would auto-complete `DFF26`. However, with this plugin installed that doesn't happen.

**Comment by DonJayamanne** [comment]
Raw strings are not part of the auto completion, I don't see the point in auto completin.
Besides you shouldn't be copying (repeating) the text, instead you should be reusing the variable "code", and intellisense would work for that.

**Comment by nchammas** [comment]
That was just a toy example to provide a minimal reproduction of the issue, since I assumed it was unintentional that you could not auto-complete strings.

Since you in fact don't see the point of doing that, let me provide some more realistic examples.

1. **Dictionary lookups**: Dictionary keys are often strings. If I look something up by a certain key, I would expect auto-complete to suggest that key in the future.

   ```
   if root_device['Ebs']['VolumeSize'] < min_root_device_size_gb:
        root_device['Ebs'].update(...)
   ```
2. **Magic strings**: Many strings have a special meaning in certain contexts. For example, to check that an Amazon EC2 instance is running using [Boto3](https://github.com/boto/boto3/), you would check:

   ```
   if instance.state == 'running':
        ...
   ```
   You will likely want to refer to this magic string in other parts of your code. When you do, auto-complete should suggest it.
3. **Object attributes that double as items**: If you've ever used DataFrames from Pandas or PySpark, you know you can access fields either as attributes (e.g. `person.first_name`) or as items (e.g. `person['first_name']`). Both access methods are very common in both of these libraries. 

   Auto-complete should suggest keys that I've used, regardless of whether I am using the attribute access method or the item access method.

I think these are all very common usage patterns. You can change your code to avoid using strings in these ways, but I think common usage patterns should inform how workflow tools work, and not the other way around.

**Comment by nchammas** [comment]
User-defined named tuples are another area where you'd want auto-completion to pick up strings:

```python
from collections import namedtuple

Person = namedtuple('Person', ['first_name', 'last_name'])
person1 = Person(fir  # <== auto-completion should kick in right there
```

**Comment by DonJayamanne** [comment]
@nchammas , i've raised your issue against the Jedi library, as that's what's being used to provide the intellisense in Python.
