### ISSUE TITLE
can't run debugger as sudo

### ISSUE THREAD

**Issue by rodcox89** [DonJayamanne/pythonVSCode#224]
I'm trying to run the debugger on a flask app that runs on port 80, but am unable to because this process requires root access. It appears that the debugger doesn't allow you to run programs using sudo.

**Comment by DonJayamanne** [comment]
@rodcox89, not sure about that, never tried it. I guess the answer at this stage would be - no it isn't officially supported, not yet. Will look into this issue soon .

**Comment by DonJayamanne** [comment]
@rodcox89 , what OS are you using at this stage? Will be fixing this today.

**Comment by DonJayamanne** [comment]
@rodcox89 , the next build will contain the fix for this and the instructions are as follows:
https://github.com/DonJayamanne/pythonVSCode/wiki/Debugging-:-Sudo-(root-privileges)

**Comment by rodcox89** [comment]
Nice!!
