### ISSUE TITLE
Unable to debug flask blueprint functions

### ISSUE THREAD

**Issue by carc1n0gen** [DonJayamanne/pythonVSCode#225]
Hello, I've created a minimal flask application with a single blueprint, that has  single function routed.  The debugger does pause outside the function (when the blueprint is imported).  But if I put a breakpoint inside the function that gets routed, the debugger says it's an `Unverified Breakpoint` and it never stops there even when I hit the route in my browser.

I'm on my phone atm, but if requested I will put up my code and link to it.

**Comment by DonJayamanne** [comment]
@carc1n0gen , uploading the code would definitely help. thanks

**Comment by carc1n0gen** [comment]
Sorry for the false issue.  It turns out that if you have debug enabled in the flask config, then VS Code is unable to debug properly.  Disabling debug mode fixed things.
