### ISSUE TITLE
Linter does not work

### ISSUE THREAD

**Issue by khaledkbadr** [DonJayamanne/pythonVSCode#226]
I installed the extension in VS Code but doesn't see any linting in any of my files.
I don't know wonder if I missed a configuration or it's broken.

**Comment by DonJayamanne** [comment]
You need to install the linter. Please check the troubleshooting guide.
```
Pip install pylint
```

**Comment by khaledkbadr** [comment]
I've installed pylint but it doesn't work. I'm on Ubuntu. seems to work fine on my Mac though!
