### ISSUE TITLE
python3 pylint unable to import 'enum'

### ISSUE THREAD

**Issue by Livenux** [DonJayamanne/pythonVSCode#227]
I use vscode edit python3 program import enum,pylint error is follows:`E0404:unable to import enum`, but enum operates nornally under Python3.while python2 does not, my Python of vscode operating configuration is Python3.

**Comment by DonJayamanne** [comment]
If it works under python3 and not python2, then you need to do two things:
- Configure vs code to point to python 2  
- Ensure pylint is installed in the python 2 environment  

Have a look [here](https://github.com/DonJayamanne/pythonVSCode/wiki/Troubleshooting-Linting#1-unable-to-import--pylint)
