### ISSUE TITLE
Configuration for relative to workspace Python Path

### ISSUE THREAD

**Issue by ivomachado** [DonJayamanne/pythonVSCode#228]
Nowadays it's necessary to put the full path in the python.pythonPath settings. It would be very nice if we could do something like "${workspaceRoot}/venv/bin/python" in linux or "${workspaceRoot}/venv/Scripts/python.exe" in Windows.

Thank you for the great extension.

**Comment by DonJayamanne** [comment]
@ivomachado , that should work. Have you tried that?

**Comment by ivomachado** [comment]
It worked, sorry for the created issue, I looked for something in the documentation and didn't found. Thank you.
