### ISSUE TITLE
Debugger crashes os

### ISSUE THREAD

**Issue by tsrdatatech** [DonJayamanne/pythonVSCode#229]
I configured the launch.json file to debug some stuff and added the pythonPath to it to use. The section of launch.json that's relevant looks like:

` {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${file}",
            "pythonPath": "/home/tom/anaconda2/envs/ttheorydataextractor/lib/python2.7/site-packages/scrapy/cmdline.py",
            "args": [
                "crawl",
                "wsjdiary"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }`

After running the debugger I seen some output to the debug console that showed `Error: spawn EACCES`, once I hit the stop button it crashed the window manager and closes pretty much everything else.

I am running Python 2.7 on Ubuntu 16.04.

If I remove the pythonPath from launch.json it runs fine especially when launching vscode from terminal where I activated the virtualenv.

**Comment by DonJayamanne** [comment]
@tsrdatatech , the value for pythonPath is incorrect. ```pythonPath``` needs to point to the interpretter not to a python program.  
Example:   
```
"pythonPath": "/home/tom/anaconda2/envs/bin/python"
```

## Another solution:   
- Remove the pythonPath setting
- Close all instances of VS Code
- Activate the virtualenv from your terminal window, 
- From that terminal session launch vscode (this way VSCode will inherit the virtual environment settings, including the python interpreter from the virtual env)

More details can be found [here on the Wiki](https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version#virtual-environments)

**Comment by DonJayamanne** [comment]
@tsrdatatech , fixed this issue. Didn't realise the gravity of the issue until I tested it myself.

**Comment by tsrdatatech** [comment]
Ok great, thanks, appreciate you checking into this.
