### ISSUE TITLE
DebugAdapter bin folder not found on path /home/user/.vscode/extensions/donjayamanne.python-0.2.8/out/client/debugger/main.js.

### ISSUE THREAD

**Issue by Nerdenator** [DonJayamanne/pythonVSCode#23]
When I press F5 to debug, I get a message stating, "Please set up the launch configuration file to debug your application." That opens up my launch.json file, which looks like:
```

{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Python",
			"type": "python",
			"request": "launch",
			"stopOnEntry": true,
			"program": "${file}",
			"debugOptions": [
				"WaitOnAbnormalExit",
				"WaitOnNormalExit",
				"RedirectOutput"
			]
		},
		{
			"name": "Python Console App",
			"type": "python",
			"request": "launch",
			"stopOnEntry": true,
			"program": "${file}",
			"externalConsole": true,
			"debugOptions": [
				"WaitOnAbnormalExit",
				"WaitOnNormalExit"
			]
		},
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "externalConsole":false,
            "program": "${file}",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }
	]
}
```

Then, pressing the "play" button in the Debug pane gets me this error:
`DebugAdapter bin folder not found on path /home/user/.vscode/extensions/donjayamanne.python-0.2.8/out/client/debugger/main.js.`

It looks like it's looking for the DebugAdapter that VSCode needs for this extension, but isn't finding it.

Other info:
Version 0.10.8
Commit db71ac615ddf9f33b133ff2536f5d33a77d4774e
Date 2016-02-05T10:00:07.223Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1

Ubuntu Linux 15.10 x64.
Python 2.7.10

**Comment by DonJayamanne** [comment]
Please could you confirm python is in your current path. If not, please provide the fully qualified path to the python executable in the pythonPath setting in launch.json

**Comment by Nerdenator** [comment]
I ran `which python`, yielding `/usr/bin/python`, which I have added in each of the JSON objects:

`{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Python",
			"type": "python",
			"request": "launch",
			"stopOnEntry": true,
			"program": "${file}",
            "pythonPath": "/usr/bin/python",
			"debugOptions": [
				"WaitOnAbnormalExit",
				"WaitOnNormalExit",
				"RedirectOutput"
			]
		},
		{
			"name": "Python Console App",
			"type": "python",
			"request": "launch",
			"stopOnEntry": true,
			"program": "${file}",
            "pythonPath": "/usr/bin/python",
			"externalConsole": true,
			"debugOptions": [
				"WaitOnAbnormalExit",
				"WaitOnNormalExit"
			]
		},
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "externalConsole":false,
            "program": "${file}",
            "pythonPath": "/usr/bin/python",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }
	]
}`

No resolution yet; still throwing the exception. Would deinstallation/reinstallation help?

**Comment by DonJayamanne** [comment]
Hmmm, please do give that a go.

**Comment by Nerdenator** [comment]
Uninstalled both the extension and VSCode, no dice. 

What else is on the list?

**Comment by DonJayamanne** [comment]
I will need to try this out at my end. Unfortunately I will be out of town for a week and half. Meaning I won't be able to check this out. I'm sorry, but I will try to have a look at this tomorrow if  possible, before I head off. If you are keen, then you could debug the extension at your end and determine the cause.

**Comment by Nerdenator** [comment]
I'll try and dig-in on that in a while when I get a few moments free. Thanks for the attention so far; I appreciate it.

**Comment by DonJayamanne** [comment]
Please could you remove the last item from the launch.json config. There are three items, please remove the last one, that's as duplicate of the first. The one with three "name":"python"

**Comment by Fiveside** [comment]
I'm receiving also receiving this error.  After some cursory debugging, the error is referencing file `main.js`, but the file on disk is `Main.js`.  On windows, this doesn't matter because filenames are case insensitive.  However on OSX and Linux, filenames are case sensitive, and the import fails.

**Comment by DonJayamanne** [comment]
Tiles, thanks for identifying that. Will fix it tonight

**Comment by DonJayamanne** [comment]
Fixed in the latest build, please install the latest version

**Comment by Nerdenator** [comment]
Latest version installed; debug now works. Thanks!

**Comment by DonJayamanne** [comment]
Yay, special thanks  @Fiveside

**Comment by niki-sp** [comment]
same problem Main.js vs main.js in 0.2.10

**Comment by TheRealPhoneCall** [comment]
Same problem here, on build 0.5.5

Debug adapter executable 'C:/Users/daryl/.vscode/extensions/donjayamanne.python-0.5.5/out/client/debugger/Main.js' not found.
