### ISSUE TITLE
Couldn't figure out how to run unittest

### ISSUE THREAD

**Issue by zjaml** [DonJayamanne/pythonVSCode#230]
Please forgive me if this is a really dumb question. But I couldn't find any document about how to run unittest files with the latest VSCode.

- I have tried using the entry below in launch.json

```
    {
      "name": "python test",
      "type": "python",
      "request": "launch",
      "program": "${workspaceRoot}/test.py",
      "cwd": "${workspaceRoot}",
      "args": []
    }
```
 which produces 
```TypeError: Cannot read property 'join' of undefined```

- I have tried the following in tasks.json
```
{
	"version": "0.1.0",
	"command": "python",
	"isShellCommand": true,
	"showOutput": "always",
	"args": ["${file}"]
}
```

which gives me a weird error 
``` 
in <module>
    "isShellCommand": true,
NameError: name 'true' is not defined
```

**Comment by csprabala** [comment]
try setting "cwd": "/Users/name/path-to-code-directory" and try.

You may also want to set the debug options

"debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"

            ]

**Comment by zjaml** [comment]
@csprabala problem solved by your suggestion! Thank you!

**Comment by DonJayamanne** [comment]
@zjaml , how did you manage to run the unit tests?
Was it via the tasks.json file?

**Comment by zjaml** [comment]
@DonJayamanne I started a testrunner directly from launch.json file with the debug opitions you provided. The testrunner loads unittests and run them.
```
  {
      "name": "python test",
      "type": "python",
      "request": "launch",
      "program": "${workspaceRoot}/src/gae/testrunner.py",
      "debugOptions": [
        "WaitOnAbnormalExit",
        "WaitOnNormalExit",
        "RedirectOutput"
      ]
}
```

**Comment by DonJayamanne** [comment]
@zjaml , would you be able to provide the contents of testrunner.py? thanks

**Comment by zjaml** [comment]
@DonJayamanne [Here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/standard/localtesting/runner.py) it is. The idea comes from [this](https://cloud.google.com/appengine/docs/python/tools/localunittesting) page.
