### ISSUE TITLE
Code backlight like Python2 instead of Python3

### ISSUE THREAD

**Issue by selfvoid** [DonJayamanne/pythonVSCode#232]
Good day, this is not an issue generally, but, how to get it do it right? I'm using Python3.

![snapshot1](https://cloud.githubusercontent.com/assets/12895600/17237705/9a7b4988-5576-11e6-9d33-7b4db9c8af6a.png)

![snapshot2](https://cloud.githubusercontent.com/assets/12895600/17237708/a07962f2-5576-11e6-91c8-daa8306c0701.png)

**Comment by DonJayamanne** [comment]
@selfvoid , The standard theme doesn't colorize the functions (this seems to be the case in javascript and typescript as well). 
If you try some other themes, then it works (not all of them), here's one such example - [Monokai](https://marketplace.visualstudio.com/items?itemName=gerane.Theme-Monokai)
