### ISSUE TITLE
Can't seem to run Python 2.7

### ISSUE THREAD

**Issue by gbritton1** [DonJayamanne/pythonVSCode#234]
I have both Python 2.7 and Python 3.5 installed.  My settings.json looks like this

`// Place your settings in this file to overwrite default and user settings.
{
    "python.pythonPath": "c:/python27/python.exe"
    ,"python.linting.enabled": false
}`

I have a little program to print the version:

`import sys
print(sys.version)`

When I run it, using the settings.json as above, I get:

`3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)]`

In the debug console.

How do I make the extension run Python 2.7 instead of 3.5?

**Comment by DonJayamanne** [comment]
You need to configure the pythonPath setting in the launch.json file too. Have a look at this link https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version#python-version-used-for-debugging

Ensure the setting points to "c:/python/pythonnext"
