### ISSUE TITLE
`suite` vs `pass` for snippet bodies

### ISSUE THREAD

**Issue by srfraser** [DonJayamanne/pythonVSCode#235]
When using a snippet, you end up with `suite` in the body, such as:

    def funcname(parameter_list):
        suite

Would it be better to have `pass` instead of `suite` so that a function body, `with` block or similar can be left empty while working on the structure of the code? I understand that the way it is at the moment, all the template sections must be replaced and that serves as a reminder to make those changes, it just seems more convenient to let `pass` be the body

**Comment by DonJayamanne** [comment]
@srfraser , great suggestion and makes perfect sense.
