### ISSUE TITLE
sample on how to use unittest with the extension

### ISSUE THREAD

**Issue by symbioticKid** [DonJayamanne/pythonVSCode#236]
Would be nice to have some samples on how to use the python unittest feature

**Comment by DonJayamanne** [comment]
@symbioticKid , @aggFTW, I am planning on removing support for Unit Tests at this stage. 
At the moment the unit test support in the extension in pretty woeful.

All it does is invoke the py.test or nosetest with the arguments that you need to configure.
I.e. you (users) might as well configure the tasks.json file to run the unit tests. I reckon that would be easier and better at this state as it is built into VS Code and I'm certain Microsoft will improve upon it.

Below are two examples on configuring the tasks.json to run unit tests:
- http://mahugh.com/2016/04/27/python-and-vs-code/
- https://bespohk.com/blog/configuring-python-visual-studio-code

I will update the documentation to include the suggestions from the above sites to run unit tests in VS Code.

**Comment by aggFTW** [comment]
I had already configured my unit test runs with tasks, but this seemed like
a nicer experience.
Thank you for following up!

**Comment by DonJayamanne** [comment]
@aggFTW , I am trying to provide a much better UX for unit tests. Hang in there.

**Comment by DonJayamanne** [comment]
@symbioticKid , @aggFTW, @zjaml, @csprabala
What testing framework do you use?
Do you always run all the tests?
Or there instances when you run specific test suites or test functions?

**Comment by aggFTW** [comment]
I use nose and unittest depending on which project I'm using, but usually nose.
For the project I develop on the most, I have 3 different libraries with 3 different unit test folders, and I run one specific folder while developing but run all 3 before a PR.

**Comment by DonJayamanne** [comment]
@aggFTW , my plan is t build a UI (similar to a test explorer) that will list all tests (suites and test functions), from there you could either run all, a specific test suite or a specific test function. But at this stage that will only work for pytest (simply because pytest can run unittest, nose, and more. Hence that would be a good starting point).

Thanks @aggFTW  for your feedback.

**Comment by zjaml** [comment]
@DonJayamanne really excited about the UI feature! It would be much nicer to be able to select single test and run for development.
BTW, pycharm has some pretty similar feature where it lists up all the tests and each can be run seperately. It also has great support for GAE, which is huge for me because currently many dependency problems show up when I debug tests from vscode, especially for thirdparty libs.

**Comment by DonJayamanne** [comment]
@zjaml , unfortuantely support for GAE will probably be a secondary step. First step, get the UI and basic testing working. Will keep you posted on this thread.

**Comment by DonJayamanne** [comment]
@symbioticKid, sorry for the delay, will submit a sample soon. Busy working in the integrated unit test (better ux).

**Comment by DonJayamanne** [comment]
@zjaml , @symbioticKid , @aggFTW 
here's a preview of what I'm working on, feedback is welcome.
the UX will be very very simple at this stage, display all unit tests, you call either run all, or a specific test(s). Results will be displayed in the output window. Nothing fancy, but stage one.

Using pytest (which has support for nosetests, unittests, etc).

<img width="807" alt="screen shot 2016-08-05 at 20 00 51" src="https://cloud.githubusercontent.com/assets/1948812/17433343/7297186c-5b47-11e6-8cac-23cdd0feb960.png">

**Comment by DonJayamanne** [comment]
@zjaml, good news, gae unit tests can be run from pytest, there are at least two plugins for pytest that make this possible.

**Comment by aggFTW** [comment]
Hey, thanks for the great start :)

Some questions:

1. Is there any way to have the test explorer on the left? I'm just thinking that some people might want to have the test explorer open while looking at tests... I guess you can simple divide the main view, so it should be good.
2. How does pytest discover unit tests? What's the setup process?
3. How would results be displayed?
4. How can I act on results? For example, after a first run, I could then choose to only run failing tests on subsequent executions.
5. Will debugger work while running unit tests?

Thanks for your effort!

**Comment by symbioticKid** [comment]
+1 on having the test explorer on the left
Some more feedback:
1. Visual markers for showing pass/fail (green/red)
2. Aggregating the number of tests within a hierarchy and showing a number next to it (for each hierarchy level) would be useful
3. Right click to add tests within the context of the GUI (or what does the test discovery process look like)
4. Ability to create a unit test from the context of the actual code/object file being tested (right click -> create unit test)

**Comment by zjaml** [comment]
Looks awesome, will definitely try running with GAE. 
+1 on having the test explorer on the left.

Thanks

**Comment by DonJayamanne** [comment]
@aggFTW, answers inline:

1. Is there any way to have the test explorer on the left?    
**Yes will do.**
2. How does pytest discover unit tests? What's the setup process?   
**py.test supports a ```--collect-only``` command line arg to discover all tests.**  
```py.test --collect-only <folder> <folder> <file> ```
3. How would results be displayed?   
**Test output will be displayed in the python output channel**
**A green or red indicator will be displayed next to the test name on the explorer**
4. How can I act on results? For example, after a first run, I could then choose to only run failing tests on subsequent executions.   
**Yes, an option will be display to run just the failed tests**
5. Will debugger work while running unit tests?   
**Unfortunately not at this stage**

**Comment by DonJayamanne** [comment]
@symbioticKid 

1. Visual markers for showing pass/fail (green/red)   
**will do**
2. Aggregating the number of tests within a hierarchy and showing a number next to it (for each hierarchy level) would be useful   
**will do**
3. Right click to add tests within the context of the GUI (or what does the test discovery process look like)   
**Later**
4. Ability to create a unit test from the context of the actual code/object file being tested (right click -> create unit test)   
**Later**

**Comment by DonJayamanne** [comment]
@symbioticKid , @aggFTW , @zjaml slight change in plans.

We are exploring other simpler UX at this stage, such as the following (without a test explorer). 
- Allow user to run all tests (in the project)    
- Allow user to run all tests in a file (right click a file and run tests)  
- Display the test results in the status bar (how many failed, succeeded, etc)
- Ability to re-run all tests, run last test or run failed tests from command pallet (or status bar)
- Possibly display error markers, decorators (next to the code) and code lenses in unit tests to show what unit test failed in what line and why.

This simpler UX gives you pretty much everything that the original test explorer provided, with the exception of displaying all unit tests. If you did want to run a unit test, just select that file, right click on it and run the tests.

Will keep you posted.

**Comment by DonJayamanne** [comment]
@zjaml , I believe I have found a way to debug the unit tests.
I can provide you with some instructions for debugging with py.test and nosetest if necessary (I will make this seemless later on).

_**Debugging with nosetests:**_
- Create a file named xyz.py in the root directory  
- Add the following code   
- Add a break point in you test method (the test method you wish to debug)   
- Start debugging
```python
import nose
nose.run()
```

_**Debugging with py.test:**_
- Create a file named xyz.py in the root directory  
- Add the following code   
- Add a break point in you test method (the test method you wish to debug)   
- Start debugging
```python
import pytest
pytest.main()
```

**Comment by DonJayamanne** [comment]
Documentation has been updated with the new release:
https://github.com/DonJayamanne/pythonVSCode/wiki/UnitTests
