### ISSUE TITLE
Syntax highlight for dict comprehensions in Python 2.7

### ISSUE THREAD

**Issue by aitchnyu** [DonJayamanne/pythonVSCode#238]
Syntax highlighter trips on an example of dict comprehensions for Python 2.7 codebase. It is apparent by pasting this into VS Code. The second example highlights fine, but the first example highlights the stuff after the comma in the color for dict keys.

```
print {k:v for k,v in a if v}
print {k:k*k for k in a if k>0}
```

**Comment by DonJayamanne** [comment]
@aitchnyu , syntax highlighting isn't part of this extension. Please try installing the [Magic Python](https://marketplace.visualstudio.com/items?itemName=magicstack.MagicPython) extension for better experience.
