### ISSUE TITLE
Integrated Unit Tests

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#239]
- [x] Code Lens (Add text 'Test')
- [x] Code Lens to run the test directly
- [x] When running a test via the codelens, support parameterized tests (nose, pytests)
- [ ] Update documentation with samples for each (NoseTest, PyTest and UnitTests)
- [x] Add support for UnitTest (build in test framework)

**Phase 2:**
- [ ] Update Code Lens if a new method is added to a test file
- [ ] Display test status in codelens
- [ ] Debug Test File (if simple)
- [ ] Code Lens to display quickpick - View test result
- [ ] Code Lens to display quickpick - Debug test
   + Ensure to add breakpoint to first line of code in the method
   + Ensure any launcher files created/used do not get displayed in debugger (such api exists in ptvsd)
- [x] Upon selecting a function from quick pick display another quick pick
   + [x] Run test function
   + [ ] Debug test function
   + [x] View result of previous test for this function
   + [ ] Navigate to test function

**Phase 3**
- [x] Optional use of Colors in ouput (https://github.com/Microsoft/vscode/issues/571)
- [ ] Optionally running tests in integrated terminal (problem - output is still not colorized)

**Comment by DonJayamanne** [comment]
Early preview
![testsnose_pytest](https://cloud.githubusercontent.com/assets/1948812/17954856/2c6f33ae-6ac1-11e6-8c86-15b2dfd99769.gif)

**Comment by kieferrm** [comment]
@DonJayamanne  The flow shown in the gif makes sense. The visual presentation needs some work. I can point out what I think needs improvement, but we need to work with @bgashler1 to find out which solution is best.

1. Progress indication in the status bar when discovering tests should be an animated icon inspired by what we show when performing git pull/push.
2. I like the cue in the status bar when tests didn’t run yet. But I don't like what it looks like right now. The play-it icon doesn’t look right.
3. There should be a visual separation between the different logical groups of entries (actions versus test methods) in the drop down.
4. The presentation of the detail information in the drop down for "View Test Output" and "Run Failed Tests" is too close to the regular entries. That causes them to clutter the drop down visually.
5. The output console is very bland. Is there a way to use green as the text color for success information and red for failure information?

**Comment by DonJayamanne** [comment]
@kieferrm 
>1. Progress indication in the status bar when discovering tests should be an animated icon inspired by what we show when performing git pull/push.

Status bar icons are limited to unicode icons and ociticons. Octicons are supported using the ```$(iconName)``` format. 

**Option1** - How about a similar format (```$(filename)```)? If text within```$(...)``` is a filename, then VS Code displays that image. This could be extended in the future to base64 images or other font icons - [fontawesome](http://fontawesome.io/icons/), etc. 
Is this opening up the API too much, we could end up with too many distracting icons in the statusbar (today they are limited to just flat icons/gifs). 

**Option 2** - Or we could add support for some built in icons that extension authors could utilize.  

If you like either of the two approaches then I could try to work on a PR for vscode & others could probably critique it (probably after the rest have been done and sounds like a fairly simple PR). 

>2 & 3. There should be a visual separation between the different logical groups of entries (actions versus test methods) in the drop down.

Agreed. 

>5. The output console is very bland.

Output channels don't support colours (not yet - Microsoft/vscode/issues/571). 
I could however run the tests in a Terminal window using the new Terminal API. 
This should present the text in the standard colors.

>5. Is there a way to use green as the text color for success 

Running the tests in a terminal window will display the results in the standard colors, that would fix this issue. However successful tests aren't displayed in green. Will check if there are ways to customize the output.

> What next

I'll tweek some of the UI (without any VS Code PR) and upload another set of images that you and @bgashler1 could critique.

**Comment by DonJayamanne** [comment]
@kieferrm

>Option 2 - Or we could add support for some built in icons that extension authors could utilize. 

The more I think about supporting additional icons in the status bar, I believe the above **Option 2** is the best approach.
We could add support for custom built in icons using a format similar to ```$(vscode-...)```.  
This would ensure we have a consistent set of icons in the statusbar. Extension authors could use the same icon for a check, a cross or any other, and personally thats better, specially to a user - consistent UX.  

Just as we have a set of octicons, we would have a set of vscode icons that can be re-used by extension authors. As a first step this would only be supported in the status bar.

**Caution** If we add support for such custom icons in the status bar, we would need to consider supporting this approach elsewhere in VS Code as well. Places where octicons are supported today, such in quick pick lists.

**Comment by DonJayamanne** [comment]
<img width="822" alt="screen shot 2016-09-01 at 07 41 59" src="https://cloud.githubusercontent.com/assets/1948812/18147484/169887cc-7018-11e6-9446-394db40781f4.png">
