### ISSUE TITLE
External Console/Terminal Debugging 

### ISSUE THREAD

**Issue by Cistoran** [DonJayamanne/pythonVSCode#242]
I have a simple Python script that I wrote in VSCode using your Extension on Windows. I migrated one of my machines to Linux and worked on getting VSCode installed and up and running with the Python extension. I'm almost ready to go but the issue I have now is that the debugger isn't launching in an external console. 

Instead it throws the error
`EOFError, EOF when reading a line` 

The line it is erroring on looks like this
 `email = input('Email: ')`

Here's what my `launch.json` file looks like

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "program": "${file}",
            "pythonPath": "/usr/bin/python3.5",
            "externalConsole": true,
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Python Console App",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "program": "${file}",
            "pythonPath": "/usr/bin/python3.5",
            "externalConsole": true,
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Django",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${workspaceRoot}/manage.py",
            "args": [
                "runserver",
                "--noreload"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "DjangoDebugging"
            ]
        },
        {
            "name": "Watson",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${workspaceRoot}/console.py",
            "args": [
                "dev",
                "runserver",
                "--noreload=True"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }
    ]
}
```

And my `settings.json` file looks like this

```
{
    "python.pythonPath": "usr/bin/python3.5"
}
```

I've tried searching and read through the Wiki but couldn't find anything on why this would be happening. Any help would be greatly appreciated.

**Comment by DonJayamanne** [comment]
@Cistoran, launching the external terminal for Linux will be available in the next release (probably over the weekend, after the next version of VS Code is released).
This issue (scoped to just Linux) was fixed recently 7ce72ef72babbed157b2731c21e8d642005b9732.

**Comment by Cistoran** [comment]
@DonJayamanne The newest version of VSCode (1.4) just released. Is there anyway to compile the extension with those changes now instead of waiting for the release?

**Comment by DonJayamanne** [comment]
Aah, will release the new version in a few minutes then. Let me test everything.
Hang in there for a few minutes.

**Comment by DonJayamanne** [comment]
@Cistoran , new version has been published
