### ISSUE TITLE
Refactoring not working (windows)

### ISSUE THREAD

**Issue by omerbenamram** [DonJayamanne/pythonVSCode#244]
Hi!

I couldn't get any of the refactoring features to work.
Autocompletion seems to be working fine though.

I'm getting -
Cannot perform refactoring using selected element(s)

for even the most trivial refactors (also for sort imports).
something like:

```
def test():
    x = 1
    var = x + 1
    ...

```

would throw the error.
I'm using windows 10 64-bit, with python 3.5 (anaconda)
I can't even attempt to debug this since there are no stacktraces.

Thanks!

**Comment by DonJayamanne** [comment]
Please  have a look at the python output window (output channel) and provide the contents.

**Comment by omerbenamram** [comment]
ahh 
- Refactor failed, Currently code refactoring is only supported in Python 2.x

Well I guess that covers it :(

**Comment by DonJayamanne** [comment]
@omerbenamram, Oh, sorry, will fix that, it is supported on python 3.5, will remove that check later today. Sorry about that.
Will let you know once it has been fixed, hang in there

**Comment by DonJayamanne** [comment]
@omerbenamram, this has been fixed in the latest version 0.3.21. please check it out.

**Comment by omerbenamram** [comment]
@DonJayamanne I've updated to 0.3.21 - and now getting this for method extraction on a simple function:
```
def test():
    x = 1
    var = x + 1
```
(extract var = x+1 to a separate function)
can you reproduce?

```
##########Refactor Output##########
Error in refactoring:
Refactor failed. IndexError: string index out of range
  
Traceback (most recent call last):
  File "refactor.py", line 245, in watch
    self._process_request(self._input.readline())
  File "refactor.py", line 234, in _process_request
    request['start']), int(request['end']), request['name'])
  File "refactor.py", line 195, in _extractMethod
    refactor.refactor()
  File "refactor.py", line 89, in refactor
    self.onRefactor()
  File "refactor.py", line 152, in onRefactor
    self.project, self.resource, self._startOffset, self._endOffset)
  File "C:\Users\Omer\.vscode\extensions\donjayamanne.python-0.3.21\pythonFiles\rope\refactor\extract.py", line 79, in __init__
    super(ExtractMethod, self).__init__(*args, **kwds)
  File "C:\Users\Omer\.vscode\extensions\donjayamanne.python-0.3.21\pythonFiles\rope\refactor\extract.py", line 43, in __init__
    self.end_offset = self._fix_end(resource.read(), end_offset)
  File "C:\Users\Omer\.vscode\extensions\donjayamanne.python-0.3.21\pythonFiles\rope\refactor\extract.py", line 51, in _fix_end
    while offset > 0 and source[offset - 1].isspace():
IndexError: string index out of range
```

**Comment by DonJayamanne** [comment]
Oops, will look into this asap, somehow missed this

**Comment by DonJayamanne** [comment]
@omerbenamram, please could you try the following?

- Ensure you have at least one empty line at the end of the file (see below)  
- Highlight just ```var = x + 1``` and try to extract into a method. 
- Is python3.5 in your current path? (i.e. is this your default version of python)   
- Have you configured the path to python in settings.json (not necessary if point 2. is Yes)   

```python
def test():
    x = 1
    var = x + 1

# empty lines
# empty lines

```

**Comment by omerbenamram** [comment]
@DonJayamanne it seems to work with the empty lines. Thanks!

**Comment by DonJayamanne** [comment]
Hmm, perhaps something to be validated prior to the refactor. Thanks
