### ISSUE TITLE
python.pythonPath is not working when path is relative.

### ISSUE THREAD

**Issue by conmute** [DonJayamanne/pythonVSCode#246]
Example of Visual Studio Code workspace settings:

    {
        "python.pythonPath": "./venv/bin/python3.5",
        "python.linting.prospectorPath": "./venv/bin/prospector",
        "python.linting.prospectorArgs": [
            "--strictness",
            "veryhigh"
        ],
        "python.linting.pylintPath": "./venv/bin/pylint",
        "python.linting.pylintArgs": [
            "--rcfile=./config/pylint.rc"
        ],
        "python.linting.pydocStylePath": "./venv/bin/pydocstyle"
    }

When i change "python.pythonPath" to 

    "python.pythonPath": "/opt/cosname/http/one-off/providence/site/venv/bin/python3.5",

InteliSense will work perfectly, that i cannot say the same for previous `pythonPath` value. Though relative path for `pylint` and `pydocstyle` with `prospector` works perfectly.

Would be nice to keep all paths as relative ones. So i can add environment settings to the commit  :3

**Comment by DonJayamanne** [comment]
will fix that asap.
However for the moment you could use the following setting.
Always prefix with **${workspaceRoot}**, when dealing with paths relative to the workspace root (or project directory).

```json
{
    "python.pythonPath": "${workspaceRoot}/venv/bin/python3.5",
    "python.linting.prospectorPath": "${workspaceRoot}/venv/bin/prospector",
    "python.linting.prospectorArgs": [
        "--strictness",
        "veryhigh"
    ],
    "python.linting.pylintPath": "${workspaceRoot}/venv/bin/pylint",
    "python.linting.pylintArgs": [
        "--rcfile=./config/pylint.rc"
    ],
    "python.linting.pydocStylePath": "${workspaceRoot}/venv/bin/pydocstyle"
}
```

Using a fully qualified path in this manner is the safest approach.
