### ISSUE TITLE
Intellisense not working on new file before save

### ISSUE THREAD

**Issue by mww012** [DonJayamanne/pythonVSCode#248]
Something I've noticed is that if I open a new untitled file(either through File>New File or through the Command Palette) Intellisense doesn't work until the file is saved.  As soon as it's saved everything seems to work great.  Just a minor inconvenience but thought I'd mention it in case no one else has.

OS: Win10
VSCode version: 1.4.0
Python Ext version: 0.3.21

**Comment by DonJayamanne** [comment]
Unfortunately this will never work.  
Intellisense kicks off when the filetype has been detected.
If the file hasn't been saved (or no name has been given to the file), then the file type cannot be determined.  
You could even be writing javascript code, VS Code won't know - until the file has been given an extension.

**Comment by mww012** [comment]
That makes sense.  I didn't know if manually setting the language would give intellisense enough info to work but it doesn't sound like intellisense can use that info right now.  Thanks for check on this.
