### ISSUE TITLE
How to use VSCode to debug Scrapy projects

### ISSUE THREAD

**Issue by seozed** [DonJayamanne/pythonVSCode#249]
I want to test my Scrapy spiders using it. Anyone knows how to do that please?

**Comment by DonJayamanne** [comment]
@qsnow6 
Here's the solution:
- Sample file is myspider.py found in http://scrapy.org/
- Create a file named 'runner.py' with the following contents:
```python
from scrapy.cmdline import execute
execute(['scrapy','runspider', 'fullly qualified path to myspider.py file'])
```
- Add a breakpoint in your myspider.py file
- Start debugging by debugging the runner.py 

It should now work.

**Comment by strefethen** [comment]
Fwiw, here's an alternative: http://www.stevetrefethen.com/blog/debugging-a-python-scrapy-project-in-vscode

**Comment by DonJayamanne** [comment]
Reopening as a personal reminder to update documentation, and optionally add a debug config for this.

**Comment by DonJayamanne** [comment]
Turn this into a debug recipe

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#63
