### ISSUE TITLE
Intellisense aggressively inserts () and "" in code

### ISSUE THREAD

**Issue by davehamby** [DonJayamanne/pythonVSCode#251]
The first is usually an issue when moving a "(". "()" results.
The second is a problem almost always when inserting  a double quote or closing quotes.

**Comment by DonJayamanne** [comment]
@davehamby , this is an issue with VS Code that automatically inserts closing braces and closing quotes. 
You could turn it off in your (user or workspace settings) settings.json as follows:  
```json
"editor.autoClosingBrackets": false
```
