### ISSUE TITLE
Feature Request - Interactive Coding Experience Improvements

### ISSUE THREAD

**Issue by drcrook1** [DonJayamanne/pythonVSCode#253]
Hello,

This is really the only reason I don't use this tool.  Everything else is on par with what I want except this.

Here is what I'm looking for.  Specifically it needs to work with Ubuntu 16.04.
1.  Highlight a section of code -> Ctrl + Enter executes just that block
2.  Ctrl + Enter executes just the current line.
3.  Kernel Explorer
  3a.  Show currently loaded variables with drill down.
  3b.  Show currently loaded functions.
4.  Plot Visualizer Area

The most important features in this list to me are 1 and 2.  3 and 4 are nice to have extras.  If 1 & 2 were done, I would probably use this tool instead of Spyder.

**Comment by DonJayamanne** [comment]
Enhancements for #183

**Comment by DonJayamanne** [comment]
@drcrook1 , closing this as i'd like to move the discussion to #303
