### ISSUE TITLE
Display message if linter (or python tool) is not installed under current python environment

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#255]
Scenario:  
- Assume pylint is installed in python2 environment.   
- Python isn't installed in python3 environment  
- vs code is configured to use python3 and pytlint is turned on

Problem:
- pytlint might complain about not being able import certain modules (hence report a number of errors - false positives).  
- This seems to be a common occurrence
   
Reason:
- Pylint isn't installed under python3 environment.  

Solution:
- Determine the install location of such tools (packages) and if not under the right environment, then display a message (warning) (optional present button to install under the currently configured env)

**Comment by jabooth** [comment]
@DonJayamanne I wonder if we could go one step further, and bundle the default linter with the extension.

So, on fresh install of the extension, without custom configuration:

1. linting (powered by a version of pylint internal to the extension) 'just works' without touching the user's active Python environment (only the interpreter needs to be there to run the internal pylint). This is a similar experience to PyCharm.
2. If a version of pylint is present in the `python.pythonPath` install, this still takes precedence.
3. The user is still free to a) turn linting off b) use an alternative linting service, so long as they install it into the active Python environment.

If we had this setup, the issues raised here would be alleviated, and it would be (in my opinion) a better user experience. For example, as a user moves between different projects (each let's say with it's on Python environment) the user isn't constantly prompted to re-install pylint.

Again, happy to work on a PR for that if you like the idea!

**Comment by DonJayamanne** [comment]
I liked that, please proceed with that, as does the other, still not sure about that one, bit will check it out.

**Comment by DonJayamanne** [comment]
@jabooth , please don't do anything in this space yet.
I need to check the sizes of the linters. pre-packaging the linters is great, but eventually increases the file size of the extension.

**Comment by jabooth** [comment]
@DonJayamanne totally fair comment.

Quick test (Python 2.7/OS X)
```sh
> conda create -n pylint_size python=2.7
Package plan for installation in environment /Users/jab08/miniconda/envs/pylint_size:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2h-2     
    pip:        8.1.2-py27_0 
    python:     2.7.12-1     
    readline:   6.2-2        
    setuptools: 26.1.1-py27_0
    sqlite:     3.13.0-0     
    tk:         8.5.18-0     
    wheel:      0.29.0-py27_0
    zlib:       1.2.8-3      

> source activate pylint_size 
(pylint_size) > du -ks ~/miniconda/envs/pylint_size/lib/python2.7/site-packages/
8640	/Users/jab08/miniconda/envs/pylint_size/lib/python2.7/site-packages/
(pylint_size) > pip install pylint
Collecting pylint
  Using cached pylint-1.6.4-py2.py3-none-any.whl
Collecting isort>=4.2.5 (from pylint)
  Using cached isort-4.2.5-py2.py3-none-any.whl
Collecting astroid<1.5.0,>=1.4.5 (from pylint)
  Using cached astroid-1.4.8-py2.py3-none-any.whl
Collecting mccabe (from pylint)
  Using cached mccabe-0.5.2-py2.py3-none-any.whl
Collecting six (from pylint)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting configparser; python_version == "2.7" (from pylint)
  Downloading configparser-3.5.0.tar.gz
Collecting backports.functools-lru-cache; python_version == "2.7" (from pylint)
  Using cached backports.functools_lru_cache-1.2.1-py2.py3-none-any.whl
Collecting wrapt (from astroid<1.5.0,>=1.4.5->pylint)
Collecting lazy-object-proxy (from astroid<1.5.0,>=1.4.5->pylint)
Building wheels for collected packages: configparser
  Running setup.py bdist_wheel for configparser ... done
  Stored in directory: /Users/jab08/Library/Caches/pip/wheels/1c/bd/b4/277af3f6c40645661b4cd1c21df26aca0f2e1e9714a1d4cda8
Successfully built configparser
Installing collected packages: isort, six, wrapt, lazy-object-proxy, astroid, mccabe, configparser, backports.functools-lru-cache, pylint
Successfully installed astroid-1.4.8 backports.functools-lru-cache-1.2.1 configparser-3.5.0 isort-4.2.5 lazy-object-proxy-1.2.2 mccabe-0.5.2 pylint-1.6.4 six-1.10.0 wrapt-1.10.8
(pylint_size) > du -ks ~/miniconda/envs/pylint_size/lib/python2.7/site-packages/
19352	/Users/jab08/miniconda/envs/pylint_size/lib/python2.7/site-packages/
```
So that's 19352 - 8640 = 19352 - 8640 = 10,712KB = **10.46MB** for `pylint` + deps.

Two thoughts:

1. We could likely reduce this somewhat with a little cheeky optimisation
2. We could omit this from the download to start with but prompt the user to install the builtin linter

10MB is a reasonable increase in size for sure, but it's *such* a leap forward in the user experience to have linting work out of the box that IMHO it is probably worth the trade off.

**Comment by jabooth** [comment]
```
> cd  ~/miniconda/envs/pylint_size/lib/python2.7/site-packages
> find . -name '*.pyc' -type f -exec rm {} \;
> du -ks ~/miniconda/envs/pylint_size/lib/python2.7/site-packages/
10980	/Users/jab08/miniconda/envs/pylint_size/lib/python2.7/site-packages/
```
So that's actually around **5MB** once we remove the `.pyc` files.

**Comment by jabooth** [comment]
`pylint`s test folder is 3.3MB, `astroid`s is 778KB, so that's around 4MB...

I recon we can bundle pylint and all deps for under 1MB, would that be acceptable?

**Comment by DonJayamanne** [comment]
@jbooth, how about displaying a promt to install it, and then running the necessary install script in the integrated terminal. I think that would be better. I will have a chat with a few of my colleaguas and get back to you on this. also this was the original plan discussed with them.  
Thanks for your thoughts and research.

**Comment by jabooth** [comment]
@DonJayamanne That is a OK option, and an improvement from now, but I still feel like this is a poor user experience. Let me give this one last go... ;)

As an end user, I just want Python IDE-like features to work in VS Code (and I think that's true of the vast majority of your users). For most people that means syntax highlighting, linting, tab completion, refactoring, & debugging. Currently those features are provided as follows:

#### Bundled with VS Code
- Syntax highlighting (powered by Magic Python as of 1.5 if I understand correctly?)

#### DonJayamanne/python out of box (bring your own interpreter *only*)
- Tab competition (Powered by Jedi, bundled)
- Refactoring (Powered by Rope + isort, bundled)
- Debugging (wrapping the Python debugger?)

#### DonJayamanne/python + install tools in active interpreter
- Linting (powered by PyLint, etc.)

The truth is **I don't think the majority of your users know or care** that there is a whole load of discrete projects being used under the hood to create a rich Python editing experience. They are thankful that you are doing the hard work to make a tool that works for them, but it isn't at all obvious that linting is powered by one project (pylint) whilst suggestions come from a totally separate static analysis tool (Jedi). At least, it wasn't to me. To them, they just see that one feature they expect (linting) is harder to set up than the other stuff. For me, that's a bad user experience. Remember, the alternative is PyCharm, where all this stuff *just works*.

This is again why I strongly encourage that a default linting experience should be provided out of the box by bundling one linter and having it work with no configuration. Of course a more advanced user should be able to bring their own linter and set it up, but we could strive to have at least basic linting work every time a Python file is opened in VS code, which just seems like such a huge win for me. 

### Example of current friction

1. A user needs to debug a Python script they are using from someone else. They download the file to a dir, make a fresh virutalenv next to it (best practice) and pip install the deps from the requirements.txt file. This is just a quick job, no need for a whole project setup with PyCharm. Perfect job for VSCode.
2. They open the folder in VSCode, and quickly set the interpreter correctly using the new command. They now have access to everything they expect to get their work done: debugging, suggestions, refactorings...
3. ...expect they have no linting. This strikes them as an odd omission, and they google to find [that linting in particular](https://code.visualstudio.com/docs/languages/python) requires installing pylint into the active interpreter.

I think being able to get rid of that third step is a big improvement.

### How much bigger would the extension be?

To test this out, I've made a branch on my fork where I optimally [bundle the current version of pylint and all it's dependencies](https://github.com/jabooth/pythonVSCode/tree/bundle-pylint).

```
> git checkout master
> vsce package -o master.vsix
> git checkout bundle_pylint
> vsce package -o bundle_pylint.vsix
> du -h *.vsix
5.8M	master.vsix
6.2M	bundle_pylint.vsix
```
So the download size increase to the end user is **400KB**.

### Pros and Cons
Sorry this has gone a bit long, but to wrap up:

#### Pros
+ Big improvement to the default out of box experience
+ Doesn't compromise on the ability to customise the linting per-interpreter/workspace if desired
+ Can control the default linter to provide a good experience (e.g. keep up to date with pylint changes, ensure users have a strong default)
+ It's what is already done for all other IDE tools (jedi/isort/rope). If we shouldn't bundle pylint, why bundle these?

#### Cons
- Adds some more code to this repo (longer clone times etc)
- Adds maintenance burden to bump pylint from time to time
- 400KB larger download

Unless there are other cons I'm missing, I really feel strongly that it's well worth bundling a default linter for the benefits it will bring to the thousands of Python devs using the extension.

**Comment by DonJayamanne** [comment]
@jabooth , in light of the recent ballooning of the extension. I believe its definitely acceptable to proceed with your suggestion of bundling pylint.

**Comment by jabooth** [comment]
@DonJayamanne fantastic, thanks for hearing me out!

I'll put a PR up when I can to integrate pylint then.

**Comment by DonJayamanne** [comment]
@jabooth , can I suggest you try something as follows:
- Place pylint folder in the pythonFiles directory
- Modify [executePythonFile](https://github.com/DonJayamanne/pythonVSCode/blob/master/src/client/common/utils.ts#L73) to add the pythonFiles directory into the current path variable
- Similar to what we have done [here](https://github.com/DonJayamanne/pythonVSCode/blob/master/src/client/common/utils.ts#L97)

FYI - There's a bug in the logic today, i'll fix it today.
Thanks
