### ISSUE TITLE
Start Python child process with PYTHONUNBUFFERED=1 instead of -u

### ISSUE THREAD

**Issue by hexchain** [DonJayamanne/pythonVSCode#256]
I'm using VSCode with buildout. To get completion support I need to change `python.pythonPath` to the python interpreter script generated by buildout (which includes paths to project eggs).

But unfortunately that script does not recognize `-u` parameter and will fail if encountered. Should we use a more generic way (i.e. set `PYTHONUNBUFFERED` environment variable) to achieve the same result?

**Comment by DonJayamanne** [comment]
Agreed, will include your suggestion in the next build. 
You can make this change temporarily at your end by altering the generated javascript code found in the extension directory.

Thanks for the suggestion.
