### ISSUE TITLE
How to configure for web application debugging?

### ISSUE THREAD

**Issue by mzabuawala** [DonJayamanne/pythonVSCode#259]
Hi,

First of all thank you for such a great extension.

I'm learning Flask and I need help in configuration, How do I configure visual studio code to debug Flask web application ?

For example when I set debugger on view function it should allow me to step through that function when we hit that view route in browser.

I tried all of the debug options like python, python console, wattson, attach but none of them worked in my case.

**Comment by DonJayamanne** [comment]
@mzabuawala , apologies for the delay. I will update the wiki with some instructions and let you know asap when done.

**Comment by DonJayamanne** [comment]
@mzabuawala , please check out the instructions in the [following page](https://github.com/DonJayamanne/pythonVSCode/wiki/Debugging:-Flask).
If you have any trouble let me me.

**Comment by mzabuawala** [comment]
Thanks a lot Don, Works like a charm :)

**Comment by csyleos** [comment]
Hi,

Thanks for this excellent plugin for vscode. 

This does work when we disable the *debug=True*. Dow you know why it dosen't when flask debugging is enabled? because when disabled it dosen't reload the code on changes automatically. You have to restart the debugger every time. or is there another solution for auto reloading on code changes

thank you in advance, Chris.

**Comment by DonJayamanne** [comment]
@csyleos , unfortunately when debug=True, flask creates a separate python process to start the web application that cannot be tracked by the debugger.

**Comment by csyleos** [comment]
@DonJayamanne thanks a lot

**Comment by csyleos** [comment]
Hi, can i ask something if its possible, is there a way that the pythonVSCode plugin can reload the debugger when it detects changes in the code of the project?

thanks in advance

**Comment by DonJayamanne** [comment]
Unfortunately no

**Comment by csyleos** [comment]
@DonJayamanne thanks for the immediate response
