### ISSUE TITLE
Run file in integrated terminal window

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#261]
Schaub Steve, 

One feature that I would like to see is the ability to launch the current Python script in the integrated terminal. This would be similar to, but independent from, the debugger “Run” mode. It would have a separate (optional) VScode configuration to specify the name of the interpreter, etc., with reasonable platform defaults. It would not require the overhead of the debugging infrastructure (i.e., no need to set up a launch.json configuration or have a directory open).
 
This feature would reduce the effort required to launch and test simple Python scripts. If you like the idea, I could work on it and submit a pull request. Let me know what you think.

**Comment by DonJayamanne** [comment]
Great suggestion.
Here's the workflow as I originally envisioned it: 
-	Right click a file (in the explorer) and select the menu option “Run in Terminal”
-	If a file is opened, go into the Command Pallet and select “Terminal: Run Python file in Terminal”  
-	Both of them do the exact same thing, i.e. they both invoke the command “python.execInTerminal” passing a Uri of a python file

The way the code would work is:
-	The command handler would receive a Uri as an argument
-	The extension would then open up a new terminal window “X”
    +	The extension would re-use this terminal for all subsequent operations
    +	As opposed to creating a new Terminal Window every time
-	The extension would then send the following text to the terminal window:
    +	_**“\<pythonPath\> \<file name\>”**_
    +	_**“pythonPath”**_ is the value from “[settings.python.pythonPath](https://github.com/DonJayamanne/pythonVSCode/blob/9d292b59f8f3cdac5f73314642af7dd04cf9b106/src/client/common/utils.ts#L39)” (stored in settings.json)
    +	_**“file name”**_ is the name of the file

FYI – Unfortunately the API to create a terminal and send text to it is not yet available (will be available in around 2-3 weeks - in the next 1.5 release).

Here’s a sample for interacting with the terminal window:
-	https://github.com/Tyriar/vscode-terminal-api-example

If your approach was different to the above, please do let me know.

> It would have a separate (optional) VScode configuration to specify the name of the interpreter, etc., with reasonable platform defaults.  

Please could you elaborate on this, hopefully with some example. I don't quite understand this.

**Comment by gandhis1** [comment]
One very important part of this feature would be the ability to send **pieces** of code to the terminal window. With Python Tools for Visual Studio, one can highlight code, press "Ctrl+E+E", and the highlighted code would execute in the terminal (IPython). Often, people will not want to execute the entire script in the terminal window.
