### ISSUE TITLE
Autocomplete For Build In Special Methods

### ISSUE THREAD

**Issue by devNaresh** [DonJayamanne/pythonVSCode#262]
I tried everything but autocomplete for build in special methods are not supported.
methods like --  \__get__, \__set__, \__getitem__, \__setitem__, \__iter__ etc. These methods not come in autocomplete. Would be great if suggestions come for these methods as well.

Use Cases Example

# Example 1

```python
class Vector:

        def __init__(self, components):
            self._components = array(self.typecode, components)

        def __iter__(self):
            return iter(self._components)

        def __str__(self):
            return str(tuple(self))

        def __len__(self):
            return len(self._components)

        def __getitem__(self, index):
            cls = type(self)
            if isinstance(index, slice):
                return cls(self._components[index])
            elif isinstance(index, numbers.Integral):
                return self._components[index]
            else:
                msg = '{.__name__} indices must be integers'
                raise TypeError(msg.format(cls))```

```
# Example 2

```python
class Quantity:
    __counter = 0

    def __init__(self):
        cls = self.__class__
        prefix = cls.__name__
        self.storage_name = "_{0}#{1}".format(prefix, cls.__counter)
        cls.__counter += 1

    def __get__(self, instance, owner):
        return getattr(instance, self.storage_name)

    def __set__(self, instance, value):
        if value > 0:
            setattr(instance, self.storage_name, value)
        else:
            raise ValueError("Value must be greater than zero")


class LineItem:
    """
    Here weight, price is storage attribute

    _Quanitity#0, _Quantity#1 is a managed Attribute

    """
    weight = Quantity()
    price = Quantity()

    def __init__(self, description, weight, price):
        self.description = description
        self.weight = weight
        self.price = price```

**Comment by DonJayamanne** [comment]
Not sure what you're talking about. But these methods are not to be used directly.
Please could you provide a use case sample for such a usage?
Closing for now.

**Comment by devNaresh** [comment]
@DonJayamanne As you have asked for some use cases i editied my issue with use cases. kindly open this issue again.

**Comment by DonJayamanne** [comment]
@devNaresh , ok now please could you let me know where you are not getting auto completion.  
- Can you write some code and show me the line number where you are not getting intellisense?  
- Can you also list the members you are expecting to see?  

I.e. at what line and column do you expect autocomplete to display a list of items & what exactly do you expect to see in this list?

**Comment by DonJayamanne** [comment]
@devNaresh closing as this kind of auto complete isn't supported.
