### ISSUE TITLE
Autocompletion doesn't work with anonymous functions

### ISSUE THREAD

**Issue by GinoHereIam** [DonJayamanne/pythonVSCode#265]
Hello,

when I declare an anonymous function with lambda, the **autocompletion** does not work anymore, like this:
`instant_print = lambda x: [print(x), sys.stdout.flush(), sys.stderr.flush()]`

but when I define a function like this it works again:

`def instant_print():
    return lambda x: [print(x), sys.stdout.flush(), sys.stderr.flush()]`

Regards
Gino

**Comment by DonJayamanne** [comment]
@GinoHereIam  Will check this out tomorrow.

**Comment by GinoHereIam** [comment]
Hey, how is it going on? Could you re-produce it?

**Comment by DonJayamanne** [comment]
@GinoHereIam , yes I've been able to replicate this. I believe this is an issue with the Jedi (autocompletion) library itself.

**Comment by GinoHereIam** [comment]
Ah, so you can't fix it? :(

**Comment by DonJayamanne** [comment]
@GinoHereIam , what version of Python are you using?

**Comment by DonJayamanne** [comment]
@GinoHereIam , I can get it to work. All you need to do is ensure you're python interpreter settings.json is pointing to the right version of python3.

Here's my change in settings.json (workspace settings):
```json
    "python.pythonPath": "/Users/donjayamanne/Python/Temp/MyEnvs/p3/bin/python",
```

If this doesn't fix it, please re-open the issue.
