### ISSUE TITLE
Sorting imports not working

### ISSUE THREAD

**Issue by jole78** [DonJayamanne/pythonVSCode#266]
When I try to sort the imports it doesn't work any more (used to work though).
Getting this error:

  File "/home/johanleino/.vscode/extensions/donjayamanne.python-0.3.21/pythonFiles/sortImports.py", line 1, in <module>
    import isort.main
  File "/home/johanleino/.vscode/extensions/donjayamanne.python-0.3.21/pythonFiles/isort/main.py", line 28, in <module>
    import setuptools
ImportError: No module named setuptools

**Comment by DonJayamanne** [comment]
@jole78 , seems to work just fine for me.
Please could you provide the following info:
- Version of the extension  
- Version of Python being used

**Comment by jole78** [comment]
0.3.21 and Python 2.7.11+
On Linux Mint

**Comment by jole78** [comment]
@DonJayamanne hey, it was just a matter of installing that missing module (e.g. sudo pip install setuptools).

Closing the issue...
