### ISSUE TITLE
autocomplete improvement: make arguments pops up right after parenthesis or comma input

### ISSUE THREAD

**Issue by mickeydonkey** [DonJayamanne/pythonVSCode#267]
Currently, After input some function name and parenthesis, One need to recall the argument's leading characters before the whole argument name pops up. It is not very useful except from avoiding extra types. 
![snip20160825_2](https://cloud.githubusercontent.com/assets/12562760/17940035/d8fdbd8c-6a5f-11e6-8df6-1cfcb2c7c1c2.png)

I hope these arguments can pop up after I input the parenthesis of  a function or after one parameter is passed and a comma was typed. In this way, One doesn't need to remember arguments of that function.

Thanks you!

**Comment by DonJayamanne** [comment]
@mickeydonkey, this should be working.
The latest version does provide the list of the parameters after you enter ```(``` or ```,```
Please could you confirm the version of VS Code and the Python Extension.
