### ISSUE TITLE
bug: docstring of a function is not rendered correctly when inputting function calls

### ISSUE THREAD

**Issue by mickeydonkey** [DonJayamanne/pythonVSCode#268]
![snip20160825_3](https://cloud.githubusercontent.com/assets/12562760/17940315/21053640-6a61-11e6-8ef3-b8f7af4cb46e.png)

**Comment by mickeydonkey** [comment]
BTW, is there any way to disable this docstring pop up? cause it's it's distracting and not very useful for familiar functions, for which, I believe, only some hint of argument names is needed.

**Comment by DonJayamanne** [comment]
@mickeydonkey , closing this as this has been identified and flagged as a fix in #183
