### ISSUE TITLE
Auto format on saving

### ISSUE THREAD

**Issue by coladou** [DonJayamanne/pythonVSCode#27]
How do you thing about this feature?
@DonJayamanne

**Comment by DonJayamanne** [comment]
Sounds good, will put it in the next release. Keep the suggestions coming.

**Comment by coladou** [comment]
Great!

**Comment by DonJayamanne** [comment]
Sorry bit this cannot be achieved at this stage due to limitations on the use, visual studio code doesn't raise any events inducing the file was saved. Hopefully this will be added in their future release

**Comment by coladou** [comment]
Golang  Reference: https://marketplace.visualstudio.com/items?itemName=lukehoban.Go

**Comment by DonJayamanne** [comment]
Oops sorry. No idea what I was on at that time. I have already written some code in the extension to run the linters when changes are saved. Sorry, I will work on this during the week.

**Comment by dlorch** [comment]
Could you alternatively have a git pre-commit hook achieve the same thing?
