### ISSUE TITLE
Disable warnings green squiggly

### ISSUE THREAD

**Issue by gbritton1** [DonJayamanne/pythonVSCode#270]
Is there a way to disable the warnings green squiggly?  I have a module where I import some classes, but don't refer to them directly.  Instead I get references by looking in vars(sys.modules[__name__]).items().  It works great but I don't want to see the green squiggles.

Is there a preference setting for that?

**Comment by DonJayamanne** [comment]
@gbritton1  Please could you upload a screen sample

**Comment by gbritton1** [comment]
![2016-08-27_7-24-23](https://cloud.githubusercontent.com/assets/12263288/18027110/49ece206-6c28-11e6-8c2e-28dbf40f9afc.png)

image uploaded

**Comment by DonJayamanne** [comment]
@gbritton1 , these green squiggly lines are linter errors displayed.
You need to configure the linter to ignore these errors.
Please hover over the green lines or view your [linter messages](https://code.visualstudio.com/docs/editor/editingevolved#_errors-warnings)
