### ISSUE TITLE
debug - run as a package

### ISSUE THREAD

**Issue by Gluriurl** [DonJayamanne/pythonVSCode#272]
I try to debug a file that needs to be run as a package in order to avoid the following error:
ValueError: Attempted relative import in non-package

I have tried to use runtimeArgs but it seems that it has not effect.
My configuration:
{
            "name": "CurrentFile",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "runtimeArgs": [
                "-m"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ],
            "exceptionHandling": { "ignore": ["copy.Error"] }
},

Thanks

**Comment by DonJayamanne** [comment]
Can you run this package/file from the command line?
If yes what are the arguments, details of the command?

**Comment by Gluriurl** [comment]
Thanks for you answer.
command:
python -m package.module_a

[package.zip](https://github.com/DonJayamanne/pythonVSCode/files/440645/package.zip)

**Comment by DonJayamanne** [comment]
@Gluriurl, this should work: 
- when you have the module_a.py file opened in your editor.
- Or you could modify your launch.json as follows:
```json
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${workspaceRoot}/package/module_a.py",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
```
