### ISSUE TITLE
Autocomplete is not working on overriding Parent class method

### ISSUE THREAD

**Issue by devNaresh** [DonJayamanne/pythonVSCode#273]
Autocomplete for overriding parent class method and build in special methods are not supported.
methods like --  \__get__, \__set__, \__getitem__, \__setitem__, \__iter__ etc. These methods not come in autocomplete. Would be great if suggestions come for these methods as well.

Use Cases Example

# Example 1

```python
class Vector:

        def __init__(self, components):
            self._components = array(self.typecode, components)

        def __iter__(self):
            return iter(self._components)

        def __str__(self):
            return str(tuple(self))

        def __len__(self):
            return len(self._components)

        def __getitem__(self, index):
            cls = type(self)
            if isinstance(index, slice):
                return cls(self._components[index])
            elif isinstance(index, numbers.Integral):
                return self._components[index]
            else:
                msg = '{.__name__} indices must be integers'
                raise TypeError(msg.format(cls))```

```
# Example 2

```python
class Quantity:
    __counter = 0

    def __init__(self):
        cls = self.__class__
        prefix = cls.__name__
        self.storage_name = "_{0}#{1}".format(prefix, cls.__counter)
        cls.__counter += 1

    def __get__(self, instance, owner):
        return getattr(instance, self.storage_name)

    def __set__(self, instance, value):
        if value > 0:
            setattr(instance, self.storage_name, value)
        else:
            raise ValueError("Value must be greater than zero")


class LineItem():
    """
    Here weight, price is storage attribute

    _Quanitity#0, _Quantity#1 is a managed Attribute

    """
    weight = Quantity()
    price = Quantity()

    def __init__(self, description, weight, price):
        self.description = description
        self.weight = weight
        self.price = price

    def subtotal(self):
        return self.weight * self.price

class Test(LineItem):

    def subtotal():
        pass```
```
In Example1 parent class is **_object_** class and Example2 parent class is **_LineItem_**. While Writing Test Class, Autocomplete suggestion not came for **_subtotal_** method and overriding icon should come on overriding method.

**Comment by DonJayamanne** [comment]
>Autocomplete suggestion not came for subtotal method
There's a bug in the code, please add the argument ```self``` to subtotal as displayed below.
```python
class Test(LineItem):

    def subtotal(self):
        self.subtotal # this works now
```
Now, when you go into the subtotal method of Test class, you will get auto complete for the parent LineItem members.

>2. overriding icon should come on overriding method.
Please could you explain this.
If you're referring to displaying the subtotal method as you're typing when you want to override it.
Then that's a new feature that you're requesting, and at this stage I wont be adding that.

**Comment by devNaresh** [comment]
@DonJayamanne  yeh i forgot to add self my mistake. But autocomplete suggestions don't come at the time of defining a method after **def** keyword( In above case at the time of defining subtotal, __get__, ___set__). 
Yes i am asking to display parent class method suggestion in child class(in above case subtotal, ___get__, ___set__) while typing.

And I am also asking to show some kind of indicator or symbol that this method is overridded method to know which method is overridden while looking at code.

**Comment by DonJayamanne** [comment]
@devNaresh , sorry but that kind of auto complete isn't supported at this stage.
thanks for clarifying.
