### ISSUE TITLE
"Caching" for autocompletion/intellisense possible?

### ISSUE THREAD

**Issue by domoson** [DonJayamanne/pythonVSCode#275]
It would be great if there was a mechanism to cache suggestions/autocompletion/...

Example:
I use a library called vtk (rather large, compiled module). If I type
```python
import vtk

vtk.<CTRL+Space>
```
it takes a few seconds to load the suggestions. Is it possible to cache these results so that the next time I type 
```python
vtk.<CTRL+Space>
```
the previous suggestions are being displayed instantaneously?

**Comment by domoson** [comment]
Just FYI: I tested this for both Python 2.7 and 3.5 and the behavior (long wait time) is about the same.

**Comment by DonJayamanne** [comment]
@domoson , it doesn't make any difference what version of python you are using. The intellisense is provided by the [Jedi library](http://jedi.jedidjah.ch/en/latest/). 
I don't think there's much that could be done in this regard, as the Jedi library has its own caching mechanism as well.
For insance if you have vtk on line 1 and we cache it.
Further down in line 100, vtk could point to some other value hence the cached info it not relevant anymore.

Such caching works well with large libraries such as pandas, numpy, etc.

**Comment by domoson** [comment]
@DonJayamanne Thanks for the reply. That makes a lot of sense actually, I haven't thought about it this way I have to admit. 

PyCharm probably uses a completely different mechanism as it manages to be much faster (not instantaneous, but faster), or it uses other kinds of optimizations. I'll think about this a bit more, meanwhile feel free to close this issue.

**Comment by DonJayamanne** [comment]
Cheers.
