### ISSUE TITLE
Re issue #270 -- closed too soon!  (green squigglies)

### ISSUE THREAD

**Issue by gbritton1** [DonJayamanne/pythonVSCode#277]
Ok, so I have this in my settings.json file:

{
    "python.pythonPath": "c:/python35/python.exe"
    ,"editor.insertSpaces": true
    ,"python.linting.enabled": false
}

Shouldn't that disable linting altogether and the green squigglies as well?

**Comment by DonJayamanne** [comment]
@gbritton1 , please feel free to re-open an issue if you feel that it was closed too early.
That way the conversation stays on the same issue.

Yes, disabling the linter should remove the green squiggles.
If you still find them, then please look at the Problems panel that displays the errors and that should tell you the source of the errors..
