### ISSUE TITLE
Import packages from current project directory

### ISSUE THREAD

**Issue by devNaresh** [DonJayamanne/pythonVSCode#278]
Actually its a Question.

When I build or debug a particular file in my Python project (which imports a user defined package),  It gives an import error.

Let us say i have  TestProject directory and below is my directory structure 

 ── sum
│   ├── sum.py
│   ├── __init__.py
├── Test
│   ├── __init__.py
│   ├── test.py

# Example

In sum.py i have sum method
```python
def sum_test(a,b):
    return a+b```

```
In **test.py** if I import **sum_test** method it gives import error that **cannot import sum**

``` python 
from sum.sum import sum_test 
```

How can I solve this problem?

**Comment by DonJayamanne** [comment]
@devNaresh , is this a general Python question or something specific to VS Code and the extension? If it is a general python question please post it on stackoverflow or similar.

**Comment by devNaresh** [comment]
@DonJayamanne it is not general python question. if i run test.py from terminal i am not getting error

**Comment by DonJayamanne** [comment]
@devNaresh, sounds like a general python question as you're running test.py from the terminal (i.e. nothing specific to the extension nor vs code).

**Comment by devNaresh** [comment]
@DonJayamanne i have one question

what is the use of below three settings.

```python
   // Whether to enable or disable unit testing using pytest.
    "python.unitTest.pyTestEnabled": true,

    // Path to pytest (py.test), you can use a custom version of pytest by modifying this setting to include the full path.
    "python.unitTest.pyTestPath": "pytest",

    // Arguments passed in. Each argument is a separate item in the array.
    "python.unitTest.pyTestArgs": ["${workspaceRoot}"]
```

How i can run tests??
I already configure tasks.json and running test through that but what is use of above line..

**Comment by DonJayamanne** [comment]
@devNaresh , unfortunately unit test is undergoing a major refactor and will be updated in the next release (September). Please refer to issues #239 & #236
