### ISSUE TITLE
[Debugger] Cursor of type psycopg2.extras.DictCursor returns None when fetching

### ISSUE THREAD

**Issue by sevetseh28** [DonJayamanne/pythonVSCode#279]
```
cur = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
cur.execute(sql_query)
row = cur.fetchone()
```

Doing that returns None even if there is one record in the query result. Tried running the exact same code and debugging it with PyCharm and I get the correct result in the row variable. 
If I create the normal cursor

```
cur = conn.cursor()
cur.execute(sql_query)
row = cur.fetchone()
```

row is not None in the VS Code debugger, so there is clearly a bug with the DictCursor type.

**Comment by DonJayamanne** [comment]
@sevetseh28 
- Please could you confirm you have configured the python interpreter correctly in settings.json and launch.json (both should point to the right interpreter)  
- Please could you past a screenshot of the issue.

**Comment by sevetseh28** [comment]
Yes. I have them correctly configured. Here you have two screenshots,:
Fetching using DictCursor:
![bug debugger fetchone](https://cloud.githubusercontent.com/assets/13895313/18225366/f5429fee-71c6-11e6-88a6-af9412bd99d6.png)

Fetching using the common Cursor:
![bug debugger 2](https://cloud.githubusercontent.com/assets/13895313/18225367/f754cf46-71c6-11e6-944e-7c7c5b03de38.png)

Take into account that the variable 'rows' is not None when debugging in PyCharm with the DictCursor type.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#64
