### ISSUE TITLE
How to specify python3 in launch.json

### ISSUE THREAD

**Issue by tstringer** [DonJayamanne/pythonVSCode#280]
I see the `pythonPath` key, but I can't seem to locate the configuration setting to modify this to point to `python3`.

I ended up doing this for now: `"pythonPath": "/usr/local/bin/python3"`

But with that being said, I'd need to set this for all new python projects.  Where is the global configuration setting for this?

Thank you in advance! 😄  And awesome extension! Love it! ❤️

**Comment by DonJayamanne** [comment]
@tstringer , launch.json is something that will have to be defined for each workspace/project.
That being said, there's a way to get this working.
The following suggestion assumes that all of your projects will always use the interpreter defined in ```/usr/local/bin/python3```

- Go into the Preferences -> User Settings menu option  
- In the settings.json file configure the python path as follows:  
Note: This is the same as configuring the path in your workspace settings (settings.json) file.  
```json
"python.pythonPath" : "/usr/local/bin/python3"
```
- Open your launch.json file and set the path as follows:  
This will ensure that launch.json will reference the ```python.pythonPath``` setting from your settings file. 
```json
"pythonPath": "${config.python.pythonPath}",
```
- Finally the above setting in launch.json is the default value, i.e. when ever launch.json is created, you don't have to change anything.  


More info on configuring the paths can be found here: 
https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version

**Comment by tstringer** [comment]
That worked, thanks! 👍  😄
