### ISSUE TITLE
Intellisense for 3rd party packages

### ISSUE THREAD

**Issue by tstringer** [DonJayamanne/pythonVSCode#281]
I'm using `python3`, and I've done the following for pull in a 3rd party package: `pip3 install gitpython`.

In the editor I `import git`, and the module is working just fine I'm just not getting any intellisense for this package.

Is this currently supported?  Thanks in advance! 😄

**Comment by domoson** [comment]
Does this not work? https://github.com/DonJayamanne/pythonVSCode/wiki/Autocomplete-Intellisense

**Comment by DonJayamanne** [comment]
@tstringer , this should work.
Please could you ensure the python.pythonPath setting in settings.json points to the right python interpreter (the one in which you have git installed).

Please check the following troubleshooting guide - https://github.com/DonJayamanne/pythonVSCode/wiki/Troubleshooting-Intellisense-Autocompletion#1-intellisenseautocompletion-not-working-for-custom-modules

**Comment by DonJayamanne** [comment]
@tstringer , I have managed to get this working by following the instructions outlined above.
Closing this, unless you have any other issues. 
Please re-open if you are still unable to resolve this - as indicated it is merely a configuration issue.

**Comment by tstringer** [comment]
Thanks fixed it, thanks! 👍  😄
