### ISSUE TITLE
Incomplete/incorrect autocomplete for pygame packages.

### ISSUE THREAD

**Issue by chrahunt** [DonJayamanne/pythonVSCode#284]
You can see from the image here

![example showing incorrect type MissingModule determined for pygame.draw](https://cloud.githubusercontent.com/assets/2312275/18186703/375d2972-7072-11e6-985a-e9a26c21932c.png)

that the type of `pygame.draw` is being determined incorrectly. Further, available members are not being populated:

![example showing autocomplete options with info, name, reason, which are not typical members of pygame.draw](https://cloud.githubusercontent.com/assets/2312275/18186714/4d224ada-7072-11e6-8b06-60ef47882fe2.png)

Compare the available autocompletions to:

![output of help(pygame.draw) in the Python console](https://cloud.githubusercontent.com/assets/2312275/18186721/5d285cda-7072-11e6-99b9-8edd56c33d60.png)

I also tried this with `display` and it had the same result.

I did a little investigating. `draw.__file__` gives 'C:\\Users\\Christopher\\AppData\\Local\\Programs\\Python\\Python35\\lib\\site-packages\\pygame\\draw.cp35-win_amd64.pyd', so it is a shared library/dll. Inspection of `pygame\\__init__.py` shows that a [`ModuleMissing` class](https://bitbucket.org/pygame/pygame/src/a9c9f5bf17445dfc8f7a85b9c5222dbcb3ece3bb/lib/__init__.py?at=default&fileviewer=file-view-default#__init__.py-80) is defined and `pygame.draw` isn't directly imported at the top level, rather:

```python
try:
    import pygame.draw
except (ImportError, IOError):
    draw = MissingModule("draw", geterror(), 1)
```

from [here](https://bitbucket.org/pygame/pygame/src/a9c9f5bf17445dfc8f7a85b9c5222dbcb3ece3bb/lib/__init__.py?at=default&fileviewer=file-view-default#__init__.py-169).

So it looks like that may be confusing the autocomplete.

For what it's worth it looks like this is working correctly in VS 2015 Community edition with PTVS 2.2.5:
![showing autocomplete options from PTVS](https://cloud.githubusercontent.com/assets/2312275/18186885/69faaf52-7073-11e6-8f69-622a21debf70.png)

Just for completeness: VSCode 1.4.0, Python extension 0.3.21, fresh install of Python 3.5.2 followed by `pip install pygame`. The version of Python used is on my PATH and `pygame` was installed using pip. Just to be sure, I tried adding the relevant Python executable to `python.pythonPath`  and adding the directory for `pygame` to `python.autoComplete.extraPaths` but it did not make a difference.

Let me know if I can provide any more information.

**Comment by DonJayamanne** [comment]
@chrahunt , unfortunately this is a problem with the [Jedi library](http://jedi.jedidjah.ch/en/latest/docs/features.html). 
For some reason the Jedi library doesn't list these members you have mentioned.
I don't believe Jedi will work here, as Jedi doesn't execute the code to provide autocomplete/list members, instead it merely statically evaluates the code.

So I guess, at this stage its looking like it won't work.

**Comment by chrahunt** [comment]
Thanks, I filed an upstream issue. It looks like jedi does not have a problem with providing completion on the C extension, but on the presence of an assignment in the `except` block above. I will update when I hear back on the other issue if this is something that can be resolved in jedi and then pulled in if/when the fix reaches stable.
