### ISSUE TITLE
arguments prompts or docstring has display issue

### ISSUE THREAD

**Issue by shelper** [DonJayamanne/pythonVSCode#285]
I am using Mac version vs code with this tool version 0.3.21
and i found the arguments prompt does not wrap the line correctly, 
for standard lib, it seems ok, but for numpy, e.g., it cannot display the docstring correctly.

the figure below shows exactly what i mean. 
<img width="550" alt="screen shot 2016-09-02 at 7 59 16 pm" src="https://cloud.githubusercontent.com/assets/546163/18221193/f7bdd042-7147-11e6-8478-3a059551c11d.png">

and if i move the cursor to the function, i got a peek of the docstring, which is cutoff from the top, i can only see the whole docstring by moving the function line to the bottom of the screen. the figures below explain what i mean:
with cutoff 
<img width="560" alt="screen shot 2016-09-02 at 8 21 56 pm" src="https://cloud.githubusercontent.com/assets/546163/18221445/57c4c7c2-714b-11e6-8193-652a4651a97e.png">

move the line down to show the whole docstring prompt:
<img width="543" alt="screen shot 2016-09-02 at 8 22 31 pm" src="https://cloud.githubusercontent.com/assets/546163/18221454/77f1dbfc-714b-11e6-8961-41dbbaf8ac2b.png">

**Comment by DonJayamanne** [comment]
Similar to #268, and covered in #183
