### ISSUE TITLE
go to definition and autocomplete not working when using from <module> import *

### ISSUE THREAD

**Issue by evan-wehi** [DonJayamanne/pythonVSCode#286]
Sorry if I've missed this in the documentation:

When importing using `from` as per the following example I cannot "go to the definition" of `pipeline_run()`. Nor do I get autocompletion. 
```
from ruffus import *
pipeline_run()
```

The following works as I would expect:
```
import ruffus
ruffus.pipeline_run()
```

The module was installed using a standard installer and is in the system site-packages library. Adding the following to user settings does not help.
```
    "python.autoComplete.extraPaths": [
        "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ruffus/"
    ]
```

A bit of testing reveals that the standard module `calendar` shows the same problem but `sys` does not.

Thanks,
Evan.

**Comment by DonJayamanne** [comment]
@evan-wehi , unfortunately wildcard imports aren't support for autocomplete and intellisense.
This is due to a limitation in the [Jedi library](http://jedi.jedidjah.ch/en/latest/) used.

**Comment by arpruss** [comment]
Is it a bug in the Jedi library? Should it be reported to them?

At some level in the code, wildcard imports work. For instance, if you have three python files: file1.py, file2.py and file3.py, and file2.py says `from file1 import *` while file3.py says `import file2`, then autocomplete in file3.py picks up all wildcard imported stuff, but of course only if you prefix with file2. So the autocomplete code must have parsed the `from file1 import*` correctly. BUT when you're in file2.py, you don't get to use autocomplete on the symbols from file1.py.

**Comment by arpruss** [comment]
I think it may be time to reopen this, since Atom's autocomplete-python works fine with wildcard import in Jedi mode. So perhaps the Jedi library has since been updated to allow for wildcard import?
