### ISSUE TITLE
rename symbol is not working in 0.3.21

### ISSUE THREAD

**Issue by johnnytorres** [DonJayamanne/pythonVSCode#288]
it never finish renaming a variable (the progress bar in top keeps showing)
i'm just trying to rename the parameter 'type' as 'usertype' in the following class:
class TwitterNode:
    def __init__(type(self, screen_name, type)):
        self.screen_name = screen_name
        self.type = type

**Comment by DonJayamanne** [comment]
@johnnytorres , I'm getting a syntax error with your code, indicating the syntax is incorrect.
You should see this error message if you have turned on your linter as well.

**Comment by johnnytorres** [comment]
Sorry, I didn't notice the error in that case but in the following case it seems the error occurs:

items = {'u' : 1}

for u, val in items:
    u['u'] = u['u'] + 1

try renaming variable u  doesn't work
