### ISSUE TITLE
Autocomplete support via type hint using 'assert isinstance()' and/or 'if False: var = type'

### ISSUE THREAD

**Issue by johncruise** [DonJayamanne/pythonVSCode#289]
**NOTE:** This is not the same as PEP 484 which only applies to 3.x

Could you add same autocomplete support via type hinting implemented in PTVS via code below:

```python
assert isinstance(myvar, thetype)
# or
if False:
    myvar = thetype()
# or
if False:
    assert isinstance(myvar, thetype)
    myvar = thetype()
```

**Comment by Cologler** [comment]
Type hint already work for `assert isinstance()`.
And, what is `if False`?

**Comment by johncruise** [comment]
``if False`` is just a no-op code that other editors uses to type hint.

Going back to ``assert isinstance()``: I guess with my first check, there might be something going on with my environment.  It was not working when I tried it.  However, after a reboot and some vscode + python extension updates, it kind-of works.  However, the implementation is a little bit incomplete.

inline assert isinstance() works.
```python
assert isinstance(myvar, customclass)
customclass. # after pressing '.', function list shows up
```
functions returning a type-hinted value "within the same module" works.
```python
import copy

def getsomeobj(somevar):
    assert isinstance(somevar, someclass)
    ret = somevar.getsomeobj()
    assert isinstance(ret, someotherclass)
    return ret

def otherfoo(somevar):
    theobj = getsomeobj(somevar)
    theobj.  # hitting '.' shows up the function list again
```

However, splitting those functions in to 2 modules, it is a hit-and-miss.  At times it works, at times it doesn't.  I'm hoping to get more good sample code for you to emulate later.  However, the autocomplete works reliably with Visual Studio Community with PTVS.

**Comment by DonJayamanne** [comment]
Closing as auto complete is made possible using the Jedi library. 
Please add suggestions into that repo (jedi.jedidjah.ch/en/latest/)
