### ISSUE TITLE
How do I set the correct path to appengine libs?

### ISSUE THREAD

**Issue by mayankbhagya** [DonJayamanne/pythonVSCode#29]
I can't find a field in launch.json where I can specify the environment in which the process runs.

**Comment by DonJayamanne** [comment]
Sorry for the delay, been away the last week. You can configure the path to the executable as per the documentation here: https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Version.

Apart from that, virtual environments are currently not supported. So, for now, please provide the fully qualified path on the launch.json. 
Virtual environment will be supported soon, someone has been kind enough to do the work. I just need to extend that for the debugger as well.

**Comment by mayankbhagya** [comment]
Thanks Don.

I need to set certain environment variables for including app engine libs, e.g. PYTHONPATH.
How do you suggest I can fix that using a fully qualified path in launch.json?

**Comment by DonJayamanne** [comment]
Hi, unfortunately this isn't supported at this stage. I will look into adding this.

**Comment by mayankbhagya** [comment]
Thanks!

**Comment by DonJayamanne** [comment]
Hopefully this will be added in the next release, either later today or tomorrow.

**Comment by mayankbhagya** [comment]
That would be great Don!

-mayank

**Comment by DonJayamanne** [comment]
A new version has been released where you can set the env variable in the launch settings. I will update the docs later next week.

**Comment by lxcid** [comment]
Sorry just to check, is the virtual environment supported yet? Would love to have this.

**Comment by DonJayamanne** [comment]
Virtual env in currently in development (progress)

**Comment by lxcid** [comment]
Thanks! :+1: looking forward to it!

**Comment by DonJayamanne** [comment]
Closing this as this was originally for environment variables, FYI - support for virtual env is on the way. Not forgotten.
