### ISSUE TITLE
"in" keyword needs to be highlighted

### ISSUE THREAD

**Issue by srinath29** [DonJayamanne/pythonVSCode#290]
Hi
When I am doing
`for file in os.scandir("."):`
'in' is not getting highlighted. 
Using the vscode 1.4 and just installed the extension from marketplace.

**Comment by DonJayamanne** [comment]
@srinath29 , syntax highlighting is not part of the extension.
Please try installing Magic Python or please wait for the next release of VS Code (around late this week or next week).

**Comment by srinath29** [comment]
thank you :)
