### ISSUE TITLE
Autocomplete doesn't work when the cursor within C extension:

### ISSUE THREAD

**Issue by ypyf** [DonJayamanne/pythonVSCode#291]
```python
import os
import mx # module written in C
```

When I type
```python
mx.a_method(os.
```
Now, the autocomplete loads nothing.

**Comment by inter1965** [comment]
the same with built-in python module datetime, the autocomplete loads nothing either.

**Comment by gandhis1** [comment]
Make sure that the module is in one of the search paths specified in your user or workspace JSON settings. What this means is that you cannot add a path to your system environment variables (PATH) and have the module auto-complete work. 

Second, **and this is the actual issue**, auto-complete requires one to type the module name,  ".", and then press CTRL + Space. If you do not do this, the auto-complete will not automatically come up. Plus, it seems like every time you do this, it takes a while to load all the symbols from the PYD/DLL or whatever binary.

I do not know whether this extension automatically adds PYTHONPATH environment variable paths to the autocomplete search paths. Ideally, the extension would check all system paths, including PATH and PYTHONPATH, and then also pull the symbols from imported C modules.

**Comment by DonJayamanne** [comment]
@ypyf 
- What's the OS? 
- What's the version of Python you are using? 
- Where have you installed the mx package? 
- Please could you upload your settings.json file? Or please confirm you have selected the right interpreter?

I've tested this on OSX with Python 2.7 and insalled using ```pip install egenix-mx-base``` [install instructions here](http://www.egenix.com/products/python/mxBase/#Installation)

**Having done the above, it works as expected.**

**Comment by ypyf** [comment]
1. What's the OS?
Microsoft Windows [Version 6.1.7601].

2. What's the version of Python you are using?
Python 2.7.12.

3. Where have you installed the mx package?
The "mx" is a very simple C extension I wrote using pybind11. It contains a method that  just takes a string parameter and print it out.

4. Please could you upload your settings.json file? Or please confirm you have selected the right interpreter?
I'm pretty sure I have the right interpreter, because exactly one python installed on my computer.

the following is settings.json:
{
    "editor.fontSize": 16,
    "editor.mouseWheelZoom": true,
    "editor.formatOnType": false,
    "editor.renderIndentGuides": true,

    "files.eol": "\n",
    "files.trimTrailingWhitespace": true,

    "git.autofetch": false,
    "git.confirmSync": true,

    "python.linting.enabled": true,
    "python.linting.pylintEnabled": false,
    "python.linting.pep8Enabled": true,
    "python.formatting.provider": "autopep8"
}

**Comment by DonJayamanne** [comment]
@ypyf 
- Where have you installed the mx package?  
For intellisense to pick this up, the python interpretter must be able to pick this up along with the python code in the extension?
So, that's why i've asked whether this has been installed a package.

So the problem is that you haven't configured this properly.

1. Where is this module? (i.e. in relation to your python file, where is this module located?) 
2. Can you configure the autocompete path as per the documentation:
    + https://github.com/DonJayamanne/pythonVSCode/wiki/Autocomplete-Intellisense

**Comment by DonJayamanne** [comment]
@ypyf any progress on this.
Please re-open if the problem persists.
