### ISSUE TITLE
variable expression watch issue

### ISSUE THREAD

**Issue by nNullSpace** [DonJayamanne/pythonVSCode#292]
My environment:
Windows 8 64bits
Python 3.5.1 64bits
visual studio note 1.4.0
Python for VSCode 0.2.3

Description of the issue:
(as image links)
 
step1 ( http://i.imgur.com/MdIn6Og.png )
I set a sequence to change value of "a1" and watch it on the left panel. Expression "a1*2" is the key of this mail.
 
step2 ( http://i.imgur.com/hmCiI4S.png )
a1 was set to 1, but expression "a1*2" did not work.
 
step3 ( http://i.imgur.com/94KkHcl.png )
Double click the expression "a1*2" -> enter edit mode -> press [enter] -> the expression shows correct value.
 
 
According to the experience using other IDE, I think the expression should change with code steps automatically.

**Comment by DonJayamanne** [comment]
@nNullSpace , you can upload images directly into github issues (there's a link just blow the textarea)

**Step1**
![mdin6og](https://cloud.githubusercontent.com/assets/1948812/18330737/ad1b85de-759d-11e6-95d0-62b63bfc5cda.png)

**Step2**
![hmcii4s](https://cloud.githubusercontent.com/assets/1948812/18330751/be667330-759d-11e6-9aa2-1d75e6664b13.png)

**Step3**
![94kkhcl](https://cloud.githubusercontent.com/assets/1948812/18330754/c47620e0-759d-11e6-88b0-6a436df20e51.png)

**Comment by nNullSpace** [comment]
Thank you Don.
Sorry for that I am not familiar with github, this is my very first time to use this.
You are so kind^^

**Comment by DonJayamanne** [comment]
@nNullSpace , fixed, will be in the next build

**Comment by nNullSpace** [comment]
It works! Thank you , Don.

**Comment by DonJayamanne** [comment]
Yay
