### ISSUE TITLE
broken docstring encoding

### ISSUE THREAD

**Issue by zaz600** [DonJayamanne/pythonVSCode#293]
hi. 
docstrings that was written in russian (file encoding utf-8) displayed as scribbles. it is impossible to read them :

![image](https://cloud.githubusercontent.com/assets/1171520/18369604/83a2dc2e-762f-11e6-8eaf-9789a59d0bd7.png)

![image](https://cloud.githubusercontent.com/assets/1171520/18369730/31214b38-7630-11e6-95b5-108e3bbd2f82.png)

vscode 1.5.1
vscpython 0.3.21
python 3.5.1

**Comment by DonJayamanne** [comment]
@zaz600 , I've tested this at my end and seems to be ok.
- What OS are you are using? 
- Are you experiencing this with all files/projects? Or is it scoped to one file/project?
- Please could you update both VS Code as well as the extension to the latest versions and check this out?

Here's the code I've used:
```python
def showMessage():
    """
    Кюм ут жэмпэр пошжим льаборэж, коммюны янтэрэсщэт нам ед, декта игнота ныморэ жят эи. 
    Шэа декам экшырки эи, эи зыд эррэм докэндё, векж факэтэ пэрчыквюэрёж ку.
    """
    print('1234')
    
showMessage()
```

**Comment by zaz600** [comment]
the problem presents if i do ctrl-mouse_over on imported function

same module. ok
<img width="463" alt="screenshot_1" src="https://cloud.githubusercontent.com/assets/1171520/18886376/4a2a3c30-84f8-11e6-9a40-c6ae97795437.png">

imported module. broken encoding
<img width="598" alt="screenshot_2" src="https://cloud.githubusercontent.com/assets/1171520/18886436/898d0bd2-84f8-11e6-9bc6-a650c2b1f5de.png">

lib
<img width="419" alt="screenshot_3" src="https://cloud.githubusercontent.com/assets/1171520/18886460/a5e68e34-84f8-11e6-91a6-eaec6d82c10d.png">

src folder
[test.zip](https://github.com/DonJayamanne/pythonVSCode/files/496377/test.zip)

**Comment by zaz600** [comment]
sorry. i installed updates to vscode (1.5.3) and vscpython (0.3.24) and now it's work if src file contains `# -*- coding: UTF-8 -*-`
if this line missing btw file has utf-8 encoding docstrings that was written in russian displayed as scribbles

**Comment by DonJayamanne** [comment]
@zaz600 , I've been able to replicate this.
Opening the lib.py file and hovering over the libfunc function fixes it.

**Comment by DonJayamanne** [comment]
@zaz600 , @guhuajun, @IgorNovozhilov (including others as well, as they too have had encoding issues).
The problem or requirement of the Jedi library (used for intelliense) is that the encoding be specified on the file header.
I.e. including ```# -*- coding: UTF-8 -*-``` fixes this and this is a requirement of jedi library as seen [here](https://github.com/davidhalter/jedi/blob/master/jedi/common.py#L127)

I'll update the wiki (documentation) with this information.
I'll see if we can make a change upstream to resolve this.

**Comment by DonJayamanne** [comment]
@

**Comment by DonJayamanne** [comment]
@zaz600 I believe this can be fixed, just need some time to get this tested thoroughly.
