### ISSUE TITLE
Code snippet for main enhencement

### ISSUE THREAD

**Issue by goowell** [DonJayamanne/pythonVSCode#294]
Code snippet for main function doesn't work if you just input "if(main)" then hit tab key:
```python
def main():
    pass

if __name__ == '__main__':
    sys.exit(int(main() or 0))
```

There is an error `"NameError: name 'sys' is not defined"` if you run it directly.
I suggest add one more line code 
`import sys` 
before 
`sys.exit(int(main() or 0))`

The finally code should be:
```python
def main():
    pass

if __name__ == '__main__':
    import sys
    sys.exit(int(main() or 0))
```

**Comment by DonJayamanne** [comment]
Will release in the next build. Released a new version just a minute ago

**Comment by DonJayamanne** [comment]
@goowell , and thanks.

**Comment by goowell** [comment]
thank you.
