### ISSUE TITLE
extension package size has increased over 4x since 0.3.21

### ISSUE THREAD

**Issue by jabooth** [DonJayamanne/pythonVSCode#296]
In researching the feasibility of [bundling pylint with the extension](https://github.com/DonJayamanne/pythonVSCode/issues/255#issuecomment-245846458) I discovered that the extension size has ballooned by a factor of nearly 5 in the last few releases:

```
> git checkout 0.3.21
> vsce package
> git checkout 0.3.22
> vsce package
> git checkout master
> vsce package -o python-master.vsix
> du -h *.vsix
```
```
1.3M	python-0.3.21.vsix
4.6M	python-0.3.22.vsix
5.8M	python-master.vsix
```
That's all from the addition of the image folder contents I guess. Does seem a little wasteful to ship these images that are 3x larger than the actual code itself..don't know if it could be avoided?

**Comment by DonJayamanne** [comment]
@jabooth What??!? Crap, I thought the image folder were excluded from the build. Damn  it. 
Will check when I get home. Damn. Thanks for the pointer

**Comment by DonJayamanne** [comment]
@jabooth , fixed, thanks a lot.
