### ISSUE TITLE
[Feature Reques] more info in tooltip

### ISSUE THREAD

**Issue by Cologler** [DonJayamanne/pythonVSCode#297]
Since jedi already know `_doc` is `dict` type, is possible to let tooltip contain more info?
Something like `self._doc : dict` ?

![picpick-20160909-165744-001](https://cloud.githubusercontent.com/assets/10906962/18381610/98cab434-76af-11e6-92ed-fbf1e6875520.png)

**Comment by DonJayamanne** [comment]
@Cologler , sorry, but I don't quite understand the request.

**Comment by Cologler** [comment]
@DonJayamanne Updated.  o(T _ T)o.....

**Comment by DonJayamanne** [comment]
Closing as the information displayed relies on the information provided by the jedi library.

**Comment by Cologler** [comment]
@DonJayamanne 
in `hoverProvider.ts`, I found `var txt = definition.description || definition.text;`.
Could we replace `definition.text` to something like `definition.text + ":" + definition.pythonType` (not vscode type) ?

**Comment by DonJayamanne** [comment]
Makes sense, but the question is the UX (cuz some places definition.description works better specially if a docstring is present).

**Comment by Cologler** [comment]
Agree :)

**Comment by DonJayamanne** [comment]
Closing as I don't see much value in adding this, also there haven't been too many up votes on this (requesting for this).
