### ISSUE TITLE
Cannot step into library function

### ISSUE THREAD

**Issue by ruoyu0088** [DonJayamanne/pythonVSCode#299]
For example I add break point at line 2 of following code:

```
from matplotlib import pyplot as plt
fig, ax = plt.subplots()
```
and click step into icon in the Debug toolbar,  the current  point doesn't jump to the source code of `subplots()`, but to the next line.

Versions:

* VS Code Version 1.5.1
* Python Extension 0.3.22

I confirmed this on both Windows 10 and Ubuntu.

**Comment by DonJayamanne** [comment]
@ruoyu0088 , apologies for not documenting this.
Here you go (updated the wiki):
    + [Debug Library Functions](https://github.com/DonJayamanne/pythonVSCode/wiki/Debug-Library-Functions)

**Comment by lampwins** [comment]
@DonJayamanne Please update this link to point to the updated docs location.

**Comment by DonJayamanne** [comment]
All work on this extension is now done in the Microsoft repo and official docs can be found [here](https://code.visualstudio.com/docs/languages/python)
