### ISSUE TITLE
[BUG] import package without __init__.py

### ISSUE THREAD

**Issue by Cologler** [DonJayamanne/pythonVSCode#300]
I make a package in env var in `PYTHONPATH`.
if sony_sfo do not contains a `__init__.py` file, it will display a error (and lose auto-completion):
![picpick-20160910-172541-001](https://cloud.githubusercontent.com/assets/10906962/18409526/cfd91a5c-777b-11e6-8882-d68a340dc964.png)
After add a empty `__init__.py`, everything ok.
Since python support import package without `__init__.py`, I think this is a bug.

**Comment by DonJayamanne** [comment]
@cologler, what liner are you using? This error is returned from the linter such pylint, or the  like. So really this isn't an error with the extension, either your code or the linter you are using. From the sounds of it, it is the linter.

**Comment by Cologler** [comment]
@DonJayamanne So this is jedi's problem? I don't care the linter, but auto-completion should work with this.

**Comment by Cologler** [comment]
And I cannot navigate to definition (F12).

**Comment by DonJayamanne** [comment]
Apologies for that.

**Comment by DonJayamanne** [comment]
@cologler What is the vale of PYTHONPATH and how have your created this package, please could you provide some sample code for me to get a better idea. Also weekday is the linter error message. It is possible, that jedi can't pick it.

**Comment by Cologler** [comment]
I added a path `D:\Projects\pylibs` into my `PYTHONPATH`.
Here is my package directory:
![picpick-20160910-203858-001](https://cloud.githubusercontent.com/assets/10906962/18410473/9aa7aa36-7796-11e6-9760-16bfdc588bea.png)
After add a empty file `__init__.py`, now it work.

**Comment by gandhis1** [comment]
Cologler, it would probably be easier to investigate this if you provided some actual files + folder structure. If someone else can replicate the issue on their computer, they can then debug it.

**Comment by Cologler** [comment]
@gandhis1 
project can found here
https://github.com/Jasily/py.dataformat.sfo

**Comment by DonJayamanne** [comment]
Yes, this isn't something that's supported by the extension. This is something that would need to be supported by the Jedi library.
For it to work the __init__.py is necessary. I believe you are after something like namespace packages or similar. Either way, this isn't any issue with the extension.
