### ISSUE TITLE
Remote debugger - When stop on a breakpoint error: Source \Unknown Source is not available.

### ISSUE THREAD

**Issue by mulyoved** [DonJayamanne/pythonVSCode#302]
When debugger stop on a breakpoint does not show the right line of the code and instead show error:
"Source \Unknown Source is not available."

**Env:**
Code 1.5.1 run on Windows 7 
Remote Debug Python 2.7 run inside docker container
ptvsd 2.2.0
Ext version 0.3.22

For a short while, I got it working with an old version of the ext, I think 0.3.20 then after the upgrade I get the above error. unfortunately cannot seem to be able to install old versions of the ext to confirm.

launch.json paths configured correctly I think as I got it to work in the previous version and in any case, the error says \Unknown and not any of my files.

code
<details>
```
import ptvsd
ptvsd.enable_attach("ai", address = ('0.0.0.0', 8889))
ptvsd.wait_for_attach()
ptvsd.break_into_debugger()

import time

for i in xrange(10000):
    time.sleep(1)
    if i % 100 == 0:
        print i 

```
</details>

![9-11-2016 7-55-42 pm](https://cloud.githubusercontent.com/assets/2309907/18419009/533e5a4a-785a-11e6-904a-b200d9eeaf4e.png)

**Comment by DonJayamanne** [comment]
@mulyoved , please could you upload you launch.json files.
A change was introduced in the latest release to fix another issue related to remote debugging and resolving of paths, and that has obviously introduced another issue.
I can release a new fix by tomorrow or the day after.

**Comment by DonJayamanne** [comment]
Fixed in https://github.com/DonJayamanne/pythonVSCode/commit/2828ce27122a1419301a191edbe78f1a671334f3 (re-introduced previous logic with validation of path, else falls back to new method)
