### ISSUE TITLE
Virtual Environment pythonPath Old Settings Conflict

### ISSUE THREAD

**Issue by akras-apixio** [DonJayamanne/pythonVSCode#310]
Please feel free to close this as soon as you read this. 

I had an issue where I previously have configured python.pythonPath in my launch.json and it used to work, but recent update of vscode and python plugin broke it.

The only way I was able to resolve it was by:

1. Removing the .vscode folder
2. Following instructions from [https://github.com/DonJayamanne/pythonVSCode/wiki/Miscellaneous#select-an-interpreter](https://github.com/DonJayamanne/pythonVSCode/wiki/Miscellaneous#select-an-interpreter) and manually adding it to my settings.json file.

**Comment by DonJayamanne** [comment]
@akras-apixio 
What do you mean by broke it?
>but recent update of vscode and python plugin broke it.

**Comment by akras-apixio** [comment]
I am using Django, so the error was:

```
Traceback (most recent call last):
  File "/Users/akras/apixio/hcc-application/manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
```

Which means it was not loading my virtual enviroment but rather was trying to run from my default python path, even though I had python.pythonPath configured in my settings.json. I also tried to remove it and re-add it in launch.json but it didn't seem to help, until I removed .vscode folder.

**Comment by DonJayamanne** [comment]
@akras-apixio , odd. Anyways, as you've got this working I'll close it.

**Comment by akras-apixio** [comment]
Yep, 100% Just wanted to mentioned it here in case somebody else will have a similar problem.

Thanks for the awesome plug-in! Allows me to stay out of an IDE for Python work.
