### ISSUE TITLE
ISSUE: auto execute python script

### ISSUE THREAD

**Issue by tienhv** [DonJayamanne/pythonVSCode#313]
Edited to make it clear:
Hi, I am using Vscode 1.5.2, with vs-python 0.3.23 and go plugins installed.
When never vscode opens a python file, it will execute the file immediately. For example, I open a python script that opens Firefox and saves html files, it starts Firefox right away to do the job. There is no terminal/console screen pops up.
At the end, I have to downgrade the plugin to 0.2.22 and the problem gone (I also tried to remove the go plugins and it didn't solve the issue).

Hope this help for future releases.

**Comment by DonJayamanne** [comment]
@tienhv , sorry but I can't understand the issue?

**Comment by tienhv** [comment]
@DonJayamanne thannk, i had edited the comment above.

**Comment by DonJayamanne** [comment]
Sorry but I still don't get the issue

**Comment by tienhv** [comment]
Thanks for your patient, it is like this:
1. Having vscode and vs-python 0.3.23 installed.
2. Using vscode to open a folder contains many python scripts.
3. Click on one of those script, the script content is shown inside editor.
4. At the same time with (3), the script is executed automatically without control of user, before he is able to do anything like editing, etc.
The expected behavior must be: a) open the script, edit the script. b) the script runs when user wants to run it. 
Thanks again,

**Comment by DonJayamanne** [comment]
That's odd, no one has reported such an issue, there's no such functionality to automatically execute any file when it opens.
If this was the case, everyone would be reporting this issue, as it is quite a serious issue.

However I will leave this issue open until I I get more information.

**Comment by tienhv** [comment]
Hi,
After checking, here are details of the errors:
- Conditions:
1. vs-python 0.3.23 installed,
2. personal preference has this line: "python.unitTest.pyTestEnabled": true
3. The python file contains a class with name starts by "Test", for example my class is "TestAffluentBudget"
Thanks,

**Comment by DonJayamanne** [comment]
@tienhv PLease could you upload the code

**Comment by DonJayamanne** [comment]
@tienhv , I've tested this at my end and the code doesn't get executed.
All that happens is tests get discovered.
Please could you upload the sample code for me to test at this end.

**Comment by tienhv** [comment]
@DonJayamanne Thank you so much! I had checked and tested at my end. This problem is too specific to my case, so it is better for you to move on another useful things. 


However, I put it here https://github.com/tienhv/problems, take time to setup, inside the repo there is vs_code_setting.txt which contains settings for vs-code. Whenever I click on any Python in test folder (of the repo), it will run Firefox immediately (on Mac). as seen in the screenshot.
 
<img width="1440" alt="screenshot 2016-09-22 11 25 11" src="https://cloud.githubusercontent.com/assets/9072983/18743906/8e8ecf30-80bb-11e6-8404-42f53c6e1f68.png">

**Comment by DonJayamanne** [comment]
@tienhv 
is this a public repo or private?
I'd like to have a look at the tests in there.

**Comment by tienhv** [comment]
@DonJayamanne It is public and free to do anything there.

**Comment by DonJayamanne** [comment]
@tienhv , thanks will look into this.

**Comment by DonJayamanne** [comment]
@tienhv , your test files seem to have more than just tests.
Ideally you shouldn't have any code that would get executed when a test file is loaded:

- [print("hellopp")](https://github.com/tienhv/problems/blob/master/test/delete_me.py#L5)  
Ideally you need to write some hooks into the pytest (http://doc.pytest.org/en/latest/fixture.html#fixtures)  
- [comm = TestSimpleCommands()](https://github.com/tienhv/problems/blob/master/test/test_google_shopping.py#L117)  
- [comm.browser_training_site("../automation")(https://github.com/tienhv/problems/blob/master/test/test_google_shopping.py#L120)  

As you can see (specially the last two examples), such code will get executed even when the test hasn't been invoked. I.e. merely loading (importing) this file will cause this code to get executed.  
I haven't checked other parts of your tests, but I'm certain you'll have similar code there, if not then the code identified above needs to be fixed.
