### ISSUE TITLE
Python code does not execute from the actual file location when selecting "Run python code in terminal"

### ISSUE THREAD

**Issue by msaadq** [DonJayamanne/pythonVSCode#314]
When running a python file from VS code using the following option:

![untitled](https://cloud.githubusercontent.com/assets/11469405/18605566/8c81c64a-7cae-11e6-8027-96fcf281cfcd.png)

The code is executed from some default location and not the location of the file:

![untitled](https://cloud.githubusercontent.com/assets/11469405/18605576/ce1e4b1e-7cae-11e6-9984-86ba1fe4965d.png)

**Comment by gandhis1** [comment]
The command is run Python file in terminal. Wherever you set your terminal startup directory to, is where it will execute. If you want to execute a Python script in the same directory, you should really set up a task to do it in tasks.json.

**Comment by msaadq** [comment]
Shouldn't there be an option to run it in the same directory out of the box, as most of work I do involves manipulating different files which are referenced relative to location of python file.

**Comment by DonJayamanne** [comment]
This feature will be available in the next release and documentation on the Wiki will be updated (code has been merged).
