### ISSUE TITLE
Intellisense does not work with custom objects identifiers

### ISSUE THREAD

**Issue by msaadq** [DonJayamanne/pythonVSCode#315]
Intellisense does work fine with basic functions and library methods, but as soon as I declare a custom variable, say numpy.array object, the intellisense stops working on it:
![image](https://cloud.githubusercontent.com/assets/11469405/18605725/765cc888-7cb3-11e6-8ff5-b1755bdbccb2.png)

However, it does work for native datatypes like list:
![untitled](https://cloud.githubusercontent.com/assets/11469405/18605740/cbc8f116-7cb3-11e6-8b0f-2d89f10393b3.png)

**Comment by gandhis1** [comment]
I propose merging this with #291. Once again, the core problem is that there's too much of a delay in the autocomplete. I think a symbol caching system is needed to address this.

**Comment by DonJayamanne** [comment]
Unfortunately this is an upstream issue, related to the Jedi library.
https://github.com/davidhalter/jedi/issues/372
