### ISSUE TITLE
The output is mess

### ISSUE THREAD

**Issue by Lynn-Lau** [DonJayamanne/pythonVSCode#319]
![default](https://cloud.githubusercontent.com/assets/15011168/18615814/bdb73d14-7de2-11e6-8083-e756421b5b75.PNG)
I dont't know what's going on here, I can type the Python code in the editor, made a right configuration , but when I build the program something goes wrong.

**Comment by gandhis1** [comment]
Give test code, and the exact steps.

**Comment by DonJayamanne** [comment]
Agreed.
Also please could you test this code in the external terminal as well. Could have something to do with encoding

**Comment by DonJayamanne** [comment]
@Lynn-Lau , have you got any updates on this?

**Comment by Lynn-Lau** [comment]
Got it, I figured it out. 
Something wrong with my path configuration, the right path should be like that `(c:/anaconda2/python)`, while my path configuration is that `c:\anaconda2\python` copy from windows directly. 

Thank you. @DonJayamanne
