### ISSUE TITLE
autocompletion for numpy on Ubuntu 15.10

### ISSUE THREAD

**Issue by Luglio** [DonJayamanne/pythonVSCode#32]
Hello. I am using a user-compiled version of python 2.7.11 on Ubuntu 15.10 x64, with the user-compiled package numpy. In the .vscode settings, I have already chosen the proper python.pythonPath.

However, while editing my codes, I find that the autocompletion for numpy seems incomplete:
when typing `import numpy` or `import numpy.linalg`, it is okay;
when typing `from numpy import linalg`, it doesn't work;
when typing `numpy.linalg.multi_dot((X, X, X))`, it doesn't work even in the brackets.
The commands above can work in the interpreter (of course, the matrices should be specified such as `X = numpy.arange(4).reshape(2, 2)`).

For your quick reference, here is the code for `numpy/linalg/__init__.py`, without comments:
```
from __future__ import division, absolute_import, print_function

from .info import __doc__

from .linalg import *

from numpy.testing import Tester
test = Tester().test
bench = Tester().test

```
and here is the head part of the file `numpy/linalg/linalg.py`:
```
from __future__ import division, absolute_import, print_function


__all__ = ['matrix_power', 'solve', 'tensorsolve', 'tensorinv', 'inv',
           'cholesky', 'eigvals', 'eigvalsh', 'pinv', 'slogdet', 'det',
           'svd', 'eig', 'eigh', 'lstsq', 'norm', 'qr', 'cond', 'matrix_rank',
           'LinAlgError', 'multi_dot']

import warnings

from numpy.core import (
    array, asarray, zeros, empty, empty_like, transpose, intc, single, double,
    csingle, cdouble, inexact, complexfloating, newaxis, ravel, all, Inf, dot,
    add, multiply, sqrt, maximum, fastCopyAndTranspose, sum, isfinite, size,
    finfo, errstate, geterrobj, longdouble, rollaxis, amin, amax, product, abs,
    broadcast, atleast_2d, intp, asanyarray, isscalar
    )
from numpy.lib import triu, asfarray
from numpy.linalg import lapack_lite, _umath_linalg
from numpy.matrixlib.defmatrix import matrix_power
from numpy.compat import asbytes
```
Thanks,
luglio

**Comment by DonJayamanne** [comment]
Hi, so from what you are telling me auto complete works only when you type the import in a specific manner. Hmmm. I will release a version later today, with done improved logging, hopefully that will show us what is going on.

**Comment by Luglio** [comment]
Hi, I just re-installed the 0.2.10 version, and am using the system-built python with the [numpy](https://github.com/numpy/numpy) package.
Now it seems there are not changes happening on the examples above.

I tried on some other commands:
In `from numpy.linalg import multi_dot`, it works well at the dot, but nothing is shown after typing `import`.
When the function `multi_dot` is imported as above, it works well to start a new line with the function, and is able to be tracked by pressing F12 to `numpy/linalg/linalg.py`.

**Comment by DonJayamanne** [comment]
Hi thanks for getting back on this. Unfortunately this is a large and complex area, besides Auto complete is enabled with the use of a separate library, you might want to make you suggestion on their repository. Sorry. Here is the link to their repo : https://github.com/davidhalter/jedi

**Comment by Luglio** [comment]
Hi, I am sorry to inform you that after the recent updates, the VSCode reports error(s) on the top while a `numpy.linalg.multi_dot((X, X, X))` command is typed letter-by-letter. If it is an upper issue, will you manage to hide the error reports? Thx.
![2016-03-26 14-12-00](https://cloud.githubusercontent.com/assets/13797847/14058488/f3f89ec4-f35c-11e5-9ff8-471b9d703081.png)
