### ISSUE TITLE
how to configure options when use "run python file in terminal". 

### ISSUE THREAD

**Issue by mickeydonkey** [DonJayamanne/pythonVSCode#321]
One can specify args while launch terminal by modifying ,`"terminal.integrated.shellArgs.osx": ["--login"]`, similarly can we add options and args for python interpreter? like `python -i /path/to/myfile.py`. I tried to add `"args": ["-i"],` to "Integrated Terminal/Console" configuration in launch.json, but it seems the wrong way.

**Comment by gandhis1** [comment]
That configuration is sort of a global configuration, which usually means Bash/cmd. 

We can create a configuration that's Python specific. In #316 I added a setting to execute the file in it's own directory (as opposed to the working folder), a setting could be added under the same python.terminal umbrella to specify arguments, e.g.:

```
    "python.terminal.launchArguments": [
        "-i",
        "-E",
    ]
```

**Comment by DonJayamanne** [comment]
Code has been merged, Next version will contain the ability to both configure the startup arguments for the interpreter when running a file in the terminal
