### ISSUE TITLE
Intellisense browser object icon not rendering

### ISSUE THREAD

**Issue by lsternlicht** [DonJayamanne/pythonVSCode#322]
Object browser icons are not rendering on a mac or windows machine. 

Here is the gif from your README:
https://raw.githubusercontent.com/DonJayamanne/pythonVSCode/master/images/general.gif

Here is a gif from what mine is showing:
https://www.dropbox.com/s/bn94z9yaweifumh/no_type_icon.gif

**Comment by gandhis1** [comment]
You know what, I'd never noticed, but I have the same issue.

**Comment by DonJayamanne** [comment]
@lsternlicht , @gandhis1 , that's interesting.
I'm using Mac for development and tested this on windows and cannot replicate this issuee.

**Comment by DonJayamanne** [comment]
@lsternlicht , @gandhis1 , I'm tempted to say that this may be an upstream issue. Will need to dig deeper.

**Comment by DonJayamanne** [comment]
Fixed, no idea how this crept in. Thanks for that pick guys.

**Comment by DonJayamanne** [comment]
@lsternlicht , @gandhis1 new release has been published with this fix
