### ISSUE TITLE
find symbol is slower than sublime text

### ISSUE THREAD

**Issue by jeffery9** [DonJayamanne/pythonVSCode#324]
VSCode Version: 1.5.2
OS Version: win10
Steps to Reproduce:

install python extension
open the same file in the same project in vscode and sublime text,
ctl+shift+o in vscode, and ctl+r in sublime text, vscode list all the symbol is slower than sublime text almost in 10 times. and vscode can not list symbol in tree structure like sublime text doing.
vscode has debug tools is better than sublime text, sublime text is faster than vscode.
any improvement ?

**Comment by DonJayamanne** [comment]
> and vscode can not list symbol in tree structure like sublime text doing. 

This would be a feature request, and something that needs to be provided by VS Code (i.e. an upstream issue).

> vscode list all the symbol is slower than sublime text 

Please could you upload a sample file that you've used for testing. I'd like to check the performance at my end. From my experience and testing the symbols are displayed fairly quickly, less than 2 seconds.

**Comment by jeffery9** [comment]
good.  can you test this file  https://github.com/odoo/odoo/blob/9.0/openerp/models.py ?

can't upload video or gif file.

**Comment by DonJayamanne** [comment]
@jeffery9 , wow, that's one large file.
Anyways I've tried that at my end and I get a response in around 2-3 seconds.
How long does it take at your end? Its difficult to look into issues when you compare it to something and say it is very slow compare to sublime text.

**Comment by jeffery9** [comment]
sublime list symbol in less than 1s, and vscode should be more than 10s.  : (

**Comment by DonJayamanne** [comment]
@jeffery9 , will look into this. Problem is that I'm using a 3rd party library [Jedi](http://jedi.jedidjah.ch/en/latest/) to get a list of all definitions and the types.

**Comment by DonJayamanne** [comment]
@jeffery9 , found an issue in the Jedi library and I believe that's what causing the delay.
The first time the response comes back in around 2 seconds, the second time you try and view the symbols it just waits indefinitely, this is because the jedi library has crashed. 
So, there are two problems - upstream and the extension isn't handling the error properly.
Thanks for reporting this.

**Comment by DonJayamanne** [comment]
@jeffery9 , fixed. Will be in the next release

**Comment by jeffery9** [comment]
the same problem, slower than sublime
