### ISSUE TITLE
[BUG?] rename the symbol name created by 'import as'

### ISSUE THREAD

**Issue by drzunny** [DonJayamanne/pythonVSCode#325]
Hi.

I want to rename function name imported from other package by using the `import as` statement, but the extension go wrong to rename **ALL** symbol appear in my project and package source code.

Here is  the example:

```python
from flask.ext.mongoengine.wtf import model_from as Func
```

If i  rename `Func` to `Func1`:

```
from flask.ext.mongoengine.wtf import Func1as Func

# "Func" is not changed, but "model_form" changed
```

not only my project,  the source codes of `flask-mongoengine` in *site-packages* are also renamed by extension.

> VSCode 1.5.2  /  Windows 7  /  Python 2.7.11 / Extension version: 0.3.24

**Comment by DonJayamanne** [comment]
@drzunny fix will be in the next release

**Comment by drzunny** [comment]
that's cool ! thanks!

**Comment by DonJayamanne** [comment]
@drzunny new release has been published
