### ISSUE TITLE
Please publish .vsix for local installation

### ISSUE THREAD

**Issue by bearslumber** [DonJayamanne/pythonVSCode#326]
Hi,

I am a newbie to visual studio code.

I am unable to get passed our works proxy.

I'd be very grateful if you could publish the .vsix so I could install the extension locally.

Otherwise please advise how I can install the extension locally.

All help greatly appreciated.

Bearslumber

**Comment by DonJayamanne** [comment]
here you go
- Download the following file
    + https://donjayamanne.gallery.vsassets.io/_apis/public/gallery/publisher/donjayamanne/extension/python/0.3.24/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage?install=true)
- Rename the downloaded Microsoft.VisualStudio.Services.VSIXPackage package's file extension to Microsoft.VisualStudio.Services.vsix.
- Run code Microsoft.VisualStudio.Services.vsix as described in the [installation instructions](https://code.visualstudio.com/docs/extensions/install-extension#_install-a-packaged-extension-vsix).
- Restart the editor.

**Comment by bearslumber** [comment]
Thanks DonJayamaanne

Much appreciated.

**Comment by mantvydasb** [comment]
Beautiful, thank you for the vsix.

**Comment by DonJayamanne** [comment]
@mantvydasb 
Please note, the above link points to an old version, you'll need to change the version number in the link to point to the latest version.

**Comment by sketchymoose** [comment]
Can confirm this works! Changed to 0.5.8 :D
