### ISSUE TITLE
Indicators of formatting progress

### ISSUE THREAD

**Issue by vasa-chi** [DonJayamanne/pythonVSCode#327]
Currently, when I start formatting through yapf or isort, there is no visual indication that it started, or finished. I believe that there should be an indicator of formatting progress, probably in the status bar.

**Comment by DonJayamanne** [comment]
@vasa-chi , how long does it take for you.
Displaying a progress or message isn't the best UX. None of the IDEs or editors do this.

**Comment by vasa-chi** [comment]
<img width="200" alt="2016-09-22 16 36 42" src="https://cloud.githubusercontent.com/assets/180167/18750185/c2d46472-80e2-11e6-99be-95672a0536e5.png">

This, for instance, is displayed in Atom with yapf and isort plugins.
I sometimes experience several seconds lag between triggering yapf and the result.

Also there is no indication that yapf succeeded or failed.

**Comment by DonJayamanne** [comment]
Ok, that makes sense now. I'll add this in the next release.

**Comment by DonJayamanne** [comment]
What atom plugin is this? I'd like to understand the ux.

**Comment by vasa-chi** [comment]
[python-isort](https://atom.io/packages/python-isort) and [python-yapf](https://atom.io/packages/python-yapf)
