### ISSUE TITLE
Option and/or default behavior to re-order linter issues in more intuitive way

### ISSUE THREAD

**Issue by gandhis1** [DonJayamanne/pythonVSCode#329]
Right now, linter issues are listed by line number. So when one clicks on the linter window, the issues look like the screenshot below.

1) Should issues be listed by priority, for instance the errors/warnings first, and then the "informational" issues? Within each issue type, it should remain sorted by line number. If not by default behavior, can there be an option available to do this?
2) When the linter window is focused, should it automatically scroll to the line number you are focused on in the editor?

(1) seems like a good idea to me, and (2) as well. 

![capture](https://cloud.githubusercontent.com/assets/21064086/18757492/221e03b4-80c2-11e6-9c23-e822f8cd54ac.PNG)

**Comment by DonJayamanne** [comment]
@gandhis1 
The linter messages are sorted by VS Code. I.e. sorting them within the extension makes no difference. I believe the logic is to sort them based on the line number and that makes sense.
