### ISSUE TITLE
Breakpoints within other files than the source file

### ISSUE THREAD

**Issue by evakili** [DonJayamanne/pythonVSCode#33]
I've a *Django* site and I want to debug it within VSCode. Only breakpoints in `manage.py` are caught and others marked as unverifiable.
Is there any way to debug codes that are broken among multiple files?

**Comment by DonJayamanne** [comment]
You can add break points to other files . That's odd. Just a suggestion to try, when starting django, wait for it to load completely then navigate to the website and then add the break points and check. This is just to check if it works. This is not how it is supposed to behave though.

**Comment by DonJayamanne** [comment]
Hi, i just tested this and I can add break points to other source files.
For instance i can debug the source file that renders the view.

**Comment by evakili** [comment]
Thank you @DonJayamanne.
I tried your suggestion but there was no success. Could you send a sample `launch.json`?

**Comment by evakili** [comment]
Here is my `launch.json`:

```json
{
    "version": "0.0.1",
    "configurations": [
        {
            "name": "Python (Django)",
            "type": "python",
            "request": "launch",
            "program": "${workspaceRoot}/my_site/manage.py",
            "pythonPath": "py.exe",
            "args": ["runserver", "8000"],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }
    ]
}
```

I use `py.exe` to launch proper Python version.

**Comment by evakili** [comment]
I found the problem:
The parameter `--noreload` should be passed to 'runserver'. Thanks for your attention.
