### ISSUE TITLE
Multiple pylintrc files

### ISSUE THREAD

**Issue by jeffgabhart** [DonJayamanne/pythonVSCode#331]
I have several python projects in the same workspace that need separate pylintrc files. I'd like to put the pylintrc file at the root of each of those projects instead of the workspace root. pylint says it will walk up the directories to find a pylintrc so that would be nice.

Relates to #146

**Comment by DonJayamanne** [comment]
@jeffgabhart , that's odd. It should work. Will look into this.

**Comment by DonJayamanne** [comment]
@jeffgabhart , unfortunately what you're asking for isn't supported.
In VS Code, the workspace root is the project. There's no concept of sub-projects.
There's only one test runner. With your setup you'd need multiple test runners (one for each project). Multiple because you'd need to configure the test runner to run on each project (i.e. each directory).

**Comment by DonJayamanne** [comment]
@jeffgabhart , based on the documentation pylint will work up the directories only under certain circumstances:
- https://docs.pylint.org/en/1.6.0/run.html#command-line-options

**Please could you confirm running pylint from command prompt, give you what you expect.**  

If this works with some configuration settings, then please configure pylint in settings.json (passing in the necessary arguments).

**Comment by jeffgabhart** [comment]
@DonJayamanne My testing confirms that running pylint from a command prompt will search up the tree (each directory contains a __init__.py) to find a pylintrc. I also tried vscode's integrated terminal, and that worked too. 
But when pylint runs on save inside vscode, it seems to only use a pylintrc in the root of the workspace.

**Comment by DonJayamanne** [comment]
You must have some  weird  setup. As  running pylint via the extension is identical to running via terminal. These is nothing special I am doing.
Please could you send your directory structure out the entire code base (hopefully zipped or on a git  repo).
Or set up a simple python sample project to replicate this.
Also what is the command line syntax you are using.

**Comment by jeffgabhart** [comment]
Here you go https://github.com/jeffgabhart/pythonVSCode-sample

The pylintrc in the root of the workspace is the default config while the ones in the sub directories have all of the rules disabled.

This command uses the pylintrc in the root
```
pylint main/src/python/sub/fib.py
```

While this one walks up the tree to find the one with disabled rules
```
cd main/src/python/sub; pylint fib.py
```

I was running the second one in my testing earlier
