### ISSUE TITLE
Debugging Nosetests

### ISSUE THREAD

**Issue by MozJon** [DonJayamanne/pythonVSCode#332]
So I have a test framework built on top of Selenium using nosetests. I've been trying everything I can to set up debugging via launch.json unfortunately when I tell it to use nosetests as the program it says nosetests doesn't exist. It absolutely does and I'd love to use VSCode and this extension to perform debugging of the tests. 

I'm very aware I may just be making a mistake somewhere

```
       {
            "name": "NoseTests",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config.python.pythonPath}",
            "program": "nosetests",
            "args": [
                "${workspaceRoot}/run_user.py",
                "-s",
                "-v",
                "-a BVT",
                "-m test_method"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }
```

**Comment by DonJayamanne** [comment]
Have you tried this:
https://github.com/DonJayamanne/pythonVSCode/wiki/Debugging-nosetests

**Comment by MozJon** [comment]
Wow So I messed that up... I half expected it to use my bash_profile. I needed to specify the full path to nosetests `/usr/local/bin/nosetests`

{
            "name": "NoseTests",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config.python.pythonPath}",
            "program": "/usr/local/bin/nosetests",
            "args": [
                "${workspaceRoot}/run_user.py",
                "-s",
                "-v",
                "-a", "BVT",
                "-m", "test_method"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }

**Comment by DonJayamanne** [comment]
Did your solution work as well? 
If it did then I'd like to update the wiki accordingly. Fyi, these are temporary solutions. My plan is to add a shortcut (codelens ) to debug a test file or method.
