### ISSUE TITLE
Automatically attach debugger to child processes (support automatic django reloads)

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#334]
Useful when debugging applications such as django, with the auto reload feature turned in.

**Comment by DonJayamanne** [comment]
@LRPalacios , @Avrong , @nnfdiogosilva, @bufke , @mmclark, @wengole, @abdelouahabb, @davehamby, @IornL, @ysfjwd , @deronnax, @LRPalacios , @goowell, @vstoykov, @thekorn, @i5on9i , @imaia, @MightyWing, @akras-apixio , @XianwuLin , @lzantal , @vanflymen , @coladou , @holyoaks, @adambrenecki, @evakili , @Botong 

Hi everyone, I have included all of you in this message as each one of you have worked on Django at one point or the other when using VS Code (hopefully you still are).
I'm planning on taking a punt at supporting django reloading when debugging django applications from VS Code.

I would appreciate it if you could share your views on this topic here.

**Comment by i5on9i** [comment]
Do you mean that the '--noreload' option of Django in launch.json is removed by default?

**Comment by DonJayamanne** [comment]
@i5on9i , yes I'm referring to --noreload option of Django for debugging.

**Comment by i5on9i** [comment]
IMO, it's better, usually I forgot to remove that option on vscode. ;)

**Comment by LRPalacios** [comment]
normally when i work a django project i run from the console the server, that way i keep the autoreload feature working, i only run it from  VS or VSCode when i really need to debug, but i am aware that when debuggin if i change the code i will need to restart the server manually, if we could have the auto reload while debuggin it would be awesome, but i can live without it.

**Comment by DonJayamanne** [comment]
@i5on9i 
>without --noreload, the debugger does not work now, does it?

No it doesn't

**Comment by DonJayamanne** [comment]
Closing for now
