### ISSUE TITLE
Debugger adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by gbritton1** [DonJayamanne/pythonVSCode#337]
Hi -- I'm getting this error anytime I try to run a Python program in code on Windows 7 or Windows 10:

"Debugger adapter process has terminated unexpectedly"

![vscode1](https://cloud.githubusercontent.com/assets/12263288/18885420/8f60aed6-84b9-11e6-97a4-255db7f63678.png)
![vscode2](https://cloud.githubusercontent.com/assets/12263288/18885419/8f5e7698-84b9-11e6-9c56-b2e4d39f2fa5.png)

What should I do?

**Comment by DonJayamanne** [comment]
@gbritton1 
- what version of Python are you using?
- Is Python in your current path? (just open the terminal window and type  ```pthon```)
- Please could you update your extension to the latest version (0.3.24) and also ensure you have the latest version of VS Code installed.
- Finally, please upload a copy of your launch.json and settings.json

**Comment by gbritton1** [comment]
- I use two Python versions, 2.7.12 and 3.5.2
- Python is not in my current path.  That's intentional, since I switch between versions frequently.
- I'd love to update the extension!  However, VSCode does not offer to do that.  Where can I get 3.24?
- I attached my settings.json and launch.json files


[launch.json.txt](https://github.com/DonJayamanne/pythonVSCode/files/498043/launch.json.txt)
[settings.json.txt](https://github.com/DonJayamanne/pythonVSCode/files/498042/settings.json.txt)

**Comment by DonJayamanne** [comment]
Here's how you can update the extension:
https://code.visualstudio.com/docs/editor/extension-gallery

**Comment by DonJayamanne** [comment]
@gbritton1 , what version of VS Code have you got installed?

**Comment by gbritton1** [comment]
I'm running version 1.5.3 of VS Code

When I went to install 3.24 I got the error message:

"Self-signed certificate in certificate chain"

What does that mean and what should I do to fix that?

**Comment by DonJayamanne** [comment]
Does this happen when you install another extension?
Please check https://github.com/Microsoft/vscode/issues/9790

**Comment by gbritton1** [comment]
Looks like this is a known problem for installations behind a corporate firewall.  on my Azure Win 10 machine, I installed 3.24 without issue *and* it fixed my original issue too!

**Comment by khizerrehands** [comment]
Any one could help ? i have updated typescript 2.1.5 to 2.1.6 in previous version my debugger was working fine in VS Code editor but due to update it is giving me following error!
![screenshot_1](https://cloud.githubusercontent.com/assets/26121221/23510358/137a4c7c-ff7b-11e6-99b6-fecac54f5802.png)

**Comment by DonJayamanne** [comment]
@khizerrehands Please report this issue on the VS Code repo. You're having issues with TypeScript. This repo is for the Python extension.
