### ISSUE TITLE
How to specify "python.pythonPath" ?

### ISSUE THREAD

**Issue by DavidA2014** [DonJayamanne/pythonVSCode#34]
I'm not certain of where to specify "python.pythonPath" in settings.json.  Would I just add something like:

```
python.pythonPath": "C:/Kivy-1.9.0-py3.4-win32-x64/Python34/python.exe
```
below the editor settings, or does your plugin use its own section?  

[Here](https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Version) you show just:

```
python.pythonPath": "c:/python27/python.exe
```
but for [debugging](https://github.com/DonJayamanne/pythonVSCode/wiki/Debugging) you show:

```
{
    "name": "Python",
    "type": "python",
    "request": "launch",
    "stopOnEntry": true,
    "externalConsole":false,
    "program": "${file}",
    "debugOptions": [
        "WaitOnAbnormalExit",
        "WaitOnNormalExit",
        "RedirectOutput"
    ]
}
```

I just want to use the debugger, not the interpreter.  If I add the full section, as shown above for debugging, after the editor settings I get an error on the first curly brace.

Sorry that my difficulty is really a lack of understanding of config settings in general, but I would be grateful for your help.

Best regards

David

**Comment by xqliu** [comment]
I think it's pythonPath now, not python.pythonPath

**Comment by DavidA2014** [comment]
Sorry, I misunderstood the documentation, which is correct. Please close this issue.
