### ISSUE TITLE
Command python.execInTerminal is not executing through shortcut

### ISSUE THREAD

**Issue by rica-benhossi** [DonJayamanne/pythonVSCode#340]
I've been using the command "Run Python file in terminal" and it runs perfectly. However if I run it using a keybinding I've set (ctrl + alt + n) is shows the message: "Command python.execInTerminal is not executing through shortcut"

Below the commando I'm using on file Keybinding.json.

{
        "key": "ctrl+alt+n",
        "command": "python.execInTerminal",
        "when": "editorTextFocus && !editorHasSelection"
    }

If I change the command to "python.execSelectionInTerminal" and select a piece of the code, it runs ok.

I'm using VSCode version 1.5.3

**Comment by DonJayamanne** [comment]
@rica-benhossi , fix will be available in the next release

**Comment by codeliger** [comment]
I am still having this error

**Comment by RicaBenhossi** [comment]
Hey @codeliger I had fixed this new problem while running python using the instructions @DonJayamanne gave on this post: 
https://github.com/Microsoft/vscode-python/blob/master/CONTRIBUTING.md#insiders-build

After that, my problem was solved and I could run python again. Try it...
