### ISSUE TITLE
Pylint error counts not showing at bottom left of VSCode

### ISSUE THREAD

**Issue by gbritton1** [DonJayamanne/pythonVSCode#341]
I created a Python file with some pylint violations.  However, though I can see them if I click on the bottom left section of the VSCode Window (which shows X 0 ! 0) the counts are not showing there.  I would have expected X 0 ! 3 for 3 pylint errors. e.g. 
![9-28-2016 2-24-41 pm](https://cloud.githubusercontent.com/assets/12263288/18926965/c994756e-8587-11e6-8510-042ee6ff726b.png)

**Comment by DonJayamanne** [comment]
@gbritton1 , 
>VSCode Window (which shows X 0 ! 0) the counts are not showing there. 

This is an upstream issue. Please report this on the [VS Code repository](https://github.com/Microsoft/vscode).

>I would have expected X 0 ! 3 for 3 pylint errors. e.g. 

why would you have expected to see 3, when only one warning is displayed?

**Comment by gbritton1** [comment]
> why would you have expected to see 3, when only one warning is displayed?

I wouldn't in that case. I was just giving an example

**Comment by gbritton1** [comment]
[Issue](https://github.com/Microsoft/vscode/issues/13007)

created

**Comment by DonJayamanne** [comment]
@gbritton1 , this has been re-opened (as requested [here](https://github.com/DonJayamanne/pythonVSCode/issues/351#event-810891843)). 
Did you have any additional information or any other issues with the extension?

**Comment by gbritton1** [comment]
The upstream support said:

@gbritton1 It is because, the extension is generating markers of type unknowns/ignore. Status bar only shows information about errors/warnings/info and ignores unknowns.

If you think these markers are important enough not to be ignored, you should create an issue against the extension generating them to change the type of them.

**Comment by gbritton1** [comment]
From Upstream:

@gbritton1 It is because, the extension is generating markers of type unknowns/ignore. Status bar only shows information about errors/warnings/info and ignores unknowns.

If you think these markers are important enough not to be ignored, you should create an issue against the extension generating them to change the type of them.

Thanks

**Comment by DonJayamanne** [comment]
@gbritton1 , now I understand the issue.
Some linter messages such as the one you are seeing above are treated as hints. These have a category of ```convention``` in pylint.  
Now, as @sandy081 has mentioned on VS Code github issue, that items such as the ones above (marked as ```Hints```), are not displayed in the status bar and for some weird reason they are labeled as ```Unknowns```.

So the solution is simple, you can configure these pylint ```convention``` messages to be treated as either one of the following (default is ```hint```):   
- Warning   
- Error   
- Information   

Please check the section ```Pylint Category Mapping``` under [Pylint](https://github.com/DonJayamanne/pythonVSCode/wiki/Linting#pylint).

**Comment by DonJayamanne** [comment]
@gbritton1 , on second thought I'll change the default setting of pylint convention messages to information. This will be fixed in tomorrows release

**Comment by DonJayamanne** [comment]
@gbritton1 , new version has been published
