### ISSUE TITLE
Installing via VS Code extension menu downloads v0.3.23

### ISSUE THREAD

**Issue by neumannrf** [DonJayamanne/pythonVSCode#343]
When I click **Install** and **Enable** the extension, I am greeted with an update notice because, in fact, the version that is installed is `v0.3.23` instead of `v0.3.24`. Even if I click **Update** and **Enable** `v0.3.24` is never installed, keeping me at `v0.3.23`.

I am using version `1.4.0` on MacOS Sierra.

**Comment by DonJayamanne** [comment]
Please update vs code to  1.5.3

**Comment by DonJayamanne** [comment]
@neumannrf , please re-open if the problem persists
