### ISSUE TITLE
matplotlib.pyplot.show() hangs up during debug on Mac OS 

### ISSUE THREAD

**Issue by akochepasov** [DonJayamanne/pythonVSCode#345]
Debugger hangs up on plt.show()

Script to reproduce:
```
import numpy as np
import matplotlib.pyplot as plt
plt.plot(np.linspace(0, 10))
plt.show() # <<<< here
```
OS X El Capitan
Python 2.7.11 |Anaconda 4.1.0 (x86_64)| (default, Jun 15 2016, 16:09:16) 
VS Code Version 1.5.3 (1.5.3)

**Comment by DonJayamanne** [comment]
Yes it will, because plt.show is a synchronous blocking call. 
The ui will probably be displayed in the background. Look for the window in the background window.
