### ISSUE TITLE
How to run file with python3?

### ISSUE THREAD

**Issue by dingfengsaniao** [DonJayamanne/pythonVSCode#347]
I'm newer to python and vs code, Is it possible to use python3? When I click "Run python file in terminal", it is always running with python2~~ I want to know how to run file with python3~
Thank you in advance!!!!!!(Please forgive my poor English XD)

**Comment by DonJayamanne** [comment]
Yes this is possible, please check this out:
https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version

Let me know if you have any trouble
