### ISSUE TITLE
Unable to debug, breakpoints are not reached

### ISSUE THREAD

**Issue by Resousse** [DonJayamanne/pythonVSCode#348]
Hi Don,

My post http://stackoverflow.com/questions/39792325/visual-studio-code-doesnt-stop-on-python-breakpoint-debug brings me there.

To sum up : Windows 10, python 2.7 installed prior the VScode install, latest VScode install then the python extension (no other extension), no breakpoints are reached
The script is run as there was no breakpoint at all...

Let me know if I can help or do some other test.

Thanks
EDIT : I just tried on my mac, no problem, breakpoints are reached, is it a Windows compatibility problem?

**Comment by pseandersson** [comment]
I experience the same issue on my Mac, even though I call the exit() command, debug want stop.

**Comment by DonJayamanne** [comment]
I can't replicate this on my Windows nor Mac.

**Comment by DonJayamanne** [comment]
Will check this out soon

**Comment by Resousse** [comment]
I download the extension code, I tried to debug it, but I have a problem with an empty "out" folder on VS fork opening. How can I "compile" the ext to populate the out folder? (Sorry, just installed VScode 2 days ago for the first time, totally newbie with this...)

**Comment by DonJayamanne** [comment]
Ctrl+shift+b to build

**Comment by DonJayamanne** [comment]
@pseandersson, are you able to step through the code and use breakpoints?
(please ignore exit() command, I'll check that out separately).

**Comment by DonJayamanne** [comment]
Hiw @pseandersson , at my end using the exit(), does indeed stop the debugger.

**Comment by Resousse** [comment]
Hi Don,
Trying to debug, what I did : 
Installing the latest nodeJS (I haven't it before) in the same bitversion as VScode (I selected the X64 first so I had to redo the install...)
Then "npm install" to download dependencies in the packages file
Then "npm config set msvs_version 2013 --global" to avoid the VCBuild.exe or the missing VSCode module error

- Now I have "Cannot find module './_assignValue'" when the VSCode fork is launched.
- During the build I had the error "ERROR in Cannot find module 'core-js/library/fn/symbol/iterator'" 

Is there any solution to each of the errors? 
Thanks

**Comment by DonJayamanne** [comment]
@Resousse , you don't need to build VS Code locally. Please read this:
https://github.com/DonJayamanne/pythonVSCode/wiki/Contribution

**Comment by Resousse** [comment]
Ok, the remote debug works, but I'm not able to find the root cause...
In debugger\Main.ts only the constructor is called, I put breakpoints on all functions of this file.
Not able to debug it easily, I should have missing dependencies or configuration conflict..

**Comment by pseandersson** [comment]
@DonJayamanne  breakpoints doesn't work either.

**Comment by hunter-xue** [comment]
Got the same issue on Sierra (MAC OS), if I use pyvenv. Everything is ok without virtual environment.

**Comment by DonJayamanne** [comment]
@hunter-xue , have you configured the settings.json and launch.json correctly. 
Please check these links:   
- https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version#virtual-environments   
- https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version#python-version-used-for-debugging

**Comment by hunter-xue** [comment]
yes. I did that.




Best wishes.
Hunter Xue

Sent from cellphone.


-------- 原始信息 --------
由： Don Jayamanne <notifications@github.com>
日期: 16/10/4 16:39 (GMT+08:00)
收件人： DonJayamanne/pythonVSCode <pythonVSCode@noreply.github.com>
抄送： Hunter Xue <hunter.xue@outlook.com>, Mention <mention@noreply.github.com>
主题： Re: [DonJayamanne/pythonVSCode] Unable to debug, breakpoints are not reached (#348)


@hunter-xue<https://github.com/hunter-xue> , have you configured the settings.json and launch.json correctly.
Please check these links:

  *   https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version#virtual-environments
  *   https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version#python-version-used-for-debugging

―

**Comment by Resousse** [comment]
@DonJayamanne I just installed Python 3 and it works as expected. There should be a problem with 2.7.12 (64 and 32 bits)

**Comment by DonJayamanne** [comment]
@Resousse
Why do you say there  should be a problem?
What's wrong? It works at my end!

**Comment by Resousse** [comment]
@DonJayamanne 
On the same computer, one python debugger is working (Python 3.0), one other is not (Python 2.7.12), is this expected? 
Thanks

**Comment by DonJayamanne** [comment]
Ok do you mean to say it is not working as opposed to it should not work. Thanks.

**Comment by pseandersson** [comment]
@DonJayamanne ,
What information would you like me to give you so you could solve the problem? I use python 2.7.6.

**Comment by DonJayamanne** [comment]
@Resousse, @pseandersson, @hunter-xue  
Please could you try the following:

- Create a python file named ```test.py``` 
- Add the following code:   
```python
import sys
print(sys.version)
print(sys.executable)
```
- Add a break point to the second line (```print(sys.version)```)  
- Start debugging using the standard ```Python``` debug configuration (don't use Integrated terminal, don't use remote debugging etc)  
- Press the ```Continue``` button (or ```F5```)


**Expected behaviour:**    
- Debugger should break at the first line (default behaviour)  
- Debugger should break at the second line (due to break point)

### **Finally, Please send me the output of the debugger (from the debug window).**

**Comment by hunter-xue** [comment]
It works for me follow your steps:
3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)]
C:\Python34\python.exe

But cannot work if I create a virtual venv of python and set the interpreter path to venv. 
python -m venv .

**Comment by hunter-xue** [comment]
Also, I guess this issue should be: breakpoint are not reached with python virtual environment. :)

**Comment by DonJayamanne** [comment]
@hunter-xue ,
what's ```python -m venv```?
What are you trying to do there?

Please could you send the following information:  
- Fully qualified path to your venv directory  
- 1. Upload the contents of settings.json   
- 2. Upload contents of launch.json   
- Open your terminal window and activate your venv, then execute the following command:
```which python```
- 3. Paste the output of that command here.

**Comment by hunter-xue** [comment]
Here are my steps: 
1. Create new virtual environment: 
mkdir  E:\Coding\python\p3
cd  E:\Coding\python\p3
python -m venv .

2. then I can active the new environment with command below: 
.\Scripts\activate.bat

3. Open VS Code and set python interpreter path (settings.json): 
// Place your settings in this file to overwrite default and user settings.
{
    "python.pythonPath": "e:/Coding/python/p3/Scripts/python"
}

4. start debug, source code run well but cannot reach the breakpoints which I set.

**Comment by hunter-xue** [comment]
`python -m venv .` used to create a new python virtual environment. 

Refer here: https://docs.python.org/3/library/venv.html

**Comment by DonJayamanne** [comment]
Yes I understand that, I thought you were using that command in you're python path. All I need to know is that a virtual env is in use. Thanks. Will check this out.

**Comment by Resousse** [comment]
@DonJayamanne The debug didn't stop on breakpoints :( 
I got the following output:
2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
C:\Python27\python.exe

**Comment by pseandersson** [comment]
@DonJayamanne 
Output:
2.7.6 (v2.7.6:3a1db0d2747e, Nov 10 2013, 00:42:54) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python

Now it works. Strange. The only thing I did differently from last time was that I open the debug panel, selected Python as debug environment a pressed the play button in that panel.

**Comment by Resousse** [comment]
@pseandersson you made me dream, but this trick doesn't work for me ... :(
You were using F5 before?

**Comment by pseandersson** [comment]
@Resousse i'm sorry but I can't really see the why it started to work. Below I'm trying to clarify it even more:

First I made sure that everything was up2date.
Then I closed VSCode and ensured it would open up with no open documents. 
I created a new folder/project, created the test.py file as mention above in the folder.
I open up the debug panel, selected the Python environment, I pressed the play button, and  then it was executing as expected.

**Comment by Resousse** [comment]
Hold on... @DonJayamanne @pseandersson 
I created a new empty directory and I put the test.py file and it works as expected.

Previously I was using the Scripts directory inside the python folder, this could be the cause!
What I have in this folder is **pip.exe** and **easy_install.exe** and a small script I wrote...
I moved out all non related files to another dir, and it's still not working, may be the extension doesn't like the C:\Python27\Scripts folder?

**Comment by DonJayamanne** [comment]
@Resousse , that's sounding good.
>Previously I was using the Scripts directory inside the python folder

What do you mean by this.

Please could you provide a screen sample or some how list the folder structure, so I get a better understanding of the folder/file structure.  
Please do list the files in the directories if possible, or just zip the files and upload to github (here). You can upload files directly into this issue when adding comments (look for the link immediately below the comments textbox and above the buttons).

**Comment by Resousse** [comment]
I mean the directory I was using was C:\Python27\Scripts (inside my python install directory)
Here the content of the directory I was using.
[Scripts.zip](https://github.com/DonJayamanne/pythonVSCode/files/521219/Scripts.zip)

@pseandersson what was the folder you used before?

**Comment by DonJayamanne** [comment]
@Resousse, oh no, that's a very dangerous environment to  be coding in. Not to be done.

**Comment by pseandersson** [comment]
@Resousse 
Just a folder in my home directory. /Users/pse.../VSPYDebugTest or something similar...

**Comment by ArgosHon** [comment]
I had the same problem. Windows 7, latest VS Code with Python 2.7. My .py file was in c:\Python27\Scripts (because as a newbie that's were you'd think you could put your scripts...)

Then moved my .py file to a directory under C:\Users\<username> (full path then C:\Users\<username>\Python) - AND THEN SUDDENLY DEBUGGING WORKED :-)

**Comment by DonJayamanne** [comment]
Looks like people have been placing scripts in the python interpreter directory.
Please move it out of there,

**Comment by JasonMFry** [comment]
@DonJayamanne I know this issue has been marked closed, but I'm having the same issue and am not putting my scripts in the python interpreter directory. If you'd prefer me to open a new issue or add my info to another open issue, let me know. But for now, here's what's happening.

### Problem
Adding a breakpoint to a file then starting the debugger marks the breakpoint as `Unverified Breakpoint`, file is in debugging mode for several seconds, then debugging mode stops with no output to the Debugging window.

### My setup

- [launch and settings.zip](https://github.com/DonJayamanne/pythonVSCode/files/1260532/launch.and.settings.zip)
- Output of `which python`: /Users/jason/Developer/Feathr/feathr-blackbox/.venv/bin/python
- I created the file `~/Developer/Feathr/feathr-blackbox/app/tests/scripts/stubs/test.py`, pasted the below code, added a breakpoint to line 2.
```
import sys
print(sys.version)
print(sys.executable)
```
- After debugging, there is no output in the Debugging window
- I have restarted VSC, cleared all breakpoints and re-added them, and still doesn't work.
- In `launch.json`, if I change `"program": "/Users/jason/Developer/Feathr/feathr-blackbox/application.py",` to `"program": "${file}", debugging will work as expected in `test.py`. However, I get an `ImportError` in a file that tries to import `app.models`. 

For even more info, including specifics on the `ImportError`, I have a detailed [stackoverflow post](https://stackoverflow.com/questions/45941526/vs-code-debugging-always-gives-importerror-on-internal-modules-in-python/45941527#45941527).

**Comment by veuncent** [comment]
In case it is relevant for anyone: in my case breakpoints were not hit due to a remnant piece of code I used for remote debugging using ptvsd:

`ptvsd.enable_attach()`

Removing this solved this issue while debugging using `launch.json` for me.
