### ISSUE TITLE
Syntax coloring only works partially

### ISSUE THREAD

**Issue by flyfj** [DonJayamanne/pythonVSCode#35]
Hi, thanks for providing this awesome extension for python, really love it!

An issue I have is the syntax coloring seems to be working only for certain elements. My os is win10 pro 64bit, and things like def, class are not colored. When I test on other os, e.g. win12 server, it works ok (my macbook pro also doesn't work). Is there anyway to fix this?

**Comment by DonJayamanne** [comment]
This extension doesn't support syntax highlighting. Please try the following extension https://marketplace.visualstudio.com/items?itemName=magicstack.MagicPython
