### ISSUE TITLE
Remote debugging over SSH

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#350]
Would appreciate some help and information on SSH, port forwarding and the like.

Remote debugging is possible today over a simple TCP connect. Would SSH port forwarding work here? I don't know, don't even know much about SSH.

**Comment by Resousse** [comment]
SSH port forwarding, you mean ssh tunnel?
What would be the use case? (remote debugging on a server which the debug port is not opened?)

I used port forwarding for this kind of purpose (java debugging):
- I open a SSH connection to the remote server I want to debug
- I enable the port forwarding for a local port mapped to a remote port (for example localhost:4443 would be linked to remote:443)
- I configure the debugging client locally to going trough the tunnel (connect the application to localhost:4443 to access remote:443 which is not opened from my computer)

**Comment by DonJayamanne** [comment]
@Resousse 

>SSH port forwarding, you mean ssh tunnel?

Don't know. SSH is something I am not familiar with. 
What I do know is that debugging over SSH is something that has been requested (see below).
From what I understand it is similar to what you have indicated (port forwarding - you can see my comments). So my initial plan is to investigate this and document it. I.e. highly unlikely I'd need to make any changes to the code base.

> What would be the use case?   

- Requested by users (https://github.com/DonJayamanne/pythonVSCode/issues/183#issuecomment-229492622)  
- Debugging applications on AWS, etc

**Comment by DonJayamanne** [comment]
@Resousse , you seem to know more about this than I do. Would appreciate some help in documenting this. (I believe we both agree that this is merely a configuration issue).

**Comment by Resousse** [comment]
Actually, using windows, it's pretty simple 👍 
Firstable, the ssh portforwading must be enabled on server side (sshd_config or similar).
Then on windows : Putty SSH tunnel could be established using the following procedure : http://realprogrammers.com/how_to/set_up_an_ssh_tunnel_with_putty.html (until Open the session section).
On the Tunnels screen, using a local mode, source port (which is the port which will be the entry point on the local computer) can be different from the destination port (the end point on the server).
Destination address should be the localhost or 127.0.0.1 address (which is the address that the remote ssh server will use to establish the tunnel).

On Linux/Mac, it's even easier,
ssh -L sourceport:localhost:destinationport  user@remoteadresse 

Once the tunnel is opened (and you are able to see a prompt in the ssh session), you have to configure the VSCode launch.json file to connect to localhost:sourceport (where source port should be replaced by the one you put in the Tunnels screen, which is the debug port).
Then on the server you should launch the python script using the python remote debug prior to use the VSCode remote debug using the "Attach (Remote Debug)" mode

**Comment by DonJayamanne** [comment]
@Resousse , wow, brilliant. Thanks. Will update the wiki with your information. Thanks.

**Comment by DonJayamanne** [comment]
@Resousse , thanks
Wiki updated: https://github.com/DonJayamanne/pythonVSCode/wiki/Debugging-over-SSH

**Comment by allanhaywood** [comment]
I may be missing something, but I have an ssh tunnel set up (I've gotten it to work for other purposes).
However, when I attempt to execute the python script, it indicates address is already in use.

**Comment by Resousse** [comment]
Hi @allanhaywood,

Could you provide technical details? What is the command you entered? On which port did you run the debug serverside?

Thanks

**Comment by FuriouslyCurious** [comment]
Hi @Resousse 

Can you elaborate on following:

> Then on the server you should launch the python script using the python remote debug prior to use the VSCode remote debug using the "Attach (Remote Debug)" mode

Does this mean we are starting python interpreter on remote server, or are we starting pdb / other commands?

Thank you!

**Comment by Resousse** [comment]
Hi @FuriouslyCurious,

https://stackoverflow.com/questions/35066784/how-to-setup-remote-debugging-with-eclipse-and-pydev Look at the first answer

The pydev lib is used to transform your remote python code to a debug server (pretty easy, a library and couples of line to add). 
I haven't tried it, let me know if it works or not!
Thanks
