### ISSUE TITLE
Right click "find definition and Peek does not work with files in open folder

### ISSUE THREAD

**Issue by i-frost** [DonJayamanne/pythonVSCode#352]
python extension :Version 0.3.24
VSCode Version: Version 1.5.3
OS Version: Linux Mint 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Steps to Reproduce:

open git repo folder in code, python files
right click select "Go to Definition"
Nothing happens, definition file.py is in same folder
Same with "peek definition"
Find all References just displays "loading"

It works if the definition is in the same file but anything defined in another file it does not work.
The searching does not work even if def is in same file.

**Comment by DonJayamanne** [comment]
@i-frost , please could you upload the two python files?

**Comment by i-frost** [comment]
Hey Don,

I copied 2 files into a new directory and reopened code and selected the new folder and it is working! 

So are there any code files hidden or otherwise which I might delete to flush any conflicts etc. I wonder if the git files are someway involved.

I will try and add each file to this new directory until it breaks again.

Thanks

**Comment by DonJayamanne** [comment]
>So are there any code files hidden

No

>I will try and add each file to this new directory until it breaks again.

Sure thing, until then i'll close this issue.

**Comment by i-frost** [comment]
Hey Don,

I have been doing some playing and I have some very strange things going on.
I am running this on a chromebook running Arch Arm with a compiled version of vscode

Version 1.5.0
Commit Unknown
Date Unknown
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
Python exten Ver 0.3.24

[testCode.zip](https://github.com/DonJayamanne/pythonVSCode/files/511037/testCode.zip)

If I have the imports in check_membership I can not see any definitions in test.py

If I comment out the imports in check_membership I can not see any definitions.

If I remove the imports from check_membership I can see the first definition. But not the next 2 definitions. If I remove the comments I can see them.


I will go and see if this is the same on my desktop running mint and a non compiled version of code.

Thanks

**Comment by i-frost** [comment]
Version 1.5.3
Commit 5be4091987a98e3870d89d630eb87be6d9bafd27
Date 2016-09-22T08:40:08.699Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
Python exten Ver 0.3.24

Same problem on Desktop I checked the python paths and I can import all core python modules. And code completes their names including check_membership.

But will only see the first definition in check_membership file if I remove the import lines. Also does not like the comments in the file, will not see the definition if any comments before def or on same line.

**Comment by DonJayamanne** [comment]
Just click the reopen button

**Comment by DonJayamanne** [comment]
Please upload the sample code used to replicate the issue

**Comment by DonJayamanne** [comment]
Found that you have uploaded it, thanks

**Comment by DonJayamanne** [comment]
Closing as this is an upstream issue with the Jedi library.
https://github.com/davidhalter/jedi/issues/772
