### ISSUE TITLE
Debug - Run as Python Package

### ISSUE THREAD

**Issue by eaplatanios** [DonJayamanne/pythonVSCode#354]
Hi,

This is effectively a repeat of issues #222 and #272. These issues cannot really be considered closed yet. The proposed answer does not deal with the issue of relative imports in the python script (e.g. `from ..package.module import xyz`). This is important when running scripts that are part of packages. In order to do this from the terminal, one would type: `python -m package1.module1.script` instead of `python package1/module1/script.py`. Is there currently any way to specify that in launch.json?

Thank you!

**Comment by DonJayamanne** [comment]
Unfortunately no, but this can be added easily.
Is package1, the root directory of the project?

For instance if I were to automate this:
- Would you expect the debugger to automatically determine the package name?   
    + If this is done, then I'd need to know what rules to use?
    + Do i use the current working directory as the package name or the subdirectory as the package name?
- Or would you manually type in the package name?
    + I will add support for this too (so as to override the name inferred by the debugger above)

**Comment by eaplatanios** [comment]
Thanks for the quick response! Judging from my personal experience, the following is usually true, but other can also provide feedback:

- The main package lies in `workspaceRoot` or a path relative to that (e.g., `${workspaceRoot}/src/package`).
- The user can provide the path to the package root in this way, in launch.conf.
- Then, as a simple rule, given `${file}`, the debugger removes `${workspaceRoot}/src/` from the front of the string and replaces all path separators with periods.
- Then, runs the script using `python -m {processed_as_above_name}` from within `${workspaceRoot}/src/`.

If the filename cannot be processed (e.g., because the first part does not match the package directory provided), then an error may be thrown.

I'm not sure what of the above is possible and how easy it is to implement, but I think this setup covers many common scenarios. I would really appreciate some feedback though, as the above is just from some fairly limited personal experience.

**Comment by eaplatanios** [comment]
You can also find a nice description of how relative imports work in Python, [here](http://stackoverflow.com/questions/14132789/relative-imports-for-the-billionth-time).

The answer also describes how relative imports work based on how you execute a Python script, which is what this issue is about.

**Comment by DonJayamanne** [comment]
Similar to #518 
This feature has been added.

Completed, will be in the next release:
```json
        {
            "name": "Python Module",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "module": "myMod.foo.bar.baz",
            "cwd": "${workspaceRoot}",
            "args": [
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
```

Added the new setting ```module``` . This is where you would provide the name of the module to be debugged.
As there's no file name you'll need to ensure the setting ```cwd``` is provided. In the above sample it is configured to point to the workspace root.

Note: ```args``` is empty here, provide values that need to be passed into the module. '-m' is provided by the debugger for the module when launching it, i.e. you need not use the value '-m' in the set of args.

**Comment by ajs394** [comment]
I get an error when attempting to use the following configuration:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python Module",
            "type": "python",
            "pythonPath":"${config.python.pythonPath}", 
            "request": "launch",
            "stopOnEntry": false,
            "cwd": "${workspaceRoot}",
            "module": "foo.bar",
            "args": [
                
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }
    ]
}
```

Error:
`TypeError: Cannot read property 'cwd' of undefined`

however the following config executes fine (but doesn't serve my needs)

```
{
    "version": "0.0.1",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "pythonPath":"${config.python.pythonPath}", 
            "request": "launch",
            "stopOnEntry": false,
            "console": "none",
            "program": "${workspaceRoot}/__init__.py",
            "cwd": "${workspaceRoot}",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }
    ]
}
```

The error appears as soon as there is a non-white space module tag
