### ISSUE TITLE
Unable to debug django process

### ISSUE THREAD

**Issue by imaia** [DonJayamanne/pythonVSCode#355]
Django debug is not working. Breakpoints are never triggered.

**Comment by DonJayamanne** [comment]
@imaia , please could you try the following:

- Create a file named manage.py and add the following contents

```python
import sys
 
from django.conf import settings
from django.conf.urls import patterns
from django.http import HttpResponse
from django.core.management import execute_from_command_line
 
settings.configure(
    DEBUG=True,
    SECRET_KEY='placerandomsecretkeyhere',
    ROOT_URLCONF=sys.modules[__name__],
)
 
def index(request):
    return HttpResponse('Powered by Django')
 
urlpatterns = patterns('', 
    (r'^$', index),
)
 
if __name__ == "__main__":
    execute_from_command_line(sys.argv)
```

- Start debugging using the "Django" configuration.
- Next navigate to the following url in your browser - http://127.0.0.1:8000/
- Next add a break point to the line ```return HttpResponse('Powered by Django')```

Please try in that order and let me know if it works?

**Comment by imaia** [comment]
Thanks @DonJayamanne The problem was that I removed --noreload from launch args. That caused the problem.
