### ISSUE TITLE
[Intellisense] Support PEP484

### ISSUE THREAD

**Issue by chengyuhui** [DonJayamanne/pythonVSCode#359]
Latest version of Jedi supports PEP-0484 style type hinting like this: (copied from document)
```python
def myfunction(node: ProgramNode, foo: str) -> None:
    """Do something with a ``node``.

    """
    node.| # complete here
```

And Jedi source in this repo is more than 2 years old. Is it possible to get an update?

**Comment by DonJayamanne** [comment]
@chengyuhui , yes the latest version suppoerts PEP-484. Infact so did the old version, but there's a bug. The latest version hasn't been released as it is incomplete.  
- https://github.com/davidhalter/jedi/issues/742  
- https://github.com/davidhalter/jedi/issues/740  

I will consider releasing the dev branch as a preview option.
