### ISSUE TITLE
Is there any sample to enable nose test?

### ISSUE THREAD

**Issue by xqliu** [DonJayamanne/pythonVSCode#36]
Dear All,

Is there any sample to enable nose test?

I have searched out the wiki and issues but didn't find some information regarding run unit tests.

When a unit test file is opened and I tried to run Python:run unit tests and the system out put the follow information on OUTPUT panel:
```
----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

But actually there's some unit test there.
```
I would like to appreciate for any valuable information here.

**Comment by DonJayamanne** [comment]
I will add a sample on Monday. Sorry for the delay

**Comment by DonJayamanne** [comment]
Sorry for the delay here are the steps:
1. First enable nosetests in the settings (either usersettings or workspace settings)
```json
"python.unitTest.nosetestsEnabled": true
```
2. Next create your unit test file as per the sample on this page   
http://pythontesting.net/framework/nose/nose-introduction/

3. Create a file named test_um_nose.py
4. Add the test code in there
5. Run the unit tests this time and it will work.
