### ISSUE TITLE
autocomplete doesn't stay up-to-date for unsaved files

### ISSUE THREAD

**Issue by ags799** [DonJayamanne/pythonVSCode#360]
While editing a module `a` that imports module `b`, if I change the function names in `b`, those changes aren't reflected in autocompletions in `a` until `b` is saved. Best explained by a picture:

![screen shot 2016-10-06 at 6 07 47 pm](https://cloud.githubusercontent.com/assets/2957581/19173276/8ebab700-8bf4-11e6-94b7-d8034add79a4.png)

The unsaved function name is `bax`, but the autocompletion is for its old saved name, `baz`.

Maybe this is an issue with VSCode. Thanks!

**Comment by DonJayamanne** [comment]
Unfortunately In such circumstances, the changes will have to be saved.

**Comment by ags799** [comment]
Thanks for responding, may I ask if this is a limitation of VS Code, or could some contribution to pythonVSCode enable this?

**Comment by DonJayamanne** [comment]
This is a limitation with the [Jedi library](http://jedi.jedidjah.ch/en/latest/), that's being used. You might want to consider contributing to that library.
