### ISSUE TITLE
Keybinding for "python.execInTerminal" returns "Running the contributed command:'python.execInTerminal' failed."

### ISSUE THREAD

**Issue by SeaDude** [DonJayamanne/pythonVSCode#361]
Hello, 

OS: 
Ubuntu 16.04
VS Code: 
Version 1.5.3
Commit 5be4091987a98e3870d89d630eb87be6d9bafd27
Date 2016-09-22T08:40:08.699Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

I installed the python extension works great. I want to create a shortcut to execute python. When I set a VS keybinding to: 

`[
{ "key": "ctrl+shift+s",            "command": "python.execInTerminal"} 
]`

in my keybindings.json file, I get the ` "Running the contributed command:'python.execInTerminal' failed."`error. 

The gui for `Run Python file in terminal` shows `ctrl+shift+s` next to it. Why is this custom keybinding not working? 

Thank you,

**Comment by DonJayamanne** [comment]
Duplicate https://github.com/DonJayamanne/pythonVSCode/issues/340
New version will be available later today after the release of VS Code 1.6

**Comment by SeaDude** [comment]
Thank you for the fast response! I should have searched before posting. My apologies.

**Comment by DonJayamanne** [comment]
No big deal

**Comment by DonJayamanne** [comment]
@SeaDude new release has been published

**Comment by al123xiaaaa** [comment]
But now I still have the same problem

**Comment by miguelfc** [comment]
Here too: command 'python.execInTerminal' not found. Using version 0.5.8

**Comment by gandhis1** [comment]
This was fixed on a more recent version (0.6.0)
