### ISSUE TITLE
Functionalities are borken due to encoding issue

### ISSUE THREAD

**Issue by guhuajun** [DonJayamanne/pythonVSCode#364]
Greetings,

I have upgraded vscode and python extension to latest verison.
Peek definition and other functionalities are broken due to encoding issue.

![vscode_error](https://cloud.githubusercontent.com/assets/14121694/19257067/362e77ee-8f9f-11e6-8d56-6c677ffdba51.png)

**Comment by DonJayamanne** [comment]
Please could you upload the sample code you have used.
Right now there's a know issue with unicode characters in docstrings (#293).

**Comment by guhuajun** [comment]
The issue.zip is the file for reproducing this issue.

It works before. I am guessing this issue is caused by some special character.

[issue.zip](https://github.com/DonJayamanne/pythonVSCode/files/520946/issue.zip)

**Comment by DonJayamanne** [comment]
@guhuajun , I can't replicate the issue. Please provide the following:
- OS  
- Version of Python
- Sample file that doesn't work

I tried the following code and it works, tried without the comments and still works.
Please provide the sample code that breaks it, and what is it exactly that doesn't work.
```python
# -*- coding：utf-8 -*-
# pylint: disable=E0401, W0512

import os


class Foo(object):
    '''说明'''

    @staticmethod
    def bar():
        # 说明 - keep this line, it works
        # delete following line, it works
        # 如果存在需要等待审批或正在执行的任务，将不刷新页面
        return os.path.exists('c:/')

Foo.bar()
```

**Comment by guhuajun** [comment]
OS: Windows 7 SP1
Python: Python3.5

You may check this screenshot. The code is same.
![vscode_error](https://cloud.githubusercontent.com/assets/14121694/19259995/c5748e3e-8fb8-11e6-8e73-b42b2d0aea72.png)

**Comment by DonJayamanne** [comment]
Thanks,
>I have upgraded vscode and python extension to latest verison.

Did this work in older versions? If you don't know thats fine.

**Comment by guhuajun** [comment]
I will update later when using my laptop at home. :)

**Comment by guhuajun** [comment]
@DonJayamanne WOW! Thanks for adding django templates debugging in 0.4.1!!! It's amazing!!!

After upgrading, this issue still happens. But it's not a block issue for releasing my project to production.
Keep fighting! Your python extension is awesome! 
![vscode_error1](https://cloud.githubusercontent.com/assets/14121694/19293432/ba1f16be-9056-11e6-90d1-f50f07b26a59.png)

**Comment by grasssand** [comment]
I found the same problem with python 0.4 and 0.4.1. I temporarily put the 'C:\xxx\.vscode\extensions\donjayamanne.python-0.4.1\pythonFiles\jedi\api\__init__.py' into this, it looks to work. However, I do not know where the problem lies.(sorry for my bad english :)
![ashampoo_snap_2016 10 12_11h05m43s_002_](https://cloud.githubusercontent.com/assets/11460505/19296147/0bf34252-906c-11e6-8307-e0d7b9c73b35.png)
![ashampoo_snap_2016 10 12_11h07m50s_003_](https://cloud.githubusercontent.com/assets/11460505/19296167/2a3fb02e-906c-11e6-90fa-45b377781a01.png)

**Comment by DonJayamanne** [comment]
@grasssand 
>I temporarily put the 'C:\xxx.vscode\extensions\donjayamanne.python-0.4.1\pythonFiles\jedi\api__init__.py' into this, it looks to work.

What did you do to make it work?

**Comment by DonJayamanne** [comment]
@guhuajun , @grasssand 
I would like to get to the bottom of this.  

(1). **Please could you check the value of ```locale.getpreferredencoding(False)```**
- Open a terminal window and execute the above command in Python 
- Open a terminal window inside VS Code (integrated terminal) and execute the above command  

(2). **Next please execute the following code in python outside VS Code**  
Where ```path``` is the fully qualified path to the file in question.
```python
    print(locale.getpreferredencoding(False))
    with open(path) as f:
        source = f.read()
```

(3). **Also, please modify the following file (before line 90):**
- ```C:\xxx.vscode\extensions\donjayamanne.python-0.4.1\pythonFiles\jedi\api__init__.py```  
- Add some code to create a temporary file 
- To that temporary file write out the value of ```locale.getpreferredencoding(False)```

What I'd like to check is the encoding in the process that is opening the text file. (i.e. we're debugging here - a very dirty and old fashioned way :))
Thanks

**Comment by DonJayamanne** [comment]
@guhuajun , @grasssand 
I would like to ask for one last favour.
Would really appreciate it if you could try this. Helps me rule out certain things.

**Please could one of you try the following:**
### **Test 1**
- Download and install the previous version of the extension (version ```0.3.24```)
    + https://donjayamanne.gallery.vsassets.io/_apis/public/gallery/publisher/donjayamanne/extension/python/0.3.24/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage?install=true)
    + Rename the downloaded Microsoft.VisualStudio.Services.VSIXPackage package's file extension to Microsoft.VisualStudio.Services.vsix.
    + Run code Microsoft.VisualStudio.Services.vsix as described in the [installation instructions](https://code.visualstudio.com/docs/extensions/install-extension#_install-a-packaged-extension-vsix).
    + Restart the editor.
    + **Can you replicate this issue?**

### **Test 2**
- Download the older version of VS Code from here (https://code.visualstudio.com/updates/v1_5)
- Install the latest version of the extension and check if you can still replicate the issue.
- Confirm whether you can still replicate the issue?

### **Test 3**
- If you can replicate the issue then try the following:
    + Download the following file (old version ```0.3.24```)
    + https://donjayamanne.gallery.vsassets.io/_apis/public/gallery/publisher/donjayamanne/extension/python/0.3.24/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage?install=true)
    + Rename the downloaded Microsoft.VisualStudio.Services.VSIXPackage package's file extension to Microsoft.VisualStudio.Services.vsix.
    + Run code Microsoft.VisualStudio.Services.vsix as described in the [installation instructions](https://code.visualstudio.com/docs/extensions/install-extension#_install-a-packaged-extension-vsix).
    + Restart the editor.

**Comment by guhuajun** [comment]
@DonJayamanne 

Here are the screenshots for investigating this issue.

![vscode_python_evd1](https://cloud.githubusercontent.com/assets/14121694/19301665/32b7c418-9093-11e6-87ce-5035db55f505.png)
![vscode_python_evd2](https://cloud.githubusercontent.com/assets/14121694/19301668/33150fa6-9093-11e6-917b-aee3059e2099.png)
![vscode_python_evd3](https://cloud.githubusercontent.com/assets/14121694/19301669/331c2a7a-9093-11e6-9596-76df38fa7787.png)

**Comment by DonJayamanne** [comment]
Thanks  guys, I think the problem only exists in the new version.

**Comment by DonJayamanne** [comment]
That should be enough for now

**Comment by DonJayamanne** [comment]
Fixed along with https://github.com/DonJayamanne/pythonVSCode/issues/372

**Comment by DonJayamanne** [comment]
@guhuajun , @grasssand 
Hi guys, a new build has been published. Please download that and test that out.
Thanks for your help in sorting this out.

**Comment by guhuajun** [comment]
@DonJayamanne Thanks for your effort here. Every thing works again. :+1:
