### ISSUE TITLE
Version incompatibility in Jupyter (Python extension). View 'Help' for further details.

### ISSUE THREAD

**Issue by willyd** [DonJayamanne/pythonVSCode#366]
Hi,

I just installed VSCode 1.6. Then updated the extension to 0.4.0. When I try the Jupyter plot example I get the above error message? 

From what I can understand this is a problem with the jmp module. I don't have (AFAIK) this module anywhere else on my harddrive so I doubt it is loading the incorrect version. Anyway I can figure out what jmp module is being loaded here?

Thanks

**Comment by mratsim** [comment]
I had this message while on VSCode 1.3.X. It disappeared when I upgraded to VScode 1.6 .

VSCode auto-update didn't work even though I was popped up 3 times with "VScode will upgrade after restarting". So maybe check if the upgrade happened properly?

**Comment by DonJayamanne** [comment]
@willyd 
Please confirm the update worked and try reinstalling the python extension.

Also what is your OS?

**Comment by gandhis1** [comment]
I have this issue on Windows 10, with the nightly VS Code build, and latest Python extension version.

**Comment by DonJayamanne** [comment]
@gandhis1
Instead of using the nightly build please could you try  the official release. 
Fyi - I am working on removing this version incompatibility.

**Comment by willyd** [comment]
@DonJayamanne 

I have the same issue on two machines. Both are:

Windows 10 64 bit
VSCode 1.6
Python Extension 0.4.0

both have the issue. 

One machine was updated with the VSCode installer because of firewall issues and I actually downloaded the VSIX and installed the extension using the VSIX (again because of firewall restrictions).

The other machine was updated normal via vscode itself.

Uninstalling the extension has no effect on the first machine. I will try on the other one and report back.

**Comment by DonJayamanne** [comment]
@willyd are you using the official release or the nightly build?

**Comment by willyd** [comment]
AFAIK official release. I downloaded:

https://az764295.vo.msecnd.net/stable/e52fb0bc87e6f5c8f144e172639891d8d8c9aa55/VSCodeSetup-stable.exe

**Comment by Darktex** [comment]
I have the same problem. My machine is brand new (freshly installed a couple of days ago), and it is running Atom with Hydrogen just fine on Windows 10 Anniversary Update.

I use Anaconda 3 (with Python 3 being installed into C:\Users\<My_User>\AppData\Local\Continuum\Anaconda). My Windows default points to that Python interpreter. In addition, I do have another Anaconda environment that uses Python 2.7 for when I need it, but it's not the default.

I have seen in [another issue](https://github.com/DonJayamanne/pythonVSCode/issues/369) that this may be caused by Jupyter picking the wrong kernel. However, Hydrogen on Atom is working just fine on Python 3, and the Windows default for IPython does point to the right path.

**Comment by DonJayamanne** [comment]
@willyd , @gandhis1 , @Darktex 
I believe I know what's wrong, please could you ensure you have installed ZeroMQ as defined here:
https://github.com/DonJayamanne/pythonVSCode/wiki/Jupyter-(IPython)-Prerequisites

I'll update the error message for the next release (this week).

**Comment by Darktex** [comment]
Uhm that's what I did. I have installed ZeroMQ from the MSI for Python 3 (this one: https://github.com/downloads/zeromq/pyzmq/pyzmq-2.2.0.1.win-amd64-py3.3.msi ). I just re-downloaded it and re-installed it (they have a Repair option) to see if this changed things but it did not. I did restart my computer just in case.

**Comment by DonJayamanne** [comment]
@Darktex , please could you open your ```Python``` output panel and let me know what's displayed there. (Menu ->View->Output and then select ```Python``` from the dropdown list)

**Comment by Darktex** [comment]
If VS Code is cold started, there is no "Python" in the dropdown list, only Python Test Log (should be expected, reporting just in case).

Using Ctrl Alt P and choosing Jupyter: Run Cell makes Python appear in the dropdown list and this shows up:

> VS Code Kernels updated:, Python 3
> Error Message: Version incompatibility in Jupyter (Python extension). View 'Help' for further details., (Version incompatibility in Jupyter (Python extension). View 'Help' for further details.)

**Comment by DonJayamanne** [comment]
@Darktex , thats not very helpful. I'll release a version shortly with a few more fixes and features. Hopefully that'll shed more light on this.

**Comment by DonJayamanne** [comment]
@Darktex , a new version (```0.4.1```)has been published with a few new features and fixes.
Please test this and let me know what error is logged in the output panel. Thanks.

**Comment by Darktex** [comment]
Same behavior, but the error message has now some more information:

> VS Code Kernels updated:, Python 3
Error Message: %1 is not a valid Win32 application.
\\?\C:\Users\<MyUser>\.vscode\extensions\donjayamanne.python-0.4.1\node_modules\zmq\build\Release\zmq.node, (Error)

**Comment by DonJayamanne** [comment]
@willyd , @gandhis1 , @Darktex , I believe I now understand the problem.
I believe the problem here is the additional dependency needs to be build specifically for each OS.
Unfortunately you will need to wait for a subsequent release that will fix this.

I have already started working on removing this (zmq) dependency completely. However this would take around a week. Hope you can wait until then.

Once again apologies for this issue and the delay in getting a fix for you.

**Comment by Darktex** [comment]
Thanks for looking into it! ZMQ has been a serious pain to get working on Windows. Looking forward to doing away with this package 👍

**Comment by DonJayamanne** [comment]
@willyd , @gandhis1 , @Darktex 
The modifications will not only do away with this dependency, but it will purely based on Python. However, If I'm not mistaken IPython and Jupyter_client do have a dependencies on zmq (in some for or another).

For instance looking at [Jupyter_client](https://pypi.python.org/pypi/jupyter_client/4.3.0) the dependencies are:  
- ipykernel; extra == 'test'
- traitlets
- _**pyzmq (>=13)**_
- jupyter-core

@willyd , @gandhis1 , @Darktex 
- Is anyone of you using Anaconda? 
- Or are you using a standard Python 3.5 install with IPython or Jupyter installed via Pip?

**Comment by gandhis1** [comment]
I am using an Intel Python distribution, which is similar to Anaconda.

**Comment by Darktex** [comment]
I'm on the latest Anaconda Python 3. Downloaded it less than a week ago (new machine). Jupyter does not require an explicit ZMQ installation/recompilation though, and it's generally a hassle-free experience on Windows if you use Anaconda. So I'm quite optimist that this problem will solve itself if VS Code's dependencies are the same as Jupyter :)

**Comment by willyd** [comment]
@DonJayamanne 

Just tested with 0.4.1 and I still get the same error message:


Linting with pylint failed.
You could either install the 'pylint' linter or turn it off in setings.json via "python.linting.pylintEnabled = false".
Error: spawn pylint ENOENT
VS Code Kernels updated:, Python 2
Error Message: %1 is not a valid Win32 application.
\\?\C:\Users\guillaume\.vscode\extensions\donjayamanne.python-0.4.1\node_modules\zmq\build\Release\zmq.node, (Error)



> @willyd , @gandhis1 , @Darktex
> 
> Is anyone of you using Anaconda?
> Or are you using a standard Python 3.5 install with IPython or Jupyter installed via Pip?

I am using anaconda 2.7 as my main environment. Using stock IPython from anaconda not installed via pip.

Thanks for the prompt responses. I will wait for the fix.

Please let us know.

**Comment by DonJayamanne** [comment]
Great

**Comment by DonJayamanne** [comment]
@mratsim, @willyd, @gandhis1 , @Darktex, @blaueck, @neilsustc, @ycdoit, @mulyoved,
@sth4nth, @MichaelT0, @codingyourlife, @leido, @piec, @kuza55

I everyone. I'm almost done with the changes to remove zmq completely and go with a pure Python solution. I'm hoping some of you can volunteer to test this for me. I'll create a build (*.vsix file) and then you can install this locally (manually using instructions outlined [here](https://code.visualstudio.com/Docs/extensions/install-extension#_install-a-packaged-extension-vsix) )

Please let me know if you would like to help out. I'll try to upload a build later today.

**Comment by DonJayamanne** [comment]
here's the vsix file
[python-0.4.2.vsix.zip](https://github.com/DonJayamanne/pythonVSCode/files/538175/python-0.4.2.vsix.zip)

- Change the extensino from ```.zip``` to ```.vsix```  
- Uninstall existing Python extension  
- Install as per instructions found [here](https://code.visualstudio.com/Docs/extensions/install-extension#_install-a-packaged-extension-vsix)

**Comment by piec** [comment]
Thanks, works for me!
conf: Arch Linux, jupyter in a virtualenv

**Comment by DonJayamanne** [comment]
@piec , thanks. Anyone tested on Windows yet. Thanks.

**Comment by leido** [comment]
It works! thanks very much.
But I noticed there isn't any default keybindings for jupyter commands. besides that, it is perfect.

conf: Linux mint 18, python3 system, vscode 1.6.1

**Comment by willyd** [comment]
@DonJayamanne 

Just tested on Windows 10 and VS Code 1.6.0 and Python 3.5 and I don't see the problem about the jmp module anymore but:

- When I click Run cell I don't get any output in the Results split editor. I only see the Append Results and Clear Results buttons. Here is the content of my test file.

```
#%%
import sys
print(sys.prefix)

#%%
x = range(10)
print(x)

#%%
from matplotlib import pyplot as plt
plt.plot(range(10))
plt.show()
```
- The debugger does not work anymore. When I try to debug via F5 I get:

Error Debug adapter process has terminated unexpectedly.

**Comment by DonJayamanne** [comment]
@willyd please try the new extension:  
- Fixes the debugger issue  
- No fix for jupyter results, however i'd like you to install this either way  
- Once installed, once again try to run a cell 
- Please let me know what errors are displayed in the ```python output panel``` if nothing then go into:   
    + Help->Toggle Developer Tools menu
    + Go into Console tab and let me know if there are any errors (red), if so please provide the errors

FYI - I have tried this on a Windows 10 environment as well, and works as expected.
[python-0.4.2.vsix.zip](https://github.com/DonJayamanne/pythonVSCode/files/540410/python-0.4.2.vsix.zip)

**Comment by DonJayamanne** [comment]
@leido will add some default key bindings.
Please could you let me know the commands for which you would like to have keybindings? 
Or are you after bindings for all the commands?

**Comment by gandhis1** [comment]
The main one for me would be Run Selection/Line. Ctrl + E, Ctrl + Enter, or Ctrl + Alt + Enter are common ones for this in other IDEs.

P.S. I think the Jupyter commands should be capitalized in the action menu to blend in with the broader convention. Looks rather out-of-place as is.

**Comment by DonJayamanne** [comment]
@gandhis1 , thanks.
> blend in with the broader convention. Looks rather out-of-place as is.

Don't quite follow you here. I find that other menus aren't capitalized. Please could you provide an example.

**Comment by willyd** [comment]
> FYI - I have tried this on a Windows 10 environment as well, and works as expected.
> python-0.4.2.vsix.zip

@DonJayamanne The second link to python-0.4.2.vsix.zip is broken.

**Comment by DonJayamanne** [comment]
@willyd
[python-0.5.0.vsix.zip](https://github.com/DonJayamanne/pythonVSCode/files/540505/python-0.5.0.vsix.zip)

**Comment by willyd** [comment]
@DonJayamanne Both the debugger and jupyter work on my home machine. Actually, the previous version the jupyter integration worked too. Not sure why it does not on my work machine. I will test on that other machine and get back to you.

**Comment by DonJayamanne** [comment]
@willyd , that's very interesting. 
Let me know, i'm close to publishing this new version.
I could create a separate version with some more logging for you.
Also, thanks a lot for testing this out on multiple environments. 👍

**Comment by willyd** [comment]
@DonJayamanne On my work computer the jupyter integration does not work, maybe this is due to a more restrictive firewall which blocks communication between the ipython kernel and vscode?

I don't see any error messages in the Output Window at the bottom of vscode if this is what you mean by `python output panel`. 

However, a similar error (though not in red) appear on both machines whenever I run a cell. 

On the working machine I get:
```
webview.ts:78 [Embedded Page] Uncaught TypeError: Cannot use 'in' operator to search for 'text/plain' in ok
```
On broken machine I get:
```
webview.ts:78 [Embedded Page] Uncaught SyntaxError: Invalid Unicode escape sequence
```
Does that ring any bell for you?

**Comment by willyd** [comment]
BTW, thanks to you for your support, good software with good support is always better!

**Comment by DonJayamanne** [comment]
@willyd , please could you ensure you have the latest version of VS Code installed.
Are those the only errors you're getting?

**Comment by willyd** [comment]
Yes both machine have 1.6.1 installed. I actually had another error in the developer tools (this time in red) which came from the CMake Tools extension. Once I uninstalled it the error was gone. Apart from this and the previously mentionned `webview.ts` error I have no other errors.

**Comment by gandhis1** [comment]
The new version works for me. How do I figure out which URL the notebook is located at?

On the capitalization point, look at the below - what looks out of place?

![image](https://cloud.githubusercontent.com/assets/21064086/19542375/a7233f0a-963b-11e6-9d0c-b90bc95b5398.png)

**Comment by DonJayamanne** [comment]
@willyd , having checked it out locally that shouldn't cause any issues.
I'll put some more logging and create a separate build for you.

**Comment by DonJayamanne** [comment]
@gandhis1 , got it thanks

**Comment by DonJayamanne** [comment]
@gandhis1 , please could you create two separate issues (for the REPL and the autocomplete), that way others too could vote for it.
I have a few questions related to the IPYTHON repl, but would like to move that discussion to a separate issue. Please create it and lets carry on from there. 
@gandhis1 , thanks for the great feedback.

>>It's hard to tell what code produced what in your notebook - shouldn't the code be copied to the notebook output as well?

We're working on displaying the results (inline) within the editor similar to Atom. Will keep you posted.

**Comment by DonJayamanne** [comment]
New version has been published

**Comment by Darktex** [comment]
Works like a charm! (Windows 10, Anaconda Python 3.5)

**Comment by willyd** [comment]
@DonJayamanne Any update about the build with more logging? If that's too complicated maybe you could give me some guidelines so I can try to debug this myself?

**Comment by DonJayamanne** [comment]
@willyd 
>update about the build with more logging 

What kind of issues are you experiencing?

**Comment by willyd** [comment]
On one machine I don't get any output in the right pane (I only see Append Results and Clear Results buttons). On another machine everything works as it should.

I was wondering how I could try to pinpoint what's wrong on the first machine. I tried adding exceptions to the firewall for python and VSCode to no avail.

Any idea how I can find what's wrong here?

**Comment by DonJayamanne** [comment]
@willyd  
Is anything displayed in the ```console``` window of ```Help->Developer Tools```
