### ISSUE TITLE
Specify python module path in debug config

### ISSUE THREAD

**Issue by go2sh** [DonJayamanne/pythonVSCode#367]
It would be nice to specify additional paths for python modules (aka PYTHONPATH or sys.path). It would be especially cool to add the current workspace root.

**Comment by DonJayamanne** [comment]
@go2sh , 
The recommended approach is to use the same python path in settings.json and debug configuration. I.e. use the same python interpreter for editing, code intellisense, etc as well as debugging.

The two paths are configured in settings.json and launch.json. The launch.json merely references the value in settings.json, though you could independantly configure the two.

Both environment variables and workspace roots can be referenced as defined here:
https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version#environment-variables-when-configuring-python-interpreter

**Comment by go2sh** [comment]
Its not about the interpreter. Some example directory layout:
```
reglib:
  __init__.py
  moda.py
script:
  run_moda.py
```
Now the problem is, that I want to reference a class in moda in run_moda.py like this:
`from reglib.moda import A`
Debugging the run_moda.py script with fail with import error and also the linter will complain.

It would be ideal to tell python and the linter to use the workspace root as path (PYTHONPATH) for looking for python modules. A virtual environment would not help with that.

**Comment by go2sh** [comment]
By the way calling the option `pythonPath` is a little confusing, since python has a enviroment variable called `PYTHONPATH`, described [here](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH). 

From my point of view it would be nice to have an option to modify the `sys.path` list before running or debugging a script by specifying a list of paths in the run config.

**Comment by DonJayamanne** [comment]
@gosh
You can use the cwd (https://github.com/DonJayamanne/pythonVSCode/wiki/Debugging#cwd) setting  on launch.json to specify the working directory.

**Comment by baconalot** [comment]
@DonJayamanne  Setting the working dir is not enough. I have my code laid out in several projects like @go2sh 's example. I really need to be able to update `$PYTHONPATH` with multiple extra paths before the python executable is invoked. This cannot be solved in the projects themselves with the `sys.path` because production takes a different setup.
This would be needed for all executions of `python.pythonPath`, not only debugging.

**Comment by go2sh** [comment]
You can use the `env` key in the debugging settings to add a `PYTHONPATH` Env-Variable to  the execution, which is recognized by the python interpreter. Though, It's a little confusing overall.
