### ISSUE TITLE
stange quick info for python functions

### ISSUE THREAD

**Issue by largezhou** [DonJayamanne/pythonVSCode#368]
![default](https://cloud.githubusercontent.com/assets/13796692/19269161/820294ec-8feb-11e6-87d0-d1ba8395dc2f.jpg)
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: donjayamanne.python-0.4.0, robertohuertasm.vscode-icons-3.0.1, spywhere.guides-0.5.1

Steps to Reproduce:

1.type a function name, and then you type a '('. 
2.you can see the stange quickinfo...

**Comment by DonJayamanne** [comment]
@largezhou , ouch, this looks like a VS Code (upstream) issue. Will check this out.

**Comment by gandhis1** [comment]
This seems like the same issue I was referencing in #344.

**Comment by gandhis1** [comment]
Not that it really helps solve this issue, but I do get it in multiple places. Long doc-strings appear to be the culprit:

![image](https://cloud.githubusercontent.com/assets/21064086/19543607/ba241cae-9646-11e6-9cea-bd728fa02830.png)

**Comment by DonJayamanne** [comment]
Will look into this today

**Comment by DonJayamanne** [comment]
Fix will be in next release
