### ISSUE TITLE
Jupyter: allow custom ipython path (ipython3)

### ISSUE THREAD

**Issue by mratsim** [DonJayamanne/pythonVSCode#369]
I'm really excited about jupyter support and was eagerly waiting the whole weekend for v0.4.

To have jupyter recognize my python3 kernel I had to symlink ipython3 to ipython. 
`ln -s /usr/local/bin/ipython3 /usr/local/bin/ipython`
Would it be possible to have that as a user setting?

Thanks

**Comment by DonJayamanne** [comment]
Yes sure, will work on this for the next release.

**Comment by DonJayamanne** [comment]
@mratsim , how did you manage to install ipython3?
Also, if you have any suggestions/feature requests please do create issues for them.

**Comment by mratsim** [comment]
I'm on macOS and used Homebrew to install python3.

Then I used "pip3" to install jupyter, ipython and everything else.

**Comment by DonJayamanne** [comment]
@mratsim 
the next version (will be published today) will pick ipython/jupyter from the interpreter [configured for the extension](https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version#selecting-an-interpreter).
Most of the discussion can be found here. https://github.com/DonJayamanne/pythonVSCode/issues/366

Closing this as the next version to be published today resolves this. Please reopen if it is still a issue after the new release.

**Comment by mratsim** [comment]
Tested version 5.0 before publication. It works for me as well on OSX + Python3/Ipython/Jupyter installed through Homebrew.

Thanks !
