### ISSUE TITLE
format code not working

### ISSUE THREAD

**Issue by cuongtranba** [DonJayamanne/pythonVSCode#370]
I have configured setting.json to use autopep8 formatting but it's seem not working when I use format code in VS code (Ctrl+Shift+I)
here is my setting.json
`
{
    "python.pythonPath": "/usr/bin/python3",
    "python.formatting.provider": "autopep8",
    "python.unitTest.unittestEnabled": true,
    "python.unitTest.pyTestEnabled": false,
    "python.unitTest.nosetestsEnabled": false
}`
Thanks

**Comment by DonJayamanne** [comment]
@cuongtranba 
Are any errors being displayed in the ```Python``` output panel?
Please check the following troubleshooting sections:  
- [Troubleshooting-Formatting](https://github.com/DonJayamanne/pythonVSCode/wiki/Troubleshooting-Formatting)  
- Check if errors are displayed in the ```Python``` output panel (Go to menu ->View->Output)

**Comment by cuongtranba** [comment]
@DonJayamanne  Thank for your reply
I will try again.

**Comment by cuongtranba** [comment]
Resolved I will close issues. Thanks
