### ISSUE TITLE
Enhancement: Add shortcuts for Jupyter

### ISSUE THREAD

**Issue by mratsim** [DonJayamanne/pythonVSCode#371]
I suspect a lot of users of Jupyter will use it for the instant feedback. Currently there is no keyboard shortcuts. Here are the default ones from [Ipython](https://ipython.org/ipython-doc/1/interactive/notebook.html#keyboard-shortcuts).

I suspect there are conflicts for the Shift/Alt/Ctrl+Enter shortcuts so Atom-Hydrogen shortcuts might be better:

![image](https://cloud.githubusercontent.com/assets/22738317/19278969/a83bcbbc-8fdf-11e6-9ab3-1d267e1812fd.png)

**Comment by gandhis1** [comment]
I second these thoughts, and asked for them previously. I do believe there should be a default shortcut configuration, instead of leaving it up to the user.

**Comment by DonJayamanne** [comment]
@mratsim , @gandhis1 , please suggest keyboard shortcuts and I'll add them for the next release.

**Comment by DonJayamanne** [comment]
Short cut added for executing a line/selectiong.

**Comment by gandhis1** [comment]
Hey Don,

Looks like the shortcut chosen (CTRL+ALT+Enter) conflicts with the find+replace shortcut of replace all (CTRL+Alt+Enter). Didn't realize this when I suggested it, but having accidentally triggered Jupyter when in reality I wanted to find and replace all, this won't work. 

Is Ctrl+Enter taken by anything?

**Comment by DonJayamanne** [comment]
From what I could find it wasn't taken up by anything. This is very difficult to find. VS Code team too are finding it difficult to add shortcuts as plenty of them are taken up, that's primarily why i'm reluctant to add any ( and why i added only one shortcut).
Will change it to something else in the next version, a conflicting with find+replace is a big one.

**Comment by gandhis1** [comment]
Don, I think I've figured this out. First, let me paste in the default keybindings:

{ "key": "ctrl+alt+enter",        "command": "editor.action.replaceAll",
                                               "when": "editorFocus && findWidgetVisible" },
{ "key": "ctrl+alt+enter",        "command": "search.action.replaceAll",
                                              "when": "replaceActive && searchViewletVisible && !findWidgetVisible" },
{ "key": "ctrl+alt+enter",        "command": "jupyter.runSelectionLine" },

You see what the solution is? It should be this:

{ "key": "ctrl+alt+enter",        "command": "jupyter.runSelectionLine
                                               "when": "editorFocus && !replaceActive && !searchViewletVisible && !findWidgetVisible" },
