### ISSUE TITLE
Error: UnicodeDecodeError: 'charmap' codec can't decode byte 0x98

### ISSUE THREAD

**Issue by IgorNovozhilov** [DonJayamanne/pythonVSCode#372]
```
Error (stderr) Traceback (most recent call last):
  File "completion.py", line 336, in watch
    self._process_request(self._input.readline())
  File "completion.py", line 313, in _process_request
    column=request['column'], path=request.get('path', ''))
  File "C:\Users\user1\.vscode-insiders\extensions\donjayamanne.python-0.4.1\pythonFiles\jedi\api\__init__.py", line 91, in __init__
    source = f.read()
  File "C:\Python33\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 107: character maps to <undefined>

```

**Comment by DonJayamanne** [comment]
@IgorNovozhilov 
Please could you provide the following information:
- OS
- Version of Python
- Sample python code used to replicate this issue

**Comment by IgorNovozhilov** [comment]
![2016-10-12_08h51_04](https://cloud.githubusercontent.com/assets/3082812/19299308/4ae72ff6-905c-11e6-87b2-50b66bf8ee43.png)

python 3.3

```
''' Функция проверки ИНН и КПП '''
def CheckInnKpp( inn, kpp=None ):
   return True
```

**Comment by DonJayamanne** [comment]
@IgorNovozhilov , please could you try this with the standard release instead of the insiders build?
Thanks

**Comment by IgorNovozhilov** [comment]
![2016-10-12_09h32_28](https://cloud.githubusercontent.com/assets/3082812/19299727/ce48ef22-905e-11e6-856f-5246bae832eb.png)

```
Error (stderr) Traceback (most recent call last):
  File "completion.py", line 336, in watch
    self._process_request(self._input.readline())
  File "completion.py", line 313, in _process_request
    column=request['column'], path=request.get('path', ''))
  File "C:\Users\user1\.vscode\extensions\donjayamanne.python-0.4.1\pythonFiles\jedi\api\__init__.py", line 91, in __init__
    source = f.read()
  File "C:\Python33\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 83: character maps to <undefined>

```

**Comment by DonJayamanne** [comment]
@IgorNovozhilov 
please could you check the value of ```locale.getpreferredencoding(False)```
- Open a terminal window and execute the above command in Python 
- Open a terminal window inside VS Code (integrated terminal) and execute the above command  

Also, did this work in the past?

**Comment by DonJayamanne** [comment]
Also, please could you try the following:

Where ```path``` is the fully qualified path to the file in question.
```python
    print(locale.getpreferredencoding(False))
    with open(path) as f:
        source = f.read()
```

Finally, please could you help diagnose this issue.
Please modify the following file (before line 90):
- ```C:\Users\user1\.vscode\extensions\donjayamanne.python-0.4.1\pythonFiles\jedi\api\__init__.py```  
- Add some code to create a temporary file 
- To that temporary file write out the value of ```locale.getpreferredencoding(False)```

What I'd like to check is the encoding in the process that is opening the text file. (i.e. we're debugging here - a very dirty and old fashioned way :))
Thanks

**Comment by IgorNovozhilov** [comment]
![2016-10-12_09h44_20](https://cloud.githubusercontent.com/assets/3082812/19300100/f617550a-9060-11e6-9dbd-7a5aee4a4009.png)

**Comment by IgorNovozhilov** [comment]
![2016-10-12_09h57_14](https://cloud.githubusercontent.com/assets/3082812/19300311/497eb0c0-9062-11e6-9fac-38f30bf032b0.png)

**Comment by DonJayamanne** [comment]
@IgorNovozhilov , thanks

**Comment by IgorNovozhilov** [comment]
I think to read a file you need to use the definition of the encoding and not to use the OS encoding by default.

![2016-10-12_10h09_15](https://cloud.githubusercontent.com/assets/3082812/19300679/3bfcf4aa-9064-11e6-9efa-9b9a18fd80a2.png)

**Comment by DonJayamanne** [comment]
@IgorNovozhilov 
Please could you uninstall the Python extension and install the older version (```0.3.24```). I'm baffled here. Can't understand what's going on. 
- Download and install the previous version of the extension (version ```0.3.24```)
    + https://donjayamanne.gallery.vsassets.io/_apis/public/gallery/publisher/donjayamanne/extension/python/0.3.24/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage?install=true)
    + Rename the downloaded Microsoft.VisualStudio.Services.VSIXPackage package's file extension to Microsoft.VisualStudio.Services.vsix.
    + Run code Microsoft.VisualStudio.Services.vsix as described in the [installation instructions](https://code.visualstudio.com/docs/extensions/install-extension#_install-a-packaged-extension-vsix).
    + Restart the editor.
    + **Can you replicate this issue?**

**Comment by DonJayamanne** [comment]
@IgorNovozhilov , thanks for that. Please could you try the above suggestion. Thanks.
That should be it.

**Comment by IgorNovozhilov** [comment]
Yes, version 0.3.24 is works without that error

![2016-10-12_10h17_59](https://cloud.githubusercontent.com/assets/3082812/19301427/2acb0a92-9068-11e6-9a53-c4a3ef285cca.png)

**Comment by DonJayamanne** [comment]
Yay, now to try and identify the change and fix it.

**Comment by IgorNovozhilov** [comment]
Like this
http://ru.stackoverflow.com/questions/517085/python-charmap-codec-cant-decode-byte-0x98

**Comment by IgorNovozhilov** [comment]
So #374
And I think that's not all, to support the extension work on localization different from "en-us", you must add a second argument to "open", indicating the encoding of the file. Otherwise, open uses the system encoding which may differ from 'utf-8'

**Comment by DonJayamanne** [comment]
I think the problem is a change was introduced that has broken the code. As you identified it worked in the previous version. So the solution I would employ is to revert the problematic changes

**Comment by DonJayamanne** [comment]
Thanks for your research and feed back.

**Comment by DonJayamanne** [comment]
@IgorNovozhilov , new version has been published, please test.
Thanks for your help.

**Comment by DonJayamanne** [comment]
Updated readme accordingly.
https://github.com/DonJayamanne/pythonVSCode/tree/master#thanks
Will ensure this goes into the new build. Was keen on publishing the build (remembered to add this after the build sorry).
This will be in the next build.

**Comment by DonJayamanne** [comment]
@IgorNovozhilov , thanks a lot for your patience and effort in identifying the cause.
