### ISSUE TITLE
Error: Ensure you have a Jupyter/IPython and the prerequisites installed

### ISSUE THREAD

**Issue by leido** [DonJayamanne/pythonVSCode#373]
I'm very excited about Jupyter/Ipython feature support. But do I really need to install Anaconda for this to work? For some reason, I don't really want to install anaconda because it has its own python executable which is conflicted with system's python executable. Besides, I have to customize the python path manually if using Anaconda.

I've installed jupyter and ipython on my computer through pip, as well as libzmq3-dev using apt, but I've still get an error.(I want to use python3 jupyter kernel.)

I assume there are some dependencies specifically in Anaconda, hope you can point out, so I can install them using pip on my computer instead of INSTALL Anaconda as a whole.
  

VSCode: 1.6.0
Python extension: 0.4.1
System Python version: 3.5.2

**Comment by DonJayamanne** [comment]
Please could you provide the error message displayed in the ```Python``` output panel.

**Comment by leido** [comment]
@DonJayamanne 
I right click the file, and select `Run Python File In Terminal`, the output is fine and no error accrued.
```
#!/usr/bin/python3

#%%
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-3, 3, 100)
plt.plot(x, np.sin(x)+x)
plt.show()
```
Then I toggled development mode of vscode, here is the console error:
![error_vscode](https://cloud.githubusercontent.com/assets/6065941/19301851/1c035984-9094-11e6-98dc-c6a86b165926.png)

**Comment by DonJayamanne** [comment]
Closing this, as the solution of removing the dependency on zmq will revolve this, tracked in #366

**Comment by leido** [comment]
I'm looking forward to that, thanks.
