### ISSUE TITLE
Debug python odoo application can't restart or stop properly

### ISSUE THREAD

**Issue by hulb** [DonJayamanne/pythonVSCode#376]
when I'm using python-extension in vscode to debug a odoo application which is written in python, I can't restart or stop the debug process properly when a breakpoint is hitten.There are more info below:

VSCode Version: Code 1.6.0 (e52fb0b, 2016-10-10T18:28:55.412Z)
OS Version: Darwin x64 16.0.0
Extensions: donjayamanne.python-0.4.1
Steps to Reproduce:

1.set a breakpoint
2.run debug mode
3.hit the breakpoint
4.restart the debug
5.it shows the address my web application used before is already in use.It tells me that the previous process doesn't end properly.

and my luanch setting:
{
"name": "odoo",
"type": "python",
"request": "launch",
"stopOnEntry": false,
"pythonPath": "/Users/xxx/.virtualenvs/odoo/bin/python",
"program": "/Users/xxx/Documents/workspace/code/yy/start",
"args": [
"-c",
"/Users/xxx/Documents/workspace/code/yy/openerp-server.conf"
],
"debugOptions": [
"WaitOnAbnormalExit",
"WaitOnNormalExit",
"RedirectOutput"
]
},
and I'm using virtualenv,the python version is 2.7.11

**Comment by DonJayamanne** [comment]
@hulb 
Are you still experiencing this issue with the latest version of the extension?

**Comment by hulb** [comment]
sorry,quit busy recently.Yes, problem is still there.I just check it again.
