### ISSUE TITLE
[Feature Request] Please implement debugging of jinja templates

### ISSUE THREAD

**Issue by xqliu** [DonJayamanne/pythonVSCode#377]
Dear,

As many python forks are using flask as the framework and using jinja as the template engine, could you please also implement debug of jinja template also?

Thanks for your great help and this great plugin here 👍 💯

**Comment by DonJayamanne** [comment]
Closing as this is looking too difficult. Wouldn't accept PR if someone is willing to contribute.
On a side note, PyCharm too doesn't support jinja template debugging.

**Comment by xqliu** [comment]
@DonJayamanne Actually pycharm do support jinja2 template debuging and I am living on that :)
