### ISSUE TITLE
Debugger breaks on GeneratorExit when "Uncaught Exceptions" is checked

### ISSUE THREAD

**Issue by dolevdotan** [DonJayamanne/pythonVSCode#379]
When the "Uncaught Exceptions" checkbox is checked, the debugger breaks at generator expressions such as
`if any(a.val == 0 for a in arr):`

I'm running on:
Python 3.4.3 |Anaconda 2.3.0 (64-bit)| (default, Mar  6 2015, 12:06:10) [MSC v.1600 64 bit (AMD64)] on win32

**Comment by DonJayamanne** [comment]
Interesting. For some reason Python 3.5 throws these as errors and not Pyton 2.7
https://docs.python.org/2/library/exceptions.html#exceptions.StandardError

Fixed (to ignore this error, unless overridden by the user) and will be in the next release.
