### ISSUE TITLE
VSC with Python reads / as floor division (// works fine)

### ISSUE THREAD

**Issue by Pawlowskieiro** [DonJayamanne/pythonVSCode#380]
I've been using VSC 1.6.0 for Mac (OS Sierra 10.12) for about a week now and have encountered an issue with division. The problem is, when I try to apply division, VSC prints the result as if it was performing floor division (when I tell it to perform floor division (//)  it works fine). So, basically I cannot perform regular division and get any decimals.

I'm stuck with coding and have no idea what to do about it. I'd much appreciate any help 👍

**Comment by Resousse** [comment]
Hi,
Is it python 2 or 3?
Is this behavior similar when you run this without debuger (using python command on a regular terminal)?
http://stackoverflow.com/questions/1267869/how-can-i-force-division-to-be-floating-point-in-python
Thanks

**Comment by Pawlowskieiro** [comment]
Hi!

Thanks for replying so fast! It is python 3, and it only occurs in VSC. When I run it in the shell, everything works fine.

Also, I looked up the page you sent me and I just noticed that true division (/) works fine if only I add a dot to a number, either the dividend or the divider, say „3." instead of just „3”. I have no idea why it does it or how to make it default

Thanks again!

**Comment by DonJayamanne** [comment]
@Pawlowskieiro , 
please could you give me an example of what works outside vs code and what doesn't? Thanks

**Comment by DonJayamanne** [comment]
@Pawlowskieiro 
Closing this issue. Please provide the information requested and the re-open it, thanks.
