### ISSUE TITLE
extension fails to activate

### ISSUE THREAD

**Issue by beefybug** [DonJayamanne/pythonVSCode#382]
The extension fails to activate on both 1.6 and 1.7 insider on windows 7.

This is the error message.

![image](https://cloud.githubusercontent.com/assets/7582689/19354545/1e1ae826-9135-11e6-9138-31f24c4d2717.png)

**Comment by DonJayamanne** [comment]
@beefybug 
Untill the new release you could try the following:  
- Open the following file (displayed above in the error): 
```
c:\Users\jliu\.vscode-insiders\extensions\donjayamanne.python-0.4.2\out\client\common\telemetry.js
```
- Remove line 57
- Remove line 65

This should fix it. Let me know if it doesn't
