### ISSUE TITLE
Jupyter: Setting Remote Kernel

### ISSUE THREAD

**Issue by anjueappen** [DonJayamanne/pythonVSCode#383]
Is there a way to set a custom IP for accessing a remote Jupyter notebook? Didn't see anything that we could configure, currently.

**Comment by DonJayamanne** [comment]
Unfortunately not yet.

**Comment by Earthson** [comment]
Is there a way to connect to existing kernel by %connect_info?

http://jupyter-notebook.readthedocs.io/en/latest/examples/Notebook/Connecting%20with%20the%20Qt%20Console.html#The-Frontend/Kernel-Model

**Comment by DonJayamanne** [comment]
Unfortunately this isn't supported as of yet and will be looked at for a future release.

**Comment by mkohram** [comment]
I would be more than glad to help with getting existing implemented if I could get a couple of pointers where to start. Please let me know.

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/vscodeJupyter#26
