### ISSUE TITLE
Wiki Issues

### ISSUE THREAD

**Issue by noahleigh** [DonJayamanne/pythonVSCode#384]
The big [More Options](https://github.com/DonJayamanne/pythonVSCode/wiki/UnitTests#more-options) link on the [UnitTests](https://github.com/DonJayamanne/pythonVSCode/wiki/UnitTests) page is broken. It goes to:

https://github.com/DonJayamanne/pythonVSCode/wiki/Unitest:-Advanced-Options

when it should go to:

https://github.com/DonJayamanne/pythonVSCode/wiki/Unitest:-More-Options

---
The instructions for [Running Tests](https://github.com/DonJayamanne/pythonVSCode/wiki/UnitTests#running-tests) look like an unformatted ordered list, but I believe it should be an unordered list (properly formatted).

**Comment by DonJayamanne** [comment]
@noahleigh , fixed thanks heaps
