### ISSUE TITLE
Test Discovery Failed

### ISSUE THREAD

**Issue by noahleigh** [DonJayamanne/pythonVSCode#386]
When I try to discover unittest tests, this is the output from the Python Test Log:
``` 
Test Disovery failed: 
Command failed: D:/Anaconda2/python.exe -c import unittest 
loader = unittest.TestLoader() 
suites = loader.discover("./tests", pattern="test*.py") 
print("start") #Don't remove this line 
for suite in suites._tests: 
    for cls in suite._tests: 
        try: 
            for m in cls._tests: 
                print(m.id()) 
        except: 
            pass 

``` 
When I run that same code as a python script at the root of my workspace it seems to work just fine (prints a list of `unittest.TestCase` classes). 

My `./tests` folder has an `__init__.py` file in it, but it doesn't seem to make any difference. 

Any guidance?

**Comment by DonJayamanne** [comment]
@noahleigh , aren't there any other errors?

**Comment by DonJayamanne** [comment]
@noahleigh 
Please could you provide the output of your script? (when you run the above code as a script in the root directory).
Thanks

**Comment by noahleigh** [comment]
No other errors that I can see. Clicking on `Discover Tests` just prints that message again with an "There was an error in discovering tests" alert bar. 

Here is the output when I run the script myself:
```python
start 
test_archive_utils.UnzipArchivesTest.test_unzip_archives 
test_helper_functions.StandaloneFunctionTest.test_is_dir_stable 
test_helper_functions.StandaloneFunctionTest.test_listdir_files 
test_helper_functions.StandaloneFunctionTest.test_matches_patterns 
test_helper_functions.StandaloneFunctionTest.test_move_files_with_patterns 
test_helper_functions.StandaloneFunctionTest.test_move_folder_contents 
test_helper_functions.StandaloneFunctionTest.test_remove_dir_contents 
test_parser.ParserComponentsTest.test_archive_file
test_parser.ParserComponentsTest.test_cleanup_already_processed_delete 
test_parser.ParserComponentsTest.test_cleanup_already_processed_segregate 
test_parser.ParserComponentsTest.test_get_acid
```

**Comment by DonJayamanne** [comment]
@noahleigh 
thanks, I believe i have identified the issue. Hope you can wait till monday for a fix (new release).

**Comment by DonJayamanne** [comment]
@noahleigh ,nope, i think you can use the following workaround for now:

```json
    "python.unitTest.unittestEnabled": true,
    "python.unitTest.unittestArgs": [
        "",
        "-s=./tests",
        "-p=test_*.py"
    ]
```

**Comment by DonJayamanne** [comment]
Please could you show me your settings.json

**Comment by DonJayamanne** [comment]
@noahleigh , fixed and build will be released early next week.
Will provide a patch for you (that you can apply at your end) until the release

**Comment by DonJayamanne** [comment]
Identify the location of the python extension:
- Generally located here ```C:\Users\xxxx\.vscode\extensions\donjayamanne.python-0.4.2```  
- Copy the attached file into the ```out\client\unittests\unittest```  sub-directory (overwriting the existing ```collector.js``` file)   

- Restart VS Code and test

**Comment by noahleigh** [comment]
After overwriting `collector.ts` with the version in d4e9712, there is no `Discover Tests` button on the status bar any longer.

**Comment by DonJayamanne** [comment]
You need to open a python file, for the Burton to appear.

**Comment by noahleigh** [comment]
I reopened the same Python workspace and files, and no button appeared.

Current `settings.json`: 

```json 
// Place your settings in this file to overwrite the default settings 
{ 
"python.pythonPath": "D:/Anaconda2/python.exe", 
"http.proxyStrictSSL": false, 
"git.enabled": true, 
"files.associations": 
{ 
"*.pyx": "python", 
".coveragerc": "ini", 
".pylintrc": "ini", 
"*.cls": "vb", 
"*.frm": "vb", 
"*.bas": "vb" 
}, 
"files.exclude": 
{ 
"**/*.pyc": true, 
"**/*.frx": true 
}, 
// Define profile for specified syntax or use your own profile with specific rules. 
"emmet.syntaxProfiles": { 
"python": "html" 
}, 
"editor.rulers": [100], 

// Whether to enable or disable unit testing using unittest. 
"python.unitTest.unittestEnabled": true, 
"python.unitTest.unittestArgs": [ 
"", 
"-s=./tests", 
"-p=test_*.py" 
], 

"telemetry.enableTelemetry": false, 
"telemetry.enableCrashReporter": false, 

"editor.renderIndentGuides": true, 
"editor.mouseWheelZoom": true, 
"editor.fontSize": 14, 
"files.trimTrailingWhitespace": true, 

// Automatically update extensions 
"extensions.autoUpdate": false 
} 
```

**Comment by DonJayamanne** [comment]
@noahleigh , apologies I should have uploaded the transpiled javascript file. here it is and please follow the instructions outlined (same as earlier):   

Identify the location of the python extension:
- Generally located here ```C:\Users\xxxx\.vscode\extensions\donjayamanne.python-0.4.2```  
- Extract the **attached** 
_**javascript**_ file into the ```out\client\unittests\unittest```  sub-directory (overwriting the existing ```collector.js``` file)   

- Restart VS Code and test  

[collector.js.zip](https://github.com/DonJayamanne/pythonVSCode/files/532129/collector.js.zip)

**Comment by DonJayamanne** [comment]
@rica-benhossi , I believe I have identified the issue. Will get back to you soon.

**Comment by DonJayamanne** [comment]
@noahleigh 
Please try the following, the problem was I hadn't provided you with the transpiled javascript file:

Identify the location of the python extension:
- Generally located here ```C:\Users\xxxx\.vscode\extensions\donjayamanne.python-0.4.2```  
- Extract the attached javascript file (from [collector.js.zip](https://github.com/DonJayamanne/pythonVSCode/files/532137/collector.js.zip)) into the ```out\client\unittests\unittest```  sub-directory (overwriting the existing ```collector.js``` file)   

- Restart VS Code and test

**Comment by noahleigh** [comment]
The issue remains after replacing `collector.js`. No change in output. Perhaps you could add some extra debugging logs to the Python Test Log?
