### ISSUE TITLE
Command python.execSelectionInTerminal is not executing all commands

### ISSUE THREAD

**Issue by rica-benhossi** [DonJayamanne/pythonVSCode#387]
I've been trying to run some piece of code on terminal using this command, but the selected code never run properly. Seems that the command run it line by line, using the command python -c "commands" which makes the terminal not run all the selected lines. Follow the terminal message:

Microsoft Windows [Version 10.0.14942]
(c) 2016 Microsoft Corporation. All rights reserved.
C:\Development\Python\PythonTrainning>c:\python35\python.exe -c "x = 'text on a string'
C:\Development\Python\PythonTrainning>print('test')
Unable to initialize device PRN
C:\Development\Python\PythonTrainning>print(x)"
C:\Development\Python\PythonTrainning>

**Comment by DonJayamanne** [comment]
What command are you trying you execute?
Please send that through.

**Comment by rica-benhossi** [comment]
I'm trying to run this code as an example:

x = 'text on a string'
print('test')
print(x)

If I select only the command print('test') it works ok. But all the commands together, doesn't work. Even if we select same commands. In the example below, the first command runs ok, but the second doesn't run.

print('first command')
print('second command')

Here's the result:

Microsoft Windows [Version 10.0.14946]
(c) 2016 Microsoft Corporation. All rights reserved.
C:\Development\Python\PythonTrainning>c:\python35\python.exe -c "print('first command')
first command

C:\Development\Python\PythonTrainning>print('second command')"
C:\Development\Python\PythonTrainning>

**Comment by DonJayamanne** [comment]
@rica-benhossi , I believe I have identified the issue. Will get back to you soon.

**Comment by rica-benhossi** [comment]
Great... Thank you for replying.

**Comment by KrugerMN** [comment]
Hi Don how did u do it?
