### ISSUE TITLE
Bundle ZeroMQ rather than requiring a separate install

### ISSUE THREAD

**Issue by kuza55** [DonJayamanne/pythonVSCode#388]
I'm particularly interested in this for windows since installing ZeroMQ on windows requires a compiler and I don't really want to install VC++.

The people working on Hydrogen (which has similar Jupyter functionality for Atom) are working on making this poissible for their project and you can see the progress here: https://github.com/nteract/zmq-prebuilt/issues/2

**Comment by DonJayamanne** [comment]
Couple of problems:. 
- End user needs node.js installed
- It is only backwards compatible, not forward ( so when a new version of node is released with vscode, then we need a new version of this zmq and ends user needs to install a new version as well)
- Complicated setup for end user  and maintainers

Removing zmq and just relying on python fixes it, which is what I am currently working on.

**Comment by DonJayamanne** [comment]
Thanks for the great research and sharing it.
