### ISSUE TITLE
jmp + Windows

### ISSUE THREAD

**Issue by rgbkrk** [DonJayamanne/pythonVSCode#389]
Hey @DonJayamanne, I just noticed you're using `spawnteract` and `jmp`, and that you're hoping to support Windows soon. The latest release of `jmp` now relies on [`zmq-prebuilt`](https://github.com/nteract/zmq-prebuilt) which, when rebuilt with Electron headers, will rebuild appropriately. @lgeiger and a bunch of folks (even upstream in ZMQ) got us into a state of making Windows practically easier than *nix.

Anyways, happy to open a dialogue and collaborate with you for Jupyter support in VSCode. 😄

**Comment by DonJayamanne** [comment]
@rgbkrk oh yes I am interested, let's resume or conversion in three  days (It is saturday and 7 yr daughter's birthday today, Ie very busy today).

However what I learnt is that this is only backwards compatible. Ie when a new version of node is released with electron, end user will need a new version installed (it isn't forward compatible).

**Comment by DonJayamanne** [comment]
Fyi - My plan is to bring in this zmq for other languages using zmq-prebuilt, but that's a separate task for later.

**Comment by rgbkrk** [comment]
> when a new version of node is released with electron, end user will need a new version installed (it isn't forward compatible).

That is very correct. What we're figuring out for Hydrogen (in Atom) is to make sure that the fallback to building from source occurs.

In https://github.com/nteract/nteract we build from source and publish static binaries for node zmq.

**Comment by rgbkrk** [comment]
> oh yes I am interested, let's resume or conversion in three days

Sounds great, I'll be around. Enjoy family time!

**Comment by DonJayamanne** [comment]
On second thought I will use prebuilt at least for now, thanks. Fixes  issues with Windows, I.e makes it easier for all. Thanks

**Comment by lgeiger** [comment]
@DonJayamanne I'm happy to see our packages in use.

We are also moving to `zmq-prebuilt` in Hydrogen (Atom) [here](https://github.com/nteract/hydrogen/pull/476). Let us know if you experience any trouble with it.

**Comment by DonJayamanne** [comment]
Closing as I have opted to go with a python only solution for now, to avoid the head aches of the native dependency. Will revisit this when zmq-prebuilt is stable.
