### ISSUE TITLE
pythonVSCode vs Idle problem

### ISSUE THREAD

**Issue by BigRex** [DonJayamanne/pythonVSCode#390]
I'm new to VS Code and I can't get my script back-up snippet to run in pythonVSCode that works fine in IDLE.  When I run the script inside pythonVSCode and coderunner, it fails at Script = Scripts[-1]

Here's the offender:

from os import listdir, path
from shutil import copyfile
from time import asctime
import sys
import string
import time as ti
from datetime import datetime

#####################################################
###Timekeeping Stuff#################################
#####################################################
####################################################
###Back-Up Stuff#################################
#####################################################
flineo = sys._getframe()
## define timestamp
FORMATY = '%Y'
FORMATm = '%m'
FORMATd = '%d'
FORMATH = '%H'
FORMATM = '%M'

stamp =  '%s_%s_%s_%s_%s' % (datetime.now().strftime(FORMATY),datetime.now().strftime(FORMATm),
                                   datetime.now().strftime(FORMATd),datetime.now().strftime(FORMATH),
                                   datetime.now().strftime(FORMATM))

LocalPath = '.'
Scripts = [s for s in listdir(LocalPath)
     if path.isfile(path.join(LocalPath, s))]
Scripts = (sorted( f for f in listdir(LocalPath) if f.endswith('.py')))
Scripts.sort(key=lambda s: path.getmtime(path.join(LocalPath, s)))
Script = Scripts[-1]

##ScriptBU = path.join('M:\Scripts',stamp+'_'+Script)
##copyfile(Script, ScriptBU)
ScriptBU_2 = path.join('C:\Users\Bruno\OneDrive\Scripts',stamp+'_'+Script)
copyfile(Script, ScriptBU_2)
print flineo.f_lineno, 'Now its', asctime(),'\n',Script,'is backed up and running'
##############################################################
#################################################################

**Comment by DonJayamanne** [comment]
@BigRex , ow are you running this script in code runner? 
Please could you provide the contents of tasks.json file.

**Comment by BigRex** [comment]
As you guessed I'm new to the environment.  I installed code runner and I kick it off with a right click of the mouse.  I also ran the script with the MS default Run Python in Terminal Window command with the same result. BTW,  I've run several other Python scripts and they work fine. 

Here is the settings.json file:

{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "npm",
    "isShellCommand": true,
    "showOutput": "always",
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "install",
            "args": ["install"]
        },
        {
            "taskName": "update",
            "args": ["update"]
        },
        {
            "taskName": "test",
            "args": ["run", "test"]
        }
    ]
}

**Comment by DonJayamanne** [comment]
@BigRex , if the issue is with Code Runner, then please raise an issue in that repo.

**Comment by BigRex** [comment]
It's not coderunner.  The VSCode Python runner flunked in the same place,
too.

**Comment by DonJayamanne** [comment]
@BigRex , please provide the following information in detail necessary to replicate this issue.
At the moment none of this is making sense. If this has nothing to do with code runner or anything similar, then please don't mention them, that's just noise that adds to the confusion.

**Comment by BigRex** [comment]
Don,

I'm sorry about the confusion with my original post.  When I run the script below VSCode I get an error:
--------------------------------------------------------------------------
from os import listdir, path
from shutil import copyfile
from time import asctime
import sys
import string
import time as ti
from datetime import datetime

###Back-Up Stuff#################################
#####################################################
flineo = sys._getframe()
## define timestamp
FORMATY = '%Y'
FORMATm = '%m'
FORMATd = '%d'
FORMATH = '%H'
FORMATM = '%M'

stamp =  '%s_%s_%s_%s_%s' % (datetime.now().strftime(FORMATY),datetime.now().strftime(FORMATm),
                                   datetime.now().strftime(FORMATd),datetime.now().strftime(FORMATH),
                                   datetime.now().strftime(FORMATM))

LocalPath = '.'
Scripts = [s for s in listdir(LocalPath)
     if path.isfile(path.join(LocalPath, s))]
Scripts = (sorted( f for f in listdir(LocalPath) if f.endswith('.py')))
Scripts.sort(key=lambda s: path.getmtime(path.join(LocalPath, s)))
Script = Scripts[-1]

ScriptBU_2 = path.join('C:\Users\Bruno\OneDrive\Scripts',stamp+'_'+Script)
copyfile(Script, ScriptBU_2)
print flineo.f_lineno, 'Now its', asctime(),'\n',Script,'is backed up and running'
##############################################################

print 'hello world'
-----------------------------------------------------------------------------------

VSCode kicks out the following error in the terminal:

**Comment by DonJayamanne** [comment]
You are getting an error in your code. Have you tried to identify what is wrong with the code? 

You are getting an index out of range rite at lube 34? Do you know why? My suggestion usd you first try to understand the bug.

**Comment by BigRex** [comment]
Its only a bug inside VS Code.  I've been using the scrap I submitted for
several years now.  In addition,  I checked the script I submitted with
IDLE and Powershell and it ran fine.  The error is being thrown with a [-1]
list statement.

**Comment by DonJayamanne** [comment]
@BigRex , Im' sorry, but you don't seem to have made any attempt to identify what is wrong. All you are doing is referring to an error message. You need to take the initiative of debugging the code and figuring out why it isn't working (this is your code).

It is obvious something is wrong with the following code:
```python
LocalPath = '.'
Scripts = [s for s in listdir(LocalPath)
if path.isfile(path.join(LocalPath, s))]
Scripts = (sorted( f for f in listdir(LocalPath) if f.endswith('.py')))
Scripts.sort(key=lambda s: path.getmtime(path.join(LocalPath, s)))
Script = Scripts[-1]
```

You need to find out why your code is falling over. for instance have you tried the following:
```python
LocalPath = '.'
Scripts = [s for s in listdir(LocalPath)
print Scripts
```

As mentioned earlier, this is a problem with your code. Not VS Code. 
For instance are you running this code from the same directory and same permissions, etc.

**Comment by BigRex** [comment]
We' ll just have to agree to disagree.  I've now tried the same code with
three IDEs and still problems in VSCode.
