### ISSUE TITLE
Should StopIteration be considered an "Uncaught Exception"?

### ISSUE THREAD

**Issue by tillahoffmann** [DonJayamanne/pythonVSCode#392]
When the checkbox next to "Uncaught Exceptions" is ticked in the "Breakpoints" section of the debug view, the debugger breaks whenever a generator is exhausted. Is that intended or should that be considered a bug? Minimal example to reproduce:

```python
def generator():
    for i in range(5):
        yield i


for x in generator():
    print(x)
```

**Comment by DonJayamanne** [comment]
Interesting. For some reason Python 3.5 throws these as errors and not Pyton 2.7
https://docs.python.org/2/library/exceptions.html#exceptions.StandardError

Fixed (to ignore this error, unless overridden by the user) and will be in the next release.

**Comment by tillahoffmann** [comment]
Great! Thanks for all your work on this project.
