### ISSUE TITLE
snippet stop working after extension installed

### ISSUE THREAD

**Issue by hanbaobao2005** [DonJayamanne/pythonVSCode#397]
Issue description:
1. OS: windows 10 Pro 1607 x64
2. Install VS code on D: drive which is not OS drive
3. snippet works before I install the extension
4. my python path is D:/Program Files (x86)/python3.5/python.exe, and I configured setting item:
"python.pythonPath": "\"D:/Program Files (x86)/python3.5/python.exe\""
5. Snippet stops to work after I install the extension: the snippet doesn't pop up anymore.

Expectation:
Snippet should works after I install the extension.

More info:
I installed the extension on other windows 2008 R2 which python path is 'C:/Python34/python.exe', snippet works well.

I would like to provide more info to locate the root cause.
Thanks,

**Comment by DonJayamanne** [comment]
Please confirm you have installed the extension correctly and are trying this on a python  file. 
Snippets require absolutely no configuration, I.e it has no dependency on the python path.

**Comment by hanbaobao2005** [comment]
My VSCode version: 1.6.1
Extension version: 0.4.2
I installed the extension from the extension bar, and I indeed opened a Python file. 
I tried it many times and found that snippets pop up stop working after I installed the extension. 
I would like to collect the logs for issue analysis.

**Comment by DonJayamanne** [comment]
Unfortunately no logs are generated. If snippets work on one OS and not the other, then this is an upstream issue, i.e. a VS Code issue.
Are snippets working in other languages, such as HTML or JavaScript..

**Comment by hanbaobao2005** [comment]
Got it, Thanks for your info.

**Comment by hanbaobao2005** [comment]
Related issue: https://github.com/Microsoft/vscode/issues/13980

**Comment by hanbaobao2005** [comment]
@DonJayamanne is it possible that autocomplete function affects snippet?
Thanks,

**Comment by DonJayamanne** [comment]
Snippets and auto complete are completely different and managed by vs code.

**Comment by hanbaobao2005** [comment]
@DonJayamanne 
Please access my PC by teamviewer credential:
![image](https://cloud.githubusercontent.com/assets/1937472/19552788/f196e12e-96e3-11e6-967d-3fb9c71cbe19.png)
Thanks,

**Comment by DonJayamanne** [comment]
I'll send a skype request shortly.

**Comment by DonJayamanne** [comment]
Problem was settings.json was configured incorrectly and caused extension not to load correctly.

**Comment by hanbaobao2005** [comment]
Issue resolved by update
"python.pythonPath": "\"D:/Program Files (x86)/python3.5/python.exe\""
to 
"python.pythonPath": "D:/Program Files (x86)/python3.5/python.exe"
