### ISSUE TITLE
Jupyter Support - Anaconda3 Support?

### ISSUE THREAD

**Issue by drcrook1** [DonJayamanne/pythonVSCode#398]
Prequisites state Anaconda is needed.  I have Anaconda3.  

~/anaconda3
I also have jupyter

I am getting error I need to follow instructions for pre-requisites.  Any chance we can get Anaconda3 supported, I'm assuming thats the missing link.

Lots of goodness in python 3.5 :D

**Comment by drcrook1** [comment]
This is being tracked in a different issue...

**Comment by DonJayamanne** [comment]
@drcrook1 , my plan was to close this when the new version is released. Much of the discussion is on the issue https://github.com/DonJayamanne/pythonVSCode/issues/366. 
A new version will be released today. 
The pre-requisites have changed, all you now need is Python + (Jupyter or IPython).
Wiki with prerequisites will be updated shortly, but you will need to wait for the new release.
