### ISSUE TITLE
Can not see object properties

### ISSUE THREAD

**Issue by pokekey** [DonJayamanne/pythonVSCode#4]
When debugging the 'locals' pane shows local objects but I can not expand them to see the properties (fields).  I can add a property to the 'watch' pane but this is fairly heavy weight.  

This is a common feature of debuggers.  Have I just not understood how to inspect an object?

(Thanks for the package.)

**Comment by DonJayamanne** [comment]
Unfortunately the underlying pdb debugger being used doesn't support this. I will update the readme to include these missing features. At the same time will also try to do something about, like serializing the object to a json, giving you visibility of all properties.

**Comment by pokekey** [comment]
OK.  Thanks for trying.  

The other thing that I did not see is console output.  

VS code is nice.  It is sort of an IDE but it is not really an IDE.  Don’t know quite what to think of it.

Tom

**Comment by DonJayamanne** [comment]
This has been fixed in the current release, but only works on Windows at this stage.

**Comment by DonJayamanne** [comment]
Good news this will work on the Mac as well. I will release a new version later today or tomorrow.
