### ISSUE TITLE
Jupyter/IPython REPL enhancement

### ISSUE THREAD

**Issue by gandhis1** [DonJayamanne/pythonVSCode#401]
Currently, the Jupyter implementation provides results in a separate pane, but with limited visual cues on the relation of code and outputs. 

For instance, Atom's Hydrogen - the user is running a specific code block at a time, and the results show up right below the code. If given code does not produce anything, nothing shows up, but the user is aware that it ran. Right now, if I run "Run Selection/Line" on code that does nothing, e.g. imports, there is no visual feedback to see that it ran.

![image](https://i.github-camo.com/72e6077d4293e44220f5a5c33a897d1394b49b2c/68747470733a2f2f636c6f75642e67697468756275736572636f6e74656e742e636f6d2f6173736574732f31333238353830382f31343539383737382f31636666316233322d303535342d313165362d383138312d3530343330376361366235362e676966)

Another alternative/example would be the PyQT IPython REPL, which has a different layout, but still the same core idea:

![image](https://cloud.githubusercontent.com/assets/21064086/19542546/0a808336-963d-11e6-94fa-75193a7961f9.png)

I think one of the big use cases for Jupyter is going to be interactive coding, which isn't nearly as seamless right now as it could be.

**Comment by DonJayamanne** [comment]
@gandhis1 , we're looking at implementing the first solution. I.e. displaying results inline.

**Comment by gandhis1** [comment]
That sounds great! Looking forward to it...I do a lot of "interactive" coding, from which things don't necessarily align themselves neatly into the concept of a cell. I'd be using a lot of "Run Selection", and modifying code on-the-fly.

**Comment by DonJayamanne** [comment]
@gandhis1 , got it thanks.
Just out of curiosity, when you say "interactive" coding, do you mean Hydrogen or a IPython REPL.

**Comment by gandhis1** [comment]
Currently I use something more along the lines of an IPython REPL (IPython terminal in VSCode or IPython QT in PTVS), but for my usage I don't really see that much of a difference vs. Hydrogen. Hydrogen is just in-lined and lacks IPython magic functions / features. But the core idea is interactively executing code...which both accomplish. 

I'm probably more keen on seeing Hydrogen happening than an IPython REPL, since as I mentioned, one can do the latter anyway through the terminal (it just isn't that well-integrated).

**Comment by DonJayamanne** [comment]
@gandhis1 
>it just isn't that well-integrated

What isn't integrated? Sorry , but I'm trying to understand what features are crucial here (when building the functionality into my extension).
Is it the fact that the images are non interactive, or there's a lack of intellisense? Thanks.

**Comment by gandhis1** [comment]
Well mainly just the fact that I have to highlight code, copy, then click on the terminal window to activate it, and paste it in. It can become tedious. In PTVS, I highlight code, press CTRL+E, and it channels into the IPython REPL. Also, the VS Code terminal window has limited capability for "text-editing", e.g highlighting text with your keyboard is not easy, for instance. 

The way I see it, there are 2 paths:

- Use an IPython REPL and integrate it a bit more closely with the text-editor. The issue I see with this is this seems somewhat redundant - when does one use the Jupyter notebook functionality vs. this? Bit of a grey area.
- Implement a hydrogen-esque solution, which extends the existing Jupyter notebook functionality. Downsides include not having IPython magic functions and auto-completion. Upsides include having 1 feature serving two purposes, (1) a REPL, and (2) a cell-based notebook. 

Maybe a good idea to get more opinions, I'm sure others have other, perhaps broader, experiences with this.

**Comment by Darktex** [comment]
+1 on providing some sort of feedback back to the user.

Also, I like Hydrogen's behavior better for Ctrl + Alt + Enter, which is Run Selection and Advance instead of Run Selection only. It helps with the visual feedback and allows you to quickly rerun a bunch of different commands simply by spamming Enter while keeping Ctrl and Alt pressed. Hydrogen has Run only on Ctrl Shift Enter by default.

More than that, Run and Advance is not working for me. It does run the line, but it doesn't advance.

One more feature that Hydrogen has that I like a lot is that it's cleverer with multiline code. If you have a N-lines expression, you can use Ctrl Alt Enter on the first line of the expression, and it will evaluate the whole thing, with the cursor going down N+1 lines instead of just 1 line. Currently, to do the same I'd have to select everything with my mouse, which is slower and breaks my flow.

**Comment by gandhis1** [comment]
And +1 on your comments. It makes a whole lot more sense for the command to advance ahead. If I can execute an entire Python script without ever leaving the editor, that would be fantastic.

Thinking about this, perhaps the keyboard shortcut should be able to be "smart", i.e.:

- If the cursor is located in a cell, execute the entire cell, and advance to the code after the cell.
- If the cursor is not located in a cell, execute the entire line, if no text is selected, and move to the next statement.
- If the cursor is not located in a cell, and text is selected, execute the selected text, and move to code immediately following the selection.

**Comment by auphofBSF** [comment]
Being able to select and Ctrl C copy  part of a result block would be great, Hydrogen only allows "**copy to clipboard**" and "**open in Editor**"
![image](https://cloud.githubusercontent.com/assets/11743864/19711347/a1928838-9b91-11e6-9551-c2823089594c.png)

**Comment by DonJayamanne** [comment]
@auphofBSF , not sure if this can be implemented. The current design of inline widgets in VS Code (in early development) doesn't support this. Will chase this up though.

**Comment by gandhis1** [comment]
Depends on how long you intend to maintain the current output window format, but it would be great if "Append Results" meant auto-scrolling to the most recent result as well.

**Comment by DonJayamanne** [comment]
Append result does scroll to the last result

**Comment by gandhis1** [comment]
I've had this behave inconsistently, will see if I can come up with a test case to show this.

**Comment by gandhis1** [comment]
Hey @DonJayamanne, do you actually get the window to scroll to the last result, including when you print a Pandas dataframe? My window does not scroll to the last result at all, in any context. 

For example, the screenshot below, with append turned on, you can see the scroll bar only has scrolled to where I manually scrolled to and no further. There are more dataframes below the one you see.

![untitled](https://cloud.githubusercontent.com/assets/21064086/19988882/429248e6-a1f9-11e6-8080-89ca68006ec4.png)

**Comment by DonJayamanne** [comment]
@gandhis1 Will look into this. Works at my end for Mac.
Haven't tried with dataframes though. Only tried with plain text, images and similar.

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/vscodeJupyter#25
