### ISSUE TITLE
Triple quotes auto-completion is not working properly

### ISSUE THREAD

**Issue by splendido** [DonJayamanne/pythonVSCode#405]
`"""|` becomes `"""|"

`'''|` becomes `'''|'`

(I used `|` to show the cursor position...)

Is there a solution using VSCode API to solve this problem?
See also https://github.com/Microsoft/vscode/issues/12976

**Comment by DonJayamanne** [comment]
Sorry but no solution. As this applies to F# and is being tracked in vs code repo, I will close this.
