### ISSUE TITLE
Jupyter - Autocomplete from jupyter kernel

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#409]
Make use of the kernel autocomplete capabilities instead of the static analysis provided by Jedi library.

As suggested [here](https://github.com/DonJayamanne/pythonVSCode/issues/366#issuecomment-254979304) by @gandhis1

**Comment by gandhis1** [comment]
Thanks - although instead of "instead" maybe "in addition to" or "in conjunction with"? If this functionality exists, surely wouldn't want to wait until code is sent to the kernel for execution to provide completions.

**Comment by DonJayamanne** [comment]
Agreed

**Comment by Darktex** [comment]
+1, would find it very useful

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/vscodeJupyter#22
