### ISSUE TITLE
Intellisense and sys.path.append()

### ISSUE THREAD

**Issue by DavidA2014** [DonJayamanne/pythonVSCode#41]
Don, I have a more complicated scenario for Intellisense. Can your plugin cope with this?

My project's folder structure is:

```
myProj---python---MsgQueue.py
       |
       |-gui---main.py
```
and gui\main.py contains

```
sys.path.append('../python')
import MsgQueue
```

Currently, when editing main.py, Intellisense isn't working for module MsgQueue. Is there anything I can do about that?

**Comment by DonJayamanne** [comment]
Sorry, but please can this wait for a few days. Getting into bed now for a nice long weekend.    
Add a temporary solution you might want to try out the other option of using additional paths. Check oocytes the wiki for sample Auto complete with Google app engine. User that solution to provide the path to the MsgQueue path out that folder. 

Sorry, but will check it out next week. Good night

**Comment by DavidA2014** [comment]
Don, this is low priority so don't worry about it. However, it would be interesting to find a solution. In Microsoft's PTVS it is possible to specify 'search paths', which may be relative. I was just wondering whether it is possible to support that in your extension?

**Comment by DavidA2014** [comment]
Sorry, I hadn't read the wiki properly. 'extraPaths' fixes my problem, even with relative paths.

```
    "python.autoComplete.extraPaths": [
    "../python" ]
```
