### ISSUE TITLE
The only linting suggestion is "Sort imports"

### ISSUE THREAD

**Issue by merlineus** [DonJayamanne/pythonVSCode#413]
VS Code 1.6.1
Python extension 0.5
pylint 1.6.4

Issue info:
![](http://image.prntscr.com/image/a7bf1d3b5a604046a14bf1fd3df9e8e2.jpeg)

After pressing hint:
![](http://image.prntscr.com/image/be774732216f404fb4522c390ef863a2.jpeg)

**Comment by DonJayamanne** [comment]
Unfortunately hints to resolve linter messages hasn't been implemented yet. 
https://github.com/DonJayamanne/pythonVSCode/issues/183
