### ISSUE TITLE
Cannot make Autocomplete to work

### ISSUE THREAD

**Issue by dionisi** [DonJayamanne/pythonVSCode#415]
Hi,

I've installed Python 0.5.0 for VS Code and configured the settings.json

``` json
{
    "python.pythonPath": "C:/Tools/python_3.5.2/python.exe"
}
```

Unfortunately, when I create a new .py file and try to use autocomplete (ctrl+space) nothing happens, only a pop up appears saying "Loading...". 

The python is not configured globally for my system. I don't have it anywhere in my environment except in this configuration file.

Should I configure anything else?

**Comment by DonJayamanne** [comment]
Please check if there are any errors logged in the python output panel or in the console window of ```Help->Toggle Developer Tools```

**Comment by dionisi** [comment]
Thanks for the prompt answer
In the developer console, after I click CTRL+Space, I can see the following error:
```
[Extension Host] ---------------------------
[Extension Host] sendCommand jediProxy
[Extension Host] Error (sendCommand) This socket has been ended by the other party
```

![image](https://cloud.githubusercontent.com/assets/4642757/19597472/82886b6c-979d-11e6-959e-9aa35abe305c.png)


I'm pretty shure it is some configuration error from my side, but I'm not sure what is it.
My machine is behind proxy, but the VS Code works without any additional proxy settings

**Comment by DonJayamanne** [comment]
@dionisi 
- Please could you uninstall the extension and re-install it (possible it didn't get installed correctly)  
- Also please could you confirm the path ```C:/Tools/python_3.5.2/python.exe``` points to a valid python interpreter (i.e. it launches Python)

**Comment by jasonyslai** [comment]
Hi,
  I am facing the same issue.
My Environment:
  OS:  Window 10 Home 64bit & Window 10 Pro 64bit
  IDE: Visual Studio Code 1.6.1
  Ext: Python 0.5.0

**Comment by jasonyslai** [comment]
Problem description:
Simply open a  .py file would happen this issue after installing vs code and the extension without any environment settings.

**Comment by DonJayamanne** [comment]
@jasonyslai , @dionisi 
- Please could you upload your settings.json  
- Please confirm the path provided for ```python.pythonPath``` is valid (open a terminal window an confirm this)

**Comment by jasonyslai** [comment]
Hi, @dionisi @DonJayamanne  ,
FYI , thanks!
![image](https://cloud.githubusercontent.com/assets/958382/19997577/7bf879e4-a2a2-11e6-92e4-a1660b6258b8.png)

**Comment by DonJayamanne** [comment]
@jasonyslai 
1. Please type the following in your terminal window:  
```D:\Code\Python-3.5.2-embed-win32\python.exe```
2. Please change the value of ```python.pythonPath``` to just ```python```

**Comment by jasonyslai** [comment]
Hi @DonJayamanne ,
  yes i am using the default value "python",
the path dosesn't save just show you my python path only=)

**Comment by jasonyslai** [comment]
Hi @DonJayamanne 
Debug is fines.

![image](https://cloud.githubusercontent.com/assets/958382/19997845/31253004-a2a4-11e6-9572-0f035801916a.png)

**Comment by jasonyslai** [comment]
Hi @DonJayamanne ,
When i press "Ctrl + space", intellisence works fine.
![image](https://cloud.githubusercontent.com/assets/958382/19998018/4117b918-a2a5-11e6-9b73-f6d32ffaff21.png)

When i remove the autocomplete box or just key some words without "Ctrl + space":
![image](https://cloud.githubusercontent.com/assets/958382/19998011/28e3544c-a2a5-11e6-950d-3ff4fddb66ad.png)

**Comment by DonJayamanne** [comment]
@jasonyslai 
Please could you try the latest version.

**Comment by DonJayamanne** [comment]
@dionisi , @jasonyslai 
please try the latest version and let me know how it goes

**Comment by dionisi** [comment]
@DonJayamanne Sorry for the late response, but I have just updated to 0.5.2 and now the automcomplete works fine.

Thank you for resolving the issue.

**Comment by jasonyslai** [comment]
@DonJayamanne Sorry for the late response too, i will test it at this weekend thx!

**Comment by jasonyslai** [comment]
@DonJayamanne It's solved! Thanks!!

**Comment by DonJayamanne** [comment]
Thanks
