### ISSUE TITLE
IPython(Jupyter) preview error

### ISSUE THREAD

**Issue by leaxoy** [DonJayamanne/pythonVSCode#416]
I have installed this extension.
And write a code cell.
Click `Run Cell` then error occured like below shows.
![](http://o8z0dg641.bkt.clouddn.com/py.png)

**Comment by DonJayamanne** [comment]
What is you're os and python version

**Comment by DonJayamanne** [comment]
@leaxoy 
Please could you try uninstalling jupyter and re-installing jupyter.
If that fails could you try installing anaconda.
This seems to be an issue with the jupyter client (see here https://github.com/jupyter/jupyter_client/issues/154)
