### ISSUE TITLE
Sorting imports ignores configuration

### ISSUE THREAD

**Issue by jsnjack** [DonJayamanne/pythonVSCode#417]
When document has unsaved changes "Sort imports" ignores configuration file `.isort.cfg`

**Comment by DonJayamanne** [comment]
Fixed, you will need to provide the path to the location of the configuration file.
Unforunately when file contents are not saved, a temporary file is created to sort the contents, and that won't pick up the configuration file.

The easiest is for you to provide the path to the config file as follows:
- Assuming your config is located in your project (root) directory 
- If not then use something as follows ```${workspaceRoot}/pathtoConfig```

```json
"python.sortImports.args" = ["-sp", "${workspaceRoot}"];
```
https://github.com/DonJayamanne/pythonVSCode/commit/d2f238bd36f9ab51efec12af35cab55d2956f2b7

Fix will be in the next release, hopefully later this week.

**Comment by jsnjack** [comment]
Thanks for fixing it so quickly! :+1:

**Comment by DonJayamanne** [comment]
No worries
