### ISSUE TITLE
DebugAdapter bin folder not found

### ISSUE THREAD

**Issue by cgars** [DonJayamanne/pythonVSCode#42]
Hey there Thanks for the nice extension!

When i tried to debug some code examples i stumbled over the following error. It appeared as soon as i hit debug.
`DebugAdapter bin folder not found on path ~/.vscode/extensions/donjayamanne.python-0.2.10/out/client/debugger/main.js.`

The issues is fixed once i rename 
`~/.vscode/extensions/donjayamanne.python-0.2.10/out/client/debugger/Main.js `
to 
`~/.vscode/extensions/donjayamanne.python-0.2.10/out/client/debugger/main.js  `

The issue appeared on a machine running Ubuntu 15.04 64bit 

It might be that this is caused by a very recent change to [package.json](https://github.com/DonJayamanne/pythonVSCode/blob/master/package.json#L63)

**Comment by dylan-bourque** [comment]
I saw the exact same issue on 2 different Linux systems, one is Linux Mint 17.2 and the other is CentOS 7.  The same change fixed the issue on those systems as well.

For completeness, I tried it on a Windows 10 system and it worked perfectly out of the box.

**Comment by DonJayamanne** [comment]
Please could you update to the latest version. It has been fixed.

**Comment by dylan-bourque** [comment]
I updated to the latest version (0.3.1) from version 0.2.10 and everything works.

Thanks Don
