### ISSUE TITLE
can not autocomplete when the type is 'file' in my compute

### ISSUE THREAD

**Issue by wzdnzd** [DonJayamanne/pythonVSCode#420]
I want to type "python2 = os.popen('python2 -V 2>&1').read().startswith('Python2.') and 'python2' or 'python'",however it can not auto-complete when i type "python2 = os.popen('python2 -V 2>&1').",can you enhance the feature of autocompletion?Thanks.
![default](https://cloud.githubusercontent.com/assets/8565764/19616556/b0f41c34-9848-11e6-9e46-2fa0e2da7017.png)
![default](https://cloud.githubusercontent.com/assets/8565764/19624429/86947480-9928-11e6-90bb-2e2f4524b9e1.png)

**Comment by DonJayamanne** [comment]
Unfortunately auto complete functionality is provided by [Jedi library](http://jedi.jedidjah.ch/en/latest/), hence if this doesn't work, then its area of improvement for the [Jedi library](http://jedi.jedidjah.ch/en/latest/)
