### ISSUE TITLE
Why removed the function of automatic formatting when saving?

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [DonJayamanne/pythonVSCode#421]
`editor.formatOnSave`  setting item is global effective, If I open this option, all of the files will be formatted while it was saved.

However, this does not apply to some files that I don't want to format (such as the .json file, the effect is bad).

Therefore, I still need a local, only .py file effective options (`python.formatOnSave` ).

**Comment by DonJayamanne** [comment]
Oh, sorry in that case I will revert the change with another setying, to check if global save isn't turned on.

**Comment by zhengxiaoyao0716** [comment]
Thanks for your prompt reply, I love this plugin, and I look forward to the next update. By the way, there are a typo 'pylit' in the ReadMe.md.

**Comment by DonJayamanne** [comment]
Yes, that has been fixed and will be in the next release. Cheers

**Comment by DonJayamanne** [comment]
@zhengxiaoyao0716 , fixed. Will be in next release (next week)
