### ISSUE TITLE
Autocomplete Improvement: Adding brackets for function calls

### ISSUE THREAD

**Issue by hd5970** [DonJayamanne/pythonVSCode#425]
Hi,

when auto-completing function calls like open, it completes the function name. I think most of the time it would be useful to also append the () and put the cursor inside the brackets. When it's not required one could simply press backspace to remove these two brackets.

Thanks

**Comment by DonJayamanne** [comment]
I don't see a similar behaviour with other languages such as C#, JavaScript and TypeScript in VS Code.

**Comment by DonJayamanne** [comment]
@hd5970 , @gandhis1 , @svkurowski, @hd5970  @sunilkr
Done, however this feature is turned off by default.
If you would like it enabled, then turn on the following setting in your ```settings.json``` (preferably in your user settings - this way you define it once for all workspaces):  
```json
"python.autoComplete.addBrackets": true
```

**Comment by hd5970** [comment]
Great!
Thank you
