### ISSUE TITLE
Jupyter: support %matplotlib notebook (and enable by default)

### ISSUE THREAD

**Issue by gandhis1** [DonJayamanne/pythonVSCode#426]
Currently, Jupyter startup code is %matplotlib inline, which produces static graphs. 

Is it possible to support %matplotlib notebook, which produces interactive graphs (a la screenshot below)? If so, I think it ought to be the default option as well. 

![image](https://cloud.githubusercontent.com/assets/21064086/19628986/c3a4fede-9938-11e6-9ef2-010a5bd26b41.png)

**Comment by DonJayamanne** [comment]
@gandhis1 , unfortunately ```%matplotlib notebook``` from within the Jupyter notebook. PyCharm have some form of support for notebooks, however this command ```%matplotlib notebook``` isn't supported in there either.  As mentioned this only works within the jupyter notebook web (browser) application.

**Comment by DonJayamanne** [comment]
@gandhis1 
You could try getting interactive graphs using something like D3js or bokeh (have a look [here](https://github.com/DonJayamanne/pythonVSCode/wiki/Jupyter-Examples#Interactive-Plot-using-D3js))

**Comment by gandhis1** [comment]
Ok, wasn't aware that was the case. Mpld3 works pretty well, I guess I can always go with that.
