### ISSUE TITLE
handle python print error 

### ISSUE THREAD

**Issue by weinand** [DonJayamanne/pythonVSCode#427]
_From @TBWISK on October 24, 2016 9:0_

- VSCode Version:1.6.1 (1.6.1) 9e4e44c19e393803e2b05fe2323cf4ed7e36880e
- OS Version:10.12 (16A323)

Steps to Reproduce:

1. when i use python to handler string ,and this string with xA char ,when print this string in vscode,it  like a '\n' char in my mac, like 
2. print "helloxAthisxAisxAabug"     
and it would be show in the screen
such as :   
hello   
this  
is  
abug   

_Copied from original issue: Microsoft/vscode#14263_

**Comment by DonJayamanne** [comment]
@TBWISK, I am unable to replicate this.
I have tested this on both Python 2.7 and 3.5.
I have tested this in the integrated terminal as well as the debugger.

Please could you provide the following information:
- OS
- Python version
- How did you replicate this issue (debugger, terminal)?

**Comment by TBWISK** [comment]
@DonJayamanne my python version is python 2.7.10

**Comment by TBWISK** [comment]
Sorry,my desc wasn't obvios   
@DonJayamanne my python version is Python 2.7.10    
and this worry show that look like this:   
[this error img show](http://7sby3x.com1.z0.glb.clouddn.com/52268952-4322-4F2B-81B0-5FAD498B0549.png)   
I hope it can help you to replicate this error

**Comment by DonJayamanne** [comment]
@TBWISK 
how are you running the python code? 
I.e. what command, menu option or shortcut key are you using?

**Comment by DonJayamanne** [comment]
@TBWISK
I don't think this is related to this python extension. Please provide the above requested info.

**Comment by TBWISK** [comment]
@DonJayamanne 
Sorry  
I run this command use Command+shift+b   
and my vscode use python extension about Python and MagicPython   
and i think this is not a python extension woring too.   
but i don't know how to use other language to test it .   
if you can use js or other language to test it ,do it.   
and it konw 'xA' in xml is \n   
thanks

**Comment by DonJayamanne** [comment]
@TBWISK Please  could you send me your tasks.json file

**Comment by DonJayamanne** [comment]
please uninstall python extension and try again

**Comment by TBWISK** [comment]
@DonJayamanne 
Sorry   
I am too later too deal with it.   
and I uninstall all my python extension  ,and use command +shift+b to run it .   
but this bug is till here   
and my tasks.json is that   
```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "/Users/youyou/Envs/wechat-article-monitor/bin/python",
    "isShellCommand": true,
    "args": ["${file}"],
    "showOutput": "always"
}
```
