### ISSUE TITLE
'NoneType' object has no attribute 'names_dict'

### ISSUE THREAD

**Issue by skelbley** [DonJayamanne/pythonVSCode#43]
Plugin version is 0.3.1, error shows up every time I stop typing. Only error message shown is "Error Traceback (most recent call last):". Is there logging somewhere I could check to hopefully find more info? Thanks for all your hard work by the way!

OS is Fedora 23, Python version 2.7.10.

**Visual Studio Code version info:**
Version 0.10.10
Commit 5b5f4db87c10345b9d5c8d0bed745bcad4533135
Date 2016-03-08T12:53:20.616Z
Shell 0.36.10
Renderer 47.0.2526.110
Node 5.1.1

**Comment by skelbley** [comment]
Finally remembered that this basically runs in a browser, got this from the console:

Error (stderr) Traceback (most recent call last):
  File "completion.py", line 309, in watch
    self._process_request(self._input.readline())
  File "completion.py", line 300, in _process_request
    request.get('prefix', '')))
  File "completion.py", line 136, in _serialize_completions
    completions = script.completions()
  File "/home/skelbley/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/api/__init__.py", line 192, in completions
    completion_names = get_completions(user_stmt, b)
  File "/home/skelbley/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/api/__init__.py", line 178, in get_completions
    completion_names += self._simple_complete(path, dot, like)
  File "/home/skelbley/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/api/__init__.py", line 246, in _simple_complete
    for names_dict, pos in names_dicts:
  File "/home/skelbley/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/finder.py", line 500, in global_names_dict_generator
    for names_dict in scope.names_dicts(True):
  File "/home/skelbley/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/representation.py", line 720, in names_dicts
    yield star_module.names_dict
AttributeError: 'NoneType' object has no attribute 'names_dict'

**Comment by DonJayamanne** [comment]
Hi,
1. Is this some thing you encounter always, even in a very simple Python file with 1-2 lines of code in it?
2. Please could you try upgrading your vscode version to the latest version and let me know how it goes?

**Comment by skelbley** [comment]
Thanks for the response, here are my answers:

1. Just tried creating a new file, imported os, and after typing 'os.' saw these four errors in the console:

```
[Plugin Host] ---------------------------
(anonymous function) @ threadService.ts:199
emitTwo @ events.js:87
emit @ events.js:172
handleMessage @ internal/child_process.js:685
channel.onread @ internal/child_process.js:440

[Plugin Host] stdout jediProxy
(anonymous function) @ threadService.ts:199
emitTwo @ events.js:87
emit @ events.js:172
handleMessage @ internal/child_process.js:685
channel.onread @ internal/child_process.js:440

[Plugin Host] Error (stdout) Unexpected token r
(anonymous function) @ threadService.ts:199
emitTwo @ events.js:87
emit @ events.js:172
handleMessage @ internal/child_process.js:685
channel.onread @ internal/child_process.js:440

There was an error in the python extension. Error Unexpected token r
e.doShow @ messageService.ts:147
e.show @ messageService.ts:131
(anonymous function) @ extHostMessageService.ts:80
n.undefined.t.Class.derive._oncancel @ winjs.base.raw.js:1901
e.showMessage @ extHostMessageService.ts:72
e.handle @ abstractThreadService.ts:100
c @ ipcRemoteCom.ts:172
f @ ipcRemoteCom.ts:120
doNTCallback0 @ node.js:420
_tickCallback @ node.js:349
```
2. Same errors reproduced on the latest stable build as well.

**Comment by feuerwelt** [comment]
Unfortunately I have the same `completion.py` issue :/
Have any of you guys found out what may be causing it?

**Comment by DonJayamanne** [comment]
Hi, i have updated the extension with the latest version of the jedi library.
If you still experience these issues with regards to the completion.py file, then please (unfortunately) raise issues in the following git repo:
https://github.com/davidhalter/jedi
