### ISSUE TITLE
Chinese characters are not correctly encoded while debugging Python in VS Code

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#431]
@shixuexeon

- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: donjayamanne.python-0.4.2, dvdbrink.vscode-sql-connect-0.2.1

Steps to Reproduce:
代码为：
print('我的代码')
输出显示为：
�ҵĴ���

**Comment by DonJayamanne** [comment]
Steps to Reproduce:

The code is print('我的代码')
The out put is �ҵĴ���

@shixuexeon , can you try to run this piece of code in your terminal and provide the output?

**Comment by DonJayamanne** [comment]
@shixuexeon
- What version of Python are you using?
- Also, please try updating to the latest version of the Python extension (currently 0.5.0)

**Comment by shixuexeon** [comment]
I have to solve this problem.Add in the file task.json the following configuration:





    "env":{
        "PYTHONIOENCODING": "UTF-8"
      }








------------------ 原始邮件 ------------------




 
 发件人: Don Jayamanne  <notifications@github.com>
 

 
 发送时间: 2016-10-26 15:30:08
 

 
 收件人:DonJayamanne/pythonVSCode <pythonvscode@noreply.github.com> 

 
 抄送:田永海 <tianyonghai@139.com>,Mention <mention@noreply.github.com> 

 
 主题: Re: [DonJayamanne/pythonVSCode] Chinese characters are not correctlyencoded while debugging Python in VS Code (#431)
 



Steps to Reproduce:

 The code is print('我的代码')
 The out put is �ҵĴ���

 @shixuexeon , can you try to run this piece of code in your terminal and provide the output?

**Comment by DonJayamanne** [comment]
Oh, that has nothing to do with this Python extension. You're using tasks.json to run a file.
However you mentioned that you are **debugging**.
