### ISSUE TITLE
Auto indent else inside if block

### ISSUE THREAD

**Issue by MFairley** [DonJayamanne/pythonVSCode#432]
``` python
if test:
    a = 1
    # Else not autoindented
    else:
```

Is it possible to make the `else:` auto indent back to the level of `if`? Sublime Text does this automatically.

**Comment by gandhis1** [comment]
Is this working properly? In the example below I follow these steps:

1) Type the if statement
2) Type a= 3. 
3) Press enter.
4) Type b = 5.
5) Press Enter. 
6) Type "else:". 
7) Press Enter
8) I expected "else:" to be auto-formatted to the correct indentation, and for my cursor to be at the correct indentation level. This did not happen.

![image](https://cloud.githubusercontent.com/assets/21064086/20567847/4e2093e2-b168-11e6-889d-3bc14d635efe.png)

**Comment by DonJayamanne** [comment]
@gandhis1 
You need to turn on the following setting (preferably in your user settings):
```json
"editor.formatOnType": true,
```

**Comment by DonJayamanne** [comment]
This will work, provied the ```if``` is NOT the first line of code.
Will fix that.

**Comment by gandhis1** [comment]
This sounds like something that should be default behavior (and a setting to turn it off). I mean, I feel as though any setting should default to the behavior someone who is not a "power user" expects, and the setting should be for someone who is a "power user". Or, equivalently, the default behavior should be the more "useful" behavior of the two alternatives. Just my 2 cents...

**Comment by DonJayamanne** [comment]
Unfortunately the way VS Code is structured, this setting applies across all extensions and all languages. So even if this was turned on by default, it could activate other behaviours from other extensions that are off by default.
I agree with you on this. let me chase this up with the VS Code team.

**Comment by DonJayamanne** [comment]
Raised an issue on VS Code Github:
https://github.com/Microsoft/vscode/issues/15989
