### ISSUE TITLE
Exception when trying to find references to an import math statement

### ISSUE THREAD

**Issue by Tyriar** [DonJayamanne/pythonVSCode#434]
![image](https://cloud.githubusercontent.com/assets/2193314/19739029/59f3e6a2-9b6e-11e6-9677-352e0345d8c9.png)

It's loading indefinitely:

![image](https://cloud.githubusercontent.com/assets/2193314/19739047/6778df8a-9b6e-11e6-81a5-fd169b2d4910.png)

Here is the file I was on at the time: https://github.com/gwtw/py-sorting/blob/master/sort/bucket_sort.py#L6

**Comment by ramya-rao-a** [comment]
Same thing when I tried "Find All references" on the `fabs` mthod below
`abc = math.fabs(-10)`

Custom modules work fine
