### ISSUE TITLE
Hovering a variable should give a peek of its source/definition, not for the function to which it was provided

### ISSUE THREAD

**Issue by Tyriar** [DonJayamanne/pythonVSCode#437]
![image](https://cloud.githubusercontent.com/assets/2193314/19739346/6db2ba6e-9b6f-11e6-9a1c-417c04130b88.png)

Related: https://github.com/DonJayamanne/pythonVSCode/issues/435

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/DonJayamanne/pythonVSCode/issues/457
