### ISSUE TITLE
Refactoring and navigation does not work at all in Untitled files with a language set

### ISSUE THREAD

**Issue by Tyriar** [DonJayamanne/pythonVSCode#439]
At the very least refactoring and navigation working on the local file only should be functional.

Steps to reproduce:
1. Create a new file
2. Set language to python
3. Paste in:
   
   ``` python
   foo = []
   bar = 1
   foo.append(bar)
   ```
4. Mouse over `append`, no hover detail
5. Put cursor before `.append`
6. Press F2, no rename dialog
7. Press F12, no go to definition

**Comment by DonJayamanne** [comment]
@Tyriar 
Same issue with JavaScript and TypeScript.
I guess that's why the context menus for ```Go to definition```, ```Rename Symbol```, etc don't appear.
