### ISSUE TITLE
"Rename symbol" not working - "No result"

### ISSUE THREAD

**Issue by roblourens** [DonJayamanne/pythonVSCode#440]
In a simple file - am I doing something wrong? Tried with 2.x and 3.x interpreters.

(Pressing F2)
![oct-26-2016 11-36-31](https://cloud.githubusercontent.com/assets/323878/19739611/7aa93f44-9b70-11e6-9ef0-9eb3e8a35291.gif)

**Comment by gandhis1** [comment]
I get this quite a bit. The rename feature is certainly hard to rely on. Sometimes, I use it, and it starts running the refactor, but never finishes (with the ribbon animation).
