### ISSUE TITLE
Extract method appears to use the file on disk, not the unsaved file in the editor

### ISSUE THREAD

**Issue by Tyriar** [DonJayamanne/pythonVSCode#441]
This makes extract method feel inconsistent and buggy if you don't work with auto save on.

**Comment by DonJayamanne** [comment]
@Tyriar 
Extracting methods without saving the changes (to a file) isn't possible.
- Should I just save the changes to the file?  
- Prompt the user to save?  
- Or just display a message indicating renaming without saving isn't supported?  

FYI - Will investigate the possibility of creating a temporary file or file in memory. If this doesn't work, then I'll need to proceed with one of the above.
You feedback is most appreciated on the UX

**Comment by Tyriar** [comment]
@DonJayamanne yeah I was thinking if the lib required it to save to a temp directory via `os.tmpdir()` and using that.

**Comment by DonJayamanne** [comment]
Renaming symbols across files  won't work, add the other folks will be located else where. The library won't be able to handle it's the only option is to go with the prompts (or presave option).
