### ISSUE TITLE
Extract method has mixed indentation that only partially matches the editor's setting

### ISSUE THREAD

**Issue by Tyriar** [DonJayamanne/pythonVSCode#442]
See the following image has the extracted method has 4 space indents after the `def` and 2 space inside the function.

![image](https://cloud.githubusercontent.com/assets/2193314/19740383/63885856-9b73-11e6-91a0-654d777cab52.png)

![image](https://cloud.githubusercontent.com/assets/2193314/19740415/782a7d2a-9b73-11e6-8b47-2fcb714a4883.png)

**Comment by DonJayamanne** [comment]
Fixed https://github.com/DonJayamanne/pythonVSCode/commit/af7560d0056428d1036054cdfb17c5b8a044a883
