### ISSUE TITLE
Renaming a symbol should read from the currently unsaved buffer

### ISSUE THREAD

**Issue by Tyriar** [DonJayamanne/pythonVSCode#443]
Steps to reproduce:
1. Open a python file
2. Edit it (don't save)
3. F2, change name and enter

![image](https://cloud.githubusercontent.com/assets/2193314/19742109/6ebcd4b8-9b78-11e6-8dbd-921cb9c0a545.png)

**Comment by DonJayamanne** [comment]
@Tyriar 
Renaming without saving the changes isn't possible.
- Should I just save the changes to the file?  
- Prompt the user to save?  
- Or just display a message indicating renaming without saving isn't supported?

**Comment by Tyriar** [comment]
See https://github.com/DonJayamanne/pythonVSCode/issues/441#issuecomment-256937107

**Comment by Tyriar** [comment]
RE: https://github.com/DonJayamanne/pythonVSCode/issues/441#issuecomment-257031586

> Renaming symbols across files won't work, add the other folks will be located else where. The library won't be able to handle it's the only option is to go with the prompts (or presave option).

@DonJayamanne this really limits the usability of the feature imo, so does that mean that it also saves it to disk and you cannot undo the change? I just tried to use it but go to def and rename don't seem to be working anymore.

**Comment by DonJayamanne** [comment]
Yes changed will be saved to the disc, however my preferred is to prompt the user before doing this.

When you say go to def and rename don't work anymore, is that in the released extension or the master branch source?

**Comment by Tyriar** [comment]
Just downloaded it 30 minutes ago and tried, F2/F12 don't work.

**Comment by DonJayamanne** [comment]
@Tyriar 
Seems to be all fine at this end. 
Any errors logged in the ```Python``` output panel or the error table in the ```Console``` window of ```Developer Tools```.

**Comment by Tyriar** [comment]
```
workbench.main.js:121 [Extension Host] Activating extension `donjayamanne.python` failed: Cannot read property 'indexOf' of undefined.I.logExtensionHostMessage @ workbench.main.js:121
workbench.main.js:121 [Extension Host] Activating extension `donjayamanne.python` failed:  Cannot read property 'indexOf' of undefinedI.logExtensionHostMessage @ workbench.main.js:121
workbench.main.js:121 [Extension Host] Here is the error stack:  TypeError: Cannot read property 'indexOf' of undefined
    at getAbsolutePath (/home/daniel/.vscode-insiders/extensions/donjayamanne.python-0.5.0/out/client/common/configSettings.js:141:20)
    at PythonSettings.initializeSettings (/home/daniel/.vscode-insiders/extensions/donjayamanne.python-0.5.0/out/client/common/configSettings.js:26:27)
    at PythonSettings (/home/daniel/.vscode-insiders/extensions/donjayamanne.python-0.5.0/out/client/common/configSettings.js:17:14)
    at Object.<anonymous> (/home/daniel/.vscode-insiders/extensions/donjayamanne.python-0.5.0/out/client/common/configSettings.js:135:33)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.M.d._load (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:28523)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/daniel/.vscode-insiders/extensions/donjayamanne.python-0.5.0/out/client/providers/jediProxy.js:5:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
workbench.main.js:101 Activating extension `donjayamanne.python` failed: Cannot read property 'indexOf' of undefined.
```

**Comment by Tyriar** [comment]
This may be the issue @roblourens was seeing

**Comment by DonJayamanne** [comment]
You are using the insiders version.
Is the fix for [this](https://github.com/Microsoft/vscode/issues/14500#issuecomment-256885213) in the insiders build?

The above issue in VS Code is what's causing this issue.

**Comment by DonJayamanne** [comment]
Let me check this... sorry, saturday morning

**Comment by roblourens** [comment]
Or @octref, different issues but same error.

**Comment by Tyriar** [comment]
It should be:

Version 1.7.0-insider
Commit 0706b425537d8cfe2766eac00662ecf988c7ed7f
Date 2016-10-28T13:01:34.267Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0

Ah sorry about that :stuck_out_tongue:

**Comment by DonJayamanne** [comment]
Just installed the latest version of Insiders and works for me.

**Comment by octref** [comment]
@Tyriar this is the issue: https://github.com/Microsoft/vscode/issues/14632.

I saw exact same error yesterday for Python, although I reported using Dart pictures.

Latest version 0706b4 doesn't seem to fix that. Let me see...

**Comment by octref** [comment]
@DonJayamanne If you have a tab with py file open and Cmd+Shift+P -> Reload Window, does it error out?

**Comment by DonJayamanne** [comment]
@octref all good at this end:
- Version 1.7.0-insider (1.7.0-insider)
- 2016-10-28T12:58:19.996Z
- OS X (El Capitan 10.11.6)

**Comment by octref** [comment]
@DonJayamanne Thanks, I added these lines here:

![image](https://cloud.githubusercontent.com/assets/4033249/19824605/da6e95da-9d25-11e6-9be5-2d5f252ca1a0.png)

And `pythonSettings` is null. Let me take a look.

**Comment by DonJayamanne** [comment]
@octref, thanks

**Comment by octref** [comment]
`vscode.workspace.getConfiguration('python')` returns empty object. Seems contributed configuration is not read at startup. Reopened https://github.com/Microsoft/vscode/issues/14500.
