### ISSUE TITLE
The extension blew up when I tried to sort imports

### ISSUE THREAD

**Issue by Tyriar** [DonJayamanne/pythonVSCode#444]
![image](https://cloud.githubusercontent.com/assets/2193314/19742259/06693914-9b79-11e6-83ac-2d39f4b100de.png)

Looks like it's due to a lack of pylint, ideally this would be handled more gracefully. The message also doesn't inform the user how pylint can be installed. Something like how vscode-go goes about this would be better, on launch inform the user to install pylint (ideally with a don't ask me again option).

**Comment by DonJayamanne** [comment]
>doesn't inform the user how pylint can be installed

This has been fixed, the new version will prompt the user to install it.
