### ISSUE TITLE
Interpreter selector doesn't offer Python 3.5 on Windows

### ISSUE THREAD

**Issue by chrmarti** [DonJayamanne/pythonVSCode#446]
Version 0.5.0, Windows 10

I installed Python 3.5.2 with default settings (in user app folder, no PATH entry) and it is not listed. Python 2.7 with default settings (c:\python27, no PATH entry) is listed.

**Comment by DonJayamanne** [comment]
Could you provide the fully qualitified path to the interpreter in your app folder.

**Comment by chrmarti** [comment]
That's `C:\Users\chrmarti\AppData\Local\Programs\Python\Python35-32\python.exe`.
