### ISSUE TITLE
Function intellisense and hover detail should indicate more structured information on the function prototype 

### ISSUE THREAD

**Issue by Tyriar** [DonJayamanne/pythonVSCode#447]
Python:

![image](https://cloud.githubusercontent.com/assets/2193314/19742671/fd9735dc-9b7a-11e6-945c-ae1cf323d43d.png)

![image](https://cloud.githubusercontent.com/assets/2193314/19742738/418c2f9a-9b7b-11e6-9b7e-be3643afe25f.png)

JavaScript:

![image](https://cloud.githubusercontent.com/assets/2193314/19742698/19b8a4da-9b7b-11e6-9b6a-ed065e625616.png)

![image](https://cloud.githubusercontent.com/assets/2193314/19742717/3180c8b8-9b7b-11e6-84af-caac866b1496.png)

**Comment by DonJayamanne** [comment]
Unfortunately the information displayed is limited to the information returned by the library used to provide intelliense information ((Jedi)[http://jedi.jedidjah.ch/en/latest/docs/plugin-api-classes.html#jedi.api.classes.Completion]))

**Comment by Tyriar** [comment]
@DonJayamanne can't the result descriptions be parsed based on the symbol type? For example it knows that `foo` is a function, so it can look for `foo\(.*\)` in the description, pull it out and insert it into a string of the form `def foo\(.*\)` on the right side?

**Comment by DonJayamanne** [comment]
Agreed
