### ISSUE TITLE
Intellisense not working for certain modules

### ISSUE THREAD

**Issue by ramya-rao-a** [DonJayamanne/pythonVSCode#449]
Repro steps:

1. import random and math modules
2. type `math.`, you will see autocomplete kick in giving options for all functions in math module
3. type `random.`, you dont get any functions from the random module

I tried both Python 2.7 and 3.0 interpretors

**Comment by DonJayamanne** [comment]
@ramya-rao-a 
```random``` works for me. Perhaps it is a little slow in building up the intellisense cache.
Please give it a few seconds and let me know how it goes.

**Comment by ramya-rao-a** [comment]
Gave it a few hours. All other standard modules seem to work fine except random...

**Comment by DonJayamanne** [comment]
@ramya-rao-a , ok a few hours is not necessary.
Please could you open the Developer tools and let me know what errors are logged in the console window.

**Comment by ramya-rao-a** [comment]
No console errors.
This could be totally random too (pun totally intended)

**Comment by ramya-rao-a** [comment]
```python
import random
print(random.randint(0, 5))
```

When debug this, I dont get any errors. It prints a random number between 0 and 5
But linter says "Module 'random' has no 'randint' member

While typing `import ra` I do get prompted to complete it with "random"

**Comment by DonJayamanne** [comment]
@ramya-rao-a 
thats odd. I thought ```randint``` was a standard memeber.
Hmm, what version of Python are you using?

**Comment by ramya-rao-a** [comment]
I tried using both Python 2.7 and 3.0 interpreter in ubuntu

**Comment by DonJayamanne** [comment]
@ramya-rao-a 
This doesn't seem to be an issue with the extension, but more with your environment. 
randint to my knowledge is a standard member.

Can you check the following links:
- http://stackoverflow.com/questions/4178648/random-randint-error
- http://stackoverflow.com/questions/35689795/python-object-has-no-attribute-randint

**Comment by DonJayamanne** [comment]
This (incorrect file name or similar) would explain why you aren't getting any intellisense either

**Comment by ramya-rao-a** [comment]
Doh! My file was named "random" , sorry my bad
