### ISSUE TITLE
Function info  does not match the Python interpreter version

### ISSUE THREAD

**Issue by ramya-rao-a** [DonJayamanne/pythonVSCode#450]
I have selected Python 2.7 interpreter
The below code results in an error while debugging, because the "end" is not supported in Python 2.7

`print(n1,",",n2,end=',')`

But the intellisense, param hints, hover info shows support for the "end" parameter as is supported in Python 3

**Comment by DonJayamanne** [comment]
@ramya-rao-a 
Not following you here.
>shows support for the "end" parameter as is supported in Python 3

But you're trying to debug in Python 2.7.
That makes sense, doesn't it. You're trying to use a feature in version that is not supported!

**Comment by ramya-rao-a** [comment]
Yes, the fact that the error was thrown is correct.

But the intellisense (hover info, autocomplete), suggest that "end" parameter is supported which is misleading

**Comment by DonJayamanne** [comment]
>But the intellisense (hover info, autocomplete), suggest that "end" parameter is supported which is misleading

Please could you confirm you have selected the Python 2.7 interpreter?
Please could you upload the contents of your ```settings.json```.

**Comment by ramya-rao-a** [comment]
My settings are empty.

Here are better repro steps

- Select Python 2.7 interpreter
- Hover on print, you get just "print" because print is not a method in 2.7
- Select Python 3.0 interpreter
- Hover on print, you get the whole method definition 
- Select Python 2.7 interpreter again
- Hover on print, you still get the whole method definition from Python 3.0
- Reload VS Code
- Hover on print, you get just "print" because print is not a method in 2.7

**Comment by DonJayamanne** [comment]
@ramya-rao-a 
I think the problem is that you've been changing the interpreter too often. 
This is an very unlikely scenario, as generally people will stick to one interpreter in a workspace.
Here you're changing it 3 times in quick succession.

**Comment by ramya-rao-a** [comment]
agreed, will close
