### ISSUE TITLE
Issue when not setting a different workspace interpreter

### ISSUE THREAD

**Issue by roblourens** [DonJayamanne/pythonVSCode#451]
I filed this issue on vscode because it may be an issue on them - https://github.com/Microsoft/vscode/issues/14559

But I'm not sure. Would be great if other people are able to repro as well. This is on insiders-1.7, not 1.6.

Pasted here -

> - Install the python extension
> - Create a folder with one python file
> - Open in vscode and see that you have python intellisense. 
> - Close/reopen vscode on the same folder
> - Now the extension fails to load with this error - 
> 
> ![image](https://cloud.githubusercontent.com/assets/323878/19744550/d2e1b120-9b82-11e6-8b48-6e76fe930645.png)
> 
> This works in stable. Debugging, it looks like an issue with these lines -
> 
> ```typescript
> let pythonSettings = vscode.workspace.getConfiguration('python');
> this.pythonPath = systemVariables.resolveAny(pythonSettings.get<string>('pythonPath'));
> ```
> 
> The first time the folder is opened, (and every time in stable), `pythonSettings.get('pythonPath')` returns 'python', which is the default value of that setting. If I add a settings.json file in the workspace with 'python' or some other interpreter, it works. Otherwise, it seems like vscode is doing the wrong thing.

**Comment by roblourens** [comment]
And it would be good to have error handling for when python is not on the path, or pythonPath is invalid. In this case, it just silently doesn't work.

**Comment by DonJayamanne** [comment]
@roblourens 
Are you using the ```Insiders``` build of Visual Studio Code?

**Comment by roblourens** [comment]
Yes, it only fails in the insiders build

**Comment by DonJayamanne** [comment]
Its related to an issue in VS Code itself (https://github.com/Microsoft/vscode/issues/14500#event-837643135).
You'll need to wait for the next build of Insiders.

**Comment by roblourens** [comment]
Oh cool, thanks
