### ISSUE TITLE
When all tests error out the status bar says "No Tests Ran"

### ISSUE THREAD

**Issue by Tyriar** [DonJayamanne/pythonVSCode#452]
![image](https://cloud.githubusercontent.com/assets/2193314/19744995/b80d161c-9b84-11e6-8224-196e0a015a13.png)

**Comment by DonJayamanne** [comment]
fixed https://github.com/DonJayamanne/pythonVSCode/commit/fcd6611aa9d5d5a60da9ff92d23fcd61e017d536
