### ISSUE TITLE
Code actions on unsupported feature not helpful

### ISSUE THREAD

**Issue by ramya-rao-a** [DonJayamanne/pythonVSCode#454]
Below is valid in Python 3.0 and not in Python 2.7

`print(n1,",",n2,end=',')`

- Select workspace interpreter to Python 2.7 and add the above code and save
- You will see the red squiggly line below it, Hover on it you will see "[pylint] E0001: invalid syntax"
- There is a bulb for code action which gives the below options, none of which are applicable to the current case
     - Sort Imports
     - Extract Variable
     - Extract Method

**Comment by DonJayamanne** [comment]
@ramya-rao-a 
Agreed, will remove the code actions complete, as the commands and context menus are available.
