### ISSUE TITLE
Linter gives error for feature supported in Python 3.0

### ISSUE THREAD

**Issue by ramya-rao-a** [DonJayamanne/pythonVSCode#455]
Below is valid in Python 3.0 and not in Python 2.7

`print(n1,",",n2,end=',')`

- Select workspace interpreter to Python 2.7 and add the above code and save
- You will see the red squiggly line below it, Hover on it you will see "[pylint] E0001: invalid syntax"
- Select workspace interpreter to Python 3.0
- Debugging is successful without issues, but the red squiggly line does not go away

**Comment by DonJayamanne** [comment]
@ramya-rao-a , please ensure ```pylint``` is installed in the ```Python 3.0``` interpreter.
Looks like it isn't.
