### ISSUE TITLE
Hover shows details of surrounding expression

### ISSUE THREAD

**Issue by chrmarti** [DonJayamanne/pythonVSCode#457]
Version 0.5.0, Windows 10

![python-hover-over-subexpression](https://cloud.githubusercontent.com/assets/9205389/19745515/cdd54abc-9b86-11e6-8854-e2e8b29d4a39.PNG)

Maybe the same as #437. The hover shows information about the surrounding print() instead of the capitalize() the mouse hovers over.

**Comment by DonJayamanne** [comment]
@chrmarti 
Yes can replicate it. seems to be an issue when you have text selected.
