### ISSUE TITLE
The diary of a very patient person attempting to configure unit tests for their existing project

### ISSUE THREAD

**Issue by Tyriar** [DonJayamanne/pythonVSCode#459]
Here is the process I followed on https://github.com/gwtw/py-sorting
1. Run command via command palette, it told me I need to enable it (#448)
2. Looked in settings.json and set `"python.unitTest.unittestEnabled": true`
3. Run command via command palette, it said there were no tests run in the status bar (this would be very difficult to see if you weren't looking for it)
4. Looked at other `python.unitTest.unittest*` settings
5. Found `python.unitTest.unittestArgs`, my test script is python3 -m unittest discover test '*_test.py' so I tried setting:
   
   ``` json
   "python.unitTest.unittestArgs": [
     "discover",
     "test",
     "*_test.py"
   ]
   ```
6. Run command via command palette, no tests run
7. Start getting grumpy :angry: 
8. Tried setting workspace interpreter to python3
9. Run command via command palette, no tests run
10. Toggle test output and see this repeated a bunch of times:
    
    ```
    ----------------------------------------------------------------------
    Ran 0 tests in 0.000s
    
    OK
    ```
11. Verify that my tests do indeed run by running my regular script:
    
    ```
    ~/dev/gwtw/py-sorting @master ?
    ❯ ./run_tests
    ..........................................................................................................................................................................................
    ..........................................................................................................................................................................................
    .....................................................................................................................
    ----------------------------------------------------------------------
    Ran 489 tests in 0.044s
    
    OK
    ```
12. Try the following configs to no avail:
    
    ``` json
    "python.unitTest.unittestArgs": [
      "test"
      "*_test.py"
    ]
    ```
    
    ``` json
    "python.unitTest.unittestArgs": [
      "*_test.py"
    ]
    ```
    
    ``` json
    "python.unitTest.unittestArgs": [
      "'*_test.py'"
    ]
    ```
13. Get more grumpy and go and look at the extension code :rage: 
14. See [this](https://github.com/DonJayamanne/pythonVSCode/blob/d4e97123e42b41ce6e4fcc2bdfd7a0fa9a862229/src/client/unittests/unittest/collector.ts#L33) and try this config:
    
    ``` json
    "python.unitTest.unittestArgs": [
      "-p",
      "*_test.py"
    ]
    ```
    
    It didn't work.
15. Look for documentation in the repo, find [this](https://github.com/DonJayamanne/pythonVSCode/wiki/unitest-%28Standard-Unit-testing%29-Framework) and try this config:
    
    ``` json
    "python.unitTest.unittestArgs": [
      "-p *_test.py"
    ]
    ```
    
    This was unexpected as it's behaving differently to how I would expect args to work in other programs (ie. `-p` and `*_test.py` are separate args #456). "No tests run" again.
16. Go look at the test output and notice something _was_ actually happening (#452). Here is the output:
    
    ```
    ENoneType
    ENoneType
    ENoneType
    ENoneType
    ENoneType
    ENoneType
    ENoneType
    ENoneType
    ENoneType
    ENoneType
    ENoneType
    ENoneType
    ENoneType
    ENoneType
    
    ======================================================================
    ERROR: test.bubble_sort_optimised_test (unittest.loader._FailedTest)
    ----------------------------------------------------------------------
    ImportError: Failed to import test module: test.bubble_sort_optimised_test
    Traceback (most recent call last):
      File "/usr/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
        module = self._get_module_from_name(name)
      File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
        __import__(name)
      File "/home/daimms/dev/gwtw/py-sorting/test/bubble_sort_optimised_test.py", line 5, in <module>
        from base_custom_comparison_sort_test import BaseCustomComparisonSortTest
    ImportError: No module named 'base_custom_comparison_sort_test'
    
    ...
    
    ======================================================================
    ERROR: test.selection_sort_test (unittest.loader._FailedTest)
    ----------------------------------------------------------------------
    ImportError: Failed to import test module: test.selection_sort_test
    Traceback (most recent call last):
      File "/usr/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
        module = self._get_module_from_name(name)
      File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
        __import__(name)
      File "/home/daimms/dev/gwtw/py-sorting/test/selection_sort_test.py", line 5, in <module>
        from base_custom_comparison_sort_test import BaseCustomComparisonSortTest
    ImportError: No module named 'base_custom_comparison_sort_test'
    
    
    ----------------------------------------------------------------------
    Ran 14 tests in 0.004s
    
    FAILED (errors=14)
    ```
17. Switch back to python2.7 and I see this in the status bar:
    
    ![image](https://cloud.githubusercontent.com/assets/2193314/19744728/94b054e6-9b83-11e6-8016-b8013a166a3b.png)
18. Wonder why it's saying that only 7 tests passing when there are 489 tests.
19. Wonder why it's kind of working in python2.7 but not as all on python3 when my original test script uses python3
20. Look at the test output and notice it's saying 20 tests ran, 13 errored (ie. 7 passed) - my project only has 14 test _suites_ containing 489 individual unit tests.
21. Go back to the docs and see [this](https://github.com/DonJayamanne/pythonVSCode/wiki/unitest-%28Standard-Unit-testing%29-Framework#test-discovery), I add __init__.py to `./sort/common`
22. Run again and see this (#453):
    
    ![image](https://cloud.githubusercontent.com/assets/2193314/19745091/17494628-9b85-11e6-8e22-d5e3e2e2ecd2.png)
23. Assume these errors are due to the fact I'm still on python2.7 so I switch back to python3 and try running again. It still says No Tests Run and 14 tests failed in the output.
24. Get fed up and give up because I had spent about an hour trying to get it working.
### Actionable items

Ideally the user would get a little more help here, it was obviously a very cumbersome and irritating experience. Here are some things that could use some help:
- Why do I need to say I'm using `unittest`? Can't that be detected for me?
- Why can't the extension provide a little more help in configuring `python.unitTest.unittestArgs` through a few quick picks after my first test run. For example:
  - (Trigger run all tests, check if there is an existing test config for the workspace)
  - Quick pick: Select the test runner
  - Quick pick: Enter the test start directory (if not `.`)
  - Quick pick: Enter the test pattern (eg. `*_test.py`)
- Is there some standard way of indicating how tests are run in python projects similar to `npm test`? I generally don't want to commit a `.vscode` directory to a project, many projects won't accept editor-specific directories. This in particular means that you _must_ have VS Code in order to run tests.
- Why does the test runner not like my imports but my simple script works just fine?
- Anything else to aid in getting my tests to run under `python3` as I was never actually able to get them running.

Other self-contained issues that came out of this: #452, #453, #456, #458

**Comment by DonJayamanne** [comment]
https://github.com/DonJayamanne/pythonVSCode/commit/3f7097613080bc12525c4f53cdce62f113c1fd3d
https://github.com/DonJayamanne/pythonVSCode/commit/b68456347dd840d33e4ff0d90ad702efa2a1c672
https://github.com/DonJayamanne/pythonVSCode/commit/493bbf4bc83519fe3012f45942dd5f1f89958449
https://github.com/DonJayamanne/pythonVSCode/commit/f44da6ce1ff465f3939b06e0bde347b5c94b51cb

**Comment by DonJayamanne** [comment]
@Tyriar , totally agree with your suggestions.
Detecting test files and displaying prompts to setup the test framework.
Much better UX.. thanks for the great feedback.

**Comment by Tyriar** [comment]
@DonJayamanne thanks for looking into making improvements, anything to make it smoother will surely end in happier users :smile:

**Comment by DonJayamanne** [comment]
https://github.com/DonJayamanne/pythonVSCode/commit/4c8b08ebfcfb7d6599305f4f908901c79211021d
https://github.com/DonJayamanne/pythonVSCode/commit/0234dccb58c6e5597bbedde3146e3e3fc97ac7ea

**Comment by DonJayamanne** [comment]
>Switch back to python2.7 and I see this in the status bar:
Fixed
Note, the tests don't work on Python 2.7. This has to do with the imports of the tests.
When running the tests in the terminal window (it fails), i.e. tests fail even when not using VS Code Python extension.
Will try to identify the cause, either way, this isn't a extension issue.

> Wonder why it's saying that only 7 tests passing when there are 489 tests.
Fixed (bug).

> Wonder why it's kind of working in python2.7 but not as all on python3 when my original test script uses python3
I guess this was due to a configuration issue (haven't been able to replicate this).

**Comment by DonJayamanne** [comment]
> Is there some standard way of indicating how tests are run in python projects similar to npm test? 

Unfortunately no, not that I'm aware of.

> Why does the test runner not like my imports but my simple script works just fine?

This seems to be a Python 2.7 issue. Running the unittests via terminal results in similar (ImportError) issues. 

> Anything else to aid in getting my tests to run under python3 as I was never actually able to get them running.

Hopefully the recent changes will fix everything. At least from the testing I've done it has.

**Comment by DonJayamanne** [comment]
Identified the problem with running unittests against Python2.7:
You need to place a file named ```__init__.py``` in the ```py-sorting/sort/common``` directory as well.
