### ISSUE TITLE
completion item kind is always keyword 

### ISSUE THREAD

**Issue by Evrins** [DonJayamanne/pythonVSCode#46]
It looks like working fine in older version of Visual Studio Code.
but after I upgrade to Version 0.10.11, It always shows all completion item as a keyword.

Mac OSX: 10.11.3 (15D21)
Python: 3.5.1
Visual Studio Code 0.10.11

<img width="618" alt="screen shot 2016-03-17 at 10 52 49 pm" src="https://cloud.githubusercontent.com/assets/13133620/13850215/ffa051c4-ec93-11e5-998b-17eee20d0d99.png">

**Comment by DonJayamanne** [comment]
That's odd, please could you confirm that this is the case for everything ina Python file?

**Comment by Evrins** [comment]
Yes It is in a python file
and also I try use Mac OSX builtin version of python 2.7.10 It has the same problem
<img width="1280" alt="screen shot 2016-03-18 at 8 14 02 pm" src="https://cloud.githubusercontent.com/assets/13133620/13877548/7a7bef04-ed46-11e5-827d-587e05f088d5.png">
<img width="1280" alt="screen shot 2016-03-18 at 8 14 29 pm" src="https://cloud.githubusercontent.com/assets/13133620/13877549/7a95a818-ed46-11e5-8ee2-41e9569b955f.png">

**Comment by DonJayamanne** [comment]
Hi, please could you try the latest version and check how that goes.

**Comment by Evrins** [comment]
I have tried in two version of vs code, both does not work 
Code Insiders Version 0.10.14-insider (0.10.14-insider)
![2016-04-05 21 28 10](https://cloud.githubusercontent.com/assets/13133620/14283595/875a2ffe-fb76-11e5-8e33-c279ec639032.jpg)
![2016-04-05 21 28 31](https://cloud.githubusercontent.com/assets/13133620/14283599/8bf521c2-fb76-11e5-99b8-cc61655966a0.jpg)

Code Version 0.10.11 (0.10.11)

![2016-04-05 21 28 10](https://cloud.githubusercontent.com/assets/13133620/14283788/44fb82f6-fb77-11e5-8278-65073e47e909.jpg)
![2016-04-05 21 28 31](https://cloud.githubusercontent.com/assets/13133620/14283795/49e53e56-fb77-11e5-8f24-bb35272194bc.jpg)

**Comment by Evrins** [comment]
I have tried in two version of vs code, both does not work 
Code Insiders Version 0.10.14-insider (0.10.14-insider)
![2016-04-05 21 28 10](https://cloud.githubusercontent.com/assets/13133620/14283595/875a2ffe-fb76-11e5-8e33-c279ec639032.jpg)
![2016-04-05 21 28 31](https://cloud.githubusercontent.com/assets/13133620/14283599/8bf521c2-fb76-11e5-99b8-cc61655966a0.jpg)

Code Version 0.10.11 (0.10.11)

![2016-04-05 21 28 10](https://cloud.githubusercontent.com/assets/13133620/14283788/44fb82f6-fb77-11e5-8278-65073e47e909.jpg)
![2016-04-05 21 28 31](https://cloud.githubusercontent.com/assets/13133620/14283795/49e53e56-fb77-11e5-8f24-bb35272194bc.jpg)

**Comment by DonJayamanne** [comment]
I believe this issue can be closed as no one has has reported this. Please re-open if you are still experiencing this issue.
