### ISSUE TITLE
Jupyter - "Run cell" doesn't do anything

### ISSUE THREAD

**Issue by roblourens** [DonJayamanne/pythonVSCode#461]
I can't get this to work. I have jupyter installed and on the path, but 'Run cell' does nothing when I click on it. What am I doing wrong?

![image](https://cloud.githubusercontent.com/assets/323878/19746099/b278ba4e-9b89-11e6-9d9b-0535c1b46f7e.png)

**Comment by DonJayamanne** [comment]
@roblourens 
- Please check if any errors are logged in the ```Python``` output panel.
- Also check the console window in ```Developer Tools``` (Menu option Help->Developer Tools)

**Comment by roblourens** [comment]
No errors in the output panel or developer tools console

**Comment by roblourens** [comment]
I have built the extension and can debug if needed

**Comment by roblourens** [comment]
I was able to get this working. I'd installed Anaconda, but had my pythonPath set to a different python version that was missing ipython and the other required packages. I could get it working two ways - Once I installed ipython, I saw errors for other missing packages and could install them with pip, then have it working. Or also, I could set my pythonPath to one with those packages, and it worked.

It would be much nicer if there was an obvious error message when these packages are missing.

**Comment by DonJayamanne** [comment]
>I saw errors for other missing packages and could install them with pip

I thought you said there were no errors earlier.

>It would be much nicer if there was an obvious error message when these packages are missing.

Yes, Will look into this.

**Comment by roblourens** [comment]
At first there were no errors. Then @octref had me install ipython (for the correct python install). After that, we saw a few errors in the python output channel for other missing packages. I don't know why there was no error for ipython missing.

**Comment by octref** [comment]
@DonJayamanne Just wondering, is it after you install Anaconda you need to point the kernel to `~/anaconda/bin/python`? Rob had set `/usr/local/bin/python3.5` as kernel and it didn't work.

**Comment by DonJayamanne** [comment]
@octref 
When installing anaconda, you are installing a completely different python interpreter. 
Hence you need to tell VS Code which interpreter is to be used. You can do this from the command palette (```Select Workspace Interpreter```)

**Comment by octref** [comment]
@DonJayamanne Thanks for your explanation. If anaconda is targeted to people who don't have much python experience, what you said should also added to the wiki to make the experience smoother for them, imo.
