### ISSUE TITLE
Linter not run when opening file

### ISSUE THREAD

**Issue by chrmarti** [DonJayamanne/pythonVSCode#462]
Version 0.5.0, Windows 10

Using pylint, opening a file does not show any linting annotations:

![linter-not-run-on-open](https://cloud.githubusercontent.com/assets/9205389/19746247/5d1c6270-9b8a-11e6-8228-13576367e38f.PNG)

Only after save:

![linter-run-on-save](https://cloud.githubusercontent.com/assets/9205389/19746255/65afd462-9b8a-11e6-94dc-93672b5ee5c5.PNG)

I'd expect the linter to run on all open files.

The Python Output channel doesn't show any linter output after opening the file, only after saving. (Consistent with the behavior above.)

**Comment by DonJayamanne** [comment]
@chrmarti 
Yes thats right. Today linter is run only when a file is saved.
I'll make the changes to run the linter when a file is opened (consistent with typescript and javascript linters).
