### ISSUE TITLE
Rename local variable success, but the indicator on top keeps going on 

### ISSUE THREAD

**Issue by ramya-rao-a** [DonJayamanne/pythonVSCode#464]
```python
abc = 1
print(abc)
```

I renamed the `abc` variable above, the rename was a success, undo works, but the progress bar up top keeps going on and on and on .....

No errors in the console

**Comment by gandhis1** [comment]
As I mentioned in #440, I have run into this and similar issues quite frequently (just never had enough time to put together a complete test case and submit as a bug). Often, it simply does not work. If more examples are needed I can add some here.

**Comment by DonJayamanne** [comment]
Will close and track it in #440
