### ISSUE TITLE
Python crashes while debugging

### ISSUE THREAD

**Issue by roblourens** [DonJayamanne/pythonVSCode#465]
Simple script, debugging with the system's python3.5, and when i step all the way to the end, it says "python quit unexpectedly". Not sure why or whether there's anything you can do about it. Right now it's happening about 2/3 times.

![image](https://cloud.githubusercontent.com/assets/323878/19747195/1df5ba7e-9b8f-11e6-85d0-f12a2d437544.png)

**Comment by DonJayamanne** [comment]
@roblourens 
- Is this random or always?  
- What happens if you run this script outside VS Code?

**Comment by roblourens** [comment]
Randomly, but often. I haven't seen any crash if I run it in the terminal. And with any script it seems, if I run it all the way to the end.

**Comment by DonJayamanne** [comment]
@roblourens 
at this stage I have absolutely no idea where this is coming from.
Can you also check the ```console``` window in  developer tools (menu Help -> Developer Tools)

**Comment by roblourens** [comment]
I don't see any errors there. I also don't see it crash with other installations of python.

When I run it with `"console": "integratedTerminal"`, I see "segmentation fault: 11" when it crashes. There's probably not much to do here so you can close it if you want. It's not blocking anything since it only crashes at the end of the program. But one clue is that it only crashes when I 'step' off the end, never when I 'continue' to the end.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#66
