### ISSUE TITLE
Extract variable and Extract method do not use the user provided name

### ISSUE THREAD

**Issue by ramya-rao-a** [DonJayamanne/pythonVSCode#467]
- Have the code `print 16`
- Select 16 -> Right-click -> Choose "Extract Variable"
- New name is generated, and a box opens where user can override the new name
- Type in your choice , hit enter

Your choice is not taken 

- Undo the change
- Select "print 16" -> Right-click -> Choose "Extract Method"
- New name is generated, and a box opens where user can override the new name
- Type in your choice , hit enter

Your choice is not taken 

And then there is that progress bar on top that goes on and on and on ...

**Comment by DonJayamanne** [comment]
Fixed https://github.com/DonJayamanne/pythonVSCode/commit/7c82b49c7f517251c3d08282b02a897abb594bdb
