### ISSUE TITLE
debugger launch.json configuration options not documented

### ISSUE THREAD

**Issue by Spensaur-K** [DonJayamanne/pythonVSCode#47]
I apologize in advance If I've just missed something on the readme, but I have python 2 on my PATH (windows) and needed to debug with python 3. The readme states that the "Path to python can be configured", but I couldn't find any instructions on how to do this and ended up searching the source code for `configurations[].pythonPath`

Would be possible to either document new launch.json configuration options in the readme or add them to the default configuration file (if there is one) with null values?

**Comment by ghjconan** [comment]
![image](https://cloud.githubusercontent.com/assets/5849164/13863462/eeff886c-ecd4-11e5-8644-3e7f4aab9a83.jpeg)
you can just add pythonPath directly.

**Comment by Spensaur-K** [comment]
Yeah I figured that out, but my problem was that I had to dig into the source for it. I was wondering if it could be documented somewhere

**Comment by DonJayamanne** [comment]
Hi, the documentation is already available.
When on the [Python Extensions page](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python), click into the Wiki or on the [Wiki](https://github.com/DonJayamanne/pythonVSCode/wiki) in Github.
& then go to [Debugging](https://github.com/DonJayamanne/pythonVSCode/wiki/Debugging)
