### ISSUE TITLE
Auto-complete on import statement shows unnecessary/redundant symbols

### ISSUE THREAD

**Issue by gandhis1** [DonJayamanne/pythonVSCode#472]
When I have two files, one importing from another file, like the example below, and I attempt to auto-complete the "from X import Y", I get a lot of unnecessary and redundant symbols.

- The auto-complete does not work until I press CTRL + Space.
- The other module's imports show up in this list
- Code snippets show up here, which doesn't make sense. It should know that you are ending an import statement and only importable objects should be in this list. 
- In the screenshot below, there are only two things that really should show up here, and that is "main" and "generate_hpi_analytics_national_level". The rest comes from other modules. 

![untitled](https://cloud.githubusercontent.com/assets/21064086/19776565/88dd7602-9c42-11e6-9cdf-6bba8020e9d6.png)

**Comment by DonJayamanne** [comment]
Unfortunately this is an upstream issue ((Jupyter)[http://jedi.jedidjah.ch/en/latest/docs/plugin-api-classes.html#jedi.api.classes.Completion]), library used to provide autocompete/intellisense functionality.
