### ISSUE TITLE
Debugger in Python not stopping after using MongoDB server listening

### ISSUE THREAD

**Issue by rodischi** [DonJayamanne/pythonVSCode#473]
Using VS Code: Debugger stops at break points before the call to connect to server. After that the program still runs but it does not stop at any break points from then on.
Included the file with comments "Stops here" . Once it goes to bottle.run it does not come to any more breakpoints. (Rename it back to *.py to see the code better)

[blog.py.txt](https://github.com/DonJayamanne/pythonVSCode/files/559086/blog.py.txt)

I have something similar with nodeJS debugger and that works fine.

thanks.

**Comment by rodischi** [comment]
no worries, it started working, I don't have any idea why it wasn't before, since it stopped at some points.

**Comment by DonJayamanne** [comment]
Thanks

**Comment by rodischi** [comment]
thank you for the great job witth creating this debugger, and your prompt response!Rodica
