### ISSUE TITLE
Problem with the function in the code cell block

### ISSUE THREAD

**Issue by PFSWcas** [DonJayamanne/pythonVSCode#475]
Firstly, I want to say that the pythonVScode is very nice. However, I encounter a problem when I run the code cell in the pythonVscode. There is a called function in the cell block and this function is defined in another .py file. When I change this function and run the cell, the change of the function do not take effect and the older version still runs. Can you help me?

**Comment by DonJayamanne** [comment]
Sure thing, however I'll need some more information, more than you have already provided. Here's what I need:
- OS version  
- Python version  
- Provide the code for both files  
- Provide any errors displayed (in ```Python``` output panel and ```console``` tab of Develper Tools)  
- Steps to reproduce the issue

**Comment by PFSWcas** [comment]
OK, 
# The OS version is Windows 10 64 bits.
#  The python version is 3.5
#  The code is below:

`testVscode.py`

`# -*- coding: utf-8 -*-
"""
Created on Mon Oct 24 19:23:29 2016
@author: PFSW
"""
def printInfo():
    print('My OS is Windows 10')`

The main function:
`
#%%
from classifiers.testVScode import printInfo
printInfo()
`
When I run the cell block, the Results show:
My OS is Windows 10
When I change the testVscode.py to:
`
def printInfo():
    print('My OS is Windows 10')
    print('My python version is 3.5')
`
then I run the cell again, the Results show:
My OS is Windows 10

This is the problem. How can I handle it ?

**Comment by PFSWcas** [comment]
# Basic information
OS version: Windows 10 
Python version: 3.5
#  Code
`testVScode.py`
`def printInfo():`
      `print('My OS is Windows 10')`

`maintest.py`
...
`#%%`
`from classifiers.testVScode import printInfo`
`printInfo()`

When I run the cell, then the **Results** show that:
My OS is Windows 10.
However, when I change the `testVScode.py` to:
`def printInfo():`
      `print('My OS is Windows 10')`
      `print('My python version is 3.5')`

Then I run the cell again, then the **Results** show that:
My OS is Windows 10

The change does not takes effect. So, this is the problem.

**Comment by willyd** [comment]
If I am not mistaken ipython will not automatically reload modules on change unless told to do so via configuration. In my ipython_config.py I have
```
c = get_config()
c.InteractiveShellApp.extensions = ['autoreload']
c.InteractiveShellApp.exec_lines = ['%autoreload 2']
c.InteractiveShellApp.exec_lines.append('print("Warning: disable autoreload in ipython_config.py to improve performance.")')
```
This way whenever I make a change to some module ipython will reload the module.

**Comment by PFSWcas** [comment]
It really works. Thank you very much for your help! @willyd @DonJayamanne

**Comment by DonJayamanne** [comment]
@willyd , thanks for your response. Will include this into the Wiki and then close this.

**Comment by DonJayamanne** [comment]
Wiki has been updated

**Comment by willyd** [comment]
No problem. Glad I could help.
