### ISSUE TITLE
Jupyter starts up with errors

### ISSUE THREAD

**Issue by gandhis1** [DonJayamanne/pythonVSCode#476]
So typically when I start up VS Code, open a Python file, highlight some text, and press CTRL+Alt+Enter, the first time I do so, I get a number of error messages at the top of the screen. Instead of screenshotting those, I copied the log entries below. The strange thing to me is that if I wait and I continue to do nothing else but press CTRL+Alt+Enter, eventually the kernel does start up and the code runs.

If the kernel isn't available, ideally the extension should be telling me it is starting/restarting it, and show some kind of indication in the bottom status bar that it is starting up the kernel (or whatever it is doing). 

Operating System: Windows 7
VS Code: 1.6.1
Python Extension: 0.5.0 (latest public)
Python Distribution: Anaconda 64-bit (latest)

![capture342](https://cloud.githubusercontent.com/assets/21064086/19830693/1283a442-9dcb-11e6-83c5-25ced25c18af.PNG)

**Comment by gandhis1** [comment]
I'm still getting these errors in 0.5.1. Will do some more digging later to see if I can get some more information on why these are occurring.

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/vscodeJupyter#20
