### ISSUE TITLE
Python extension breaks CTRL + ALT + ENTER shortcut in VSCode

### ISSUE THREAD

**Issue by pcgeek86** [DonJayamanne/pythonVSCode#477]
In VSCode 1.6.1, I follow this process:

1. Create a new file, and add some text (eg. `Trevor Sullivan`)
2. Perform a replace operation (`CTRL + H`)
3. Use the `CTRL +ALT + ENTER` command to "Replace All" (global replace)

Unfortunately, with the Python extension installed, this keyboard shortcut seems to be broken. I've replicated this behavior on two separate systems, so I'm fairly certain it's a bug with the Python extension. As soon as I remove the Python extension, and reload VSCode, the `CTRL + ALT + ENTER` keyboard shortcut works correctly for global replace.

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by gandhis1** [comment]
This was identified and fixed in #423, which will come out with next release (whenever it is)

**Comment by pcgeek86** [comment]
@gandhis1 Thanks for the heads up!
