### ISSUE TITLE
Python decorator obsfucates function signature in hover

### ISSUE THREAD

**Issue by gandhis1** [DonJayamanne/pythonVSCode#478]
So I have a function which uses Numba's jit decorator.

```
@jit()
def calculate_cash_flows(remaining_loan_term, remaining_io_term,
                         settle_balance, settle_date, payment_day, 
                         ir_fixed, ir_accrual_day_count_basis,
                         amortizing_debt_service):
```

Hovering over a call of this function does not show the correct signature, although the auto-complete right below it does. 

![untitled](https://cloud.githubusercontent.com/assets/21064086/19858770/29198e6c-9f59-11e6-9fda-7b15c34729b3.png)

**Comment by DonJayamanne** [comment]
Fixed in https://github.com/DonJayamanne/pythonVSCode/issues/457

**Comment by DonJayamanne** [comment]
Duplicate https://github.com/DonJayamanne/pythonVSCode/issues/742
