### ISSUE TITLE
Django 1.7 template debugging 

### ISSUE THREAD

**Issue by martingronlund** [DonJayamanne/pythonVSCode#479]
I can see in the code you've written for django template debugging that you've only added support for version 1.8 and above, which is a valid thing to do given that django < 1.8 is considered insecure. However, I'm in need of a 1.7 version. Right now I can't use my debug console because the following is being spit out for each template:
'WARNING: Template path is not available. Please set TEMPLATE_DEBUG=True in your settings.py to make django template breakpoints working'
with an occasional
'Source is None\n'

**Comment by DonJayamanne** [comment]
Have you tried setting ```TEMPLATE_DEBUG=True ``` in settings.py.
Debugging templates for <1.8 isn't supported.

**Comment by DonJayamanne** [comment]
Ok, let me get this right. All you would like is for the these messages not to be displayed in the debug console, is that right?

**Comment by martingronlund** [comment]
That'd be great, since they don't apply.

**Comment by DonJayamanne** [comment]
Fix will be in the next release.
All you will need to do is modify ```launch.json``` and the value "IgnoreDjangoTemplateWarnings" into the "debugOptions" array, see below for a sample:

```json
          {
            "name": "Django",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${workspaceRoot}/manage.py",
            "args": [
              "runserver",
              "--noreload"
            ],
            "debugOptions": [
              "WaitOnAbnormalExit",
              "WaitOnNormalExit",
              "RedirectOutput",
              "DjangoDebugging",
              "IgnoreDjangoTemplateWarnings"
            ]
          },
```
