### ISSUE TITLE
how to use this for flask virtualenv

### ISSUE THREAD

**Issue by lewis617** [DonJayamanne/pythonVSCode#48]
I use flask and I use the virtualenv to run the manage.py ,but I do not know how to to change the python path to virtualenv python path I build .

so I want to ask how to use this for flask virtualenv

**Comment by hedin** [comment]
You should set python.pythonPath variable to your python executable inside virtualenv's bin/ directory as described here: https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Version
For example my python.pythonPath looks like this:
`"pythonPath": "/home/alex/.virtualenvs/venv-py3/bin/python3"`

**Comment by lewis617** [comment]
@hedin 
thanks, you are right! I should read the document carefully
