### ISSUE TITLE
feature request: support IPython console

### ISSUE THREAD

**Issue by mickeydonkey** [DonJayamanne/pythonVSCode#480]
Dear developer of pythonVSCode:

IMHO current IPython integration #303 is like a variation of jupyter notebook. While IPython console is a popular REPL mode  which arms user with convenient magic commands.
To enter IPython console, one just types 'ipython' in terminal. It'll be great to see functionality like:
1. simply "python: run selection in ipython console"
2. running a code cell in the IPython console and display its output in parallel;

Thanks

**Comment by mickeydonkey** [comment]
IPython Qtconsole is more powerful than plain IPython console in terminal. An app that embeds IPython QT is spyder-ide (https://github.com/spyder-ide/spyder)console,  I'm not sure If it can be embeded in vscode though.

**Comment by DonJayamanne** [comment]
@mickeydonkey 
Embedding the QTconsole into VS Code wouldn't be possible. However we could build something similar.

**Comment by gandhis1** [comment]
@mickeydonkey , What benefit do you see in using IPython console instead of the Jupyter notebook kernel? To me, having both features is redundant. You can run magic commands in Jupyter, and you can also run selections in Jupyter.

**Comment by mickeydonkey** [comment]
@gandhis1 Thanks for your interest. Yes, IPython console, IPython QTconsole and Jupyter notebook all provide some functionalities in common, like the magic commands you mentioned. that is because of the IPython kernel they are all connected to. IPython console or the improved counterpart - IPython QTconsole- is not the reinvented wheel compared to jupyter notebook.

 To me IPython console is more like the under-the-hood mode of IPython kernel, all user codes history in the IPython kernel are recorded and displayed in the console so I can see the order in which my code inputs were ran. By pressing upper-arrow key I can easily call the code in history and make some modification based on that. But when it comes notebook, code cell are overwritten when I modify existing code cells and the order of cells are not that easy to figure out. That is especially true when your task involves lots of small try-and-error experiments before you finally know how to do the job correctly. I am more comfortable with shell-like convenience, In fact Most of time Qtconsole's image-display feature can make me happy and I only resort to notebook when I need fancier data visualization functionality for data-presentation purpose. 

IPython console can also be used as a debug console as the PyCharm IDE already supported. When the program stops at one breakpoint, I can explore with IPython console's functionality. For debugging data science programs like data wrangling, Traditional watch list approach is not good for watching data tables, It could be a huge benefit if we can display some inline image to inspect the on-the-fly status of our "tables". Actually a friend of mine who comes from MATLAB world complained to me the lack of similar feature in Python world. 

I've tried several IDEs and found out no perfect one for data science project. Either weak in debug, visualization or interactivity. As VS Code use the web-technology like RStudio, more possibilities are open. I am looking forward to seeing VS Code growing into the de facto data science IDE for python.

**Comment by martinfiers** [comment]
I would also like to vote for this feature. My main usage would be to run small try-and-error experiments without having to leave the editor environment. Secondly, I'd use it to run small pieces from selection or from a code cell; inspect the results, experiment with some list comprehensions based on the available variables, etc, in a REPL fashion. So quite similar to what @mickeydonkey explains.

Resetting the console would be quite important, especially when the applications you're debugging are very stateful.

**Comment by Twizzledrizzle** [comment]
Also interested in this! Currently testing with running ipython in the debug console instead

**Comment by gandhis1** [comment]
I have a few additional thoughts on this. There are currently a couple of actions that can be performed in the editor, "Run Python File in Terminal" and "Run Selection in Python Terminal". What if a setting was added which allows one to use iPython Console instead of a regular Python Terminal, and then executing code in the terminal operated off of this?

**Comment by jruizaranguren** [comment]
This can be done just by changing the pythonpath setting in the workspace settings (or alternatively in the user settings). For instance, if you have installed Anaconda:

```
{
    "python.pythonPath": "D:/Anaconda/Scripts/ipython3.exe"
}
```

**Comment by gandhis1** [comment]
If I am running an application stand-alone, of course I want to use the regular Python interpreter, which is more lightweight and has faster startup time. Only if I want to be doing interactive stuff do I want to be using IPython. To use the same for both would not be ideal.

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/vscodeJupyter#19

**Comment by sillmanite** [comment]
I'd like to see a better interpreter as well
