### ISSUE TITLE
Python Debugging

### ISSUE THREAD

**Issue by mohantsa** [DonJayamanne/pythonVSCode#481]
am finding issue like Error: spawn EACCES . when debugging.

**Comment by DonJayamanne** [comment]
Please could you go into console window (help->developer tools) and let me know what errors are in there.

**Comment by DonJayamanne** [comment]
Please reopen if problem persists

**Comment by mohantsa** [comment]
Error: spawn EACCES
help debug
Please start a debug session to evaluate
