### ISSUE TITLE
Add support for meta-linter Pylama

### ISSUE THREAD

**Issue by tdamsma** [DonJayamanne/pythonVSCode#482]
It would be very nice if support for [pylama](https://github.com/klen/pylama) can be added. Pylama wraps several other linters, and is configurable from setup.cfg/tox.ini/pytest.ini etc, making it easy to use for testing and continuous integration. 

The following atom linters already implement pylama, maybe that helps:
 - https://atom.io/packages/linter-pylama
 - https://atom.io/packages/linter-python

**Comment by JWDobken** [comment]
@tdamsma this would be a nice improv; actually a critical feature for me to completely step over from Atom

**Comment by ErnaOudman** [comment]
That would indeed be a great addition!

**Comment by DonJayamanne** [comment]
@tdamsma 
You need to define the configuration settings in package.json as follows:
```json
        "python.linting.pylamaEnabled": {
          "type": "boolean",
          "default": true,
          "description": "Whether to lint Python files using pylama."
        },
        "python.linting.pylamaPath": {
          "type": "string",
          "default": "pylama",
          "description": "Path to pylama, you can use a custom version of pylama by modifying this setting to include the full path."
        },
        "python.linting.pylamaArgs": {
          "type": "array",
          "description": "Arguments passed in. Each argument is a separate item in the array.",
          "default": [],
          "items": {
            "type": "string"
          }
        },
```

**Comment by DonJayamanne** [comment]
Closed, as this has been added in the latest version 
Closed via PR, thanks @tdamsma  https://github.com/DonJayamanne/pythonVSCode/pull/495
