### ISSUE TITLE
Something was wrong when i use run cell function

### ISSUE THREAD

**Issue by CwjXFH** [DonJayamanne/pythonVSCode#484]
Hi,
I feel the run cell function is cool,but when i usinge it,i encountered some errors.
### Basic Info
**OS Version:**         Windows10
**Python Version:**   3.4.3
**VSCode Version:** 1.7.1

### My Code
```Python

#%%
print('python.jupyter')
```
### My Config
```json
    "python.pythonPath": "D:\\Python\\python.exe",
    "python.jupyter.defaultKernel": "D:\\Python\\python.exe"
```

### Error Info
![error info shown in developer tool](https://cloud.githubusercontent.com/assets/11468733/19994017/1584ea2a-a285-11e6-9a08-b9938ea74443.PNG)
![error info shown in developer tool](https://cloud.githubusercontent.com/assets/11468733/19994027/2cbded40-a285-11e6-9dcf-ddaa724c9eb8.PNG)

**Comment by DonJayamanne** [comment]
Please try clearing the value for ```defaultKernel``` and try again

**Comment by CwjXFH** [comment]
I installed Python2 and Python3, the value of defaultKernel is the path to Python3.
I clear it and try again,but the above error  still occurs.

**Comment by DonJayamanne** [comment]
@CwjXFH 
Have you installed Jupyter or IPython?

**Comment by CwjXFH** [comment]
@DonJayamanne 
No,
i download python from https://www.python.org/

**Comment by DonJayamanne** [comment]
You need to install jupyter

**Comment by DonJayamanne** [comment]
http://jupyter.org
