### ISSUE TITLE
goToDeclaration doesn't work

### ISSUE THREAD

**Issue by liuhao2050** [DonJayamanne/pythonVSCode#49]
VSCode Version:0.10.11
OS Version:ubuntu 14.04 LTS

When I use F12 or Alt+click to go to a definition of python class,it doesnt work.

Please help me ...

**Comment by DonJayamanne** [comment]
Hi, does it work for other classes?
Can you try the following:
Create a new directory add a simple Python file in there and open up that directory from vscode.
Now add a class into that file and check if code navigation works?

**Comment by liuhao2050** [comment]
I did this ,and it doesn't work with any class.

**Comment by DonJayamanne** [comment]
Please could you confirm you have configured the path thom to the python executable as per the documentation.

**Comment by liuhao2050** [comment]
Hi,thank you very much , following  is my only config in task.json and  I do nothing but this.
// Compiles a HelloWorld.ts program
{
	"version": "0.1.0",

	// The command is tsc. Assumes that tsc has been installed using npm install -g typescript
	"command": "python",

	// The command is a shell script
	"isShellCommand": true,

	// Show the output window only if unrecognized errors occur.
	"showOutput": "always",

	// args is the HelloWorld program to compile.
	"args": ["${file}"]
	
}

**Comment by DonJayamanne** [comment]
Hi, please could you configure your settings file as per the documentation on the following page:
https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Version

**Comment by DonJayamanne** [comment]
That should fix it

**Comment by liuhao2050** [comment]
Hi,I just did that page's say and it doesn't works.I'm sorry, T_T, following is my settings, could you please  find something  error?
```
//User Settings file (settings.json) 
{
    "editor.fontFamily": "Monaco",
    "editor.fontSize": 16,
    "editor.tabSize": 4,
    "editor.insertSpaces": true,
    "editor.renderWhitespace": true,
    "draw_white_space": "all",
    "exclude_folders": [".git","node_modules","bower_components"
    ,"*.pyc"],
    "python.pythonPath": "/usr/bin/python"

}
```
```
//Workspace Settings file (settings.json)
{
    "python.pythonPath": "/usr/bin/python"
}
```
```
//lunch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${file}",
            "pythonPath": "/usr/bin/python",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }
    ]
}
```
➜  ~ which python   
/usr/bin/python
➜  ~ 
OS Version:ubuntu 14.04 LTS
Thank you!
