### ISSUE TITLE
Add visual feedback animation for entering Python debugging

### ISSUE THREAD

**Issue by gandhis1** [DonJayamanne/pythonVSCode#490]
When attempting to debug the extension itself, I noticed TS/JS had a useful visual feedback animation in the bottom left-hand corner. 

![image](https://cloud.githubusercontent.com/assets/21064086/20039598/a7530bf4-a414-11e6-8a9e-bfd5a8ce3f91.png)

Sometimes, the Python start-up takes a bit of time, and it would be good to have some kind of visual feedback, so I don't end up pressing F5 multiple times because I'm not aware it worked the first time.

**Comment by DonJayamanne** [comment]
Upstream issue. Not related to the extension.
