### ISSUE TITLE
Debugger breaks on first line of source file

### ISSUE THREAD

**Issue by gandhis1** [DonJayamanne/pythonVSCode#491]
I've only ever noticed this behavior from pythonVSCode, and not any other IDE I've used in the past.

If I haven't set a breakpoint at that line, why is it breaking there? It should hit the first breakpoint I actually set, wherever it is located. 

![image](https://cloud.githubusercontent.com/assets/21064086/20039690/1ad1e860-a416-11e6-82bc-f019086e7009.png)

**Comment by DonJayamanne** [comment]
Change the value of ```stopOnEntry``` to ```false``` in ```launch.json```.

**Comment by gandhis1** [comment]
Thanks, is there a reason why it's set to true by default? Seems like non-standard IDE behavior compared to the others I've used before

**Comment by DonJayamanne** [comment]
@gandhis1 
I agree with you to a certain extent. (PR https://github.com/DonJayamanne/pythonVSCode/pull/508) 
However, this is the standard behaviour in the nodejs debugger in VS Code. I wanted to have a similar experience.
To date only two people have raised this issue, your self and another (#519).

So changing this now, would result in a major UX for all users who are accustomed to this behaviour. I.e. it isn't a change that can be made, without impacting everyone who expects the debugger to break as soon as they start debugging.

I have re-open this issue so we can get users feed back on this.

**Comment by gpassero** [comment]
I've got frustrated with this behavior too. Changing stopOnEntry parameters solved. I'd also like this parameter to have "false" value by default.

**Comment by DonJayamanne** [comment]
Not in favour of this, as this is the default with node.js debugger on vs code.

**Comment by DonJayamanne** [comment]
Closing as this is the default behaviour in VS Code for other languages. And there haven't been too many up-votes for this.
