### ISSUE TITLE
remote debug - "source Unknown Source is not available"

### ISSUE THREAD

**Issue by komi3D** [DonJayamanne/pythonVSCode#493]
VSCode: 
Version 1.7.1
Commit 02611b40b24c9df2726ad8b33f5ef5f67ac30b44
Date 2016-11-03T13:53:14.822Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0

pythonVSCode: 0.5.0

I have Python34 installed on my Windows X PC. I also have PTVS 2.2 installed.

When debugging it in VSCode it opens new file with name on tab: Unknown Source and a message:
"source Unknown Source is not available"
Debugger seems to be working partly. I can see the variables, I can add Watch. I can also step through breakpoints using top debugger tools.
Unfortunatelly I cannot see the remote source file and I don't know which is the ACTIVE breakpoint.
Callstack section also shows: "module: Unknown Source".

I have a sample file 'test_remote_debug.py':

` import sys
import ptvsd
from time import sleep

ptvsd.enable_attach("my_secret", address = ('127.0.0.1', 3000))
a = 10
print('waiting on 3000')
#Enable the below line of code only if you want the application to wait untill the debugger has attached to it
ptvsd.wait_for_attach()
print('ATTACHED!')
a = 20
ptvsd.wait_for_attach
sleep(3)
a = 30
print('Slept well!')
a = 40`

I put 3 breakpoint on last three assignments to 'a' variable on the file my Y: disk in one of subfolders (this is the workspace opened in VSCode). I run the copied file from C:/tmp directory
with command 
`python test_remote_debug.py`
I
My configuration 'launch.json' is the following:
`{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach (Remote Debug)",
      "type": "python",
      "request": "attach",
      "localRoot": "${workspaceRoot}",
      "remoteRoot": "C:/tmp",
      "port": 3000,
      "secret": "my_secret",
      "host": "127.0.0.1"
    }
  ]
}`

Could you please take a look at it and fix it? I would really like to use remote debugging feature.
I tested the same file with Visual Studio Community 2013 with PTVS 2.2 extension and debugger is working fine.

Thanks for a great addon!

**Comment by DonJayamanne** [comment]
What is the structure of the source and remote source location? 
Please provide file names with folder structures.

**Comment by komi3D** [comment]
Hi,
Today I found some time to play around with this a bit more. Here are my test results:
I always run python test_remote_debug.py from C:/tmp directory
1) in case my vscode workspace is:
C:/vscode_workspace
C:/vscode_workspace/test_remote_debug.py
C:/vscode_workspace/.vscode/launch.json
I am able to attach and the remote file with tmp is opened in new tab. However debugging stops on different line than I put breakpoints.
IMPORTANT: it only works if in launch.json I have settings:
      "localRoot": "${workspaceRoot}",
      "remoteRoot": "${workspaceRoot}",
If I change remoteRoot to "C:/tmp" 
I get the described error: Source Unknown, Source Unavailable

If I change remoteRoot to "C:\\tmp"
Then the new tab with remote file is not shown, but the debugging starts working on the file from workspace: C:/vscode_workspace/test_remote_debug.py

So maybe after all this is simply a configuration issue with the path in remoteRoot setting?

Anyway - could you please describe what should happen when a user presses Attach?
Should a new remote file be opened in new tab?
Should it contain breakpoints?
Where should user define breakpoints? in local file or in opened remote file?

For anyone having the same issue: it seems the solution is in WINDOWS to use path with double backslashes for the remoteRoot property. I have no idea if a similar issue exists on Linux...

Thanks.

**Comment by DonJayamanne** [comment]
@komi3D are you still experiencing this issue, please reopen if you are.
