### ISSUE TITLE
Function or class annotation cannt display Unicode 

### ISSUE THREAD

**Issue by onefate** [DonJayamanne/pythonVSCode#496]
When move my mouse on a function or a class writen by myself , it  can't show unicode(utf8) doc currently .

**Comment by DonJayamanne** [comment]
Please  provide an example of the issue

**Comment by onefate** [comment]
@DonJayamanne Just see some [imgs](https://www.dropbox.com/sh/we58u70mfzq8hwv/AADk-6R0-5xr9NdL25jTekt2a?dl=0) from my dropbox;
PS: I did some further acitons: When I open the .py file where the function was defined.  And when mouseon its name, it shows the docstring currently. Then I come back to the file who called this function, repeat "mouseon",it becomes current. And then I closed vscode editor without any save, and open vscode again it shows wrong again.

**Comment by DonJayamanne** [comment]
This has been fixed in the latest version (please download and install the latest version of the extension, Version 0.5.1)
Related issue - https://github.com/DonJayamanne/pythonVSCode/issues/293

**Comment by onefate** [comment]
@DonJayamanne Are you sure, because it now shows "loading" all the time.（in Chinese : 正在加载...）
The version of my vscode is 1.7.1

**Comment by DonJayamanne** [comment]
What's in the console (help->developer tools menu)

**Comment by onefate** [comment]
@DonJayamanne but I'm sure my files  are all in utf8, not in gbk

workbench.main.js:121 [Extension Host] ---------------------------I.logExtensionHostMessage @ workbench.main.js:121I.onMessaage @ workbench.main.js:121(anonymous function) @ workbench.main.js:121emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
workbench.main.js:121 [Extension Host] stderr jediProxyI.logExtensionHostMessage @ workbench.main.js:121I.onMessaage @ workbench.main.js:121(anonymous function) @ workbench.main.js:121emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
workbench.main.js:121 [Extension Host] Error (stderr) Traceback (most recent call last):
  File "completion.py", line 404, in watch
    self._process_request(self._input.readline())
  File "completion.py", line 374, in _process_request
    column=request['column'], path=request.get('path', ''))
  File "preview\jedi\jedi\api\__init__.py", line 109, in __init__
    source = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 16: illegal multibyte sequence

I.logExtensionHostMessage @ workbench.main.js:121I.onMessaage @ workbench.main.js:121(anonymous function) @ workbench.main.js:121emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98

**Comment by onefate** [comment]
![1](https://cloud.githubusercontent.com/assets/7592341/20132307/4f71771e-a69d-11e6-95b6-4917679d18cf.png)

**Comment by DonJayamanne** [comment]
Please could you try the following:
- Close all instances of VS Code  
- Set the environment variable ```PYTHONIOENCODING``` to ```gbk```  
- Open VS Code and try again

**Comment by onefate** [comment]
@DonJayamanne I will try your method later, but I just **edited your code** and it seems work... I don't know why. 
![1](https://cloud.githubusercontent.com/assets/7592341/20136750/80bee8e2-a6b1-11e6-89b7-dd01d79b42b4.png)

**Comment by guhuajun** [comment]
After rolling back to 0.5.0, it works again.

**Comment by DonJayamanne** [comment]
Will fix this asap.

**Comment by DonJayamanne** [comment]
New version released, with this fix
