### ISSUE TITLE
type hint and auto completion has different result.

### ISSUE THREAD

**Issue by Cologler** [DonJayamanne/pythonVSCode#497]
## Environment data
VS Code version:  1.7.1
Python Extension version:  0.5.0
Python Version:   3.5.1
OS and version:    win 10 x64
pylint version: 1.6.4

## Actual behavior

err msg:

![picpick-20161108-225132-001](https://cloud.githubusercontent.com/assets/10906962/20103685/f439206e-a605-11e6-9190-ec137664bee0.png)

but auto completion know it is my custom type:

![picpick-20161108-224925-001](https://cloud.githubusercontent.com/assets/10906962/20103613/b4d68d30-a605-11e6-9c19-493c1c2dee15.png)

**Is this is pylint's bug?**

project can found here:

https://github.com/Cologler/py.jasily.cologler

the file is `./dependencyinjection/impl_invoker.py`

**Comment by DonJayamanne** [comment]
This is a pylint issue

**Comment by gandhis1** [comment]
Can we re-open this? It's still possible that pyLint is not configured correctly or some similar issue. At least one person on the issue thread (https://github.com/PyCQA/pylint/issues/1161) indicates that it should work on an up-to-date version of PyLint.

See thread here: https://github.com/PyCQA/pylint/issues/1161
