### ISSUE TITLE
nosetests --where discovery not working

### ISSUE THREAD

**Issue by joshpeng** [DonJayamanne/pythonVSCode#499]
## Environment data
VS Code version:  1.7.1
Python Extension version:  0.5.1
Python Version:   2.7
OS and version:    Win10
Your settings.json:   
```json
"python.unitTest.nosetestsEnabled": true,
    "python.linting.pylintEnabled": true,
    "python.linting.flake8Enabled": false,
    "python.unitTest.nosetestArgs": [
        "--stop",
        "--where tests/"
    ],
```   

## Actual behavior
Can't find any tests I put in the /tests/ directory.
## Expected  behavior
It should be able to find the tests.

## Steps to reproduce:  
I've tried many different directory structures and the usage of [--where](http://nose.readthedocs.io/en/latest/usage.html?options#options) option, but they all don't work. However when I am in Command Prompt, they do execute my nosetests. For some reason the Python plugin can't find them though.

This structure = no tests found with or without ```--where tests/```
```
$tree
.
├── tests
    ├──__init__.py
    ├──test_one.py
__init__.py
one.py
```
Also no tests found for this structure with or without ```--where tests/```
```
$tree
.
├── tests
    ├──__init__.py
    ├──test_one.py
└── something
    ├── __init__.py
    ├── one.py
```
The only structure I was able to get the Python extension to find my nosetests without ```--where tests/``` is this flat structure:
```
$tree
.
__init__.py
test_one.py
one.py
```

Can you please provide some insights into how exactly the tests need to be arranged to get the Python to detect them? Thanks. No idea why the plugin can't find them, but I can execute the nosetests just fine from command prompt.

**Comment by joshpeng** [comment]
Dug around in the source code and noticed this in testConfigurationManager.ts

[Line 73](https://github.com/DonJayamanne/pythonVSCode/blob/master/src/client/unittests/common/testConfigurationManager.ts#L73)
You are matching for only a directory named "test". That would explain why all my attempts failed with the folder "tests". Perhaps this could be expanded to allow for either folder name or at least document it in the Wiki

[Line 69](https://github.com/DonJayamanne/pythonVSCode/blob/master/src/client/unittests/common/testConfigurationManager.ts#L69)
My understanding is that since you are running it off ```rootDir``` (I assume this is the project directory I've opened in VSCode), I won't be able to get any test folders detected if I don't open VSCode exactly to the correct depth of the modules. Can this be changed to be more flexible? Sometimes I open VSCode to a directory that is broader than where the exact tests would reside. For example I may have a projects directory that contains multiple different projects with their own individual test suites.

**Comment by DonJayamanne** [comment]
@joshpeng 
Please try the following:
- Remove the following settings:   
```json
"python.unitTest.nosetestsEnabled": true,
    "python.unitTest.nosetestArgs": [
        "--stop",
        "--where tests/"
    ],
```
- Next from the command palette select ```Python: Run All Unit Tests```   
- This will walk you through the configuration of the unit tests

Let me know if this works, it should.
In the mean time, I will fix the issue with the ```--where```

**Comment by DonJayamanne** [comment]
The problem is you have ```--where tests/``` in one setting, you need to split them up as they are separate values. See below:
```json
"python.unitTest.nosetestsEnabled": true,
    "python.unitTest.nosetestArgs": [
        "--stop",
        "--where", 
        "tests/"
    ],
```

**Comment by joshpeng** [comment]
@DonJayamanne Thank you for the quick response.
The suggestion you provided is working for this structure
```
$tree
.
└── tests
    ├──__init__.py
    ├──test_one.py
└── something
    ├── __init__.py
    ├── one.py
```
But this one still doesn't work
```
$tree
.
├── Folder1
├── Folder2
└── Python
    └── tests
        ├──__init__.py
        ├──test_one.py
    └── something
        ├── __init__.py
        ├── one.py
```
If the tests aren't in the root level I'm not sure how to tell the plugin to get to them.

**Comment by DonJayamanne** [comment]
Simple, use the following
"--where", "./Python/tests"

**Comment by joshpeng** [comment]
@DonJayamanne Okay. So that is a static way to do it, but seems to only work from one folder. I wasn't able to stack a bunch of ```--where``` to collect all my tests. Sorry if I wasn't clear earlier. I'm wondering if there is any way to just get this to somehow figure it out on its own?
```
$tree
.
├── Folder1
├── Folder2
├── PythonProject1
    ├── something
        ├── __init__.py
        └── one.py
    └── tests
        ├── __init__.py
        └── test_one.py
└── PythonProject2
    ├── otherthing
        ├── __init__.py
        └── two.py
    └── tests
        ├── __init__.py
        └── test_two.py
```
When I have ```one.py``` open and click "Run All Unit Tests", I'd like it to run it's test suite from its own subdirectory. Then when I am working on ```two.py```, triggering the unit tests to run the other test suite.
