### ISSUE TITLE
Question on the generated launch.json

### ISSUE THREAD

**Issue by Botong** [DonJayamanne/pythonVSCode#5]
Thanks for this great extension.
Quick question on the generated launch.json.
I want to add arguments before launching the program. Usually in the terminal I just do python -m pdb filename.py -arguments[], in vscode, how to add the arguments in the launch.json? I tried to add an args property and it is saying this property is not allowed, why is that?

**Comment by DonJayamanne** [comment]
Oops, will fix that in the next release. Please give me a day.
