### ISSUE TITLE
settings for jedi path.

### ISSUE THREAD

**Issue by Cologler** [DonJayamanne/pythonVSCode#500]
## Environment data

VS Code version: 1.7.1
Python Extension version: 0.5.0
Python Version: 3.5.1
OS and version: win 10 x64

## Actual behavior

After update pythonVSCode, replace old version jedi over and over again.

## Expected  behavior

a setting can set my jedi path.

**Comment by DonJayamanne** [comment]
@Cologler , FYI the latest version of the extension uses the latest version of Jedi 0.10.0 (master branch)

**Comment by Cologler** [comment]
@DonJayamanne But jedi still contains bugs. Today I create a pull request for it.

**Comment by DonJayamanne** [comment]
Fixed, you can set the path in ```settings.json``` as follows:
```json
"python.jediPath": "xxxxx"
```
Will be in the next release

**Comment by DonJayamanne** [comment]
New version released, with this fix

**Comment by Cologler** [comment]
thanks
