### ISSUE TITLE
Support for pylint ignored paths

### ISSUE THREAD

**Issue by patrick91** [DonJayamanne/pythonVSCode#501]
This is my .pylintrc
```
[MASTER]
ignore=tests
load-plugins=pylint_django

[TYPECHECK]
ignored-modules = responses
```

if I run pylint like this: `pylint backend/folder` it works fine, but if I run `pylint backend/folder/tests` I still get the file linted. Since the extension seem to run the pylint executable directly on the current file maybe it should read the pylintrc ignored paths.

**Comment by DonJayamanne** [comment]
@patrick91 
The linter will pickup the pylintrc. Please ensure it is configured properly. Do you have any other config files. Generally the pylint linter walks up from the file path looking for config files.

**Comment by patrick91** [comment]
@DonJayamanne what can I check? the python output looks ok, the console has not errors. 

Are you able to ignore specific folders using the pylintrc file?

**Comment by DonJayamanne** [comment]
@patrick91 
This is a problem with pylint.
If using pylint to lint a specific file, then the ignore section of the config file isn't respected (not working).
As you have already identified, running the linter as follows ```pylint backend/folder/tests``` results in the files getting linted.

I will add a new configuration setting that will allow you to configure what files and folders can be ignored.

**Comment by patrick91** [comment]
Thanks! Not sure if this is a feature or bug of pylint :)

**Comment by DonJayamanne** [comment]
@patrick91 
Added a new setting as follows:

```json
        "python.linting.ignorePatterns":  [
            ".vscode/*.py",
            "**/site-packages/**/*.py"
          ],
```

By default all files under the ```.vscode``` and ```site-packages``` directories will be excluded form the linter.

**Comment by patrick91** [comment]
Thanks!
