### ISSUE TITLE
Debug Toolbar invisible, Shortcuts for debugging not working

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#503]
_From @clepet on November 8, 2016 7:34_

- VSCode Version: 1.7.1
- OS Version: Kubuntu 16.04.1 LTS

Since I updated my VSCode to 1.7.1 yesterday my debugging process is kinda buggy. Everytime I run (not debug!, Ctrl+F5) my application, the application is run but I don't see the debug toolbar. Besides that I also can't use my debug hotkeys to start/stop the application. What's weird about this is that as soon as I type anything into my debug console the debug toolbar gets visible and the debug hotkeys get usable again. 
I'm working with Python, therefore I'm using [this](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python) extension.

Steps to Reproduce:

1. Run any Application. Default shortcut: Ctrl + F5

**UPDATE**

I tried to completely reinstall VSCode now, which didn't work unfortunately. I still had that bug.
After uninstalling VSCode 1.7.1 and reinstalling VSCode 1.6.1 it works again. So I am pretty sure it has to do something with the new Version 1.7.1.

_Copied from original issue: Microsoft/vscode#15147_

**Comment by DonJayamanne** [comment]
_From @isidorn on November 8, 2016 14:33_

This work fine for me - though I only tried it for node debugging. Does regular debugging work for you all the time?
Forwarding to @DonJayamanne since he owns the python extension and can check if things are working fine on his end.

**Comment by DonJayamanne** [comment]
@clepet 
Please could you try running a simple python program such as the following:
```python
print('1234')
```

**Comment by DonJayamanne** [comment]
@clepet 
Any progress on this?

**Comment by clepet** [comment]
Hey @DonJayamanne. Sorry that I'm replying so late.

**Comment by DonJayamanne** [comment]
No worries, take your time. 
You are the one facing the problems, not me :)
Let me know when you have some more info.

**Comment by clepet** [comment]
OK, I just tried it again. I was updating my current VS Code 1.6.1 with newest version of the python extension to VS Code 1.7.2 and it didn't work. After that I completely removed VS Code and installed VS Code 1.7.2 new. Still didn't work. 
Unfortunately I can't really wait for instructions with the buggy version 1.7.2 here at work. Is there a possibility to have two instances of VS Code installed on my computer? 1.6.1 and 1.7.2? That would be very nice.

**Comment by DonJayamanne** [comment]
@clepet 
You'd need to check this with the VS Code community, please raise an issue on their repo.
https://github.com/Microsoft/vscode/issues/new
