### ISSUE TITLE
Can't disable "No tests discovered" popup

### ISSUE THREAD

**Issue by joshpeng** [DonJayamanne/pythonVSCode#504]
## Environment data
VS Code version:  1.7.1
Python Extension version:  0.5.1

## Actual behavior
![untitled](https://cloud.githubusercontent.com/assets/22549127/20160865/1a8f4cf4-a69f-11e6-8916-73cc46aa2143.png)

## Expected  behavior
Even though I have unit tests enabled in my user settings doesn't mean I always have unit tests on all my projects. I don't want to need to configure these settings on a per workspace basis over and over again.

The use case is that despite being in the occasional/new project folder with no tests, I don't need to be asked on every VSCode start to config unit tests. Need an option to disable/"not show again" the popup. Thanks.

**Comment by DonJayamanne** [comment]
>I have unit tests enabled in my user settings

The settings in ```user settings``` is a global setting, hence applies to all workspaces. 
If you don't want this, then you need to turn it on individually in each workspace or vice versa. That's how ```user settings``` work.  

If you don't want unit tests for all workspaces, then you shouldn't be turning this on at the ```user settings``` level.

**Comment by joshpeng** [comment]
@DonJayamanne I do want it on the global level though. I just don't need it to tell me it isn't working on certain workspaces every single time I open VSCode.

I have tests on half of my workspaces. What you're saying is now I have to go through every single one and setup unit tests manually. In the previous version of this plugin it just "failed" gracefully and didn't nag me about missing tests. It would actually even work very nicely when tests were finally added, detecting them automatically with no extra work from me.

The way it is working now with your suggestion I would have to enable unit tests every single time I have a project that finally gets tests added or live with the nag toast. IMO this is a bit of an usability regression.
