### ISSUE TITLE
Jupyter notebook creates temporary kernel-*.json files in working directory

### ISSUE THREAD

**Issue by gandhis1** [DonJayamanne/pythonVSCode#506]
## Environment data
VS Code version:  18.0-Insider
Python Extension version:  0.5.1
Python Version:  3.5.2
OS and version: Windows 10   

## Actual behavior
Jupyter spits out a number of kernel.json files while contain code similar to the below. This crowds my main working directory with files I don't want to see. If you're using source control, this can become especially annoying.
```
{
  "iopub_port": 62703,
  "signature_scheme": "hmac-sha256",
  "stdin_port": 62704,
  "hb_port": 62706,
  "key": "81f6d215-18b4-48b1-b421-d1df7f142bbd",
  "ip": "127.0.0.1",
  "kernel_name": "",
  "transport": "tcp",
  "control_port": 62705,
  "shell_port": 62702
}
```
![image](https://cloud.githubusercontent.com/assets/21064086/20162965/b7055f98-a6c6-11e6-9ca6-b7e71cbefcb8.png)

## Expected  behavior
Any files needed should be written to a temporary directory, or extension-specific directory, not the current working directory.

## Steps to reproduce:  
-  Start up VSCode, enter a Python project.
-  Select some text, run it in Jupyter notebook.

**P.S. Another bug is that the pythonVSCode template for submitting a new issue has TWO sections for Actual behavior, instead of just one**

**Comment by rampage644** [comment]
@gandhis1 Those are jupyter kernel files which are deleted once kernel is stopped (Try to stop kernel manually from VS Code).
However, they're not deleted on Code exit and this seems to be the problem. You proposal is interesting but it don't address real issue.

**Comment by gandhis1** [comment]
I see. So it should delete those files, although writing those files to the working folder means that Git may inadvertently pick them up, which isn't ideal.

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/vscodeJupyter#17
