### ISSUE TITLE
Remote debugger - When stop on a breakpoint error: Source \Unknown Source is not available

### ISSUE THREAD

**Issue by hanbaobao2005** [DonJayamanne/pythonVSCode#507]
Refer to bug: https://github.com/DonJayamanne/pythonVSCode/issues/302
## Environment data
VS Code version:  1.7.1 (Both local and remote)
Python Extension version:  0.5.2 (Both local and remote)
Python Version:   Local: python3.5 x64; Remote Python3.4 x64
OS and version:    
Local: Win10
Remote: Win2008
Your launch.json (if dealing with debugger issues):  
[launch.zip](https://github.com/DonJayamanne/pythonVSCode/files/582450/launch.zip)

The real paht of "${workspaceRoot}" is D:/temp/Dropbox (NT)/Kevin Self/ST/uitestkz.py  

## Logs 
Output from ```Console window``` (Help->Developer Tools menu)
```
workbench.main.js:121 [Extension Host] Lintings failed on openI.logExtensionHostMessage @ workbench.main.js:121
workbench.main.js:121 [Extension Host] File: file:///d%3A/temp/Dropbox%20%28NT%29/Kevin%20Self/ST/uitestkz.pyI.logExtensionHostMessage @ workbench.main.js:121
workbench.main.js:121 [Extension Host] Message: TypeError: Cannot read property 'uri' of undefinedI.logExtensionHostMessage @ workbench.main.js:121
```

## Actual behavior
![image](https://cloud.githubusercontent.com/assets/1937472/20163356/dc5297fa-a736-11e6-950f-289c9d45c2c4.png)

## Expected  behavior
The code should be loaded.

**Comment by sfertman** [comment]
Same issue on Ubuntu 16.04 debugging a python test app in a docker container.
local: Ubuntu 16.04
remote: Fedora 24 (Docker)
VSCode: 1.7.2
Python extension: 0.5.5 (donjayamanne.python)

This is my `launch.js` attaching process part:
```
{
    "name": "Attach (Remote Debug)",
    "type": "python",
    "request": "attach",
    "localRoot": "${workspaceRoot}/mainprog",
    "remoteRoot": "$/var/app", // source files are definitely in that directory and accessible from inside the python program
    "port": ...,
    "secret": ...,
    "host": ...
}
```

**Comment by robomojo** [comment]
I was having this unknown source issue for a while on windows, but recently got it working by playing with the slashes in the remotePath string. (Compare yours with the path to the os module in the image)

Any slashes in the localPath happily use "/" or "\\", but I think remotePath really wants "\\", on windows at least.

So instead of:
`"remoteRoot": "c:/Users/Administrator/Desktop/QA_PyScript/"`
I would try:
`"remoteRoot": "C:\\Users\\Administrator\\Desktop\\QA_PyScript"`

**Comment by sfertman** [comment]
@robomojo, interesting. 

I changed my remote path to windows style (`"remoteRoot": "\\var\\app"`) and it worked, but the thing is, my remote is _Fedora_! 

Also debugger shows only source files that are in the root path, files in subdirectories still do not show.

**Comment by imaia** [comment]
This problem is affecting vscode 1.9.1
Was the error message more descriptive, it would be easier to try a workaround.

**Comment by DonJayamanne** [comment]
@hanbaobao2005 are you still experiencing this issue? Please reopen if you are.

**Comment by hanbaobao2005** [comment]
@DonJayamanne  Thanks for your reminder. Unfortunately, I run the debug with an error:
![image](https://user-images.githubusercontent.com/1937472/30514042-a1b54260-9b40-11e7-8dca-a12f79ddf06d.png)

which mentioned in https://github.com/PowerShell/vscode-powershell/issues/243
My VS version is
![image](https://user-images.githubusercontent.com/1937472/30514034-8d14b3b8-9b40-11e7-9149-bae700d6ccb8.png)

Python extension version: 0.7.0

I will run the test again tmr to see if can replicate it.
Thanks,
