### ISSUE TITLE
Read Jupyter Notebook files and display Notebook UI

### ISSUE THREAD

**Issue by cesarr** [DonJayamanne/pythonVSCode#512]
@DonJayamanne any plan to add the capacity to read and write Jupyter Notebook files and display the Notebook UI?

Thank you for this great extension to VS Code!

**Comment by DonJayamanne** [comment]
Perhaps, have been looking into that.

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/vscodeJupyter#16
