### ISSUE TITLE
Potential solution for autoimports

### ISSUE THREAD

**Issue by Immortalin** [DonJayamanne/pythonVSCode#513]
Autoimports is a feature request. Emacs does this with this --> https://github.com/jorgenschaefer/elpy  i.e. hook into importmagic

**Comment by gandhis1** [comment]
I'm not sure exactly what this means, but does it have anything to do with the type of thing I mention for PyLint below? If so, it could be useful for providing better linting and code completion. 

https://github.com/PyCQA/pylint/issues/1161

**Comment by JGH1000** [comment]
Added to feature request in https://github.com/DonJayamanne/pythonVSCode/issues/183

**Comment by DonJayamanne** [comment]
Closing in favor of https://github.com/Microsoft/vscode-python/issues/21
