### ISSUE TITLE
When set "python.terminal.executeInFileDir":true,the terminal return error

### ISSUE THREAD

**Issue by MightyWing** [DonJayamanne/pythonVSCode#514]
## Environment data
VS Code version:  1.7.1
Python Extension version:  
Python Version:   2.7
OS and version:  ubuntu 16.04 and win 10 all test
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
{
"python.terminal.executeInFileDir":true
}
## Logs
Output from ```Python``` output panel  
cd "home/mighty/PycharmProjects/myproject"
bash: cd: home/mighty/PycharmProjects/myproject: 没有那个文件或目录

Output from ```Console window``` (Help->Developer Tools menu)
```
```

## Steps to reproduce:  
-  
-

**Comment by DonJayamanne** [comment]
What's the error?

**Comment by MightyWing** [comment]
cd "home/mighty/PycharmProjects/myproject"
bash: cd: home/mighty/PycharmProjects/myproject: 没有那个文件或目录
in english is  not that file or dir.

**Comment by guhuajun** [comment]
I can reproduce this issue in windows 10. It looks like driver name (windows) and '/' (linux) is missing.

(env) C:\codingnet\elkdashboard
cd "**<missing>**:\codingnet\elkdashboard"
文件名、目录名或卷标语法不正确。
