### ISSUE TITLE
Single python file cannot import library

### ISSUE THREAD

**Issue by leeyongda** [DonJayamanne/pythonVSCode#515]
**Single python file cannot import library**
OS Version: Windows10
Python Version: 2.7.11
VSCode Version: 1.7.1

example:
This problem is only a single py file cannot import library.

![01](https://cloud.githubusercontent.com/assets/11832476/20237851/d00d134c-a918-11e6-9772-8a061eb8c4d3.jpg)

**Comment by DonJayamanne** [comment]
Please could you provide more information of the problem.
Sample file, what are you importing, error displayed, what is the expected behaviour, etc?

**Comment by leeyongda** [comment]
@DonJayamanne 
Single python file cannot import library
OS Version: Windows10
Python Version: 2.7.11
VSCode Version: 1.7.1

example:
This problem is only a single py file cannot autoimport library.
![01](https://cloud.githubusercontent.com/assets/11832476/20238003/5058f3b0-a91c-11e6-883e-118345163290.jpg)

**Comment by DonJayamanne** [comment]
Does this work if you have two py files in the directory?

**Comment by DonJayamanne** [comment]
What are the contents of your ```settings.json```?
Is python in your current path? (open terminal window and type the command ```python``` check if this works).

**Comment by leeyongda** [comment]
@DonJayamanne 
Yes, py files in the directory under normal working,
But a single py file, can not work(autoimport).

**Comment by DonJayamanne** [comment]
What are the contents of your settings.json?
Is python in your current path? (open terminal window and type the command python check if this works).

**Comment by leeyongda** [comment]
@DonJayamanne 
This problem is only a single py file on the windows 10 dekstop  open with vscode  cannot import library.
Other paths, No problem, normal working.

**Comment by DonJayamanne** [comment]
Duplicate issue
