### ISSUE TITLE
Vote to get VS Code and this extension added to awesome-python!

### ISSUE THREAD

**Issue by rogersachan** [DonJayamanne/pythonVSCode#516]
In order to get ourselves listed on this repo, which has over 26K stars, is that we need 20 upvotes in this PR to get it added.

PR is here: vinta/awesome-python#772

**Comment by DonJayamanne** [comment]
Would appreciate your help here guys.
Please vote on this PR if possible: vinta/awesome-python#772

@LRPalacios , @Avrong , @nnfdiogosilva, @bufke , @mmclark, @wengole, @abdelouahabb, @davehamby, @IornL, @ysfjwd , @deronnax, @LRPalacios , @goowell, @vstoykov, @thekorn, @i5on9i , @imaia, @MightyWing, @akras-apixio , @XianwuLin , @lzantal , @vanflymen , @coladou , @holyoaks, @adambrenecki, @evakili , @Botong

**Comment by rogersachan** [comment]
That was faster than I thought, thanks everyone!

**Comment by abdelouahabb** [comment]
Voted :dancer:
