### ISSUE TITLE
is there a launch configuration for modules

### ISSUE THREAD

**Issue by asquare** [DonJayamanne/pythonVSCode#518]
Great extension - the debugger works great for regular python scripts. But when trying to step into a user module under development, the -m flag is not respected. Seems like there should be a launch configuration for modules? Could'nt find any in the documentation. Thanks

## Environment data
VS Code version:  1.7.1
Python Extension version:  0.3.22
Python Version:   3.5.2
OS and version:    macOS Sierra 10.12.1
Your launch.json (if dealing with debugger issues):  
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Integrated Terminal",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "console": "integratedTerminal",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ],
            "args": [
                "-m",
                "<module>"
            ]
        }
    ]
}
```   
Your settings.json:   
```json
{
    "python.pythonPath": "/usr/local/bin/python3",
    "python.linting.enabled": false
}
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

## Steps to reproduce:  
-  create an empty module
-  try to debug the module
- the generated launch command-line seems to not respect the -m flag

**Comment by DonJayamanne** [comment]
This should be easy, will work in this next.

**Comment by DonJayamanne** [comment]
Oh yes, the answer to your question is no, this feature isn't supported today.

**Comment by DonJayamanne** [comment]
Completed, will be in the next release:
```json
        {
            "name": "Python Module",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "module": "myMod.foo.bar.baz",
            "cwd": "${workspaceRoot}",
            "args": [
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
```

Added the new setting ```module``` . This is where you would provide the name of the module to be debugged.
As there's no file name you'll need to ensure the setting ```cwd``` is provided. In the above sample it is configured to point to the workspace root.

**Comment by starprank** [comment]
This does not appear to be working for me.
in launch.json
`        {
            "name": "Python Module",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "module": "test.hello",
            "cwd": "${workspaceRoot}",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
`

directory tree:
-- .vscode
----launch.json
----settings.json
--test
----__init__.py
----hello.py
--__init__.py

I get the following error - "TypeError: Path must be a string. Received undefined"

Version 0.5.6

Assistance greatly appreciated

**Comment by nicolajkirchhof** [comment]
As a quick workaround, try to add `"program": ""` to your launch.json. That worked for me.

**Comment by DonJayamanne** [comment]
Ooops, fixed, please wait for the next release.
