### ISSUE TITLE
vscode python debuging stop on first import and when exceptions exist even if not breackpoint

### ISSUE THREAD

**Issue by efirvida** [DonJayamanne/pythonVSCode#519]
## Environment data
VS Code version:  1.7.1
Python Extension version:  5.1
Python Version:   2.7.12
OS and version:    Win 10 x64
Your launch.json (if dealing with debugger issues):  
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${file}",
            "pythonPath": "${config.python.pythonPath}",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }
    ]
}
```   
Your settings.json:   
```json
{
    "python.pythonPath": "C:/Python27/python.exe"
}
```   
## Actual behavior
test.py file
```python
import sys
import os
print(sys.version)

try:
    os.mkdir('asdf')  # exception when asdf folder exist
except (os.error) as err:
    print err

print(sys.executable)  # <-- break point
```   
debuguer stop on `import sys` then when continue stop on the `os.mkdir` if exeption exist then stop on the brackpoint

## Expected  behavior
debuguer stop only on the breakpoint

**Comment by DonJayamanne** [comment]
Please change the battle of the setting ```stopOnEntry": true,``` to ```false```

**Comment by gandhis1** [comment]
The counter-intuitiveness of this is why I opened PR #508.

**Comment by efirvida** [comment]
thanks! but still stoping on exeption,

**Comment by DonJayamanne** [comment]
Oh sorry, I didn't read the issue carefully.
The debugger will break on all exceptions. 
If you want to control the behaviour of breaking on exceptions then you have the following options:
- Bottom left of the debugger panel, you will find two checkboxes:
    + [x] All Exceptions
    + [x] Uncaught Exceptions
- You also control what exceptions need to be ignored by the debugger. 
```json
            "debugOptions": [
                "WaitOnAbnormalExit", "WaitOnNormalExit", "RedirectOutput"
            ],
            "exceptionHandling": {
                "always": [
                        // Quoted and Comma delimited list of exception types for which the debugger MUST always break
                ]
                ,"ignore": [
                        // Quoted and Comma delimited list of exception types to be ignored by the debugger                    
                ],
                "unhandled": [
                        // Quoted and Comma delimited list of exception types for which the debugger MUST always break even if the exception is handled in user code
                ]
            }
```

**Comment by efirvida** [comment]
thnkas a lot!

**Comment by JeffHanna** [comment]
Is it possible to configure the exceptionHandling setting to ignore certain types of exceptions but only at certain locations? If I have the Uncaught Exceptions checkbox enabled wxPython 4.x will always break in core._Size___get_item__( ) with an IndexError. I don't want to ignore all IndexError exceptions, but with wx.Size being called a lot by wxPython I can't reasonably debug my code when it constantly halts in wx.Size( ).
