### ISSUE TITLE
No tests discovered

### ISSUE THREAD

**Issue by feinstruktur** [DonJayamanne/pythonVSCode#520]
## Environment data
VS Code version:  1.7.1
Python Extension version:  0.5.2
Python Version:   3.5.2
OS and version:    macOS 10.12

Your settings.json:   
```json
// Place your settings in this file to overwrite the default settings
{
    "editor.fontFamily": "SF Mono, monospace",
    "editor.fontSize": 10.5,
    "editor.wrappingColumn": 0,
    "editor.wrappingIndent": "indent",
    "editor.renderLineHighlight": false,
    "python.linting.enabled": true,
    "python.linting.pylintEnabled": false,
    "python.linting.flake8Enabled": true,
    "python.unitTest.unittestEnabled": true,
    "python.unitTest.nosetestsEnabled": true
}
```   

Worspace settings.json:
```
{
    "python.pythonPath": "/Users/sas/.pyenv/versions/vme3/bin/python”
}
```

`vme3` is a Python 3.5.2 virtualenv with nose-1.3.7 installed (among other packages).

## Actual behavior

My project consists of a single python file with a bare bones unit test:

```
import unittest
import logging
logging.disable(logging.INFO)


class Foo(unittest.TestCase):

    def test_foo(self):
        self.assertEqual(2, 1 + 1)
```

Upon opening the project, a banner is displayed stating:

```
No tests discovered, please check the configuration settings for the tests.
```

The only way to make the test discoverable it to comment out or remove the two `logging` lines:

```
import unittest
# import logging
# logging.disable(logging.INFO)


class Foo(unittest.TestCase):

    def test_foo(self):
        self.assertEqual(2, 1 + 1)
```

## Expected  behavior

I expected the unit test to be discovered even with those lines enabled. This is a trimmed down file of a larger project where these lines disable discovery of all tests.

Note that “Run all tests” does still run all tests but it is not possible to run individual tests.

## Steps to reproduce:  

-  create folder with test file `test_foo.py` in it
-  open project
- observe error

**Comment by DonJayamanne** [comment]
What framework are you using too run the tests? Python Unittest or nose?

**Comment by feinstruktur** [comment]
This is running with nose. I’ve actually had both enabled as part of my effort to debug but this. But even if I just use

```
    "python.unitTest.nosetestsEnabled": true
```

the results are the same.

**Comment by feinstruktur** [comment]
However, I just noticed that if I try with just

```
    "python.unitTest.unittestEnabled": true,
```

the tests are discovered correctly.

**Comment by DonJayamanne** [comment]
@feinstruktur 
Identified the bug, with nosetests, the current code is expecting the tests to be located in a sub directory (e.g. sub directory named ```tests```).

Will work on the fix in the mean time.

**Comment by DonJayamanne** [comment]
@feinstruktur 
Further to the issue, the following block of code does interfere with the discovery of tests when using ```nose```:  
```python
import logging
logging.disable(logging.INFO)
```

**Comment by DonJayamanne** [comment]
Good news, I have found a work around, however this still take a few days, already started on the work.

**Comment by feinstruktur** [comment]
Actually - related but slightly off-topic - is it possible to turn off the ‘Test’ links that appear in the unit test files and allow you to run individual tests? I actually ended up keeping the offending `logging` statements in as such a switch, because these links make the lines jitter up and down when editing a test file.

**Comment by DonJayamanne** [comment]
Hmmm, sure thing. Will make that feature optional.

**Comment by DonJayamanne** [comment]
Please could you add a separate issue for that, lest I forget

**Comment by DonJayamanne** [comment]
>Good news, I have found a work around, however this still take a few days, already started on the work.

Sorry @feinstruktur , the work around doesn't work :(
Will try to find another solution.

**Comment by DonJayamanne** [comment]
@feinstruktur 
The best i can do is to still allow you to run the tests. 
It will run the tests, display the results with the ability to run failed tests.
But you won't be able to run a specific test suite or test method.

Right now the code assumes that there are no tests, just because it was unable to discover them. When in fact there are some tests.

**Comment by feinstruktur** [comment]
No worries, thanks a lot for your efforts and the update! I’ve had a look into a bug report for the jittering issue but found that it doesn’t happen in the minimal test project I set up. I’ll raise it again if/when I can test it in the larger project where I first saw it.

**Comment by DonJayamanne** [comment]
@feinstruktur 
made the necessary changes to allow you to at least run the tests.
