### ISSUE TITLE
Resolve not to import library. Thank you very much @DonJayamanne

### ISSUE THREAD

**Issue by leeyongda** [DonJayamanne/pythonVSCode#521]
OS Version: Windows10
Python Version: 2.7.11
VSCode Version: 1.7.1
## **issues:**
![error](https://cloud.githubusercontent.com/assets/11832476/20253931/a1fdbad0-aa6a-11e6-9c84-ef9c43ee188e.jpg)

##  **So, I Should add code in completion.py . Already solve the problem .**
![02](https://cloud.githubusercontent.com/assets/11832476/20254035/b0f2e88e-aa6b-11e6-90e9-477436b08119.jpg)

**Comment by DonJayamanne** [comment]
Isn't this the same as #515?

**Comment by DonJayamanne** [comment]
What version of the python extension are you using?

**Comment by leeyongda** [comment]
## python extension : 0.5.2 (Latest version)
There are some problems.
example:(I want to delete some code.)
## Error:
![03](https://cloud.githubusercontent.com/assets/11832476/20254771/58bb88fe-aa72-11e6-85f9-4b3bc8f73c7d.jpg)

**Comment by DonJayamanne** [comment]
>>example:(I want to delete some code.)

Sorry, but that doesn't make much sense to me. Please could you be more specific.

**Comment by DonJayamanne** [comment]
Please could you report these errors in the Jedi repo, these are specific to the Jedi library version 0.10.0:
https://github.com/davidhalter/jedi/issues/new

**Comment by leeyongda** [comment]
**Thank you !**

**Comment by DonJayamanne** [comment]
@leeyongda 
Thanks for assisting in narrowing down the issue to the library.
