### ISSUE TITLE
workspaceRootFolderName didn't work in pythonPath

### ISSUE THREAD

**Issue by skilliscode** [DonJayamanne/pythonVSCode#522]
## Environment data
VS Code version:  1.7.1
Python Extension version:  0.5.2
Python Version:   3.5.2
OS and version:    macOS 10.12.1

Your settings.json:   
    "python.pythonPath": "/Users/myname/.virtualenvs/${workspaceRootFolderName}/bin/python"

## Actual behavior
/Users/myname/.virtualenvs//bin/python
## Expected  behavior
/Users/myname/.virtualenvs/workspacefoldername/bin/python

**Comment by DonJayamanne** [comment]
Closed with PR https://github.com/DonJayamanne/pythonVSCode/pull/525
