### ISSUE TITLE
Intellisense and Autocomplete not working

### ISSUE THREAD

**Issue by alfadil94** [DonJayamanne/pythonVSCode#523]
## Environment data
VS Code version:  
Python Extension version:  
Python Version:   2.7
OS and version:    ubuntu 16
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

## Actual behavior
Ability to include custom module paths not working
## Expected  behavior
to work
## Steps to reproduce:  
-  
-

**Comment by DonJayamanne** [comment]
What's the out put from the console window?
> Output from Console window (Help->Developer Tools menu)

**Comment by alfadil94** [comment]
Nothing

Sent from my iPhone

On Nov 15, 2016, at 12:46 PM, Don Jayamanne <notifications@github.com<mailto:notifications@github.com>> wrote:


What's the out put from the console window?

Output from Console window (Help->Developer Tools menu)

-

**Comment by alfadil94** [comment]
nothing

**Comment by DonJayamanne** [comment]
That can't be, there may be some error. 
Please upload your settings.json and the sample code used to check if intellisense works or not.

Finally is python in your path?

**Comment by alfadil94** [comment]
my settings
// Place your settings in this file to overwrite the default settings
{"files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.DS_Store": true,
        "**/*.pyc": true
    },
    "python.autoComplete.extraPaths": ["/home/user/odoo-7.0/openerp"]}
//////////////////////////////////////////////
and yah  I have python2.7 in my pc

**Comment by alfadil94** [comment]
i just imported openerp module in my code but nothing works

**Comment by DonJayamanne** [comment]
Can you open a terminal window (in Visual Studio Code) and type the command ```python``` and let me know what the output is.

**Comment by alfadil94** [comment]
Python 2.7.12 (default, Jul  1 2016, 15:12:24)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by DonJayamanne** [comment]
Please check this: 
>Can you import os and check if you get code completion for os
```
import os
os. #<- Here you get auto completion after typing the character '.'
```

**Comment by alfadil94** [comment]
it works fine

**Comment by DonJayamanne** [comment]
Ok, so intellisense does work, its just that it doesn't work for your library.
Please ensure you provide the full information next time with some code sample.

**Comment by alfadil94** [comment]
thanks for your time

**Comment by DonJayamanne** [comment]
Change the path to:
```json  
"python.autoComplete.extraPaths": ["/home/user/odoo-7.0"]}
```

This should work because, the named folder needs to exist in the python path for python to import the module (module name is ```openerp``` hence the parent directory containing this module needs to be in the path)

**Comment by DonJayamanne** [comment]
Let me know if that fixes it.

**Comment by alfadil94** [comment]
yah it works very well now thanks a lot
