### ISSUE TITLE
pyTest can't import module locates in the root of project folder

### ISSUE THREAD

**Issue by Mr-Binary** [DonJayamanne/pythonVSCode#527]
## Environment data
VS Code version:  lastest
Python Extension version:  lastest
Python Version:   3.5.2
OS and version:    OS X 10.12.1

Your settings.json:   
```json
// Place your settings in this file to overwrite default and user settings.
{
    "python.unitTest.pyTestEnabled": true,
    "python.unitTest.unittestEnabled": false,
    "python.unitTest.nosetestsEnabled": false,
    "python.unitTest.pyTestArgs": [
        "--exitfirst",
        "--verbose"
    ]
}
```   

## Logs
```bash
__________There was an error in identifying unit tests in tests/data_store_tests/test_dataStore.py__________
__________ ERROR collecting tests/data_store_tests/test_dataStore.py ___________
../../../.pyenv/versions/3.5.2/lib/python3.5/site-packages/kivy/__init__.py:325: in <module>
__________There was an error in identifying unit tests in 'debug',__________
    'config=', 'debug', 'dpi='])
../../../.pyenv/versions/3.5.2/lib/python3.5/getopt.py:93: in getopt
__________There was an error in identifying unit tests in = do_longs(opts, args[0][2:], longopts,__________
    opts, args = do_longs(opts, args[0][2:], longopts, args[1:])
../../../.pyenv/versions/3.5.2/lib/python3.5/getopt.py:157: in do_longs
__________There was an error in identifying unit tests in t = long_has_args(opt,__________
    has_arg, opt = long_has_args(opt, longopts)
../../../.pyenv/versions/3.5.2/lib/python3.5/getopt.py:174: in long_has_args
    raise GetoptError(_('option --%s not recognized') % opt, opt)
E   getopt.GetoptError: option --cache-clear not recognized
During handling of the above exception, another exception occurred:
tests/data_store_tests/test_dataStore.py:10: in <module>
    from moblib.datalib import jsParse
../moblib/moblib/__init__.py:4: in <module>
    from moblib import guilib
../moblib/moblib/guilib.py:5: in <module>
    from kivy.uix.widget import Widget
../../../.pyenv/versions/3.5.2/lib/python3.5/site-packages/kivy/__init__.py:330: in <module>
    sys.exit(2)
E   SystemExit: 2
------------------------------- Captured stdout --------------------------------
Kivy Usage: py.test [OPTION...]::
        -h, --help
            Prints this help message.
        -d, --debug
            Shows debug log.
        -a, --auto-fullscreen
            Force 'auto' fullscreen mode (no resolution change).
            Uses your display's resolution. This is most likely what you want.
        -c, --config section:key[:value]
__________There was an error in identifying unit tests in a custom [section] key=value in the configuration__________
            Set a custom [section] key=value in the configuration object.
        -f, --fullscreen
            Force running in fullscreen mode.
        -k, --fake-fullscreen
            Force 'fake' fullscreen mode (no window border/decoration).
            Uses the resolution specified by width and height in your config.
        -w, --windowed
            Force running in a window.
        -p, --provider id:provider[,options]
            Add an input provider (eg: ccvtable1:tuio,192.168.0.1:3333).
__________There was an error in identifying unit tests in __________
        -m mod, --module=mod
            Activate a module (use "list" to get a list of available modules).
        -r, --rotation
            Rotate the window's contents (0, 90, 180, 270).
        -s, --save
            Save current Kivy configuration.
__________There was an error in identifying unit tests in __________
        --size=640x480
            Size of window geometry.
__________There was an error in identifying unit tests in __________
        --dpi=96
            Manually overload the Window DPI (for testing only.)
------------------------------- Captured stderr --------------------------------
[INFO              ] [Logger      ] Record log in /Users/albertgao/.kivy/logs/kivy_16-11-17_1.txt
[ERROR             ] [Core        ] option --cache-clear not recognized
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
```   

## Actual behavior
I click the test button on the buttom of the screen, which currently showed me "No Tests", after clicking it, gives me error and along with these 2 notifications:
- INFO: No tests discovered, please check the configuration settings for the tests.
- ERROR: There were some errors in disovering unit tests
The error message is above.

## Expected  behavior
Running the test

## A little more detail:  
-  the module 'config' locates at the root of the project folder
- Tests cases sit in the tests/xxx_tests/test_xxx.py
-  When I run via bash, I can use "python -m pytest tests/", no errors
- I tried to add "tests/" as a user setting, doesn't work
- I don't import kivy in my tests, I only import moblib.guilib, which imports kivy
- Kivy is a python framework which provides a command that you can use like "kivy -m hello.py"
- I checked my debugging setting, I used "pythonPath": "${config.python.pythonPath}" for every entry. So it shouldn't fire kivy at the stage

What happened after I click that button?
How to solve it? Thanks

**Comment by DonJayamanne** [comment]
1. Are you able to run the tests from the terminal window? (Without using vs code), I.e does pytest work with your tests?

2. If above works, please send the command line used.

3. What version of pytest do you have installed?

4. Would it be possible to put together a very simple python app with test files that could be used too replicate this. Our is it something I can find on a public repo?

Thanks, will look into this today.

**Comment by Mr-Binary** [comment]
Thanks for the fast reply.

1. Yes, I can run pytest from terminal successfully:

2. The commands list as follow:
- pytest
- pytest tests/
- python -m pytest
- python -m pytest tests/

3. Currently latest release: 3.0.4

4. I create a new one it works:
- Create a new folder named 'python'
- Create a file called 'play.py' in the root, add a function add(a, b)
- Put the settings.json with the same default values as above to the '.vscode'
- Create tests folder: python/tests/test_play/
- Create test file: python/tests/test_play/test_play.py

```python
import sys
sys.path.insert(0, "/Users/albertgao/Codes/python/")

from play import add

class TestPlay:
    def test_add(self):
        assert add(1, 1) == 2
```

It works now. But still can't get it work for the original one, seems something wrong with my projects, but could I know what happened after clicking that button?

**Comment by DonJayamanne** [comment]
@Mr-Binary 
So let me get this right, its working for the sample code but not for your project.
Is it possible to provide the code to that? You could email it to me if possible.

**Comment by Mr-Binary** [comment]
Thanks so much, already sent. :) Keen for getting it work via VSC :)

**Comment by DonJayamanne** [comment]
@Mr-Binary , received your email, will look into this shortly.

**Comment by DonJayamanne** [comment]
@Mr-Binary 
Please try renaming the two test files in the tests directory to something as follows:
```
test_configs1.py  
test_main1.py  
```

The problem with those names for some reason are conflicting with the search process used by py.test (when collecting tests).

**Comment by Mr-Binary** [comment]
Thanks Don, I renamed the files as you said. but still doesn't work :( No Tests as well.

**Comment by DonJayamanne** [comment]
please could you type the following into terminal window and let me know what you get:
```
py.test tests --collect-only
```

**Comment by DonJayamanne** [comment]
It worked for me.

**Comment by Mr-Binary** [comment]
```bash
Alberts-MacBook-Pro:handset albertgao$ pytest tests --collect-only
============================= test session starts ==============================
platform darwin -- Python 3.5.2, pytest-3.0.4, py-1.4.31, pluggy-0.4.0
rootdir: /Users/albertgao/Codes/work/handset, inifile: pytest.ini
collected 3 items 
<Module 'tests/test_configs1.py'>
  <Class 'TestSaltConfig'>
    <Instance '()'>
      <Function 'test_check_phone_number_on_first_contact[404]'>
      <Function 'test_check_phone_number_on_first_contact[500]'>
<Module 'tests/test_main1.py'>
  <Class 'TestDataStore'>
    <Instance '()'>
      <Function 'test_data_store_fname_missing'>

========================= no tests ran in 0.01 seconds =========================
Alberts-MacBook-Pro:handset albertgao$ 
```

I tried to reboot the vsc, doesn't help :(

**Comment by DonJayamanne** [comment]
O.j., Please try changing your settings.json as follows:. 
```json
{
    "python.unitTest.pyTestEnabled": true,
    "python.unitTest.unittestEnabled": false,
    "python.unitTest.nosetestsEnabled": false,
    "python.unitTest.pyTestArgs": [
        "tests"
    ]
}
```

If that works try the following:. 
```json 
// Place your settings in this file to overwrite default and user settings.
{
    "python.unitTest.pyTestEnabled": true,
    "python.unitTest.unittestEnabled": false,
    "python.unitTest.nosetestsEnabled": false,
    "python.unitTest.pyTestArgs": [
        "--exitfirst",
        "--verbose",
        "tests"
    ]
}
```

**Comment by Mr-Binary** [comment]
Thanks so much, works like a charm now, with the first one.
When I modified it back, doesn't work, it can find the tests now. But it continued "Running Tests". I checked the terminal, seems Kivy tried to run itself at the front. But no problem at all, now I can enjoy the productivity gaining from the tool chain. Thanks so much!

I think for the other people who has this same issue, this sort of replace and replace-back method will solve the problem.

A more detail here:
If I leave VSC opend the settings.json, then close it.
When I opened it back again, it will still maintain the current file open which is still settings,json.
But the bottom testing-icon is missing.
When I switch to another file, it will show and check the tests again.
Maybe it's the intention here to close the tests-icon when user tries to modify the settings, if not, hope this detail could help.

Anyway, thanks!

Thanks for your work! Very rapid and effective!

**Comment by Mr-Binary** [comment]
It can even show my fixture which output different objects to the same test function as separate tests! Awesome job!

**Comment by DonJayamanne** [comment]
@Mr-Binary , thanks . Will try to fine tune the product.

**Comment by mike-pt** [comment]
Not sure if related but if I try to use args with "--" instead of "-" they all fail from python debugger with "getopt.GetoptError"

`option --st 10 not recognized`
`option --section sectionExample not recognized`

Could the real issue here be with using "--" ? 

this all works from the console just fine
