### ISSUE TITLE
Debugger stops for uncaught exception on import (direct or indirect) of xml.etree.cElementTree

### ISSUE THREAD

**Issue by dylan-bourque** [DonJayamanne/pythonVSCode#53]
Environment summary:
* Linux CentOS 7
* Python 2.7
* Visual Studio Code (v0.10.10)
* Python VSCode Extension (v0.3.1)

When launching the debugger, the application stops on an uncaught exception.  The error message reported to the console is `copy.Error, un(shallow)copyable object of type <type 'Element'>`.  I'm able to continue the debugging session by hitting the F5 key.

I noticed this behavior while trying to debug code that uses the AWS Boto3 library, but was able to reproduce it with nothing but the following:
```python
#!/usr/bin/env python
import xml.etree.cElementTree
```

This appears to be very similar to [this issue](http://pytools.codeplex.com/workitem/2077) for the Python Tools for Visual Studio.

**Comment by DonJayamanne** [comment]
Will be checking this out next week

**Comment by DonJayamanne** [comment]
Sorry for the delay. This has been fixed in the latest build.
You will need to configure the launch.json file to ignore such exception types.
Here's a sample configuration entry that you need to add into the "configurations" setting of launch.json

```json
            "exceptionHandling":{
                "ignore": ["copy.Error"]
            } 
```

**Comment by dylan-bourque** [comment]
Thanks for the update.  I installed the latest version of the extension
today and tested it.  Worked like a charm.

**Comment by DonJayamanne** [comment]
Excellent

**Comment by afdevries** [comment]
Hi @DonJayamanne I have the same issue as stated in this ticket. I can replicate this using only the import.xml.cElementTree statement.

OS X El Capitan 10.11.4
Python 2.7.10
Visual Studio Code 1.1.1
Python VSCode Extension 0.3.9

Tried to suppress the error using your suggestion to configure an ignore, but it still comes up.

` 
 "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${workspaceRoot}/malmberg/interval/interval_upload.py",
            "exceptionHandling": {
                "ignore": ["copy.Error"]
            },
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }
`

Thanks for your time!

**Comment by DonJayamanne** [comment]
Hi, i've tested this in the same environment and it works as expected.

**Comment by rajasimon** [comment]
Please update the "Debugging: Flask" wiki documentation.

**Comment by arasub** [comment]
Does this works with Python 2.7? still i have the same error. 

> copy.Error, un(shallow)copyable object of type <type 'Element'>

do we need to update to 3?
