### ISSUE TITLE
CV2 issues when installed with anaconda

### ISSUE THREAD

**Issue by srinath29** [DonJayamanne/pythonVSCode#530]
## Environment data
VS Code version:  1.7.1
Python Extension version:  0.5.2
Python Version:   3.5.2
OS and version:    windows 7
## Logs
Output from ```Python``` output panel  
```
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  5 2016, 11:41:13
1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```   

## Actual behavior
I am using Anaconda from continuum analytic. To install openCV3  I have used
```
conda install -c menpo opencv3=3.1.0
```
Now when I am importing cv2 and using any internal method like cv2.imread(''C.TIF"), I am getting red lines saying cv2 doesn't have imread method. It is same for all methods within cv2.

all extension settings are set to default. 
Python interpreter path is in my environment.

**Comment by DonJayamanne** [comment]
What liner is displaying this message?

**Comment by srinath29** [comment]
![capture](https://cloud.githubusercontent.com/assets/10499766/20390103/35f77ea8-acf3-11e6-8b5b-697ace414635.PNG)
I am attaching the image of the sample code. 
I have enabled your extension.

**Comment by DonJayamanne** [comment]
These are  issues reported by a liner. Have a look at the diagnostic messages.

**Comment by DonJayamanne** [comment]
@srinath29 
The linter for some reason is reporting this error message, not sure if its a problem with the linter or something else, either way the error is reported by the linter. 

You'll want to check why the linter is returning this message.
