### ISSUE TITLE
Autocompletion broken in 0.5.2

### ISSUE THREAD

**Issue by mrhockeymonkey** [DonJayamanne/pythonVSCode#531]
## Environment data
VS Code version:  1.7.1
Python Extension version:  0.5.2
Python Version:   3.5.2
OS and version:    Windows 10

Your  user settings.json:   
```json
// Place your settings in this file to overwrite the default settings
{
    "editor.tabCompletion": true,

    "editor.insertSpaces": false,

    "editor.autoClosingBrackets": false,

    "editor.acceptSuggestionOnEnter": false,

    "editor.renderWhitespace": "boundary"
}
```   

Your workspace settings.json:
```
// Place your settings in this file to overwrite default and user settings.
{
	"python.linting.pylintEnabled": false
}
```

## Logs
Output from ```Console window``` (Help->Developer Tools menu)
```
[Extension Host] Error (stderr) Traceback (most recent call last):
  File "completion.py", line 404, in watch
    self._process_request(self._input.readline())
  File "completion.py", line 395, in _process_request
    request.get('prefix', '')))
  File "completion.py", line 149, in _serialize_completions
    for signature, name, value in self._get_call_signatures(script):
  File "completion.py", line 73, in _get_call_signatures
    call_signatures = script.call_signatures()
  File "preview\jedi\api\__init__.py", line 301, in call_signatures
    helpers.get_call_signature_details(self._get_module(), self._pos)
  File "preview\jedi\api\helpers.py", line 274, in get_call_signature_details
    node = leaf.parent
AttributeError: 'NoneType' object has no attribute 'parent'

```

## Actual behavior
when typing no auto-complete appears. If i force it by hitting ctrl + space the i only get "loading...". I have tried uninstalling the extension and re installing. This actually work but on restarting VSCode it has since broken again. 

similar to below issue but different erorrs in the console window. any help or advice appreciated. 

https://github.com/DonJayamanne/pythonVSCode/issues/415

**Comment by DonJayamanne** [comment]
@mrhockeymonkey 
Please could you try adding the following setting into your ```settings.json``` file and let me know how it goes:  
```json
    "python.devOptions":[
        "USERELEASEAUTOCOMP"
    ]
```

**Comment by mrhockeymonkey** [comment]
@DonJayamanne 

I did a full uninstall and reinstall of both VSCode and the extention. Autocomplete seems to be better now for most things. however there are still a few cases. here is another log for when i hit ctrl + space whilst inside a bracket, in this case for a tkinter frame

```
Extension Host] Error (stderr) Traceback (most recent call last):
  File "preview\jedi\api\classes.py", line 751, in full
    return self._name.doc
AttributeError: 'ExprStmt' object has no attribute 'doc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "completion.py", line 404, in watch
    self._process_request(self._input.readline())
  File "completion.py", line 395, in _process_request
    request.get('prefix', '')))
  File "completion.py", line 180, in _serialize_completions
    description = completion.docstring()
  File "preview\jedi\api\classes.py", line 486, in docstring
    return _Help(definition).full()
  File "preview\jedi\api\classes.py", line 753, in full
    return self.raw()
  File "preview\jedi\api\classes.py", line 762, in raw
    return self._name.raw_doc
  File "preview\jedi\parser\tree.py", line 81, in raw_doc
    index = c.index(simple_stmt)
ValueError: Node(simple_stmt, [<ExprStmt: #define and configure the frame
 	pd_frame = ttk.Frame(pd_window)@139,1>, <Newline: '\r\n'>]) is not in list
```

that is with the added setting you suggested above. I'm happy that most of the intellisense seems to be back. perhaps this is an edge case issue now for tkinter?? let me know if you want me to try anything else 

thanks for you quick reply

**Comment by shuffle2** [comment]
I am having this issue too, however I have not tried reinstalling yet. IMO if reinstalling fixes it, there is some bug (maybe in VSCode?) that still needs fixing...

**Comment by DonJayamanne** [comment]
@mrhockeymonkey , @shuffle2 
This is most likely a bug in the [Jedi library](http://jedi.jedidjah.ch/en/latest/) that I'm using for intellisense.
I'll report this issue on that repo.

Note: Currently i'm using the latest (development) version of the library (not the stable release version). Hence there could be a few issues, and this (the one you have reported) looks like a bug.

If this gets too annoying, you can always revert back to the original (final) release by adding the following setting in your user ```settings.json``` (user settings, so you don't have to apply it in every workspace):   

```json 
    "python.devOptions":[
        "USERELEASEAUTOCOMP"
    ]
```

**Comment by shuffle2** [comment]
Thanks! that `python.devOptions` does work.
