### ISSUE TITLE
Remove certain pylint Categories

### ISSUE THREAD

**Issue by 3ximus** [DonJayamanne/pythonVSCode#532]
I see in the documentation the possibility to change the categories of pylint with one of these:
```json
	// Severity of Pylint message type 'Convention/C'.
	"python.linting.pylintCategorySeverity.convention": "Information",

	// Severity of Pylint message type 'Refactor/R'.
	"python.linting.pylintCategorySeverity.refactor": "Hint",

	// Severity of Pylint message type 'Warning/W'.
	"python.linting.pylintCategorySeverity.warning": "Warning",

	// Severity of Pylint message type 'Error/E'.
	"python.linting.pylintCategorySeverity.error": "Error",

	// Severity of Pylint message type 'Fatal/F'.
	"python.linting.pylintCategorySeverity.fatal": "Error",
```

But there doesnt seem to be a way to turn them off, could this be added? I have to turn this off since i use tabs for indentation and the underlining is annoying...

**Comment by DonJayamanne** [comment]
@3ximus 
You could configure pylint in your user settings file (```settings.json```) as follows:  
```json
    "python.linting.pylintArgs": [
        "--disable=W0312"
    ],
```

This way specific error messages from pylint are ignored, and ignored across all workspaces.
FYI - The error number is displayed against the error message displayed.

**Comment by 3ximus** [comment]
@DonJayamanne Thanks :+1:
