### ISSUE TITLE
Move Jupyter stuff into separate extension and make language agnostic

### ISSUE THREAD

**Issue by davidanthoff** [DonJayamanne/pythonVSCode#533]
I just came across this extension, and it is great! I maintain the [julia language extension](https://github.com/JuliaEditorSupport/julia-vscode), and essentially now that I have seen all the cool jupyter stuff here, I would like to provide all the same functionality for julia users.

Given that jupyter is language-agnostic, is there a chance that the generic stuff could be moved into a separate jupyter extension that works with other language kernels as well, e.g. the julia kernel?

I haven't looked into extension dependencies, but I believe they exist now? So maybe a design could be that both the python and julia extension depend on the jupyter extension, and then the language specific code (e.g. detection of code cells etc.) would live in the language extension?

**Comment by DonJayamanne** [comment]
Sounds like a plan, will start on this asap (will add you as a contributor as well).

**Comment by davidanthoff** [comment]
Great!

**Comment by DonJayamanne** [comment]
@davidanthoff 
Work has commenced and will be completed soon. Will let you know tomorrow.
At the moment, the only language specific code would be the detection of the cells.
My plan is to do this via RegularExpressions. Individual extensions would provide the necessary regex to detect the cell boundaries.

**Comment by davidanthoff** [comment]
Wow, that is so cool, very much looking forward to this.

**Comment by DonJayamanne** [comment]
Will be published this weekend.
https://github.com/DonJayamanne/vscodeJupyter
