### ISSUE TITLE
Find and utilise WSL Python Environments

### ISSUE THREAD

**Issue by kuza55** [DonJayamanne/pythonVSCode#534]
Since windows processes can now call bash.exe to call processes in the WSL subsystem, it would be nice if VS code could:

a) Be configured to utilise a python interpreter inside WSL through bash.exe
b) Automatically find WSL virtualenvs in the current project and let the user use them easily

Making the Jupyter integration work in this scenario would also be very cool.

**Comment by rogersachan** [comment]
I'll close #195 since this is better worded

**Comment by shanalikhan** [comment]
+1 , i am using python extension in code inside ubuntu and inside virtual box :)
Would love if Bash support is provided with intellisense so i can use Bash with this extension and compile using bash libraries

**Comment by M-Adoo** [comment]
+1

That be nice, if i can use wsl python enviroment across some config. 

like this ?
```json
{
   "python.linting.pylintPath": "C:\\Windows\\sysnative\\bash.exe",
    "python.linting.pylintArgs": ["-c", "pylint"]
}
```

**Comment by csholmq** [comment]
Using @M-Adoo's approach, debugging "Integrated Terminal/Console" launches WSL successfully. But then it tries calling

```
$ cd null ; env PYTHONIOENCODING=UTF-8 python C:\Users\sholmq\.vscode-insiders\extensions\donjayaman
ne.python-0.5.5\pythonFiles\PythonTools\visualstudio_py_launcher.py null 60475 34806ad9-833a-4524-8cd6-18ca4aa74f14 WaitOnAbnormalExit,WaitOnNormalExit c
:\Users\sholmq\Desktop\pycflow2dot\pycflow2dot.py
```

to try and launch _visualstudio_py_launcher.py_. The problem is that on WSL, the `C:/` root is at `/mnt/c/` instead.

Any way to change this?

**Comment by tmcdonnell87** [comment]
+1

**Comment by dalyIsaac** [comment]
+1

**Comment by rogersachan** [comment]
Please see https://github.com/Microsoft/vscode-cpptools/issues/85#issuecomment-277128833

It appears a API will be made available for WSL/Bash for Windows.

**Comment by joel-wright** [comment]
Is there any update on this or the other Bash on Windows 10 issues?

**Comment by DonJayamanne** [comment]
Unfortunately nothing yet.

**Comment by overshard** [comment]
I'm still looking for this too, it appears to be a matter pythonVSCode can't be told if it's executing stuff on windows or on WSL. We just need a way to have it use WSL pathing `/mnt/c/Users/"USERNAME"/.vscode/extensions/...` instead of the windows path and we could atleast get projects running through the integrated terminal functionality. Pretty much what @csholmq says above.

**Comment by postgrep** [comment]
I think an option to choose to either use the Windows environment or the WSL environment should be provided direcly by the editor, not by each plugin.

Other language plugins for VScode for Windows have this issue too.
https://github.com/Microsoft/vscode-go/issues/926

I think the following issue in VScode itself relates to this one.
Microsoft/vscode#22663

I would prefer a global option in the editor itself.

**Comment by rjgonza** [comment]
+1

**Comment by hacdias** [comment]
+1

**Comment by trungtrinh44** [comment]
+1

**Comment by brettcannon** [comment]
FYI, the best way to vote for a feature is to simply use the 👍 reaction on the top message in the feature request as that helps provide a concrete number of how many people want this. +1s get lost in the noise of the feature request and end up generating email for everyone following this issue.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#67
