### ISSUE TITLE
Incomplete auto-complete list

### ISSUE THREAD

**Issue by ACFred** [DonJayamanne/pythonVSCode#535]
## Environment data
VS Code version:  1.7.1
Python Extension version:  0.5.2
Python Version:   2.7.6 (Maya's custom version, mayapy.exe)
OS and version:    Windows 10
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
{
    "python.pythonPath": "C:/Program Files/Autodesk/Maya2016/bin/mayapy.exe",
    "python.linting.pylintEnabled": false,
    "python.linting.pylintPath": "C:/Program Files/Autodesk/Maya2016/Python/Scripts/pylint.exe",
    "sendToMaya.mayaHost": "192.168.0.127",
    "python.autoComplete.extraPaths": [
        "C:/Program Files/Autodesk/Maya2016/lib",
        "C:/Program Files/Autodesk/Maya2016/Python/Lib"
    ]
}
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

## Actual behavior
If I import a Maya module this way:
import maya.cmds as mc
and then do
dir(mc)
I get:
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__']

## Expected  behavior
In Maya, performing the same steps above, I get:
['ATOMTemplateOptions',
 'AbcExport',
 'AbcImport',
 'AbortCurrentTool',
 'ActivateFullBodyPivot',
 'ActivateGlobalScreenSlider',
 'ActivateGlobalScreenSliderModeMarkingMenu',
 'ActivateViewport20',
 'AddAnimationOffset',
 'AddAnimationOffsetOptions',
 'AddAttribute',
 'AddAuxEffector',
 'AddBlendShape',
 'AddBlendShapeOptions',
 'AddBoatLocator',
 'AddBoatLocatorOptions',
 'AddCurvesToHairSystem',
 'AddDivisions',
 'AddDivisionsOptions',
 'AddDynamicBuoy',
 'AddDynamicBuoyOptions',
 'AddEdgeDivisions',
 'AddEdgeDivisionsOptions',
 'AddFaceDivisions',
 'AddFaceDivisionsOptions',
 'AddFloorContactPlane',
 'AddHolder',
 'AddHolderOptions',
...]

## Steps to reproduce:  
-  See above.
-

**Comment by ACFred** [comment]
I got this mostly working now. For Maya 2016+, the python completion files were removed from the main install and put into a separate devkit. Grabbing the right completion directory and pointing to that allows for code completion. 

Is there a way to force code completion without first having to press ctrl+spacebar? I'll look that up, but thought I'd ask. It may be more annoying to have that pop up all of the time without prompting.

Anyway, here are some solution links:

Maya 2016 Ext. 2 Devkit:
https://apps.autodesk.com/MAYA/en/Detail/Index?id=5595681162321676385&appLang=en&os=Win64&autostart=true

Point VS Code to /devkitBase/devkit/other/pymel/extras/completion/py.
I ended up pulling it out of the zip file and placing it with my Maya files so my VS Code settings look like this:

"python.autoComplete.extraPaths": [
        "C:/Program Files/Autodesk/Maya2016/devkit/other/pymel/extras/completion/py"
    ]

After spending too much time looking for a solution for this, I think I now want to just create a way to pull up Maya's Python help file by right-clicking a word instead of relying on intellisense.

**Comment by DonJayamanne** [comment]
You don't need to press ctrl+space. Intellisense  pops up when you type . Character

**Comment by monkeez** [comment]
I'm having the same issue but with Maya 2018. This is my settings.json

```
{
    "editor.acceptSuggestionOnEnter": "off",
    "editor.fontFamily": "Fira Mono, Consolas, 'Courier New', monospace",
    "python.pythonPath": "C:/Program Files/Autodesk/Maya2018/bin/mayapy.exe",
    "python.autoComplete.extraPaths": [
        "C:/Program Files/Autodesk/Maya2018/devkit/other/pymel/extras/completion/py"
    ]
}
```

I'm able to get auto complete to work in PyCharm because I can remove this path from the interpreter: `C:/Program Files/Autodesk/Maya2018/Python/Lib/site-packages`

It seems to create conflicts with the extraPaths, is there any way to remove a path in this extension?
