### ISSUE TITLE
Wiki documentation error in the linting section

### ISSUE THREAD

**Issue by gtracy** [DonJayamanne/pythonVSCode#536]
https://github.com/DonJayamanne/pythonVSCode/wiki/Linting

In the pylint section there is a remote reference to command line arguments in the "Custom Configuration" section,

> Custom Configuration
> You can customize the linter by providing a configuration file for pylint and placing it in the necessary location.
> For instance you could place a pylintrc or .pylintrc file in the workspace folder. For further details please refer Pylint Command Line Options
> 

That link to "Pylint Command Line Options" is not correct. It should be,

https://pylint.readthedocs.io/en/latest/user_guide/run.html#command-line-options

I don't believe there is a pull request workflow for Wiki changes. Otherwise, I'd fix this myself.

**Comment by DonJayamanne** [comment]
Done, thanks
