### ISSUE TITLE
Not all pytest test methods get test lenses

### ISSUE THREAD

**Issue by iivvoo** [DonJayamanne/pythonVSCode#538]
## Environment data
VS Code version:  1.7.1
Python Extension version:  0.5.2
Python Version:   3.5.1
OS and version:    Ubuntu 16.04.1 64bit

Your settings.json:   
```json

    "python.pythonPath": "bin/python",
    "python.unitTest.pyTestEnabled": true,
    "python.unitTest.unittestEnabled": false,
    "python.unitTest.nosetestsEnabled": false,
    "python.unitTest.pyTestArgs": [
        "--exitfirst",
        "--verbose"
    
```   
## Logs

(nothing relevant)

## Actual behavior

pythonVSCode doesn't recognize all pytest test methods. Seems to be different per module. See attached screenshot - classlevel and one methodlevel test code lens is present

## Expected  behavior

I expect code lenses to be present above other test methods

## Steps to reproduce:  

A test class with 4 test methods: `test_hide`, `test_nohide`, `test_event_ended`, `test_event_notended`
Only the class and first method get the test lens. Changing the other test method names to `test_hide` does give them a lens.

![pytest](https://cloud.githubusercontent.com/assets/540122/20483477/7e1e7b1c-aff2-11e6-8b77-aa547292f1dd.png)

(ignore the duplication on line 64 - not relevant)

**Comment by iivvoo** [comment]
For completeness sake, if I copy the entire test class to a standalone test module I no longer get any lenses at all anymore.

Test code:
```
import pytest
from django.core.urlresolvers import reverse
from django.utils import timezone
from datetime import timedelta

from .factories import EventFactory


@pytest.mark.django_db(transaction=False)
class TestAPIFilter:

    def test_hide(self, client):
        EventFactory.create(hide=True)
        response = client.get(reverse('guts_events'))
        assert len(response.data['results']) == 0

    def test_nohide(self, client):
        EventFactory.create(hide=True)
        response = client.get(reverse('guts_events'))
        assert len(response.data['results']) == 0

    def test_ended(self, client):
        EventFactory.create(hide=False)
        response = client.get(reverse('guts_events'))
        assert len(response.data['results']) == 1

    def test_event_ended(self, client):
        past = timezone.now() - timedelta(days=1)
        EventFactory.create(ends=past)
        response = client.get(reverse('guts_events'))
        assert len(response.data['results']) == 0

    def test_event_notended(self, client):
        future = timezone.now() + timedelta(days=1)
        EventFactory.create(ends=future)
        response = client.get(reverse('guts_events'))
        assert len(response.data['results']) == 1
```

**Comment by DonJayamanne** [comment]
@iivvoo 
Please could you provide the following information?  
- Where is you test file located in your project?  (what directory is it located in)  
- What is the name of your test file
- Please type the following command in you terminal window and provide the output:  
```py.test <testdirectory> --collect-only```

Where ```<testdirectory>``` is to be replaced with the directory containing you test files. If it is in the root directory, then omit that argument.

**Comment by DonJayamanne** [comment]
Any update in this

**Comment by pchomik** [comment]
Editor version: 1.8.1
Plugin version: 0.5.5

I have similar issue. In addition when I run command "python.selectAndRunTestMethod" I'm getting such error:
![image](https://cloud.githubusercontent.com/assets/1779381/21389942/91c00b28-c784-11e6-9d3d-54c6f6f188d0.png)
After that I'm reopening file and everything looks ok.

**Comment by tillahoffmann** [comment]
Having a similar problem with the following setup

* VSCode: 1.8.1
* Plugin: 0.5.5

Tests are located in `<root>/tests/test_sampling.py`. Some are decorated with a test lens. Some aren't. Running `py.test tests --collect-only` discovers all tests including the ones without a decorator.

After restarting VSCode, the all tests were discovered by the plugin. Some issue with caching?

**Comment by DonJayamanne** [comment]
@tillahoffmann, thanks for the repo, will check this when I get back. Still away on my break.

**Comment by Christoph-Schabert** [comment]
Still having the problem is there a workaround without restarting vscode?

**Comment by mungojam** [comment]
we are getting this same problem with various versions of VS Code/python extension including the latest. Disabling GitLens fixes it, but they seem convinced that it's an issue with the python extension. 

Still using Jedi for now as had some maxxing-CPU issues with the new language server.
