### ISSUE TITLE
Add support for PySpark

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#541]
@shengyfu 

Currently if someone wants to us PySpark they need to launch the command ```python.updateSparkLibrary```.

This is different to when someone wants to use Anaconda, or other Python interpreters.
To keep things consistent we should:

1. Modify ```src/client/providers/setInterpreterProvider.ts``` to add the PySpark interpreter into the list. To do this, modify the following method to make another call to a new function ```suggestionsFromPySpark()```, as follows:
```python
function suggestPythonPaths(): Promise<PythonPathQuickPickItem[]> {
    // For now we only interrogate conda for suggestions.
    const condaSuggestions = suggestionsFromConda();
    const knownPathSuggestions = suggestionsFromKnownPaths();
    const virtualEnvSuggestions = lookForInterpretersInVirtualEnvs(vscode.workspace.rootPath);
    const pysparkSuggestions = suggestionsFromPySpark();

function suggestionsFromPySpark(): Promise<PythonPathSuggestion[]> {
    // Here you can check if the path ${env.SPARK_HOME} exits. if it does, then depending on the current os you can return the appropriate path :
    // osx - ${env.SPARK_HOME}/bin/spark-submit
    // windows- ${env.SPARK_HOME}/bin/spark-submit.cmd
    // linux - ${env.SPARK_HOME}/bin/spark-submit
```

2. Modify the [jediProxy.ts](https://github.com/DonJayamanne/pythonVSCode/blob/master/src/client/providers/jediProxy.ts#L502) file to dynamically add the pyspark paths. 
- Check if the current ```python.pythonPath``` is starting with the resolved value of ```${env.SPARK_HOME}```
- If yes, then the user is most likely using PySpark in VS Code
- Next, (if the above evaluated to true) append the paths ```${env.SPARK_HOME}/python``` and ```${env.SPARK_HOME}/python/pyspark``` to the list [extraPaths](https://github.com/DonJayamanne/pythonVSCode/blob/master/src/client/providers/jediProxy.ts#L502)

With this change, the end user need not invoke a command to configure the intellisense paths.

Let me know if you have any questions, I believe the changes are fairly simple.

**Comment by shengyfu** [comment]
@DonJayamanne 
Thanks for the suggestions, we tried both and worked as you suggested, but the intellisense fails once the pythonPath changes to spark-submit path, I think the reason is spark-submit is a batch file, not a real python interpreter, see attached zip file containing the batch files.


[bin.zip](https://github.com/DonJayamanne/pythonVSCode/files/607917/bin.zip)

**Comment by DonJayamanne** [comment]
@shengyfu 
Yes, that makes sense.
Ok, I guess you have to retain the command ```python.updateSparkLibrary```.

One last question, does the debugging work?

**Comment by shengyfu** [comment]
Yes, debugging works great!

**Comment by DonJayamanne** [comment]
ok then, i guess thats it, thanks
