### ISSUE TITLE
vscode.workspace.rootPath would be undefined when no folder has been opened

### ISSUE THREAD

**Issue by lcy0321** [DonJayamanne/pythonVSCode#542]
## Environment data
VS Code version:  1.7.2
Python Extension version:  0.5.3
Python Version:   3.5.2
OS and version:   Windows 7

In [the reference of VS Code](https://code.visualstudio.com/Docs/extensionAPI/vscode-api#_workspace)
> rootPath: The folder that is open in VS Code. `undefined `when no folder has been opened.

However,
in `"src/client/common/systemVariables.ts, line 140-141"`:
> this._workspaceRoot = vscode.workspace.rootPath;
> this._workspaceRootFolderName = Path.basename(this._workspaceRoot);

in `"src/client/providers/lintProvider.ts, line 141"`:
> const relativeFileName = path.relative(vscode.workspace.rootPath, document.fileName);`

Beacause `path.basename()` and `path.relative()` would throw `TypeError` if the given path is not a string, 
so it will raise `TypeError: Path must be a string. Received undefined` when there is no folder has been opened, and the extension would stop working.

**Comment by DonJayamanne** [comment]
@lcy0321 
Will fix this tomorrow.
