### ISSUE TITLE
Cannot install missing packages: pylint, flake8, etc.

### ISSUE THREAD

**Issue by skilliscode** [DonJayamanne/pythonVSCode#544]
## Environment data
VS Code version:  1.7.2
Python Extension version: 0.5.3 
Python Version:   3.52
OS and version:    macOS 10.12.1

## Logs
Output from ```Python``` output panel  
```
python -m -m pip install flake8
```   

## Actual behavior
Package is not installed
## Expected  behavior
Package is installed.
## Steps to reproduce:  
Click "install pylint/flake8" from the alert box when after open a py file.

**Comment by rusty-coder** [comment]
I have faced the same issue when I click on the popup to install pylint.

I am using a python virtual environment. When I click on the install button for pylint, the following command gets executed

`<python_virtual_environment>\python.exe -m -m pip install pylint`

which obviously throws a *"No module named -m"* error

VS Code version: 1.7.2
Python Extension version: 0.5.3
Python Version: 3.52
OS and version: Windows 7

**Comment by DonJayamanne** [comment]
Fixed 292c010ce86146d94dae71f65b39ba8e3e8d6694
Will release a new version today
