### ISSUE TITLE
Cannot run debug in node 1.7.2 ENOENT error

### ISSUE THREAD

**Issue by imaia** [DonJayamanne/pythonVSCode#546]
## Environment data
VS Code version:  1.7.2
Python Extension version:  0.5.3
Python Version:   3.5.2
OS and version:  xubuntu 16.04  
Your launch.json (if dealing with debugger issues):  
```json
    {
            "name": "Django",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${workspaceRoot}/manage.py",
            "cwd": "null",
            "args": [
                "runserver",
                "--noreload",
                "--settings=settings.dev"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "DjangoDebugging"
            ]
        },
```   
Your settings.json:   
```json
// Place your settings in this file to overwrite default and user settings.
{
    "python.pythonPath": "/home/me/.virtualenvs/project/bin/python",

    "editor.trimAutoWhitespace": true,
    "files.trimTrailingWhitespace": false
}
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
Error: spawn /home/me/.virtualenvs/project/bin/python ENOENT
```

## Actual behavior
Prints the error, even thought /home/me/.virtualenvs/project/bin/python exists. 

## Expected  behavior
Should start runserver in debug mode.

## Steps to reproduce:  
- Default python debug configuration + run django debug

**Comment by DonJayamanne** [comment]
Please check if there is a space in the value within the quotes:
"/home/me/.virtualenvs/project/bin/python"

Finally, please enter this value as us into the terminal window and check if it works. 

The value is not valid, that's why you are getting this error, the file cannot be found.

**Comment by imaia** [comment]
There isn't an space. I just copied it from settings and threw in my console. Python console is called alright.

**Comment by imaia** [comment]
Found the problem. The debug config cwd was set to null. This was set by default by VScode, so I paid it no mind. After changing it to ${workspaceRoot} debug is working once more.

**Comment by DonJayamanne** [comment]
Will fix the default values for cwd
