### ISSUE TITLE
extraPaths should work for linting too

### ISSUE THREAD

**Issue by imaia** [DonJayamanne/pythonVSCode#547]
VS Code version: 1.7.2
Python Extension version: 0.5.3
Python Version: 3.5.2
OS and version: xubuntu 16.04
Your settings.json:   
```json
{
    "python.autoComplete.extraPaths": ["~/somelibs"]
}
```   

## Actual behavior
Autocomplete becames able to import from "somelibs", but pylint still accuses of import error.

## Expected  behavior
Autocomplete and linting should both be affected by extraPaths as it makes sense for both of them to have the same path.

## Steps to reproduce:  
- Configure autocomplete extraArgs with a folder outside of the default path.

**Comment by DonJayamanne** [comment]
This is an issue with the pyLint linter .

Please confirm you have installed pyLint in the right portion environment. If yes, and it is still not getting picked up, then please report this issue in pylint.

**Comment by imaia** [comment]
I wonder if this issue could be related to #546

**Comment by DonJayamanne** [comment]
If you are getting liner messages, then no.

**Comment by imaia** [comment]
Well, I moved to flake8 for now. Works just fine. Maybe having it as default would be nice.

**Comment by DonJayamanne** [comment]
Will change the behavior to display a prompt
