### ISSUE TITLE
Run Python File in Terminal

### ISSUE THREAD

**Issue by JonasUJ** [DonJayamanne/pythonVSCode#548]
## Environment data
VS Code version:  v1.7.2
Python Extension version:  v0.5.3
Python Version:   v3.5
OS and version:   Windows 10 Home 64-bit (10.0, Build 14393)
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

## Actual behavior
Error message saying: ERROR command 'python.execInTerminal' not found

## Expected  behavior
Python file runs in terminal

## Steps to reproduce:  
-  Rightclick
-  Click "Run Python File in Terminal"

It worked, then I noticed the 0.5.3 update for Python in vscode. I installed it, reloaded, rightclick - run python file and it gave me the error.

**Comment by DonJayamanne** [comment]
@JonasUJ 
Please could you go into ```Help->Toggle Developer Tools``` and check what errors are displayed in the console window.

**Comment by DonJayamanne** [comment]
Similar to #550
