### ISSUE TITLE
The problems view gets empty for a while after saving

### ISSUE THREAD

**Issue by marmistrz** [DonJayamanne/pythonVSCode#552]
## Environment data
VS Code version: 1.7.2
Python Extension version: 0.5.5
Python Version: 3.5.2
OS and version: Arch Linux
Your settings.json:   
```
{
    "update.channel": "none",
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false,
    "files.trimTrailingWhitespace": true
}
```   
## Logs
Output from ```Python``` output panel: can't find that, probably irrelevant
Output from ```Console window```: clean

## Steps to reproduce:  
-  Create a python script which doesn't adhere to what pylint accepts.
-  Remove one problem
-  Save the file

## Actual behavior
The problem list disappears for a while then appears again. 
## Expected  behavior
The problem list should stay as it is until updated. A busy indicator could be shown on the top of it, but the list of problems should definitely stay.

**Comment by DonJayamanne** [comment]
Unfortunately this is a problem with VS Code. I don't clear the problems list untill I have everything.
