### ISSUE TITLE
vscode.executeDocumentSymbolProvider seems to only work once

### ISSUE THREAD

**Issue by eamodio** [DonJayamanne/pythonVSCode#553]
## Environment data
VSCode Version: `1.8.0-insider (1.8.0-insider)` 0b847998d914ff84fd9c13b2972cc8803745c24d
Python Extension version:  `0.5.5`
Python Version: 
OS and version: macOS Sierra `10.12.1 (16B2555)`

## Actual behavior
- In an extension call `vscode.executeDocumentSymbolProvider` it works once, but doesn't seem to work a second time. Returns 0 symbols.

## Expected  behavior
- Should work no matter how many times called

## Steps to reproduce:  
-  In an extension call `vscode.executeDocumentSymbolProvider` -- will return all the symbols
-  In another extension call `vscode.executeDocumentSymbolProvider` -- will return 0 symbols

This *might* be related to https://github.com/DonJayamanne/pythonVSCode/issues/538

See also https://github.com/eamodio/vscode-gitlens/issues/18 for more information.

**Comment by mklemarczyk** [comment]
👍  Thank you for solving problem

**Comment by timharris777** [comment]
What is the status of this? I'm currently running into this issue. Symbols are not working for python

**Comment by eamodio** [comment]
@DonJayamanne why was this closed without any resolution? It looks like there is another case of this causing: https://github.com/eamodio/vscode-gitlens/issues/439
