### ISSUE TITLE
`is` keyword is not highlighted

### ISSUE THREAD

**Issue by ethanroday** [DonJayamanne/pythonVSCode#556]
## Environment data
VS Code version:  1.7.2
Python Extension version:  0.5.5
Python Version:  3.5
OS and version:  Windows 10

settings.json is empty
## Actual behavior
When typing a line such as ```if a is None:```, the keyword ```is``` is not highlighted.

## Expected  behavior
The keyword should be highlighted.

## Steps to reproduce:  
- Type a line with the keyword ```is``` in a Python file.

**Comment by gandhis1** [comment]
To add to this, the keywords `and` and `or` are also not highlighted.

**Comment by DonJayamanne** [comment]
This is an upstream issue
