### ISSUE TITLE
Python Debugging will not stop when I click the stop button.

### ISSUE THREAD

**Issue by toknee** [DonJayamanne/pythonVSCode#557]
## Environment data
VS Code version:  1.7.2
Python Extension version:  0.5.5
Python Version:   2.7
OS and version:   Windows 7 
Your launch.json (if dealing with debugger issues):  
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Integrated Terminal/Console",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "console": "integratedTerminal",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
        {
            "name": "External Terminal/Console",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "console": "externalTerminal",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
        {
            "name": "Django",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${workspaceRoot}/manage.py",
            "args": [
                "runserver",
                "--noreload"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "DjangoDebugging"
            ]
        },
        {
            "name": "Flask",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${workspaceRoot}/run.py",
            "args": [],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Watson",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${workspaceRoot}/console.py",
            "args": [
                "dev",
                "runserver",
                "--noreload=True"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Attach (Remote Debug)",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "${workspaceRoot}",
            "port": 3000,
            "secret": "my_secret",
            "host": "localhost"
        }
    ]
}
```   
Your settings.json:   
```
{
}
```   
## Logs
Output from ```Python``` output panel  
```
N/A
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
N/A
```

## Actual behavior
When debugging a Python script and I want to Stop a debugging session, I hit the Red stop button but the session does not stop. I have to close out of VSCODE and open again to regain control.

## Expected  behavior
Stopping debugging by hitting STOP button will stop the debugging session.
## Steps to reproduce:  
-  Start debugging session with breakpoints, attempt to stop the session by hitting the red stop debug button
-  Does not stop

**Comment by DonJayamanne** [comment]
What is the debug configuration you are using?  
What kind of application is being debugged?  
Can you replicate this with a simple python program that waits for input from the user (from console window)?

**Comment by toknee** [comment]
If you mean the debug config in the launch.json, I've included it on the original post.

This is more of a self contained script used to manipulate strings and output a lengthy formatted string based on inputs. No use of imports or external dependencies, just basic python.

Yes, I can reproduce it with this simple construct::

def doit(xx):
    raw_input("Press Enter to continue...")
    print(xx) 

doit('finished')

I put the breakpoint at the print, start debug session, it waits for input, I hit stop debugging button and nothing happens

**Comment by DonJayamanne** [comment]
Which debug configuration are you using?  
When you start debugging, what item have you selected from the dropdown list?
```Python```, ```Integrated Terminal/Console```, ```External Terminal/Console```...

**Comment by toknee** [comment]
{
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }
If that's not it, then I'm not sure what you're referring to.

When I debug I leave the dropdown set to Python.

**Comment by DonJayamanne** [comment]
Closing this as I am unable to replicate this. Please reopen if this problem still persists.
