### ISSUE TITLE
Python Interactive - List Errors in Results View

### ISSUE THREAD

**Issue by drcrook1** [DonJayamanne/pythonVSCode#558]
It would be good if an error occurred during execution of a cell that the error for that cell were presented in the results view.  Makes a cleaner debugging experience.

**Comment by DonJayamanne** [comment]
Errors are displayed in the results views today. Please describe scenario in detail, what isn't happening, with an example.

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/vscodeJupyter#15
