### ISSUE TITLE
Annoying Tests Prompts

### ISSUE THREAD

**Issue by gandhis1** [DonJayamanne/pythonVSCode#559]
For workspaces in which I do not have tests, I get rather annoying prompts when discovering tests:

If there are not tests discovered, a notification in the task bar would be nice, but does it really need to show a large, conspicuous prompt at the top? Even if there are errors, I don't feel there should be that prompt at the top. Status bar notifications are enough, the current set up I feel is too much of an annoyance.

![image](https://cloud.githubusercontent.com/assets/21064086/20720055/dfe7bbe4-b62b-11e6-8fa5-0a03c3af8b43.png)

**Comment by DonJayamanne** [comment]
Looks like you have turned on tests at a user level, hence this message. You need to turn it off at the user level.
Basically you have said that all work spaces will have tests, hence the message.

**Comment by gandhis1** [comment]
So this forces me to have a workspace-specific settings? Why am I required to have tests (or working tests) if the settings is turned on? The setting is whether the tests/testing framework is _enabled_, not whether it is _active_.

**Comment by DonJayamanne** [comment]
Will provide a prompt to disable tests, if not discovered.

**Comment by DonJayamanne** [comment]
> The setting is whether the tests/testing framework is enabled, not whether it is active.
Enabled and Turned on are the same. There are no two different settings.

**Comment by gandhis1** [comment]
I know...what I'm asking is why when a testing framework is enabled, there has to be tests. Does there have to be code when a linter is enabled? It just doesn't lint anything. If I understand the prompt correctly, it would disable tests in the workspace permanently. Is there going to be a prompt when one finally does add tests to re-enable it? Why should this be manual behavior rather than automatic behavior. A developer probably already has knowledge of the existence (or lack thereof) of tests in his/her workspace. 

The user experience I feel is most logical is I can enable tests globally, and if tests are there, it runs, if there are no tests, then it will display a subtle message in the task bar, rather than the jarring prompt as of now. That prompt shows up every time I re-open my workspace, too, making it even more jarring.

**Comment by DonJayamanne** [comment]
Initially the message was displayed in the task bar, but later requested by msft to display a prompt. Hence the prompt.

**Comment by gandhis1** [comment]
@jospeng has pretty much a word for word copy of my issue in #504. As he described it in his nearly identical issue, this seems like a usability regression.

What are the circumstances surrounding the MSFT request? I know there were a large number of issues created by MSFT people a couple months ago. I'm sure whoever it is has good intentions, but they may not be using the extension day-to-day like myself and @joshpeng are. Perhaps they didn't foresee this result of moving to a prompt?

**Comment by DonJayamanne** [comment]
His issue was different. Back then tests were enabled by default, even when the user didn't want it. So he was getting a prompt, even when he didn't want the tests.

You on the other hand have stated (via config) that you want test every where, however don't want to be notified  of the issues/errors related to it.

**Comment by DonJayamanne** [comment]
The UX Issue is, if the configuration of tests are invalid, then tests won't work. The message displayed in the status bar isn't too obvious to the user, hence the prompt.
So really, there  are two sides to this.

**Comment by joshpeng** [comment]
To clarify my issue is pretty much the same as @gandhis1.

This is what it used to do:
1. Tests activated globally <-- desired. Don't want to have to manually turn on tests per workspace. Too much work
2. When tests are present = worked
3. When tests are not present = no popup, only says "No tests found" <-- MSFT concern of hard to find

What it is now:
1. Tests activated globally
2. When tests were present = worked;
3. When tests are not present = popup every single time this workspace is opened <-- gets annoying

So right now if you don't want to be nagged every time you have to activate tests on every workspace manually instead of setting it globally. This is the usability regression because it is too much work to do so.

I believe the MSFT request you are referring to is for the original scenario where "No tests found" was insufficient for user discovery of the feature. If that is the concern then all we need is a "do not show again" feature on the popup.

Ideal behavior is then this:
1. Tests activated globally <-- desired.
2. When tests are present = worked
3. When tests are not present = popup, but with a "do not show again" option to disable the message

**Comment by DonJayamanne** [comment]
>When tests are not present = popup, but with a "do not show again" option to disable the message

- Would this be to turn off the message for this session. I.e. if you close and open this workspace, would you expect to see the prompt once again.
- By 'don't show again' does this actually turn off unittests or merely turns off the display of the prompt.

**Comment by joshpeng** [comment]
If possible, disable the prompt for the relevant workspace permanently. Probably overkill would be trying to reactivate the prompt if some config changes to unit tests were made.

**Comment by DonJayamanne** [comment]
Ok, so the change I'd make is, "Don't show again" would be displayed and doing so would turn off the prompt for the workspace permanently.
Will implement this.

**Comment by DonJayamanne** [comment]
@gandhis1 @joshpeng 
Thanks guys,

**Comment by joshpeng** [comment]
@DonJayamanne Hi Don, hope you had some great holiday vacationing. Just wanted to check in on this. Thanks a bunch for all the good work.

**Comment by DonJayamanne** [comment]
Will work on this, as for the holiday, it isn't over yet 😁

**Comment by DonJayamanne** [comment]
Thanks for being patient

**Comment by joshpeng** [comment]
@DonJayamanne Thanks for the latest version. This is the new setting right?
```
"python.unitTest.promptToConfigure": false
```
I set it in my User Settings, but I am still getting the _"No tests discovered, please check the configuration settings for the tests."_ message. Is there something else new I am missing? Thanks. I'm not trying to disable the tests in the workspace, just the prompts.

**Comment by DonJayamanne** [comment]
@joshpeng, thats incorrect.
You will need to add the following settings:
```json
"python.unitTest.unittestEnabled": false,
"python.unitTest.pyTestEnabled": false,
"python.unitTest.nosetestsEnabled": false,

```
