### ISSUE TITLE
quick fix (command+.) no longer working

### ISSUE THREAD

**Issue by potatochip** [DonJayamanne/pythonVSCode#562]
## Environment data
VS Code version:  
Python Extension version:  
Python Version:   
OS and version:    
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

## Steps to reproduce:  
-  
-

**Comment by DonJayamanne** [comment]
Need  more info

**Comment by DonJayamanne** [comment]
Quick fix commands were only displaying the refactor options, these are now standard context menu items
