### ISSUE TITLE
Refactoring while syntax error exists in file fails ungracefully

### ISSUE THREAD

**Issue by mousetraps** [DonJayamanne/pythonVSCode#563]
Two issues:
1. the refactor fails
2. two messages are displayed in the info bar
![image](https://cloud.githubusercontent.com/assets/762848/20911516/4d5c8844-bb1d-11e6-8f1d-75fa2a62660e.png)

Repro steps - try renaming `hours` in the following example where python 2.7 print syntax was invalid-ly used w/ python 3.5
```python
print 'hello'

def get_total_pay(hours, dollars_per_hour):
    return hours * dollars_per_hour
```

**Comment by DonJayamanne** [comment]
The refactor can only work if there's valid Python code in the file.  
As the error indicates the syntax is invalid, hence the refactoring has failed.
