### ISSUE TITLE
redundant empty tooltips for some functions

### ISSUE THREAD

**Issue by mousetraps** [DonJayamanne/pythonVSCode#565]
See below. All items are the same as you arrow through the list:

![image](https://cloud.githubusercontent.com/assets/762848/20912564/ed30c662-bb24-11e6-8c0e-6cd47fed20f6.png)

![image](https://cloud.githubusercontent.com/assets/762848/20912569/f98cf12e-bb24-11e6-9580-67628d45f347.png)

**Comment by DonJayamanne** [comment]
Fixed in latest version
