### ISSUE TITLE
Lists/dicts in variable view are collapsed when stepping through code

### ISSUE THREAD

**Issue by woutgg** [DonJayamanne/pythonVSCode#566]
When debugging anything involving a list or dictionary I like to expand its tree in the variable view to have the items visible vertically..
When doing any kind of continue/step operation however, the view collapses again which makes it difficult and somewhat annoying to see what has changed.
It would be nice if this collapsed/expanded state would be retained while stepping through the code.

**Comment by DonJayamanne** [comment]
Unfortunately this list gets refreshed as each stack could potentially update the values, and VS Code will re-query the list of items for display.
I'll check what happens with node.js and other debuggers in VS Code.
