### ISSUE TITLE
Idea: Change default linter behavior to "pylint -E"

### ISSUE THREAD

**Issue by ncoghlan** [DonJayamanne/pythonVSCode#568]
Hi, I'm considering switching to vscode as my main editor, and the main thing holding me back is that I haven't figured out yet how to change the default linter behaviour to "python -E" (in the absence of a project-specific pylint configuration file).

Reading https://codewithoutrules.com/2016/10/19/pylint/ today though prompted me to file this as an RFE for changing the default: I'm sure I'm far from the only one that has tried to use vscode with existing code bases and been put off entirely by the sheer amount of noise and nonsense generated by pylint's default settings.

Defaulting to `pylint -E` instead would mean that user's initial experience with vscode and its Python plugin would be for it to consistently catch real bugs in their code, and they could defer the question of whether or not to start using the more opinionated levels based on the kinds of problems they tend to encounter in code review, testing, and post-deployment.

**Comment by DonJayamanne** [comment]
Thanks for the suggestion, unfortunately its too late for me to change this at this stage.
Changing this now would change the output (behaviour) of Pylint for almost all users out there.  
Besides Pylint is the default linter enabled by this extension, hence everyone would be affected.
