### ISSUE TITLE
How to turn off pylint warning?

### ISSUE THREAD

**Issue by Yefee** [DonJayamanne/pythonVSCode#570]
## Environment data
VS Code version:  1.7.2
Python Extension version:  
Python Version:   2.7.12
OS and version:    Mac OS, 10.11.6

Hi, all

I want to turn off the pylint warning, as the green lines show in the figure.
![screen shot 2016-12-07 at 11 40 40 pm](https://cloud.githubusercontent.com/assets/6420873/20998975/0946a624-bcd7-11e6-9b9b-5c3408a42521.png)

Below is what I modified in my setting.json.
```
  // Severity of Pylint message type 'Warning/W'.
    "python.linting.pylintCategorySeverity.warning": "Hint"
```
Just hack the warning to hind, but failed. Is there any good suggestions?

**Comment by coreylenertz** [comment]
Hi Yefee. I ran into this problem a few hours ago and thought I would share my solution.

Navigate to your project working directory and execute `pylint --generate-rcfile > .pylintrc`. This will generate a configuration file for pylint. Open the file and search for the line that starts with "disable=". Provide a comma delimited list of messages you want to disable. For available messages, you can execute `pylint --list-msgs`.

You can also add a comment at the end of the line you want to modify linting rules.
Example: `import foo # pylint: disable=W0611`

**Comment by Yefee** [comment]
Thanks, @coreylenertz ! That works fine!

**Comment by amoghskulkarni** [comment]
Found another way -
Go to File > Preferences > Settings. Add the following to your user settings -
```javascript
{
    "python.linting.pylintArgs": ["--errors-only"]
}
```
For some reason, my `pylint` stopped working as soon as I generated `.pylintrc`, so I had to opt for another solution.

**Comment by Yefee** [comment]
@amoghskulkarni 
Thats a fantastic way!

**Comment by keitherskine** [comment]
Has anybody got any idea how to disable certain pylint messages in VS Code on Windows?  I tried creating a custom pylint rc file and defining the following setting:
```
"python.linting.pylintArgs": ['--rcfile=C:\Users\Keith\Documents\Python\pylint_rc_file.txt']
```
but the config file seems to be being ignored.

**Comment by keitherskine** [comment]
I figured it out, the setting should be:
```
"python.linting.pylintArgs": ["--rcfile=C:/Users/Keith/Documents/Python/pylint_rc_file.txt"]
```

**Comment by fmder** [comment]
I think this is of interest ...

```json
{
    "python.linting.enabled": false
}
```

**Comment by phil-harmoniq** [comment]
Hi guys, I managed to get it working for a single warning by adding
```json
"python.linting.pylintArgs": [
	"--disable=C0111"
],
```
in my settings.

**Comment by noahgift** [comment]
This is what I typically include in a Makefile and it works in settings:

"python.linting.pylintArgs": ["--disable=R,C"]

Personally, I think warnings are very important, i.e., unused variables, so ["--errors-only"] is not as useful.

**Comment by psedik** [comment]
@phil-harmoniq
Thank you! This I think is the most useful, disable only specific warnings and keep all others.

**Comment by tchapin** [comment]
If I add 
`  "python.linting.pep8Args": [
    "--disable=E501"
  ],
`
To user settings is disabled linting altogether.

**Comment by anshulc95** [comment]
@tchapin this worked for me, I was trying to ignore warnings to write docstrings,
I am using `pylint` though, not `pep8`
```json
"python.linting.pylintArgs": [
        "--disable=C0111"
    ],
```

**Comment by ianfhunter** [comment]
@tchapin if you use ``--ignore`` instead of ``disable`` for pep8 it works for me

**Comment by tchapin** [comment]
@geoidesic 
`// Whether to lint Python files.
  "python.linting.enabled": false,`

**Comment by Nathoune** [comment]
Hi guys, 

I format my code with black and don't want to use pylint at all, but each time I save a python file, vsCode ask me to install pylint. How to disable it ?
The solutions you showed just disabled some pylint errors with pylint installed, but I don't want to install it...
any idea ?

**Comment by gurunath-p** [comment]
![pylint_vs](https://user-images.githubusercontent.com/24391028/47853779-da17dd80-de05-11e8-9e76-2e4d6f51263a.png)
I am not able to disable a specific error by using this(and also the argument is shown with a red background). Further whenever I use this `python.linting.pylintArgs` the pylint doesn't work and any warnings present are not displayed. What am I missing?

**Comment by tombola** [comment]
I found that to disable specific pylint errors I had to use `--disable-msg` and the error code as separate parameters:

`"python.linting.pylintArgs": ["--disable-msg", "E0401"],`

I got this from example in the docs:

https://code.visualstudio.com/docs/python/linting#_specific-linters
