### ISSUE TITLE
Pytest debugging with pytest-cov - Wiki update

### ISSUE THREAD

**Issue by oailloud** [DonJayamanne/pythonVSCode#571]
I've been struggling quite a while on the debugger : all the breakpoints were skipped during tests with py.test. The reason was the use of pytest-cov in the pytest options (this is my setup.cfg) :
`addopts = --cov-report xml --cov-report term-missing --cov=folder`

Pytest-cov prevents most debuggers to work as stated [here](http://pytest-cov.readthedocs.io/en/latest/readme.html#coverage-and-debuggers).

My workaround was to edit pytest options in the settings.json by adding this line :
`"python.unitTest.pyTestArgs": ["--no-cov"],`

It allows me to keep coverage when lauching via the CLI while debugging properly in VS Code.

I think it would be nice to mention it in https://github.com/DonJayamanne/pythonVSCode/wiki/Debugging-py.test .

**Comment by DonJayamanne** [comment]
Done,
