### ISSUE TITLE
If I just modify but do not save， lint can't check my code for errors

### ISSUE THREAD

**Issue by tongguang** [DonJayamanne/pythonVSCode#574]
## Environment data
VS Code version:  1.7.2
Python Extension version:  0.5.5
Python Version:   2.7
OS and version:    win10

Your settings.json:   
default

If I just modify but do not save， lint can't check my code for errors。only check when i save code。

I'm sure "python.linting.lintOnTextChange": true, because i  did not change this option

**Comment by DonJayamanne** [comment]
Unfortunately this only works on saved changes.
