### ISSUE TITLE
Debugger struck at user input point.

### ISSUE THREAD

**Issue by Akash187** [DonJayamanne/pythonVSCode#575]
## Environment data
VS Code version:  
Python Extension version:  
Python Version:   
OS and version:    
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

## Steps to reproduce:  
-  
-  

Here is the code which i am trying to debug.
import sys
min = sys.maxint
max = -sys.maxint-1
while True:
    try:
        num = raw_input("Enter a number: ")
        if num == "done":
            break
        num = int(num)
        if num > max:
            max = num
        if num < min:
            min = num
    except:
        print "Invalid input"         
print "Maximum is " + str(max)
print "Minimum is " + str(min)

**Comment by fj128** [comment]
If you're using "Python" launch configuration then input is not supported. Use "Integrated Terminal/Console".
