### ISSUE TITLE
Refactor (rename variable) renames the wrong object

### ISSUE THREAD

**Issue by gandhis1** [DonJayamanne/pythonVSCode#579]
This issue may be useless, because I can't reproduce this easily, but I had the strangest thing happen and I can't figure out why. 

I have a line of code that goes something like this:

`el_scale = pd.read_excel(expected_loss_rating_scale_file)`

1) I hover over `expected_loss_rating_scale_file`, and press F2 to rename.
2) I rename to `el_scale_file`.
3) `pd.read_excel` is renamed to `pd.el_scale_file.` Instead of gracefully failing, the wrong thing (a Pandas function) is renamed.
4) In every other file in my workspace that uses pd.read_excel, it too is renamed to pd.el_scale_file.

The fourth step actually does make sense, if step 3 was correct. However, the fact that Jedi/PyLint/whatever is renaming pd.read_excel incorrectly is a major issue. 

Only thing is, I can't really reproduce this in a compact test case. What I can do is a large sample file through which this issue occurs, however, the information in this file is sensitive so I'd prefer not to post this publicly. 

One potential solution to this - is there any way to check that the variable that Jedi/Pylint wants to rename **is the same** variable as the one that was selected as input? So if I select a variable x and choose to rename it, it does not ever rename anything else except that.

**Comment by StefanUlbrich** [comment]
I experienced a similar behavior – sometimes exactly the same, sometime nothing would happen, sometime rope/python would run forever.

I am running on MacOS and changing the line endings from CRLF to LF fixed the issue – refactoring works – but slow. That might be the source of error.

**Comment by sgtoj** [comment]
I have the same issue. When using the rename symbol option, it only works some times. Most of the time, it does nothing, throws exception, or rename the wrong symbol. Enabling or disabling symbols via `ctags` does not resolve the issue.

![Issue renaming symbol with ctags enabled.](http://i.imgur.com/58pvqim.gif)
*Note: The link may appear to be broken, but it valid Imgur link.*

**Comment by gandhis1** [comment]
What is really needed to solve this issue is a replicable, self-contained test case.

**Comment by DonJayamanne** [comment]
Fixed in the latest version
