### ISSUE TITLE
Go to symbol error

### ISSUE THREAD

**Issue by ghenom** [DonJayamanne/pythonVSCode#58]
Pluggin generates error on go to symbol:
stderr jediProxy
Error (stderr) Traceback (most recent call last):
  File "completion.py", line 309, in watch
    self._process_request(self._input.readline())
  File "completion.py", line 282, in _process_request
    request['id']))
  File "completion.py", line 216, in _serialize_definitions
    'line': definition.line - 1,
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

**Comment by DonJayamanne** [comment]
Hi, I have updated the extension with a new version.
Please could you re-test it, if it doesn't work. The issue is in the Jedi library used. 
If it still exists, then please report the issue on the following git repo:
https://github.com/davidhalter/jedi

**Comment by ghenom** [comment]
This is incorrect, Jedi told me to contact the plugin owner which is you:
https://github.com/davidhalter/jedi/issues/714

**Comment by wakensky** [comment]
Also,  I got the same error on osx 10.11.3.  @DonJayamanne, please try to find out the root cause, thanks!

**Comment by wakensky** [comment]
@ghenom  You may find a quick solution on this pull request
https://github.com/DonJayamanne/pythonVSCode/pull/78

Hope that would help. If you have any questions, please ping me freely :)
