### ISSUE TITLE
Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by Lucidyan** [DonJayamanne/pythonVSCode#583]
## Environment data
VS Code version:  
- Version 1.8.0
- Commit 38746938a4ab94f2f57d9e1309c51fd6fb37553d
- Date 2016-12-13T18:03:00.506Z
- Shell 1.4.6
- Renderer 53.0.2785.143
- Node 6.5.0

Python Extension version:  0.5.5
Python Version:  3.5.2
OS and version:   Ubuntu 16.10 | Linux 4.8.0-30-generic 

## Actual behavior
When I try to format wrong one line like 

> import       pandas as pd

 without new line in the end, with Ctrl+Shift+I, I get

> Cannot read property 'substring' of undefined

But when I add new line to the end of file or write string by pep8, it's working fine.
It's reproduce with yapf, autopep8 crashes without end of file line even with pep8-writed first string.

## Expected  behavior
Autoformatting

**Comment by SkyFather** [comment]
Same issue here

**Comment by rjmacarthy** [comment]
Same issue here.

**Comment by tdbear** [comment]
+1

**Comment by lezhiii** [comment]
+1

**Comment by flyfj** [comment]
adding new line to the end of the file seems to fix my issue.

**Comment by tdbear** [comment]
Upgrading to 1.9.0 Fixed my issue. Newline at end of file did not fix it. So maybe another issue.

**Comment by SkyFather** [comment]
@tdbear I turned to use insider version and this problem is solved. In fact by using the insider, I have never seen the error in both cases.

**Comment by BrianDGLS** [comment]
Adding a new line at the end of the file fixed it for me also.

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/vscodeJupyter#14
