### ISSUE TITLE
LaTeX do not rendered

### ISSUE THREAD

**Issue by Lishen1** [DonJayamanne/pythonVSCode#584]
## Environment data
VS Code version:  1.8.0 
Python Extension version:  0.5.5  
Python Version:   Python 3.5.2 :: Anaconda 4.2.0 (64-bit)
OS and version:    Win 7 x64
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

## Actual behavior
```
from IPython.display import Latex
Latex('''The mass-energy equivalence is described by the famous equation

$$E=mc^2$$

discovered in 1905 by Albert Einstein.
In natural units ($c$ = 1), the formula expresses the identity

\\begin{equation}
E=m
\\end{equation}''')
```
print same text to console.

if i use:
```
import sympy as sym
from sympy import init_printing
init_printing(forecolor='White') 
x = sym.symbols('x')
from IPython.display import display
display(integ)
```
render LaTeX normal, but always on white background.
## Expected  behavior
print rendered LaTeX
## Steps to reproduce:  
-  
-

**Comment by Cody-Duncan** [comment]
Can confirm this reprodues in 
VS Code Version: 1.9.1
Python Version: 3.6
OS: Windows 10

The bug title should be more clear that the IPython/Juptyer output window does not render Latex output.

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/vscodeJupyter#13
