### ISSUE TITLE
Debug Consoles

### ISSUE THREAD

**Issue by claytoncarney** [DonJayamanne/pythonVSCode#586]
## Environment data
VS Code version:  1.8.0
Python Extension version:  0.5.5
Python Version:   3.5.2
OS and version:    Win10 Home 64-bit

Two potential issues:

ONE: The default launch.json file has `"cwd": "null"` for both the 'Integrated Terminal/Console' and the 'External Terminal/Console' configuations. IME this does not work. Integrated fails with 'The system cannot find the path specified.'. External fails with 'Debug adapter process has terminated unexpectedly'. Changing to `"cwd": null` or `"cwd": "${workspaceRoot}"` fixes both problems. Intellisense suggests `(leave null)`. Appears the default launch.json file is being creating with `"cwd": "null"` rather than `"cwd": null`.

TWO: In the 'Python' configuration, the Debug Console appears to be adding an additional newline to every print statement. This issue is not observed in the Integrated or External Consoles.

![image](https://cloud.githubusercontent.com/assets/1275536/21251055/9ef34e30-c307-11e6-9eb3-903150863cdd.png)

![image](https://cloud.githubusercontent.com/assets/1275536/21251169/c274a704-c308-11e6-94c8-f0cd8d78fecc.png)

**Comment by tonka3000** [comment]
I have the same problem with the newlines. It only appears in the `Debug Console` from vs.

**Comment by DonJayamanne** [comment]
Part One has been fixed.
The second issue with regards to additional new lines is an upstream issue (in VS Code), see below:
https://github.com/Microsoft/vscode/issues/17526

**Comment by tonka3000** [comment]
ok, good to know.
thx @DonJayamanne
