### ISSUE TITLE
autocomplete for parameters is not working

### ISSUE THREAD

**Issue by pchomik** [DonJayamanne/pythonVSCode#587]
## Environment data
VS Code version:  1.8.0
Python Extension version:  0.5.5
Python Version:   2.7.12
OS and version:    Ubuntu 16.04

Your settings.json:   
```
    "python.pythonPath": "/home/user/.pyenv/shims/python",
    "python.linting.pep8Enabled": true,
    "python.linting.pep8Path": "/home/user/.pyenv/shims/pep8",
    "python.linting.pylintPath": "/home/user/.pyenv/shims/pylint",
    "python.unitTest.pyTestPath": "/home/user/.pyenv/shims/py.test",
    "python.unitTest.pyTestEnabled": true,
    "python.linting.pep8Args": ["--max-line-length=150"],
    "python.linting.pylintArgs": ["--disable=W0221,I0011,E0401,E1101,E0633,C0301,C0111,C0325"],
    "python.autoComplete.addBrackets": true,
```   

## Actual behavior

I wrote such code as example:
```
class A(object):
    def do_something(self, param1, param2="default"):
        pass

class B(object):
    def do_something(self, )
```
In current state autocomplete is working for do_something method but not for arguments.

## Expected  behavior

Method and method arguments should be available via autocomplete popup window.

## Steps to reproduce:  

Type above code.

**Comment by DonJayamanne** [comment]
@pchomik 
I don't understand why you would expect parameter auto complete to popup when you type ```def do_something(self, ...)```

Please let me know what code you are typing exactly (where is the cursor located) to replicate this issue. From what you'd told me I don't see the need for any auto completion.

If you do, then please raise this issue in the [Jedi library](https://github.com/davidhalter/jedi)

**Comment by pchomik** [comment]
@DonJayamanne you are right. I provided wrong example. I will try to fix example and explain where is the problem.

Example:
```
class Parent(object):
    def do_something(self, param1, param2="default"):
        pass

class Child1(Parent):
    def do_<cursor>

class Child2(Parent):
    def do_something(self,<cursor>
```

Autocomplete logic is working for Child1 when I'm typing "def do_". Autocomplete window popups and method do_something is available there.
I'd like to have something similar for parameters (Child2 example). I'd like to see similar window after typing "def do_something(self,". At least name of available parameters should appear. 

Is it clear now?

**Comment by pchomik** [comment]
@DonJayamanne could you reopen this issue?

**Comment by DonJayamanne** [comment]
Unfortunately this is a feature that would have to be added in the Jedi library
The sample you have provided for Jedi is for the invocation of the ```strftime``` method. However what you require is intellisense for the definition and not for the invocation.
Leaving it closed.
