### ISSUE TITLE
Option "Run test" and "Debug test" should be located above decorators

### ISSUE THREAD

**Issue by pchomik** [DonJayamanne/pythonVSCode#588]
## Environment data
VS Code version:  1.8.0
Python Extension version:  0.5.5
Python Version:   2.7.12
OS and version:    Ubuntu 16.04

Your settings.json:   
```
    "python.pythonPath": "/home/user/.pyenv/shims/python",
    "python.linting.pep8Enabled": true,
    "python.linting.pep8Path": "/home/user/.pyenv/shims/pep8",
    "python.linting.pylintPath": "/home/user/.pyenv/shims/pylint",
    "python.unitTest.pyTestPath": "/home/user/.pyenv/shims/py.test",
    "python.unitTest.pyTestEnabled": true,
    "python.linting.pep8Args": ["--max-line-length=150"],
    "python.linting.pylintArgs": ["--disable=W0221,I0011,E0401,E1101,E0633,C0301,C0111,C0325"],
    "python.autoComplete.addBrackets": true,
```   

## Example

![image](https://cloud.githubusercontent.com/assets/1779381/21257195/053ef648-c377-11e6-9bbd-cd06e7350d8a.png)

## Actual behavior

Red rectangle in example

## Expected  behavior

Green rectangle in example

## Steps to reproduce:  

Please use code from example. 
In current implementation decorator and test look like two separate parts. In case of many tests this is problematic for me. Could you move "Run test" and "Debug test" above decorators?

**Comment by DonJayamanne** [comment]
Agreed

**Comment by DonJayamanne** [comment]
todo: hint, check if line above starts with @

**Comment by DonJayamanne** [comment]
@pchomik I have decided to leave this as is, because of the current behavior in Visual Studio. There too the codelense is displayed in a similar manner, at least in the case of .NET languages and unit tests. (I'd like for this to be consistent with Visual Studio IDE)
