### ISSUE TITLE
Extension failed to load with "Error. Error. Python spawn ENOENT" until you set the path

### ISSUE THREAD

**Issue by markdall** [DonJayamanne/pythonVSCode#59]
After installing this extension for vscode I got the error message in the title. The fix was to click File, Preferences, User Settings, and set my python path like so: 
```
// Place your settings in this file to overwrite the default settings
{
    // Path to Python, you can use a custom version of Python by modifying this setting to include the full path.
	"python.pythonPath": "c:\\python27\\python.exe"
}
```
It'd be great if this requirement were somehow more clear, like an instruction when you download it or something.

(Thanks for the awesome extension!)

**Comment by wolf99** [comment]
AFAICT this is still not mentioned in the readme... It would save a a whole pile of confusion if it was...
