### ISSUE TITLE
Start without debugging not ending

### ISSUE THREAD

**Issue by tonyedgecombe** [DonJayamanne/pythonVSCode#591]
## Environment data
VS Code version:  1.8.0
Python Extension version:  0.5.5
Python Version:   3.5.2
OS and version:    Windows 10
Your launch.json (if dealing with debugger issues):  
```
    {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
ctags --options=C:\Users\tonyedgecombe\.vscode\extensions\donjayamanne.python-0.5.5\resources\ctagOptions --languages=Python -o tags .
```

## Actual behavior

If I start without debugging (Ctrl+F5) the program runs but doesn't end, I need to manually click on the stop button. Each time I run like this it leaves another VSCode process running that doesn't close until I completely exit VSCode. Shift-F5 doesn't stop the program either, only clicking on the stop button.

![start_without_debugging](https://cloud.githubusercontent.com/assets/503569/21286503/b5120b2e-c44d-11e6-9d54-12d8d3581d94.png)

**Comment by ladevan** [comment]
Found the same issue also.

**Comment by JSONMartin** [comment]
Any updates on this? I'm also running into the same issue.

**Comment by bondsbw** [comment]
Same here.

**Comment by samedi2k** [comment]
@DonJayamanne: first of all - many thanks for this great extension.

Regarding this issue: i face the same problem, that programs do not terminate when started without debugger (CTRL-F5). I'm a bit wondering why this issue is pending such a long time. Starting programs with debugger (F5) takes much more time. Not in every case somene wants to start a debugger session after some small changes, but just watch the program running. Would you mind increasing priority for this issue? Shouldn't be a big deal to solve.

**Comment by DonJayamanne** [comment]
Sorry, but I am busy trying to solve a few other issues. I had a very brief look at this some time ago and couldn't figure out our, then again, I agree with you, it must be something very simple.

Will give look into this once again, please do drop another reminder if you don't see any update in a week.

**Comment by stuartaw** [comment]
Just dropping another reminder as requested :) Sorry am seeing the same effect here it is a quite annoying to say the least..
I am also seeing that breakpoints cannot be put in an execfile loaded section, however that is a core python debugger issue and not surprising  I suspect so I'm not even filing it..

**Comment by solidxsnake** [comment]
One more reminder here... This happens even if the program itself ends (e.g. I have a console app, I exit it and the terminal returns to a shell prompt, but the debugger toolbar still appears as if the program is still running). Running with debug works just fine; when the program exits, the debugger toolbar disappears (however I get a "Debug adapter process has terminated unexpectedly" without fail).

**Comment by kadung** [comment]
One more kindly reminder. Hope to here your good news soon since it is very annoying issue.

**Comment by jsonMartin** [comment]
+1 to this issue...I don't know enough about Python debugging or the code base to submit a PR to fix this issue.

Would love if someone could figure this out! 🙏

**Comment by elenfant** [comment]
Yet another reminder. Anyway, thanks for the plugin!

**Comment by DonJayamanne** [comment]
Closing in favor of https://github.com/Microsoft/vscode-python/issues/35
