### ISSUE TITLE
mypy linter does not show errors for typed imports

### ISSUE THREAD

**Issue by moopling** [DonJayamanne/pythonVSCode#592]
## Environment data

VS Code version:  1.8.0
Python Extension version:  0.55
Python Version:   3.5.2
OS and version:    Windows 10
Your launch.json (if dealing with debugger issues):  
```json
```   
{
    "python.pythonPath": "C:/PROGRA\~1/Anaconda3/python.exe",
    "python.linting.mypyPath": "C:/PROGRA\~1/Anaconda3/Scripts/mypy.bat",
    "python.linting.mypyEnabled": true,
    "python.linting.pylintArgs": ["--disable=missing-docstring"],
    "python.linting.mypyArgs": ["-s"],
    "window.zoomLevel": 0,
    "window.openFilesInNewWindow": false,
    "projectManager.openInNewWindow": false,
    "git.confirmSync": false,
    "python.formatting.provider": "yapf",
    "editor.cursorBlinking": "smooth",
    "python.formatting.formatOnSave": true,
    "editor.autoClosingBrackets": false,
    "files.autoSave": "onFocusChange",
    "python.unitTest.pyTestEnabled": true,
    "python.unitTest.pyTestPath": "py.test",
    "python.jupyter.appendResults": false
}
## Logs
Output from ```Python``` output panel  
None

Output from ```Problems``` output panel  
None

Output from ```Console window``` (Help->Developer Tools menu)
mypy p2.py:
p2.py: note: In function "main":
p2.py:5: error: Argument 1 to "add" has incompatibl
e type "str"; expected "int"
p2.py:5: error: Argument 2 to "add" has incompatibl
e type "str"; expected "int"

## Actual behavior
When importing functions with type annotation mypy linter does not report errors that may occur.

## Expected  behavior
The problems pannel to show the same behaviour as calling mypy from the command line.

## Steps to reproduce:  
Write a function in one file with type annotations, import it in another file. Use with invalid types.

**Comment by DonJayamanne** [comment]
Please upload your p2.py code file

**Comment by moopling** [comment]
[problem_example.zip](https://github.com/DonJayamanne/pythonVSCode/files/659787/problem_example.zip)

**Comment by DonJayamanne** [comment]
Please reopen if problem persists.

**Comment by mboujonnier** [comment]
Hi,

Is it really fixed ?
I have the same problem with VSCode 1.25.1, mypy linter doesn't detect the type errors as detected using the command line.

Thanks
