### ISSUE TITLE
'Run Test' on TestCase class does not recognise test methods when using nose

### ISSUE THREAD

**Issue by rkaramc** [DonJayamanne/pythonVSCode#597]
## Environment data
VS Code version:  1.9.0-Insider
Python Extension version:  0.5.5
Python Version:   3.5.2
OS and version:    macos sierra 10.12.2beta
Your settings.json:   
```json
{  "python.unitTest.nosetestArgs": [
    "--with-xunit",
    "--xunit-file=${workspaceRoot}/nosetests.xml"
  ],
  "python.unitTest.nosetestsEnabled": true
}
```   
## Logs
Output from ```Python``` output panel  
```
E
======================================================================
ERROR: Failure: ValueError (No such test tests.test_class.TestABC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/____/anaconda/envs/microsvc/lib/python3.5/site-packages/nose/failure.py", line 42, in runTest
    raise self.exc_class(self.exc_val)
ValueError: No such test tests.test_class.TestABC

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
```   

## Actual behavior
For the below test class, clicking 'Run Test' on the class fails with the above message. Nose is unable to recognise the two test methods included in the class.

```python
# tests/test_class.py
class TestABC(TestCase):
    """ testing """

    def test_ok(self):
        """ testing """
        self.assertTrue(1 == 1)

    def test_not_ok(self):
        """ testing False """
        self.assertFalse(1 == 2)
```
## Expected  behavior
Clicking 'Run Test' for the class should run the two test methods test_ok and test_not_ok.

## Steps to reproduce:  
-  create a test class as above
-  click on the 'Run Test' link for the class TestABC

**Comment by rkaramc** [comment]
btw, this works with unittest - am able to run all test methods in a testcase class by clicking 'run test'.

**Comment by DonJayamanne** [comment]
@rkaramc 
Apologies for the delay will look into this, this week.

**Comment by JeffZen** [comment]
I am also running into this problem. I can execute all my tests from command line but for some reason in VS Code they do not all get picked up. My Test Log shows nose.selector as the last method called and does not go over to nose.plugins.collect

**Comment by DonJayamanne** [comment]
@JeffZen please could you provide a code sample (folder structure and tests, asking with your vscode workspace settings.Json).

**Comment by efremovd** [comment]
I hit it too and this is what I've found so far about this issue:

extension calls nosetests with argument like this
```
nose.core: DEBUG: Test names are ['tests/test_cardholder.py:tests.test_cardholder.TestBasicCardholder']
```
and nosetests can't find such test and complains about. 

When I try to run from command line like this:
```
nosetests tests/test_cardholder.py:tests.test_cardholder.TestBasicCardholder
```
I'm getting the same complain as with run from extension

but if I run like this:
```
nosetests tests.test_cardholder.TestBasicCardholder
```
it works as expected.

I looked into code a little and I think problem is in pythonVSCode\src\client\unittests\nosetest\collector.ts in method parseNoseTestModuleCollectionResult
```typescript
        if (line.startsWith('nose.selector: DEBUG: wantClass <class \'')) {
            let name = extractBetweenDelimiters(line, 'nose.selector: DEBUG: wantClass <class \'', '\'>? True');
            const testSuite: TestSuite = {
                name: path.extname(name).substring(1), nameToRun: fileName + `:${name}`,
                functions: [], suites: [], xmlName: name, time: 0, isUnitTest: false,
                isInstance: false, functionsFailed: 0, functionsPassed: 0
            };
            testFile.suites.push(testSuite);
            return;
        }
```
As you can see nameToRun here is `filename +':${name}'` and looks like this variable got passed as arg to nosetests. So my guess it should be just `${name}`.

I hope this helps, can't verify since have no env set to try.

**Comment by DonJayamanne** [comment]
Thanks for the code sample and digging into this, will look into this soon.
