### ISSUE TITLE
Cannot Disable Formatting

### ISSUE THREAD

**Issue by tills13** [DonJayamanne/pythonVSCode#599]
## Environment data
VS Code version:  1.8.1 Recovery Build
Python Extension version:  
Python Version:   
OS and version:  OS X

Your settings.json:
```json
    "python.formatting.provider": "yapf", <-- why can I not set this to null?
    "python.formatting.formatOnSave": false,
    "editor.formatOnType": false,
    "editor.formatOnSave": true <-- I need this for other formatters to work
```   

## Actual behavior
* incessant nagging about yapf and/or autopep8

## Expected  behavior
* none - it should not bother me about formatters

## Steps to reproduce:  
-  install plugin
-  be nagged

**Comment by DonJayamanne** [comment]
Fix will be in the next release, please add the following into your settings.json file:     
```json
"python.formatting.provider" :"none"
```

**Comment by tills13** [comment]
thank you
