### ISSUE TITLE
Custom module search path configurations

### ISSUE THREAD

**Issue by bgse** [DonJayamanne/pythonVSCode#6]
For projects that aren't python-only, assume a structure like this:

project/
project/lib1/
project/lib1/mod1/ <-- module
project/lib1/mod2/ <-- module
project/lib2/
project/lib2/mod3/ <-- module

Additionally, being able to add to search path relative (but outside) project folder would be great.

**Comment by DonJayamanne** [comment]
Hi, the new build should fix this issue. You can add your custom paths as follows in the settings files.
FYI - you can add multiple paths as this setting takes an array of paths.
"python.autoComplete.extraPaths": ["/usr/local/google_appengine"]

Please test and let me know.

**Comment by bgse** [comment]
From a quick glance, it appears to work fine. Could only do some quick testing on windows machine though which I'm not really used to.

Absolute paths worked without issues, is there a way to use supply paths relative to the workspace too?

**Comment by frecio231** [comment]
Hello, how I can set-up the extraPaths to work with blender libraries (e.g bpy, bge...)?

**Comment by DonJayamanne** [comment]
Hi, i haven't useed Blender libraries. But all you need to do is configure the paths for auto-complete, pointing to the paths where the libraries/modules are located.

**Comment by DonJayamanne** [comment]
Hi bgse, I have now added support for relative paths in the latest build. Please test and let me know.
I have tested it and it works as expected.

**Comment by bgse** [comment]
@DonJayamanne Works like a charm, thanks a lot. Closing the issue as this is fully resolved.
