### ISSUE TITLE
Support pytest as unit test option

### ISSUE THREAD

**Issue by martinpengellyphillips** [DonJayamanne/pythonVSCode#60]
Would be great to have support for pytest (http://pytest.org/latest/) in addition to unittest and nosetest.

**Comment by DonJayamanne** [comment]
Thanks for the suggestion, will look into this.

**Comment by DonJayamanne** [comment]
@martinpengellyphillips  Available in the latest build. Thanks @aschlapsi

**Comment by martinpengellyphillips** [comment]
Thanks!
