### ISSUE TITLE
Execute in Terminal: please add error highlighting and support for problem matcher

### ISSUE THREAD

**Issue by danil-tolkachev** [DonJayamanne/pythonVSCode#600]
`Run Python File in Terminal` is very useful command. It would be more convenient to use it for quick fix error in python script if there were error highlihting and Problem Matcher integration.

Here is part of Task Runner config for that purpose. However I don't know how to use it with `Run Python File in Terminal` command.

```json
"problemMatcher": {
    "fileLocation": "absolute",
    "pattern": [
        {
            "regexp": "File \"(.*)\", line (\\d+)",
            "file": 1,
            "line": 2
        },
        {
            "regexp": ".*"
        },
        {
            "regexp": "(.*Error:.*)",
            "message": 1
        },
    ]
}
```

**Comment by DonJayamanne** [comment]
Error highlighting and problem matching is not supported in the terminal today.  
This is due to limitations of the terminal (i.e. such API isn't exposed to the authors of extensions).

**Comment by hendrics** [comment]
@DonJayamanne i don't think this is about integrating the terminal, but rather scanning the errors and highlighting them in the browser... can this be reopened please?

**Comment by DonJayamanne** [comment]
Again scanning the output of the terminal is not supported.
