### ISSUE TITLE
Autocompletion Stopped Working After Upgrading to Python 3.6

### ISSUE THREAD

**Issue by moigagoo** [DonJayamanne/pythonVSCode#601]
## Environment data
VS Code version:  1.9.0-insider
Python Extension version:  0.5.5
Python Version:  3.6.0
OS and version:  Windows 10, build 14986
Your settings.json:   
```json
// Place your settings in this file to overwrite default and user settings.
{
    "python.pythonPath": "C:\\Users\\moigagoo\\path\\to\\my_project\\.venv\\Scripts\\python.exe"
}
```
## Logs
Output from ```Python``` output panel  
```
##########Linting Output - pylint##########
************* Module namer
40,0,error,E0401:Unable to import 'yaml'
44,0,convention,C0111:Missing function docstring
52,0,convention,C0111:Missing function docstring
54,61,error,E1101:Module 're' has no 'MULTILINE' member
61,0,convention,C0111:Missing function docstring
65,0,convention,C0111:Missing function docstring
68,0,convention,C0111:Missing function docstring
78,4,convention,C0111:Missing function docstring
85,27,convention,C0321:More than one statement on a single line
95,0,convention,C0111:Missing function docstring

No config file found, using default configuration

```   
Output from ```Console window``` (Help->Developer Tools menu)
```
extensionHost.ts:293 [Extension Host] Error (stderr) Traceback (most recent call last):
  File "preview\jedi\parser\__init__.py", line 56, in load_grammar
    return _loaded_grammars[path]
KeyError: 'preview\\jedi\\parser\\grammar3.6.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "completion.py", line 404, in watch
    self._process_request(self._input.readline())
  File "completion.py", line 374, in _process_request
    column=request['column'], path=request.get('path', ''))
  File "preview\jedi\api\__init__.py", line 130, in __init__
    self._grammar = load_grammar(version='%s.%s' % sys.version_info[:2])
  File "preview\jedi\parser\__init__.py", line 58, in load_grammar
    return _loaded_grammars.setdefault(path, generate_grammar(path))
  File "preview\jedi\parser\pgen2\pgen.py", line 393, in generate_grammar
    p = ParserGenerator(filename)
  File "preview\jedi\parser\pgen2\pgen.py", line 18, in __init__
    stream = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: 'preview\\jedi\\parser\\grammar3.6.txt'

```

## Actual behavior
Autocompletion doesn't work, no suggestions are shown after ".", installed modules are not detected, not existing errors are highlighted ("[pylint] E1101:Module 're' has no 'MULTILINE' member").

## Expected  behavior
Autocompletion and suggestions should work the same way as with python 3.5.2, modules from the current virtualenv should be importable, no false positives should be reported.

## Steps to reproduce:  
-  Install Python 3.6 (I did with `scoop install python`, the same way as always)
-  Open any Python file and hit Ctrl+S to invoke jedi and pylint.

**Comment by moigagoo** [comment]
Looks like a Jedi issue, reported it https://github.com/davidhalter/jedi/issues/820

**Comment by moigagoo** [comment]
I just copied grammar3.5.txt to grammar3.6.txt in ~\.vscode-insiders\extensions\donjayamanne.python-0.5.5\pythonFiles\preview\jedi\parser and autocompetion worked again. Pylint still argues it can't import modules and that re doesn't have MULTILINE member, but it's more or less fine, and it's probably a different issue.

**Comment by skovmand** [comment]
+1

**Comment by reaCodes** [comment]
+1

**Comment by andresgottlieb** [comment]
I'm having the same behavior with:

VS Code version: **1.8.1**
Python Extension version: **0.5.5**
Python Version:  **3.6.0**
OS and version:  **macOS Sierra 10.12.2**

**Comment by feliperyan** [comment]
Yep same here on Windows 10 | Python 3.6 | VSC 1.8.1 - No intellisense at all

**Comment by moigagoo** [comment]
The Pylint issue I mentioned in the original report can't be solved or worked around so far—Pylint officially doesn't support Python 3.6 yet: https://github.com/PyCQA/pylint/issues/1241

I just disabled Pylint and enabled Flake8 instead.

**Comment by Satak** [comment]
+1

**Comment by pauis** [comment]
+1 on Windows 10 Hone, 10.0.14393

**Comment by SarthakYadav** [comment]
+1 on Antergos (Arch) Linux, VSCode 1.8, Python 3.6

**Comment by aleksey-su** [comment]
+1

VS Code version: 1.8.1
Python Extension version: 0.5.5
Python Version: 3.6.0
OS and version: Windows 7

**Comment by ericloong90** [comment]
To continue on @moigagoo comment on changing grammar3.5.txt to grammar3.6.txt. Here's same path if you're on Mac OSX.

~/.vscode/extensions/donjayamanne.python-0.5.5/pythonFiles/preview/jedi/parser

**Comment by pauis** [comment]
On windows:
C:\Users\<USERNAME>\.vscode\extensions\donjayamanne.python-0.5.5\pythonFiles\preview\jedi\parser

**Comment by moigagoo** [comment]
Jedi added the new grammar and resolved the issue https://github.com/davidhalter/jedi/issues/820

They haven't cut a new release yet, but your can install Jedi directly from GitHub with `pip install git+https://github.com/davidhalter/jedi`
