### ISSUE TITLE
Code completion fails if jedi generates stdout

### ISSUE THREAD

**Issue by martinfiers** [DonJayamanne/pythonVSCode#602]
## Environment data
VS Code version:  1.8.1 until 1.9.1
Python Extension version: 0.5.5 until 0.5.8
Python Version:   2.7
OS and version:   Windows 10 

## Actual behavior

If, for some reason, jedi generates stdout, the code completion will not work anymore for the active VS Code session.

The problem is that the stdout is read by the client\providers\jediProxy.js , and jediProxy.js does not know how to interprete this.

## Expected behavior

Code completion still works in spite of jedi generating stdout.

## Discussion

In theory, if jedi is supposed to do static analysis, it should not import modules, and hence, not execute print statements which may be in the package. And I agree that normally importing a module should not generate any stdout, but in this case it does. 

## Steps to reproduce:  

It's difficult to reproduce because the package is part of a commercial product, and it's pretty complicated to find out why the printing actually occurs (it occurs in a C extension if that matters).

**Comment by martinfiers** [comment]
Ok I was able to find the actual problem: it was actually not related to the number of items. It was related to jedi somehow executing some of the code in our module (not sure yet why, I thought it only did static analysis), causing some output to be generated to stdout. That output got mixed with the other output which ``completion.py`` is supposed to generate, and hence it confused jediProxy.js.

It would be nice though if some exception handling could be put into jediProxy.js, to recover from this possible erroneous behavior. 

I changed the title to avoid confusion and keep the issue tracker clean.

**Comment by martinfiers** [comment]
@DonJayamanne do you have any opinions on this? Today I modified the story to reflect the current status of my findings (which is a more accurate description).

My workaround now is to redirect stdout to /dev/null, import the offending package, and then put back stdout. But that's of course not really desirable :)

Perhaps in your experience you have ideas on why jedi generates stdout, or you know of a quick fix in your extension that doesn't mean making any further assumptions.

**Comment by DonJayamanne** [comment]
I will modify the extension to make it more robust and handle such cases, thanks for the excellent research and explanation.

**Comment by martinfiers** [comment]
Hey,

Thank you very much for looking into this! If I can help testing, let me know.

Kind regards,

**Comment by DonJayamanne** [comment]
@martinfiers 
Please could you provide me with the sample code (and instructions) to replicate this issue.  
I'd like to look into this.

**Comment by martinfiers** [comment]
Hello Don,

Thanks very much for looking into it. It is very hard to reproduce, because it happens when Jedi is generating stdout (which shouldn't happen if it's statically analyzing, anyway - which I don't fully understand yet). Until now I haven't found exactly when this happens. It happens in one of our proprietary C extensions, so it's tough to reproduce. I'll try to find a way to reproduce it.

The workaround I used now was (in completion.py):

    class RedirectStdout(object):
        def __init__(self, new_stdout=None):
            """If stdout is None, redirect to /dev/null"""
            self._new_stdout = new_stdout or open(os.devnull, 'w')

        def __enter__(self):
            sys.stdout.flush()
            oldstdout_fno = self.oldstdout_fno = os.dup(sys.stdout.fileno())
            os.dup2(self._new_stdout.fileno(), 1)

        def __exit__(self, exc_type, exc_value, traceback):
            self._new_stdout.flush();
            os.dup2(self.oldstdout_fno, 1)
      
And then pre-loading the offending package:

    with RedirectStdout():
        import package_causing_stdout

(but that's of course just solving a symptom and not scalable :) )

**Comment by martinfiers** [comment]
Ah! I found a way to reproduce after quite some debugging!

0. Start an empty vs code python project

1. Make a file my_module.py, containing a print statement and a function:

        print("Loading my_module")
        def my_func(): 
            return 1

2. Make a second file in the same folder, test_module.py, which imports my_module.py.

        import my_module
        my_module.  # will do code completion and show my_func
    
3. Execute test_module.py, so that a my_module.pyc is generated.
4. Remove my_module.py
5. Restart vs code
6. Load vs code, open test_module.py.
7. Try to do a code completion. It will fail. In fact, all code completion will fail from now on.

The reason is that jedi will actually import non-py files (in my case that was a compiled module, but a pyc file will also do). During import, a print statement is executed, which then messes up the client/server for code completion (proxyJedi.ts/completion.py).

I thought I would be able to use ``python.autoComplete.preloadModules`` to preload the offending module (note that I needed a fix, see my comment in #581), but also there, the print statement will be captured by proxyJedi.ts.

One workaround could be to also RedirectStdout around the jedi.preload_module statement, but still I think it's not a robust solution because it would only work for known modules that do printing. @DonJayamanne  can you reproduce this?

**Comment by martinfiers** [comment]
@DonJayamanne any update on this? Is there anything more I can provide to reproduce the problem? Thanks!

**Comment by DonJayamanne** [comment]
Oh no, nothing, just requires a major code change in my post, will try to squeeze this in for third months release.

**Comment by martinfiers** [comment]
Ok, thanks for the heads-up. Let me know if you need a tester.

**Comment by DonJayamanne** [comment]
Thanks, hopefully I can have this done this week.

**Comment by martinfiers** [comment]
Hello @DonJayamanne . In the meanwhile I think I have found a more robust fix. Basically, by redirecting all stdout of jedi during the execution of the main watch loop, and ensure only the properly formatted output is sent to stdout. 

A way to implement this could be:

(in completion.py)

```python
    def watch(self):
        while True:
            try:
                rq = self._input.readline()
                if len(rq) == 0:
                    # Reached EOF - indication our parent process is gone. 
                    sys.stderr.write('Received EOF from the standard input,exiting' + '\n')
                    sys.stderr.flush()
                    return
                with RedirectStdout():
                    response = self._process_request(rq)
                self._write_response(response)
```

This assumes self._process_request returns the string, instead of calling self._write_response itself. This way, you can redirect any accidentally generated stdout to /dev/null, and then write the actual response to stdout.

I tested this on the latest version of the plugin (0.6.5) and it works. (BTW not sure what has changed in the meanwhile, it looks like you did a large refactoring, but I can't directly see how this impacts this work).

**Comment by DonJayamanne** [comment]
Thanks a lot for your help. Simple elegant solution. Thanks, will release a new version soon.
