### ISSUE TITLE
Error: Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by egamma** [DonJayamanne/pythonVSCode#603]
_From @shashi-netra on December 24, 2016 22:49_

- VSCode Version:V 1.8.1
- OS Version: macOS Sierra 10.12.2

> "Error: Debug adapter process has terminated unexpectedly"

Steps to Reproduce:

1. Trying to build any file gives me the above error. It was working fine earlier.
2. I have the following extensions installed: MagicPython,Python, Python for VSCode and SublimeText Keymap.

_Copied from original issue: Microsoft/vscode#17804_

**Comment by egamma** [comment]
@shashi-netra 

>Trying to build any file gives me the above error. It was working fine earlier.

Can you explain what you mean by `build any file`. The error message comes from a debugger, so do you see the message when debugging?

What files are you working on when this happens? From the list of extensions you have installed it looks like you are using VS Code for Python development?

**Comment by egamma** [comment]
_From @shashi-netra on December 25, 2016 15:42_

I get the error when I try to run any python script even a simple one as shown in this screencast. I see the error message in a message box at the top.
http://g.recordit.co/O0VSOnZzJl.gif

p.s. yes I am using it for Python development

**Comment by egamma** [comment]
@shashi-netra thanks for the recording it helps to clarify the issue. Python debugging is contributed by the Python extension and I'm moving the issue to corresponding issues repository.

**Comment by shashi-netra** [comment]
OK not sure if this is really a fix, but I got it working by uninstalling VScode and reinstalling it.

**Comment by DonJayamanne** [comment]
@shashi-netra
- Please could you try debugging a simpler python file with the following code:
```python
x = 1
y = 2
z = x + y
print(z)
```

- Next, please could you also provide the following information:  
    + OS version  
    + Python version  
    + Contents of settings.json   
    + Contents of launch.json

**Comment by shashi-netra** [comment]
@DonJayamanne I was able to "fix" it by uninstalling VS code and reinstalling it. VSC works fine now.
