### ISSUE TITLE
Highlighting not working when calling functions inside f-strings

### ISSUE THREAD

**Issue by Satak** [DonJayamanne/pythonVSCode#604]
## Environment data
VS Code version:  1.8.1
Python Extension version:  0.5.5
Python Version:   3.6
OS and version:    Windows 10

## Actual behavior
Python 3.6 f-strings are not properly highlighted if {} have function call inside.

OK:
`f'{name}'`
Not OK: 
`f'{function_name(name)}'`

## Expected  behavior
Expected to highlight everything inside {} the same
## Steps to reproduce:  
-  create function
-  call it inside f-string f'{function_name(name)}'

**Comment by Satak** [comment]
Same thing for dictionaries if you get value, it doesn't highlight it correctly
`f"{person['firstname']}"`

**Comment by DonJayamanne** [comment]
Syntax highlighting isn't provided by this extension. It is part of vscode. You might want to try and install the magic python extension. If that doesn't work please report an issue on thier [repo](https://github.com/MagicStack/MagicPython)
