### ISSUE TITLE
Suggestion: Add better support for ipython cell mode

### ISSUE THREAD

**Issue by talkaminker** [DonJayamanne/pythonVSCode#606]
This is a suggestion to add better support for cell execution mode.
Currently the cell execution mode is a bit too simple
1) There should be a clear horizontal line separator between two cells (and then the Run Cell button should disappear)
2) the output panel should have a clear separator between two outputs, so that you could easily tell when a cell's output end and another cell output begins.
3) There should be a console in the output panel to allow small bits of code to be executed as if they where cells (like regular python console) with live auto-complete from the running ipython kernel.
Take a look a spyder to see what I mean:
![spyder](https://cloud.githubusercontent.com/assets/13932998/21520065/48e4e10a-ccfa-11e6-852f-a7b290f8605e.jpg)

Also, Great plugin!

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/vscodeJupyter#11
