### ISSUE TITLE
Can we django debug without --noreload?

### ISSUE THREAD

**Issue by evaldobratti** [DonJayamanne/pythonVSCode#608]
Can we django debug without `--noreload` option, so we can develop, type and debug without need to restart?

~~And, can we launch django without debug in vs code, like, just launch, with reload and no debugging, so I don't have to open a terminal just for it?~~
EDIT: just discovered I can launch a terminal inside vs code

Thank you, your extension is really awesome so far.

**Comment by DonJayamanne** [comment]
Yes, this is possible, and will require quite a lot of work with the debugger.  
Unfortunately that's a few weeks/months away.

**Comment by DonJayamanne** [comment]
Will keep you posted when I start working on it.

**Comment by DonJayamanne** [comment]
Currently the debugger (PTVSD) I'm using in the extension doesn't support debugging without ```--noreload```.

**Comment by pcannons** [comment]
@DonJayamanne Any update on this? In a world of hot reloading React, etc. it's definitely something that would be awesome to have for Django.
