### ISSUE TITLE
can't use the virtualenv python

### ISSUE THREAD

**Issue by fakegit** [DonJayamanne/pythonVSCode#61]
My system is win7 x64.
I have made the config in the settings.json and launch.json files as bellow.
settings.json file
`"python.pythonPath": "C:/Users/Administrator/.virtualenvs/python27/Scripts/python.exe",`

launch.json file
`"pythonPath": "C:/Users/Administrator/.virtualenvs/python27/Scripts/python.exe",`

But it didn't work.
what should i do?

**Comment by DonJayamanne** [comment]
Please could you tell me what error you are getting?

**Comment by fakegit** [comment]
@DonJayamanne It still use the default python version.

I have installed the geoip module in the virtuanlenv python27. But when CTRL+SHIFT+B to run some code, I get this:
`Traceback (most recent call last):
  File "e:\Downloads\lantern\manage\helper\utils.py", line 11, in <module>
    from geoip import geolite2
ImportError: No module named geoip`

**Comment by arjamizo** [comment]
Did you get it done?

**Comment by fakegit** [comment]
Not work.

**Comment by DonJayamanne** [comment]
Hi, i've just tried this and it works as expected. 
Please could you confirm that the geoip module has been installed in the right virtual environment.

**Comment by DonJayamanne** [comment]
Also, please could you try to debug a separate python file within the same project with the following contents:
```python
print sys.prefix
```

**Comment by DonJayamanne** [comment]
@fakegit , I have a simple suggestion that will prove to be quite simple when using VS Code with Python virtual envs.

The suggestion is as follows:
1. Clear all of the custom python paths in the settings.json (leave it to their defaults) and close VS Code
2. Open your terminal (command) window and activate the relevant python environment
3. Next, launch VS Code from that terminal (command window) session

Now, VS Code will inherit the environment variables (settings) configured for that particular Python Virtual Environment and everything should work as expected.
Please let me know how this goes.

**Comment by fakegit** [comment]
@DonJayamanne Sorry for not replying as soon as possible. I uninstall all my python and virtualenvs, and try to use the conda, it works.

**Comment by DonJayamanne** [comment]
Thanks for getting back
