### ISSUE TITLE
SQLite3 not supported?

### ISSUE THREAD

**Issue by dbaeumer** [DonJayamanne/pythonVSCode#611]
_From @DanJ210 on December 30, 2016 0:52_

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14986
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-css-formatter|aeschli|0.0.2|
|vs-code-css-comments|ashhitch|1.0.2|
|vscode-icontheme-nomo-dark|be5invis|1.2.1|
|javadebugger|donjayamanne|0.0.2|
|python|donjayamanne|0.5.1|
|vscode-html-css|ecmel|0.0.30|
|javac-linter|faustinoaq|1.2.1|
|php-intellisense|felixfbecker|0.0.12|
|auto-close-tag|formulahendry|0.3.7|
|auto-rename-tag|formulahendry|0.0.9|
|code-runner|formulahendry|0.6.5|
|csharpextensions|jchannon|1.1.0|
|format-indent|Kasik96|1.3.0|
|format-php|Kasik96|1.1.2|
|ftp-sync|lukasz-wronski|0.3.2|
|cpptools|ms-vscode|0.9.3|
|csharp|ms-vscode|1.6.2|
|theme-railscasts|PaulOlteanu|1.0.0|
|material-icon-theme|PKief|1.1.5|
|vscode-icons|robertohuertasm|4.3.0|
|elise|schematrix|0.0.1|
|theme-tinaciousdesign|tinaciousdesign|0.1.1|

---

Steps to Reproduce:

1. Trying to use SQLite3 with PHP in the editor, everywhere says it's built in without any installation needed.
2. $test = new SQLiteDatabase; (Says Fatal Error: class not found)

What do we have to do to get this awesome DMB with its classes into VS code? Am I missing something?

_Copied from original issue: Microsoft/vscode#17919_

**Comment by dbaeumer** [comment]
This has to come from the Python extension (https://github.com/DonJayamanne/pythonVSCode). Moving.

**Comment by DanJ210** [comment]
@dbaeumer Thanks. I don't understand thought. This was moved and then closed? So is it supported or must it be supported(come from) python vscode?

**Comment by DanJ210** [comment]
In fact, I've already got this exact extension installed so how can I use SQLite3? I see no mention of it. I'm totally confused with what just happened if someone doesn't mind helping me understand please. Thank you very much :)

**Comment by DonJayamanne** [comment]
@dbaeumer  Not sure why this has been added to the Python extension, when @DanJ210 has mentioned that he's trying to use SQLite from PHP!
```
Trying to use SQLite3 with PHP in the editor
```
