### ISSUE TITLE
out/client/common/tags takes 41GB

### ISSUE THREAD

**Issue by iamaziz** [DonJayamanne/pythonVSCode#616]
## Environment data
VS Code version:  1.8.1 (1.8.1)
Python Extension version:  0.5.5
Python Version:   2.7
OS and version:    macOS 10.12

Hi there, I am not sure what is that, see screenshot below

![tags](https://cloud.githubusercontent.com/assets/3298308/21579437/3786e860-cf7d-11e6-8947-df637ff9e552.png)

**Comment by andrevoget** [comment]
I have the same problem, with the same VS Code version, Python version and macOS version.

**Comment by DonJayamanne** [comment]
You can disable the use of ctags by adding the following configuration into your settings.json file (either your workspace or user settings - user settings if you wish to disable this globally, which I believe is what you're after)

```json
"python.workspaceSymbols.enabled": true,
```

**Comment by iamaziz** [comment]
Great thanks a lot!
