### ISSUE TITLE
"Go to Definition" from a new class definition doesn't work when using import *

### ISSUE THREAD

**Issue by aullrich2013** [DonJayamanne/pythonVSCode#617]
## Environment data
VS Code version:  1.8.1
Python Extension version:  0.5.5
Python Version:   2.7.11
OS and version:    OS X 10.12.2
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
{}
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

## Actual behavior
"Go to Definition" of imported classes doesn't work from a definition of a new class. Example
```python
from myClasses import * # where BaseClass is defined
class MyNewClass(BaseClass): # clicking BaseClass >> go to definition does nothing
    pass
```

**Other Notes**
The issue goes away if you import BaseClass explicitly.
```python
from myClasses import BaseClass
``` 
The issue also isn't observed if BaseClass is used in the normal code. E.g. clicking on 
```python
BaseClass.classmethod(blah) # clicking on "BaseClass" >> Go to definition works from here
```

## Expected  behavior
It should take me to BaseClass's definition

## Steps to reproduce:  
-  Define a base class in one file
-  Import that file as shown above
-  Define a new class based on the other class
-  Attempt to "Go to Definition" on the base class and observe that it does nothing

**Comment by joshdurham** [comment]
This is a problem with jedi: https://github.com/davidhalter/jedi/issues/772
