### ISSUE TITLE
wrong output of variable in output window

### ISSUE THREAD

**Issue by ranjan-ranjan** [DonJayamanne/pythonVSCode#618]
VS Code version: 1.8.1 
Python Extension version: 0.5.5
Python Version: 3.6
OS and version: Windows 10 Pro 1607

I am debugging a python program as shown in the snapshot. I have output the result of `soup.title.string` in console window. The result is of the variable `soup`, not `soup.title.string`.
![1](https://cloud.githubusercontent.com/assets/16834561/21636468/db5555c2-d288-11e6-9bf8-4c23ba5a3b42.png)

**Comment by DonJayamanne** [comment]
@ranjan-ranjan Apologies for never getting back to you on this. 
This is correct, it is displaying the other memebers on thte string property.
Try the following:  
```python
print(dir(soup.title.string))
```

You'll see other members. Also, by default only the value ```Google``` is displayed. You have chosen to expand it to view its members.
