### ISSUE TITLE
Nicer marketplace banner

### ISSUE THREAD

**Issue by felixfbecker** [DonJayamanne/pythonVSCode#62]
I suggest you change the background color to the background color of the [python homepage](https://www.python.org/) (#1e415e) and use a [transparent, scalable official Python logo as SVG](https://www.python.org/static/community_logos/python-logo-generic.svg).

**Comment by felixfbecker** [comment]
Looks awesome imo!

**Comment by DonJayamanne** [comment]
Agreed
