### ISSUE TITLE
Intellisense not working with virtual environments in Mac OS

### ISSUE THREAD

**Issue by sh3lld00m** [DonJayamanne/pythonVSCode#620]
## Environment data
VS Code version:  1.8.1
Python Extension version:  0.5.5
Python Version:   2.7
OS and version:    Mac OS Sierra
Your launch.json (if dealing with debugger issues):  Does not apply

Your settings.json:   No workspace settings.json configured.
User settings.json as follows:
```
// Place your settings in this file to overwrite the default settings
{
  // Disable telemetry to MS 
    "telemetry.enableCrashReporter": false,
    "telemetry.enableTelemetry": false,
    //git disabled
    "git.enabled": true,
    "git.autofetch": false,
    // "editor.tabSize": 2,
    "jshint.enable": true,
    "editor.fontFamily": "Menlo",
    "editor.fontSize": 14,
    "editor.rulers": [80,120],
    "files.exclude": {
      "**/.git": true,
      "node_modules": true,
      "typings": true,
      "**/.DS_Store": true,
      ".vscode": true
    },
    // Open iTerm2 instead of Terminal app
    "terminal.external.osxExec": "iTerm.app",
    // Python specific configurations
    "python.formatting.provider": "autopep8",
    "python.linting.enabled": true
}
```

## Logs
Output from ```Python``` output panel  
```[pylint] E0401:Unable to import 'google.cloud'```

## Actual behavior
Pylint reports it's unable to import google.cloud, and VSCode does not provide intellisense on the package.

## Expected  behavior
There should be no pylint error messages and the functions and classes of the package should be picke up by VSCode.

## Steps to reproduce:  
1.- Setup a new workspace directory
```
$ mkdir workspace
```
2.- Using virtualenv, set up a new virtual environment there:
```
$ cd workspace; virtualenv venv
```
3.- Activate virtualenv
```
$ source venv/bin/activate
```
4.- Install Pylint and third party client library
```
$ pip install pylint
$ pip install --upgrade google-cloud-pubsub
```
5.- Open vscode from the workspace directory
```
$ vscode .
```
6.- Create a new python file and try to import from the recently installed package:
```python
from google.cloud import pubsub
```

Pylint throws the error detailed above.

**Comment by ehartford** [comment]
Same problem here.  I am in a virtual environment.

    $ pylint --version
    pylint 1.6.4,
    astroid 1.4.9
    Python 2.7.12 (default, Oct 11 2016, 05:20:59)
    [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]

I tried launching vscode with 

    open -a /Applications/Visual\ Studio\ Code.app

and 

    /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code

 bunch of E0401 when I know that the code works...

**Comment by DonJayamanne** [comment]
You haven't configured the python path setting, you need to tell vscode to use your virtual environment.

Please check the trouble shooting guide: 
https://github.com/DonJayamanne/pythonVSCode/wiki/Troubleshooting-Intellisense-Autocompletion

**Comment by sh3lld00m** [comment]
Hi Don,

As per instructions [here in Option 2](https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version), I've left the path setting empty and chose to start vscode from the workspace directory with the virtualenv enabled. I've read some other issues here before reporting mine and I thought that virtual environments were supported proceeding this way.

Anyway, configuring the Python path setting for my workspace does not make any difference and pylint is throwing the same error. Here's my workspace settings.json:
```
// Place your settings in this file to overwrite default and user settings.
{
    "python.pythonPath": "/Users/sh3lld00m/workspace/venv/bin/python"
}
```

**Comment by kinwong** [comment]
This issue is closed but I still couldn't get it working.

**Comment by alexwhittemore** [comment]
I'm having the same issue right now, also on Sierra (10.12.6) - Code doesn't respect the python path of the environment it was launched in, nor does setting python.pythonPath have any impact per @sh3lld00m above

**Comment by daibertdiego** [comment]
+1
