### ISSUE TITLE
upon "running" program, it should automatically exit

### ISSUE THREAD

**Issue by ranjan-ranjan** [DonJayamanne/pythonVSCode#621]
VS Code version: 1.8.1
Python Extension version: 0.5.5
Python Version: 3.6
OS and version: Windows 10 Pro 1607

I am running python program. Upon doing "Ctrl + F5", it should automatically exit. This the current result of the action.
![3](https://cloud.githubusercontent.com/assets/16834561/21636174/a00610d4-d287-11e6-9c5d-b59a0da23743.png)

From: https://github.com/Microsoft/vscode/issues/18088

**Comment by DonJayamanne** [comment]
Closing in favor of https://github.com/Microsoft/vscode-python/issues/35
