### ISSUE TITLE
Autocompetion OpenCV 3.2 

### ISSUE THREAD

**Issue by MarioGalimbertiMectho** [DonJayamanne/pythonVSCode#623]
Autocompetion works with system libraries but it doesn't work with the library OpenCV 3.2.
I copiled and installed OpenCV library from repository and the installation process copied the file "cv2.cpython-35m-x86_64-linux-gnu.so" in "/usr/local/lib/python3.5/dist-packages" so I added the path to "python.autoComplete.extraPaths" but it was useless. 
What can i do to solve the problem?

Kind regards!

## Environment data
VS Code version:  1.8.1
Python Extension version:  0.5.5
Python Version:   3.5
OS and version:   Kubuntu 16.04 64bit
```   
Your settings.json:   
{
"python.pythonPath": "python3",
    "python.linting.enabled": true ,
    "python.linting.pylintEnabled": false,
    "python.linting.pep8Enabled": true,
    // /usr/local/lib/python3.5/dist-packages/cv2.cpython-35m-x86_64-linux-gnu.so
    "python.autoComplete.extraPaths": ["/usr/local/lib/python3.5/dist-packages"]
}
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

## Actual behavior

## Expected  behavior

## Steps to reproduce:  
1)  Install python 3.5
2)  install OpenCV 3.2

**Comment by Kjue** [comment]
I'm having similar issues with Windows environment. I had the same problem already with OpenCV 3.1.

**Comment by cgycorey** [comment]
I had a very similar issue with OpenCV 3.1 on Windows 8 Environment. The file cv2.cp35-win_amd64.pyd is placed in\Lib\site-packages. Python version is 3.5 and the Extension version is 0.5.6. The pop up tool tip kept on showing "Loading" and was unable to retrieve the keywords when I typed "cv2." The plugin works fine on other third party python libraries except for this one.

**Comment by jaybo** [comment]
I had a similar issue on Windows 7 with OpenCV 3.1 and WinPython 2.7.10.  
Fixed it by updating the opencv_python package to the latest version via:  

`pip install --upgrade opencv-python`

**Comment by MarioGalimbertiMectho** [comment]
I upgraded VS Code to the version 1.9.0 and Python Extension to 0.5.8; the Issue disappeared!!!

VS Code version: 1.9.0
Python Extension version: 0.5.8
Python Version: 3.5

Great job guys

**Comment by ladevan** [comment]
@cgycorey, I have exactly the same issue like you. Just want to know if this issue has been solved?

**Comment by cgycorey** [comment]
@ladevan Is this issue happening recently after you updated all the VS Code python extension plugins?

For the above issue it was resolved, but 2 days ago I updated with the latest python plugin as well as latest version of OpenCV-python. This issue reappeared again. And it is not only for VSCode, I used Atom's autocomplete-python and it was also showing the same issue. I would say this would be a Jedi-powered auto-completion problem in general.

This is the related ticket:

https://github.com/davidhalter/jedi/issues/777

Seems like we are not alone.

**Comment by ladevan** [comment]
@cgycorey, yes, it happened with latest VS Code + Python extension.

**Comment by DollarAkshay** [comment]
Facing the same issue here. All latest version.


Python : 3.5.2

**Comment by chenyv** [comment]
I also meet the same issue. VScode and python extension are lastest version.

anaconda 4.2.0
python 3.5.2
opencv 3.2.0.7 is installed by: pip install opencv-python

**Comment by zixia** [comment]
+1

I ran into this issue on Ubuntu 17.04, with OpenCV 3.2.0 installed from source.

**Comment by wuyuanyi135** [comment]
+1 windows 10 latest vscode and anaconda OpenCV 3.2.0

**Comment by chaoer** [comment]
I have the same issue on windows 10.
VSCode 1.19.3; Python 3.5; opencv 3.4.0.

Is there any one have solution to this problem?

**Comment by kotzir** [comment]
@chaoer, the only IDE that has OpenCV autocompletion working for me is PyCharm.

**Comment by chaoer** [comment]
@kotzir 
Thanks for your reply. 
I finally find that Spyder also supports OpenCV autocompletion.

**Comment by brotaku13** [comment]
Bumping for visibility. Running into errors with cv2 on ubuntu 16.04. 
VsCode version 1.20.1
python 3.6
anaconda
![spectacle j16400](https://user-images.githubusercontent.com/21026830/36750975-b728f954-1bb3-11e8-9078-d971583e722c.png)

**Comment by skaematik** [comment]
Same issue. 

VSCode version 1.23.1
Extension version 2018.4.0 (2 May 2018)
Python 3.6.4

**Comment by KIRI-Z** [comment]
Same issue.
Seemingly occurs whenever `from xx import *` if xx is a .pyd module like in cv2/\_\_init\_\_.py
I've found another error example which is [Tesserocr](https://github.com/sirfz/tesserocr). It has a \_\_init\_\_.py containing `from .tesserocr import *` which is `_tesserocr.cp36-win_amd64.pyd`

OS: windows 10 1803
VSCode: 1.24
Extension: 2018.5.0
Python: 3.6

**Comment by George35mk** [comment]
Hi, any of you find a solution on this. I get the same pylint error

**Comment by ClementeSerrano** [comment]
Hi guys! I´m having the same issue. 

Importing "import cv2",  "import os" and  "import numpy as np" I got the following errors:

1. [pylint] E1101:Module 'cv2' has no 'imread' member
2. [pylint] E1101:Module 'cv2' has no 'resize' member
3. [pylint] E1101:Module 'cv2' has no 'imshow' member
4. [pylint] E1101:Module 'cv2' has no 'waitKey' member
5. [pylint] E1101:Module 'cv2' has no 'destroyAllWindows' member

Any solution?

**Comment by George35mk** [comment]
You must ignore the errors until vscode linder be fixed. If you run you python script is gonna work.

**Comment by sstoychev** [comment]
I actually found the problem and solution:
copy c:\Python27\Lib\site-packages\cv2\cv2.pyd  to c:\Python27\DLLs

Well, if you need change the paths but you get the idea

**Comment by George35mk** [comment]
I hope this is gona help i gonna try this and i tell you. I have python3.6

**Comment by oskrcl** [comment]
The solution given by @sstoychev works perfectly on python 3.5-32. TY.

**Comment by kol310** [comment]
Anyone knows how to solve this on Linux?

**Comment by PCManticore** [comment]
For folks still having this issue, pylint should work if you pass `--extension-pkg-whitelist=cv2` to it as in `pylint --extension-pkg-whitelist=cv2 ...`. The reason for this flag is that `cv2` seems to be an extension package, thus it's C code that pylint cannot understand. The extension whitelist flag lets pylint import `cv2` in order to build an AST out of the imported cv2 module.

**Comment by uriva** [comment]
To future readers, in vsc this means adding this line to the settings:
`python.linting.pylintArgs": ["--extension-pkg-whitelist=cv2"]`
