### ISSUE TITLE
Ctags rebuildOnFileSave doesn't work

### ISSUE THREAD

**Issue by mdalpi** [DonJayamanne/pythonVSCode#624]
## Environment data
VS Code version: 1.8.1
Python Extension version: 0.5.5
Python Version: 3.6.0
OS and version: macOS 10.12.2

If you delete the tags file, make a change in a Python file and save, the tags is not rebuild.
`rebuildOnStart` is working as expected.

---------
Now about `exclusionPatterns` setting, shouldn't `files.exclude` be add to `exclusionPatterns` by default? 
I'm new to ctags and it probably doesn't process another file extension when set to Python, but lets supose that I add my `.ansible` folder to `files.exclude`, it has some Python files in it and I don't want ctags to index them too.
I know it's just a convenience, but this will follow how VS Code settings work for `files.exclude` and `search.exclude`.

**Comment by DonJayamanne** [comment]
Great suggestion, but will take some time to implement, as the files.exclude is not a simple glob pattern, it could be some nested json structure with some custom logic/rules.
