### ISSUE TITLE
Be a guest on Talk Python To Me

### ISSUE THREAD

**Issue by mikeckennedy** [DonJayamanne/pythonVSCode#625]
Hi Don,

I would love to have you as a guest on Talk Python To Me to talk about this project. I can't seem to find a way to get in touch with you so I'm filing an issue. Sorry about the out-of-band communication channel.

Best,
Michael

**Comment by DonJayamanne** [comment]
@mikeckennedy, that sounds great. I have replied to you on your email address (from profile page).

FYI, still away on my break, back to work on Monday, hence the silence. Also my email address is on my profile page.
