### ISSUE TITLE
Extend "Run cell" link in IPython mode with more characters (like ------) to separate cells clearly

### ISSUE THREAD

**Issue by nguyen14ck** [DonJayamanne/pythonVSCode#629]
## Environment data
VS Code version:  1.8.1
Python Extension version:  0.55
Python Version:   2.7.12
OS and version:    Windows 10

## Actual behavior
Run cell

## Expected  behavior
---------------------------- Run cell --------------------------------------------------------------------------------
## Steps to reproduce:  
-  
-

**Comment by DonJayamanne** [comment]
Will work on this soon. Looking at Jupyter issues these days.

**Comment by DonJayamanne** [comment]
Fixed in a standalone extension for jupyter (will be published this weekend).
https://github.com/DonJayamanne/vscodeJupyter

**Comment by nguyen14ck** [comment]
Sorry for late reply. Could you show me how to enable this feature in new Jupyter extension? Thanks.
