### ISSUE TITLE
Decorators and autocomplete

### ISSUE THREAD

**Issue by gbritton1** [DonJayamanne/pythonVSCode#630]
![2017-01-09_19-15-50](https://cloud.githubusercontent.com/assets/12263288/21789078/547017f6-d6a0-11e6-851c-2c0cb6edfcec.gif)
## Environment data
VS Code version:  
Python Extension version:  
Python Version:   
OS and version:    
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

## Actual behavior

When using the Python decorator syntax, (at-sign) autocomplete doesn't show the decorators in a module

## Expected  behavior

I see the various available decorators

## Steps to reproduce:  
-  import abc
class Deco:
    @abc.  # I don't see abstractmethod, for example

-

**Comment by DonJayamanne** [comment]
Intellisense is provided using the [Jedi](https://github.com/davidhalter/jedi) library. Please report this on their repo.

**Comment by gbritton1** [comment]
Done: https://github.com/davidhalter/jedi/issues/830
