### ISSUE TITLE
python 3.6, anaconda environment : no intellisense

### ISSUE THREAD

**Issue by LunarLanding** [DonJayamanne/pythonVSCode#631]
## Environment data
VS Code version:  Version 1.8.1
Python Extension version:  0.5.5
Python Version:   3.6.0
OS and version:    ubuntu 16.04 LTS
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
{
    "python.pythonPath": "/home/ma/miniconda3/envs/test/bin/python"
}
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
extensionHost.ts:293[Extension Host] ---------------------------A.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293[Extension Host] stderr jediProxyA.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293[Extension Host] Error (stderr) Traceback (most recent call last):
  File "preview/jedi/parser/__init__.py", line 56, in load_grammar
    return _loaded_grammars[path]
KeyError: 'preview/jedi/parser/grammar3.6.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "completion.py", line 404, in watch
    self._process_request(self._input.readline())
  File "completion.py", line 374, in _process_request
    column=request['column'], path=request.get('path', ''))
  File "preview/jedi/api/__init__.py", line 130, in __init__
    self._grammar = load_grammar(version='%s.%s' % sys.version_info[:2])
  File "preview/jedi/parser/__init__.py", line 58, in load_grammar
    return _loaded_grammars.setdefault(path, generate_grammar(path))
  File "preview/jedi/parser/pgen2/pgen.py", line 393, in generate_grammar
    p = ParserGenerator(filename)
  File "preview/jedi/parser/pgen2/pgen.py", line 18, in __init__
    stream = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: 'preview/jedi/parser/grammar3.6.txt'

A.logExtensionHostMessage @ extensionHost.ts:293
```

## Actual behavior
No autocompletion, hovering cursor over words shows "Loading" tootl-tip

## Steps to reproduce:  
-  install minianaconda distribution
-  create environment with "conda create --name test python=3"
-  activate environment with "source activate test"
-  open code with "code ."
- create file "test.py" with "import math", save file
- click the "install pylint" warning that appears.
- on an external terminal, activate the test environment, run "pip list". it will not list "pylint"; therefore vscode does not pick up the environment set by anaconda.
- force vscode to use the anaconda environment via the setting the python path config via the gui. two identical entries appear regarding the test environment. select the first one.
- launch vscode from a terminal where the conda environment was activated. edit and save the test file. pylint is working. Therefore, vscode is using the pylint module installed in the default python, and not the environment, even when the settings.json points to the test environment.

I used virtualenv before. It worked. So I guess there's some difference between virtualenv and anaconda environments for this to happen.
The error in the console also points to there not being support for python 3.6 in "jedi".

**Comment by LunarLanding** [comment]
PS: I created an environment using virtualenv with the option "python=python3". This defaulted to an environment with python-3.5.2.  This explains my confusion: the same default in different environment managers leads to different python versions, and python 3.6 is too modern for vscode dependencies.
I will use instead python 3.5.

**Comment by booyaa** [comment]
relates to #601
