### ISSUE TITLE
memory leak in code completion

### ISSUE THREAD

**Issue by follnoob** [DonJayamanne/pythonVSCode#633]
## Environment data
VS Code version:  1.8.1
Python Extension version:  0.5.5
Python Version:   3.4.3
OS and version:    Ubuntu 14.04 
Your settings.json:   
```json
// Place your settings in this file to overwrite default and user settings.
{
    "python.pythonPath": "python",
    "python.linting.flake8Enabled": true,
    "python.linting.pylintEnabled": false,
    "python.linting.flake8Path": "flake8",
    "python.formatting.autopep8Path": "autopep8",
    "editor.formatOnSave": true,
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "**/*.pyc": true
    }
}
```   
## Logs
Output from ```Python``` output panel  
```
no output
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
no output
```

## Actual behavior
codecompletion.py preview uses somtimes a high amount of memory (1710MiB) or fills my complete
memory so i cant use my system anymore.
![taskmgr](https://cloud.githubusercontent.com/assets/15342895/21845135/bc5ba68a-d7f1-11e6-8eb1-4ecc868055f5.png)

## Expected  behavior
no memory leak

## Steps to reproduce:  
-  random
-  writing code or hover over code

**Comment by DonJayamanne** [comment]
Unfortunately the intellisense is provided using the [Jedi]( https://github.com/davidhalter/jedi) library, I.e. this is an upstream issue.

**Comment by follnoob** [comment]
Maybe you want to know that i fixed the memory leak by using the jedi version from pypi

**Comment by magicdict** [comment]
"python.linting.pylintEnabled": false,
reproduce the problem when set pylintEnabled to false。

**Comment by pingyangtiaer** [comment]
I had the same issue, how did you fix it, I sometimes got used up my whole memory (32G), does disable the ESlint fix the issue?
