### ISSUE TITLE
Remove pylint messages (& anything else) from closed files in 'Problems' panel

### ISSUE THREAD

**Issue by BillDenton** [DonJayamanne/pythonVSCode#634]
## Environment data
VS Code version:  Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
Python Extension version:  0.5.5
Python Version:   Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
OS and version:    Windows_NT ia32 6.1.7601
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

## Actual behavior
Open python file. See messages in problems panel. Close python file. Pylint messages still in problems panel.
## Expected  behavior
Open python file. See messages in problems panel. Close python file. Pylint messages removed from problems panel.
## Steps to reproduce:  
-  
-  
Apparently (https://github.com/Jason-Rev/vscode-spell-checker/issues/54) TS and TSLint remove their messages from the Problems panel.

**Comment by DonJayamanne** [comment]
This has been fixed in the latest version.
