### ISSUE TITLE
Using input() function in debug never exits

### ISSUE THREAD

**Issue by gbritton1** [DonJayamanne/pythonVSCode#635]
## Environment data
VS Code version:  1.8.1
Python Extension version:  5.5
Python Version:   3.6
OS and version:    win 7 64
Your launch.json (if dealing with debugger issues):  
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${file}",
            "pythonPath": "${config.python.pythonPath}",
            // "pythonPath": "c:\\python27\\python.exe",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Python 2.7",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${file}",
            "pythonPath": "c:\\python27\\python.exe",
            "externalConsole": true,
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
        {
            "name": "Python 3.5",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${file}",
            "pythonPath": "c:\\python35\\python.exe",
            "externalConsole": true,
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
        {
            "name": "Django",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${workspaceRoot}/manage.py",
            "args": [
                "runserver",
                "--noreload"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "DjangoDebugging"
            ]
        },
        {
            "name": "Watson",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${workspaceRoot}/console.py",
            "args": [
                "dev",
                "runserver",
                "--noreload=True"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }
    ]
}
Your settings.json:   
// Place your settings in this file to overwrite the default settings
{
    "editor.wrappingColumn": 120,
    "python.pythonPath": "C:\\Program Files (x86)\\Python36-32\\python.exe",
    "python.linting.pylintArgs": 
        ["--docstring-min-length","10",
         "--extension-pkg-whitelist", "pyodbc"],
    "python.linting.pylintEnabled": true,
    "http.proxyStrictSSL": false,
    "mssql.connections": [
        {
            "server": "(localdb)\\mssqllocaldb",
            "database": "",
            "authenticationType": "Integrated",
            "profileName": "MSSQLLocalDB",
            "password": ""
        },
        {
            "server": "SISDSLBCB0TBV,3341",
            "database": "Vision",
            "authenticationType": "Integrated",
            "profileName": "Vision_UAT",
            "password": ""
        }
    ]
,
"files.autoSave": "afterDelay"
}
## Logs
Output from ```Python``` output panel  
Nothing
Output from ```Console window``` (Help->Developer Tools menu)
nothing

## Actual behavior

in a two-line program:

a = input('b')
print('got: ' + a)

running under debugger, the input prompt accepts my input, but after I hit enter, the next line is never reached

e.g. in the Debug Console I see:

b
1
2
3

If I run the program and enter 1, 2 and 3.  However I do not expect to be prompted more than once and 
the print command is never reached.  I'm in an infinite loop

## Expected  behavior

I see "got: a" in the output window

## Steps to reproduce:  

1. create a new program, enter two lines:
a = input('b')
print('got: ' + a)
2. run the program under debug (hit F5)

**Comment by DonJayamanne** [comment]
@gbritton1  what debug configuration are you using?

**Comment by gbritton1** [comment]
Debug config:

        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${file}",
            "pythonPath": "${config.python.pythonPath}",
            // "pythonPath": "c:\\python27\\python.exe",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },

Python Path: 

"python.pythonPath": "C:\\Program Files (x86)\\Python36-32\\python.exe",

**Comment by gbritton1** [comment]
FYI -- just retested with extension version .0.5.6 (just released).  Same results

**Comment by DonJayamanne** [comment]
You do not have a console for the input. Please add the following to your debug config, of delete the launch.Json and it will get created again.
```json
externalConsole": true,
```

**Comment by gbritton1** [comment]
Well, that was interesting.  I put that in (got a deprecation message?) and retested.  Now, when it get's to the line a= input('b'), it _neither_ prompts me for input _nor_ errors out (no exceptions are raised).  It just sits there.  No prompt on the debug console or the integrated terminal.  The pause button doesn't do anything at that point.  I have to hit stop.
