### ISSUE TITLE
Trouble with Linting on BashOnWindows

### ISSUE THREAD

**Issue by wasabigeek** [DonJayamanne/pythonVSCode#636]
I am using https://github.com/Microsoft/BashOnWindows with VS Code, and tried to install flake8 using the integrated terminal, but it failed due to permissions. So I installed it using my regular bash terminal, but still can't seem to get it working. Is it my paths?

## Environment data
VS Code version:  1.8.1
Python Extension version: 0.5.5 
OS and version:  Windows 10, rs1_release 14393
Your settings.json:  
```json
{
    "editor.renderWhitespace": true,
    "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe",
    "python.linting.pylintEnabled": false,
    "python.linting.flake8Enabled": true,
    "python.linting.flake8Path": "C:\\Users\\USER\\AppData\\Local\\lxss\\rootfs\\usr\\local\\bin\\flake8"
}
```   
## Logs
Output from ```Python``` output panel  

Initial install:
```
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/flake8'
```
After installing manually:
```
python -m pip install flake8

USER@DESKTOP:/mnt/c/Users/USER/$ python -m pip install flake8
Requirement already satisfied (use --upgrade to upgrade): flake8 in /usr/local/lib/python2.7/dist-packages
Cleaning up...
```   
## Actual
"Linter flake8 is not installed" error

## Steps to reproduce:  
- Open Bash on Windows, sudo install flake8
- Create settings.json as above

**Comment by JFox** [comment]
Exact same problem here

**Comment by wasabigeek** [comment]
@JFox it's something to do with Bash on Windows, I remember seeinganother issue on it too. I switched instead to Git Bash instead, that works
