### ISSUE TITLE
The best way to debug a remote Django app

### ISSUE THREAD

**Issue by ychab** [DonJayamanne/pythonVSCode#637]
Hi,

I'm trying to debug a remote Django app which is a privileged LXC container. Source code is mounted on an entry mount point via LXC.

Just in case, I'm using :
* VSCode 1.8.1 on an Ubuntu 16.04
* pythonVSCode 0.5.5
* *ptvsd* 2.2.0 with Python3.4

To do so, I'm using this remote debug conf :
```javascript
       {
            "name": "Remote Django App",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "/srv/projects/django",
            "port": 3000,
            "secret": "my_secret",
            "host": "10.0.3.49"
        }
```
Just for testing, I have edited the ``manage.py`` script to include ptvsd (I plan to use a script wrapper later):
```python
#!/usr/bin/env python3
import os, sys

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "mysettings")

    from django.core.management import execute_from_command_line

    import ptvsd
    ptvsd.enable_attach("my_secret", address = ('0.0.0.0', 3000))

    execute_from_command_line(sys.argv)
```
then I execute in the container the runserver command (through SSH):
```
python manage.py runserver --noreload --nothreading 0.0.0.0:8000
```
Finally on my host machine, I start the debugging config.
I set some breakpoint and hit the website.

Everything seems to works fin (nice!), except that:
* it is really slow
* I need to set the ``--nothreading`` flag otherwise, I cannot see the highlighting cursor when breakpoint is hit (but the variables are updated properly if I jump between step!)

Am I missing something? There is an another way to do it?

Thanks a lot

**Comment by DonJayamanne** [comment]
Unfortunately for the moment this is the only way. Hopefully in the future this will be improved.
