### ISSUE TITLE
Step through not working

### ISSUE THREAD

**Issue by TheodoreYin** [DonJayamanne/pythonVSCode#639]
## Environment data
VS Code version:  1.8.1
Python Extension version:  0.5.5
Python Version:   3.5
OS and version:    macOS 10.12.2
Your launch.json (if dealing with debugger issues):  
{
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Integrated Terminal/Console",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "console": "integratedTerminal",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
        {
            "name": "External Terminal/Console",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "console": "externalTerminal",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
        {
            "name": "Django",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${workspaceRoot}/manage.py",
            "args": [
                "runserver",
                "--noreload"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "DjangoDebugging"
            ]
        },
        {
            "name": "Flask",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config.python.pythonPath}",
            "program": "fully qualified path fo 'flask' executable. Generally located along with python interpreter",
            "env": {
                "FLASK_APP": "${workspaceRoot}/quickstart/app.py"
            },
            "args": [
                "run",
                "--no-debugger",
                "--no-reload"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Flask (old)",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${workspaceRoot}/run.py",
            "args": [],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Watson",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${workspaceRoot}/console.py",
            "args": [
                "dev",
                "runserver",
                "--noreload=True"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Attach (Remote Debug)",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "${workspaceRoot}",
            "port": 3000,
            "secret": "my_secret",
            "host": "localhost"
        }
    ]
}
Your settings.json:   
```{
    "python.pythonPath": "/usr/local/bin/python3.5",
    "python.linting.pylintEnabled": false
}
```   

The problem is the debugger runs well but I can't step into , step over, step out. 
If i press one of the three button, things happened like this
![image](https://cloud.githubusercontent.com/assets/17927631/21892519/3150691e-d912-11e6-828e-2875de19703d.png)
Variables and stacks are clear, and all I could do is to restart or stop it.
some screenshots may help
![image](https://cloud.githubusercontent.com/assets/17927631/21892707/100d627e-d913-11e6-9697-21a5932c6f67.png)
![image](https://cloud.githubusercontent.com/assets/17927631/21892716/133b4bfa-d913-11e6-8861-2c438fe12989.png)
![image](https://cloud.githubusercontent.com/assets/17927631/21892723/16dc916a-d913-11e6-9a09-3026cf86d676.png)

**Comment by DonJayamanne** [comment]
Please could you translate the text (displayed in the images) into English,

**Comment by TheodoreYin** [comment]
"Can't find the message of key XXXXX" 
all the yellow part is like this

**Comment by DonJayamanne** [comment]
Is this still an issue. If it is please reopen the issue.
