### ISSUE TITLE
Question: will cloned and installed pythonVSCode still make vscode prompt for update?

### ISSUE THREAD

**Issue by fredrikaverpil** [DonJayamanne/pythonVSCode#641]
I was eager to get my hands on some of the [new stuff](https://github.com/DonJayamanne/pythonVSCode/issues/353), so I cloned and installed the current master branch into `~/.vscode/extensions/donjayamanne.python-0.5.5`.

However, I would've liked to be prompted by vscode when pythonVSCode in fact is getting its next release so I can jump back onto the 'official' pythonVSCode train.

Will this just work - or do I need to keep an eye out for when the next release will be?

Thanks so much for this great package! 😄

**Comment by DonJayamanne** [comment]
You will need to keep an eye out for an update. Hopefully I will have something before the end of the month, back from holidays and time to start fixing issues

**Comment by fredrikaverpil** [comment]
Ok, thanks!

**Comment by DonJayamanne** [comment]
New version has been released
