### ISSUE TITLE
escape characters in string with leading char "r" (raw string indicator)

### ISSUE THREAD

**Issue by nNullSpace** [DonJayamanne/pythonVSCode#643]
## Environment data
VS Code version:  1.8.1
Python Extension version:  0.5.5
Python Version:   3.5.2
OS and version:    windows 8 (64bit)
= = = =

um... we can tell it from the attached image, so I deleted some sections.
If this issue was not related to pythonVCode or I said something stupid, I am sorry.

![1](https://cloud.githubusercontent.com/assets/22057021/21955127/646e7532-da9f-11e6-9204-ea7afc9b050e.jpg)

[http://i.imgur.com/Ix4eE07.jpg](url)  (if attached failed)

The string is following "r", then it's a raw string with no escape characters, but someone (pythonVSCode or VSCode ... I am not sure actually) marked escape characters in it.

Thank you very much.

Have a nice day :)

**Comment by DonJayamanne** [comment]
Unfortunately syntax highlighting isn't party of this extension. This is provided by vscode, or please try installing the latest Magic Python extension, of not please report this issue on their repo ([Magic Python](https://github.com/MagicStack/MagicPython))

**Comment by nNullSpace** [comment]
OK, thank you again :)

**Comment by danil-tolkachev** [comment]
@nNullSpace try prefix with uppercase R:

```python
dir = R"C:\temp\a"
dir = r"C:\temp\a"
```

I believe it is a feature, not a bug. It is useful for highlighting regular expressions.

**Comment by nNullSpace** [comment]
How come that you can find that.
Danil-tolkachev you are amazing.
Thanks bro :)

**Comment by nNullSpace** [comment]
uh.... it might be not that perfect

![2](https://cloud.githubusercontent.com/assets/22057021/21964866/f3134eee-db8e-11e6-9760-e721e07a25b5.jpg)

**Comment by danil-tolkachev** [comment]
I can't reproduce this. Which color theme do you use? Do you try to install MagicPython extension? What is your VS Code version?

**Comment by nNullSpace** [comment]
I install no MagicPython , VSCode is 1.8.1

My test code:

```
from os import listdir
from os.path import isfile, join
import re
import os, sys
import shutil

s=R"c:\temp\a"
s=r"c:\temp\a"

pattern = R"^[A-Z]+-\d+"
pattern = r"^[A-Z]+-\d+"

os.mkdir(s)

```

Phenomenon image on my site:
![3](https://cloud.githubusercontent.com/assets/22057021/21975567/5ef4383e-dc08-11e6-935c-d8bd1a98e28f.jpg)

That's really strange.
=_=

**Comment by DonJayamanne** [comment]
@nNullSpace VS Code ships with the magic python theme preinstalled. Hence any issues you may have with the syntax highlithing will have to be reported to the Magic Python repo.

**Comment by danil-tolkachev** [comment]
@nNullSpace I reproduce your bug. Causer is Python for VSCode extension by Thomas Haakon Townsend. It brings own syntax highlighting.

**Comment by nNullSpace** [comment]
I confirmed that, Thomas Haakon Townsend's extension is the root cause.
Nothing strange anymore after closing the extension.

Thank you, Danil Tolkachev, you are GREAT :)

**Comment by danil-tolkachev** [comment]
@nNullSpace You're welcome =)
@DonJayamanne Sorry for noise.

**Comment by DonJayamanne** [comment]
@danil-tolkachev, no worries. As long as you got the issue resolved.
