### ISSUE TITLE
Automatically expand full docstring when autocompleting

### ISSUE THREAD

**Issue by fredrikaverpil** [DonJayamanne/pythonVSCode#645]
Would it be possible to automatically expand the docstring without requiring clicking the "info" symbol button?

Current behavior requires you to click the "info" symbol button to view the full docstring:

![01](https://cloud.githubusercontent.com/assets/994357/21961187/380fc748-db03-11e6-9507-74a584098550.png)
![02](https://cloud.githubusercontent.com/assets/994357/21961165/b2e0ab00-db02-11e6-9f52-e03834859821.png)

For comparison, here's how Atom deals with this (always expands the full docstring):

![atom](https://cloud.githubusercontent.com/assets/994357/21961171/d2b00afc-db02-11e6-95d3-4762f163d940.png)

**Comment by gandhis1** [comment]
I agree, but it should be intelligent, and there should be an upper limit on box height. There can be some really long doc strings our there.

**Comment by DonJayamanne** [comment]
This is a feature request for vscode. Please submit in the vscode repo
