### ISSUE TITLE
Intellisense not working with Python 3.6

### ISSUE THREAD

**Issue by senhtry** [DonJayamanne/pythonVSCode#646]
Intellisense not working with Python 3.6. Python extension hasn't the 3.6 grammer file.

Solution:
copy grammar3.5.txt to grammar3.6.txt in ~\.vscode-insiders\extensions\donjayamanne.python-0.5.5\pythonFiles\preview\jedi\parser and my autocompletion started to work again.

**Comment by andreagrandi** [comment]
@senhtry I confirm to have the same issue and your workaround (with a few path adjustments) works for me.
