### ISSUE TITLE
Feature suggestion: inline coverage reporting

### ISSUE THREAD

**Issue by sfermigier** [DonJayamanne/pythonVSCode#647]
Issue #183 being now closed, here's an independent issue for a feature suggestion that I find really important: inline reports for `coverage.py` results (or `pytest --cov`, etc.).

**Comment by patrys** [comment]
Here's an example implementation for Golang: https://github.com/Microsoft/vscode-go/pull/143

**Comment by cristim** [comment]
Coming from golang I miss this a lot.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#72
