### ISSUE TITLE
Feature suggestion: run Django unittests

### ISSUE THREAD

**Issue by jvaesteves** [DonJayamanne/pythonVSCode#648]
Django unittest extends from unittests, but you can't run as the former on this extension. For this, you need to "manage.py test", but it would be awesome if there were those same shortcuts.

**Comment by guhuajun** [comment]
I did something like following. I think it's supported now.

![default](https://cloud.githubusercontent.com/assets/14121694/22096457/9ca20710-de56-11e6-8b0b-6d2d539a7222.png)

![default](https://cloud.githubusercontent.com/assets/14121694/22096465/aa041484-de56-11e6-8b0f-d1fb8add0b95.png)

**Comment by jvaesteves** [comment]
I tried your suggestion, copying the same parameters on the settings.json file, but running the "Run Unit Test Method..." command still doesn't work. The Output Console gives me the following message:

**ImproperlyConfigured:** Requested setting DATABASES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

And then, when I configure this environment variable to my global_settings.py path, the message change to: **ImportError:** Import by filename is not supported.

**Comment by guhuajun** [comment]
https://github.com/DonJayamanne/pythonVSCode/wiki/unitest-(Standard-Unit-testing)-Framework#test-discovery
Please try to place a __init__.py.

Yes, missing DJANGO_SETTINGS_MODULE is annoying. I encountered this issue when writing tests for a django-cms project.

**Comment by DonJayamanne** [comment]
@jvaesteves Will be closing this issue as @guhuajun has a solution.

**Comment by DonJayamanne** [comment]
@jvaesteves please confirm @guhuajun suggestion works, so I can close this issue.

**Comment by jvaesteves** [comment]
No, it didn't.

**Comment by james-perretta** [comment]
It looks to me like the suggestion from @guhuajun gets us part of the way there for running Django test cases. Unless I'm mistaken, you can't really use unittest to run tests for any serious Django project.
When you run `python manage.py test`, it first does general setup (figuring out which settings module to use and calling django.setup()). After that, it hands the rest off to a test-runner class that does even more important things like creating and destroying the databases that the test cases need to operate on.

I did a bit of digging, and although I'm not particularly familiar with the implementation details of your plugin, I think this is a starter summary of what it would require to add this:
- Add client modules similar to those for nose and pytest (I have almost zero knowledge of how this part works)
- Add handling for testFx == 'django' in [testlauncher.py](https://github.com/DonJayamanne/pythonVSCode/blob/ee9f3586c8df3071775d096c65bc815d36ca428e/pythonFiles/PythonTools/testlauncher.py). This would involve code similar to what you see [here in the runtests.py snippet](https://docs.djangoproject.com/en/1.10/topics/testing/advanced/#using-the-django-test-runner-to-test-reusable-applications). 
- Possibly add a workspace settings option that lets the user specify the value for DJANGO_SETTINGS_MODULE. That environment variable needs to be set before calling django.setup()
- Certain `manage.py test` options should always be passed, such as --no-input
- Add support for other django-specific unit test options, such as --tag, --exclude-tag, and maybe --parallel

Thoughts?

**Comment by PlugaruT** [comment]
Because I have different settings files for each environment (production, local, test), I can't run tests because with this plugin because `DJANGO_SETTINGS_MODULE` is not set when trying to run the tests. I would be nice if I could set this env variable in in the `workspace.json` or somewhere else.

**Comment by DonJayamanne** [comment]
@PlugaruT  Environment variables can be set for the workspace. Just create a file named ```.env``` in your workspace root and add the necessary variables in there.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#73
