### ISSUE TITLE
Go to definition not showing in right click context...

### ISSUE THREAD

**Issue by Devansh3790** [DonJayamanne/pythonVSCode#649]
I have updated extension and Go to definition not coming when I right click on any class name and `ctrl+left_click ` is also not working.

**Comment by DonJayamanne** [comment]
>Go to definition not coming when I right click on any class name

Sounds like something is wrong with VS Code, are you sure you have the extension installed?

Please could you provide the following info:

- Version of python
- Version of the extension
- OS
- Did this work before? (

**Comment by DonJayamanne** [comment]
Please reopen if persists.
