### ISSUE TITLE
Remote debugging?

### ISSUE THREAD

**Issue by arjamizo** [DonJayamanne/pythonVSCode#65]
What if I want to debug a remote machine? 

Thanks

**Comment by DonJayamanne** [comment]
Hi, this is possible. I'll update the documentation/wiki with instructions.

**Comment by arjamizo** [comment]
When can this be done? If you are willing to give me some instructions then I can write a draft for this if you do not mind.

**Comment by DonJayamanne** [comment]
Hi will send this through today

**Comment by DonJayamanne** [comment]
Thanks for the help

**Comment by arjamizo** [comment]
Do you still remember? : )

**Comment by DonJayamanne** [comment]
Sorry, been very busy with all sorts of stuff. Here it is:

1. First get the ptvs library from https://pypi.python.org/pypi/ptvsd
2. Create a sample python script file and import the above library (see below two lines)
```python
import ptvsd
ptvsd.enable_attach("my_secret", address = ('0.0.0.0', 3000))
```
3. Make the above change in both script files (i.e. scripts on both the local and remote machines)
4. Run your remote program
5. Open the local script and add an entry into your launch.json as follows:
```json
        {
            "name": "remote",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "C:/temp/python",
            "port": 3000,
            "secret": "my_secret"
        }
```
Where remoteRoot is the path to the script file on the remote machine.
port is the port to connect to the remote machine on
secret is a pass phrase used to authenticate for remote debugging
url is the url to the remove server

Thats all.

Unfortunately, I just identified a serious problem. I have only enabled remote debugging on the same machine. I did test the remote debugging against a mac, looks like i never commited those changes. bummer. I dont have access to that environment, at this stage.
I'm sorry, i'll complete that later tonight. 

Once again, apologies for the delay and for the misleading information.

**Comment by arjamizo** [comment]
Thanks! I will try it!

**Comment by DonJayamanne** [comment]
I have tested the changes and will be publishing the build tonight

**Comment by DonJayamanne** [comment]
Fixed in latest build

**Comment by hiitiger** [comment]
After setup remote debugging, I set  a break point  and begin remote debugging,  when the break point hits, it shows can not find the file with file's remote path, seems it doesn't look for corresponding file at local working directory.

**Comment by DonJayamanne** [comment]
documentation: https://github.com/DonJayamanne/pythonVSCode/wiki/Debugging:-Remote-Debuging

**Comment by DonJayamanne** [comment]
@hiitiger , didn't notice you message until now. Apologies for this, the issue was closed, hence your message would have been lost amongst others.
Did you manage to solve this?

**Comment by deepak-khopade-isdr** [comment]
Tried all the above steps but no luck :(
It's simply keep waiting and never attaches.
