### ISSUE TITLE
Feature Suggestion: Ability to ignore specific PEP8 rules for linting and formatting

### ISSUE THREAD

**Issue by dralley** [DonJayamanne/pythonVSCode#650]
Example from the Sublime Text plugin "Anaconda"

```
  "pep8_ignore":
  [
      "E501", // Line too long
      "E309", // Missing blank line after class declaration
  ],
  "pep8_max_line_length": 120,
  "autoformat_ignore":
  [
      "E501", // Line too long
      "E701", // Put colon-separated compound statement on separate lines.
      "E26",  // Spacing after comment hash
      "E122", // Add absent indentation for hanging indentation.
  ],
```

Similar example from VS Code

```
    // Configure glob patterns for excluding files and folders.
    "files.exclude": {
        "**/.git": true,
        "**/.idea": true,
        "**/.DS_Store": true,
        "**/*.pyc": true
    },
```

This is really useful because it allows you to, as an example, avoid fixing enforcing line length limits and other lesser-importance rules selectively.

**Comment by gandhis1** [comment]
I like this more than having a separate PyLint configuration file (and this could be global).

**Comment by DonJayamanne** [comment]
Will not implement for now. 
Implementing this opens a whole can of worms, there are a number of linters supported by this extension. To be consistent I'd have to support other linters too, and adding the ability to exclude messages from different linters would mean I'd have to create custom configuration settings, i.e. a long a complicated process.

**Comment by cardonator** [comment]
Couldn't you just add an "ignore_linter_rules" dictionary instead such as

`"ignore_linter_rules": {
    "C0301",
    "C0103"
}`

And just have the parser that highlights the lines unhighlight matching rules?

**Comment by DonJayamanne** [comment]
Nope, not that simple. It is easier for you to use a standard (linter specific) config file for the linter.

**Comment by cardonator** [comment]
Interesting. I'm happy to use the standard linter config. I'll have to figure that out.

**Comment by DonJayamanne** [comment]
Here you go, check documenting on using custom configuration for each linter.
https://github.com/DonJayamanne/pythonVSCode/wiki/Linting#pylint8

**Comment by DonJayamanne** [comment]
Closing, as I do not plan on implementing this.
