### ISSUE TITLE
Running Python file in Terminal failed if Terminal is PowerShell

### ISSUE THREAD

**Issue by yanxyz** [DonJayamanne/pythonVSCode#651]
![image](https://cloud.githubusercontent.com/assets/737120/22053602/bcc6395a-dd8c-11e6-87de-cc85cf9f2316.png)

Sending "Python" to PowerShell, PowerShell will treat it as string then output it instead of invoking Python。

## Environment data
VS Code version:  1.8.1
Python Extension version:  0.5.6
Python Version:   
OS and version:   Windows10 x64

**Comment by gandhis1** [comment]
This is a newly introduced bug that I experience as well. Besides updating the Python extension I am not aware of any other meaningful changes to my environment.

**Comment by gandhis1** [comment]
That's exactly what it is. See this PR:

https://github.com/Microsoft/vscode/pull/18493

**Comment by yanxyz** [comment]
@gandhis, thanks.  

Why I change VSCode terminal to powershell.exe ? I'm learning PowerShell and VSCode these days.

1. Some PowerShell guides tells that changing VSCode terminal to powershell.exe to get a better PowerShell development environment. 

1. Windows 10 Insider Preview replaces cmd.exe with powershell.exe. 
https://blogs.windows.com/windowsexperience/2016/11/17/announcing-windows-10-insider-preview-build-14971-for-pc/
