### ISSUE TITLE
Wrong current working directory when there's only a single file open

### ISSUE THREAD

**Issue by Agnpalm** [DonJayamanne/pythonVSCode#653]
VS Code version:  1.8.1
Python Extension version:  0.5.6
Python Version:   3.6.0
OS and version:    Windows 10 x64

When I open a single file instead of a folder, the current working directory is 'C:\Program Files (x86)\Microsoft VS Code'. It would be much better if it would be the same folder as where the .py file is, as that is the expected behavior.  This works as expected if I instead open the folder with the file.

For now I've added a os.chdir(...) at the top of the file. I first tried using the `__file__` constant since I don't want hardcoded paths in my code, but `__file__` isn't defined when running Jupyter cells, I guess since it's running code in REPL mode.

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/vscodeJupyter#10
