### ISSUE TITLE
Please make it possible to enlarge images in Jupyter output window

### ISSUE THREAD

**Issue by Agnpalm** [DonJayamanne/pythonVSCode#655]
VS Code version:  1.8.1
Python Extension version:  0.5.6
Python Version:   3.6.0
OS and version:    Windows 10 x64

When showing images in the Jupyter output window they're way too small. It might be ok for some plots, but I was working with images and edge detection, and a lot of the edges weren't visible due to the small output images and the pretty bad resampling.

There's several ways this could be implemented. Click and drag on the image to resize, add a resize handle to the image, open a full size image in a separate overlay when clicked, and so on.

**Comment by Agnpalm** [comment]
As a workaround, it's possible to add this command to your script:
`plt.rcParams["figure.figsize"] = [10, 9]`

I guess this could be added to the auto executed code in the settings, but you would have to add `import matplotlib.pyplot as plt` too.

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/vscodeJupyter#9
