### ISSUE TITLE
Scroll output window when outputting to Jupyter window

### ISSUE THREAD

**Issue by Agnpalm** [DonJayamanne/pythonVSCode#656]
When printing output to Jupyter the output is added at the bottom (as expected), but the output window doesn't scroll down to show it. This makes it tedious to run a cell, and then switch to the mouse and scroll down to the bottom. I found myself turning off 'Append Results' to always see the latest output.

I think it makes sense to scroll to the bottom when new data is available. Maybe put in a check to see if the user has scrolled up to look at something in the history, and not automatically scroll down if that is the case.

Also, I think it would be preferable if the scroll was animated, to make it obvious that new output was added. I'm not a web developer, but I found [this library](https://github.com/GabrielDelepine/smooth-scroll) with a quick search. Animations can be both beneficial and annoying depending on implementation and personal taste, so maybe make the animation time configurable if you add this.

**Comment by gandhis1** [comment]
I agree, said something similar in #401

**Comment by Agnpalm** [comment]
I wasn't aware of that discussion. In reference to the latest comment from @DonJayamanne in that thread about it working on his Mac, I'd like to add that I'm using Windows 10. I didn't expect that to make a difference since I thought VS Code was using the same Chromium engine for all platforms.

**Comment by gandhis1** [comment]
This bug may be related to the fix applied here: https://github.com/Microsoft/vscode/pull/20064

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/vscodeJupyter#8
