### ISSUE TITLE
Extra new lines after each line in debug console

### ISSUE THREAD

**Issue by Kenuat** [DonJayamanne/pythonVSCode#659]
## Environment data
VS Code version:  1.8.1
Python Extension version:  0.5.6
Python Version:   2.7.13
OS and version:    Windows 8.1 Pro 

## Actual behavior
Debug console inserts extra lines between all strings

## Expected  behavior
no extra lines between strings

## Steps to reproduce:  
just print two strings and run debug as Python configuration (default)
```
print "first string"
print "second string"
```

## Settings  
both files are default

## Logs
Output from ```Python``` output panel  
empty

Output from ```Console window``` (Help->Developer Tools menu)
empty

I am very new to VS Code, so please be compassionate if this is something lame :)

Thank you.

**Comment by DonJayamanne** [comment]
This is an upstream issue (VS Code)
https://github.com/Microsoft/vscode/issues/17526
