### ISSUE TITLE
Support debug snippets

### ISSUE THREAD

**Issue by isidorn** [DonJayamanne/pythonVSCode#660]
Please support debug snippets so setting up pythong debugging is a smother experience.
Example how node is doing this https://github.com/Microsoft/vscode-node-debug/blob/master/package.json#L98

Once this is done the blue add configuration button in launch.json can be used to add new python snippets.

**Comment by DonJayamanne** [comment]
@isidorn ,
Done, thanks for the heads up, great little feature.
