### ISSUE TITLE
intellisense autocomplete not working in the debug console

### ISSUE THREAD

**Issue by ridgebackcap** [DonJayamanne/pythonVSCode#661]
## Environment data
VS Code version:  1.8.1
Python Extension version:  0.5.6
Python Version:   2.7.13
OS and version: Windows 10   

## Actual behavior
intellisense is not working in the debug console:

![debug_intellisense](https://cloud.githubusercontent.com/assets/20070277/22116864/d8b17c5c-de3f-11e6-8019-adf79e5a3fe3.gif)

## Expected  behavior
same as in the editor

## Steps to reproduce:  
- see gif  
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
This was never working, would be a feature request.

**Comment by mdeangelo272** [comment]
Don, pthonVSCode is really great, thank you for creating it!

I too would like to see this enhancement.

**Comment by DonJayamanne** [comment]
Hi everyone, I haven't looked into this as there wasn't must interest here. This can most certainly be done, but requires some effort and I didn't feel that the feature was worth the effort. Hopefully there'll be more up votes for this issue.

**Comment by cryptomaniac512** [comment]
I would very much like to have this feature. Otherwise, it is more convenient for me to use the `pdbp` and run tests from the console.

**Comment by sambhare** [comment]
No idea how to officially upvote on Github, but yes, this would be very handy!

**Comment by DonJayamanne** [comment]
@sambhare go to the (preferably) message with most number of up votes (👍) and click on the little smiley face on the top right hand corner.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#81
