### ISSUE TITLE
Pylint: Unable to import 'queue' in Python3.6

### ISSUE THREAD

**Issue by atnoslen** [DonJayamanne/pythonVSCode#663]
## Environment data
VS Code version:  1.8.1
Python Extension version:  0.5.6
Python Version:   3.6.0
Pylint Version: 1.6.4
OS and version:  OSX 10.11.6

## Actual behavior
Added `#!/usr/bin/env python3` to beginning of file.
Changed Workspace Interpreter to Python3.6
Validated `settings.json` are
```
{
    "python.pythonPath": "/usr/local/bin/python3.6"
}
```
Receiving [pylint] E0401:Unable to import 'queue' in IDE.

Debugging runs python3 and application performs appropriately.

Importing other Python3 modules, such as `configparser` instead of `ConfigParser` appear proper.
## Expected  behavior
No errors on runnable code.

## Steps to reproduce:  
-  Change Workspace Interpreter to Python3.6
-  `import queue` receives pylint unable to import

## Settings  
Your launch.json (if dealing with debugger issues):  
```
{
    "python.pythonPath": "/usr/local/bin/python3.6"
}
```   
## Logs
Output from ```Python``` output panel  
Removed other pylint errors.
```
##########Linting Output - pylint##########
************* Module ***
12,0,error,E0401:Unable to import 'queue'


No config file found, using default configuration
```

**Comment by DonJayamanne** [comment]
Do you get this error when running pylint manually from the terminal?

**Comment by atnoslen** [comment]
Negative.  

From `output`
```
##########Linting Output - pylint##########
************* Module ping
380,0,info,I0011:Locally disabling broad-except (W0703)
28,0,convention,C0301:Line too long (105/100)
12,0,error,E0401:Unable to import 'queue'
35,0,refactor,R0902:Too many instance attributes (29/7)
175,11,refactor,R0916:Too many boolean expressions in if statement (6/5)
580,4,refactor,R0912:Too many branches (15/12)
580,4,refactor,R0915:Too many statements (70/50)
823,-1,warning,W0105:String statement has no effect
854,-1,warning,W0105:String statement has no effect
889,-1,warning,W0105:String statement has no effect
935,-1,warning,W0105:String statement has no effect
948,-1,warning,W0105:String statement has no effect
955,-1,warning,W0105:String statement has no effect
962,-1,warning,W0105:String statement has no effect

No config file found, using default configuration
```

From Terminal.

```
(venv) anelson006923:TV3_ping_rtl anelson$ pylint ping.py
No config file found, using default configuration
************* Module ping
I:380, 0: Locally disabling broad-except (W0703) (locally-disabled)
C: 28, 0: Line too long (105/100) (line-too-long)
R: 35, 0: Too many instance attributes (29/7) (too-many-instance-attributes)
R:175,11: Too many boolean expressions in if statement (6/5) (too-many-boolean-expressions)
E:738,40: Instance of 'object' has no 'split' member (no-member)
R:580, 4: Too many branches (15/12) (too-many-branches)
R:580, 4: Too many statements (70/50) (too-many-statements)
W:823,-1: String statement has no effect (pointless-string-statement)
W:854,-1: String statement has no effect (pointless-string-statement)
W:889,-1: String statement has no effect (pointless-string-statement)
W:935,-1: String statement has no effect (pointless-string-statement)
W:948,-1: String statement has no effect (pointless-string-statement)
W:955,-1: String statement has no effect (pointless-string-statement)
W:962,-1: String statement has no effect (pointless-string-statement)
```

**Comment by DonJayamanne** [comment]
Ok, please confirm you have pylint installed in the python3.6 environment. It looks like it isn't.

**Comment by atnoslen** [comment]
As far as I can tell, pylint has been installed in my python3.6 environment.

```
$ pip3.6 install pylint
Requirement already satisfied: pylint in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requirement already satisfied: isort>=4.2.5 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pylint)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pylint)
Requirement already satisfied: mccabe in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pylint)
Requirement already satisfied: astroid<1.5.0,>=1.4.5 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pylint)
Requirement already satisfied: lazy-object-proxy in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from astroid<1.5.0,>=1.4.5->pylint)
Requirement already satisfied: wrapt in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from astroid<1.5.0,>=1.4.5->pylint)

```

Running `less $(which pylint)` gives me:

```
#!/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6

# -*- coding: utf-8 -*-
import re
import sys

from pylint import run_pylint

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(run_pylint())
```

And as you can see from running pylint from the terminal I do not receive the error.  

I've setup my venv and run `code .` to ensure VS Code is running within the venv.  Is there a setting within the extension that I may be missing?

**Comment by DonJayamanne** [comment]
please could you execute the following two commands:  
```which python```  
```which pylint```

**Comment by RAbraham** [comment]
I have a similar issue. I notice that `pylint` only complains on files and modules within my project and not on modules that are in `site-packages` (e.g. `requests` library) or the  `sys` module for e.g. Where would you like us to run `which python` and `which lint`. I ran it within the terminal within VS Code and it didn't find pylint but unless I am mistaken, that is kind of expected as I did not activate my virtual environment. Once I activated it, it found `pylint` in my virtual environment. My `python.pythonPath` is an absolute path to the binary in virtual environment.

**Comment by RAbraham** [comment]
I just disabled `pylint` and installed `flake8` and I don't get that type of warning(.. unable to import..) anymore.

**Comment by MatthewGieger** [comment]
Any update on this? I'm also running into the same issue.

**Comment by DonJayamanne** [comment]
@MatthewGieger 
Please could you provide some more information, details of your workspace settings, OS, python version (virtual environment), etc.

**Comment by meichthys** [comment]
@DonJayamanne 

Here's a screenshot of my 'Problems' panel:
![image](https://user-images.githubusercontent.com/10717998/30445470-06d85450-9954-11e7-8c4a-01fb2253fdcb.png)


My setup is:
OS: Windows 7 (but also tested on OSX 10.13)
Python: 3.6
Virtual Environment: Yes
VSCode Version: 1.16.0
Workspace Settings:

```
{
    "python.pythonPath": ".venv\\Scripts\\python.exe",
    "python.venvPath": "${Workspace}\\.venv\\",
    "python.linting.pylintArgs": ["--disable=E0611"]
}
```

Related User Settings:
```
{
    "python.pythonPath": "${workspaceRoot}/.venv/Scripts/python.exe",
    "python.venvPath": "${workspaceRoot}/.venv",
    "python.linting.pylintPath": "${workspaceRoot}/.venv/Scripts/pylint.exe",
    "python.linting.pylintArgs": ["--disable=E1101"]
}
```
And for reference i'm getting this error in my main.py and all the modules under 'lib'. Here's my project directory structure:
![image](https://user-images.githubusercontent.com/10717998/30445768-1971d888-9955-11e7-8439-f2f6a9f48fed.png)

And my imports from main.py:
![image](https://user-images.githubusercontent.com/10717998/30445583-733c3ada-9954-11e7-8770-1e70542c6cac.png)

And my imports from a module inside 'lib':
![image](https://user-images.githubusercontent.com/10717998/30445606-856a76b8-9954-11e7-88e9-236efddf15bc.png)

Let me know if there's anything else that would help.

**Comment by DonJayamanne** [comment]
This isn't the same issue, you're having issues importing your own packages.

**Comment by DonJayamanne** [comment]
Try running pylint from command line with the current working directory as your workspace. You'll have the same problem. I believe the solution is to set PYTHONPATH appropriately.
