### ISSUE TITLE
Unhelpful automatic indentation behavior

### ISSUE THREAD

**Issue by gandhis1** [DonJayamanne/pythonVSCode#666]
So it appears there's some automatic indentation being applied, but it is not doing it correctly. 

In the GIF below, you can see me add a parenthesis to the end of a line to close a multi-line expression. After doing so, PythonVSCode automatically indents back to the beginning of the line. This is not the desired behavior. I have to manually re-indent the line, which is shown below as well. You can even see the green line showing up, which is the PyCodeStyle linter complaining about the incorrect indentation. 

![indentation](https://cloud.githubusercontent.com/assets/21064086/22156118/e0519dfa-deff-11e6-9bdd-01d7f336d8d3.gif)

**Comment by DonJayamanne** [comment]
Unable to replicate this issue, please try disabling the python extension and confirm it still exists.
This looks like a result of some other extension or other.

**Comment by DonJayamanne** [comment]
If still persists, it is possible you have auto formatting turned on, and in that case you need to configure the formatter you have used.

**Comment by gandhis1** [comment]
1) I uninstalled all extensions besides Python, just to be sure.

2) I do not believe I have any auto formatting turned on. My workspace JSON is empty and my user JSON is below:

`// Place your settings in this file to overwrite the default settings
{
    // "terminal.integrated.shell.windows": "C:\\IntelPython27\\Scripts\\ipython.exe",

    "files.exclude": {
        "**/*.git": true,
        "**/*.svn": true,
        "**/*.hg": true,
        "**/*.DS_Store": true,
        "**/*.pyc": true,
        "**/*.sln": true,
        "**/*.suo": true,
        "**/*.vssscc": true,
        "**/*.vsspcc": true,
        "**/*.vspscc": true,
        "**/*.TMP": true,
        "**/*.pyproj": true
    },

    "editor.wrappingColumn": -1,

    "editor.rulers": [79],

    "python.autoComplete.extraPaths": [
        "C:\\IAS-Auto-ON-2013-x64_20160726.1"
    ],


    // Unit-testing from pyTest enabled
    "python.unitTest.pyTestEnabled": true,
    
    // Linting settings
    "python.linting.enabled": true,
    "python.linting.pylintEnabled": false,
    "python.linting.flake8Enabled": true,

    // Auto-save settings
    "files.autoSave": "off",
    "workbench.activityBar.visible": true,
    "window.zoomLevel": 0
}`

**Comment by DonJayamanne** [comment]
Have you tried uninstalling the python extension and trying this out? I can't replicate this at my end, also there is no code to format text when you type ")"

**Comment by gandhis1** [comment]
I uninstalled the Python extension and still get this behavior on a blank file. Should I report this in the VSCode repository? Any ideas what this could be?

**Comment by gandhis1** [comment]
This is being fixed in https://github.com/Microsoft/vscode/issues/19303
