### ISSUE TITLE
Linting problem with CNTK / NumPy

### ISSUE THREAD

**Issue by davidarh** [DonJayamanne/pythonVSCode#667]
Hello, I am running a virtual machine on azure with CNTK. I am using a virtual machine template for machine learning with GPU capacity. 

Once I install the plugin, Python works, but linting is really off. Most of the code is underlined red, and green. How can I correct this?

This same thing happens on a local machine, where I installed the latest versions of CNTK, VS COde and Python plugin.

Please see the attached image.
![linting](https://cloud.githubusercontent.com/assets/25058566/22159005/f93d9906-df0c-11e6-9234-26756ba960c2.png)

**Comment by gandhis1** [comment]
Can you specify what the errors are? This may be related to the issue I reported here https://github.com/PyCQA/pylint/issues/1161

**Comment by davidarh** [comment]
There error is E0401: Unable to import 'MODULE NAME'

It's as if non standard libraries are not detected, or as if PYLINT were searching for modules in one folder, and then when python runs, it were using another python kernel with the modules that weren't found before.

Is there any way to know what kernel PYLINT is using?

**Comment by DonJayamanne** [comment]
@davidarh 
Please confirm you have Pylint, and the rest of your python modules installed in the same Python environment.
Apologies for the delay in replying to your issue.

**Comment by DonJayamanne** [comment]
This should be resolved in the latest version.
