### ISSUE TITLE
How to use an Anaconda environment with VS Code?

### ISSUE THREAD

**Issue by gc435** [DonJayamanne/pythonVSCode#669]
## Environment data
VS Code version:  1.8.1
Python Extension version:  0.5.6
Python Version:   3.5.2
OS and version:    OSX 10.11.6

## Actual behavior

VS Code appears to use the version of Python installed by Anaconda (as determined by `sys.version`), but not the Anaconda environment which was active when I launched VSC from the command line.  For example, Python in VSC can't find modules which are only installed in an Anaconda environment.

## Expected  behavior

Expected to use a selected Anaconda environment.

## Steps to reproduce:  
-  Activate an Anaconda environment with `source activate my-env1`
-  Install a module into that environment with `conda` or `pip`
-  Attempt to find that module with `import` in a Python file run in VSC with `code file.py` from the command line

## Settings  

Your settings.json:   
```json
    "python.pythonPath": "/Users/me/anaconda/envs/my-env1/bin/python"

```

**Comment by gc435** [comment]
Resolved.  The problem was specific to the GPU version of TensorFlow, which relies on CUDA.  Various CUDA environment variables were set in `.bash_profile` on OSX, and they were not picked up by VSC.  I moved those environment variables to `bashrc` and now all works as expected.

**Comment by Revan007** [comment]
When i tried launching VSC, I get this...

ERROR anaconda api.vscode update_config:963 [Errno 13] Permission denied: '/home/revaapriyan/.config/Code/User/settings.json'

have also changed the permission of the file ".config/Code/User/settings.json" to read and write using "chmod" command
