### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by leandrobrunner** [DonJayamanne/pythonVSCode#67]
Highly elevated CPU usage by the multiple Python processes, and at close a window of VSCode these are not freed.
![screenshot](https://cloud.githubusercontent.com/assets/1664991/14337593/d4c241b2-fc45-11e5-8f38-ec584d024957.png)

**Comment by DonJayamanne** [comment]
Hi, please could you try  closing vs code all together. Theses processes are used when a python Extension is loaded. How ever when vs code is closed, these should be released.

**Comment by leandrobrunner** [comment]
It is a eventual problem. When VSCode is completely closed, the Python processes sometimes are kept, in others not, and sometimes are kept some.
But in general it works correctly.

**Comment by DonJayamanne** [comment]
Reopening as this needs to be fixed, in order to reduce this unnecessary memory usage.

**Comment by DonJayamanne** [comment]
Closing this as this will be resolved in #18
