### ISSUE TITLE
Request for future releases 

### ISSUE THREAD

**Issue by emrahyigit** [DonJayamanne/pythonVSCode#670]
Hello,

First of all thank you for this great extension It helps us a lot. I just wonder how close we are to the following screen, I already changed my shell to python.exe and made some changes on the code for continous interaction on that console. But it would be great if we can integrate jupyter console to vscode. 

Thank you for advance. 

![python_vscode](https://cloud.githubusercontent.com/assets/9334985/22240840/646294a0-e225-11e6-94c4-ffaf169c2f5c.jpg)

**Comment by talkaminker** [comment]
If we could have this + cell mode working + variable explorer (not only in debug mode) I will switch to vscode from spyder in a heartbeat.

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/vscodeJupyter#7
