### ISSUE TITLE
Intellisense not working properly

### ISSUE THREAD

**Issue by joaobpedro** [DonJayamanne/pythonVSCode#671]
## Environment data
VS Code version:  1.8.1
Python Extension version:  0.5.4
Python Version:   Anaconda 2.4.1, Python 2.7.13 64-bit
OS and version:   Windows 7 (version 6.1.7601) 

## Actual behavior
When right click on variable, peek definition and go to definition no longer available, still available for other languages, such html
Extract method or varibale gives: command 'python.refactorExtractMethod' not found

## Steps to reproduce:  
-  always there, I just need to load any python file and intellisense no longer works properly 
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
{
    "http.proxy": "http://XXXXXXXXXXX",
    "http.proxyStrictSSL": false,

    //editor options
    "window.openFilesInNewWindow": false,
    "editor.fontSize": 16,

    //python
    "python.linting.pylintEnabled": false,
    "python.autoComplete.addBrackets": true

}
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by joaobpedro** [comment]
Re-install the extension and it is now working normally

**Comment by fredrikaverpil** [comment]
This happened to me too... weird. A reinstall fixed it for me too.
