### ISSUE TITLE
Indicating Pylint not installed but it is, and its failing with ENOENT

### ISSUE THREAD

**Issue by cicorias** [DonJayamanne/pythonVSCode#672]
## Environment data
VS Code version:  
1.8.1

Python Extension version:
0.5.6  

Python Version:  
2.7.12

OS and version:    
Windows 10 14393.693

## Actual behavior
After install and restart of extension, getting the following set of errors indicating that Pylint is not installed although it is.
<img width="1047" alt="pylint" src="https://cloud.githubusercontent.com/assets/1080406/22273622/d7fa6cf0-e2f5-11e6-9bfe-910752596275.PNG">
<img width="1030" alt="pylint1" src="https://cloud.githubusercontent.com/assets/1080406/22273626/db461bb6-e2f5-11e6-8a5e-8e36b58ccbeb.PNG">

C:\g\ethereum\python\btcrelay>python -m pip install pylint
                      Requirement already satisfied: pylint in c:\python27\lib\site-packages
Requirement already satisfied: mccabe in c:\python27\lib\site-packages (from pylint)
Requirement already satisfied: isort>=4.2.5 in c:\python27\lib\site-packages (from pylint)
Requirement already satisfied: six in c:\python27\lib\site-packages (from pylint)
Requirement already satisfied: configparser; python_version == "2.7" in c:\python27\lib\site-packages (from pylint)
Requirement already satisfied: backports.functools-lru-cache; python_version == "2.7" in c:\python27\lib\site-packages (from pylint)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\python27\lib\site-packages (from pylint)
Requirement already satisfied: astroid<1.5.0,>=1.4.5 in c:\python27\lib\site-packages (from pylint)
Requirement already satisfied: wrapt in c:\python27\lib\site-packages (from astroid<1.5.0,>=1.4.5->pylint)
Requirement already satisfied: lazy-object-proxy in c:\python27\lib\site-packages (from astroid<1.5.0,>=1.4.5->pylint)

## Expected  behavior
Normal linting and no error messages
## Steps to reproduce:  
-  fresh install of VS code
-  install extension
- open a PY file then await and respond to installing pylint

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
{}
```   
## Logs
Output from ```Python``` output panel  
```
C:\g\ethereum\python\btcrelay>python -m pip install pylint
                      Requirement already satisfied: pylint in c:\python27\lib\site-packages
Requirement already satisfied: mccabe in c:\python27\lib\site-packages (from pylint)
Requirement already satisfied: isort>=4.2.5 in c:\python27\lib\site-packages (from pylint)
Requirement already satisfied: six in c:\python27\lib\site-packages (from pylint)
Requirement already satisfied: configparser; python_version == "2.7" in c:\python27\lib\site-packages (from pylint)
Requirement already satisfied: backports.functools-lru-cache; python_version == "2.7" in c:\python27\lib\site-packages (from pylint)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\python27\lib\site-packages (from pylint)
Requirement already satisfied: astroid<1.5.0,>=1.4.5 in c:\python27\lib\site-packages (from pylint)
Requirement already satisfied: wrapt in c:\python27\lib\site-packages (from astroid<1.5.0,>=1.4.5->pylint)
Requirement already satisfied: lazy-object-proxy in c:\python27\lib\site-packages (from astroid<1.5.0,>=1.4.5->pylint)
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
Linting with pylint failed.
You could either install the 'pylint' linter or turn it off in setings.json via "python.linting.pylintEnabled = false".
Error: spawn pylint ENOENT


```

**Comment by gandhis1** [comment]
This looks like it may be related to #505

**Comment by cicorias** [comment]
yea, just figured out that adding the `"python.pythonPath": "C:\\Python27\\"` in user settings fixes this.  Not sure if you want to close or address this in deployment, etc.

**Comment by DonJayamanne** [comment]
This is an indication that c:\python27\python.Exe is not the same python interpreter as the default. You might want to check your environment path settings.
