### ISSUE TITLE
Debugger: show variables in multiple ways: hex, dec, ascii, binary

### ISSUE THREAD

**Issue by GPContributors** [DonJayamanne/pythonVSCode#673]
## Environment data
VS Code version:  1.8.1
Python Extension version:  0.3.24
Python Version:   3.5
OS and version:    Windows 7

It would be nice to show all alternate forms of a variable into the debugger -- hex, dec, ascii, binary -- or have a way to switch between types in the UI.

thanks

**Comment by DonJayamanne** [comment]
This would be a feature request for the VS Code editor.

**Comment by AdamBJ** [comment]
Seems like the VS Code devs are saying it's up to the extension writers: https://github.com/Microsoft/vscode/issues/28025
