### ISSUE TITLE
unittest unhandled exception in thread after running tests

### ISSUE THREAD

**Issue by dosentmatter** [DonJayamanne/pythonVSCode#674]
## Environment data
VS Code version:  1.8.1
Python Extension version:  0.5.6
Python Version:   3.5.2 and 3.6.0
OS and version:    macOS Sierra Version 10.12.3

## Actual behavior
I am using the standard unit testing framework, unittest. After running my tests, whether they pass or not and whether I run a single test or multiple tests, I get "Unhandled exception in thread started by" after the OK or FAILED. There is nothing after the "by" it is started "by<blank>". It does not seem like a big problem though since tests are still run.
## Expected  behavior
I should not get the "Unhandled exception in thread started by" message.
## Steps to reproduce:  
-  Create a project folder
-  Create a file called test_unit.py and put this in it:

```
import unittest

class TestUnit(unittest.TestCase):

    def test_unit(self):
        pass
```

- run all or the single unittest with the settings.json below.
- Test passes with OK but you get "Unhandled exception in thread started by".

## Settings  
Your launch.json (if dealing with debugger issues):  
**none**
Your settings.json:   
```
// Place your settings in this file to overwrite default and user settings.
{
    "python.unitTest.unittestEnabled": true,

    "python.unitTest.unittestArgs": [
        "-v",
        "-p",
        "test_unit*.py"
    ]
}
```   
## Logs
Output from ```Python``` output panel  
```
test_unit (test_unit.TestUnit) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
Unhandled exception in thread started by 
```   
Output from ```Console window``` (Help->Developer Tools menu)
**none**

**Comment by tomhunter-gh** [comment]
I am getting the same or very similar.  On the first go I am able to debug tests but I can't debug a second time without restarting VSCode.  Not much of an error, just
```
----------------------------------------------------------------------
Ran 1 test in 0.752s

OK
Unhandled exception in thread started by 
READY
```

The status bar has the exclamation mark and "Running Tests" and spinner spinning forever..

```
Visual Studio Code
Version 1.9.0
Commit 27240e71ef390bf2d66307e677c2a333cebf75af
Date 2017-02-02T08:31:00.827Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```

VSCode Python extension version 0.5.8
Python 3.6 (Anaconda)
Windows 10 (latest - "device up to date")

**Comment by dosentmatter** [comment]
I also tested the debug all/single test(s) but this was a couple days back so I don't remember the specifics. It always worked on the first go and I was able to get to a breakpoint. On the next tries, it would be stuck on running tests. This is similar to what @tomhunter-gh said.

If I keep trying to cancel the currently debug test that is running by starting another debug, it would eventually work sometimes. Though it's not clear when and why it would sometimes work.

**Comment by tomhunter-gh** [comment]
I noticed that if I debug a test (using the hyperlink above method name) and then when I'm stopped on a breakpoint hit the restart button, I get the following error message:

> There was an error in starting the debug server. Error = {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":3000}

I also noticed that the test / debug hyperlinks don't appear when you open VSCode if the test file is open (due to file being open in last session and restored) - you have to close the file and re-open to get the hyperlinks to appear.

**Comment by tomhunter-gh** [comment]
I also noticed that I get the following error in the Python Test Log on startup after it lists out the tests in my project:

> C:\Users\tomhu\Anaconda3\lib\site-packages\IPython\html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
>   "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)

**Comment by RAbraham** [comment]
What I have discovered from trial and error is:

1) If I keep the suggested settings below, `Run All Unit Tests` works but not clicking on the `Run Test` visual button above each test.  I get `No tests ran, please check the configuration settings for the tests.` 
```json
 "python.unitTest.unittestArgs": [
        "-v",
        "-s",
        ".",
        "-p",
        "*test*.py"
    ]
```
When I changed the `.` above to explicitly point to my tests i.e `${workspaceRoot}/myproject/tests`, the visual `Run Test` above each test worked for me. 

It would be nice if I could just specify `${workspaceRoot}` and the `unittest` framework would recursively find my tests for me. 

And.. thank you for your work on this plugin :)

**Comment by BlacKCaT27** [comment]
Is there any update on this? I'm seeing this same issue and it's making it rather hard to use VS Code to manage unit tests. 

What I've observed is that whatever is breaking, is breaking part of the UI in VS Code involving the "At a glance" test results in the status bar on the bottom of the screen.

For example, in my project I have 50 unit tests. If all of them pass, I see the green "&#10004; 50" in the status bar, but nothing else. If one of my tests fails, I only see the green checkmark and some value representing all the tests that passed before that test failed. It does not appear to run additional tests even though I have fail-fast turned off. But I don't see anything in the status bar relating to the number of failed or un-run tests. 

In the "Python Test Log" output window, I see:

----------------------------------------------------------------------
Ran 50 tests in 0.335s

OK
Unhandled exception in thread started by 

At the end of my test results when all tests pass. On a failure, I see:

test_assert (<my unit test>) ... FAIL
Unhandled exception in thread started by 


If I check the developer tools console output, I see:

[Extension Host] Error: read ECONNRESET   extensionHost.ts:293

Which in viewing the source, shows me this statement erroring in the logExtensionHostMessage method:

		// Send to local console unless we run tests from cli
		if (!this.isExtensionDevelopmentTestFromCli) {
			console[logEntry.severity].apply(console, consoleArgs);
		}


Really hope there's a simple fix here somewhere. I don't know VS Code extension code well enough to have time to make a PR, but if you need any more information please let me know.

**Comment by DonJayamanne** [comment]
>For example, in my project I have 50 unit tests. If all of them pass, I see the green "✔ 50" in the status bar, but nothing else. If one of my tests fails, I only see the green checkmark and some value representing all the tests that passed before that test failed. 

Apologies for never getting back on this.
All the output of the unit tests are displayed in the ```Python Test Log``` output panel (this is displayed at the bottom along with other output panels such as ```Tasks```, ```Git```, etc.

**Comment by DonJayamanne** [comment]
@BlacKCaT27 please let me know if this has been resolved.
@dosentmatter are you still experiencing this issue?

**Comment by dosentmatter** [comment]
@DonJayamanne, I still have the same problem. In the image, see "Unhandled exception in thread started by".
This happens if I click "Run Test" or if I click the green check mark on the bottom left > "Run All Tests". The tests are run but I'm not sure what's causing that error message.
![image](https://user-images.githubusercontent.com/5732253/32209147-fc2df89a-bdc3-11e7-9852-cd26c7b47235.png)

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#78
