### ISSUE TITLE
Jedi not required anymore?

### ISSUE THREAD

**Issue by fredrikaverpil** [DonJayamanne/pythonVSCode#675]
I see the instructions on installing jedi (`pip install jedi`) was removed from the Quickstart in the README. 

Is this bundled with pythonVSCode now, shomehow, or how come it isn't needed anymore?

**Comment by DonJayamanne** [comment]
It has always (from day 1) been bundled with the extension. However you have the option of telling the extension to use your own custom version of Jedi (for those 0.001% making changes to Jedi)

**Comment by fredrikaverpil** [comment]
Thanks for the clarification!
