### ISSUE TITLE
Nose2 UnitTest support

### ISSUE THREAD

**Issue by adam-smith101** [DonJayamanne/pythonVSCode#680]
Is it possible to use nose2 instead of the regular nose? nose is not being actively developed and nose2 is its successor so hopefully you can add nose2 support for it as well? (if it's not possible already)

**Comment by DonJayamanne** [comment]
Will look into this soon.

**Comment by DonJayamanne** [comment]
Looking a bit complicated. 
Its not possible to get a list of the unit tests without running them
```
nose2 --collect-only 
```
doesn't work.
Any help here would be appreciated.
