### ISSUE TITLE
Cell numbered bigger than 10 doesn't recognized as ipython cell

### ISSUE THREAD

**Issue by openingnow** [DonJayamanne/pythonVSCode#681]
## Environment data
VS Code version:  1.8.1
Python Extension version:  0.5.6
Python Version:   3.6.0
OS and version:   macos 10.12.3

## Actual behavior
Not recognized as ipython cell(`run cell` button disappears) when I fill 10+ number to `# In[]`

## Expected  behavior
Create `run cell` button

I think [regex that matches cell](https://github.com/DonJayamanne/pythonVSCode/blob/master/src/client/jupyter/common/cellHelper.ts#L6) need to be `# In\[\d*?\]`, not `# In\[\d?\]` but as I'm not sure, I'll leave as issue.

**Comment by DonJayamanne** [comment]
@openingnow thanks for identifying the issue. Fixed
