### ISSUE TITLE
Feature Suggestion: add python interpreter args to launch configuration

### ISSUE THREAD

**Issue by bsphere** [DonJayamanne/pythonVSCode#682]
This is very useful for debugging pyspark programs and adds the ability to add spark-submit args such as "--packages" and "--master"

**Comment by DonJayamanne** [comment]
You can add custom arguments to the python interpreter when debugging as follows:  
- https://github.com/DonJayamanne/pythonVSCode/wiki/Debugging/_edit#args

**Comment by bsphere** [comment]
@DonJayamanne those are args to the python program and not for the python interpreter,
e.g. `spark-submit --packages ....jar --conf spark.something.something=something program.py arg1`

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#75
