### ISSUE TITLE
FR: Allow args to be defined from "user input" by using command.extention 

### ISSUE THREAD

**Issue by mike-pt** [DonJayamanne/pythonVSCode#684]
While discussing the ability to get user input to define program or args (see [vscode#9544](https://github.com/Microsoft/vscode/issues/9544#issuecomment-276166691) ) I noticed I could do this with the python debugger for "args".

Since `args` expects an array not a strings this is at the moment impossible, however if args would be changed to string and (as suggested in the GHI) the Pyhton Debbuger impletments its own `${command.extension.python-debug.getCommandline}` we could easy promt the "user" for args, this would be very handy when testing an appp for a bunch of different scenarios that change according to those args.

Please consider this as a FR

**Comment by DonJayamanne** [comment]
Will work on this soon.

**Comment by mike-pt** [comment]
Awesome, btw in the meantime I noticed that vscode fails to parse the args if I use "--".

I.E. we have a project where we use getopt and when I pass some arg with "--something" getops fails as if I've entered something unavailable, yet it works just fine in the console (outside vs code/debugger).

I'm just adding args as:
```
args : [
"-a true",
"--se section"
]
```

**Comment by DonJayamanne** [comment]
Try the following:
```
args : [
"-a",  "true",
"--se", "section"
]
```

**Comment by mike-pt** [comment]
ah I see now I was doing it wrong, in fact that would break things specially for booleans as it would add a space (`" true"`), I did not notice before cause I was using "-atrue" there and that was was also working.

Thanks for the clarification, can't wait for the FR though as that simplifies things when I want to test different "arg cases" one after the other, ofc for now I can still just change args, or add a new configuration to launch.json

**Comment by mike-pt** [comment]
Any idea if this is still going to land soon?

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#77
