### ISSUE TITLE
Highlight current debug line on debug remote

### ISSUE THREAD

**Issue by imaia** [DonJayamanne/pythonVSCode#687]
## Environment data
VS Code version: 1.8.1  
Python Extension version:  
Python Version:   3.5
OS and version:    debian (docker)

## Actual behavior
Remote debug works and stops on breakpoint, but doesn't highlight the line it is evaluating

## Expected  behavior
It should highlight the line it is evaluating, just like the local debug

## Steps to reproduce:  
- Create a flask app with debug remote and ptvsd 
- connect
- create a breakpoint
- trigger the breakpoint

**Comment by ychab** [comment]
Same issue for me, but with a Django project. I discover that threading was the guilty (i.e : I need to start the builtin server without thread, aka ``python manage.py runserver 0.0.0.0:8000 --nothreading --noreload``. Maybe you have a similar issue with Flash...?

**Comment by kmpm** [comment]
I have, what looks like, the same issue with web.py

**Comment by Priyank30** [comment]
I am seeking the same feature. Highlighting current debug line will really boost productivity at some level.

**Comment by schroederen** [comment]
Same problem here (though not developing something web related, but a machine learning model using Tensorflow while trying to remote debug from a Windows machine to a Ubuntu server).

**Comment by DonJayamanne** [comment]
@imaia Apologies for never getting back to you on this. Are you still experiencing this issue.

**Comment by imaia** [comment]
Hello @DonJayamanne I'll try again and let you know. My work around for it was not to use vs code for task until further changes.

**Comment by DonJayamanne** [comment]
@imaia If you do come across the issue, please raise it in the Microsoft repo (which is where this project is now maintained).
https://github.com/Microsoft/vscode-python
