### ISSUE TITLE
Add remote debug auto reconnect

### ISSUE THREAD

**Issue by imaia** [DonJayamanne/pythonVSCode#689]
## Environment data
VS Code version:  1.8.1
Python Extension version:  
Python Version:   python3
OS and version:    

## Actual behavior
If project restarts, remote debug won't auto-reconnect.

## Expected  behavior
It should auto-reconnect.

**Comment by DonJayamanne** [comment]
Unfortunately this isn't supported at this stage.
Similar to https://github.com/DonJayamanne/pythonVSCode/issues/334

Was investigated and left for now, as this required a major refactor to the debugger infrastructure code.
