### ISSUE TITLE
How to use it in Visual Studio Code for Mac OS?

### ISSUE THREAD

**Issue by leniel** [DonJayamanne/pythonVSCode#69]
I was able to install the extension but I don't know what path to provide for the configuration part:

```
"pythonPath": "/Library/Frameworks/Python.framework/Versions/3.5/Resources/Python.app"
```

I set a breakpoint and hit the command Debug in View => Debug.

Nothing happens. :(

**Comment by McNull** [comment]
Open a terminal and type `which python` (or `which python3`) to grab the path of the interpreter. Press `cmd+,` in _Visual Studio Code_ to open the preferences and add the following key:

    "python.pythonPath":  "path/to/python"

Press `F5` (or press the _play_ button in the debug view). 

You will be prompted to specify a _Debug Environment_ if you haven't done so already. Select or type _Python_ to create the default launch configuration (found in `./vscode/launch.json`). Open the python file again and press `F5` again to attach the debugger.

**Comment by leniel** [comment]
Thanks for the reply @McNull! I'm getting a `spawn python3 ENOENT` error in the Debug console.

My Visual Studio Code version is 0.10.11. When I click the stop button it crashes VS Code. :(

See the print screen:

![image](https://cloud.githubusercontent.com/assets/764854/14406968/db33781e-fe8d-11e5-93ca-fb11b6d54798.png)

My `launch.json` has this:

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Python",
			"type": "python",
			"request": "launch",
			"stopOnEntry": true,
			"program": "${file}",
            "pythonPath": "python3",
			"debugOptions": [
				"WaitOnAbnormalExit",
				"WaitOnNormalExit",
				"RedirectOutput"
			]
		},
		{
			"name": "Python Console App",
			"type": "python",
			"request": "launch",
			"stopOnEntry": true,
			"program": "${file}",
			"externalConsole": true,
			"debugOptions": [
				"WaitOnAbnormalExit",
				"WaitOnNormalExit"
			]
		},
		{
			"name": "Django",
			"type": "python",
			"request": "launch",
			"stopOnEntry": true,
			"program": "${workspaceRoot}/manage.py",
			"args": [
				"runserver",
				"--noreload"
			],
			"debugOptions": [
				"WaitOnAbnormalExit",
				"WaitOnNormalExit",
				"RedirectOutput",
				"DjangoDebugging"
			]
		}
	]
}
```

**Comment by McNull** [comment]
Try removing that `"pythonPath": "python3"` from your `launch.json`. It might override the `pythonPath` from the global settings.

**Comment by leniel** [comment]
Yep... it worked! Thank you very much for your help @McNull ... may God bless your life even more. :)
