### ISSUE TITLE
Custom Line Length (C0301:Line too long)

### ISSUE THREAD

**Issue by Abdullah2993** [DonJayamanne/pythonVSCode#691]
How to change the line length enforced by PEP8 to set it other then 100
```
[pylint] C0301:Line too long (104/100)
```

**Comment by DonJayamanne** [comment]
This is an error from pylint, hence you need to configure pylint not this extension.  
Instructions as follows:   
- Create a ```.pylintrc``` with the following contents
```
# Maximum number of characters on a single line.
max-line-length=900
```

**Comment by courteouselk** [comment]
I added the following to `settings.json` in VSCode to solve this:

````
    "python.linting.pylintArgs": [
        "--max-line-length=120"
    ],
````
