### ISSUE TITLE
Question/Idea: Lint full directory/project

### ISSUE THREAD

**Issue by mdalpi** [DonJayamanne/pythonVSCode#694]
Hi.

There's any way to lint the whole project directory instead of only open files (and the errors will be displayed accordingly, error by file in problems view)?

I think it'll be great to have this with Flake8 at least (maybe PyLint is a little slow to lint the whole project after every save).

Thanks 😄

**Comment by robomojo** [comment]
I have been searching for the same thing and it seems to be a missing vscode feature.
https://github.com/Microsoft/vscode-eslint/issues/91
https://github.com/Microsoft/vscode/issues/13953
Currently the method of doing this with pylint is just to use the terminal ```pylint . -E```, but it would be nice if that output fed directly into the problems panel so I could click through to the errors.

**Comment by DonJayamanne** [comment]
Ability to run as a task and report problems. (contribute problem matchers)

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#82
