### ISSUE TITLE
Suggestion regarding displaying results in cell mode.

### ISSUE THREAD

**Issue by estw272** [DonJayamanne/pythonVSCode#696]
Hi,

First of all, let me say thank you for your work on this extension, it's amazing.

Right now it seems that Results window is displaying output when the kernel completes executing a cell. I don't know if it's even possible to implement, but it would be really nice if the results window could update as often as there is new output.

For example:
```
#%%
for number in range(1000000):
    print(number)
```

When this cell is executed, the numbers will be printed all together in the end after the loop is completed. Is it possible to update results window on every iteration? 
Running algorithms on large datasets can take a long time and seeing intermediate results is very helpful.

**Comment by DonJayamanne** [comment]
Sure thing, anything is possible. The challenge is trying to get it done in a reasonable amount of time, along with the other items on my plate. 
Will look into this soon (currently looking at all jupyter issues)

**Comment by DonJayamanne** [comment]
This has been fixed in a separate extension that will be published this weekend. 
https://github.com/DonJayamanne/vscodeJupyter

It will be published very soon
