### ISSUE TITLE
disable pylint for certain directories and/or files (high cpu)

### ISSUE THREAD

**Issue by therealmarv** [DonJayamanne/pythonVSCode#697]
## Environment data
VS Code version:  1.8.1
Python Extension version:  0.5.6
Python Version:   2.7.13
OS and version:   macOS 10.12.3

Is it possible to disable pylint for certain files or directories? I have a huge nosetest file and pylint is going regularly crazy on saving new edits to that file and using all my CPU 100%. I have no problem for using pylint for smaller files. [Link to nose test file (4825 LOC)](https://github.com/Scifabric/pybossa/blob/master/test/test_web.py)

**Comment by DonJayamanne** [comment]
You can add a setting as follows:
```json
"python.linting.ignorePatterns":[
    "pattern to ignore the file",
    "define other patterns",
    "**/site-packages/**/*.py"
]
```

**Comment by therealmarv** [comment]
@DonJayamanne 

Hi, I know you closed that issue...
I just wanted to know if you think this kind of issue is solvable in long term. While using PyCharm or Anaconda Plugin for Sublime I don't have this kind of high CPU issue. This problem is replicable on large Python code files and I do not want to exclude special files based on my angryness when looking at my CPU monitor ;)

Maybe you open this issue again for discussion. Or maybe I will open a new one?
Is it possible to cache linting result and only have new stuff linted again? Maybe with a python service running in background?

**Comment by DonJayamanne** [comment]
The high CPU usage is because of pylint (as you have identified), hence an issue

**Comment by DonJayamanne** [comment]
FYI, linting is done in the background (separate python process), so the high CPU we'll be from the python process which will not effect the performance of the editor.

**Comment by DonJayamanne** [comment]
Oops

**Comment by fcusano9** [comment]
Where exactly do you add that setting to disable pylint.

**Comment by DonJayamanne** [comment]
Go into settings.json and add the following setting:
```json
"python.linting.pylintEnabled": false,
```

**Comment by DonJayamanne** [comment]
The latest version of the extension has resolved this.
I'm killing off unnecessary python (processes started in the background to run linters)
