### ISSUE TITLE
Peek Defintion/Goto definition in combination with Cloud sdk and Flask blueprints not working

### ISSUE THREAD

**Issue by cricque** [DonJayamanne/pythonVSCode#699]
## Environment data
VS Code version:  v1.9.0
Python Extension version: latest  
Python Version:   2.7.12
OS and version:   Linux Mint

## Actual behavior
goto definition/peek definition not working (not related to the latest version), I haven't seen it working actually. 

## Expected  behavior
goto definition/peek definition

## Steps to reproduce:  
- use google cloud sdk (for app engine)  
- use flask blueprints

I would be nice to see it working. I have been doing without for quite a while
My guess is this is related to the combination of cloud sdk and Flask blueprints

## Settings  

Your settings.json:   
{
    "python.pythonPath": "/home/mylogin/.virtualenvs/py27/bin/python -b",
    
    "python.autoComplete.extraPaths": [
        "/opt/google-cloud-sdk",
        "/opt/google-cloud-sdk/lib",
        "/opt/google-cloud-sdk/lib/googlecloudsdk" 
    ],
    
    "python.linting.enabled": true,
    "python.linting.pylintEnabled": false,
    "python.linting.lintOnSave": true,
    "python.linting.prospectorEnabled": false,
    "python.linting.mypyEnabled": false,
    "python.linting.flake8Enabled": true,
    "python.linting.pylintArgs": ["--max-line-length", "175", "--docstring-min-length", "100"],

    // Extension and editor preferences
    "files.insertFinalNewline": true,
    "trailing-spaces.trimOnSave": true,

  	"search.exclude": {
        "**/.git": true,
        "**/.idea": true,
        "**/lib": true,
        "**/.vscide": true,
        "**/static/scripts/files": true,
        "**/tags": true   
    },

    "files.exclude": {
        "node_modules/": true,
         "**/*.pyc": true

    }
}

## Logs
Output from ```Console window``` (Help->Developer Tools menu)
extensionHost.ts:282 [Extension Host] Error: This socket is closed
    at Socket._writeGeneric (net.js:673:19)
    at Socket._write (net.js:725:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Socket.Writable.write (_stream_writable.js:220:11)
    at Socket.write (net.js:651:40)
    at sendCommand (/home/cricque/.vscode/extensions/donjayamanne.python-0.5.7/out/client/providers/jediProxy.js:409:20)
    at JediProxy.sendCommand (/home/cricque/.vscode/extensions/donjayamanne.python-0.5.7/out/client/providers/jediProxy.js:126:16)
    at JediProxyHandler.sendCommand (/home/cricque/.vscode/extensions/donjayamanne.python-0.5.7/out/client/providers/jediProxy.js:538:24)
    at PythonDefinitionProvider.provideDefinition (/home/cricque/.vscode/extensions/donjayamanne.python-0.5.7/out/client/providers/definitionProvider.js:39:38)d.logExtensionHostMessage @ extensionHost.ts:282(anonymous function) @ extensionHost.ts:137emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:282 [Extension Host] ---------------------------d.logExtensionHostMessage @ extensionHost.ts:282(anonymous function) @ extensionHost.ts:137emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98

**Comment by DonJayamanne** [comment]
Please could you remove the ```-b``` command line argument from the python path. That should fix it.  
Adding the ```-b``` will be supported in the next version with the use of environment file (```.env``` file), where you could specify the value for the corresponding [```PYTHONDONTWRITEBYTECODE```](https://docs.python.org/2/using/cmdline.html#envvar-PYTHONDONTWRITEBYTECODE) setting

**Comment by andersea** [comment]
Same issue here. My module starts with:

```python
from flask import Blueprint, request, jsonify
import requests
```
Can't ctrl-click on any of those from flask, but ctrl-click on requests works fine.

My launch.json looks like this:
```json
            "name": "Flask",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${workspaceRoot}/env/bin/python",
            "program": "${workspaceRoot}/env/bin/flask",
```

**Comment by DonJayamanne** [comment]
@cricque Apologies for never getting back to you on this issue. Please let me know if you are still experiencing this issue.
