### ISSUE TITLE
Error on debug single file without launch.json

### ISSUE THREAD

**Issue by st0le** [DonJayamanne/pythonVSCode#700]
## Environment data
VS Code version:  
- VSCode Version: Code - Insiders 1.9.0-insider (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-01T11:45:10.153Z)
- OS Version: Windows_NT ia32 10.0.10240

Python Extension version:  0.5.7

## Actual behavior
Error with the following message
"command 'python.python-debug.startSession' not found"

## Expected  behavior

VsCode should run/debug the python file.

## Steps to reproduce:  
-  Open a single py file and hit F5
-  

## Settings  
Your launch.json (if dealing with debugger issues):   Not applicable
```json
```

**Comment by DonJayamanne** [comment]
@st0le Please could you try this on the standard release build and then open a Python file to test this.
Works at my end.

**Comment by djhyman** [comment]
Same issue running any .py

**Comment by Agnpalm** [comment]
This might be related to Jupyter no longer working in single file mode. Cells aren't marked as cells, and when trying to run a cell anyway the error message "command 'jupyter:execCurrentCell' not found" is displayed. Works as expected when I open the folder instead. This behavior is new in 0.5.7.

**Comment by robinchow** [comment]
I have the same error message, running with a launch.json though.

**Comment by DonJayamanne** [comment]
Fixed 
https://github.com/DonJayamanne/pythonVSCode/commit/e63a59b9df77a95b5ad62c3e799116b930518138

**Comment by st0le** [comment]
@DonJayamanne I've tried it on the Main release, and _none_ of the exec commands (eg. python.execInTerminal) work on single file mode. From the commit, I'm guessing the fix you made fixes only the Jupyter issue. Everything works fine if opened with a folder (even if the file wasn't in the folder that was opened)

**Comment by DonJayamanne** [comment]
Hmm, it works at my end, will try again.

**Comment by fatherofinvention** [comment]
I too am unable to debug or run Python scripts in Visual Studio Code 1.9.0 (most current version) and the Python extension 0.5.7.

When attempting to debug: command 'python.python-debug.startSession' not found

When pressing F5: command 'python.execInTerminal' not found

Thanks in advance, Don!

**Comment by DonJayamanne** [comment]
Yes, I'm able to replicate this. Will look into this asap. Darn.

**Comment by DonJayamanne** [comment]
Yes, fixed with this commit:
https://github.com/DonJayamanne/pythonVSCode/commit/226a1f827723a75dadaca10e1b8426822971af6b

Will publish a new version

**Comment by DonJayamanne** [comment]
Please test the latest version.

**Comment by st0le** [comment]
Confirmed fix on Insiders. I'm sure it's working on the main release. Will report back if not.

Thanks @DonJayamanne . Love the extension
