### ISSUE TITLE
Debugging Google App Engine with multiple services

### ISSUE THREAD

**Issue by zeptoTon** [DonJayamanne/pythonVSCode#701]
## Environment data
VS Code version: 1.9.0 
Python Extension version:  0.5.7
Python Version:   2.7.10
OS and version:   OSX 10.12.2 

## Actual behavior
Debugger startup failed: [Errno 48] Address already in use
ptvsd will encounter the above execption when trying to start the task with multiple service.
Since port "3000" already bind with the main service (main.yaml)
Other services are not able to identify itself to bind with default port. e.g. port 3001 for report service

## Expected  behavior
debug other services, by different port, along with default service
So when debug, we can debug 2 different ports in the same client (is it possible?)
Otherwise, 
we have to config the task.json and only allow at most 1 service.

## Steps to reproduce:  
-  Set more than default service e.g. main.yaml, report.yaml, migrate.yaml, data.yaml
-  config pydev_startup.py
-  build and run with task.json

## Settings  
pydev_startup.py:
``` py
import sys
import os
from google.appengine.api import modules
import traceback
import sysconfig

#Assuming that pdvsd is located in the working folder
sys.path.append(os.getcwd()) 
import ptvsd
#Fee free to change the secret and port number 
#How to rewrite the below line to support multiple services?
ptvsd.enable_attach(secret = 'gae', address = ('0.0.0.0', 3000))

#The debug server has started and you can now use VS Code to attach to the application for debugging
print("Google App Engine has started, ready to attach the debugger")
```

launch.json:  
```json
    {
        "name": "Attach",
        "type": "python",
        "request": "attach",
        "host": "localhost",
        "secret": "gae",
        "port": 3000,
        "remoteRoot": "${workspaceRoot}",
        "localRoot": "${workspaceRoot}",
        "preLaunchTask": "python"
    }    
```   
task.json:   
```json
{
    "version": "0.1.0",
    "command": "python",
    "isShellCommand": true,
    "showOutput": "always",
    "args": [
        "/usr/local/google_appengine/dev_appserver.py",
        "--python_startup_script=${workspaceRoot}/pydev_startup.py",
        "--automatic_restart=no",
        "--max_module_instances=default:1",
        "--enable_sendmail=yes",
        "--port=12082",
        "${workspaceRoot}/app.yaml",
        "${workspaceRoot}/report.yaml",
        "${workspaceRoot}/data.yaml",
        "${workspaceRoot}/migrate.yaml"
    ]
}
```   
## Logs
Output from ```Python``` output panel  
```
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/python/runtime.py", line 140, in main
    execfile(config.python_config.startup_script, global_vars)
  File "{..discard..}/pydev_startup.py", line 12, in 
    ptvsd.enable_attach(secret = 'gae', address = ('0.0.0.0', 3000))
  File "{..discard..}/ptvsd/attach_server.py", line 167, in enable_attach
    server.bind(address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 48] Address already in use
```

**Comment by DonJayamanne** [comment]
Unfortunately its upto the developer to define the port number on which the debugger will be attaching. If your code is launched multiple times (multiple services), then you'd need to some how ensure different ports are assigned for the debug servers to be attacheable.
