### ISSUE TITLE
Wrong margins on results view when using zoom

### ISSUE THREAD

**Issue by gcusso** [DonJayamanne/pythonVSCode#702]
## Environment data
VS Code version:  1.9.0
Python Extension version:  0.5.8
Python Version:   3.5.2
OS and version:   Windows 10

## Actual behavior
When you use a zoom level greater than the default one ('Ctrl+' or 'View/Zoom In') the margins in the results view are too big.

![python_issue1](https://cloud.githubusercontent.com/assets/1783768/22592172/b0c920de-ea18-11e6-8b77-f199efbbeea5.png)

## Expected  behavior
![python_issue2](https://cloud.githubusercontent.com/assets/1783768/22592173/b4119a78-ea18-11e6-9d46-ab0677de6079.png)

## Steps to reproduce

- With this code: 
```
#%%
from IPython.display import Image
Image('http://jakevdp.github.com/figures/xkcd_version.png')
```
- Run cell
- Zoom in (Top bar, View/Zoom in)

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/vscodeJupyter#5
