### ISSUE TITLE
Consider using a language server

### ISSUE THREAD

**Issue by patrys** [DonJayamanne/pythonVSCode#704]
There's a Jedi-based version available at https://github.com/palantir/python-language-server. I've also opened an issue with Jedi to consider providing an official implementation.

Joining forces could mean less code to maintain on the TypeScript side.

**Comment by DonJayamanne** [comment]
My plan is to use that language server, would help with remote development.

**Comment by DonJayamanne** [comment]
@patrys 
https://github.com/palantir/python-language-server/issues/12

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#83
