### ISSUE TITLE
Show __str__ in debug console

### ISSUE THREAD

**Issue by gandhis1** [DonJayamanne/pythonVSCode#705]
Whenever I type in the name of a variable, and just press enter (I.e. no print statement),  I get a long list of every attribute and sub-attribute, which looks like a recursive dir call. I think in most cases this isn't useable because of its lack of readability. A good example is a DataFrame from Pandas. Instead, I believe that this action should print out the __str__  instead.

**Comment by DonJayamanne** [comment]
@gandhis1 please could you provide a screen sample of the issue

**Comment by gandhis1** [comment]
See screenshot below. The first debug console entry is what I would type in, which is usually what someone would type in an IPython console, for instance. In PTVS, for instance, the default debug console was IPython. 

However, this doesn't produce anything all that useful. It looks like it's calling dir() recurisvely to get all the attributes of the dataframe. However, I really think what would be more useful is to print either the `__repr__` or `__str__` of a given object. So when I type out_df, I get the equivalent of what the second debug console statement prints. I would think this could be done even without using IPython console for debugging.

![image](https://cloud.githubusercontent.com/assets/21064086/22752746/b0a35dc0-ee07-11e6-902f-b0e12fabdb7a.png)

See this screenshot of PTVS interactive debug console:

![image](https://cloud.githubusercontent.com/assets/21064086/22752910/2e12769c-ee08-11e6-8df9-bd7012e6e4c2.png)

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#84
