### ISSUE TITLE
No doc string for python built-in

### ISSUE THREAD

**Issue by mrvkino** [DonJayamanne/pythonVSCode#706]
## Environment data
VS Code version:  1.9.0
Python Extension version:  0.5.8
Python Version:   python3.4.2
OS and version:    MacOS Sierra 10.12.3

## Actual behaviour
When typing a built-in function (print, max, min, etc...) or a built-in class (filter, str, etc...) there is no doc string.

![print_doc_string](https://cloud.githubusercontent.com/assets/279511/22622165/69791786-eb01-11e6-82b8-6b5450a4c8b1.jpg)

## Expected  behaviour
I know they are built-in and are generally well known, but it would be great to have a doc string for them also.
![re_compile_doc_string](https://cloud.githubusercontent.com/assets/279511/22622177/b787670c-eb01-11e6-89b3-447903e02857.jpg)
## Steps to reproduce:  
Type print (or any built-in) and look at doc string.
Type re.compile (or any non built-in) and look at doc string

**Comment by DonJayamanne** [comment]
Unfortunately [Jedi](https://github.com/davidhalter/jedi) doesn't provide documentation for some of these built in types.
