### ISSUE TITLE
Upgrade Jedi to latest (0.10.0)

### ISSUE THREAD

**Issue by gandhis1** [DonJayamanne/pythonVSCode#707]
I imagine some of the current shortcomings of autocompletion in Python VSCode would be solved by upgrading to the latest version of Jedi, which was just recently released. 

https://pypi.python.org/pypi/jedi

**Comment by DonJayamanne** [comment]
Unfortunately this will have to wait (probably until the next batch of fixes/changes), as I released an update just a day before this version of Jedi was released.

**Comment by DonJayamanne** [comment]
Updated, will be in the next release
https://github.com/DonJayamanne/pythonVSCode/commit/328b5ea07304d725b852b3f2c4efb0033c30818c
