### ISSUE TITLE
command 'python.python-debug.startSession' not found

### ISSUE THREAD

**Issue by JanBrinker** [DonJayamanne/pythonVSCode#708]
## Environment data
VS Code version:  1.9.0
Python Extension version:  0.5.8
Python Version: 3.5.2
OS and version: macOS 10.12.3

## Actual behavior
When trying to run a Python program via the Debugger I get a notification from VSCode saying: "command 'python.python-debug.startSession' not found"

## Expected  behavior
Python program should execute and VSCode should go into debug mode.

## Steps to reproduce:  
-  Install the named program versions
-  Try to run any Python program

## Settings  
Your launch.json (if dealing with debugger issues):  
```{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Django",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "console": "integratedTerminal",
            "pythonPath": "${workspaceRoot}/projectenv/bin/python",
            "program": "${workspaceRoot}/manage.py",
            "args": [
                "runserver",
                "localhost:8000",
                "--settings=testproj.settings.dev"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "DjangoDebugging"
            ],
            "preLaunchTask": "Initialize environment"
        },
        {
            "name": "Shell",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "console": "integratedTerminal",
            "pythonPath": "${workspaceRoot}/projectenv/bin/python",
            "program": "${workspaceRoot}/manage.py",
            "args": [
                "shell",
                "--settings=testproj.settings.dev"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "DjangoDebugging"
            ],
            "preLaunchTask": "Initialize environment"
        },
        {
            "name": "Tests",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "console": "integratedTerminal",
            "pythonPath": "${workspaceRoot}/projectenv/bin/python",
            "program": "${workspaceRoot}/manage.py",
            "args": [
                "test",
                "sitetester",
                "--settings=testproj.settings.dev"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "DjangoDebugging"
            ]
        }
    ]
}
```   
Your settings.json:   
```{
    "python.pythonPath": "${workspaceRoot}/projectenv/bin/python",
    "python.linting.pylintArgs": ["--load-plugins", "pylint_django"]
}
```   
## Logs
Output from ```Python``` output panel  
```none
```   
Output from ```Console window``` (Help->Developer Tools menu)
```none
```

Suspicion (though I'm not a Python expert yet) I just got by looking at the settings.json: maybe it has something to do with the virtual environments. The plugin is not inside the virtualenv but Python looks for python-debug.startSession there. Just my suspicion.

**Comment by DonJayamanne** [comment]
Silly question, but please could you confirm you have a Python file opened before you have started debugging.

**Comment by JanBrinker** [comment]
Hi there. That's not a silly question at all! I checked and indeed the file my current tab pointed to was a Django template file and thus `.html`. If I switch over to a `.py` file I can run the debugger. If I stop execution and then move over to my `.html` file again starting the debugger will work again, even if started on a tab displaying a non `.py` file.

So this explains things. But now I'm wondering why this occurs, as I don't want to execute that single file but the whole project.

**Comment by DonJayamanne** [comment]
The debugger works for Python files, didn't know it would work when debugging .html files too. 
The reason for this is simple, the extension gets activated ONLY when a "python" file is opened, i.e. a file ending with a ".py" extension. So, when you've got a HTML file opened, VS Code doesn't load the Python extension, however when you open a Python file, it does, and once the extension has been loaded, all of its functionality is available.

I'll **consider** loading this extension when a Python or Html file is open. That should fix this issue.

**Comment by DonJayamanne** [comment]
@JanBrinker Thanks for your prompt response. Please open a ".py" file as a work around for the moment. Will keep you posted.

**Comment by JanBrinker** [comment]
Thanks for the quick help! And I wouldn't ask for more :)

**Comment by joneal** [comment]
Odd...used to be able to debug remotely and now I am also seeing the 'python.python-debug.startSession' error.  I do have a .py file open.

I also just upgraded to VSCode 1.9.0.

**Comment by DonJayamanne** [comment]
Very odd.
@joneal please could u confirm u have a folder open in vscode.  
Also What are the contents of your settings.json file?

**Comment by joneal** [comment]
I've tried with an open folder and loading a .py file, and also starting VSCode and loading a .py file.  Seems to behave the same.

Settings:
{
    "editor.fontFamily": "Consolas",
    "editor.fontSize": 20,
    "typescript.check.tscVersion": false,
    "python.pythonPath": "C:\\Python27\\python.exe",
    "python.autoComplete.extraPaths": [
        "C:\\Python27\\lib\\site-packages"
    ],
    "editor.detectIndentation": false
}

It appears that the VSCode update to 1.9.0 may have whacked my launch.json file.  I'm trying to reconfigure but would think that if there is a problem it would only let me not connect to the remote PTVSD server, not generate the error in question.

**Comment by joneal** [comment]
Well....I am running the same tests on a new machine and I no longer receive the error.  The machine with the error had not been used for about a month, so not sure what had changed...but there is some unholy alliance between VS Code, paths, etc.  I propose closing this issue.   Thanks for your help.

**Comment by DonJayamanne** [comment]
Thanks

**Comment by lmazuel** [comment]
@DonJayamanne seeing this with 1.9.0 and a py file opened :(

**Comment by lmazuel** [comment]
@DonJayamanne restart VSCode fixed it. I just added {} in my settings.json file. Not sure it's related... Anyway, work now...

**Comment by Rockttf** [comment]
the same problem happen again "command 'python.python-debug.startSession' not found".
I have read this issue , but I can not find a specific solution to fix it.
On a new machine , it is all ok.

**Comment by joneal** [comment]
This issue seems to have the hallmarks of an uninitialized variable....somewhere.

**Comment by dkisselev** [comment]
I've also been running into this on 1.9 and 1.10.

Uninstalling the python extension, reloading, and reinstalling the extension fixed the problem though.

Definitely sounds like a migration or uninitialized variable issue somewhere (maybe on the path up from <1.9 to 1.9+).

**Comment by BluZilla** [comment]
Thanks for the answers.  I was having the exact same issue!  I am fairly new to coding, learning as a hobby, and maybe one day use it for employment.  But, one day VSC was working fine, the next I kept getting this error, over and over.

**Comment by grahamcrowell** [comment]
I had same problem.  I uninstalled all python extensions; restarted code; reinstalled extensions.
That fixed it.

**Comment by hxnan** [comment]
The same as up floor, i update from 1.9 to 1.13 , when i debug the django project, the alert is  "Command 'python.python-debug.startSession' not found" .
After i reinstall the extensions of python and python for vscode, That fixed it.

**Comment by alsteven** [comment]
Issue just happened for me in 1.14.2. Again, uninstalling python extension, reinstalling, then restarting Code fixed it.

**Comment by beyazc** [comment]
I was getting similar error for golang:
Error command 'go.debug.startSession' not found
Uninstalling and reinstalling fixes

**Comment by copeland3300** [comment]
Initially I was getting a ```command 'python.python-debug.startSession' not found``` and tried what many in this thread suggested, and reinstalled the "Python" extension.

Reinstalling the "Python" extension yields the following new error:
```Invalid launch.json (re-create it or replace 'config.python.pythonPath' with 'config:python.pythonPath')```

Following the message, I changed 
```config.python.pythonPath```
to
```config:python.pythonPath```
and things are now working
