### ISSUE TITLE
Ctrl + Shift + Space does not work?

### ISSUE THREAD

**Issue by abc100m** [DonJayamanne/pythonVSCode#71]
I want to get intellisense for parameters info when press Ctrl + Shift  + Space, but  nothing showed

```python
def foo(a, b, c, d):
      pass
```

foo(  here press <b>Ctrl + Shift  + Space </b>  got nothing)
foo(  here press <b>.</b> can show intellisense )   *press dot key 

please help if  there is a way to let Ctrl + Shift + Space show intellisense

**Comment by DonJayamanne** [comment]
Hi, unfortunately this isn't supported at this stage.
Will look into this as a later enhancement. Sorry.

**Comment by DonJayamanne** [comment]
Reopening as this is a potential future enhancement.

**Comment by DonJayamanne** [comment]
Suggestion for #183

**Comment by DonJayamanne** [comment]
@abc100m , this will be available in the next release. However the intellisense will be available when you type "(" or "," after a function.
Opening brackets indicates the start of the invocation of a function, and "," indicates more parameters/arguments for a function.

**Comment by abc100m** [comment]
great work!  many many thanks!
