### ISSUE TITLE
autopep8 can not format with python file over 2000 lines 

### ISSUE THREAD

**Issue by toplinuxsir** [DonJayamanne/pythonVSCode#710]
autopep8 can not format with python file over 2000 lines 

## Environment data
VS Code version:  1.9.0
Python Extension version:   0.5.8
Python Version:   2.7.13
OS and version:    Debian stretch

## Steps to reproduce:  
-  
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
Unfortunately you will need to report this issue on the autopep8 repo. That's a third-party package
