### ISSUE TITLE
How do I get the latest release?

### ISSUE THREAD

**Issue by pfmoore** [DonJayamanne/pythonVSCode#712]
I installed version 0.5.6 into VS Code using ```Extensions: Install```. I see that 0.5.8 is now released, and it has a specific fix I need (support for powershell in "Run Python script in terminal"). But "Check for updates" doesn't get the new version. How do I upgrade?

**Comment by joaomoreno** [comment]
@pfmoore If you restart Code, does the update appear?

**Comment by pfmoore** [comment]
No, I tried that a few times :-(

**Comment by joaomoreno** [comment]
ping @modigrv @hamenon Could this be some Marketplace cache?

**Comment by pfmoore** [comment]
Hmm, odd. I just checked the Marketplace page (hadn't thought to do that) and it has 0.5.8. Doing "ext install Python" as noted on that page upgraded me. I don't know why "Show outdated" on the extension pane didn't report that it needed upgrading, nor allow me to do so.

If I hadn't encountered a specific bug and confirmed that a fix had been made and was in 0.5.8, I wouldn't have realised I was out of date :-(

**Comment by modigrv** [comment]
Marketplace cache has ttl of only 5 minutes. After max 5 minutes, the new versions will start showing up if checked in the API call.

**Comment by DonJayamanne** [comment]
Closing as this is an infrastructure issue (not an issue of the extension).
