### ISSUE TITLE
Improve missing `pylint` experience

### ISSUE THREAD

**Issue by joaomoreno** [DonJayamanne/pythonVSCode#713]
From Microsoft/vscode#19989, cc @G109B

VSCode recommends installing this extension. It seems that if the user doesn't have the `pylint` command in the environment, he immediately gets an error popup, which is pretty sad, given that this was an official recommendation.

**Comment by DonJayamanne** [comment]
This has been discussed a number of times with a couple of people and the final solution was to provide this message with the ability to turn it off or install it (hence the prompt/message).

The linter is completely optional and personally I don't think it should be installed without user knowing it. Also pylint is the default linter, and if none were used then majority of python developers would not get linting of python files, leading then to believe that the extension doesn't provide linting capabilities. Unless they read the documentation and enabled the necessary settings in settings.json, that's highly unlikely when using this for the first time..

**Comment by DonJayamanne** [comment]
Oops didn't mean to close it

**Comment by DonJayamanne** [comment]
@G109B
Please could you provide the contents of your settings.json file.

**Comment by G109B** [comment]
Do I have one ? Where do I find it ?

**Comment by DonJayamanne** [comment]
That's fine, I don't think you do.

**Comment by DonJayamanne** [comment]
Fixed in latest version of extension
