### ISSUE TITLE
Support for Literal String Interpolation

### ISSUE THREAD

**Issue by rod-stuchi** [DonJayamanne/pythonVSCode#715]
## Environment data
VS Code version: 1.9
Python Extension version: 0.5.8
Python Version: 3.6.0
OS and version:  Linux x64 4.9.6-1-ARCH

https://www.python.org/dev/peps/pep-0498/

## Actual behavior
![image](https://cloud.githubusercontent.com/assets/19471811/22675824/0f968882-eccf-11e6-8f33-9eac4ad32647.png)

## Expected  behavior
![image](https://cloud.githubusercontent.com/assets/19471811/22675843/238854f6-eccf-11e6-9012-4d34bdfd48c3.png)

The color of `sys.argv[2]` variable should be different from string.  

Any plans? 

And thank you for the great work!

**Comment by DonJayamanne** [comment]
Please report this issue on the Magic python repo, that's whats used by vscode to provide syntax highlighting.
https://github.com/MagicStack/MagicPython
