### ISSUE TITLE
Auto-detection of binaries

### ISSUE THREAD

**Issue by fredrikaverpil** [DonJayamanne/pythonVSCode#716]
## Environment data
VS Code version:  1.9.0
Python Extension version:  0.5.8
Python Version:   3.5
OS and version:    Windows 10

## Behavior

I've set the following:

```json
"python.pythonPath": "C:/Program Files/Miniconda2/envs/pythondev_35"
```
This autodetects `python.exe` -- but this won't auto-detect `pylint.exe`, `pep8.exe`, `autopep8.exe` or `yapf.exe`.

Therefore I have to resort to manually adding the following as well:

```json
"python.linting.pylintPath": "C:/Program Files/Miniconda2/envs/pythondev_35/Scripts/pylint.exe",
"python.linting.pep8Path": "C:/Program Files/Miniconda2/envs/pythondev_35/Scripts/pep8.exe",
"python.formatting.autopep8Path": "C:/Program Files/Miniconda2/envs/pythondev_35/bin/autopep8.exe",
"python.formatting.yapfPath": "C:/Program Files/Miniconda2/envs/pythondev_35/bin/yapf.exe"
```

This is also a problem on macOS (and most likely Linux too).

**Comment by DonJayamanne** [comment]
@fredrikaverpil I don't think the code is working as it is supposed to.
It doesn't find the "python3" executable. Currently I'm only looking for "python" and "python.exe" in the paths provided. Big - Ooops

**Comment by fredrikaverpil** [comment]
But there's a `python.exe` in there, and actually no `python3.exe` at all:

```powershell
C:\Program Files\Miniconda2\envs\pythondev_35> ll python*

    Directory:  C:\Program Files\Miniconda2\envs\pythondev_35

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a----        1/23/2017   9:07 PM    34.50KB python.exe
-a----        1/23/2017   9:07 PM   404.00KB python.pdb
-a----        1/23/2017   9:04 PM     3.75MB python35.dll
-a----        1/23/2017   9:04 PM     9.16MB python35.pdb
-a----        1/23/2017   9:07 PM    34.50KB pythonw.exe
-a----        1/23/2017   9:07 PM   404.00KB pythonw.pdb
```

**Comment by fredrikaverpil** [comment]
@DonJayamanne I know this issue is closed, but this still doesn't work for me.

I have this in my `settings.json`:
```json
"python.pythonPath": "C:/Program Files/Miniconda2/envs/pythondev_35"
```

Python itself is picked up (in my case Python 3.5: `python.exe`), but not the other binaries I'm using: `pylint.exe`, `yapf.exe`, `pep8.exe`. I need to specify these explicitly on each platform or I get the banner warnings in vscode about not having these installed.

I'm testing this now on Insider build 1.11.0.

**Comment by DonJayamanne** [comment]
Please feel free to re-open issues if the issue persists.
Will look into this.

**Comment by Fenkiou** [comment]
Not sure if I have the same problem on macOS

In user settings, python, pylint and pydocstyle paths are configured as follow:
```
"python.pythonPath": "/usr/local/bin/python",
"python.linting.pylintPath": "/usr/local/bin/pylint",
"python.linting.pydocstylePath": "/usr/local/bin/pydocstyle",
```

In my workspace, I have python path configured differently because using a virtualenv. But only my python path is different. pylint and pydocstyle paths remain unchanged.

Now, when opening python file in my workspace, I get `Linter pylint is not installed` so linting with pylint doesn't work but docstrings lint are working fine..

Even if I install pylint in my virtualenv, the error is still displayed.

**Comment by fredrikaverpil** [comment]
Just adding that on macOS, this won't detect the binaries:

```json
{
"python.pythonPath": "${env.HOME}/miniconda3/envs/pythondev_35"
}
```

...but this will:

```json
{
    "python.pythonPath": "${env.HOME}/miniconda3/envs/pythondev_35",
    "python.linting.pylintPath": "${env.HOME}/miniconda3/envs/pythondev_35/bin/pylint",
    "python.linting.pep8Path": "${env.HOME}/miniconda3/envs/pythondev_35/bin/pep8",
    "python.formatting.autopep8Path": "${env.HOME}/miniconda3/envs/pythondev_35/bin/autopep8",
    "python.formatting.yapfPath": "${env.HOME}/miniconda3/envs/pythondev_35/bin/yapf"
}
```

**Comment by DonJayamanne** [comment]
This has been fixed in the latest release of the extension.
So, you'll no longer need to define the fully qualified paths to the linters. The linters will be run as modules "python -m pylint" (meaning it will pick the installed package from the configured python environment)

**Comment by fredrikaverpil** [comment]
Fantatic, thank you for your excellent work @DonJayamanne

**Comment by vvug** [comment]
It doesn't work, see https://github.com/DonJayamanne/pythonVSCode/issues/1190

**Comment by fredrikaverpil** [comment]
Yeah @DonJayamanne this issue should be re-opened as this doesn't work.

I use this, and pylint is not found:

```json
{
    "python.pythonPath": "${env.HOME}/miniconda3/envs/pythondev_35"
}
```

However, if I specify the path to all binaries, pylint etc works:

```json
{
    "python.pythonPath": "${env.HOME}/miniconda3/envs/pythondev_35",
    "python.linting.pylintPath": "${env.HOME}/miniconda3/envs/pythondev_35/bin/pylint",
    "python.linting.pep8Path": "${env.HOME}/miniconda3/envs/pythondev_35/bin/pep8",
    "python.formatting.autopep8Path": "${env.HOME}/miniconda3/envs/pythondev_35/bin/autopep8",
    "python.formatting.yapfPath": "${env.HOME}/miniconda3/envs/pythondev_35/bin/yapf"
}
```
