### ISSUE TITLE
Refactor failed

### ISSUE THREAD

**Issue by ShevoPramide** [DonJayamanne/pythonVSCode#717]
when i trying to rename this error appeared:

> Refactor failed. Rename refactoring should be performed on resolvable python identifiers.

**Comment by DonJayamanne** [comment]
Please could you provide the sample code you are trying to refactor along with the environment information.

**Comment by seanmars** [comment]
I get this error when i rename the argument.
> Refactor failed. Syntax error in file <env/Lib/site-packages/astroid/tests/testdata/python2/data/module.py> line <32>: invalid syntax

**Comment by DonJayamanne** [comment]
Please test in the latest version, this may have been resolved along with other changes.
Please re-open if issue persists.

**Comment by seanmars** [comment]
I think it is resolved now, but rename so slow, take more then 10 seconds.
