### ISSUE TITLE
Conflicting 'has / has no' member information

### ISSUE THREAD

**Issue by alexmacniven** [DonJayamanne/pythonVSCode#718]
## Environment data
VS Code version: 1.9.0 
Python Extension version: 0.5.8  
Python Version: 2.7   
OS and version: Win10   

## Actual behavior
Extension is showing lxml.etree has no member whilst function docstring appears
![image](https://cloud.githubusercontent.com/assets/8559416/22697501/7e4ed322-ed49-11e6-91e6-4f0a46c84e85.png)

## Expected  behavior
Extension doesn't show conflicting information. If the import method used is invalid then the extension should advise a user of this
## Steps to reproduce:  
-  
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json: 
Default apart from  
```json
{
    "git.confirmSync": false,
    "editor.wrappingColumn": 300,
    "editor.rulers" : [100]
}
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
Unfortunately this is an error returned by the third-party linter, pylint.
