### ISSUE TITLE
Jupyter does not work with WinPython 3.6.0

### ISSUE THREAD

**Issue by ketigid** [DonJayamanne/pythonVSCode#719]
## Environment data
VS Code version:  1.9.0
Python Extension version:  0.5.8
Python Version:   3.6.0
OS and version:    Window 7 SP1

## Actual behavior
Nothing happens with I click Run Cell

## Expected  behavior
Results tab should appear with results. Kernel info should appear in status bar.
Jupyter works as expected with I use WinPython 3.5.1.3 though.

## Steps to reproduce:  
-  
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
    "python.workspaceSymbols.enabled": false,
    "files.autoSave": "afterDelay",
    // "python.pythonPath": "D:/WinPython-64bit-3.5.1.3/python-3.5.1.amd64/python.exe", // Works fine
    "python.pythonPath": "D:/WinPython-64bit-3.6.0.1Qt5/python-3.6.0.amd64/python.exe", // Does not work
    "python.linting.pylintEnabled": false,
    "python.linting.flake8Enabled": true
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by chengyuhui** [comment]
Try deleting `python._pth` in python directory

**Comment by ketigid** [comment]
@chengyuhui It works. Thanks. Will you explain to me why deleting `python._pth` helped?

**Comment by chengyuhui** [comment]
I think they are missing a blank line (according to docs), which also breaks the debugger and my application.

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/vscodeJupyter#4
