### ISSUE TITLE
Debugging Python loading indefinitely 

### ISSUE THREAD

**Issue by egamma** [DonJayamanne/pythonVSCode#72]
_From @vsccarl on April 8, 2016 20:17_

- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Clone https://github.com/simpleai-team/simpleai.git
2. Install Python extension
3. Start debugging

Actual:
No debug menu comes up to continue/restart/stop etc. and there is no way to stop debugging.

Can move to https://github.com/DonJayamanne/pythonVSCode if needed.

_Copied from original issue: Microsoft/vscode#5104_

**Comment by DonJayamanne** [comment]
Will look into this soon. sorry for the delay.

**Comment by szilvaa** [comment]
It appears to happen when "RedirectOutput" is missing.

**Comment by DonJayamanne** [comment]
Hi @egamma , apologies for the delay in looking into this issue.
I'm unable to replicate this issue. I've tested it and it works fine.
I've tried debugging the samples using the standard Python and 'Python Console' configurations and it works as expected.

**Comment by egamma** [comment]
One of our testers has reported this issue some time ago and the issue could be obsolete. Closing.
