### ISSUE TITLE
Environment variables not picked up from Profile.ps1 or .bashrc

### ISSUE THREAD

**Issue by fredrikaverpil** [DonJayamanne/pythonVSCode#720]
## Environment data
VS Code version: 1.9.0
Python Extension version: 0.5.8
Python Version: 3.5
OS and version: Windows 10

## Issue

I have defined a custom environment variable in my `Profile.ps1` on Windows:

    # C:\Users\fredrik\Documents\WindowsPowerShell\Profile.ps1
    $CONDAENVS = "C:\Program Files\Miniconda2\envs"

...and in my `.bashrc` on macOS:

    # ~/.bashrc
    export CONDAENVS=~/miniconda3/envs

However, I cannot use this environment variable in settings.json, as it doesn't seem to get picked up: 
```json
"python.pythonPath": "${env.CONDAENVS}/pythondev_35"
```

In the integrated vscode terminal, I can on both platforms `echo $CONDAENVS` successfully.

Are there only a few pre-defined environment variables available?

**Comment by DonJayamanne** [comment]
Terminal windows work differently. They have special files that get used to prepare the environment . However launching processes in code (.NET, Python, node.js, etc) will not pick up these profile files to initialize the environment variables.

I.e. environment variables defined in these files won't work with this extension. 

The best option is to modify the extension to add support for *.env files and defining environment variables for use within the vscode extension, this will be done here (https://github.com/DonJayamanne/pythonVSCode/issues/686)

**Comment by DonJayamanne** [comment]
@fredrikaverpil 
Oh yes a solution for this is:
- Open a terminal window and from within the terminal window, launch vscode
This way vscode will inherit the env variables from the terminal session.

You could create a shortcut for this (bat file or a bash script file).

**Comment by fredrikaverpil** [comment]
Okay, thanks.

> The best option is to modify the extension to add support for *.env files and defining environment variables for use within the vscode extension, this will be done here (#686)

I think at least for me personally, I would love to instead be able to define a platform and then different pythonpaths depending on whether I'm on macOS, Windows, Linux. Hopefully that'll get supported: #644
