### ISSUE TITLE
Run Python File in Terminal re-uses an occupied terminal which is not available

### ISSUE THREAD

**Issue by gandhis1** [DonJayamanne/pythonVSCode#723]
Steps:

1) Open a terminal. Type in "ipython" to use the interactive console. Start programming.
2) In an open file, run the command "Run Python File in Terminal".
3) Command attempts to execute in the running IPython console. This does not work.

![image](https://cloud.githubusercontent.com/assets/21064086/22758349/4e9ff268-ee1c-11e6-8d50-12b1b4432fb2.png)

**Comment by half1red** [comment]
Hi,

I think there's two way of seeing this action:
- launch a new shell terminal to execute the file with python $(file)
- execute the file inside the ipython terminal with exec() or %run

the second one would be a great feature as it would allow one to keep the variables and functions in the kernel and play with them interactively. Today I don't think that is possible.

Do you think that would be a feature that could be put in your extension (which is awesome btw)?

Thank you for your work !

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#85
