### ISSUE TITLE
Debugger picking up Pandas exception that doesn't occur when running natively

### ISSUE THREAD

**Issue by bicubic** [DonJayamanne/pythonVSCode#724]
## Environment data
VS Code version:  1.9.0
Python Extension version:  0.2.3
Python Version:  2.7.12, Anaconda 2.4.1 (64 bit)
OS and version:    Windows 10
Pandas: 0.17.1

## Actual behavior
Running a python file that imports `pandas` with debugger breaks on an exception at the Pandas entry point:

```
try:
<<<breaks here>>>    from pandas import hashtable, tslib, lib
except ImportError as e:  # pragma: no cover
    module = str(e).lstrip('cannot import name ')  # hack but overkill to use re
    raise ImportError("C extension: {0} not built. If you want to import "
                      "pandas from the source directory, you may need to run "
                      "'python setup.py build_ext --inplace' to build the C "
                      "extensions first.".format(module))

```
## Expected  behavior
Running the same file natively with `python` does not raise any exceptions. 

## Steps to reproduce:  
install pandas 0.17.1, not sure if true for other versions
create a new python file and `import pandas`
debug in vscode

## Settings  
Your launch.json:   
```json
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
```   

pythonPath is `python`

I'm guessing `if you want to import pandas from the source directory` is the clue here. Is running this project in vscode causing the runtime to import from a different location than just running `python` ?
![vscode](https://cloud.githubusercontent.com/assets/2053458/22768913/5c3851c8-eed9-11e6-8a3d-b407b876a207.PNG)

**Comment by DonJayamanne** [comment]
@bicubic 
I panda installed as a python package in a Python environment or is the source located in your project folder?  
When you run the code natively in ```python``` as described, what's the python environment you're using? is it the same as the default python executable, i.e. if you open your terminal and just type ```python``` is that the same python environment?

**Comment by bicubic** [comment]
@DonJayamanne 

>I panda installed as a python package in a Python environment or is the source located in your project folder?

pandas installed in the env

> i.e. if you open your terminal and just type python is that the same python environment?

Yes. There's only 1 instance of python installed, no virtualev, etc. `python` is it. I.e. `python myfile.py` will produce the expected behaviour.

**Comment by DonJayamanne** [comment]
@bicubic Apologies for not getting back to you on this. Please could you let me know if this problem still persists. Thanks
