### ISSUE TITLE
request: connect to existing jupyter kernel in terminal

### ISSUE THREAD

**Issue by sglyon** [DonJayamanne/pythonVSCode#725]
It would be _fantastic_ if there was a command to open a jupyter console in the vs code REPL that is connected to the same kernel as the file. Is this feasible/something you'd be willing to support?

**Comment by pierredangauthier** [comment]
You can start it from a vscode terminal. Steps:
1. run `%connect_info` in your vscode file to get the information
2.  use it in the terminal inside vscode, for instance `jupyter console --existing /home/pierre/code/hanson/kernel-8cf512b8-cbca-4653-93a0-cd1edf696665.json`

Both the file and the terminal should speak to the same kernel.

**Comment by sglyon** [comment]
Excellent. That's a good start. Thank you

 It'd be great if that was automated

**Comment by DonJayamanne** [comment]
Will close as there's a solution for this.
