### ISSUE TITLE
pytest not running from VS Code 

### ISSUE THREAD

**Issue by Manikant90** [DonJayamanne/pythonVSCode#726]
## Environment data
VS Code version:  1.9.0
Python Extension version:  0.5.8
Python Version:   2.7.13
OS and version:    windows 10 

## Actual behavior   
py tests are not running properly from vs code, but works from commandline
1. My Project structure is 
- Main Project Folder
- application.py
- test (folder)
--- unit (folder)
----- test_application.py
When I run test_application.py from within vs code, it cannot locate application.py as a module
Here is the error from within visual studio
If I run the above using pytest directly from command line the tests are
working correctly.

## Expected  behavior  
     Should be running pytest successfully

## Steps to reproduce:  
-  
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
=================================== ERRORS ====================================
_______________ ERROR collecting test/unit/test_application.py ________________
ImportError while importing test module 'd:\Users\manikant\Desktop\ffnlp\avrio-python-ffnlp\FFNLP\test\unit\test_application.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test\unit\test_application.py:5: in <module>
    import application
E   ImportError: No module named application
!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.40 seconds ===========================
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
Please upload CMD line you tried along with the working directory you used for the command

**Comment by snff** [comment]
Hello Don,
Mani is one of my team  members who posted this problem. He is in a different timezone, so in the hopes of resolving this problem here is some information that you requested, hopefully you can help us move past this issue. 
The working directory is the same as where application.py is available. Here is the output from the terminal.

(avrio) Srinaths-MBP:FFNLP srinath$ python -m pytest test/unit/test_application.py
==================================================================== test session starts ====================================================================
platform darwin -- Python 2.7.11, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /Users/srinath/git/avrio-python-ffnlp/FFNLP, inifile:
collected 1 items

test/unit/test_application.py .

================================================================= 1 passed in 12.76 seconds =================================================================
(avrio) Srinaths-MBP:FFNLP srinath$


Also settings.json looks like this

{
    "python.unitTest.pyTestEnabled": true,
    "python.unitTest.unittestEnabled": false,
    "python.unitTest.nosetestsEnabled": false,
    "python.pythonPath": "${workspaceRoot}/virtualenv/avrio/bin/python",
    "python.unitTest.pyTestArgs":[
        "--exitfirst",
        "--verbose",
        "--ignore=virtualenv/"
    ],
    "python.linting.pylintEnabled": false

Thank you.

**Comment by DonJayamanne** [comment]
The python excusable used in the command line is different to the one configured in the settings.json. 
In the command line you aren't using the virtual environment, but vs code is.

**Comment by snff** [comment]
They both are using the same virtual environment. Look at (avrio) displayed in my copy paste of the terminal. That is the avrio virtual environment active indication.

**Comment by DonJayamanne** [comment]
please could you type the following into the command window:  
- ```which python```  
- ```which pylint```

**Comment by snff** [comment]
(avrio) Srinaths-MBP:FFNLP srinath$ which python
/Users/srinath/git/avrio-python-ffnlp/FFNLP/virtualenv/avrio/bin/python
(avrio) Srinaths-MBP:FFNLP srinath$ which pylint
(avrio) Srinaths-MBP:FFNLP srinath$

**Comment by DonJayamanne** [comment]
sorry ```which pytest``` not ```pylint```

**Comment by snff** [comment]
(avrio) Srinaths-MBP:FFNLP srinath$ which pytest
/Users/srinath/git/avrio-python-ffnlp/FFNLP/virtualenv/avrio/bin/pytest
(avrio) Srinaths-MBP:FFNLP srinath$

**Comment by snff** [comment]
Here is some additional information
http://stackoverflow.com/questions/10253826/path-issue-with-pytest-importerror-no-module-named-yadayadayada

Based on this I did the following
if directly run using pytest I got the same error as in vs code (no module named ....)
if I run using python -m python .... it works fine (as mentioned above)
on my project root folder if I do export PYTHONPATH=. and then run using pytest it works fine.
Is there way to set PYTHONPATH via vscode ?

**Comment by DonJayamanne** [comment]
Thanks for identifying the issue. 
Setting PYTHONPATH can be done in the next release (https://github.com/DonJayamanne/pythonVSCode/issues/686). 

For now you could try the following:
- Open a terminal  
- Set the PYTHONPATH env variable  
- Launch vscode from this terminal

**Comment by snff** [comment]
If I did that the PYTHONPATH setting is not inherited from vscode. When I print os.environ I don't see the PYTHONPATH that I set. So this work around doesn't seem to work.

**Comment by DonJayamanne** [comment]
@snff @Manikant90 
Please try the following: 

- Create a file named .env in your root directory  
- Add the following contents to the .env file:  
```PYTHONPATH=some path you want to use```

**Comment by eromoe** [comment]
I add below,
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "PyTest",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config:python.pythonPath}",
            "module": "pytest",
            "args": [
                "-sv"
            ],
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }
    ]
}

```

switch to pytest would work:

![image](https://user-images.githubusercontent.com/3938751/30849790-0fe84e20-a2d6-11e7-9017-557c4e403355.png)

**Comment by DonJayamanne** [comment]
Closing this issue as I believe this has been resolved (using PYTHONPATH for unit tests). Please reopen if it persists.
