### ISSUE TITLE
No function description when typing

### ISSUE THREAD

**Issue by Fetandrey** [DonJayamanne/pythonVSCode#727]
## Environment data
VS Code version:  1.9.1
Python Extension version:  0.5.8
Python Version:   3.6
OS and version:    Windows 10 build 15025

## Actual behavior
Nothing is displayed except names
[
![screenshot 662](https://cloud.githubusercontent.com/assets/22403582/22793302/88c1ac04-ef00-11e6-92ea-84d1cabf2892.png)
](url)
## Expected  behavior
Function definition should be displayed when browsing suggestions
[
![screenshot 665](https://cloud.githubusercontent.com/assets/22403582/22793357/ae507f5e-ef00-11e6-99f7-5b80a94366d3.png)
](url)
## Steps to reproduce:  
-  start typing a function name
-  find this function in the suggested list using up and down arrows

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
Where can I find it?
```   
## Logs
Output from ```Python``` output panel  
```
None
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
None
```

**Comment by DonJayamanne** [comment]
Temporary fix has been applied, by reverting the jedi version to an older release.
https://github.com/davidhalter/jedi/issues/859
Leaving this issue open untill we get this issue resolved in Jedi.

**Comment by Fetandrey** [comment]
Is there a way to try this fix before an official update?

**Comment by DonJayamanne** [comment]
>Temporary fix has been applied, by reverting the jedi version to an older release.

**Comment by DHZS** [comment]
I also have this problem
No function description when typing
<img width="415" alt="1" src="https://cloud.githubusercontent.com/assets/10752166/23007758/afc69be4-f445-11e6-92af-e7f3bd5ad8b6.png">
No function description when the cursor hover over the function
![2](https://cloud.githubusercontent.com/assets/10752166/23007840/345f5256-f446-11e6-9924-a73137394ce9.png)

**Comment by DonJayamanne** [comment]
Sorry, but a new version will have to be released

**Comment by DonJayamanne** [comment]
This has been fixed
