### ISSUE TITLE
Enhancement: Pick up on PEP-0484 Type hints when present

### ISSUE THREAD

**Issue by dannystaple** [DonJayamanne/pythonVSCode#728]
## Environment data
Python Extension version:  0.5.8
Python Version:   2.7 and 3.x

Independent of platform and VSCode version.

## Expected  behaviour

PEP-484 describes type hints/annotations, and how they can be used in two ways - for Python2.7 and Python 3.x. They are only intended for IDE's Linters and do not actually modify the runtime. IE- They are not enforced.

These type annotations can be used to suggest intellisense lookups for parameters where they should be of a particular object type. 

Example annotations using the comment style:

    def prepare_for_racks(slot, location, boot_env):
        # type: (data_helper.Slot, str, data_helper.BootEnvironment)
        .
        .
        .

Example annotations using Python 3 style (will not work in python 2 and will break some linters):

    def prepare_for_racks(slot: data_helper.Slot, location: str, boot_env: data_helper.BootEnvironment):
        .
        .
        .

It could also lead into a later enhancement to support using a python type linter.

**Comment by DonJayamanne** [comment]
This issue was moved to davidhalter/jedi#858
