### ISSUE TITLE
debug console cant not print unicode

### ISSUE THREAD

**Issue by abc100m** [DonJayamanne/pythonVSCode#73]
press F5  then switch the in the "DEBUG CONSOLE" window, 
```shell
>print 'ok, go'
print 'ok,go'
None
ok,go

>print u'ok, go'
print u'ok,go'
None
ok,go

>print u'中'
print u'中'
'ascii' codec can't encode character u'\u4e2d' in position 0: ordinal not in range(128)
```

now debugger stopped with this error :
Error   Unexpected end of input. Stopping the debug adapter.

**Comment by abc100m** [comment]
python 2.7.10
windows 7
vscode 0.10.11
pythonVSCode: lasted

**Comment by DonJayamanne** [comment]
Good news, I have a fix for this. Please give me a day or two.

**Comment by DonJayamanne** [comment]
Fixed, try 
>print '中'

**Comment by abc100m** [comment]
many thanks!  now print unicode is ok
