### ISSUE TITLE
lintOnTextChange is not work for flake8

### ISSUE THREAD

**Issue by gdyuldin** [DonJayamanne/pythonVSCode#732]
## Environment data
VS Code version:   1.9.1
Python Extension version:  0.5.8
Python Version:   2.7.12
OS and version:    Linux Mint 18.1 Serena

## Actual behavior

`flake8` linter starts on each change, even if `python.linting.lintOnTextChange` is `false` both in User and Workspace settings. So if I type fast enough - `flake8` eats all CPU time and UI starts freeze. In htop at this time I can see a lot of `flake8` processes.

Your settings.json:   
```json
    "python.linting.flake8Enabled": true,
    "python.linting.lintOnTextChange": false,
```

**Comment by DonJayamanne** [comment]
Will fix this asap, apologies for this

**Comment by gdyuldin** [comment]
Sorry, it was another plugin issue.
