### ISSUE TITLE
code jumps up/down because of test lenses appearing/disappearing

### ISSUE THREAD

**Issue by iivvoo** [DonJayamanne/pythonVSCode#733]
## Environment data
VS Code version:  1.9.1
Python Extension version:  0.5.2
Python Version:   3.5.2
OS and version:    Ubuntu 16.04

## Actual behavior

Depending on the validity of the syntax I'm typing (and since I'm typing it will not always be syntactically correct), the pytest test lenses appear/disappear, shifting code up/down which can become annoying

## Expected  behavior

The lenses should be fixed and not disappear. Or they should not appear on their own line.

## Steps to reproduce:  
- create a valid (py) test and have a test lens appear
- edit the test method, opening a '(' for example
- the lens will disappear, code will jump up one line

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
    "python.unitTest.pyTestEnabled": true,
    "python.unitTest.unittestEnabled": false,
    "python.unitTest.nosetestsEnabled": false,
    "python.unitTest.pyTestArgs": [
        "--exitfirst",
        "--verbose"
    ]
```json
```

**Comment by DonJayamanne** [comment]
@iivvoo Are you still experiencing this issue?

**Comment by iivvoo** [comment]
I just tried (had to re-enable py.test): Still happening.

I tried to make a screencast of the behaviour:

https://www.dropbox.com/s/8snemjxqf41yrp3/py-test-lenses.ogv?dl=0

In general, the whole test-lenses stuff doesn't work at all, doesn't work predictably or makes code jump around.
