### ISSUE TITLE
workspace symbols with ctags - don't exclude some packages

### ISSUE THREAD

**Issue by ychab** [DonJayamanne/pythonVSCode#735]
I was wondering if we could skip some defaults exclusions, like [site-packages](https://github.com/DonJayamanne/pythonVSCode/blob/master/resources/ctagOptions#L18)?

Maybe a setting to a custom ctags option file instead of the [hardcoded](https://github.com/DonJayamanne/pythonVSCode/blob/master/src/client/workspaceSymbols/generator.ts#L14)?

In that way, I could go to Django symbols without breaking the default conf ;-)

Thanks

## Environment data
VS Code version:  1.9.1
Python Extension version:  0.5.8

**Comment by DonJayamanne** [comment]
You can do this by adding the necessary exclusion patterns into the following setting in settings.json file:  
```
"python.workspaceSymbols.exclusionPatterns": [
		
	]
```

**Comment by ychab** [comment]
@DonJayamanne Maybe I didn't explain well my problem...

I'm already using this setting to exclude some other patterns (``.history``, ``.tox``, etc). My problem is not to exclude patterns, but to **include** some patterns previously excluded by the default config (more exactly **/site-packages/**).

How can I tell : don't exclude ``**/site-packages/**``?

**Comment by DonJayamanne** [comment]
Apologies for that, hmm. I think i'm going to have to make some changes for this.
Currently there's no way to overwrite those settings.
Hang in there, i'll provide a fix for that soon.
For now, you could identify the location of the ctagsoption file on your work machine and remove that default entry from the ctagsoption file

**Comment by DonJayamanne** [comment]
Personal Note: Use telemetry to check how many people are using this setting.
Then include the ```**/site-packages/**``` value as a default value for excludePatterns.

**Comment by ychab** [comment]
Ok thanks.

Indeed, providing it instead as a default value in the ``python.workspaceSymbols.exclusionPatterns`` could be a quick and easy fix
