### ISSUE TITLE
Python manual fullpath windows 

### ISSUE THREAD

**Issue by vezycash** [DonJayamanne/pythonVSCode#736]
## Environment data
VS Code version:  1.8.1
Python Extension version:  
Python Version:   3.6
OS and version:    Windows 10, 1511

"python.pythonPath": "c:/python27/python.exe"
![capture](https://cloud.githubusercontent.com/assets/3171247/22855873/9dbebc86-f087-11e6-8d87-4e38def94b44.JPG)

## Actual behavior
Manual full path doesn't work without escaping. 

Update documentation in (https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version#python-version-used-for-intellisense-autocomplete-linting-formatting-etc) to reflect this:
"python.pythonPath": "c://python27//python.exe"
## Steps to reproduce:  
-  
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json:

     "python.pythonPath": "C:\\Users\\Edison\\AppData\\Local\\Programs\\Python\\Python36-32"

```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
There's no need to update the docs.
If you look carefully, the paths are using '/' (forward slashes) and you are using '\' (back slashes).  
When using '\' you need to escape it, and not when using '/'
