### ISSUE TITLE
Add a bit more info to Quick Start

### ISSUE THREAD

**Issue by mosajjal** [DonJayamanne/pythonVSCode#737]
If you run `vscode` inside the virtualenv, the extension will automatically work with the interpreter provided inside the virtualenv. 

Maybe adding this hint to Quick Start would help users. I know I use it and I love it. Switching between virtualenv w/o getting worried about the interpreter.

**Comment by DonJayamanne** [comment]
You can simply use the `Select Workspace Interpreter` command
https://github.com/DonJayamanne/pythonVSCode#quick-start
