### ISSUE TITLE
Cannot scroll in terminal window

### ISSUE THREAD

**Issue by hun1ahpu** [DonJayamanne/pythonVSCode#739]
## Environment data
VS Code version:  1.9.1
Python Extension version:  0.5.8
Python Version:   3
OS and version: win 10

## Actual behavior
Mouse wheel scroll doesn't work
Scroll bar is not visible
After resizing the terminal window it starts working

## Steps to reproduce:  
-  Open any python file and execute any line of it

![pythonscrollbar](https://cloud.githubusercontent.com/assets/4397796/22861272/648d3436-f115-11e6-8cf6-4b54c628cf35.gif)

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode#20505
