### ISSUE TITLE
Disable auto-completion in comments?

### ISSUE THREAD

**Issue by DavidA2014** [DonJayamanne/pythonVSCode#74]
Hi Don

Is it possible to disable auto-completion in comments? It's a little tedious to see suggestions for almost every word typed.

Also, is the docstring support documented anywhere?

Finally, I think the release notes are missing details of release 0.3.3.

Thanks for your hard work!

David

**Comment by DonJayamanne** [comment]
>>Is it possible to disable auto-completion in comments? It's a little tedious to see suggestions for almost every word typed. 
Currently no.
>>Also, is the docstring support documented anywhere?
Oops, no, will update the wiki with this.
>>Finally, I think the release notes are missing details of release 0.3.3.
Sorry about that.

**Comment by DonJayamanne** [comment]
Suggestion for #183

**Comment by gandhis1** [comment]
One addition to this might be disabling auto-complete in strings. I get this the most when I am writing docstrings.

**Comment by DonJayamanne** [comment]
Look at solution in https://github.com/Microsoft/vscode/issues/9504#issuecomment-287072634

**Comment by DonJayamanne** [comment]
Investigate why autocompelte still works in strings even after the following:

```
    "editor.quickSuggestions": {
        "other": false,
        "comments": false,
        "strings": false
    }
}
```

**Comment by DonJayamanne** [comment]
Closing in favor of https://github.com/Microsoft/vscode-python/issues/34
