### ISSUE TITLE
Problems with quick info

### ISSUE THREAD

**Issue by jasoncwj** [DonJayamanne/pythonVSCode#740]
Hi! I am new to vscode, and I like it with python extension, but it seems I have trouble using it.
When it comes to quick info (intellisense), it becomes like this on my computer:
![2017-02-12 8 52 12](https://cloud.githubusercontent.com/assets/25721850/22862212/7faeef02-f165-11e6-9e22-2583c4c329f1.png)
I think there is supposed to be an info icon on the right, which when I click on, gives me the help documents of the functions, but it seems to be missing here.
The way I want it to work is like this:
![general](https://cloud.githubusercontent.com/assets/25721850/22862234/f9a7dd3c-f165-11e6-8c32-1bd0dedcb740.gif)

I appreciate any help.
Thanks!

**Comment by DonJayamanne** [comment]
https://github.com/DonJayamanne/pythonVSCode/issues/727
