### ISSUE TITLE
unexcept newline in print() with ','

### ISSUE THREAD

**Issue by chanchancl** [DonJayamanne/pythonVSCode#743]
## Environment data
VS Code version:  1.9.1
Python Extension version:  0.5.8
Python Version:   3.5.2
OS and version:    win10.14393

## Actual behavior (in debug terminal)
 
formal arg 1:
 
abc
formal arg 2:

defaultB
formal arg 1:
 
23
formal arg 2:
 
4.56
formal arg 1:
 
abc
formal arg 2:
 
123
another arg:
 
xyz
another arg:
 
456.789
it looks like this
![image](https://cloud.githubusercontent.com/assets/11457297/22883695/599b68a0-f22c-11e6-994b-722f42578835.png)

## Expected  behavior (in normal terminal)
formal arg 1: abc
formal arg 2: defaultB
formal arg 1: 23
formal arg 2: 4.56
formal arg 1: abc
formal arg 2: 123
another arg: xyz
another arg: 456.789

it looks like this
![image](https://cloud.githubusercontent.com/assets/11457297/22883731/7e71bdf0-f22c-11e6-9962-0d496012e7df.png)

## Steps to reproduce:  
in python3.x
when I use print() and type a ',',the output will add a new line before ','
I don't know why there will be a newline here.

## Python code
```python
def tupleVarArgs(arg1, arg2='defaultB', *theRest):
    'display regular args and non-keyword variable args'
    print('formal arg 1:', arg1)
    print('formal arg 2:', arg2)
    for eachXtrArg in theRest:
        print('another arg:', eachXtrArg)

tupleVarArgs('abc')
tupleVarArgs(23, 4.56)
tupleVarArgs('abc', 123, 'xyz', 456.789)
```

**Comment by DonJayamanne** [comment]
This is an upstream issue (in VS Code):
https://github.com/Microsoft/vscode/issues/17526
