### ISSUE TITLE
Remote Debug from Windows to linux

### ISSUE THREAD

**Issue by hmdhasani** [DonJayamanne/pythonVSCode#744]
I'm trying to remote debug a script that runs on a linux machine from a VSCode that runs on Windows.
I did the instructions but as I hit 'Start Debugging' button My script on the Linux host terminates without any output and I got nothing on VSCode.
Can anyone help me?

**Comment by DonJayamanne** [comment]
Apolgies for never getting back to you on this. I am assuming you have managed to get this working. Please reopen if you haven't.
