### ISSUE TITLE
tab completion adding string 'param' to method signature   

### ISSUE THREAD

**Issue by abman2day** [DonJayamanne/pythonVSCode#745]
## Environment data
VS Code version: 1.9.1  
Python Extension version: 0.5.8 
Python Version: 2.7.12
OS and version: Ubuntu 16.04

## Actual behavior
The tab completion of the method signature addeds the string 'param' befor the arguments and have seen this problem sense the last update i don't know wheter it is the vscode or extension 
## Steps to reproduce:  
-  call a method from the class or and let tab completion display the method signature 
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```custom python path, pylint path, ignore file 
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
Please could you upload a sample code you've used for this.

**Comment by mdalpi** [comment]
![](http://i.giphy.com/uRY6QRxfnRKrm.gif)
VS Code version: 1.9.1
Python Extension version: 0.5.8
Python Version: 3.6

**Comment by DonJayamanne** [comment]
Excellent thanks

**Comment by DonJayamanne** [comment]
This has been fixed in the dev version. Fix will be in the next release.
