### ISSUE TITLE
Debug a python file in bash on windows

### ISSUE THREAD

**Issue by aviklai** [DonJayamanne/pythonVSCode#747]
I have a python file in my Bash on Windows environment. Is it possible to debug it with python for VSCode?
Can a debugger be attached to the Linux python version that exists in the Bash on Windows environment?

**Comment by DonJayamanne** [comment]
Unfortunately currently this isn't possible.
Hopefully we'll have something in April, when Bash on Windows 10 receives several enhancements in the upcoming Windows 10 update. Se more here for instance: https://news.ycombinator.com/item?id=13695255

Will be looked at along with https://github.com/DonJayamanne/pythonVSCode/issues/765

**Comment by mloskot** [comment]
Any updates on this issue?

**Comment by DonJayamanne** [comment]
Sorry, nothing yet. I have decided to park debugger issues for now as the Microsoft PTVS team is in the process of refactoring the PTVS debugger to make it compatible with the VSCode debugger protocol, meaning there will be a lot of changes to come soon, or the Msft PTVS team may end up deploying their own debugger.. Plenty of unknowns at this stage, hence the decision to park it for now.

**Comment by DonJayamanne** [comment]
Closing in favor of #765

**Comment by mloskot** [comment]
Understood, thank you
