### ISSUE TITLE
"Go to definition" doesn't work with symbols imported in a group

### ISSUE THREAD

**Issue by thauk-copperleaf** [DonJayamanne/pythonVSCode#749]
## Environment data
VS Code version:  1.9.1
Python Extension version:  0.5.8
Python Version:   3.6
OS and version:    Windows 7

## Actual behavior

Go to definition does not work on symbols imported as a group, e.g. given:

```
from pkg import (
    Foo,
)
```

Right-clicking on `Foo` and selecting Go to definition does nothing.

## Expected  behavior

That it does work.

## Steps to reproduce:  
-  Try using Go to definition on a symbol imported in a group

**Comment by DonJayamanne** [comment]
@thauk-copperleaf  Apologies for never getting back to you on this. Works at my end with the latest version, please re-open if the issue still exists.
