### ISSUE TITLE
"Goto symbol" should include methods

### ISSUE THREAD

**Issue by abetkin** [DonJayamanne/pythonVSCode#75]
Currently you can only navigate to classes and functions, which is not the best behaviour.

Editors like sublime, atom include methods in the list of "symbols".

**Comment by wakensky** [comment]
Agree!  It is very important for us to goto methods

**Comment by wakensky** [comment]
Suggest @DonJayamanne may try to configure jedi appropriately (hard to believe jedi could not pick out methods). Thanks!

**Comment by wakensky** [comment]
@abetkin  It's simple to fix.  Try [this pullrequest](https://github.com/DonJayamanne/pythonVSCode/pull/85/files)

**Comment by DonJayamanne** [comment]
Will include into the next build
