### ISSUE TITLE
Cannot Run Python File in Terminal

### ISSUE THREAD

**Issue by LukaStellwag** [DonJayamanne/pythonVSCode#750]
## Environment data
VS Code version:  1.9.1.
Python Extension version: 0.5.2  
Python Version:  Anaconda 4.2.0.
OS and version:   macOS 10.12.2 Sierra

## Actual behavior

SyntaxError: invalid syntax
>>> /anaconda/bin/python "/Users/luka/Desktop/hello.py"
  File "<stdin>", line 1
    /anaconda/bin/python "/Users/luka/Desktop/hello.py"

## Expected  behavior

Output hello world!

## Steps to reproduce:  
-  Create a new file with the following code
print("hello world!")
-  Select Run Python File in Terminal

Selecting Run Selection in Terminal works fine and does not result in an error.

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
SyntaxError: invalid syntax
>>> /anaconda/bin/python "/Users/luka/Desktop/hello.py"
  File "<stdin>", line 1
    /anaconda/bin/python "/Users/luka/Desktop/hello.py"
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
Hi, i'm unable to replicate this issue.
Please could you try the following:
1. Select the first line of code, and try the command ```Python: Run Selection/Line in Python Terminal```  
2. Please could you the following in a terminal window:
```/anaconda/bin/python "/Users/luka/Desktop/hello.py"```

**Comment by LukaStellwag** [comment]
Hi, appreciate your help. 

I've ran the command "python select workspace interpreter" and selected anaconda. VS Code has changed my workspace settings in the settings.json to the correct path and now everything works as expected.

Thanks

**Comment by squarewave24** [comment]
i have the same problem. i can select run python in the window, but when i choose "run python file in termainal" i get invalid syntax

```
>>> /usr/local/bin/python3 /Users/xx/dev/python/proofofwork.concept.py
  File "<stdin>", line 1
    /usr/local/bin/python3 /Users/xx/dev/python/proofofwork.concept.py
    ^
SyntaxError: invalid syntax
```

**Comment by kevindavenport** [comment]
Code 1.27 
MacOS 10.13.6 (17G65)

Same issue regardless of selected Interpreter. Can run lines in VS Code but the contextual menu setting of running file from terminal fails our with syntax error.
