### ISSUE TITLE
auto-complete(python plugin) has no effect if i input "#!/" first

### ISSUE THREAD

**Issue by junmoxiao** [DonJayamanne/pythonVSCode#751]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.8|
|Go|lukehoban|0.6.53|

---

Steps to Reproduce:

1.create an python file 
2.input "#!/usr/bin/env python"
3.then the editor cannot auto complete

**Comment by DonJayamanne** [comment]
1. Please could you look at the contents of the Python output channel   
2. and the console window in Developer Tools.  
3. Next, please try changing the shebang to the following:  
```
#!/usr/bin/env/python
```

**Comment by junmoxiao** [comment]
![code1](https://cloud.githubusercontent.com/assets/9711902/23058389/b8cb40c4-f52f-11e6-88f7-f171a3b56544.png)
![code2](https://cloud.githubusercontent.com/assets/9711902/23058390/ba4ca7f8-f52f-11e6-8e88-a7ccfff96e6d.png)
@DonJayamanne please see my uploaded picture, I guess this may be caused by the plugin can not recognize the shebang

**Comment by junmoxiao** [comment]
and the plugin will prompt even in comment.if close the analyze in comment this problem may be solved.
![code3](https://cloud.githubusercontent.com/assets/9711902/23058620/d87d613a-f530-11e6-99c6-9eb02f219491.png)
![code4](https://cloud.githubusercontent.com/assets/9711902/23058642/fd3073fa-f530-11e6-9cab-8ce29afb07cd.png)

**Comment by DonJayamanne** [comment]
Closed with a3aaf16729ce3ca488a6baf201c5637dc3fa3853
