### ISSUE TITLE
Use in multi-language projects?

### ISSUE THREAD

**Issue by TomasPuverle** [DonJayamanne/pythonVSCode#752]
Hi, 

I have a multi-language project, rooted at, say, "proj".  Under the root, there is a directory structure of
"lib/<lang>/".  

This sees to cause issues for both the debugger and the linter, as they can't find the project imports.  Is there any way of setting up PYTHONPATH to let the tools know where the python modules are located?

Thanks,

Tom

**Comment by DonJayamanne** [comment]
The next version of the extension will support specifying PYTHONPATH Env setting

**Comment by TomasPuverle** [comment]
Ah, that's great!  Thank you.  The only thing is: what will it be called?  pythonPath is already taken. :)

**Comment by DonJayamanne** [comment]
Environment variable and Env file

**Comment by DonJayamanne** [comment]
https://github.com/DonJayamanne/pythonVSCode/issues/686
