### ISSUE TITLE
Not able to type any input in powershell (integrated terminal) in debug mode (F5) when it runs at second time. 

### ISSUE THREAD

**Issue by yjs990427** [DonJayamanne/pythonVSCode#754]
## Environment data
VS Code version:  1.9.1
Python Extension version:  0.5.8
Python Version:   3.5.3
OS and version:    windows 10 latest

## Actual behavior
2nd time of running python code which involves input() in powershell integrated terminal would not accept any typing 
## Expected  behavior
should accept typing and work fine 
## Steps to reproduce:  
-  using `print(input())`
-  1st time works, but when I run it 2nd time with the same integrated powershell terminal, it does not let me type the `input()` 

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
        {
            "name": "Integrated Terminal/Console",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "console": "integratedTerminal",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by King-of-Infinite-Space** [comment]
I have the same problem. 
Have to kill the "Python Debug Console" terminal window if I want to run it a second time.

**Comment by DonJayamanne** [comment]
Apologies for getting back to you this late on the issue.
Works at my end, please could you provide the exact steps required to reproduce this issue.
E.g. how do you end the debugger, in order to start debugging again?  
Do you enter the input value and press ```Enter```

**Comment by yjs990427** [comment]
I tried to reproduce this issue again, and found the two things.

1. The input worked at the second time of the execution of the script __when the first execution was finished with an `Enter` in the `PowerShell` terminal__
2. However, it did not work at the second time of the execution of the script __when the first execution was finished with the `stop` button of the vscode debugger tools.__

Is this helpful? If you need more info, feel free to ask me more

**Comment by DonJayamanne** [comment]
Closing. As the terminal is waiting for input, that's why the second time it with work.
