### ISSUE TITLE
minor issue with intellisense for attribute docstrings

### ISSUE THREAD

**Issue by robomojo** [DonJayamanne/pythonVSCode#755]
## Environment data
VS Code version:  1.9.1
Python Version: 2.7.11
OS and version: Win10

## Actual behavior
I can see the attribute docstring in the dropdown (which is great!), but i need to write the docstring above the variable.

![attribute_docstrings](https://cloud.githubusercontent.com/assets/4049406/23090003/72a03f88-f5e7-11e6-8e69-b436e2d7fd7d.png)

## Expected  behavior
According to http://stackoverflow.com/questions/6060813/how-to-document-fields-and-properties-in-python, the string should occur immediately **after** the variable.

**Comment by DonJayamanne** [comment]
Please could you report this issue on the Jedi repo (https://github.com/davidhalter/jedi)

**Comment by rob3c** [comment]
I'm not sure how this is considered 'minor', since it shows the completely wrong intellisense for every class attribute according to my understanding of python docstring conventions...however  backwards they may be :-)

Is there a particular jedi issue that is tracking this anyone can point me to?

**Comment by rob3c** [comment]
Here's a screenshot from a django model that shows the clash between the model class docstring and that of its first declared attribute:

![2017-07-06 vscode python docstring problem](https://user-images.githubusercontent.com/1098077/27938734-f7ae1340-628d-11e7-9345-26ecdf1929e5.jpg)

(had to use my phone so the mouseover wouldn't disappear)
