### ISSUE TITLE
Rightclick -> Run selection in Python Terminal doesn't work

### ISSUE THREAD

**Issue by dalyIsaac** [DonJayamanne/pythonVSCode#758]
## Environment data
VS Code version:  1.10.0-insider
Python Extension version:  0.5.8
Python Version:   3.6.0
OS and version:    Windows 10 build 15031

## Actual behavior
Right clicking on a function which exists within a class and selecting "Run selection in Python Terminal" produces `IndentationError: unexpected indent`

## Expected  behavior
The function should be loaded into the terminal, so I can access it and pass values into it
## Steps to reproduce:  
-  Right click a function within a class, and select "Run selection in Python Terminal"
-  Look at Terminal

## Logs
Output from ```Terminal``` output panel  
```IndentationError: unexpected indent
```>>>                 alphabet -= 25
```  File "<stdin>", line 1
```    alphabet -= 25
```    ^

**Comment by DonJayamanne** [comment]
Please could you provide the file with the line numbers of the code that you've selected for execution.
