### ISSUE TITLE
Python vscode autocomplete not working !

### ISSUE THREAD

**Issue by toplinuxsir** [DonJayamanne/pythonVSCode#759]
## Environment data
VS Code version:   1.9.1
Python Extension version:  
Python Version:   2.7.13
OS and version:    debian 9.0

## Steps to reproduce:  
1. Create a blank test.py file
2 .Enter  #  coding=utf-8 at the first line 
 Attention: after #, must follow a blank.

-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
Please confirm there's nothing in the ```Python``` output panel and also the output from the ```COnsole Window``` (Help->Developer Tools menu)

**Comment by toplinuxsir** [comment]
Python output panel : Nothing
Develop tools menu console ouptut:
[/home/lhs/.vscode/extensions/idleberg.emoji-code-0.1.11]: “contributes.snippets.language”中存在未知的语言。提供的值: livescriptd.logExtensionHostMessage @ extensionHost.ts:282
extensionHost.ts:282[Extension Host] [/home/lhs/.vscode/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: “contributes.snippets.language”中存在未知的语言。提供的值: ejsd.logExtensionHostMessage @ extensionHost.ts:282
extensionHost.ts:282[Extension Host] [/home/lhs/.vscode/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: “contributes.snippets.language”中存在未知的语言。提供的值: latted.logExtensionHostMessage @ extensionHost.ts:282
extensionHost.ts:282[Extension Host] [/home/lhs/.vscode/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: “contributes.snippets.language”中存在未知的语言。提供的值: tpld.logExtensionHostMessage @ extensionHost.ts:282
extensionHost.ts:282[Extension Host] [/home/lhs/.vscode/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: “contributes.snippets.language”中存在未知的语言。提供的值: tsd.logExtensionHostMessage @ extensionHost.ts:282
extensionHost.ts:282[Extension Host] [/home/lhs/.vscode/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: “contributes.snippets.language”中存在未知的语言。提供的值: hamld.logExtensionHostMessage @ extensionHost.ts:282
extensionHost.ts:282[Extension Host] [/home/lhs/.vscode/extensions/xabikos.ReactSnippets-1.2.1]: “contributes.snippets.language”中存在未知的语言。提供的值: jsxd.logExtensionHostMessage @ extensionHost.ts:282
extensionHost.ts:282[Extension Host] Linux
extensionHost.ts:282[Extension Host] Looking for parseable documents...
extensionHost.ts:282[Extension Host] vscode-icons is active!
extensionHost.ts:282[Extension Host] Found all parseable documents.
extensionHost.ts:282[Extension Host] Parsing documents and looking for CSS class definitions...
extensionHost.ts:282[Extension Host] Sumary:
extensionHost.ts:282[Extension Host] 0 parseable documents found
extensionHost.ts:282[Extension Host] 0 CSS class definitions found
extensionHost.ts:282[Extension Host] 0 unique CSS class definitions found
extensionHost.ts:282[Extension Host] 0 failed attempts to parse. List of the documents:
extensionHost.ts:282[Extension Host] 
2extensionHost.ts:282[Extension Host] Error: certificate has expired
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)

**Comment by toplinuxsir** [comment]
I also tested on windows10 , the same problem .

**Comment by toplinuxsir** [comment]
windows 10 output when enter os. after enter dot , the output is :
workbench.main.js:138 channel closed: Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at IPCMessageWriter.write (C:\Users\lhs\.vscode\extensions\tht13.python-0.2.3\node_modules\vscode-jsonrpc\lib\messageWriter.js:34:22)
    at Object.sendNotification (C:\Users\lhs\.vscode\extensions\tht13.python-0.2.3\node_modules\vscode-jsonrpc\lib\main.js:180:27)
    at Object.didChangeTextDocument (C:\Users\lhs\.vscode\extensions\tht13.python-0.2.3\node_modules\vscode-languageclient\lib\main.js:55:70)
    at Delayer.task (C:\Users\lhs\.vscode\extensions\tht13.python-0.2.3\node_modules\vscode-languageclient\lib\main.js:373:28)
    at C:\Users\lhs\.vscode\extensions\tht13.python-0.2.3\node_modules\vscode-languageclient\lib\utils\async.js:27:36e.onUnexpectedError @ workbench.main.js:138(anonymous function) @ workbench.main.js:138e.onUnexpectedError @ workbench.main.js:30o @ workbench.main.js:30t.onUnexpectedExtHostError @ workbench.main.js:114e.handle @ workbench.main.js:113s @ workbench.main.js:51f @ workbench.main.js:51_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98

**Comment by DonJayamanne** [comment]
Are you sure u have my python extension. You seem to have other python extensions installed that is throwing theses errors. Please uninstall other python extension except for mine then try again

**Comment by toplinuxsir** [comment]
I uninstall other python extension on windows 10 , and test again :
![1](https://cloud.githubusercontent.com/assets/1111353/23154837/b46b37be-f84a-11e6-85ee-f0c1ded89285.PNG)

the output is :

[Extension Host] Windows_NT
workbench.main.js:133 [Extension Host] Looking for parseable documents...
workbench.main.js:133 [Extension Host] vscode-icons is active!
workbench.main.js:133 [Extension Host] Array[55]
workbench.main.js:133 [Extension Host] Found all parseable documents.
workbench.main.js:133 [Extension Host] Parsing documents and looking for CSS class definitions...
workbench.main.js:133 [Extension Host] Sumary:
workbench.main.js:133 [Extension Host] 0 parseable documents found
workbench.main.js:133 [Extension Host] 0 CSS class definitions found
workbench.main.js:133 [Extension Host] 0 unique CSS class definitions found
workbench.main.js:133 [Extension Host] 0 failed attempts to parse. List of the documents:
workbench.main.js:133 [Extension Host] 
4workbench.main.js:133 [Extension Host] INVALID text edit -> must have at least a label

**Comment by DonJayamanne** [comment]
Ok, next, 
1. please remove the first line of text ```# coding=utf-8``` and try again   
2. Please confirm python is installed and is in your current path (open a terminal window and type ```python``` and let me know what you get

**Comment by toplinuxsir** [comment]
same problem , 
![image](https://cloud.githubusercontent.com/assets/1111353/23155609/64143eba-f84e-11e6-9263-cec4d5ed024d.png)

**Comment by DonJayamanne** [comment]
Please confirm python is installed and is in your current path (open a terminal window and type python and let me know what you get

**Comment by toplinuxsir** [comment]
still no autocompletting
![image](https://cloud.githubusercontent.com/assets/1111353/23155813/217bfa88-f84f-11e6-805d-3c415da18e94.png)

**Comment by DonJayamanne** [comment]
Please could you uninstall all the Python extensions and re-install just the one Python extension, then please take another screen dump with a list of all ```installed``` extensions and upload here. Thanks

**Comment by toplinuxsir** [comment]
Still not working 
![image](https://cloud.githubusercontent.com/assets/1111353/23284459/a6768f5a-fa66-11e6-98d7-3443b432cb99.png)

**Comment by toplinuxsir** [comment]
The problem still exist with vscode 1.10

**Comment by toplinuxsir** [comment]
It seems to be fixed in the version 0.5.9
