### ISSUE TITLE
Files with unicode characters displays error

### ISSUE THREAD

**Issue by jole78** [DonJayamanne/pythonVSCode#76]
If a file has unicode characters (ex åäö for Swedish) the extension shows an error. See attachment.

VSCode 0.10.10
Python 2.7.5
Linux 

![python_extension_error](https://cloud.githubusercontent.com/assets/2247346/14488930/e44cae9a-016a-11e6-9df0-b8d28bfa26b6.PNG)

**Comment by DonJayamanne** [comment]
Similar to issue #80

**Comment by DonJayamanne** [comment]
Sorry, but this cannot be fixed. Unicode characters are supported file paths when using python 3.5, unfortunately it won't work with python 2.7.

**Comment by jole78** [comment]
Since Vscode 1.0 and the latest extension the problem had gone away fortunately. 

-------- Original message --------
