### ISSUE TITLE
Debugging step over not step to next line when it go to another package

### ISSUE THREAD

**Issue by eromoe** [DonJayamanne/pythonVSCode#760]
I write some code and try to see what a module working by debuging, such as below code

test.py:
```
from thulac import thulac
s = '我们今天出去野餐'
t = thulac()
words = t.cut(s) # breakproint has set in t.cut
for e in words:
    print('%s' % e)
```

In this file `test.py`,  `F10` does step next line. But after it hit the breakpoint I set in `t.cut` function,  `F10`  doesn't step to next line any more, instead it just goto the next breakpoint! 

Is this by design? Could I change the behave to always step to next line?

**Comment by DonJayamanne** [comment]
where is the source for ```thulac```.
Please could you upload the sample code along with the source for ```thulac``` (i'd need the entire folder to replicate this at my end).
Also what OS are python version are you using?

**Comment by eromoe** [comment]
This lib https://github.com/thunlp/THULAC-Python

- OS: Windows 7/10 X64
- ENV: python 3.5/3.6

**Comment by DonJayamanne** [comment]
@eromoe Apologies for not getting back to you on this issue. Are you still experiencing this issue?

**Comment by eromoe** [comment]
I also can't get `thulac` work on my windows now, and I forgot  which version I use at that time .... maybe just skip now.
