### ISSUE TITLE
Starting the most simple flask app in the debugger takes 30 seconds

### ISSUE THREAD

**Issue by andersea** [DonJayamanne/pythonVSCode#761]
## Environment data
VS Code version:  Version 1.9.1
Python Extension version:  0.5.8
Python Version:   Python 3.5.2 (default, Nov 17 2016, 17:05:23)
OS and version:    Kubuntu 16.04 , Kernel 4.4.0-62-generic (64bit)

## Actual behavior

Creating a flask app with the most basic example:

```python
from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello():
    return "Hello World!"

if __name__ == "__main__":
    app.run()
```
Starting this app takes 30 seconds on my machine.

## Expected  behavior

Less than 30 seconds to start. 10 maybe. 30 seconds is just too much.
Running it from the command line makes it start instantly.

## Steps to reproduce:  
-  Create a folder with a basic flask app. See above snippet.
-  Create a virtual environment in the folder (python3 -m venv env)
-  Activate the venv and install flask
-  Go to the debugger and click play.

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
        {
            "name": "Flask",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${workspaceRoot}/env/bin/flask",
            "cwd": "${workspaceRoot}",
            "env": {
                "FLASK_APP": "${workspaceRoot}/app.py"
            },
            "args": [
                "run",
                "--no-debugger",
                "--no-reload"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
```   
Your settings.json:   
```json
// Place your settings in this file to overwrite default and user settings.
{
    "python.pythonPath": "${workspaceRoot}/env/bin/python"
}
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by andersea** [comment]
Launching the app with top launch.json entry 'python', which just runs app.py takes 15 seconds to start. The cpu on my laptop really churns and fans start to spin up.

**Comment by gandhis1** [comment]
Try it again with stoponEntry false for the launch JSON. Does that change anything?

**Comment by andersea** [comment]
It is already set to false. Thats the default setting for Flask debugging.

**Comment by DenisPalchuk** [comment]
+1. The same issue. Linux 4.8.0-58-generic #63~16.04.1-Ubuntu. Looks like it works slow only on linux machines and only using virtual environments.

**Comment by DonJayamanne** [comment]
Closing in favor of https://github.com/DonJayamanne/pythonVSCode/issues/897
