### ISSUE TITLE
Linting does not start when vscode is started from terminal

### ISSUE THREAD

**Issue by causztic** [DonJayamanne/pythonVSCode#762]
## Environment data
VS Code version:  1.9.1
Python Extension version:  0.5.8
Python Version:   2.7.10
OS and version:    macOS Sierra 10.12.3 (16D32)

## Actual behavior
Pylint does not lint the documents opened when vscode is started with the command
`code .` from Terminal.

## Expected  behavior
Pylint should automatically lint files on save and on open. It works fine when I start vscode manually from my Applications Folder, however.

## Steps to reproduce:  
-  Open Terminal
-  Type `code .` to open in current directory

## Settings  

Your settings.json:   
```json
{
    "editor.fontLigatures": true,
    "editor.fontFamily": "Fira Code",
    "window.zoomLevel": 0.1,
    "terminal.integrated.fontFamily": "Inconsolata",
    "terminal.integrated.fontLigatures": false
}
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
Outputs are same for both when starting from console or manually
```
bash-3.2$ which python
/usr/bin/python
bash-3.2$ which pylint
/usr/local/bin/pylint
```

**Comment by DonJayamanne** [comment]
Please could you confirm no errors are displayed in the ```Python``` output channel (this is the output panel displayed along with the ```Git```, ```Tasks``` (dropdown) output panels.  
Also please open Help->Developer Tools and go into the ```Console``` tab and check if there are any errors logged in there.

**Comment by causztic** [comment]
No errors for Python output channel nor the Console Tab  in Developer Tools

**Comment by DonJayamanne** [comment]
Please could you test the latest version and let me know how it is

**Comment by causztic** [comment]
Opening Visual Studio Code from Terminal still doesn't run the Linter for some reason :\ Thank you for your hard work though! @DonJayamanne in the meantime I'm running it by double clicking

**Comment by DonJayamanne** [comment]
Please reopen if the problem persists.
