### ISSUE TITLE
auto import - feature request

### ISSUE THREAD

**Issue by ychab** [DonJayamanne/pythonVSCode#764]
Hi,

Don't known if this is already in the roadmap but having support for auto import, just like this plugin for Typescript : https://marketplace.visualstudio.com/items?itemName=steoates.autoimport would be awesome!

Unfortunetly, I can't give a help for development (time and knowledge!) but would enjoy to do end user testing!

Thanks

**Comment by troyharvey** [comment]
+1 Feature Request: Importing packages on the fly

- VSCode Version: 1.10.2 
- OS Version: macOS 10.12.3

Feature Request:

1. Start typing the name of a Python class or function that has not been imported. It turns red.
2. `⌥ + ⏎`  should auto-import the class or show a list of potential matches that can be added to the import list on the fly.

See [PyCharm 2016.3 Help: Importing packages on the fly](https://www.jetbrains.com/help/pycharm/2016.3/creating-imports.html#d1022065e122)

**Comment by skyjur** [comment]
Trying to do some progress:

https://github.com/DonJayamanne/pythonVSCode/compare/master...skyjur:feature/764-auto-import?expand=1

I've added a command `autoImportAtCursor`. It selects a symbol under the cursor, and tries to locate the symbol using `vscode.executeWorkspaceSymbolProvider`. Currently python symbols are supported through ctags, so it should work if ctags is configured.

I'm converting file paths into python module, by checking for __init__.py in parent directories. I believe it might not be ideal solution. Anyone has better idea or can refer to a piece of code that can do this?

This is my first ever code piece in typescript - any kind of feedback highly welcome.

**Comment by DonJayamanne** [comment]
Merged, will be available in the next release

**Comment by andreyfedoseev** [comment]
@DonJayamanne Do you have any plan on when the next release will be published?

**Comment by JGH1000** [comment]
+1

**Comment by JGH1000** [comment]
Added to feature requests in https://github.com/DonJayamanne/pythonVSCode/issues/183

**Comment by JGH1000** [comment]
Not sure if this would help at all but https://github.com/alecthomas/importmagic does exactly that. Might be easier to use a continually developed python library?

**Comment by DonJayamanne** [comment]
Closing in favor of https://github.com/Microsoft/vscode-python/issues/21
