### ISSUE TITLE
Add support for Bash on Windows 10

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#765]
Apologies everyone, I haven't been focusing on officially supporting Bash on Windows 10.
I'll be looking into this some time early march.

**Comment by DonJayamanne** [comment]
Related issues
- [ ] #762 
- [ ] #756 
- [ ] #747 
- [ ] #729 
- [ ] #534

**Comment by Agnpalm** [comment]
Bash on Windows 10 will receive several enhancements in the upcoming Windows 10 update. Se more here for instance: https://news.ycombinator.com/item?id=13695255

**Comment by DonJayamanne** [comment]
@Agnpalm wow thanks

**Comment by OmriSama** [comment]
Any updates?

**Comment by brettcannon** [comment]
No concrete updates yet, but WSL is definitely on the short list of things to add.

**Comment by DonJayamanne** [comment]
Closing in favor of https://github.com/DonJayamanne/pythonVSCode/issues/534
