### ISSUE TITLE
Issue with VS Code with Python 3.6 using matplotlib

### ISSUE THREAD

**Issue by arhubwx** [DonJayamanne/pythonVSCode#768]
## Environment data
VS Code version:  1.9.1
Python Extension version:  0.5.8
Python Version:   3.6
OS and version:    Mac OSX 10.12.3

## Actual behavior
Not able to launch python simple app using matplot.lib  Not sure which settings are not configured right to execute this app.  new to using this extension

import matplotlib.pyplot as plt
plt.plot([1, 4, 9 ,16 ,25])
plt.show()

## Expected  behavior
Launch a simple line chart

## Steps to reproduce:  
-run file both in build mode, run cell and jupyter, tried multiple options same result
  

## Settings  
Your launch.json (if dealing with debugger issues):  
{
    "version": "0.2.0",
    "configurations": [

        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}"
        ]
}
Your settings.json:   
{

    "python.pythonPath": "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6",
    "python.autoComplete.extraPaths": [
        "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages"
    ]

}
## Logs
Output from ```Python``` output panel  
{
    "version": "0.2.0",
    "configurations": [

        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}"
        }]
}
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
Do you have [Jupyter](http://jupyter.org/) installed on your Machine?  (check here for [prerequisites](https://github.com/DonJayamanne/pythonVSCode/wiki/Jupyter-(IPython)-Prerequisites))

1. Please paste the following code into a file named p.py  
```python
#%%
import matplotlib.pyplot as plt
plt.plot([1, 4, 9 ,16 ,25])
plt.show()
```
2. Ensure you have a workspace (folder) opened in VS Code  
3. Click on ```Run Cell``` (displayed above the ```#%%```)  

Please provide the following information:   
1. Output from Console window (Help->Developer Tools menu)  
2. Output from Python output panel  (this is the Panel display along with ```Git```, ```Tasks``` output panels)

**Comment by arhubwx** [comment]
Thanked for the follow up. After going back as per your note and
uninstalling and re-installing the libraries both Jupiter and Matplot lib
then installing VS Code the libraries and the extensions it now works.

Thanks for the assistance.


On February 26, 2017 at 4:06:37 AM, Don Jayamanne (notifications@github.com)
wrote:

Do you have Jupyter <http://jupyter.org/> installed on your Machine? (check
here for prerequisites
<https://github.com/DonJayamanne/pythonVSCode/wiki/Jupyter-(IPython)-Prerequisites>
)

   1. Please paste the following code into a file named p.py

#%%import matplotlib.pyplot as plt
plt.plot([1, 4, 9 ,16 ,25])
plt.show()


   1. Ensure you have a workspace (folder) opened in VS Code
   2. Click on Run Cell (displayed above the #%%)

Please provide the following information:

   1. Output from Console window (Help->Developer Tools menu)
   2. Output from Python output panel (this is the Panel display along with
   Git, Tasks output panels)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DonJayamanne/pythonVSCode/issues/768#issuecomment-282542779>,
or mute the thread
