### ISSUE TITLE
os.environ.get failed to get environment variable defined in .bash_profile and .bashrc

### ISSUE THREAD

**Issue by xqliu** [DonJayamanne/pythonVSCode#77]
Dear, 

Found an issue that:

during debug, os.environ.get can not  get environment variable defined in .bash_profile and .bashrc

Seems the environment variables defined is not passed to running python process

Inspected and found value to be None while set them in .bash_profile.

OS: Mac OS 
VS code version: 1.0
Python Plugin version: 0.3.3

**Comment by rickerliang** [comment]
There is the same problem on ubuntu.

**Comment by cdnsteve** [comment]
I know VS Code supports `"env": {}` within `launch.json` have you tried adding anything there?

**Comment by xqliu** [comment]
The follow settings in launch.json fixes this issue:

```
{
			"name": "Flask",
			"type": "python",
			"request": "launch",
            "pythonPath": "/Users/larry/Projects/betterlife/codes/psi/venv/bin/python",
			"stopOnEntry": true,
			"program": "${workspaceRoot}/wsgi.py",
			"args": [
				"runserver",
				"--noreload"
			],
			"debugOptions": [
				"WaitOnAbnormalExit",
				"WaitOnNormalExit",
				"RedirectOutput",
				"DjangoDebugging"
			],
			"env": {
				"SECRET_KEY" : "12345",
				"DATABASE_URL": "postgres://flask:flask@localhost:5432/flask",
				"DEBUG": "True"		 	
			}			
		}
```

**Comment by DonJayamanne** [comment]
Fixed
