### ISSUE TITLE
UTF-8 characters don't show up correctly on the method tooltip

### ISSUE THREAD

**Issue by joaopms** [DonJayamanne/pythonVSCode#771]
## Environment data
VS Code version: 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519)
Python Extension version: 0.5.8
Python Version: 3.6.0
OS and version: Windows 10 (Version 1607 - Build 14393)

## Actual behavior
Method docstring (`Lê e configura a configuração da aplicação`) doesn't show as expected on the method tooltip (displays as `LÃª e configura a configuraÃ§Ã£o da aplicaÃ§Ã£o`).

As weird as it is, appending `あ` to the docstring (`Lê e configura a configuração da aplicação あ`) makes the method tooltip show the docstring as expected.

## Steps to reproduce:  
- Create a method with a docstring as `"""Lê e configura a configuração da aplicação"""`
- Observe the tooltip. Should be broken (http://i.imgur.com/sI1jnkw.png)
- Create a method with a docstring as `"""Lê e configura a configuração da aplicação あ"""`
- Observe the tooltip. Should display as expected (http://i.imgur.com/bmiNY5A.png)

**Comment by DonJayamanne** [comment]
This has been fixed in the latest build
Possibly fixed along with #727 (or some other fix)
Fix will be in the next release of the extension, sometime next week.
