### ISSUE TITLE
Pylint: TensorFlow (Unable to import module/Missing module docstring/autocomplete)

### ISSUE THREAD

**Issue by tomwanzek** [DonJayamanne/pythonVSCode#772]
## Environment data
VS Code version:  1.9.1
Python Extension version:  0.5.8
Python Version:   Python 3.5.3 :: Continuum Analytics, Inc. (Installed in an Anaconda conda virtual environment for TensorFlow)
OS and version:    Windows 10

## Actual behavior

* `import tensorflow as tf` shows the following **pylint** issues:
  * [E0401] Unable to import 'tensorflow'
  * [C0111] Missing module docstring
* no autocomplete support for `tf.`
* However, mouseovers reveal valid informative tooltip text for tensorflow members, e.g. `tf.constant` or `tf.session`, in the IDE

## Expected  behavior

No **pylint** issues expected.
Autocomplete works.

## Steps to reproduce:  
-  Install Anaconda distribution and create virtual environment based on Python 3.5 (due to current  TensorFlow restriction to 3.5 on Windows)
- install TensorFlow into the conda environment.
- Use command palette to set conda environment with `Python: Select workspace interpreter`
- Create python file with following minimal repro content:
```python
import tensorflow as tf

print('TensorFlow version: {0}'.format(tf.__version__))
HELLO = tf.constant('Hello, TensorFlow!')
SESS = tf.Session()
print(SESS.run(HELLO))
```
Note: I also experienced the issue with the other options to working with a conda virtual environment described in the Wiki for this VS code extension.

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
{
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }
    ]
}
```   
Your settings.json:   
```json
{
    "python.pythonPath": "C:/Users/anybody/Anaconda3/envs/tfgpuenv/python"
}
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
Please confirm pylint is installed in the following python environment:. 

C:/Users/anybody/Anaconda3/envs/tfgpuenv/python

**Comment by tomwanzek** [comment]
@DonJayamanne thx for the amazing quick response. Yes, that seems to have been at the heart of it. It was indeed pulling **pylint** in from the `Anaconda3/scripts` directory instead of the environment. I installed it into the environment and it seems to work. My bad 😞

**Comment by DonJayamanne** [comment]
No need to apologise. How else would you have solved the problem. 😀
