### ISSUE TITLE
Intellisense does not work for standard Python modules.

### ISSUE THREAD

**Issue by mbaccia514** [DonJayamanne/pythonVSCode#773]
## Environment data
VS Code version:  1.9.1 
Python Extension version: 0.5.8
Python Version: 3.6.0
OS and version: Windows 10 Edu 1607

## Actual behavior
Intellisense does not show definitions for functions in the standard library. I tried reproducing one of the examples you have on the main page using time.sleep(); below is what I currently see:

![alt tag](https://s16.postimg.org/ymaegfx79/python_intellisense1.png)

![alt tag](https://s16.postimg.org/f5potx239/python_intellisense2.png)

## Expected  behavior
Display the definition for the highlighted function:

![alt tag](https://raw.githubusercontent.com/DonJayamanne/pythonVSCodeDocs/master/images/general.gif)

## Steps to reproduce:  
-  Highlight standard module function.

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
{
    "editor.fontSize": 16,
    "editor.rulers": [80],

    "python.linting.pylintEnabled": true,
    "python.linting.pep8Enabled": true
}
```   
## Logs
Output from ```Python``` output panel  
```
##########Linting Output - pep8##########
##########Linting Output - pylint##########
************* Module test
1,0,convention,C0111:Missing module docstring
2,0,warning,W0104:Statement seems to have no effect
2,0,error,E1101:Module 'time' has no 'slee' member

No config file found, using default configuration
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2595  for  PowerShell.ExpandAlias
extensionHost.ts:282[Extension Host] Looking for parseable documents...
extensionHost.ts:282[Extension Host] vscode-icons is active!
extensionHost.ts:282[Extension Host] Found all parseable documents.
extensionHost.ts:282[Extension Host] Parsing documents and looking for CSS class definitions...
extensionHost.ts:282[Extension Host] Sumary:
extensionHost.ts:282[Extension Host] 0 parseable documents found
extensionHost.ts:282[Extension Host] 0 CSS class definitions found
extensionHost.ts:282[Extension Host] 0 unique CSS class definitions found
extensionHost.ts:282[Extension Host] 0 failed attempts to parse. List of the documents:
extensionHost.ts:282[Extension Host] 
```

**Comment by plunntic** [comment]
Same here. I'm getting similar (bad) behaviour on Arch linux, although i can see more methods in the intelisense (tried with `time` and `sys`) but i can't view the documentation as shown on last gif above.

Don't know if that's related but intelisense does not work properly on my own classes too. Some examples what's im talking about:

```python
class Test:
    """ Some class. """

    SOME_ENUM = 0

    def __init__(self, some_arg):
        """ Some docstring. """
        do_something()
```

Now if in another file i'll import the above and type `Test.SOM` intelisense doesn't open (however it does while typing it in the same file as the definition). I'm able to force it by ctrl+space and the it's showing correct autocomplete, but also, shows `Some class.` as the description of this property.

Where in case when i do `test = Test()` it doesn't show `Some class.` as the description of the class, neither any argument types, descriptions from the docstring - and i tried every standard i could find. Is there any officially supported flavour for intelisense to work with arguments, return value, exceptions and so on? I get only plain list of arguments taken from the function signature.

vscode 1.9.1 (installed from AUR using official .deb package)
python 3.6.0

User settings json:
```json
{
    "workbench.sideBar.location": "right",
    "workbench.editor.showTabs": false,
    "window.menuBarVisibility": "toggle",
    "editor.wordSeparators": "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?_",
    "editor.renderIndentGuides": true,
    "editor.formatOnType": true,
    "editor.formatOnPaste": true,
    "editor.formatOnSave": true,
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "**/__pycache__": true,
        "**/tags": true
    },
    "files.insertFinalNewline": true,
    "files.trimTrailingWhitespace": true,
    "files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/node_modules/**": true,
        "**/__pycache__/": true
    },
    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true,
        "**/__pycache__": true
    },
    "html.format.indentHandlebars": true,
    "python.autoComplete.addBrackets": true,
    "python.formatting.formatOnSave": true,
    "python.linting.ignorePatterns": [
        ".vscode/**/*.*",
        "**/site-packages/**/*.py",
        "**/*test*.py"
    ],
    "extensions.autoUpdate": true
}
```

Project settings json:
```json
{
    "python.unitTest.pyTestArgs": [
        "tests"
    ],
    "python.unitTest.pyTestEnabled": true
}
```

**Comment by DonJayamanne** [comment]
Please could you try the latest version.

**Comment by mbaccia514** [comment]
Thank you! Everything works perfectly now. :)
