### ISSUE TITLE
Intellisense and Autocomplete not working on PyQt4

### ISSUE THREAD

**Issue by lesintion** [DonJayamanne/pythonVSCode#780]
## Environment data
VS Code version:  1.9.1
Python Extension version:  0.5.8
Python Version: 2.7.13 (x64)
OS and version:  windows 10 (x64)

## Actual behavior
Hover on QtGui or QtGui.QMainWindow always display loading and not display the package or class definition information. The code can be executed successfully without error.

Thanks for your support in advance!

Here is the sample code:

#!/usr/bin/env python2
# -*- coding: utf-8 -*-
import os
from PyQt4 import **QtGui**, uic

class MainWindow(QtGui.QMainWindow):
    """"
    """
    def __init__(self, parent=None):
        super(MainWindow, self).__init__(parent)
        self.setupUi("mainWindow.ui")

    def setupUi(self, uiFileName):
        """load ui file
        """
        ui_file_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), uiFileName)
        self.ui = uic.loadUi(ui_file_path, self)
## Steps to reproduce:  
-  Open vscode and create a new class use above code
-  Hover on QtGui or QtGui.QMainWindow

## Settings  
Your launch.json (if dealing with debugger issues):  
```No bugs
```   
Your settings.json:   
```json
```   
 "python.autoComplete.extraPaths": [
        "C:/Program Files/Python/Python27",
        "C:/Program Files/Python/Python27/DLLs",
        "C:/Program Files/Python/Python27/Lib",
        "C:/Program Files/Python/Python27/Lib/site-packages",
        "C:/Program Files/Python/Python27/Lib/site-packages/PyQt4"
    ]
## Logs
Output from ```Python``` output panel  
```No logs
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
Apologies for never getting back to you. 
Works at my end, **please reopen this issue if the problem persists.**

Please ensure your ```python.pythonPath``` is pointing to the right interpreter as follows:
```json
"python.pythonPath": "C:/Program Files/Python/Python27/python.exe"
```
