### ISSUE TITLE
Go To Definition of object instance goes to definition of type

### ISSUE THREAD

**Issue by PeterJCLaw** [DonJayamanne/pythonVSCode#781]
## Environment data
VS Code version:  1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519)
Python Extension version:  0.5.8
Python Version:   2.7.12
OS and version:     Ubuntu 16.04

## Actual behavior

Navigation from variable usage to definition goes to definition of type of variable.

## Expected behavior

Should navigate to the definition of the variable.

## Steps to reproduce:  
-  Create a new file with the following contents:
``` python
class Item(object):
    pass

ONE = Item()
print(ONE)
```
-  Starting from the usage of `ONE` in the print statement, Ctrl+Click to go to the definition of the symbol.
 - should go to the line above
 - actually goes to the first line, at the position of the declaration of the `Item` class

This issue is also present (and far more of a problem) when the declaration of the type is far away from the declaration of the variable, for example because it's in another package.

## Settings  
Reproducible with a fresh project.

## Logs
None.

**Comment by PeterJCLaw** [comment]
Since version 0.7.0 and VSCode version 1.15.0 this appears fixed, but I haven't seen anything in the release notes which looks related.

**Comment by DonJayamanne** [comment]
The release notes should be on or version of a release, will check and update.
