### ISSUE TITLE
show all symbols in workspace is slow

### ISSUE THREAD

**Issue by kentor** [DonJayamanne/pythonVSCode#782]
## Environment data
VS Code version:  1.10
Python Extension version: 0.5.8
Python Version:  2.7.12
OS and version:  macOS 10.12.2  

## Actual behavior
show all symbols in workspace is slow

## Expected  behavior
could be faster or on par with sublime text

## Steps to reproduce:  
Not sure, I have a ctags file with about 48k lines (from a private project). It takes seconds from typing to showing a list of symbols. Sublime shows the symbols almost instantly

**Comment by DonJayamanne** [comment]
I'll try to add some optimizations into the filter, so as to return as soon ass 20-30 items are found. 
However, that might not be the best either, anyways, leave this with me and I'll try to think of something.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#86
