### ISSUE TITLE
Go to definition broken for decorated methods

### ISSUE THREAD

**Issue by zackkitzmiller** [DonJayamanne/pythonVSCode#785]
## Environment data
VS Code version:  1.10.1
Python Extension version:  2.7
Python Version: 3.5.9
OS and version: OS X 10.12.3 (16D32)   

## Actual behavior
Go to definition shows definition of the decorator method when a method is wrapped

## Expected  behavior
Go to definition shows the definition of selected method

## Steps to reproduce:  
- Make a new decorated method
- Call it from somewhere else
- Select `Go to definition` 
- Wrapper method definition is shown

<img width="991" alt="screen shot 2017-03-03 at 11 50 39 am" src="https://cloud.githubusercontent.com/assets/111536/23560250/bf4c9abe-0007-11e7-962d-fa97e71ff363.png">
<img width="1297" alt="screen shot 2017-03-03 at 11 50 53 am" src="https://cloud.githubusercontent.com/assets/111536/23560249/bf4c00cc-0007-11e7-9c57-7e951f5b5405.png">

**Comment by PeterJCLaw** [comment]
Duplicate of #742?

**Comment by zackkitzmiller** [comment]
Sure is!
