### ISSUE TITLE
Retina matplotlib (IPython)

### ISSUE THREAD

**Issue by yay** [DonJayamanne/pythonVSCode#786]
## Environment data
VS Code version:  1.10.1
Python Extension version:  
Python Version:  3.6
OS and version:  macOS 10.12.3

Note: this issue should be viewed on a retina display to see the difference.

## Actual behavior
matplotlib images are blurry on hiDPI ("retina") displays:

<img width="423" alt="screen shot 2017-03-04 at 00 07 33" src="https://cloud.githubusercontent.com/assets/1799756/23572372/008d8b16-006f-11e7-96a9-33c7fcd91051.png">

The following startup options in package.json are used by the plugin by default:

![screen shot 2017-03-04 at 00 07 42](https://cloud.githubusercontent.com/assets/1799756/23572388/1555ef48-006f-11e7-8e8c-e6b4c0b59a6d.png)

## Expected  behavior
The following startup options are expected (if the devicePixelRatio is 2):

![screen shot 2017-03-04 at 00 10 13](https://cloud.githubusercontent.com/assets/1799756/23572431/5661c246-006f-11e7-9c62-bebae45033cd.png)

However, this still doesn't solve the problem competely, because the image is now twice the size, but still blurry:

<img width="753" alt="screen shot 2017-03-04 at 00 08 19" src="https://cloud.githubusercontent.com/assets/1799756/23572485/a15acaae-006f-11e7-8643-22f8a0bf5ef8.png">

This is because it has to be scaled down by 50% (which is the usual practice when rendering Canvas images on retina displays), to have the size of the original image above and look crisp:

<img width="450" alt="screen shot 2017-03-04 at 00 08 190" src="https://cloud.githubusercontent.com/assets/1799756/23572552/19f3010c-0070-11e7-89ee-dd803553ae49.png">

Notice how the fonts are visibly sharper. For this particular plot the difference is not very dramatic, but it will vary depending on the content of the plot, and can be much more obvious.

**Comment by yay** [comment]
Would also be nice if kernel json were not created in the script folder or were automatically cleaned up.

<img width="369" alt="screen shot 2017-03-04 at 00 36 26" src="https://cloud.githubusercontent.com/assets/1799756/23572922/d2440510-0072-11e7-8df6-456fb1dd7458.png">

As it is, they show up in the sidebar, and it's a drag to remove them manually, especially since you can't select multiple items in sidebar (e.g. while holding cmd, ctrl or shift) and have to remove them one by one.

**Comment by yay** [comment]
BTW, I only took the time to write all this because this extension is so awesome! :)

**Comment by gandhis1** [comment]
I reported the second issue in #506

**Comment by DonJayamanne** [comment]
Thanks for the excellent and detailed info. Helps me look into this issue, considering I am a novice Jupyter user.

Not sure how this is related to 506 though

**Comment by gandhis1** [comment]
His second post is

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/vscodeJupyter#3
