### ISSUE TITLE
Jupyter output limit to a parcel of the screen

### ISSUE THREAD

**Issue by Paul-Yuchao-Dong** [DonJayamanne/pythonVSCode#787]
Many thanks for your great contribution to python community. Now we have VS Code, a really fast editor for python coding as well as debugging. I see great potential here but I struggled to find my way around. Really hope anyone can help me out.

I have one related to jupyter on VS Code, powered by this extension.

1. Jupyter output seems to be not using screen real estate efficiently.
![image](https://cloud.githubusercontent.com/assets/7532271/23577135/a0a92438-00f2-11e7-8217-5a571adcf9ab.png)

Ideally it should also use **all** the part on the right of the screen? I think maybe it is making space for some other thing, such as minimap, but I don' really need it, want to see the chart instead.

P.S. really appreciate the great work! I am listening to Don's interview on Talk Python to Me, great stuff!
## Environment data
VS Code version:  1.10.1
Python Extension version:  0.5.9
Python Version:   3.5
OS and version:    Ubuntu 16.04

## Actual behavior

the image above

## Expected  behavior
Using the right half of the screen when displaying results from Jupyter 

## Steps to reproduce:  
-  plot or print anything with the jupyter integration
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by Paul-Yuchao-Dong** [comment]
I think I have figured out how to do item 1. Essentially I forgot to put an `$1` at the end.

```json
{
/*
	// Place your snippets for Python here. Each snippet is defined under a snippet name and has a prefix, body and 
	// description. The prefix is what is used to trigger the snippet and the body will be expanded and inserted. Possible variables are:
	// $1, $2 for tab stops, $0 for the final cursor position, and ${1:label}, ${2:another} for placeholders. Placeholders with the 
	// same ids are connected.
	// Example:
	"Print to console": {
		"prefix": "log",
		"body": [
			"console.log('$1');",
			"$2"
		],
		"description": "Log output to console"
	}
*/
"import common scipy libs": {
		"prefix": "imports",
		"body": [
			"#%%",
			"from __future__ import division, print_function",
			"import numpy as np",
			"import pandas as pd",
			"import matplotlib.pyplot as plt",
			"import matplotlib as mpl",
			"import seaborn as sns",
			"import re",
			"from calendar import monthrange",
			"from pandas_datareader import data as web",
			"from pandas.tseries.offsets import DateOffset, Second, Minute, Hour, Day",
			"import sympy as sy"
			"\n",
			"import plotly.graph_objs as pgo",
			"from plotly.offline import plot, init_notebook_mode, iplot, iplot_mpl",
			"import cufflinks as cf",
			"\n",
			"pd.options.display.max_rows = 10",
			"pd.set_option('max_columns', 50)",
			"sns.set(style='ticks', context='talk')",
			"%matplotlib inline",
			"$2"
		],
		"description": "import common scipy libs"
	}
}
```

**Comment by Paul-Yuchao-Dong** [comment]
Alright. Feel pretty stupid right now. I think I know how to set the keyboard shortcut for run cell now. Thanks Don for leaving the comments in VS Code's default key bindings. it is `jupyter.execCurrentCell`.

**Comment by Paul-Yuchao-Dong** [comment]
More info on this I tested the jupyter output in VSCode 1.9.1, and the limited output problem didn't materialize.

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/vscodeJupyter#2
