### ISSUE TITLE
Getting Unexpected Token Error when trying to debug from Integrated Console

### ISSUE THREAD

**Issue by khaled4vokalz** [DonJayamanne/pythonVSCode#788]
while trying to debug a python project using the Integrated Console an error is occuring from 
donjayamanne.python-0.5.9\pythonFiles\PythonTools\visualstudio_py_launcher.py file ..
Its showing Unexpected Token error.
Please help!

![ex](https://cloud.githubusercontent.com/assets/14083655/23577505/1f5b335a-00eb-11e7-8eb8-2c51cdf20fd7.png)

**Comment by DonJayamanne** [comment]
Fixed in https://github.com/DonJayamanne/pythonVSCode/commit/335c16d2940879141a94f60e6d551f034a867a23
https://github.com/DonJayamanne/pythonVSCode/commit/a27b24950e6b5aac2b7427f78b130d54972e07e9

Will release a new version soon and let you know once done.

**Comment by DonJayamanne** [comment]
@khaled4vokalz Please could you check whether you are still getting this error. 
If you are, please do reopen this issue.

**Comment by khaled4vokalz** [comment]
@DonJayamanne I tried a debug, It ran fine. Thanks for the fix.
