### ISSUE TITLE
Auto indent else inside if block

### ISSUE THREAD

**Issue by sword865** [DonJayamanne/pythonVSCode#789]
## Environment data
VS Code version:  1.10.1 (1.10.1)
Python Extension version:  0.5.9
Python Version:   2.7.13
OS and version:    OSX 10.11.6 

## Actual behavior
    if 2 > 1:
        a = 1
        else:
## Expected  behavior
    if 2>1:
        a = 1
    else:

This issue is similar to #432, but i think #432 is already fixed, so this may be a new bug cased by new version of vscode.

**Comment by gandhis1** [comment]
Are you sure you toggled editor.FormatOnType to true?

**Comment by sword865** [comment]
Yes, editor.FormatOnType is true

**Comment by DonJayamanne** [comment]
@sword865 Unfortunately I'm unable to replicate this. 
Please confirm you have ```editor.FormatOnType``` enabled (instead of ```editor.FormatOnSave```)  
Please could you try the VS Code Insiders version as well.

**Comment by sword865** [comment]
I try again and found now this happen when I working on a file which is not saved to the disk.
But if the file is saved on the disk, it works alright.

**Comment by DonJayamanne** [comment]
If that's the case please could you try setting the language from the drop down to ```python``` from the drop down on the bottom right of the status bar

**Comment by sword865** [comment]
I did set it, and I see the syntax highlighting works well.

**Comment by DonJayamanne** [comment]
@sword865 are you still experiencing this issue?
