### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by affanshahid** [DonJayamanne/pythonVSCode#79]
I find that the linter and auto-formatter are incredibly slow on my installation. I tend to get a 2-3 second delay from me pressing the auto-format hotkey to the code getting formatted, also the linter takes around 5 seconds to pick up errors/mistakes.

Is this normal? or just something wrong on my end? Would really appreciate some feedback on this, I realize the delays are not 'too-long' but I personally find them difficult to work with especially compared to the speeds I get while writing js etc.

using 'yapf' and 'flake8' as the formatter and linter respectively. Python 3.5

**Comment by mufaddal1165** [comment]
Same here!

**Comment by DonJayamanne** [comment]
Hi, auto  formatting is generally slow based on the file size. As for the linting, there could be a delay due to pending linting requests.

**Comment by affanshahid** [comment]
I've tested on files with 5 lines, it still takes 3 seconds. Any other ideas on what could be the reason? I have auto-save enabled if that could be an issue

**Comment by DonJayamanne** [comment]
Please could you try touring off auto save. Let's give that a go?

**Comment by affanshahid** [comment]
No change, switched off auto-save and configured it to only lint on save. Still takes a while after I manually save the file for the linter errors to show up. No effect on the format delay either.

**Comment by affanshahid** [comment]
Figured it out, it was my anti-virus (Avast) being a nuisance.
