### ISSUE TITLE
Code overriding

### ISSUE THREAD

**Issue by grafa** [DonJayamanne/pythonVSCode#792]
https://github.com/Microsoft/vscode/issues/21343

**Comment by DonJayamanne** [comment]
Closing as there haven't been any upvotes on this

**Comment by jsmedmar** [comment]
This will complement _"Class Based"_ development a lot. Many frameworks such as Django/Django-Rest Framework enable users to override methods to add extra functionality. I think it would be amazing if you could jump to the original definition! btw, thanks for an amazing project.

**Comment by grafa** [comment]
@DonJayamanne Maybe it would be better to weight features/functionality be it's reals usage (wide/narrow) instead of "likes" on Github.

I'm not statistican but I would say that like 5 people out of 100 using VScode visit VSCode (or it's near plugins) github issues and actually leave a comment. But I would say much more people write OOP code which this feature aims for.

Anyway thank you for your time and effort. Peace :peace_symbol:
