### ISSUE TITLE
add option to hide external terminal commands from bash history

### ISSUE THREAD

**Issue by rob3c** [DonJayamanne/pythonVSCode#794]
## Environment data
VS Code version:  1.11.0-insider
Python Extension version: 0.5.9  
Python Version:   2.7.12
OS and version:    macOS Sierra 10.12.3

Hi, thanks for a great plugin! I'm really enjoying the vscode python dev experience now :-)

I've started debugging using the external terminal so I can shrink the debug console and give myself more vertical space in vscode. Until they really support multiple monitors, I'm putting the external console on a separate monitor, and it's working well.

However, after a vscode session, my terminal history is saturated with hundreds of the plugin's python CLI invocations. Since I have the `$HISTCONTROL` environment variable set, I think it should be as easy as adding an option to prepend a space to the command string to hide plugin commands from cluttering the terminal history (at least for bash).

Thanks in advance!

**Comment by DonJayamanne** [comment]
Closing as there haven't been any other requests for this feature.
Also, I believe you can hide these by making the necessary changes to your ```HISTIGNORE``` env variable.
https://unix.stackexchange.com/questions/32460/excluding-some-of-the-commands-from-being-getting-stored-in-bash-history
