### ISSUE TITLE
Debugger: don't auto-collapse the `arguments` section.

### ISSUE THREAD

**Issue by yay** [DonJayamanne/pythonVSCode#796]
## Environment data
VS Code version: 1.10.1
Python Extension version:  
Python Version:  3.6
OS and version:  10.12.3

Consider debugging the following recursive function:

<img width="928" alt="screen shot 2017-03-06 at 11 09 46" src="https://cloud.githubusercontent.com/assets/1799756/23605562/83174316-025d-11e7-9b9e-6b07d2f34717.png">

## Actual behavior

The `arguments` section is collapsed on each recursive call.

<img width="261" alt="screen shot 2017-03-06 at 11 09 12" src="https://cloud.githubusercontent.com/assets/1799756/23605625/bc40c090-025d-11e7-82e3-b4cf0f449170.png">

## Expected  behavior

The `arguments` section keeps its expanded or collapsed state.

<img width="261" alt="screen shot 2017-03-06 at 11 09 22" src="https://cloud.githubusercontent.com/assets/1799756/23605630/c2c11500-025d-11e7-83cc-b7b5988b0eaf.png">

This happens on any function call, recursion is just a good example, where the signature stays the same and you definitely don't want to hide the argument on every call.

**Comment by DonJayamanne** [comment]
That's the behaviour of VS Code. Please report it on the VS Code github repo.

**Comment by yay** [comment]
Hi Don,

Should've thought that this may be the case... Will do!

**Comment by yay** [comment]
Good to see it has been reported already: https://github.com/Microsoft/vscode/issues/16031
