### ISSUE TITLE
Autoformat seems to not work

### ISSUE THREAD

**Issue by noilly** [DonJayamanne/pythonVSCode#8]
Autopep8 is installed. However, when I select 'Format Code' from the context menu, i get the error:

`TypeError: Cannot read property 'formatDocument' of undefined`

Is there any configuration or setup I need to do other than install autopep8?

**Comment by DonJayamanne** [comment]
Hi, apologies for the bug. It has been fixed in the latest release. Please test and let me know how it goes. Thanks.

**Comment by noilly** [comment]
Looking good! Thanks :)
