### ISSUE TITLE
Unexpected end of input. Stopping the debug adapter.

### ISSUE THREAD

**Issue by up2dream** [DonJayamanne/pythonVSCode#80]
Can not run with the error: Unexpected end of input. Stopping the debug adapter.
my env: win10/vscode 1.0/python 2.7 and python 3 is also pop same error.

**Comment by HalloUniversum** [comment]
Hi
I had the same problem !
This solved the problem....

1. python.exe in ASCII char directory
2. file in ASCII char directory
3. do not use special chars in filename or path (german umlaut ä/ö/ü etc..)
4. expose python executable to system PATH:
5. leave the extension's "python.pythonPath" unchanged, i.e. "python" (maybe not nessesary..)

Hope this helps someone else .. :-)

My env : win7 / vscode 1.0 / python 3.4 and phytonVSCode 0.3.4

**Comment by DonJayamanne** [comment]
Unicode characters in file paths won't work in Python2.7 .
However it does work in Python 3.5.
