### ISSUE TITLE
Remote debugging and kill

### ISSUE THREAD

**Issue by opensw** [DonJayamanne/pythonVSCode#800]
Hello there,
   is there a way to kill automatically the remote application when the remote debugging session has closed (due exit command from Visual Studio Code or error during execution of the script or when the user types Ctrl+C on remote application)?

At the moment, under Linux, I need to open a new shell and use the kill command each time I would like to start a new remote debugging session.

Thank you

**Comment by DonJayamanne** [comment]
I don't think this is possible. It doesn't sound like a good idea either.  
One shouldn't be able to kill remote applications being debugged, attaching to remote applications for the purposes of debugging is one thing, but then leveraging that to kill the process is completely different.

**Comment by opensw** [comment]
In Visual Studio 2017, to debug C++ remote Linux application it is necessary to attach the debugger to gdbserver; when you click on stop debugging button (Shift F5) from Visual Studio, the remote application is killed too... this is pretty useful (of course you can also detach debugger from remote application without killing it). 

Without this feature I need via ssh to kill manually the remote application (when you do this for just few times it is OK but when you do this for many and many times you go crazy). Anyway, I will try to see if Python Tools for Visual Studio 2017 has same behavior like Visual Studio 2017 for Linux C++.
