### ISSUE TITLE
Refactoring Issue: Variable Mix up

### ISSUE THREAD

**Issue by ajmathews** [DonJayamanne/pythonVSCode#802]
## Environment data
VS Code version:  1.10.1
Python Extension version: 0.5.9 
Python Version:   3.6.0
OS and version:    Window 10  10.0.14393 Build 14393

## Actual behavior
When I try to rename the variable 'diffList' to 'diff_list', it replaces the 'pl' module instead of the variable itself.
Before refactoring - 
```
import matplotlib.pyplot as pl
import numpy as np

def plot_me(x, y, diffList):
    pl.plot(np.array(x), np.array(y))
    pl.plot(np.array(x), np.array(diffList))
    pl.legend(['X vs. Y Plot', '(Y-X) Diff Plot'])
    pl.grid(True)
    pl.show()
```
After refactoring -
```
import matplotlib.pyplot as pl
import numpy as np

def plot_me(x, y, diffList):
    diff_list.plot(np.array(x), np.array(y))
    diff_list.plot(np.array(x), np.array(diffList))
    diff_list.legend(['X vs. Y Plot', '(Y-X) Diff Plot'])
    diff_list.grid(True)
    diff_list.show()
```

## Expected  behavior
Expected output - 
```
import matplotlib.pyplot as pl
import numpy as np

def plot_me(x, y, diff_list):
    pl.plot(np.array(x), np.array(y))
    pl.plot(np.array(x), np.array(diff_list))
    pl.legend(['X vs. Y Plot', '(Y-X) Diff Plot'])
    pl.grid(True)
    pl.show()

```

## Steps to reproduce:  
-  Type the code into the editor
-  Right click the word 'diffList'
-  Rename Symbol
-  Type in 'diff_list'

## Settings  

Your settings.json:   
```
{
}
```

**Comment by gandhis1** [comment]
Related to #579, guess this is still an issue

**Comment by ajmathews** [comment]
That was my mistake on copying it here. I edited the original post. I am still facing the same problem though.

**Comment by gandhis1** [comment]
I have almost the exact same environment specs and am unable to replicate. Previous versions of this issue were related to the line endings of the file if I recall correctly. Can you play around with that and try again?

**Comment by ajmathews** [comment]
For it need to work, I need to switch from CRLF to LF. Is there a solution to this?

**Comment by DonJayamanne** [comment]
What os are you using

**Comment by ajmathews** [comment]
Tried on Microsoft Windows 10 Pro 10.0.14393 Build 14393 and Microsoft Windows 7 Enterprise - 6.1.7601 Service Pack 1 Build 7601

**Comment by ajmathews** [comment]
I tried debugging through the code and I basically don't get any 'changes' back when I run with CRLF. Other times, the word before the variable gets changed (including its other occurrences).
