### ISSUE TITLE
remote debug hangs when remote is python3

### ISSUE THREAD

**Issue by bradanlane** [DonJayamanne/pythonVSCode#805]
## Environment data
VS Code version:  1.10.2
Python Extension version:  tested 0.5.9 and 0.6.0
Python Version:   local: windows 3.5.3 remote: raspbian 3.4.2
OS and version:    local windows 10, remote raspbian jessie (debian 8)

## Actual behavior
start remote program (python3 tutorial01.py) and then start local debugger and then it just waits

## Expected  behavior
if I start the remote program with python 2.7.9 (python tutorial01.py) remote debugging works and my local display stops at the first breakpoint

## Steps to reproduce:  
-  (installed ptvsd for both python and python3)
-  start program on remote using python3 tutorial01.py
-  remote program waits
-  start debugger on local and the control bar appears and then it just waits
-  stop remote program and local debugger
-  start program on the remote using python tutorial01.py
-  start debugger on local and control bar appears with all options enabled
-  first breakpoint is highlighted

## Settings  
Your launch.json (if dealing with debugger issues):  
```
{
            "name": "Attach (Remote Debug)",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "/home/pi",
            "port": 3000,
            "secret": "nosecret",
            "host": "192.168.6.47"
}
```   
Your settings.json:   
(I tried with and without the following line)
```
"python.pythonPath": "c:/tools/python3/python3.exe"
```   
## Logs
Output from ```Python``` output panel  
```
no output generated  when trying to use python3 on remote
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
no output generated when trying to use python3 on remote
```

##Test program
```
import ptvsd
#ptvsd.enable_attach("nosecret")
ptvsd.enable_attach("nosecret", address=('0.0.0.0', 3000))
ptvsd.wait_for_attach()
#ptvsd.break_into_debugger()

print ('starting ...')
person = input('Enter your name: ')
print('Hello', person)
print(' ... finished')
```

**Comment by rallen** [comment]
I have a similar issue with python 2.7.10 where the remote debugger hangs running some of my project. While trying to debug this I found a small reproducible example of when this happens.

### launch.json
```
      {
            "name": "Attach (Remote Debug)",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "${workspaceRoot}",
            "port": 3000,
            "secret": "my_secret",
            "host": "localhost"
        }
```

### debug.py
```
import ptvsd
ptvsd.enable_attach("my_secret", address=('0.0.0.0', 3000))

# Enable the below line of code only if you want the application to wait untill the debugger has attached to it
ptvsd.wait_for_attach()
ptvsd.break_into_debugger()
```

### Working example:
* Run the following in the python prompt
```
# python
Python 2.7.10 (default, Jul 30 2016, 19:40:32)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import debug.py
```
- Attach using the remote debugger in vscode
- All works as expected 

### Example where the debugger hangs - steps to reproduce:
- Run the same but this time using ipython
```
ipython
Python 2.7.10 (default, Jul 30 2016, 19:40:32)
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import debug
```
- Attach using the remote debugger in vscode
- Debugger hangs indefinitely

**Comment by bradanlane** [comment]
*Additional details:*

When using python3 on the remote machine, if I enable with `ptvsd.enable_attach("my_secret", address=('0.0.0.0', 3000))` then it hangs. If I enable with `ptvsd.enable_attach("my_secret")` then I get `Error = {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"192.168.6.47","port":3000}` where the IP address is the correct address of my remote machine.

**Comment by bradanlane** [comment]
**More Additional details:**

I installed Microsoft Visual Studio 2017 Preview (_MSVC_). The preview has with support for the Python Workload. I started my remote program using `python3 tutorial01.py` and then started MSVS and attached the remote debugging using `nosecret@192.168.6.47:3000` and everything worked.

**Comment by DonJayamanne** [comment]
@bradanlane rallen

> Example where the debugger hangs - steps to reproduce:
> Run the same but this time using ipython

Debugging ipython is not supported

**Comment by DonJayamanne** [comment]
@bradanlane 
I am unable to replicate this issue. If you are using CPython, then please note VS Code doesn't support CPython (not officially). I have not tested it at all.

Please could you try running the program locally using Python 3 and attaching to it locally.

**Comment by bradanlane** [comment]
The `cpython` identification may be a red herring. My remote machine is Debian Jessie.

I have run the program locally on my Windows 10 machine using Python3 and it executes and debug was normal. 

I'll report back after I attempt the test with `ipython` On the remote machine.

**Comment by bradanlane** [comment]
@DonJayamanne - If there is a way that I may debug the addon (even if its just adding print statements), I'm happy to go down that route to help determine what my issue is.

**Comment by bradanlane** [comment]
As another test, I installed Ubuntu Xenial (server) on a different hardware platform.

Using local= Win10 an remote=Xenial(new machine) The results were the same as as test #1 and #5 above

**Comment by bradanlane** [comment]
testing with the remote being a Raspberry Pi 3 running the latest Raspbian has the same results:
* breakpoints change to to "unverified" and greyed out when the debugger attaches to the remote process
* there is no visual feedback of which line is active
* the debug console reflects the program output

Could this issue be related to a mistake in my launch.json? Syntax of the `remoteRoot`? Mismatch in the source file ?

**Comment by bradanlane** [comment]
Is there a "known configuration" that works for remote debugging Python3:
* with a Raspberry Pi (or just Debian Jessie) as the remote
* Windows (version?) as the local

If there is a working configurestion, I could test with that starting point.

**Comment by DanielDiBe** [comment]
I am experimenting exactly same problem as @bradanlane  but running VS Code on Ubuntu and being my remote machine a BBB.

The debugger apparently attaches to my remote, the debugging bar appears and I can detach properly, but the other functions like breakpoints or step to next line are disabled. On the remote side the process seems to hang on the line I place a breakpoint in the VS Code, it seems just the feedback to the VS Code is broken somehow. Also, stopping the remote process instantly stops the debugging session on VS Code, so this is partially working.

Performing a test attach debug with 2.7.12 and it's corresponding ptvsd library version works properly. Using Visual Studio 2015 from Windows 10 and the same python 3.4.2 script and library works properly. Thus, I suspect the problem is on the Python Extension for VS Code when working with python3.

# Environment data

VS Code version: 1.11.1
Python Extension version: 0.6.0
Python Version: local: 3.5.2 remote: 3.4.2
OS and version: local ubuntu 16.04 LTS, remote beaglebone black jessie (debian 8.7)
Remote PTVS version: ptvsd 3.0.0 (also tested 2.2.0 same results) <- installed through "pip3 install ptvsd"

**Comment by bradanlane** [comment]
I have reproduced @DanielDiBe results using Ubuntu and Raspberry Pi 3 and with a BBB (Beaglebone Black).

Everything seems to work with VSCode remote debugging Py2.7. Everything seems to work with MS Visual Studio Community remote debugging Py2.7 and Py3.4.

**Comment by bradanlane** [comment]
There are a small (?) handful of open issues related to "debugger not working" including #1011 and #217.

I would like to help debug the issue but to do so, I need help getting a debug environment setup/working. If anyone can assist getting me setup, I will focus on debugging the debugger issue. Thanks.

**Comment by gandhis1** [comment]
It's very easy, just follow:

https://github.com/DonJayamanne/pythonVSCode/wiki/Contribution

**Comment by bradanlane** [comment]
I went through the instructions previously. I started with a clean setup this time and here is what I have thus far:

 - installed nodejs
 - cloned pythonVSCode
 - cd to pythonVSCode
 - npn install
 - received a few warning depricated messages
 - vscode.d.ts successfully installed
 - run build task from command palette. "no build tasks defined. Mark a task with 'isBuildCommand' in tasks.json file."

Not sure what this means, where the file is located, or what I should have done prior to attempting to run the build task.

I assumed there is a missing step to "open pythonVSCode folder as a project".

 - closed active project in VSCode
 - openned pytonVSCode folder
 - run build task from command palette. "no build tasks defined. Mark a task with 'isBuildCommand' in tasks.json file."

ts-loader: Using typescript@2.3.4 and c:\Users\gsalmon\.vscode\pythonVSCode\tsconfig.json
 ...
Compilation complete. Watching for file changes.

 - Launch Extension as debugserver
 - Debugger listening on ws://127.0.0.1:42521/88b928d3-36db-4978-8144-f263baa86126. waiting for debug protocol on port 4711

What is not clear is "the next step". How do I run the extension in teh debugger *and* run my own project for remote debugging at the same time?

**Comment by gandhis1** [comment]
Ok, so you have pretty much every step done. When you open the folder containing the pythonVSCode folder, open launch.json. it will have a Launch Extension entry, that is the one you want. Make sure that entry is the first one in the file (not sure why the Python completion server entry is the first one). Once it is, press F5. A new VS Code window should open up, and you can use this to open any Python source and run it as you normally would. In the original window, you can set breakpoints anywhere which will hit based on your actions in the new window.

**Comment by bradanlane** [comment]
Pressing F5 now opens a new VSCode window and I have my simple test project in it. This is the same test project as used above. Attempting to run the test generates the error "Debug adapter process has terminated unexpectedly".

I am not sure which is the active entrypoint(s) in pythonVSCode when using it for remote debugging. I created several breakpoints in the javascript files and none are triggered.

I don't know if it should or should not but the pythonVSCode extension does not appear in the "installed extensions" list in my project window.

**Comment by DonJayamanne** [comment]
## Please try using ptvsd 3.0.0 (temporary solution)

**Comment by bradanlane** [comment]
Downgraded both the local Win10 machine and the RPi machine to ptvsd 3.0.0 and I am back to the test results from March 11.

Now, I am unable to determine which code files to set breakpoints and start to debug pythonVSCode.

I've set breakpoints on the constructor and methods of LocalDebugServer.js, PythonProcessCallbackHandler.js, RemoteDebugClient.js, and RemoteDebugServer.js (all from the `out/client/debugger/DebugClients` folder)

I can not set breakpoints in any of the pythonVSCode python files.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#92
