### ISSUE TITLE
Replace pep8 with pycodestyle

### ISSUE THREAD

**Issue by ghisvail** [DonJayamanne/pythonVSCode#808]
## Environment data
VS Code version:  1.10.2  
Python Version:  3.4.3
OS and version: Ubuntu 14.04   

## Actual behavior
I configured `pythonVSCode` to point to a venv containing all the tools. It can lint with `pep8` but cannot use `pycodestyle`, although the former is deprecated in favour of the latter.

## Expected  behavior
`pythonVSCode` should be using `pycodestyle` instead of `pep8`.

**Comment by ghisvail** [comment]
FYI, you can mitigate the issue by manually symlinking the `pycodestyle` console script to `pep8` in the venv. Still switching to `pycodestyle` would be better long-term.

**Comment by sambhare** [comment]
An easier workaround is putting "python.linting.pep8Path": "pycodestyle" in your user settings.

**Comment by rajasimon** [comment]
Any current progress for this? @sambhare That does't work in my machine. What else do I need to change?
