### ISSUE TITLE
'cwd' parameter not used in launch.json

### ISSUE THREAD

**Issue by gogoprog** [DonJayamanne/pythonVSCode#809]
## Environment data
VS Code version:  1.10.1
Python Extension version:  0.6.0
Python Version:  2
OS and version: Archlinux

## Actual behavior

The 'cwd' parameter in launch.json is not applied if not in a configuration.

## Expected  behavior

The 'cwd' parameter should be applied even if not in a configuration (as the wiki states)

## Steps to reproduce:  
-  Create a launch.json, fill the 'cwd' parameter
-  Debug a python file

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
{
    "name": "Python",
    "pythonPath":"${config.python.pythonPath}",
    "stopOnEntry": true,
    "console": "none",
    "program": "${file}",
    "cwd": "${workspaceRoot}/src/",
    "debugOptions": [
        "WaitOnAbnormalExit",
        "WaitOnNormalExit",
        "RedirectOutput"
    ],
    "env": {"name":"value"}
}
```   
Your settings.json:   
```json
{
    "python.pythonPath": "/bin/python2"
}
```   

## Note

Everything works fine if I setup a configuration in my launch.json

**Comment by DonJayamanne** [comment]
Will update the wiki. Unfortunately it needs to be applied

**Comment by DonJayamanne** [comment]
Fixed
