### ISSUE TITLE
flask-login引用提示错误

### ISSUE THREAD

**Issue by yxlwfds** [DonJayamanne/pythonVSCode#81]
flask-login引用提示错误
from flask.ext.login import login_user, logout_user, login_required, current_user

like this or user.query of sqlalchemy will still erorre

**Comment by zhouyongtao** [comment]
你的是mac环境吗，flask 这个貌似跟调试指定python版本有关系

**Comment by DonJayamanne** [comment]
Sorry, but please could you (or someone else) translate your issue into English. Thanks

**Comment by yxlwfds** [comment]
@zhouyongtao windows10 环境 python2.7  难道要3.0?

**Comment by DonJayamanne** [comment]
Is this still an issue? Please reopen if it is.
