### ISSUE TITLE
code cannot conitinue

### ISSUE THREAD

**Issue by wukongtea** [DonJayamanne/pythonVSCode#810]
## Environment data
VS Code version:  1.10.1
Python Extension version:  0.6.0
Python Version:   3
OS and version:    win8

## Actual behavior
in vscode, i write in  30000, the code cant conitinue. 
![image](https://cloud.githubusercontent.com/assets/25115961/23789308/4257566c-05b5-11e7-92c7-a5b1f31c7458.png)

## Expected  behavior
in cmd  ,it can work.
![image](https://cloud.githubusercontent.com/assets/25115961/23789317/569f51e2-05b5-11e7-9fb2-151f90e42f90.png)

## Settings  
Your launch.json (if dealing with debugger issues):  

![image](https://cloud.githubusercontent.com/assets/25115961/23789376/9414525c-05b5-11e7-9adb-fa239c7f922f.png)

Your settings.json:   

![image](https://cloud.githubusercontent.com/assets/25115961/23789422/b3dd9b84-05b5-11e7-96fc-0d7a26ba7faa.png)

**Comment by DonJayamanne** [comment]
What exactly is the issue? Please could you try to provide the sample code with step by step instructions and the issue and expected behaviour.

**Comment by DonJayamanne** [comment]
Sorry but please could you translate it into English and provide instructions with the details of the exact issue

**Comment by chanchancl** [comment]
I think what he meant :
In this program you need to input a data, he test in vscode, input the data in debug console, the program can not continue to run down.

like this code can't run to line 3.
![qq 20170314172539](https://cloud.githubusercontent.com/assets/11457297/23893923/493e37c4-08db-11e7-9a07-0e0d668c114f.png)

but in console
![image](https://cloud.githubusercontent.com/assets/11457297/23893997/7fd871a0-08db-11e7-9bd9-ee9ac9cf6d62.png)

**Comment by DonJayamanne** [comment]
You cannot input data into the debug console in VS Code. That's why you need to use the 'Integrated Terminal' or an 'External Terminal' when debugging (hence the various debugging configurations).
