### ISSUE TITLE
Run full script in Jupyter Notebook/IPython Console

### ISSUE THREAD

**Issue by thewaywewalk** [DonJayamanne/pythonVSCode#812]
## Environment data
VS Code version:  1.10.2
Python Extension version:  0.6.0
Python Version:   3.6
OS and version:    Windows 7 Pro

## Actual behavior
 
Currently I can run a piece of selected code and get the output displayed in "Results".
If I want to run a whole script/file, I need to select the whole code, which ist not really convenient.

## Desired behavior

Could you introduce a command/shortcut to run the entire file in the IPython console/Jupyter Notebook?

Thank you!

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/vscodeJupyter#29
