### ISSUE TITLE
Auto docstring feature?

### ISSUE THREAD

**Issue by hellt** [DonJayamanne/pythonVSCode#813]
Hi Don,
Have you considered to implement auto docstring feature (like implemented in PyCharm)? It populates dosctring with params name and some boilerplate for return value/type

**Comment by DonJayamanne** [comment]
Duplicate of #165
Auto generate docstring
Opened by DonJayamanne 9 months ago
enhancement  Misc


This is on my to-do list, unfortunately it is a big list
