### ISSUE TITLE
Debugging the extension: python files

### ISSUE THREAD

**Issue by ajmathews** [DonJayamanne/pythonVSCode#814]
## Environment data
VS Code version: 1.10.1
Python Extension version: 0.5.9
Python Version: 3.6.0
OS and version: Window 10 10.0.14393 Build 14393

## Actual behavior
I am trying to find why renaming variables in my files are not working properly. In order to do that, I am trying to debug the python code 'refactor.py'. I am able to debug through the TypeScript code but it does not break at the python files.  I get 'breakpoint ignore because generated code not found (source map problem)'. I am launching 'Launch Extension'. 
Am I doing something wrong here? 

## Expected  behavior
Ability to debug in the 'refactor.py' file.

## Steps to reproduce:  
-  Get the code from Github
-  Build 
-  Launch debug 'Launch Extension'
-  Try to rename on the new instance of VSCode
-  Try to step into the 'refactor.py' file

## Settings  
Your launch.json (if dealing with debugger issues):  
```
// A launch configuration that compiles the extension and then opens it inside a new window
{
	"version": "0.1.0",
	"configurations": [{
			"name": "Launch Extension",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": [
				"--extensionDevelopmentPath=${workspaceRoot}"
			],
			"stopOnEntry": false,
			"sourceMaps": true,
			"outDir": "${workspaceRoot}/out",
			"preLaunchTask": "npm"
		},
		{
			"name": "Launch Extension as debugServer", // https://code.visualstudio.com/docs/extensions/example-debuggers
			"type": "node",
			"request": "launch",
			"program": "${workspaceRoot}/out/client/debugger/Main.js",
			"stopOnEntry": false,
			"args": [
				"--server=4711"
			],
			"sourceMaps": true,
			"outDir": "${workspaceRoot}/out/client",
			"cwd": "${workspaceRoot}"
		},
		{
			"name": "Launch Tests",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": [
				"${workspaceRoot}/src/test",
				"--extensionDevelopmentPath=${workspaceRoot}",
				"--extensionTestsPath=${workspaceRoot}/out/test"
			],
			"stopOnEntry": false,
			"sourceMaps": true,
			"outDir": "${workspaceRoot}/out/test",
			"preLaunchTask": "npm"
		},
		{
			"name": "Python",
			"type": "python",
			"request": "launch",
			"stopOnEntry": true,
			"pythonPath": "python",
			"program": "${file}",
			"console": "integratedTerminal",
			"args": [],
			"debugOptions": [
				"WaitOnAbnormalExit",
				"WaitOnNormalExit",
				"RedirectOutput"
			],
			"cwd": "${workspaceRoot}"
		}
	],
	"compounds": [{
		"name": "Extension + Debugger",
		"configurations": [
			"Launch Extension", "Launch Extension as debugServer"
		]
	}]
}
```   
Your settings.json:   
```
{
    "python.pythonPath": "c:/python27/python.exe"
}
```

**Comment by DonJayamanne** [comment]
The extension won't let you debug the python code, you will need to test that separately. 
Something you could try is using ptvsd inside the python code and attaching to it  using vscode (use remote debugging).

**Comment by ajmathews** [comment]
Thanks! That worked fine. 
Reference [link](https://github.com/DonJayamanne/pythonVSCode/wiki/Debugging:-Remote-Debuging)
