### ISSUE TITLE
Workspace symbols appends .vscode to path

### ISSUE THREAD

**Issue by roser137** [DonJayamanne/pythonVSCode#816]
## Environment data
VS Code version:  1.10.2
Python Extension version:  0.6.0
Python Version:   2.7.13
OS and version:    Windows 10 Education / 10.0.14393 Build 14393
ctags: 5.8

## Actual behavior
workbench.action.showAllSymbols (ctrl + t) shows symbols with path starting with ".vscode". 
screenshot: https://aww.moe/iqo7c9.png
## Expected  behavior
symbol paths without .vscode
## Steps to reproduce:  
-  download ctags58. add it to system path.
-  use ctrl + t shortcut

## Settings  
no extra settings

## Output
----------Generating Tags----------
ctags --options=C:\Users\rrr\.vscode\extensions\donjayamanne.python-0.6.0\resources\ctagOptions --languages=Python --exclude=**/site-packages/** -o d:\code\python\steam-clientserver/.vscode/tags .

**Comment by jimcroft** [comment]
Just hit this issue too. A workaround exists though. If you set the following in your settings.json:
`"python.workspaceSymbols.tagFilePath": "${workspaceRoot}/tags"`

the tags file is generated in the root of the workspace (which you'll need to git ignore) but ctrl+t symbol links work and open in the editor as expected.
