### ISSUE TITLE
Wrong PEP8 arguments cause linting to silently fail

### ISSUE THREAD

**Issue by matyasforian** [DonJayamanne/pythonVSCode#817]
## Environment data
VS Code version:  1.10.2
Python Extension version: 0.6.0
Python Version:  3.5.2+
OS and version:  Ubuntu 16.10

## Actual behavior
When adding a wrong PEP8 argument VS Code refuses to lint my files even if linting is turned on. No error is shown in the console/notification area/anywhere.

## Expected  behavior
Wrong pep8Args cause an error message/error notification/...

## Steps to reproduce:  
1. Add the following to your settings:
```
    "python.linting.pep8Enabled": true,
    "python.linting.pep8Args": ["--wrong_setting=120"]
```
load a .py file with PEP8 errors. They wont show up.

Note: autoPEP8 might have the same issue.

**Comment by DonJayamanne** [comment]
The output of the linting is displayed in the ```Python``` output panel.
