### ISSUE TITLE
Running the contributed command:'jupyter.execRangeInKernel' failed.

### ISSUE THREAD

**Issue by casbby** [DonJayamanne/pythonVSCode#818]
## Environment data
VS Code version:  1.10.2
Python Extension version:  
Python Version:   2.7
OS and version:    windows 7

## Actual behavior

when  trying to run the jupyter cell with the new Jupyter extension the following error was returned 
Running the contributed command:'jupyter.execRangeInKernel' failed.

No such problem in previous extension

## Steps to reproduce:  
-  
-  
#%%
import numpy as np
a = np.array([1,2,3])
isinstance(a,np.ndarray)

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json

{
    "python.unitTest.pyTestEnabled": false,
    "python.unitTest.unittestEnabled": true,
    "python.unitTest.nosetestsEnabled": false,
    "python.unitTest.unittestArgs": [
        "-v",
        "-s",
        "./statistics/tests/",
        "-p",
        "*test.py"
    ],
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "*.json": true,
        "**/*.pyc": true
    }
}

```   
## Logs
Output from ```Python``` output panel  
```
None 

only the error message on the top of the window
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by guillean** [comment]
Have you tried `pip3 install jupyter` (separate from your ipython install) and restarting VS Code? This was the main reason I was getting this error.
