### ISSUE TITLE
Support setup.py as tasks

### ISSUE THREAD

**Issue by martinpengellyphillips** [DonJayamanne/pythonVSCode#82]
Don't know if this is possible, but would it make sense to support generating tasks automatically based on an existing `setup.py`? So the equivalent of gulp/grunt etc behaviour, but for Python.

**Comment by DonJayamanne** [comment]
Hi, unfortunately that would be something that needs to be supported by the VS Code IDE itself.
You might want to raise this in there. Apologies for the late response.

**Comment by martinpengellyphillips** [comment]
Thanks for the response. Added comment to https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7752336-wider-python-support
