### ISSUE TITLE
Symbol Refactoring is Broken

### ISSUE THREAD

**Issue by sgtoj** [DonJayamanne/pythonVSCode#824]
## Environment data
VS Code version:  1.10.2 (and latest Insiders)
Python Extension version:  0.6.0
Python Version:   3.6.0
OS and version:  Windows 10

## Actual behavior

Symbol renaming will fail or rename symbol before the intended to be edited. This issue *only* occurs if **End of Line Sequence** is set to `CRLF`.

## Expected  behavior

Rename the intended symbol correct with `LF` and `CRLF` line endings.

## Steps to reproduce:  

Try renaming a symbol in the following file...

```python
# -*- coding: utf-8 -*-
"""Bug Workspace"""

class Test():
    """Test Class"""

    def __init__(self):
        self._name = 'FooBar'
        self._modt = 'Hello World!'
        self._isbug = True

    @property
    def name(self) -> str:
        """Name"""
        return self._name

    @property
    def modt(self) -> str:
        """Message of the Day"""
        return self._name

    @property
    def isbug(self) -> bool:
        """Is Bug"""
        return self._isbug

    def do_something(self) -> str:
        """Do Something"""
        return 'Something is not right here.'


def main():
    """Script Entry"""
    test = Test()
    print(test.name)
    print(test.modt)
    print(test.isbug)


if __name__ == '__main__':
    main()
````

## Workspace Settings  

```json
{
    "python.linting.pylintEnabled": true,
    "python.formatting.provider": "yapf"
}
```   

## User Settings

```json
{
    "python.workspaceSymbols.enabled": true,
    "python.workspaceSymbols.ctagsPath": "C:\\ctags\\ctags",
    "python.workspaceSymbols.tagFilePath": "${workspaceRoot}\\.vscode\\tags",
}
```

**Comment by ajmathews** [comment]
Appears to be similar to the problem I had 
#802

**Comment by JGH1000** [comment]
Any fix for this? It has been reported several times #875 #885 #902 #986 #991 #1081 
For me the rename never works so I always have to do it with select/replace.

Thanks for looking into this!

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#94
