### ISSUE TITLE
ImportError: No module named 'model'

### ISSUE THREAD

**Issue by fangaofeng** [DonJayamanne/pythonVSCode#826]
## Environment data
VS Code version:  1.9
Python Extension version:  0.6
Python Version:   3.5
OS and version:    win10

## Actual behavior
when i run user.py directly ,it has a error .

## Expected  behavior
F5 or run python file in terminal
## Steps to reproduce:  
-  
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
"configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": null,
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": null,
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }, 
Your settings.json:   
// 将设置放入此文件中以覆盖默认设置
{
   "python.pythonPath": "E:/pythonvenv/tornadovenv/Scripts/python.exe",
   "python.formatting.provider": "yapf",
   "python.linting.flake8Enabled": true,
   "python.linting.enabled": false
}
## Logs
Output from ```Python``` output panel  
 E:\bornadu\bornaduServer2\model> cd 'e:\bornadu\bornaduServer2'; $env:PYTHONIOENCODING='UTF-8'; E:/pythonvenv/tornadovenv/Scripts/python.exe C:\Users\fanga\.vscode\extensions\donj
ayamanne.python-0.6.0\pythonFiles\PythonTools\visualstudio_py_launcher.py e:\bornadu\bornaduServer2 62723 34806ad9-833a-4524-8cd6-18ca4aa74f14 WaitOnAbnormalExit,WaitOnNormalExit e:\
bornadu\bornaduServer2\model\user.py
>>
Traceback (most recent call last):
  File "e:\bornadu\bornaduServer2\model\user.py", line 16, in <module>
    from model import db
ImportError: No module named 'model' 
Output from ```Console window``` (Help->Developer Tools menu)
  "python.linting.maxNumberOfProblems": 100,

**Comment by fangaofeng** [comment]
In my workspace Thera is model

**Comment by fangaofeng** [comment]
Root ---model
              ----__init__.py
              ----user.py

**Comment by DonJayamanne** [comment]
1. Can you run this code form the same project directory using the same Python interpreter?  
2. Please try the following in a command window:   
Note: Please ensure the current directory is the same project directory used above.   
```
E:/pythonvenv/tornadovenv/Scripts/python.exe e:\bornadu\bornaduServer2\model\user.py
```

**Comment by fangaofeng** [comment]
this is because PYTHONPATH not inclue workspace dir. i set    "env":  {"PYTHONPATH":"${workspaceRoot}"},  it work.
