### ISSUE TITLE
VS Code-Python Newbie Questions (Select Interpreter; VENV; VENV & Debugger; Windows Launcher)

### ISSUE THREAD

**Issue by GGillan** [DonJayamanne/pythonVSCode#827]
## Environment data
VS Code version:  1.10.2
Python Extension version:  0.6.0
Python Version:   Various, latest 3.6
OS and version:    Windows 7 (questions also pertain to 10)

Have just installed VSCode and your great extension for Python on Windows (7 and 10),  want to make sure I am setting off on the right foot. I have gone through the VSCode documentation and your extension's doc on these points (plus more), and feel the need to clarify some things. I did look through "issues", sorry if I missed existing answers. I hope this is the right venue...

My questions center around virtual environments, basically making sure I don't unwittingly mess up between different venv, different Python versions, etc. I have several different Python versions installed.

**Select Interpreter:** I opened a Python file and then looked at the options in the "Python: Select Workspace Interpreter" command. Python 3.6 was not present, even though installed. 2.7, 3.4, and 3.5 were present. FYI, I do not have any Python installation in the system or user path. The difference was that 2.7, 3.4, and 3.5 were installed in "C:\(each their own folder tree name)", while 3.6 was installed in "C:\Users\(username)\AppData\Local\Programs\Python\Python36-32". I uninstalled 3.6 and reinstalled it in "C:\Python36-32" and now 3.6 is present in the "Python: Select Workspace Interpreter" command menu. I guess this one is a report rather than a question.

**Virtual Environments-1:** "Option 1" (as described in your doc) mentions adding the venv path to python.pythonPath in the "launch.json" file. I haven't been able to find mention of a "launch.json" file in the VS Code doc pages. Has that name changed to "settings.json" in the ".vscode" sub-directory of the project/workspace folder? 

A second note on that same section in your doc. The example given is 
"python.pythonPath": "/home/xxx/dev/ala/venv/bin/python" 

From what I see on my system that example should be 
"python.pythonPath": "/home/xxx/dev/ala/venv/Scripts/python"

But I am not sure if 'bin' versus 'Scripts' there is a Linux versus MS Windows detail (I am looking at Windows 7 at the moment).

**Virtual Environments-2:** "Option 2" (as described in your doc: start the venv in a terminal window, then launch VS Code via "code ."). The doc mentions to close all instances of VS Code before launching VS Code in the venv terminal session. 

Is that meant to imply I should only be using one instance of VS Code at a time, or perhaps multiple instances of VS Code are OK but only if they are in the same venv?

**Virtual Environments and Python Debugger:** If I am using VS Code in a venv, will the debugger automatically pick up the Python interpreter from the venv? Or should I "select" the interpreter of the Python version that the venv is using? I am asking explicitly because I want to be sure that any packages loaded are the versions that I think they are, namely, from the venv. Or does the debugger need to load some packages for its own use from the Python version's main install?

**Windows Launcher:** When I first loaded a Python file after reinstalling 3.6 I noticed that VS Code seems not to be aware of the Windows Python Launcher "py". When VS Code went to lint the file it complained that pylint was not installed (which it was not yet in 3.6 after the re-installation described earlier), and I selected the option to install it. VS Code attempted to use "python -m pip install pylint" but failed because I do not have any Python installation in the path, so "python" was not found. Instead I have accepted the default Windows installation of the Launcher, "py" (so "py -3.6 -m install pylint" would have done the trick or just "py -m install pylint" to use the default Python version, also 3.6 at the moment). 

Is there a way I should make VS Code aware of "py" in place of "python" on MS Windows?

Thank you - I hope my questions are clear and not terribly redundant.

**Comment by GGillan** [comment]
I have made some progress in discovery. Regarding this:

> Virtual Environments-1: "Option 1" (as described in your doc) mentions adding the venv path to python.pythonPath in the "launch.json" file. I haven't been able to find mention of a "launch.json" file in the VS Code doc pages. Has that name changed to "settings.json" in the ".vscode" sub-directory of the project/workspace folder?

I found references to launch.json and realize I was not able to find it before because the file had not yet been created. That also solved this part for me:

> Virtual Environments and Python Debugger: If I am using VS Code in a venv, will the debugger automatically pick up the Python interpreter from the venv? Or should I "select" the interpreter of the Python version that the venv is using? I am asking explicitly because I want to be sure that any packages loaded are the versions that I think they are, namely, from the venv. Or does the debugger need to load some packages for its own use from the Python version's main install?

Hopefully the observations I made regarding Windows Python installation location, Windows Launcher ('py' instead of 'python'), and regarding 'bin' versus 'Scripts' will be helpful.

I am still wondering about conflicts if I have multiple instances of VS Code open at the same time, especially if they are referencing different venv's. Will there be subtle problems I should be concerned about?

**Comment by 1st** [comment]
I'm also interested to understand how to use virtual envs in VS Code, because I have few and it will be good to know how to switch between them, or tell VS Code that I need to use python from the given virtual environment, and associated libraries from it.

**Comment by skyjur** [comment]
> I'm also interested to understand how to use virtual envs in VS Code, because I have few and it will be good to know how to switch between them, or tell VS Code that I need to use python from the given virtual environment, and associated libraries from it.

I'm not sure if there is very easy way to switch from one venv to another, but in order to activate one it should be enough to just set:

`"python.pythonPath": "/path/to/virtual/environment/bin/python"`

I usually have just one environment associated to a project, and set this value in workspace-settigings per-project.

Also I usually create virutal environment under my project folder under `venv/`, and I have set `"python.pythonPath": "${workspaceRoot}/venv/bin/python"` as default, so for many projects I don't need custom settings.

**Comment by 1st** [comment]
My wuestion is more about "WHY DO WE NEED TO SET python.venv variable (I don't remember exact name) and python.venvsDir with path to ~/.virtualenv, if we need to setup pytjon.pythonPath manually?". Based on two given variables we can build a path to the executable python in virtual env.

python.venvsDir + python.venvName + "bin/python"
