### ISSUE TITLE
syntax highlight error

### ISSUE THREAD

**Issue by cg-cnu** [DonJayamanne/pythonVSCode#830]
## Environment data
VS Code version:   Version 1.10.2
Python Extension version:  0.6.0
Python Version:   2.7
OS and version:    Centos 7

Coming from here... https://github.com/Microsoft/vscode/issues/22779

![pythonprint](https://cloud.githubusercontent.com/assets/2767425/24033029/e6764432-0b10-11e7-96d1-5d81afcdd061.png)

Python print statement is not showing proper syntax highlighting.

**Comment by sco1** [comment]
What makes it improper?

**Comment by gandhis1** [comment]
This depends on your color scheme. Try Monokai.

**Comment by DonJayamanne** [comment]
Syntax highlighting isn't provided by by VS Code, instead it is provided by VS Code (if i'm not mistaken they use the tmlanguage file provided by Magic Python).

My suggestion is to raise this issue with [Magic Python](https://github.com/MagicStack/MagicPython)
