### ISSUE TITLE
missing the feature of  "click to follow" in debug console

### ISSUE THREAD

**Issue by ericshenjs** [DonJayamanne/pythonVSCode#831]
## Environment data
VS Code version:  
Python Extension version:  
Python Version:   
OS and version:    

## Actual behavior
cannot use  "click to follow" feature
## Expected  behavior
can use  "click to follow" feature  in debug console
## Steps to reproduce:  
-  1,debug nodejs with vscode ,if there are warning or errors ,then click the warning or error ,vscde will open the warning or error file
-  2,debug python with vscode ,if there are warning or errors ,then cannot click the warning or error to open the warning or error file

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": null,
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
Your settings.json:   
```json
```   

![Uploading vsc02.jpg…]()

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by ericshenjs** [comment]
![vsc01](https://cloud.githubusercontent.com/assets/7017653/24036873/8b07b06a-0b36-11e7-9228-8c5a5dbaf790.jpg)

**Comment by ericshenjs** [comment]
![vsc02](https://cloud.githubusercontent.com/assets/7017653/24037147/ad6a8096-0b37-11e7-9b97-9bf27efb55ca.jpg)

**Comment by DonJayamanne** [comment]
This is an upstream issue (feature provided by VS Code).
https://github.com/Microsoft/vscode/issues/15760
