### ISSUE TITLE
how to set PYTHONPATH in env or .envfile of launcher.json

### ISSUE THREAD

**Issue by fangaofeng** [DonJayamanne/pythonVSCode#832]
## Environment data
VS Code version:  1.10
Python Extension version:  0.6
Python Version:   3.5.1
OS and version:    Win10
I want to set workspace root in PYTHONPATH.
How do i do?
Who can give me a example 
## Steps to reproduce:  
-  
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by Sheljohn** [comment]
+1 I just spent 20 minutes browsing the issues and this is a nightmare. There doesn't seem to be any automatic support for the environment variable [`$PYTHONPATH`](https://docs.python.org/2/using/cmdline.html#envvar-PYTHONPATH), and at least in my case, the use setting `"python.autoComplete.extraPaths"` doesn't seem to work (neither for autocompletion, nor for linting, I get a "unable to load" error).

**Comment by DonJayamanne** [comment]
1. Create a file named ```.env``` in your root directory
2. Add the following contents to the ```.env``` file:   
```
PYTHONPATH=some path you want to use
```

**Comment by janhancic** [comment]
This doesn't seem to do anything. I've created the file, set the path to my project, restarted VS Code and I still don't get any intellisense for my python files.

Is there anything else I need to make this work?

**Comment by DonJayamanne** [comment]
That's how you set that value for PYTHONPATH, now the question is what exactly is the problem. 
Please could you provide the sample code for which intellisense isn't working?

**Comment by janhancic** [comment]
My folder structure:

![image](https://cloud.githubusercontent.com/assets/356488/24758401/29ff9bc6-1ada-11e7-963b-264c783f0ba5.png)

func1.py
```
def func1(arg1, arg2)
    pass
```

func2.py
```
def func2()
    return 'func2()'

BOB = 'a'
```

root.py
```
from istest.test2.func2 import BOB # I got completion for BOB
from istest.test2.func2 import func2 # I didn't get completion for this

from istest.test1.func1 import func1 # I get NO completion for this
```

My `.env` in root of project:
```
PYTHONPATH=/home/jan/dev/core/;/home/jan/dev/core/istest
```

I only get (some) intellisense for the stuff in folder `test1` which has a `__init__.py` file, Otherwise I get nothing.

**Comment by fangaofeng** [comment]
"env":  {"PYTHONPATH":"${workspaceRoot}"},

this is work.

**Comment by fangaofeng** [comment]
i set .env file , for example ` PYTHONPATH='e:\bornadu\bornaduserver2'`.
When i execute python , i get error .
i set .env file , for example ` `. content is nothing.
When i execute python , i get a same error .
Print a lot of env:....., git a tip , $env maybe replay by ${}.

**Comment by DonJayamanne** [comment]
@fangaofeng please could you provide the sample code you have used to test.

**Comment by janhancic** [comment]
@DonJayamanne do you have any suggestions for me? This is really limiting the usefulness of this extension and I feel like I'm just missing some setting or something I'm not aware of?

**Comment by DonJayamanne** [comment]
Sorry will look into this today.

**Comment by janhancic** [comment]
To sort of sumarise, if I don't have `__init_` files in my folders I don't get any autocompletion, otherwise I do. No combination of pythonpath settings seems to make any difference.

**Comment by darrenkenny** [comment]
To be honest, the documentation and naming of 'pythonPath' is confusing since it conflicts directly with the environment variable that is actually a colon-separated list of directories to search for modules - PYTHONPATH which would be commonly set to use workspace generated modules prior to installation for tests, etc.

I would suggest (but possibly too late now) to rename pythonPath to pythonExecPath or something else to avoid this ambiguity.

This could  be done as a once-off upgrade if say pythonPath is pointing to an executable file? If so, set pythonExecPath to pythonPath, then unset pythonPath.

**Comment by janhancic** [comment]
Any news :) ?

**Comment by janhancic** [comment]
@DonJayamanne I really just wanna hear if this is something that is ever going to be looked at or not, so I can move on with my life:) Can you please give an update?

**Comment by flamders** [comment]
Got a very similar problem and folder structure ("tests" and "moduledir"). Imports work within "moduledir" and __init_.py exist there. However, I can't import code from "moduledir" from code in the "tests" folder. Tried adding PYTHONPATH to the .env file and the launch.json (https://stackoverflow.com/questions/41471578/visual-studio-code-how-to-add-multiple-paths-to-python-path). Neither take effect after restart. Ubuntu 16.04.

**Comment by flamders** [comment]
Got "tests" and "moduldir" to work after reading issue 686 _and_ adding the full workspace path to the .env file as well: https://github.com/DonJayamanne/pythonVSCode/issues/686

So ${workspaceRoot} is not working for some reason

**Comment by flamders** [comment]
I'm running "python.pythonPath": "python3", as a _user setting_ which might be a factor in relation to launch.json. My launch.json below, if it can be of any use:

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },

**Comment by sformanjawbone** [comment]
I haven't tried it yet but I think the answer here speaks to the issue: https://stackoverflow.com/questions/41471578/visual-studio-code-how-to-add-multiple-paths-to-python-path

> in your launch.json profile entry, specify a new entry called "env", and set PYTHONPATH yourself.

```
"configurations": [
    {
        "name": "Python",
        "type": "python",
        "request": "launch",
        "stopOnEntry": false,
        "pythonPath": "${config.python.pythonPath}",
        "program": "${file}",
        "cwd": "${workspaceRoot}",
        "debugOptions": [
            "WaitOnAbnormalExit",
            "WaitOnNormalExit",
            "RedirectOutput"
        ],
        "env": {
            "PYTHONPATH": "/path/a;path/b"
        }
    }
]
```

**Comment by ahundt** [comment]
Here is an **ultra hacky workaround** until the problem is actually solved... 

1. Add this to the top of your first python file: 
```python
import sys; sys.path.append('/path/to/my/pylib')
```
2. Don't forget to remove it before you commit!

@sformanjawbone in my case what you suggest from the [stackoverflow post](https://stackoverflow.com/questions/41471578/visual-studio-code-how-to-add-multiple-paths-to-python-path) didn't work. I'm on macos with python 2.7, vscode 1.13.0, and donjayamanne.python 0.6.4. I tried both the `.env` file and the env json variable.

**Comment by martinfiers** [comment]
I agree with @darrenkenny. I think it's better to have a solid base to work from. Being able to set the PYTHONPATH as an integral part of the plugin, and removing the ambiguity with the python.pythonPath config value that is provided by the plugin, could greatly help. Not sure if backward compatibility is a great problem now, the plugin has not yet reached version 1.0, right? (but should be assessed).

**Comment by janhancic** [comment]
@ahundt that doesn't do anything for me :(

Is there really no info on this?

**Comment by DonJayamanne** [comment]
@janhancic 
https://github.com/DonJayamanne/pythonVSCode/issues/832#issuecomment-292184959
- Looking at the code, your code is invalid, you need to have the semi colon for your functions.  
- Please ensure you have __init__.py files under each directory.

**Comment by janhancic** [comment]
That's exactly the issue, our project doesn't have or need them. And unfortunately I was unsuccessful with persuading the team to add them. So not sure if there's any other workaround?

But yes, if I add them, then things work. Maybe I can add them and locally .gitignore them if nothing else.

**Comment by DonJayamanne** [comment]
@martinfiers, @ahundt

The following approach will now provide intellisense base on the path defined in PYTHONPATH in the .env file.

***How to create a .env file?*** 
Create a file named .env in your root directory
Add the following contents to the .env file:
PYTHONPATH=some path you want to use (relative paths are also supported)

**Comment by DonJayamanne** [comment]
apologies for the delay in fixing this issue.

**Comment by mlewis22** [comment]
I must be doing something wrong here.

i want to import my package to the python path. I don't want to keep importing it into a virtualenv whilst i'm working on it. 

My folder structure is here
Project:
- package
- tests
.env

i've added PYTHONPATH= "/package" to my .env

When i run the code in tests i get "No module named <package>" error. 

what am i missing?

**Comment by ZhijiaCHEN** [comment]
@DonJayamanne 
I can't add more than one path. Have tried to add env entry to launch.json and create .env file but neither works. But if I add only one path, my module could be imported by either way. I add the env entry as 
```
 "env": { "/path1/package1;/path2/package2"},
```
and create my .env file as
PYTHONPATH="/path1/package1;/path2/package2"
Is there anything wrong with my format? Thanks!

**Comment by DonJayamanne** [comment]
@ZhijiaCHEN , haven't been able to replicate your issue, however I've identified a type and hopefully that will fix it.

**Comment by ZhijiaCHEN** [comment]
@DonJayamanne I just figured out that the path separator  should be a colon other than a semicolon since i am using mac os...

**Comment by thatguy7** [comment]
So I am not sure what I am doing wrong here. I have the following structure.
```
-dir
-- library
--- __init__.py
--- ...
-- workdir
--- .env
--- mycode.py
```

The .env file contains `PYTHONPATH=..`.

I get no code completion, and when I execute mycode.py by using 'Run Python File in Terminal' the execution fails at `import library`. But, on the other hand pylint does not complain about the import and when I use the debugger it runs as it should and does not fail.

**Comment by loopinf** [comment]
same issue for me.
while module import works well in debug mode, env is not loaded in terminal mode

**Comment by fabionogueira** [comment]
for me it worked like this:

```
    "pythonPath": "${workspaceRoot}/env",
    ...
    "env": {
         "PYTHONPATH":"${workspaceRoot}/env"
    },
```

**Comment by stabenau** [comment]
Neither .env file nor env:{} entries in launcher.json seem to affect the environment (PYTHONPATH) in the terminal that runs python. 

Using Version 1.20.1 on Mac OSX

**Comment by DonJayamanne** [comment]
@stabenau 

Please report all issues on the Microsoft repo.
> .env file nor env:{} entries in launch.json seem to affect the environment (PYTHONPATH) in the terminal that runs python.

Note:`launch.json` is used by VS Code only when debugging. Also, the issue you're referring to ie being tracked here https://github.com/Microsoft/vscode-python/issues/944

**Comment by lingz** [comment]
Still does not work, in the ended up symlinking my python folder into virtualenv

```
cd env/lib/python3.6/site-packages
ln -s ~/Code/myapp/python ./
```

Now autocomplete and python tools all seem to work

**Comment by gennaro-tedesco** [comment]
I have been having the exact same problem and none of the proposed solutions seem to work: creating a `.env` file does not affect anything. As a brute force method I have seen that `export PYTHONPATH=<mypath>` in the terminal before execution _does_ work but clearly this is not how it should be done.

**Comment by flamders** [comment]
Reg. previous answers when i got this to work (this setting is still unstable). Ubuntu specific.

1) During some update common symlinks such as python3 stopped working (not sure which since i worked with other languages for a while). I.e., all python paths need to be absolute: /usr/bin/python3 NOT python3 (or e.g., /usr/bin/autopep8). 

2) I don't modify the PYTHONPATH anywhere except in .env file. My .env file, in root folder of project, looks like this, replace [Absolute path]:

PYTHONPATH=[Absolute path]/ReferenceProjectPython:[Absolute path]/ReferenceProjectPython/tests:[Absolute path]/ReferenceProjectPython/sampleservice 

sampleservice == src folder

**Comment by lingz** [comment]
So in the end, the only way that reliably worked to get VSCode to resolve imports without issues was to add a `mypath.pth` file inside the `site-packages` of our virtualenv. 

We just do:

```
echo "$(pwd)/python" > env/lib/python3.6/site-packages/mypath.pth
```

Note this is an absolute path, and that `${workspaceRoot}/python` is our `PYTHONPATH` root.

**Comment by thebalaa** [comment]
Thanks @lingz, your suggestion was the best solution for my use case. Cheers!

**Comment by gennaro-tedesco** [comment]
> Neither .env file nor env:{} entries in launch.json seem to affect the environment (PYTHONPATH) in the terminal that runs python.
> 
> Using Version 1.20.1 on Mac OSX

I confirm that the above settings do not really affect anything.

**Comment by keyblade95** [comment]
> Neither .env file nor env:{} entries in launch.json seem to affect the environment (PYTHONPATH) in the terminal that runs python.

Same here. Is there any solution beside adding manually the `.pth` file in the `site-packages` folder?
