### ISSUE TITLE
Debugging speed

### ISSUE THREAD

**Issue by alphazed35** [DonJayamanne/pythonVSCode#835]
## Environment data
VS Code version:  1.10.2
Python Extension version:  0.6.0
Python Version:   3.5
OS and version:    ubuntu 16.04

Don, I've got a working vscode with python extension setup.  I've just launched in the debugger a tkinter based graphing application.  Everything is working fine, but I'm noticing that the application is running noticibly slower in the debugger than in my previous setup using eclipse/pydev.  Without knowing a lot, I know there are some tricks using cython that pydev employs - are there any settings I can tweak to get a little speed up in vscode using your extension?   

In addition to your extension I've got Magic Python, Python Extended and Python for VSCode installed. 

I am not exactly sure why I have all that installed just yet, I'm following random instructions spread across the net, most of them at least half a year old.    

I you have some suggestions for a fast setup I would surely entertain them.

And... a big thanks for you code.  Its a nice piece of work.

**Comment by peheje** [comment]
Here is a small video showing the slow debugging on my end:
https://youtu.be/l3QBmdB4hgs

**Comment by xoviat** [comment]
Honestly why not reuse the pydev debugger? That is what pycharm does.

**Comment by DonJayamanne** [comment]
@xoviat
>Honestly why not reuse the pydev debugger? That is what pycharm does.

I am fixing these issues alone. You are more than welcome to submit a PR to use the pydev debugging we.

**Comment by xoviat** [comment]
Sources are located here: https://github.com/fabioz/PyDev.Debugger

> I am fixing these issues alone. You are more than welcome to submit a PR to use the pydev debugger.

Story of my life. Too much to do and not enough time. I may help on this if I find some.

**Comment by DonJayamanne** [comment]
Since you have found the source, why don't you do this? 

The code is already there, you managed to find the source, so do the right thing and contribute to this open source project. 

So don't be smart Alec, just contribute, rather than making your own excuses.

**Comment by xoviat** [comment]
> So don't be smart Alec, just contribute, rather than making your own excuses.

Sorry if this came off wrong. I like to use the issue as a scratchpad to gather relevant information.

@DonJayamanne 
Do you have sample data from the tpc connection established by the debugger?

**Comment by DonJayamanne** [comment]
Unfortunately I don't any sample data.

**Comment by xoviat** [comment]
@DonJayamanne 

I received this error while debugging: 

```
'C:\Program Files (x86)\Microsoft VS Code\Code.exe' --debugPluginHost=43880 --extensionDevelopmentPath=c:\Users\User\workspace\pythonVSCode 

Activating extension `donjayamanne.python` failed: Cannot find module 'c:\Users\User\workspace\pythonVSCode\out\client\extension'.
Activating extension `donjayamanne.python` failed:  Cannot find module 'c:\Users\User\workspace\pythonVSCode\out\client\extension'
Here is the error stack:  Error: Cannot find module 'c:\Users\User\workspace\pythonVSCode\out\client\extension'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.U.J.i._load (c:\Program Files (x86)\Microsoft VS \resources\app\out\vs\workbench\node\extensionHostProcess.js:4:374834)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Function.s [as __$__nodeRequire] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\loader.js:4:25882)
    at d (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:375989)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:380927
    at Object.m [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:47824)
    at Object.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:51398)
```

Given your experience with vscode extensions, do you have an explanation for this error?

**Comment by DonJayamanne** [comment]
Closing in favor of https://github.com/DonJayamanne/pythonVSCode/issues/897
