### ISSUE TITLE
python.pythonPath homedir behaviour inconsistency

### ISSUE THREAD

**Issue by nedlowe** [DonJayamanne/pythonVSCode#839]
## Environment data
VS Code version:  1.10.2
Python Extension version:  0.6.0
Python Version:   3.5.1
OS and version:    macOS Sierra 10.12.3

When I set python.pythonPath to ~/.virtualenvs/myvenv/bin/python I get an error (Failed to launch the Python Process, please validate the path '~/.virtualenvs/amaas3/bin/python').

When I set python.pythonPath to /Users/ned/.virtualenvs/myvenv/bin/python it works.

When not working, if I go to Select Workspace Interpreter, it lists my "current" interpreter as "./~/.virtualenvs/myvenv/bin/python" which is obviously wrong (and I guess the reason for this bug).

**Comment by DonJayamanne** [comment]
Relative paths are not supported. You will need to set the fully qualified path in the settings.json.  
However you can use some known variables, such as ${workspaceRoot}.

For instance if ```.virtualenvs``` is in your project (workspaceroot) directory, then you can configure settings as follows:  
```json
"python.pythonPath": "${workspaceRoot}/.virtualenvs/amaas3/bin/python"
```
