### ISSUE TITLE
Fall back to pylint3 instead of pylint

### ISSUE THREAD

**Issue by jhasse** [DonJayamanne/pythonVSCode#843]
## Environment data
VS Code version:  1.10.2
Python Extension version:  0.6.0
Python Version:   3.5.2
OS and version:    Ubuntu 16.04

## Actual behavior
Having `pylint3` installed will still result in "Linter pylint is not installed".

## Expected  behavior
Should also look for the `pylint3` executable.

## Steps to reproduce:  
-  Install pylint3 using `sudo apt install pylint3`
-  Make sure `pylint` isn't availabe but `pylint3` is.

**Comment by DonJayamanne** [comment]
For now, please change the name of the pylint executable to ```pylint3``` in your settings file as follows:   
```json
"python.linting.pylintPath": "pylint3"
```

**Comment by julian-alarcon** [comment]
Where do I set this option? In my User Settings? (/home/julian/.config/Code/User/settings.json)
I guess that there should be an option, just add a new entry for pylint3.

**Comment by DonJayamanne** [comment]
All issues will be maintained in the Microsoft repo, also you might want to check the documentation https://code.visualstudio.com/docs/python/linting
