### ISSUE TITLE
wrong docstring output encoding

### ISSUE THREAD

**Issue by IgorNovozhilov** [DonJayamanne/pythonVSCode#844]
## Environment data
VS Code version:  1.11.0-insider
Python Extension version:  0.6.0
Python Version: 3.3.5
OS and version: win7-pro

## Actual behavior
![2017-03-23_23h32_44](https://cloud.githubusercontent.com/assets/3082812/24269279/bbac59c4-1021-11e7-8d45-e1e3331f13a0.png)

## Expected  behavior
![2017-03-23_23h38_48](https://cloud.githubusercontent.com/assets/3082812/24269339/ed3a1aa8-1021-11e7-81db-e24d318b7402.png)

## Steps to reproduce:  
-  write "ru" docstring 
-  hovered methods

It's a heisenbug... The text with the wrong encoding appears not on every hover. He occasionally appears when auto-save file, even when editing parcels not related to the method or docstring.

A similar problem: https://github.com/DonJayamanne/pythonVSCode/issues/372

## Settings  

Your settings.json:  no

## Logs
no

Output from ```Console window``` (Help->Developer Tools menu)
no

**Comment by IgorNovozhilov** [comment]
I found :bug:  Wrong encoding appears only once executed linting file and highlight warnings.

**Comment by DonJayamanne** [comment]
Please could you provide some sample code and exact steps to replicate this issue.   
I'm having trouble replicating this at my end. Thanks for your help.

**Comment by IgorNovozhilov** [comment]
Occurs only on `windows` with `RU-ru` localization, and utf-8 py-file encoding.
```py
""" Модуль """

def test():
    """ Описание функции """
    pass

test()
```

**Comment by mdschweda** [comment]
Same for any Umlaut (aöü)

```python
# -*- coding: utf-8 -*-
"""Dieses Modul enthält.... <---"""

class Client(AuthenticatedClient):

    async def schema(self, entity_type: str, single: bool = False) -> object:
        """Fragt das Schema eines Typens von Eintrag ab.

        Parameters
        ----------
        entity_type : str
            Der Entitätstyp.... <---
        single : bool, optional
            Ein Wert, der bestimmt, ob das Schema alle referenzierten Entitätstypen.... <---
        """
        ....
```

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#96

**Comment by EfficientPython** [comment]
Same here with French accents éèà and German Umlaute äöü. There must be something with the encoding. The python help function that reads the docstrings doesn't support UTF-8 maybe and/or doesn't read/care about the encoding type of the function ?? I precised the encoding I wanted at the beginning of a function but no results
`# -*-coding:Utf-8 -* `
