### ISSUE TITLE
Lens display not appearing above new test functions

### ISSUE THREAD

**Issue by alexdawn** [DonJayamanne/pythonVSCode#845]
## Environment data
VS Code version:  1.10.2
Python Extension version:  0.6.0
pytest: 3.0.5
Python Version:   3.5.3
OS and version: Win7 Pro SP1

## Actual behavior
 write a new function testing function, no lens display appears, saving file does not help. For lens to display requires to run https://donjayamanne.github.io/pythonVSCodeDocs/docs/unittests_more-options/ method 1 first

existing functions in the git clone show lens, as does writing a new function with the same name as existing functions.

similar issue to: https://github.com/DonJayamanne/pythonVSCode/issues/307
## Expected  behavior
lens display appears as function is written
## Steps to reproduce:  
-  
-  

## Settings  
Your settings.json:   
```
{
    "terminal.integrated.shell.windows": "C:/Program Files/git/bin/bash.exe",
    "editor.renderWhitespace": "all",
    "python.linting.pylintEnabled": false,
    "python.linting.flake8Enabled": true,
    "files.autoSave": "off",
    "python.formatting.provider": "autopep8",
    "editor.formatOnSave": false,
    "python.unitTest.pyTestEnabled": true,
    "python.unitTest.unittestEnabled": false,
    "python.unitTest.nosetestsEnabled": false
} 
```

**Comment by alexwhittemore** [comment]
I can confirm this. I've been restarting VSCode, but worse, "discover tests" often just spins forever.

**Comment by xqliu** [comment]
I can confirm this too,  most of the time the test lens does not appear, it seems randomly appears

**Comment by eyadsibai** [comment]
I can confirm too . They appear on some test files but not others ... not random for me

**Comment by DonJayamanne** [comment]
@xqliu @eyadsibai @alexwhittemore @alexdawn 
Please could you provide sample files you have used, so I can replicate this issue at my end.

**Comment by alexwhittemore** [comment]
I'll try to work up a repeatable test case this morning. I've been having variable success lately - in the main project I spend most of my time on, things mostly seem to work. When I add a new test class, things break down, but then get stable later. I'll put some effort into repeatability.

**Comment by alexwhittemore** [comment]
I've just tried to set up a fresh project to try to reproduce, but I had to update to the latest version (0.6.4), and behavior seems stable as expected right now. Tests get properly discovered at VSCode startup, and when I create new tests, the lenses appear upon file save.

Attached: My environment setup instructions and sample project for someone else to try to make a reproduction test.
[vscode-test.zip](https://github.com/DonJayamanne/pythonVSCode/files/977090/vscode-test.zip)

**Comment by alexwhittemore** [comment]
Hmm - I do notice at least one (possibly related) oddity - in my production project (which I sadly can't share verbatim, hence trying to make a test case project/env), my tests filter is "tests*.py," since I have a bunch of test_mything.py files totally unrelated to unittest, and one tests.py which actually IS my unittests. Settings as below:

```
// Place your settings in this file to overwrite default and user settings.
{
  // Whether to lint Python files.
  "python.linting.enabled": true,
  
// Configure glob patterns for excluding files and folders.
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/.DS_Store": true,
    "*.pyc": true
},
"python.unitTest.unittestArgs": [
    "-v",
    "-s",
    ".",
    "-p",
    "tests*.py"
],
"python.unitTest.unittestEnabled": true
}
```
When I open this project in code (`code .`), if tests.py happens to already be open, the lenses don't get automatically added. I have to close the file and reopen it to get code lenses."

On the other hand, in the test project above, this isn't the case - lenses automatically appear, regardless of whether I manually open my unit test file, or whether it's already open in VSCode.

**Comment by eyadsibai** [comment]
My issue is with py.test unfortunately I cannot share the code.. but will try to replicate it

**Comment by DonJayamanne** [comment]
@alexwhittemore @alexdawn are you still experiencing this  issue. 
I've tried to look at the code sample you have uploaded and it seems to work for me. And I do apologize for getting back to your after such a long time.

**Comment by alexwhittemore** [comment]
@DonJayamanne thanks for following up anyway :). The diligence really makes this project an absolute pleasure to use. Congratulations on MS hiring you, I think that's well deserved recognition of an excellent project. 

I'm not certain I still have the environment and codebase to quickly reproduce this issue, but I'll look into it.

**Comment by DonJayamanne** [comment]
@alexwhittemore woohoo... great news. thanks for the update

**Comment by eyadsibai** [comment]
Congrat @DonJayamanne

**Comment by DonJayamanne** [comment]
@eyadsibai thanks
