### ISSUE TITLE
print function doesn't output properly

### ISSUE THREAD

**Issue by playgithub** [DonJayamanne/pythonVSCode#846]
## Environment data
VS Code version:  1.10.2
Python Extension version:  0.6.0
Python Version:  3.5.3
OS and version:  Windows 10 Pro

`print("a", "b", sep=' ', end='\n')`

## Actual behavior
Output
a
b

## Expected  behavior
Output
a b

**Comment by Jagrmi** [comment]
print('a', 'b', sep=' ', end='\n')
#or
print('a', ' ', 'b', end='\n')
![1](https://cloud.githubusercontent.com/assets/16101427/24363613/080a3d00-1319-11e7-8b3d-12752043b323.JPG)

**Comment by playgithub** [comment]
Maybe the environments are not the same.

**Comment by DonJayamanne** [comment]
This is an upstream issue that has been resolved in the latest version of VS Code.
https://github.com/Microsoft/vscode/issues/17526

Please update VS Code to the latest version.

**Comment by playgithub** [comment]
After upgrading Code from 1.10.2 to 1.11.1, the problem is solved.
Thanks.
