### ISSUE TITLE
take a long time to  continue debugging after halt at a breakpoint

### ISSUE THREAD

**Issue by aeschli** [DonJayamanne/pythonVSCode#854]
_From @Liudx1985 on March 30, 2017 1:12_

- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.0|
|xml|DotJoshJohnson|1.7.0|
|code-runner|formulahendry|0.6.15|
|changeEncode|lanmj2004|0.0.8|
|cpptools|ms-vscode|0.10.5|
|sublime-keybindings|ms-vscode|2.0.1|;

---

Steps to Reproduce:

1.set debug point at python code,start debugging
2.halt at breakpoint, check the variables a little while, then continue run, the vscode takes a very long time to work normal

_Copied from original issue: Microsoft/vscode#23631_

**Comment by asierralozano** [comment]
I'm having this issue too. Just to clarify, i'm using the remote debugging for debugging Autodesk Maya

**Comment by DonJayamanne** [comment]
@asierralozano , apologies for not getting back to you on this issue.  
The [PTVS](https://github.com/Microsoft/PTVS) team are in the process of making some changes to the debugger that would improve the performance of this.
FYI - the extension is making use of the debugger developed by the PTVS team.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#97
