### ISSUE TITLE
"run python file" and "run selection" both use python shell

### ISSUE THREAD

**Issue by nanli-7** [DonJayamanne/pythonVSCode#856]
## Environment data
VS Code version:  1.10.2
Python Extension version:  0.6.0
Python Version:   2.7.13
OS and version:    
windows 10

## Actual behavior
when "run python file in terminal" and "run selection/line in python terminal", they both use python shell. 
as a result, the python shell gives error when run "python example.py"

## Expected  behavior
"run python file in terminal" should run in system shell, and "run selection/line in python terminal"should run in python shell. they should be treated seperately

## Steps to reproduce:  
-  
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by shelper** [comment]
this issue is duplicated on Mac
