### ISSUE TITLE
Help! How to deal with the "Unexpected number. Stopping the debug adapter." error?

### ISSUE THREAD

**Issue by RoadToDream** [DonJayamanne/pythonVSCode#86]
Can anyone help me? I was able to use the Plug-in to debug, but it went wrong yesterday. 
That's really a great tool for a new user, but this problem has nearly drown me crazy. 
![1](https://cloud.githubusercontent.com/assets/8088354/14587397/d8d478f4-04e4-11e6-8385-f1e149fd5f87.png)

@DonJayamanne

**Comment by msjia** [comment]
I got the same error after I think I have configured settings.json & launch.json according to the instruction given on the page....how to resolve it?

**Comment by msjia** [comment]
@RoadToDream I encountered same problem and managed to solve this by moving my workspace folder out from a chinese character folder....

**Comment by RoadToDream** [comment]
@msjia Thanks a lot! That's a great help!
I have reinstalled the system because of this issue ...

**Comment by DonJayamanne** [comment]
Closed, similar to issue #80

**Comment by DonJayamanne** [comment]
Unicode characters in file paths won't work in Python 2.7
However characters in file paths will work in Python 3.5
