### ISSUE TITLE
Error:there was an error in running the linter 'pylint'

### ISSUE THREAD

**Issue by Hedwiglzy** [DonJayamanne/pythonVSCode#860]
## Environment data
VS Code version:  1.10.2
Python Extension version:  0.6.0
Python Version:   3.5.2
OS and version:    Windows 8.1

## Actual behavior
Sometimes when using pylint to check python syntax, an error is reported :"Error:there was an error in running the linter 'pylint'"
## Expected  behavior
The previous version does not have this problem
## Steps to reproduce:  
-  Modify the python file
-  Reported  error

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
"python.linting.pylintPath": "c:/Python35/Scripts/pylint.exe"
```   
## Logs
Output from ```Python``` output panel  
```
Linting with pylint failed.
Command failed: c:/Python35/Scripts/pylint.exe --msg-template='{line},{column},{category},{msg_id}:{msg}' --reports=n --output-format=text e:\GitHub\Book_Info_Manager_System\BIMS\tests.py

##########Linting Output - pylint##########
************* Module BIMS.tests
15,0,convention,C0304:Final newline missing
15,0,warning,W0104:Statement seems to have no effect
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```
![1](https://cloud.githubusercontent.com/assets/18751676/24664740/073feeb2-198e-11e7-8220-9eb5a8aa6e43.png)

**Comment by spitis** [comment]
I had the same problem. `pip install --upgrade pylint` fixed it for me.

**Comment by Hedwiglzy** [comment]
My pylint has been upgraded to the latest version, but still often reported the error, before the version of vscode did not have this problem.

**Comment by noahleigh** [comment]
I get this problem when I'm looking at Git diffs before I commit, as if it's trying to lint the diff view (which I assume it's not supposed to)

Vscode 1.11, extension 0.6.0

**Comment by glarue** [comment]
I have this issue as well.
OS: Linux
VSCode v. 1.11.1
Python extension v. 0.6.0

Linter output:
```
Linting with pylint failed.
Command failed: /home/glarue/anaconda3/bin/pylint --msg-template='{line},{column},{category},{msg_id}:{msg}' --reports=n --output-format=text
```

**Comment by DonJayamanne** [comment]
I believe I have fixed this issue, please test in the latest version and let me know.
Related change https://github.com/DonJayamanne/pythonVSCode/commit/6f1ece025345c31036076d923f5341192f75d1e7

**Comment by glarue** [comment]
Yep, seems to have fixed it for me.

**Comment by DonJayamanne** [comment]
Yay
