### ISSUE TITLE
wrong output encoding

### ISSUE THREAD

**Issue by IgorNovozhilov** [DonJayamanne/pythonVSCode#861]
## Environment data
VS Code version:  1.11.1
Python Extension version:  0.6.0
Python Version:   3.3
OS and version:   win7 pro RU-ru 

## Actual behavior
![image](https://cloud.githubusercontent.com/assets/3082812/24773421/cf7bbe16-1b1d-11e7-9f97-6ee7958cdfe8.png)

## Expected  behavior
![image](https://cloud.githubusercontent.com/assets/3082812/24773513/3bfaf23c-1b1e-11e7-8798-3e8b9eff600d.png)

## Steps to reproduce:  
-  open `github.com/DonJayamanne/pythonVSCode` project
-  write `#TODO: Сделать это`

Your settings.json:   
```
https://github.com/DonJayamanne/pythonVSCode/blob/master/.vscode/settings.json
```
with `"python.linting.enabled": true`

**Comment by IgorNovozhilov** [comment]
This is in continuation of this issue: https://github.com/DonJayamanne/pythonVSCode/issues/844

**Comment by IgorNovozhilov** [comment]
The problem is that all the methods `open`, you must use the parameter `encoding`. Which indicate the current encoding of the file.
![image](https://cloud.githubusercontent.com/assets/3082812/24773998/ee93e858-1b1f-11e7-8819-5011cd90c47e.png)

**Comment by IgorNovozhilov** [comment]
And required to set the `current OS encoding` to run the commands `child_process.execFile`. So, as, it uses the encoding `utf8`. And starts `cmd.exe on Windows`, which uses the encoding `cp866` in `RU-ru` localization.

Or you can not use `child_process.execFile` and `child_process.exec`. And always use 'child_process.spawn', which runs without a flag `shell` default.
https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options

![image](https://cloud.githubusercontent.com/assets/3082812/24774936/8956795c-1b23-11e7-8035-bd32daa0dd84.png)

![image](https://cloud.githubusercontent.com/assets/3082812/24774941/8f94cc6a-1b23-11e7-8a1d-a7acbe7c5d4e.png)

![image](https://cloud.githubusercontent.com/assets/3082812/24774974/b42a2174-1b23-11e7-8068-2608cf65fa98.png)

**Comment by DonJayamanne** [comment]
Not sure if I follow you here. Why didn't using execFile work, it is using utf8, I thought that would work.

**Comment by DonJayamanne** [comment]
Thanks for your help here

**Comment by IgorNovozhilov** [comment]
Let me demonstrate by the example of the module `iconv-lite`.
This is a very very old problem of os windows: https://github.com/nodejs/node-v0.x-archive/issues/2190
Example:
```js
var ivl = require('iconv-lite');

var buf = child_process.execSync('echo Привет мир')

console.log(buf.toString('utf-8'))
console.log(ivl.decode(buf, 'cp866'));
```

![image](https://cloud.githubusercontent.com/assets/3082812/24787012/46d7fd30-1b6e-11e7-88ce-33570ec6bc6c.png)

**Comment by DonJayamanne** [comment]
Thanks for the excellent instructions. I have been able to replicate it with the above instructions.  
I'm in the process of setting up my PC so I can simulate this issue in VS Code and test this correctly for a release.  

Please bear with me for now.
FYI - I'll be releasing a new version without a fix for this, rest assured this is the next thing I'll be working on (already started downloading a 4Gb update to my PC, will take the whole night to run the damn windows update).

**Comment by DonJayamanne** [comment]
I'm not having much luck with replicating this in VS Code, I keep getting the following error:  
```19,0, warning:W015: Ccannot decode using ecoding "ascii", unexpected byte at position 6```   
I have configured my environment using Russian as the language. Any idea what else needs to be done?

**Comment by DonJayamanne** [comment]
Managed to replicate in VS Code, now to start fixing this damn issue.

**Comment by DonJayamanne** [comment]
@IgorNovozhilov I believe I can solve this, by putting a special case for CP866. Will look into #844, as that's a slightly different problem, cuz I'm using a 3rd party library Jedi.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#100
