### ISSUE TITLE
Run formatter without `"python.formatting.formatOnSave": true`

### ISSUE THREAD

**Issue by tkaria** [DonJayamanne/pythonVSCode#862]
## Environment data
VS Code version:  1.10.2
Python Extension version:  0.6.0
Python Version:   2.7.8
OS and version:   OSX 10.11.6

## Actual behavior
N/A

## Expected  behavior
Would like to run the formatter without having to specify `"python.formatting.formatOnSave": true` but can't seem to find a way to do that. Behaviour I would like to emulate is that of the beautify plugin (cmd+shift+p beautify)

## Steps to reproduce:  
-  
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
Right click the editor and select format. This is a standard vscode feature (menu option).
