### ISSUE TITLE
Links above test cases: randomly appear and should be possible to hide

### ISSUE THREAD

**Issue by petrux** [DonJayamanne/pythonVSCode#863]
This is not a proper bug report but its half a bug report, half a feature request and half (wow! 3 *half*) a request for instructions.

1. The links `Run Test|Debug Test` above test cases seem to have a completely random behavior (using normal unittests). Is there any way to force the extension to re-scan them? Is this feature somehow configurable?
2. when fixing newlines, ecc., should be useful to automatically make them disappear and re-appear.

Thanks!

**Comment by DonJayamanne** [comment]
1. In order to force the rescanning of unit tests, you run the following command    
```Run all Unittests```` 
2. This doesn't seem to make sense. Please could you provide more information about this issue or feature request.

**Comment by petrux** [comment]
Regarding point 2: it would be helpful to make those links just appear/disappear with some commands. It just happened to me that sometimes, when fixing the code formatting trying to keep one line between declarations and two lines between top level declarations, I got something messed up in the test modules since the links can be misleading in getting how many blank lines are there. But I am pretty sure that running some automatic formatting tool can solve the problem and that is it just me having this issue. Thanks!

**Comment by DonJayamanne** [comment]
Please could you give me an example with some sample code for ```point 2```

**Comment by petrux** [comment]
I don't think I can give a code example. It is just about giving the user the possibility to visualize or not such links. It is just a minor issue.

**Comment by DonJayamanne** [comment]
Thanks, closing for now, as the above two commits should address most of the issues.
Thanks

**Comment by DonJayamanne** [comment]
Thanks, closing for now, as the above two commits should address most of the issues.
