### ISSUE TITLE
Git lens hides Python test lens

### ISSUE THREAD

**Issue by mklemarczyk** [DonJayamanne/pythonVSCode#865]
## Environment data
VS Code version:  1.11.1
Python Extension version:  0.6.0
Python Version:   Python 3.6
OS and version:   Windows 10

## Actual behavior
Test lens are not visible

## Expected  behavior
Test lens are visible to run separate test

## Steps to reproduce:  
-  Install GitLens
-  Open file contains python unittests

## Settings
Your settings.json: Default

![screenshot 197](https://cloud.githubusercontent.com/assets/2727261/24827903/3318b768-1c53-11e7-8610-775443a04aec.png)
![screenshot 198](https://cloud.githubusercontent.com/assets/2727261/24827905/34c760aa-1c53-11e7-8d48-f2eaa9329abd.png)

**Comment by DonJayamanne** [comment]
Sounds like a problem with gitlens, if so then please raise this issue on the git lens repo.

**Comment by mklemarczyk** [comment]
I'd opened an issue on https://github.com/eamodio/vscode-gitlens/issues/60

By the way, Python extension finds only existing tests. If I write a new test I need to restart windows to see Test lens.

**Comment by MarekLew** [comment]
By my way.Python extension finds only existing tests. If I write a new test
and save this file. I need to change focuse tab or start edit the file
to see Test lens. Restart Windows not neede.

23:59 Wt., 11.04.2017 użytkownik Don Jayamanne <notifications@github.com>
napisał:

**Comment by DonJayamanne** [comment]
Just run the command 'python:discover tests' from the command pallette.

**Comment by MarekLew** [comment]
> Just run the command 'python:discover tests' from the command pallette.

What extension added this option. I don't have this in command pallette.

**Comment by eamodio** [comment]
@DonJayamanne I'm pretty sure this is a duplicate of https://github.com/DonJayamanne/pythonVSCode/issues/553. Looking at your code for the test code lens -- you use [vscode.executeDocumentSymbolProvider](https://github.com/DonJayamanne/pythonVSCode/blob/adaeb153e527c584a3423f732796f639c7f01938/src/client/unittests/codeLenses/testFiles.ts#L64), which I also use in GitLens

**Comment by mklemarczyk** [comment]
👍  Thank you for solving problem

**Comment by xqliu** [comment]
I also don't have the python:discover tests command...

Could you please advice on how could we get this appear?

Thanks

**Comment by mklemarczyk** [comment]
@DonJayamanne discover tests does not exists in current version. Is there everything ok?
