### ISSUE TITLE
bug for python in vscode

### ISSUE THREAD

**Issue by weinand** [DonJayamanne/pythonVSCode#868]
_From @github-lwc on April 9, 2017 13:24_

hello

I found a bug about vscode, that I can't see the input prompt when I run the following python code.

test.py:
#encoding:utf-8
birth = raw_input('birth: ')
if birth < 2000:
    print u'00前'
else:
    print u'00后'

_Copied from original issue: Microsoft/vscode#24365_

**Comment by weinand** [comment]
You will have to configure your launch configuration to use a terminal fro python that supports reading user input.

**Comment by github-lwc** [comment]
yes,I have set the config for python,and can be nornal to run other code, but Unable to run the above code

the following is my config of tasks.json :
{
    "version": "0.1.0",
    "command": "python",
    "isShellCommand": true,
    "args": ["${file}"],
    "showOutput": "always"
}

**Comment by weinand** [comment]
@github-lwc your launch config does not specify something like "console", so it is using the default debug console which does not support to read user input.

**Comment by github-lwc** [comment]
I am sorry,I don't know how to specify the something like"console" in vscode, do you have some configure document ?

thanks

**Comment by DonJayamanne** [comment]
@github-lwc Please have a look at the animated gif.

https://github.com/DonJayamanne/pythonVSCode/wiki/Capture-User-Input-via-input()-or-raw_input()
