### ISSUE TITLE
Can I add multiple virtual environment?

### ISSUE THREAD

**Issue by timinGo** [DonJayamanne/pythonVSCode#869]
how can I add multiple virtual environment?
Like below:

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
{
    "python.pythonPath": "/usr/local/bin/python3.6", "/Users/jiachen/data_env/bin"
}
```

**Comment by DonJayamanne** [comment]
Why would you want to do that? Don't you use one interpreter at a time?
