### ISSUE TITLE
"python.jediPath" does not seem to work

### ISSUE THREAD

**Issue by egabrum** [DonJayamanne/pythonVSCode#870]
## Environment data
VS Code version:  1.11.1
Python Extension version:  0.6.0
Python Version:   2.7.12
OS and version:    Windows 7

## Actual behavior
Jedi 0.10.2 or 0.10.0 installed in C:\Python27\Lib\site-packages\jedi

In settings.json, if:
//"python.jediPath": "C:/Python27/Lib/site-packages/jedi", 
'Go to symbol in File'(Ctrl-Shift-O) shows symbols in code files.

but if:
"python.jediPath": "C:/Python27/Lib/site-packages/jedi", (or "C:\\Python27\\Lib\\site-packages\\jedi")
'Go to symbol in File'(Ctrl-Shift-O) DOES NOT FIND ANY SYMBOL in code files.

## Expected  behavior
'Go to symbols in File' works when I have "python.jediPath" configured.

## Steps to reproduce:  
-  Use 'Go to symbol in File'(Ctrl-Shift-O) feature with and without the "python.jediPath" setting.

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by kakinuma4ko** [comment]
i have that question too :(
