### ISSUE TITLE
Sort Imports does not allow one import per line

### ISSUE THREAD

**Issue by LukasDrude** [DonJayamanne/pythonVSCode#871]
## Environment data
VS Code version:  March 2017 (version 1.11)
Python Extension version:  0.6.0
Python Version:   Python 3.5.2 :: Anaconda custom (x86_64)
OS and version:    Darwin Kernel Version 15.6.0 (OSX)

## Actual behavior
All imports from one module are grouped to a single line (or grouped by parentheses).

Example:
```
from long_name import very_long_name
from long_name import very_very_long_name
from long_name import very_very_very_long_name
```
will be grouped to:
```
from long_name import (very_long_name, very_very_long_name,
                       very_very_very_long_name)
```

## Expected  behavior
PEP8 [Section on Imports](https://www.python.org/dev/peps/pep-0008/#id23) recommends single lines per input. If desired, it is ok to group imports.

Having one line per import lets you delete/ modify imports faster. Thus, my expectation is, that **grouping should be either disabled or there needs to be an option to disable it** and enforce line by line imports.
At least the documentation [Refactoring:-Sort-Imports](https://github.com/DonJayamanne/pythonVSCode/wiki/Refactoring:-Sort-Imports) does not tell me about such an option.

**Comment by DonJayamanne** [comment]
You need to configure isort, the sorting is fine using the isort library. 
Please place the appropriate isort config with relevant settings.

**Comment by LukasDrude** [comment]
Great. This did the trick:

Edit `~/.isort.cfg`:
```
[settings]
force_single_line=True
```

The link to the relevant [isort documentation section](https://github.com/timothycrosley/isort#multi-line-output-modes) would be great in the project wiki [Refactoring:-Sort-Imports](https://github.com/DonJayamanne/pythonVSCode/wiki/Refactoring:-Sort-Imports).

**Comment by DonJayamanne** [comment]
Will update the documentation

**Comment by DonJayamanne** [comment]
Updated https://github.com/DonJayamanne/pythonVSCode/wiki/Refactoring:-Sort-Imports
