### ISSUE TITLE
regression: command 'python.buildWorkspaceSymbols' not found since 0.61 update

### ISSUE THREAD

**Issue by ychab** [DonJayamanne/pythonVSCode#874]
Just updated to 0.6.1 and now, I cannot run the command to build workspace symbols... No more explicit message in the developer console...

Is there is any reason about this? Am I the only one to face with this?

Thanks

**Comment by DonJayamanne** [comment]
It is still there. Please ensure you have opened a Python file.  
If the problem persists, please could you open ```Developer Tools``` from the Help menu and go into the ```Console``` window and provide me a dump of any errors displayed.

**Comment by ychab** [comment]
Thanks you to reply so quickly.

Nope, as say previously, I don't have any more explicit message in dev tools console than : *command 'python.buildWorkspaceSymbols' not found* ...

What you mean by 

> opened a Python file.

? I was thinking that this command build tags for the entire workspace, not a specific file...

**Comment by ychab** [comment]
Pfff just restarting my desktop this morning and... this is working for now!! Sorry for wasting your time and thanks for your support
