### ISSUE TITLE
about search for ctags symbles used Ctrl+Shift+T.

### ISSUE THREAD

**Issue by scriptkitz** [DonJayamanne/pythonVSCode#877]
## Environment data
VS Code version:  1.11.1
Python Extension version:  0.6.1

When you press Ctrl+Shift+T to search for the ctags symbles, 
Please use the word under current cursor to enter the search editbox.

Thx.

**Comment by scriptkitz** [comment]
up @DonJayamanne ☺

**Comment by scriptkitz** [comment]
@DonJayamanne  😄

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#101
