### ISSUE TITLE
Extract method is slow

### ISSUE THREAD

**Issue by hexler81** [DonJayamanne/pythonVSCode#878]
## Environment data
VS Code version:  1.11.1
Python Extension version:  0.6.1
Python Version: 2.7.13
OS and version: Windows 10 64-bit
Machine: Intel Xeon E3-1505M (2.8GHz), 16 GB RAM

## Actual behavior
Extracting a method takes very long (14s in my case for one if-statement with 5 lines of code)!

## Settings  
Your settings.json:   
```json
python.linting.pylintArgs: ["--rcfile<path_to_my_pylintrc>"],
```

**Comment by ke-real** [comment]
Not sure if it is the same for @hexler81 but for me extracting itself is not slow, but changing name from suggested autogenerated name is what takes too much time.

**Comment by DonJayamanne** [comment]
Thanks for being patient, and I do apologize for not getting back to you on this issue. Been a little busy looking at other issues. Things will change soon and we'll be able to focus on these (as we'll have more resources looking into them).

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#103
