### ISSUE TITLE
intellisense for base classes

### ISSUE THREAD

**Issue by slayerrensky** [DonJayamanne/pythonVSCode#88]
Intellisense for base class funtions not shown.

**Comment by rampage644** [comment]
+1

**Comment by coladou** [comment]
+1

**Comment by DonJayamanne** [comment]
Hi, sorry for the delay. I'm finally able to work full time on these issues now. 
I've looked at this and can confirm that intellisense for base classes works as expected and is displayed.
Please could you provide me with an example of whats not working.

**Comment by rampage644** [comment]
Honestly, I don't remember why I've +1'ed this :)
However, I'll come with more info once I have opportunity (==once I will be able to reproduce this).

**Comment by DonJayamanne** [comment]
Thanks, I'll close this for now.
