### ISSUE TITLE
Cannot enter brackets in Python Terminal (both square "[" and curly "{")

### ISSUE THREAD

**Issue by zenkzz** [DonJayamanne/pythonVSCode#882]
## Environment data
VS Code version:  1.11.1
Python Extension version:  0.6.1
Python Version:   3.5.2
OS and version:   Windows 7 Enterprise Version 6.1 (Build 7601: Service Pack 1)

## Actual behavior
Cannot enter brackets in Python Terminal (both square "[" and curly "{")
a[b] is copied as ab to the Python Terminal
## Expected  behavior
Brackets can be copied and can be entered in the terminal
## Steps to reproduce:  
Write "a[b]" in Python Terminal 

## Settings  
Your settings.json:   
```json
// Place your settings in this file to overwrite the default settings
{
    "workbench.colorTheme": "Default Light+"
}
```

**Comment by DonJayamanne** [comment]
Please could you provide a screen shot with more precise instructions. What do you mean by python terminal, how did your access this, what menu did you use to get to this python terminal?

**Comment by zenkzz** [comment]
![image](https://cloud.githubusercontent.com/assets/1749072/25222718/881c8536-25b9-11e7-8c13-97201cb0d7e8.png)

![image](https://cloud.githubusercontent.com/assets/1749072/25222928/1953a142-25ba-11e7-8e78-24e52fa6cdc4.png)

By Python Terminal I mean: Ctrl-Shift-P "Python: Run Selection/Line in Python Terminal"
The same behavoir in View->Integration Terminal. Then "python". Then copy "print(["Hello","World"])" into the terminal. The brackets have already disappeared even before I hit Enter.

**Comment by zenkzz** [comment]
On another computer with a Russian Windows the problem does not exist. The brackets can be easily entered.

**Comment by DonJayamanne** [comment]
>The same behavoir in View->Integration Terminal. Then "python". Then copy "print(["Hello","World"])" into the terminal. The brackets have already disappeared even before I hit Enter.

If this is the case the this is an issue with VSCode  itself and not this extension. Please report this issue, on vscode repo.

**Comment by zenkzz** [comment]
Hi Don,

I created an issue with VSCode. The problem is only when in Windows the default input is German. If I switch the default input to English then I can input the brackets. Somehow the issue is only for python. In Julia I can input brackets without a problem.

**Comment by DonJayamanne** [comment]
Cheers
