### ISSUE TITLE
Unable to rename variables and methods in jupyter python files

### ISSUE THREAD

**Issue by akochepasov** [DonJayamanne/pythonVSCode#885]
## Environment data
VS Code version: 1.11.1
Python Extension version: 0.6.2
Jupyter Extension version:1.1.1
Python Version: python 2.7.13 Anaconda2
OS and version: Win 8

## Actual behavior
In python jupyter document add timing for an operator, e.g.
%%timeit -n 1000
Select a variable in any location, press F2 to rename, rename, press Enter. The result is 
Error: Refactor failed. Syntax error in file <test.py> line <111>: invalid syntax

## Expected  behavior
Successful renaming

## Steps to reproduce:  
- Take any python script 
-  Add %%timeit -n 1000 for an expression e.g.:
```
line = "12345"
%%timeit -n 10
map(int, line)
```
- Select the line variable 
- press F2 to rename, rename, press Enter. 
The result is 
Error: Refactor failed. Syntax error in file <test.py> line <5>: invalid syntax

## Settings  
Your launch.json (if dealing with debugger issues):  
Standard launch.json, no changes
Your settings.json:   
No settings.json
## Logs
Output from ```Python``` output panel  
No output

Output from ```Console window``` (Help->Developer Tools menu)
```
Refactor failed. Syntax error in file <test.py> line <102>: invalid syntax
[('refactor.py', 266, 'watch', 'self._process_request(self._input.readline())'), ('refactor.py', 247, '_process_request', "request['start']), request['name'], int(request['indent_size']))"), ('refactor.py', 178, '_rename', 'refactor.refactor()'), ('refactor.py', 89, 'refactor', 'self.onRefactor()'), ('refactor.py', 110, 'onRefactor', 'renamed = Rename(self.project, self.resource, self.startOffset)'), ('C:\\Users\\anton\\.vscode\\extensions\\donjayamanne.python-0.6.2\\pythonFiles\\rope\\refactor\\rename.py', 23, '__init__', 'this_pymodule = self.project.get_pymodule(self.resource)'), ('C:\\Users\\anton\\.vscode\\extensions\\donjayamanne.python-0.6.2\\pythonFiles\\rope\\base\\project.py', 116, 'get_pymodule', 'return self.pycore.resource_to_pyobject(resource, force_errors)'), ('C:\\Users\\anton\\.vscode\\extensions\\donjayamanne.python-0.6.2\\pythonFiles\\rope\\base\\pycore.py', 142, 'resource_to_pyobject', 'return self.module_cache.get_pymodule(resource, force_errors)'), ('C:\\Users\\anton\\.vscode\\extensions\\donjayamanne.python-0.6.2\\pythonFiles\\rope\\base\\pycore.py', 255, 'get_pymodule', 'force_errors=force_errors)'), ('C:\\Users\\anton\\.vscode\\extensions\\donjayamanne.python-0.6.2\\pythonFiles\\rope\\base\\pyobjectsdef.py', 162, '__init__', 'source, node = self._init_source(pycore, source, resource)'), ('C:\\Users\\anton\\.vscode\\extensions\\donjayamanne.python-0.6.2\\pythonFiles\\rope\\base\\pyobjectsdef.py', 191, '_init_source', 'raise exceptions.ModuleSyntaxError(filename, e.lineno, e.msg)')]

```

**Comment by akochepasov** [comment]
Essentially, it means, that if there are notebook marks, like %%, refactoring doesn't work. Using the jupyter notebooks in VSCode is great and really convenient and enabling refactoring would be another step to make the IDE even better.

**Comment by DonJayamanne** [comment]
Closing in favour of https://github.com/DonJayamanne/pythonVSCode/issues/824
