### ISSUE TITLE
NotImplementedError, cannot determine number of cpus

### ISSUE THREAD

**Issue by willyd** [DonJayamanne/pythonVSCode#89]
Hi, 

The extension is really nice. Thanks for making this available. 

I have a problem with the multiprocessing module:

I cannot execute a simple program such as:

```python
import multiprocessing
print('CPU count: {}'.format(multiprocessing.cpu_count()))
```

I get the above error.

I seems that this is all related to the fact that the environment does not seem to contain the environment variable:

NUMBER_OF_PROCESSORS 

Any chance for a fix?

**Comment by DonJayamanne** [comment]
Hi, I just tried this and it works on my pc. Windows 8 python 3.5. 
What is your environment?

**Comment by willyd** [comment]
Windows 10 Python 2.7.11 Ananconda 64 bit
`multiprocessing.__version__ == '0.70a1'`

**Comment by seeb0h** [comment]
Same error with  :
`import sklearn

It works fine when I use it without VSC.

Win7 64-bit
Anaconda 2.4.1 64-bit / Python 2.7.11

launch.json
```
            "name": "myFile",
            "type": "python",
            "request": "launch",
            "program": "${workspaceRoot}\\myFile.py",
            "stopOnEntry": false,
            "args": [],
            "pythonPath": "C:\\Users\\xxx\\AppData\\Local\\Continuum\\Anaconda2\\python.exe",
            "showOutput": "always",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
```

**Comment by albeirobu** [comment]
Uso la aplicacion Visual Code y me salia el mismo error, realice una solución un poco profesional pero me funciono!!!!!

1. ir a la carpeta dentro de Python, Pack de Anaconda o Canopy
               \lib\multiprocessing\__init__.py", line 136, in cpu_count
2. Buscar las siguentes lineas, normalmente estan en la line 100 a la 140...
                 #if num >= 1:
    if num >= 1: 
        return num
    else:
        raise NotImplementedError('cannot determine number of cpus')

**Comment by DonJayamanne** [comment]
Fixed in the latest version

**Comment by kanika0703** [comment]
What version has this issue been fixed ? I am getting similar issue when trying to run robot scripts using pabot on windows 10 and python 2.7.13 version
