### ISSUE TITLE
ctags exclude folders

### ISSUE THREAD

**Issue by janhancic** [DonJayamanne/pythonVSCode#891]
I accidentally opened the `.vscode/tags` file and noticed that ctags built a definition list (or whatever, I'm not familiar with ctags) for stuff in my excluded folders. Can this be made so it doesn't scan excluded files (or maybe create a new setting for this)?

I'm not sure of this is related to my problem of not having full intellisense or not though.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#105
