### ISSUE TITLE
When Integrated terminal is BashOnUbuntuOnWindows - Run File in Term passes windows path

### ISSUE THREAD

**Issue by EricPell** [DonJayamanne/pythonVSCode#894]
## Environment data
VS Code version:  
Python Extension version:  
Python Version:   
OS and version:    

## Actual behavior
When the integrated terminal is set to 
"terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe",

executing any python commands opens the WSL native python interpreter as expected.
However, all file name paths are still provided to python as if they are windows paths.

Output after "Run Python file in terminal":
python c:/Users/ericp/OneDrive/beyond_the_peak/python/plots/jupyter-test/_test.py

> python c:/Users/ericp/OneDrive/beyond_the_peak/python/plots/jupyter-test/_test.py
python: can't open file 'c:/Users/ericp/OneDrive/beyond_the_peak/python/plots/jupyter-test/_test.py': [Errno 2] No such file or directory
>
> which python
> /usr/bin/python 

## Expected  behavior
The file path would be sent to python using an appropriate path name for the WSL

## Steps to reproduce:  
-  Set terminal to WSL bash
-  Open python file on the windows file system (visible to bash.exe from /mnt/c/
-  select "Run Python file in terminal"

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```{
    "[cpp]": {
        "editor.quickSuggestions": false
    },
    "[c]": {
        "editor.quickSuggestions": false
    },
    "editor.minimap.enabled": true,
    "git.confirmSync": false,
    // Bash on Ubuntu (on Windows)
    "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe",
    "terminal.integrated.shell.linux": "bash.exe"
}
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
Closing in favor of https://github.com/DonJayamanne/pythonVSCode/issues/534 (to add proper support for WSL)
