### ISSUE TITLE
Linting with open/close py-file

### ISSUE THREAD

**Issue by IgorNovozhilov** [DonJayamanne/pythonVSCode#896]
## Environment data
VS Code version:  1.11.2
Python Extension version:  0.6.3
Python Version:   3.3
OS and version:    win7 pro RU-ru

## Steps to reproduce:  

Again repeated the problem described in this issue https://github.com/DonJayamanne/pythonVSCode/issues/375

**Comment by IgorNovozhilov** [comment]
## Additionally
![2017-04-19_15h47_06](https://cloud.githubusercontent.com/assets/3082812/25180720/bba90278-2517-11e7-9783-8205f1730e28.png)
![2017-04-19_15h47_47](https://cloud.githubusercontent.com/assets/3082812/25180724/c090bee8-2517-11e7-8842-3db134a45326.png)

**Comment by DonJayamanne** [comment]
Thanks, this is slightly different. Looks like the linter is linting diff files.
Thanks for the detailed explanation, will look into this.
