### ISSUE TITLE
The python debugger is extremely slow

### ISSUE THREAD

**Issue by mjbvz** [DonJayamanne/pythonVSCode#897]
_From @FuZhiyu on April 19, 2017 7:37_

- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.14.0|
|gitignore|codezombiech|0.5.0|
|git-extension-pack|donjayamanne|0.1.2|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.2|
|gitlens|eamodio|3.4.5|
|sublime-keybindings|ms-vscode|2.0.1|
|vscode-open-in-github|ziyasal|1.2.3|;

---

Steps to Reproduce:

1. run the VSC debugger;
2. run the file in the console;
3. compare the speed.

Running in the VSC debugger is much slower than running it outside.

_Copied from original issue: Microsoft/vscode#25001_

**Comment by DonJayamanne** [comment]
Please Define extremely slow.
Debugging applications will always be slower than running without debugging, that's an obvious fact.

So please define extremely slow, is it unusable? Please provide the sample code.

**Comment by DonJayamanne** [comment]
@FuZhiyu fyi

**Comment by xoviat** [comment]
@mjbvz this is actually somewhat your problem because pythonvscode uses the visual studio python debugger.

**Comment by DonJayamanne** [comment]
Still haven't answered the questions.

**Comment by DonJayamanne** [comment]
@xoviat 
How is this @mjbvz 's problem? 

> @mjbvz this is actually somewhat your problem because pythonvscode

**Comment by xoviat** [comment]
He works for Microsoft and the debugger is written by Microsoft. Now, I'm not asking him to fix this project's problems and I have no ill will towards Microsoft, but I am pointing out that the visual studio debugger probably has the same problems.

**Comment by DonJayamanne** [comment]
Lol. We can't start pointing fingers at anyone who works at Msft. Besides the problem could be with my implementation of the code, I don't think you have ruled that out. I don't think it's a good idea to start pointing fingers on this manner. If you stay doing this, you only alienate people in the opens source community.

**Comment by xoviat** [comment]
I'm not blaming microsoft. I'm saying that they might need to fix their debugger for visual studio. I'm not complaining.

**Comment by GiuseppeLaurenza** [comment]
@xoviat There are any news about the inclusion of pydev debugger?

@DonJayamanne  Some times with multithreading programming i see strange crash that i do not see with Pycharm (that use pydev) so i think that the problem is VS debugger. Also the performance of VS code in debug mode are poor with respect to the performance of Pycharm

**Comment by xoviat** [comment]
@GiuseppeLaurenza 

I have an open pull request here: https://github.com/DonJayamanne/pythonVSCode/pull/942

If you want to help, fork that and then fix the travis-ci tests.

**Comment by GiuseppeLaurenza** [comment]
@xoviat 
Thanks for the fast reply. I hope that I can help. At the end of the next job deadline I try to help

**Comment by lsternlicht** [comment]
any idea of what changed here? I am also experiencing extremely slow debug

**Comment by DonJayamanne** [comment]
Nothing has changed in the extension to slow down the debugging experience. I'll check vscode.

**Comment by imaia** [comment]
Python debugging is quite slow here too. While pdb takes about 1s, in vs code, it takes up to two minutes.

**Comment by RokkerRuslan** [comment]
Python 3.6.2 (default, Jul 20 2017, 08:43:29)
[GCC 5.4.1 20170519] on linux
Python debugging is very slow
PyCharm 3-6 seconds. VsCode 3-4 minutes (plus - no any output at console).

**Comment by cefn** [comment]
Confirm I am experiencing a slow debugger in Ubuntu Xenial 16:04. In the tests I was performing, PyCharm can debug from one point to another in the same codebase around 4 times faster than VSCode.

**Comment by JulioV** [comment]
Also in windows 10

**Comment by GiuseppeLaurenza** [comment]
i had the same problem on macOS Sierra

**Comment by doomleika** [comment]
Can confirm, it's so slow that I have to break out PyCharm for moderately computation expensive code

**Comment by hatarist** [comment]
Same here, it's insane, went back to pudb :o

**Comment by sametmax** [comment]
If I try to debug a flask process, I run the dev server. I measured that starting the server with the VSCode debugger is 22 times slower than starting it manually, which makes it unappealing compared to pdb.

**Comment by Madder** [comment]
The debugger is really unusable as it stands

**Comment by laughteroverflow** [comment]
Encountered the same problem.

In debug mode, 
"import tensorflow" cost more than 20 seconds; 
"from tensorflow.examples.tutorials.mnist import input_data" cost more than 1 minute.

OS: macOS 10.12.6
VSCode: 1.16.0
Python: 0.7.0

**Comment by EECSGEEK** [comment]
TO DonJayamann
>Please Define extremely slow.
>Debugging applications will always be slower than running without debugging, that's an obvious fact.

Run a test.py
type "python test.py" in Terminal window, is much faster \
than press double F5 to run it.

Is there any shortcut to switch cursor to Terminal window or Text edit windows?

Whats more, when mouse cursor in Terminal windows,
I press F5, the cursor doesn't switch to Debug Console Window.
So I must click to Debug Console Window to see the output,.

OS: win10 1703
VScode: 1.6.1

**Comment by brettcannon** [comment]
I believe the debugger situation is being evaluated at the moment in regards to pydevd, etc. so this may be changing in the future. Unfortunately there's no timeline, but people are aware of the desire for a different debugger option other than ptvsd.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#106
