### ISSUE TITLE
Cantnot complete in docstrings

### ISSUE THREAD

**Issue by wzdnzd** [DonJayamanne/pythonVSCode#898]
## Environment data
VS Code version:  1.11.2
Python Extension version:  0.6.3
Python Version:   2.7.13/3.6.1
OS and version:    win10

## Actual behavior
![3ccee838-2520-11e7-9a36-b45ac2894e72](https://cloud.githubusercontent.com/assets/8565764/25209890/214e5cac-25b0-11e7-8327-d4f018b63dc3.gif)

cannot complete when i typing "line." 
## Steps to reproduce:  
like the picture above-mentioned

**Comment by DonJayamanne** [comment]
This issue was moved to davidhalter/jedi#921
