### ISSUE TITLE
Any Plans to Support Virtual Environments?

### ISSUE THREAD

**Issue by moigagoo** [DonJayamanne/pythonVSCode#9]
I guess you can work around lack of virtualenv support by hacking PYTHONPATH or something like that, but I wonder if you have any plans to add a more friendly way to switch between environments.

**Comment by DonJayamanne** [comment]
To be honest I have absolutely no idea about virtual environments in Python. I've only used Python on my Raspberry PIs and a few web applications. But never used them, i have heard of them, but never used. I sure would like to support it, but would need to first get my head around it, i.e. learn about it. 
And that's something I dont have much time for :(. Busy with a few other things as well.... along with the debugger, which to me is more interesting and useful, as that's something I need.

**Comment by moigagoo** [comment]
I totally agree that the debugger is more important.

Long story short, an environment is just a directory with the Python interpreter and packages. To switch between environments basically means to pick the Python interpreter.

Theoretically, it should be enough to set the `python.pythonPath` variable in the workspace config to activate a particular environment. I tried that, but it didn't work.

I have a feeling that the debugger uses the default Python interpreter anyway just ignoring the `python.pythonPath` value. It's easy to check by running `from sys import executable; print(executable)`. I noticed that `executable` is the same no matter what I put in `python.pythonPath` in user or workspace settings.

**Comment by DonJayamanne** [comment]
Yes the debugger does use the standard default python interpreter. But there isn't any point in modifying that (current don debugger) as I am quite close to getting the new debugger working to a stage that would make it much better than the current version, even though it may have a few incomplete.

**Comment by DonJayamanne** [comment]
Thanks for the info on thre environments

**Comment by moigagoo** [comment]
> Yes the debugger does use the standard default python interpreter.

Is that intended or is it a bug? If the debugger ignores `python.pythonPath`, then where is it used at all? I mean, there's no other place where the interpreter is called as far as I can see. Am I missing something?

It _looks_ like the value should be taken into account by the debugger, but I may be interpreting this totally wrong: https://github.com/DonJayamanne/pythonVSCode/blob/master/src/client/debugger/main.ts#L144

> there isn't any point in modifying that (current don debugger) as I am quite close to getting the new debugger working to a stage

That's great, can't wait to see the new debugger in action :-) Any hint on what will it be?

**Comment by DonJayamanne** [comment]
Forgive me, you are right. My plan  was to introduce a config setting, and I forgot that I did introduce such a setting in the last release. Ingesting  that it doesn't work. Are you using a Mac or a pc? Also weekday value did you place in the config? Thanks.

**Comment by moigagoo** [comment]
I have both a Mac and a PC, so I can actually test it on both. At the moment I'm on Mac, so here's what I have here: `python3` in the user config and `/Users/kmolchanov/.local/share/virtualenvs/sloth/bin/python` in the workspace config. My intention was to declare Python 3 as the default version for VSCode to use in general and to use a particular interpreter for this particular project.

**Comment by moigagoo** [comment]
This param is ignored in Windows as well, just checked it.

**Comment by DonJayamanne** [comment]
Found the bug, the param is not passed through as i hadn't configured the path on the configuration section. This has been fixed and the new release will be available later today.

**Comment by DonJayamanne** [comment]
Sorry, didn't mean to close this issue. Butter fingers.

**Comment by moigagoo** [comment]
@DonJayamanne I just updated the extension to 0.2.3, and the custom Python path is still ignored. Is it supposed to be fixed yet, or am I checking too early?

**Comment by DonJayamanne** [comment]
Hi, it should be working. I tested is before releasing it, tested it just now.
You need to set the full path to the python executable.
Can you post a copy of your launch.json file.

**Comment by moigagoo** [comment]
I may be doing it wrong. I put the full path to the Python executable in my project's settings.json:
```
// Place your settings in this file to overwrite default and user settings.
{
    "python.pythonPath": "/Users/kmolchanov/.local/share/virtualenvs/sloth/bin/python"
}
```
Should I declare it in launch.json instead? If yes, in which param?
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Python",
			"type": "python",
			"request": "launch",
			"program": "run.py",
            "args": ["start"],
			"stopOnEntry": true
		}
	]
}
```

**Comment by DonJayamanne** [comment]
For the debugger you need to define it in "pythonPath". You should get the intellisense for that. Unfortunately there is no way to share the  settings between the debugger and workspace settings, at least  not that I know of.

**Comment by moigagoo** [comment]
Thanks a lot! All working great now.

Thanks for the kickass extension!

**Comment by DonJayamanne** [comment]
That's great news, thanks

**Comment by ericshenjs** [comment]
I set a environment variable ,like so:Anaconda_home = G:\BinX86\Py3 ,but when I set :"python.pythonPath":  "\"%Anaconda_home%\\python.exe\"", cannot work;if I set "python.pythonPath":  "G:/BinX86/Py3/pythonw.exe",can work

**Comment by moigagoo** [comment]
Try escaping backslashes: `%Anaconda_home%\\python.exe`. Also, I'm not sure env variables are allowed in those paths.

**Comment by DonJayamanne** [comment]
@moigagoo , I have updated the wiki with two options to using the extension when dealing with virtual environments. Please could you have a quick look and let me know what you think.
The preferred option is simple:
- Activate your virtual environment from your command window (or terminal window)
- From that terminal/command window, you will then launch VS Code

This will ensure VS Code will inherit all of the environment variables (settings) as defined & configured by the Virtual Environment for Python you have selected. I.e. no more messy configuration of settings.json.

Oh yes, you need to clear all of the python paths in settings.json, to ensure they point to their defaults.

**Comment by moigagoo** [comment]
@DonJayamanne Sounds great! Thanks a lot for the kickass extension and this update.

It's great that there're two ways to do it. It's nice to have a choice. I actually prefer the settings.json way because this way you just configure the project once and don't have to launch VSCode from the shell any time. But the suggested option is totally OK, it's just a matter of personal preference.
