### ISSUE TITLE
Rename refactoring fails on code with type annotations

### ISSUE THREAD

**Issue by pelotom** [DonJayamanne/pythonVSCode#902]
[PEP 3107](https://www.python.org/dev/peps/pep-3107/) introduced type annotations to python syntax, but the VS Code python extension's refactoring mechanism can't handle them.

## Environment data
VS Code version:  1.11.2
Python Extension version: 0.6.3
Python Version: 3.6
OS and version: OSX

## Steps to reproduce:  
-  Take some code with type annotations, e.g.
    ```python
    def increment(x: int) -> int:
      return x + 1
    ```
-  Attempt to rename the variable `x` to `y`.

This produces an error:
<img width="997" alt="screen shot 2017-04-20 at 3 37 52 pm" src="https://cloud.githubusercontent.com/assets/128019/25255430/5ef1472a-25df-11e7-8b01-8f980fe8eee3.png">

**Comment by DonJayamanne** [comment]
Closing in favor of https://github.com/DonJayamanne/pythonVSCode/issues/824
