### ISSUE TITLE
Slow auto complete speed for custom modules python

### ISSUE THREAD

**Issue by mjbvz** [DonJayamanne/pythonVSCode#903]
_From @quanvuong on April 21, 2017 8:35_

- VSCode Version: 1.11.2 
- OS Version: mac 10.12.4

Steps to Reproduce:

1. Install "Python" extension 
2. Create virtualenv and launch vs code from terminal when virtualenv is activated
3. Create settings.json to specify path to python executable 

```
{
    "python.pythonPath": "${workspaceRoot}/venv/bin/python",
    "python.autoComplete.extraPaths": [
        "${workspaceRoot}/venv/lib/python3.6/site-packages"
    ]
}

```

Autocomplete for custom python modules (e.g. numpy) has a 2 seconds delay. But autocomplete for native modules is speedy. 

Is there a indexing option I can set to speed up the auto complete of custom modules ?

_Copied from original issue: Microsoft/vscode#25130_

**Comment by LordAmit** [comment]
Apparently, there is. it is `python.autoComplete.preloadModules`, which should be used in workspace settings.

Does not work for me though. In fact, takes more than 6-10 seconds for me to load auto completion. 
I also followed the steps you mentioned. I should mention that my VSCode is 1.13.1 and the OS is Ubuntu 17.04.

**Comment by DonJayamanne** [comment]
Closing in favor of https://github.com/DonJayamanne/pythonVSCode/issues/581
