### ISSUE TITLE
Feature suggestion: run unit tests on save

### ISSUE THREAD

**Issue by tunebird** [DonJayamanne/pythonVSCode#905]
Hi!

I really like the integration with pytest and other unit testing frameworks, but one feature that would make it even better in my opinion is an editor setting to run the tests every time a .py source file is modified.

I'd be happy to have a go at submitting a pull request if it would be a useful feature and it's not too hard to implement.

**Comment by DonJayamanne** [comment]
Sure thing why don't you proceed with a PR. We can't make this feature optional.
