### ISSUE TITLE
pylint and autopep8 do not work on the linux subsystem for windows

### ISSUE THREAD

**Issue by StarGazerM** [DonJayamanne/pythonVSCode#906]
## Environment data
VS Code version:  1.11.2
Python Extension version:  Python
Python Version:   3.5.3
OS and version:    windows 10 1607 ubuntu  subsystem  

## Actual behavior
I set my pythonPath ,pyenv path and pylint path to the linux subsystem for windows, but the autopep8 and the pylint do not work    (TwT)√~
## Expected  behavior
use the autopep8 and the pylint in the ubuntu on win
## Steps to reproduce:  
-  set the settings.json
-  restart vscode but it doesn't have effect

## Settings  
  settings.json:   
```json
{
    "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe",
    "python.pythonPath": "C:\\Users\\56423\\AppData\\Local\\lxss\\home\\StarGazer\\.pyenv\\shims\\python",
    "python.venvPath": "C:\\Users\\56423\\AppData\\Local\\lxss\\home\\StarGazer\\.pyenv\\bin\\pyenv",
    "python.linting.pylintPath": "C:\\Users\\56423\\AppData\\Local\\lxss\\home\\StarGazer\\.pyenv\\shims\\pylint",
    "python.formatting.autopep8Path": "C:\\Users\\56423\\AppData\\Local\\lxss\\home\\StarGazer\\.pyenv\\shims\\autopep8"
}
```   
## Logs

Output from ```Console window``` (Help->Developer Tools menu)
```
linter pylint is not installed
```

**Comment by diablodale** [comment]
I tried also using slightly different settings. Then looked at the code here. Some changes will need to be made in the extension to accommodate using pylint within WSL.

For example, at https://github.com/DonJayamanne/pythonVSCode/blob/4a8319e0859f2d49165c9a08fe147a647d03ece9/src/client/linters/pylint.ts#L47 the extension runs the EXE which has been defined as pylint. One thing the external doesn't do is adjust the path to the file to lint. The code today would pass "C:\myfile.py". Instead, it needs to pass "/mnt/c/myfile.py"

A holistic approach to this is likely needed and some utility functions to handle both calling the subsystem and adjusting paths.

**Comment by DonJayamanne** [comment]
Closing in favor of https://github.com/DonJayamanne/pythonVSCode/issues/534 (to add proper support for WSL)
