### ISSUE TITLE
Sometimes ctag is unavailable

### ISSUE THREAD

**Issue by 1st** [DonJayamanne/pythonVSCode#910]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: MacOS 10.12.4 (Darwin x64 16.5.0)
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.3|;

---

## Steps to Reproduce:

I found the case where `ctags` doesn't writes file to the disk. I use mounted via sshfs folder, and tried to use it as a workspace. It created `.vscode/` folder in the workspace folder and appropriate `settings.json` file inside it. But file `ctags` wasn't created. To fix this problem I have changed config variable to place `ctags` file into the `~/.vscode/ctags` globally.

My idea was to have multiple workspaces and load appropriate `ctags` database. But I have access only to the full path to the working directory, and doesn't have variable with the workspace name. Possible solution is to add variable name like `${workspace_name}` to use it in the settings.

Maybe you can point me how to use multiple workspaces in the VS Code. It can help to specify the path where to store settings. Because in current implementation I need to have global `ctags` that isn't the solution where I need to work with multiple workspaces/projects.

Thanks.

**Comment by 1st** [comment]
Where can I install new version of the plugin to test it?

Also, is it possible to place the ctag files inside the centralized directory, not only in the project directory? Because I use a mounted sshfs it's too slow to write crags cache file into the remote file system. It will be good if your plugin will work fine with the Project plugin. In this case I can create few projects and per each project save ctag file inside ~/.vscode/project_name/ctag

What do you think about this improvement? Is it possible to get settings fron another installed plugin to use them in your plugin? It will be super fine for me!

**Comment by DonJayamanne** [comment]
You can change the settings in settings.json and point it to a central location. That would work, yes.

**Comment by DonJayamanne** [comment]
A new version will be released within a day or two.

**Comment by 1st** [comment]
Hi Don,

To make this setting - I need to create a settings.json file for each workspace that is not cool, because it will place file inside the .vscode directory inside the working directory, not a global one. Will be good to place cache files automatically in the proper place to the global ~/.vscode directory vasrd on the project name

**Comment by DonJayamanne** [comment]
>To make this setting - I need to create a settings.json file for each workspace that is not cool,  

You can add your settings into the global settings.json (user settings).

**Comment by 1st** [comment]
Thank you Don, but it looks that I can do only one global setting for all projects. But I need somehow create separate cache file for each project. Because when I will open new project - old cache will be owerwtiten by new one.

**Comment by DonJayamanne** [comment]
Unfortunately there's no way around that.
