### ISSUE TITLE
Ctags generates wrong path to the file

### ISSUE THREAD

**Issue by 1st** [DonJayamanne/pythonVSCode#912]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: MacOS 10.12.4 (Darwin x64 16.5.0)
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.3|;

---

## Steps to Reproduce:

I found that when enabled `ctags` generates list of files, but path to them is wrong. I use a symlink to the workspace directory. Internally it transforms it to the absolute path,  but this path contains two times the same leading part. In my case I have all files starting from `/private/tmp/private/tmp/workstation_code/`. Correct path is: `/private/tmp/workstation_code/`.

I think that you can avoid translation from the symlink to the absolute path and use it as it. Because for me it's better to use relative "symlinked" path in address instead of absolute one.

Second. Please check, looks like that the leading path of the path to the file if doubled and it creates the problem. When I trying to select any file from the autocomplete - it tells that this file not found.

**Comment by 1st** [comment]
Any ideas why it happens and how to fix it? Looks like it's wrong path conversation. Instead of replacing parh - it appends the absolute path to the end of the real path.

**Comment by DonJayamanne** [comment]
Please could you test the latest version of VS Code and let me know how it goes.

**Comment by 1st** [comment]
Checked. The same error still exists after update VSCode to tge latest version and rebuild the ctags file.

Pressing Command+T and type a class name. Then pressing Enter. Appears the error.

**Comment by 1st** [comment]
Don't know why - but `Go to symbol in Workspace` doesn't work anymore. I have created a new simple project with few files and few functions in them. Restarting VSCode didn't help. Why ideas how to debug the source of the problem?

**Comment by enali** [comment]
I have the same problem. When go to symbol in workspace, prompt `Unable to open xxx.py:  File not found (d:\PycharmProjects\ctf\.vscode\ctf\hello.py`. I think the path is wrong joined. open the `.vscode/tags` file, I found the symbol path is relative path, such as ` test_hello.py	ctf\test\test_hello.py	1;"	kind:file	line:1`. Maybe I should run the ctags with some args, I guess.

**Comment by 1st** [comment]
I see that in the previous release it was fixed an issue with creating `.vscode` folder if it doesn't exists. Also I found that currently `ctags` file generates correctly and I can jump to file without issues. Looks like this issue can be closed.

**Comment by DonJayamanne** [comment]
Yay
