### ISSUE TITLE
python debugger doesn't work after input function

### ISSUE THREAD

**Issue by githubuserdavid** [DonJayamanne/pythonVSCode#914]
## Environment data
VS Code version:  1.11.2
Python Extension version:  0.6.3
Python Version:   3.6.4
OS and version:    Windows 10  ver:10.0.14393

## Actual behavior
the Python debugger does nothing after input anything
and all local variables disappeared.
,weird
## Expected  behavior
//
## Steps to reproduce:  
sample code:
a = input('input something')
print(a)
print(a)

then debug

## Settings  
Your launch.json (if dealing with debugger issues):  
```
{
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
```   
Your settings.json:   
```
{
}
```   
## Logs
Output from ```Python``` output panel  
```
##########Linting Output - flake8##########
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
nothing
```

**Comment by DonJayamanne** [comment]
Please check the following:  
https://github.com/DonJayamanne/pythonVSCode/wiki/Capture-User-Input-via-input()-or-raw_input()  
https://github.com/DonJayamanne/pythonVSCode/issues/853#issuecomment-292146732  
https://github.com/DonJayamanne/pythonVSCode/issues/907#issuecomment-296812122  
There are other similar issues with the same solution.
