### ISSUE TITLE
Rightclick -> Run selection in Python Terminal does not work with indented lines

### ISSUE THREAD

**Issue by zenkzz** [DonJayamanne/pythonVSCode#916]
## Environment data
VS Code version:  1.11.2
Python Extension version:  0.6.3
Python Version:   3.5.2
OS and version:   Windows 7 Professional Version 6.1 Build 7601: Service Pack 1)

## Actual behavior
IndentationError
## Expected  behavior
Line executed like in RStudio or Visual Studio where the indent is deleted by the system. In both editors multiple lines with indentation from function or for call could be selected and executed.
## Steps to reproduce:  
- Write the following code in py file:
```
"""Module"""
def my_func():
    """Function a"""
    print("Hello World")
```

- Put cursor to print("Hello World")
- Rightclick -> Run selection in Python Terminal

![image](https://cloud.githubusercontent.com/assets/1749072/25440160/d8fd5018-2a9e-11e7-9af2-6a4a946dd80a.png)

**Comment by DonJayamanne** [comment]
Unfortunately this is one of those issues that can't be fixed.  
If for instance you had a if condition with some code, then you'd expect the indentation to be preserved.  Hence its not possible to determine whether you're running something that needs to be indented or not.

The solution I can suggest is for you to select the text to be run in the terminal, i.e. select the text ```print("Hello World")``` without the leading space.
