### ISSUE TITLE
Python 3.6 + variable annotations, no autocomplete

### ISSUE THREAD

**Issue by Tinche** [DonJayamanne/pythonVSCode#918]
## Environment data
VS Code version:  1.11.2
Python Extension version:  0.6.3
Python Version:   3.6.1
OS and version:    OS X El Capitan and Ubuntu Zesty

Autocomplete for class fields stops working if the field is annotated (a new 3.6 feature).

A small reproducer:
```
class A:
    a = 0


class B:
    b: int = 0


A().a  # -> Autocomplete works
B().b  # -> Autocomplete doesn't work
```

**Comment by DonJayamanne** [comment]
Unfortunately this is a problem with the [Jedi library](https://github.com/davidhalter/jedi)  
I could use the latest version which seems to fix this, however, it breaks a who lot more features something as simple as code navigation.
Will keep this open until the library is in a stable enough state.

**Comment by Tinche** [comment]
Thanks for the update!
