### ISSUE TITLE
but f5 do not debug python

### ISSUE THREAD

**Issue by zengkefu** [DonJayamanne/pythonVSCode#92]
{
	"version": "0.2.0",
	"configurations": [
		{  
			"name": "启动扩展",
			"type": "extensionHost",
			"request": "launch",
		    "runtimeExecutable": "${execPath}",
			"stopOnEntry":true,
			"args": [
				"--extensionDevelopmentPath=${workspaceRoot}"
			],
			"sourceMaps": true,
			"outDir":"${workspaceRoot}"
			
   
			
		}
	]
}

tasks.json
{
	// See http://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "0.1.0",
	"command": "c:\\python34\\python.exe",
	"isShellCommand": true,
	"args": ["${file}"],
	"showOutput": "always"
}

[e:/test/.vscode]: 无法读取文件 e:/test/.vscode/package.json: ENOENT: no such file or directory, open 'e:\test\.vscod

vs code :version :1.0.1

but f5 do not debug python

can you give a newer document about lannch.json ???

**Comment by DonJayamanne** [comment]
Please check out the following to learn how to debug using Vs Code 
https://code.visualstudio.com/docs/editor/debugging
