### ISSUE TITLE
Intellisense interrupting typing in strings

### ISSUE THREAD

**Issue by abrakidabra** [DonJayamanne/pythonVSCode#921]
## Environment data
VS Code version:  1.11.2
Python Extension version:  0.6.3
Python Version:   2.7.13
OS and version:    MacOS Sierra 10.12.4

## Actual behavior
When putting a full stop at the end of a line inside triple quotes the intellisense dialog pops up and suggests a bunch of options. I then hit the enter key to go to the next line but instead of going to the next line it adds the first suggestion in the intellisense dialog to the string.

## Expected  behavior
No intellisense inside triple quoted strings. It's very clunky to have to hit the escape key at the end of every line with a full stop on it.

## Steps to reproduce:  
1. Type this code. When you get to the first full stop at the end of the line it will suggest a bunch of possible options to insert.
```python
print """
There's somethign going on here.
With the three double-quotes.
"""
```

## Settings  
Workspace Settings:
```json
{
    "python.pythonPath": "/Data/Development/Python/VirtualEnvironments/vscode/bin/python2.7",
    "python.linting.pylintPath": "/Data/Development/Python/VirtualEnvironments/vscode/bin/pylint",
    "python.formatting.autopep8Path": "/Data/Development/Python/VirtualEnvironments/vscode/bin/autopep8",
    "editor.detectIndentation": false,
    "editor.insertSpaces": true,
    "editor.rulers": [
        80
    ],
    "editor.renderIndentGuides": true
}
```   
User Settings:
```json
{
    "editor.fontFamily": "Liberation Mono",
    "editor.fontSize": 11,
    "editor.autoClosingBrackets": false,
    "editor.renderWhitespace": "boundary",
    "editor.insertSpaces": false,
    "editor.detectIndentation": true,
    "editor.renderIndentGuides": true,
    "editor.formatOnType": true,
    "editor.formatOnPaste": true,
    "editor.trimAutoWhitespace": true,
    "editor.codeLens": false,

    "terminal.integrated.fontFamily": "Liberation Mono",
    "terminal.integrated.fontSize": 10

    , // Migrated from previous "File | Auto Save" setting:
    "files.autoSave": "afterDelay",
    "files.autoSaveDelay": 2000,

    "path-intellisense.showHiddenFiles": true,
    "path-intellisense.autoSlashAfterDirectory": true,

    "typescript.disableAutomaticTypeAcquisition": true,
    "window.zoomLevel": 0,
    "git.path": "/usr/local/bin/git",
    "workbench.colorTheme": "Visual Studio Dark",
    "workbench.iconTheme": "vs-nomo-dark",
    "[cpp]": {
        "editor.quickSuggestions": false
    },
    "[c]": {
        "editor.quickSuggestions": false
    }
}
```
![screen shot 2017-04-28 at 09 56 28](https://cloud.githubusercontent.com/assets/20607891/25508989/fe3b7e30-2bf8-11e7-9043-e72c6203583c.png)

**Comment by abrakidabra** [comment]
After doing a little more testing today I've noticed this is happening for all strings. Any time I put a '.' character in a string I get an intellisense dialogue.

**Comment by abrakidabra** [comment]
As an extra bit of info this only happens when coding in Python. The other languages do not have this behaviour.

**Comment by DonJayamanne** [comment]
Other languages too have this issue. Will check if there's a solution.  
https://github.com/Microsoft/vscode/issues/2461

**Comment by DonJayamanne** [comment]
https://github.com/Microsoft/vscode/issues/9504#issuecomment-299155239

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#110
