### ISSUE TITLE
Wiki Issues

### ISSUE THREAD

**Issue by noahleigh** [DonJayamanne/pythonVSCode#922]
(Chrome 58)

Many pages have their header tags broken, so they appear as `###Header`:

- https://github.com/DonJayamanne/pythonVSCode/wiki/Linting
- https://github.com/DonJayamanne/pythonVSCode/wiki/Formatting
- https://github.com/DonJayamanne/pythonVSCode/wiki/Refactoring
- https://github.com/DonJayamanne/pythonVSCode/wiki/Debugging

And possibly others.

---
On the [Debugging ](https://github.com/DonJayamanne/pythonVSCode/wiki/Debugging
) page, the sample for **args**:

1. Doesn't have any sample `args`
2. has an invalid value for pythonPath.  Should be `${config.python.pythonPath}`
3. Doesn't have JSON syntax highlighting

**Comment by DonJayamanne** [comment]
Fixedc, thanks
