### ISSUE TITLE
Remote Debugging Library Functions 

### ISSUE THREAD

**Issue by waleedka** [DonJayamanne/pythonVSCode#924]
I'm using remote debugging (with ptvsd) to debug my Python 3.5 code running in a Docker container. For the most part it's working great, I can put breakpoints and step through the code. But I can't seem to step into library functions. The "step into" command works when stepping into a function defined in my source code file, but not on functions defined in a library I've imported. Further, if the library function calls into my code, the call stack shows "Unknown Source" (see image). 

I tried to add the "DebugStdLib" as explained [here](https://github.com/DonJayamanne/pythonVSCode/wiki/Debug-Library-Functions) but vscode complained that "debugOptions" is not an allowed property. I'm guessing it doesn't work with remote type of debugging?

## Environment data
VS Code version:  1.11.2
Python Extension version:  0.6.3
Python Version:  3.5.2
OS and version:   OSX 10.11.6
OS running in the Docker container: Ubuntu 16.04

![vscode](https://cloud.githubusercontent.com/assets/106472/25559702/d217aa98-2cf4-11e7-8106-dfe0be22aa03.png)

## launch.json
```javascript
        {
            "name": "Attach (Docker)",
            "type": "python",
            "request": "attach",
            // localRoot == remoteRoot. Folder in the docker container mapped to folder in host OS
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "${workspaceRoot}",
            "port": 8888,
            "secret": "my_secret",
            "host": "localhost",
            //      vscode didn't like me adding this property. Says property is not allowed
            //"debugOptions": [
            //  "DebugStdLib"
            //]
        }
```   

Any tips to get this working? Or is this not supported in vscode?

**Comment by DonJayamanne** [comment]
Yes, unfortunately debugging library functions won't work at this stage. Will look into this.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#111
