### ISSUE TITLE
Feature Request: Goto Python Object

### ISSUE THREAD

**Issue by slint** [DonJayamanne/pythonVSCode#928]
Sublime Text (w/ Anaconda extenstion) used to have a "Goto Python Object" command, where the user could type a full path to a Python Object (eg. `marshmallow.fields`) and the respective Python source file (if existed/possible) would be opened. Having such a "global" Goto Definition command would be very useful and would be even better if it was possible to get some auto-complete while typing the object path.

(I'm not sure if there is similar functionality already or some API call provided by Jedi for this...)

**Comment by DonJayamanne** [comment]
Have you tried the commands ```Go to symbol in file``` and ```Go to symbol in workspace``` ?
Also, how do you launch the "Goto Python Object" command?

**Comment by slint** [comment]
> Have you tried the commands Go to symbol in file and Go to symbol in workspace ?

`Go to symbol...` commands works perfectly fine for objects/definitions inside the file/workspace (because of `ctags` I assume). The `Goto Python Object` should work inside the `virtualenv` (or default python environment). I can achieve the equivalent effect in VSCode by manually typing in a Python file `from marshmallow import fields`, and then doing a `Go to Definition` call on the `fields` part of the line.

> Also, how do you launch the "Goto Python Object" command?

The command in Sublime Text could be called when viewing any `.py` file. From a brief look at its [source code](https://github.com/DamnWidget/anaconda/blob/86501a6b1299366d012079808cbddb29043b5e0d/commands/goto.py#L86-L98), it's implemented by prepending `import ` to the input string, asking for completions from Jedi and then calling the equivalent "Go to Definition" command on one of the results.
