### ISSUE TITLE
workspace interpreter setting isn't persistent (or is ignored sometimes?)

### ISSUE THREAD

**Issue by dmahugh** [DonJayamanne/pythonVSCode#931]
![vscodepythoninterpreter](https://cloud.githubusercontent.com/assets/1130262/25603261/f771a90e-2eae-11e7-88a7-04027c8a21b2.png)
## Environment data
VS Code version:  1.11.2
Python Extension version:  0.6.3
Python Version:   3.4.1
OS and version:   Windows 10 Enterprise 1607

## Actual behavior

The "select interpreter" functionality doesn't seem to work correctly. Here's something I go through many times each day ...

* I launch VS Code in my project folder, and it doesn’t see the installed packages in my project's virtual environment.
* I check workspace settings, and it's pointing to the correct interpreter.
* I go to "Python: Select Workspace Interpreter" and it shows the the correct interpreter is being used, but I go ahead and re-select the same one again.
* I re-start VS Code, and now it works correctly.
* After I work in a different project and come back, I have to go through these same steps again to get VS Code to recognize my imports.

## Expected  behavior
I would like to set the workspace interpreter and have this setting persist so that I don't have to set it again so often.

## settings.json
```json
{
    "python.pythonPath": "C:/Users/dmahugh/AppData/Local/Continuum/Miniconda3/envs/bottle-msgraph/python"
}
```

**Comment by DonJayamanne** [comment]
What linter are you using?
The problem is simple, the linter isn't installed in the above python environment.
Right now it is installed on your default python environment which is in your current path!!

**Comment by dmahugh** [comment]
Got it - so I need to install pylint in every virtual environment. I've done that and all seems well. I was misled by the fact it seemed to work sometimes but not others. Thanks.
