### ISSUE TITLE
Failed to Detect Jupyter Notebook created in non-default startupFolder

### ISSUE THREAD

**Issue by edward-agarwala** [DonJayamanne/pythonVSCode#934]
## Environment data
VS Code version:  1.12.0
Python Extension version:  Python 0.6.4 and Jupyter 1.1.2
Python Version:   3.6
OS and version:    Mac OS 10.11.6

## Actual behavior
`Failed to detect Jupyter Notebook. Please use 'Select Jupyter Notebook' command`
When running a cell and choosing to start up a new notebook given default startup folder, jupyter.notebook.startupFolder, has changed.
## Expected  behavior
Correctly detect the notebook created.
## Steps to reproduce:  
-  Set, "jupyter.notebook.startupFolder": "${workspaceRoot}/folder1/folder2"
-  Try to run a python cell
-  Choose `start a new notebook`

## Workaround
The jupyter notebook is successfully created in the correct folder. After getting the error, choose to connect to a local notebook. The cells then run correctly.

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
User
{    
    "python.jupyter.defaultKernel": "localhost:8888",
}
Workspace
{
    "jupyter.notebook.startupFolder": "${workspaceRoot}/folder1/folder2"
}
```   
## Logs
Output from ```Python``` output panel  
```
Failed to detect Jupyter Notebook. Please use 'Select Jupyter Notebook' command
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
What version of Jupyter (the package, not the extension) do you have installed?  
Are you using anaconda?

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/vscodeJupyter#46
