### ISSUE TITLE
Launched intepreter doesn't always exit when instance of VSCode terminates

### ISSUE THREAD

**Issue by vladsadovsky** [DonJayamanne/pythonVSCode#935]
## Environment data
VS Code version:  11.02
Python Extension version:  "dockerized" python2.7 (executes in a child container)
Python Version:   2.7
OS and version:   Ubuntu 16.04.02

## Actual behavior
Replacing path to python interpreter with dockerized version (intepreter executes in a standardized docker container) causes completion.py to never exits.On every instantiation of VSCode there are two new containers created and not destroyed on exit. 

## Expected  behavior
After VSCode process terminates all interpreters, launched by the current instance,  should exit.

Problem is in completion.py::watch() , line 584. When reading from standard input loop should check for zero length of the readline return in addition to catching exceptions. When _input.readline() returns empty string, it is time to exit.

Pull request submitted 
## Steps to reproduce:  
-  
Difficult to do outside full containerized build environment. 
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```

```   
Output from ```Console window``` (Help->Developer Tools menu)
```

```

**Comment by DonJayamanne** [comment]
Fixed with #936 
Thanks
