### ISSUE TITLE
Debug django application

### ISSUE THREAD

**Issue by thynquest** [DonJayamanne/pythonVSCode#937]
## Environment data
VS Code version:  1.12.0
Python Extension version:  0.6.4
Python Version:   3.5 or 3
OS and version:    Linux Ubuntu 16.04 LTS

## Actual behavior
I'm trying to launch a debug on a django application but the debug doesn't  start 

## Expected  behavior
the debug should be started

## Steps to reproduce:  
-  Configure the launch.json file and lauch de django configuration
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "PySpark",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "osx": {
                "pythonPath": "${env:SPARK_HOME}/bin/spark-submit"
            },
            "windows": {
                "pythonPath": "${env:SPARK_HOME}/bin/spark-submit.cmd"
            },
            "linux": {
                "pythonPath": "${env:SPARK_HOME}/bin/spark-submit"
            },
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Python Module",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "module": "module.name",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Integrated Terminal/Console",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "",
            "console": "integratedTerminal",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
        {
            "name": "External Terminal/Console",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "",
            "console": "externalTerminal",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
        {
            "name": "Django",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${workspaceRoot}/manage.py",
            "cwd": "${workspaceRoot}",
            "args": [
                "runserver",
                "--noreload"
            ],
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "DjangoDebugging"
            ]
        },
        {
            "name": "Flask",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config:python.pythonPath}",
            "program": "fully qualified path fo 'flask' executable. Generally located along with python interpreter",
            "cwd": "${workspaceRoot}",
            "env": {
                "FLASK_APP": "${workspaceRoot}/quickstart/app.py"
            },
            "args": [
                "run",
                "--no-debugger",
                "--no-reload"
            ],
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Flask (old)",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${workspaceRoot}/run.py",
            "cwd": "${workspaceRoot}",
            "args": [],
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Pyramid",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "args": [
                "${workspaceRoot}/development.ini"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "Pyramid"
            ]
        },
        {
            "name": "Watson",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${workspaceRoot}/console.py",
            "cwd": "${workspaceRoot}",
            "args": [
                "dev",
                "runserver",
                "--noreload=True"
            ],
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Attach (Remote Debug)",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "${workspaceRoot}",
            "port": 3000,
            "secret": "my_secret",
            "host": "localhost"
        }
    ]
}
```   
Your settings.json:   
 "python.linting.pylintEnabled": true,
    "python.pythonPath": "virtual env path to python3.5",
    "python.linting.lintOnSave": true,
    "python.linting.pylintArgs": [
        "--load-plugins",
        "--disable=W5101",
        "disable=C0111"
    ],

Output from ```Console window``` (Help->Developer Tools menu)
extensionHost.ts:285 [Extension Host] vscode-icons is active!
	index.js:40 [uncaught exception]: Error: read ECONNRESET
	onError @ index.js:40
	(anonymous) @ index.js:109
	emitOne @ events.js:96
	emit @ events.js:188
	window.onerror @ /usr/share/code/resources/electron.asar/renderer/init.js:124
	i.globals.onerror @ errorTelemetry.ts:64
	index.js:43 Error: read ECONNRESET
	    at exports._errnoException (util.js:1022)
	    at Pipe.onread (net.js:572)
	onError @ index.js:43
	(anonymous) @ index.js:109
	emitOne @ events.js:96
	emit @ events.js:188
	window.onerror @ /usr/share/code/resources/electron.asar/renderer/init.js:124
	i.globals.onerror @ errorTelemetry.ts:64
	events.js:160 Uncaught Error: read ECONNRESET
	    at exports._errnoException (util.js:1022)
	    at Pipe.onread (net.js:572)
	exports._errnoException @ util.js:1022
	onread @ net.js:572

Thank you for your help

**Comment by thynquest** [comment]
One more information: I am on django 1.10.6

Thank you again for your help

**Comment by intoCL** [comment]
@thynquest I have the same problem. Also submitted an issue [here](https://github.com/DonJayamanne/pythonVSCode/issues/954).

**Comment by thynquest** [comment]
Hello again, 
I've noticed something, the debug mode does not work if you work with a postgres. to be more precise, when your postgres database has no tables the debug mode does work, but as soon as you create a table the debug mode doesn't work anymore. and if you work with sqlite, the debug mode does work. I don't know if any other database engine has the same problem but I've noticed it with postgres sql

**Comment by thynquest** [comment]
Hello 
any news on this ??

**Comment by DonJayamanne** [comment]
Sorry, been busy looking into other issues. Will try to give this some attention this week.

**Comment by thynquest** [comment]
Ok thank you. just to remember all you have to do to test it is to start a new django project, change the settings.py file by replacing the connection to a sqlite db with a connection to a postgresdb, configure the lauch.json file, be sure that your "python.pythonPath" property points to your virtualenv python and launch the django debug configuration. You'll see that the debug does not start.

thank you again for your help.

**Comment by thynquest** [comment]
Hello there 
I've checked out the latest version of the python module and it does not seems to fix the problem on linux. did you give some attention lately ? 
thank you for your help

**Comment by DonJayamanne** [comment]
Hi @thynquest , I'm sorry for never getting back to you on this. I'd like to help you resolve this issue if it still persists. Please do let me know if it does. Once again, sorry for the delay in getting back.

**Comment by thynquest** [comment]
Hi @DonJayamanne 
I still encounter the problem on linux last time I checked (yesterday) . I hoped the latest vscode update would fix the issue but it didn't.

**Comment by thynquest** [comment]
If you need more infos let me know

**Comment by DonJayamanne** [comment]
Thanks will check this out,

**Comment by DonJayamanne** [comment]
@thynquest would you be able to upload a sample code that I could use to test this out at my end.

**Comment by marcoarruda** [comment]
Is it solved? Because I can't debug any Django project in VScode
I'm using Ubuntu 14.04

Visual Studio Code
Version 1.18.1
Commit 929bacba01ef658b873545e26034d1a8067445e9
Date 2017-11-16T18:34:22.110Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by thynquest** [comment]
Not for the moment .. at least I haven't received any feedback on this bug .. meanwhile I am using ipdb.

**Comment by DonJayamanne** [comment]
Hi everyone, the extension is no longer managed in this repo. it is now managed in the [Microsoft repo](https://github.com/Microsoft/vscode-python/issues). 
Please check if your issues exist there, if no please create a new one.
