### ISSUE TITLE
matplotlib.pyplot is not not available in a Virtual Environment

### ISSUE THREAD

**Issue by PFSWcas** [DonJayamanne/pythonVSCode#938]
## Environment data
VS Code version:  1.12.1
Python Extension version:  0.6.4
Python Version:   3.5
OS and version:    Ubuntu 16.04 

## Actual behavior
plt.plot(x,y) is not available in a virtual environment. 

The code is shown below:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
x = np.arange(0, 5, 0.1);
y = np.sin(x)
plt.plot(x, y)
plt.show()

In my PC, I installed anaconda2 and a virtual environment  with python 3.5 is created. I activate the Virtual environment from my Terminal/Command Window and then launch VS Code. But the matplotlib.pyplot is  not available. However, in the  python 2.7 environment, matplotlib.pyplot is available.

What can I do to fix this? Thanks very much!

**Comment by DonJayamanne** [comment]
Can you confirm matplotlib is installed in your virtual environment?  
Also can you try setting the path to the python interpreter in the workspace ```settings.json```.

**Comment by PFSWcas** [comment]
Hi,@DonJayamanne. I can confirm that matplotlib has been installed in my virtual environment. When I divid the program into some cells and run a cell, the matplot lib. pyplot can work. However, when the program is operated in the debug mode, the matplotlib.pyplot is not available

**Comment by DonJayamanne** [comment]
can you try setting the path to the python interpreter in the workspace settings.json

**Comment by DonJayamanne** [comment]
That will fix the issue

**Comment by PFSWcas** [comment]
Sorry, @DonJayamanne , it is fault. My matplotlib version was 2.0.1, so the dependent qt version was 5.0. The problem is caused by the qt version not the pythonvscode. I removed matplotlib 2.0.1 and install maplotlib 1.5.1, then pythonvscode and matplotlib works fine. Thank you very much!

**Comment by DonJayamanne** [comment]
Cheers
