### ISSUE TITLE
Auto-Indentation breaks down in VS Code version 1.12.1

### ISSUE THREAD

**Issue by kushim6371** [DonJayamanne/pythonVSCode#939]
## Environment data
VS Code version:  1.12.1
Python Extension version: 0.6.4 
Python Version:  3.6.1
OS and version:    Windows 10 x64

## Actual behavior
Auto-indentation doesn't work in cases of line continuation

![default](https://cloud.githubusercontent.com/assets/27528988/25748350/59bef1fc-3170-11e7-8a2d-3c795f0f727a.PNG)

Didn't encounter this problem before version 1.12.

## Settings  

settings.json:   
```json
{
    "editor.formatOnType": true,
}
```

**Comment by DonJayamanne** [comment]
This was never a feature of the extension. Please could you uninstall the extension and confirm that it works in the older version of VS Code.
