### ISSUE TITLE
Not all keywords and built-in functions are highlighted

### ISSUE THREAD

**Issue by MikeYaco** [DonJayamanne/pythonVSCode#94]
As the title says, not all keywords and built-in functions are highlighted.

For instance,

![image](https://cloud.githubusercontent.com/assets/6750444/14755534/9ebcf9a8-08a8-11e6-9fe8-3bebae59fe41.png)

neither 'in' nor 'enumerate' have any syntax highlighting.

**Comment by DonJayamanne** [comment]
Highlighting is not a feature supported by this package. Please  use https://marketplace.visualstudio.com/items?itemName=magicstack.MagicPython.
