### ISSUE TITLE
Feature request: CodeLens

### ISSUE THREAD

**Issue by IAmLFish** [DonJayamanne/pythonVSCode#943]
I would look forward to see a feature like `python.referencesCodeLens.enabled`

i.e. showing an annotation above all class- and method names respectively that indicates the number references and shows those references upon clicking the annotation link.
This already exists e.g. for typescript.

What do you think?

**Comment by DonJayamanne** [comment]
Could be done, but there could be a performance impact as well. Will enable this as an opt in feature.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#115
