### ISSUE TITLE
Debugger: Passing arguments adds a white space

### ISSUE THREAD

**Issue by StefanoD** [DonJayamanne/pythonVSCode#946]
## Environment data
VS Code version:  1.12.1
Python Extension version:  python
Python Version:   3.5.2
OS and version:    Ubuntu 16.02
Related to issue [#945](https://github.com/DonJayamanne/pythonVSCode/issues/945)

## Actual behavior

Passing an argument add an white space before the argument

```
 foo
 bar
```

## Expected  behavior

Passing the arguments on the command line doesn't add a white space:

```
stefano@stefano-linux:~$ python3 args_parse.py -f foo --b bar
foo
bar
```

## Steps to reproduce:  
```python
import argparse

parser = argparse.ArgumentParser(description='Process some integers.')
parser.add_argument('-f', help='foo help')
parser.add_argument('-b', help='bar help')

args = parser.parse_args()
print(args.foo)
print(args.bar)
```

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
{
            "name": "Python",
            "args": [
                "-f foo",
                "-b bar"
            ],
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }
```   
Your settings.json:   
```json
{
  "python.pythonPath": "/usr/bin/python3"
}
```   
## Logs
Output from ```Python``` Output panel  
```
 foo
 bar
```

**Comment by DonJayamanne** [comment]
Try the following:
```json
{
            "name": "Python",
            "args": [
                "-f", "foo",
                "-b", "bar"
            ],
```

Each argument is a separate entry, not together.
For instance in the terminal you aren't passing "-f foo" as a single parameter within quotes, instead they're two separate arguments.
