### ISSUE TITLE
Memory Leak and Loop 

### ISSUE THREAD

**Issue by ppanhoto78** [DonJayamanne/pythonVSCode#947]
The bug is described at:
https://github.com/Microsoft/vscode/issues/25796

With versions and steps to reproduce

Hello.

I was starting to write a small script with a swig library. Quickly, VSCode started to consume all memory and all swap memory until I had to reboot. I'm using VSCode 1.11.2 and OpenSuSE leap 42.1

Steps to Reproduce:

Install quickfix-python
$ sudo pip install quickfix

start a project

type the script bellow.

#!/usr/bin/env python
import quickfix

class ClientApplication(quickfix.Application):
	def __init__(self, server):
		super(ClientApplication, self).__init__()
in my case, when I trigger autocompletion within the module quickfix, that is enough to cause the loop.

Extensions:
C/C++ 0.11.0
C# 1.9.0
C++ Intellisense 0.2.1
Mono Debug 0.15.5
Python 0.6.3

**Comment by DonJayamanne** [comment]
This issue was moved to davidhalter/jedi#923
