### ISSUE TITLE
Execute me,I want to know how to configure it in Ubuntu??

### ISSUE THREAD

**Issue by hippieZhou** [DonJayamanne/pythonVSCode#95]
I'm a Ubuntu lover and I want to konw how to configure it in VS Code to code my python??

**Comment by DonJayamanne** [comment]
Hi, sorry for the delay. I'll setup a ubuntu env soon and figure this out.

**Comment by hippieZhou** [comment]
Thank you so much !

**Comment by DonJayamanne** [comment]
Hi @hippieZhou , i'm in the process of setting up Ubuntu. What exactly do you want to configure?

**Comment by RobsonTargz** [comment]
I'm using Ubuntu 16.04 and this extension works like a charm... what are you talking about?
You just should install it, enable or disable in settings.json what you want and install the dependencies with pip. If you are using venv, remember to run the vscode with venv activaded.
