### ISSUE TITLE
ValueError or typeError information does not show in the DEBUG CONSOLE

### ISSUE THREAD

**Issue by PFSWcas** [DonJayamanne/pythonVSCode#951]
## Environment data
VS Code version:  1.12.1
Python Extension version:  0.6.4
Python Version:   python 3.5
OS and version:    Ubuntu 16.04 64 bits

## Actual behavior
When I debug the program, the error information does not show in the DEBUG CONSOLE after the debug process terminated  when an error exits in the function imported from other python file. So, to get the error information, I have to divide the program into some cells, and run each cell to get the error information about my program.

How can I fix this and get the error information directly from the debug console?

**Comment by DonJayamanne** [comment]
@PFSWcas Apologies in not getting back to you on this issue. 
Were you able to get this to work?
