### ISSUE TITLE
.pyi stub files

### ISSUE THREAD

**Issue by fredrikaverpil** [DonJayamanne/pythonVSCode#952]
## Environment data
VS Code version:  Version 1.12.1 (1.12.1)
Python Extension version:  0.6.4
Python Version:   3.5.x
OS and version:    macOS, Windows, Linux

Is it possible to somehow use .pyi files with this extension?

**Comment by DonJayamanne** [comment]
Closing as this is an upstream issue. as today intellisense is supported by the Jedi library. 
https://github.com/davidhalter/jedi/issues/839
