### ISSUE TITLE
Wrong intellisense icons for variables.

### ISSUE THREAD

**Issue by AndyBay** [DonJayamanne/pythonVSCode#958]
## Environment data
VS Code version:  1.12.1
Python Extension version:  0.6.4
Python Version:   3.6.1
OS and version:    Windows 10

Currently (as seen under), arguments are using the "variable" icon and class variables are using the "reference" icon.
![intellisense_pre_change_1](https://cloud.githubusercontent.com/assets/1170184/26025013/13f129cc-37df-11e7-950a-8de3e17bb5e7.png)
![intellisense_pre_change_2](https://cloud.githubusercontent.com/assets/1170184/26025017/18fbcc38-37df-11e7-8b6c-fd1094d5a7fc.png)

If we take that the icons for intellisense in Typescript is correct, and do following changes to the `out\client\providers\jediProxy.js` file.
#### Before:
`pythonVSCodeTypeMappings.set('value', vscode.CompletionItemKind.Value);`
`pythonVSCodeTypeMappings.set('variable', vscode.CompletionItemKind.Variable);`
#### After:
`pythonVSCodeTypeMappings.set('value', vscode.CompletionItemKind.Field);`
`pythonVSCodeTypeMappings.set('variable', vscode.CompletionItemKind.Property);`

![intellisense_post_change_1](https://cloud.githubusercontent.com/assets/1170184/26025164/91c7a1a8-37e1-11e7-916d-7c5c012988fe.png)
![intellisense_post_change_2](https://cloud.githubusercontent.com/assets/1170184/26025167/960a54fe-37e1-11e7-88b2-9f6d84fbcc6c.png)

This change "fixes" it as far as I can tell, except for the fact that both "variables" and "class variables" use the same icon when instead they should be `variables => Variables` and `class variables => Field`.

Also found these comments in the file :)
`// What's this, can't remember,`
 `// Great example of poorly written code (this whole file is a mess)`

**Comment by DonJayamanne** [comment]
@AndyBay Apologies for never getting back to you on this.
I've been too busy looking into other issues and managed to over look something simple as this.
I'll look into this asap and try to include this into the next release.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#117
