### ISSUE TITLE
Internationalitazion using gettext

### ISSUE THREAD

**Issue by velascopja** [DonJayamanne/pythonVSCode#959]
## Environment data
VS Code version:  1.12.1
Python Extension version:  0.6.4
Python Version:   3.5
OS and version:   Kernel: Linux 4.4.0-77-generic(x86_64) Distribution: Pearl MATE 5.0 (elle)

Besides, I'm running Linux as a guest in a VirtualBox machine running on an OSX host

## Actual behavior
I'm testing internationalization with gettext and when I run the script from VS Code, I don't get the translated string. However if I run the script directly from a Linux terminal I get the right translated string.
Is this an issue or I'm missing something?
## Expected  behavior
Getting the right translated string when running message.py from VS Code.
## Steps to reproduce:  
-  Here's a screenshot of the execution of message.py from VS Code
<img width="2560" alt="running from vs code" src="https://cloud.githubusercontent.com/assets/5985649/26026768/100a7106-3802-11e7-83e1-37919e1a1f1c.png">
As you can see in the DEBUG CONSOLE, it's printing the same phrase that is in the print() sentence: "¡Hola a todos! En el capítulo ocho estoy aprendiendo todo acerca de las funciones."

-  Here's a screenshot of the execution of message.py from a Linux terminal
<img width="2560" alt="running from a linux terminal" src="https://cloud.githubusercontent.com/assets/5985649/26026801/b8f893e2-3802-11e7-80ac-9c5f20854878.png">
As you can see, it's printing the correct translated sentence: "Hello everyone! In chapter eight, I'm learning everything about functions."

## Settings  
Your launch.json (if dealing with debugger issues):  
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "PySpark",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "osx": {
                "pythonPath": "${env:SPARK_HOME}/bin/spark-submit"
            },
            "windows": {
                "pythonPath": "${env:SPARK_HOME}/bin/spark-submit.cmd"
            },
            "linux": {
                "pythonPath": "${env:SPARK_HOME}/bin/spark-submit"
            },
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Python Module",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "module": "module.name",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Integrated Terminal/Console",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "",
            "console": "integratedTerminal",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
        {
            "name": "External Terminal/Console",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "",
            "console": "externalTerminal",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
        {
            "name": "Django",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${workspaceRoot}/manage.py",
            "cwd": "${workspaceRoot}",
            "args": [
                "runserver",
                "--noreload"
            ],
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "DjangoDebugging"
            ]
        },
        {
            "name": "Flask",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config:python.pythonPath}",
            "program": "fully qualified path fo 'flask' executable. Generally located along with python interpreter",
            "cwd": "${workspaceRoot}",
            "env": {
                "FLASK_APP": "${workspaceRoot}/quickstart/app.py"
            },
            "args": [
                "run",
                "--no-debugger",
                "--no-reload"
            ],
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Flask (old)",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${workspaceRoot}/run.py",
            "cwd": "${workspaceRoot}",
            "args": [],
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Pyramid",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "args": [
                "${workspaceRoot}/development.ini"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "Pyramid"
            ]
        },
        {
            "name": "Watson",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${workspaceRoot}/console.py",
            "cwd": "${workspaceRoot}",
            "args": [
                "dev",
                "runserver",
                "--noreload=True"
            ],
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Attach (Remote Debug)",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "${workspaceRoot}",
            "port": 3000,
            "secret": "my_secret",
            "host": "localhost"
        }
    ]
}   
Your settings.json:   
{
    "python.pythonPath": "/usr/bin/python3.5"
}   
## Logs
Output from ```Python``` output panel  
----------Generating Tags----------
ctags --options=/home/velascopja/.vscode/extensions/donjayamanne.python-0.6.4/resources/ctagOptions --languages=Python --exclude=**/site-packages/** -o /home/velascopja/Documents/python_work/chapter_8/message/.vscode/tags .
   
Output from ```Console window``` (Help->Developer Tools menu)
//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Error: spawn git ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
d.logExtensionHostMessage	@	//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29

**Comment by zgoda** [comment]
i18n catalogs are loaded according to locale found in environment. How does `os.environ['LANG']` look in your debug console?

**Comment by velascopja** [comment]
Hi Jarek,

Please find below a screenshot of my Debug Console

<img width="2560" alt="debug console" src="https://cloud.githubusercontent.com/assets/5985649/26248708/bad1990c-3ca3-11e7-86fe-0c2d13b3a21a.png">

Thank you!

**Comment by velascopja** [comment]
Hi again,

sorry about opening this issue. It has nothing to be with the extension, it's all about the paths because I forgot to set cwd (in launch.json) to the directory of the .py executing, that's why Python was translating right when executing from the Linux terminal but not when executing from VS Code.
