### ISSUE TITLE
Infinite Loading...

### ISSUE THREAD

**Issue by cprogrammer1994** [DonJayamanne/pythonVSCode#960]
## Environment data
VS Code version:  1.12.1
Python Extension version:  0.6.4
Python Version:   3.5.1 (x86)
OS and version:    Win10 1703

## Actual behavior

![image](https://cloud.githubusercontent.com/assets/11232402/26031073/eef176f8-3866-11e7-9e3d-3c084ae591c2.png)

## Expected  behavior

detect type

## Steps to reproduce:  
-  create a folder `foo` on python's path.
-  create `foo/init.py`

```python
class Foo:
    def hello(self) -> str:
        return 'hello'

class Bar:
    def Foo(self) -> Foo: # please note that there is no problem if this is all lowercase
        return Foo.__new__(Foo)

def create_bar() -> Bar:
    return Bar.__new__(Bar)
```

## Settings  
Your settings.json:

A clean python install put on path `pylint 1.7.1` installed.

**Comment by DonJayamanne** [comment]
@cprogrammer1994 Closing as I believe this would have been an environment issue.
Please reopen if it persists.
Apologies for never getting back to you on this.
