### ISSUE TITLE
Code completion without __init__.py not working

### ISSUE THREAD

**Issue by yzinets** [DonJayamanne/pythonVSCode#967]
## Environment data
VS Code version:  1.12.2
Python Extension version:  
Python Version:   3.5.2
OS and version:    elementary OS 0.4.1 loki

Completion doesn't recognize classes, that placed in project subfolders 

## Settings  
Your settings.json:   
```{
    "workbench.colorTheme": "Visual Studio Light",
    "[cpp]": {
        "editor.quickSuggestions": false
    },
    "[c]": {
        "editor.quickSuggestions": false
    },
    "python.pythonPath": "python3",
    "python.linting.pylintArgs": ["--errors-only"],
    "editor.fontSize": 12
}
```

**Comment by cprogrammer1994** [comment]
You should not be able to load those either using import.

**Comment by cprogrammer1994** [comment]
> The `__init__.py` files are required to make Python treat the directories as containing packages; this is done to prevent directories with a common name, such as `string`, from unintentionally hiding valid modules that occur later (deeper) on the module search path. In the simplest case, `__init__.py` can just be an empty file, but it can also execute initialization code for the package or set the `__all__` variable, described later.

[docs](https://docs.python.org/3/tutorial/modules.html#packages)

**Comment by yzinets** [comment]
https://www.python.org/dev/peps/pep-0420/ says that from 3.3 onward, __init__.py should not be required for namespace packages. These files make it difficult to move around the project.

**Comment by cprogrammer1994** [comment]
what is the version of your pylint?

> Namespace packages are now supported by pylint. This includes both explicit namespace packages and implicit namespace packages, supported in Python 3 through PEP 420 ( source [here](https://media.readthedocs.org/pdf/pylint/latest/pylint.pdf) )

It does not work for me either I have pylint 1.7.1

**Comment by yzinets** [comment]
Ok, my pylint version also 1.7.1.
Is it pylint issue?

**Comment by cprogrammer1994** [comment]
`import A.B.C` produces an error but
`from A.B import C` does not.

The only file i have is `A/B/C.py`, I guess it is a pylint issue but it may already be fixed but not yet released
pylint 1.8.x will support PEP 420

**Comment by cprogrammer1994** [comment]
There was a  [pylint issue](https://github.com/PyCQA/pylint/issues/842) for this.

**Comment by yzinets** [comment]
It seems like pylint 1.8.0 not fixed this issue yet.

**Comment by cprogrammer1994** [comment]
With procmon I was able to detect that pylint successfully opens the file (in my case `A/B/C.py`) but the linting is not working.

![image](https://cloud.githubusercontent.com/assets/11232402/26274313/917f88d0-3d47-11e7-9220-dc73fcd54af0.png)

And the linter is aware of the existance of `MESSAGE`

![image](https://cloud.githubusercontent.com/assets/11232402/26274333/e80932c8-3d47-11e7-9a72-c324a505f7fa.png)

I get not error when accessing the `MESSAGE` constant of `C.py`

**Comment by DonJayamanne** [comment]
Sounds like an issue with pylint. Please report it on the pylint repo.

**Comment by zgoda** [comment]
Intellisense is not working as well for such packages. I start getting autocompletion as soon as I add __init__.py file to installed package (offending example: [picotui](https://github.com/pfalcon/picotui)).

If it comes to linters, flake8 works OK and has no problems.

**Comment by dsully** [comment]
I also had to add an __init__.py to my namespace package in order for Intellisense to work:

```
__path__ = __import__('pkgutil').extend_path(__path__, __name__)
```

Even though my interpreter is Python 3.5, and that file is not required per PEP420.

No pylint involved.

**Comment by SpaceMalamute** [comment]
Is there any news on this bug? 
Implicit import in VS Code + Python 3.6 doesn't seems to be working with Intellisense....

**Comment by tesmart** [comment]
Yes this is still broken. Can it be fixed?

**Comment by zgoda** [comment]
This extension is now Microsoft.

https://github.com/Microsoft/vscode-python

I don't see this issue in their repo.
