### ISSUE TITLE
Feature request: allow selecting interpreter from list of available virtualenvs

### ISSUE THREAD

**Issue by zgoda** [DonJayamanne/pythonVSCode#968]
I work almost exclusively in virtualenvs and I'd like to be able to select interpreter from list of virtualenvs if both `workon` command and `WORKON_HOME` envvar exist.

`workon` is shell command installed by [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/en/stable/). When invoked without argument it lists available virtualenvs under its control, in alphabetical order:

```
$ workon
bde
brewlog
cocos
...
tsp
twt
wsm
yg01
```

Now I have to set complete path to interpreter in form of `$WORKON_HOME/<envname>/bin/python`. An alternative is to get virtualenvs by listing subdirs of `$WORKON_HOME` (this is exactly what `workon` does).

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#118
