### ISSUE TITLE
Feature Request: Unit Testing: Clear Output Window before every Run

### ISSUE THREAD

**Issue by RAbraham** [DonJayamanne/pythonVSCode#969]
Hi,

Currently, when I run `Run Current Unit Test File` multiple times, the output gets appended to the `Output` tab. Is it possible to clear the `Output` tab every time I run a unit test configuration so that I only see the results of the current run. Right now, I have to execute `Clear Output` every time before running the tests. 

I give `Run Current Unit Test File` as an example. I would love to see the same behaviour for all the different run configurations.

If you prefer the existing behaviour, then perhaps, like in Code Runner, have a setting?
```
    "code-runner.clearPreviousOutput": true
```

Thanks for all your effort.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#119
