### ISSUE TITLE
shell env var in debug is invalid?

### ISSUE THREAD

**Issue by 1msoft** [DonJayamanne/pythonVSCode#97]
In shell:
some_var=something
export some_var
code .

goto debug, but some_var is invalid.

**Comment by xqliu** [comment]
There is a separate env setup section in launch.json
You can setup your environment variable in this section.
You can refer to #77 for detail.

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.9.6&pv=9.3&source=email_footer_2]
On Mon, Apr 25, 2016 at 11:20 PM, William E <notifications@github.com> wrote:
In shell:
some_var=something
export some_var
code .

goto debug, but some_var is invalid.
