### ISSUE TITLE
remote debugger doesn't start

### ISSUE THREAD

**Issue by rdiaz82** [DonJayamanne/pythonVSCode#971]
## Environment data
VS Code version:  
Python Extension version:  
Python Version:   0.6.4
OS and version:    OSX 10.12 (MacOS Sierra)

## Actual behavior
Impossible to start the debugger
## Expected  behavior
After press the play button the debugger should start
## Steps to reproduce:  
-  just click on start debug
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```{
            "name": "Attach (Remote Debug)",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}/www",
            "remoteRoot": "/var/www",
            "port": 3500,
            "secret": "",
            "host": "localhost"
        }
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```extensionHost.ts:285 [Extension Host] ---------------------------
d.logExtensionHostMessage @ extensionHost.ts:285
(anonymous) @ extensionHost.ts:139
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:285 [Extension Host] error jediProxy
d.logExtensionHostMessage @ extensionHost.ts:285
(anonymous) @ extensionHost.ts:139
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:285 [Extension Host] Error (error) Error: spawn /usr/local/bin/python3.5 ENOENT
d.logExtensionHostMessage @ extensionHost.ts:285
(anonymous) @ extensionHost.ts:139
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:285 [Extension Host] ---------------------------
d.logExtensionHostMessage @ extensionHost.ts:285
(anonymous) @ extensionHost.ts:139
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:285 [Extension Host] error jediProxy
d.logExtensionHostMessage @ extensionHost.ts:285
(anonymous) @ extensionHost.ts:139
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:285 [Extension Host] Error (error) Error: spawn /usr/local/bin/python3.5 ENOENT
d.logExtensionHostMessage @ extensionHost.ts:285
(anonymous) @ extensionHost.ts:139
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
messageService.ts:125 El proceso de adaptación del depurador finalizó inesperadamente``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
Please could you try using version 3.0.0 of the PTVSD instead of using the latest version. The latest version does not work with this extension.

**Comment by rdiaz82** [comment]
Hi!
I have tried with the 3.0.0 and now it works like a charm!! 👍 
Thanks!
