### ISSUE TITLE
Is it possible connect pytest assert failures to problems and code views?

### ISSUE THREAD

**Issue by hendrics** [DonJayamanne/pythonVSCode#973]
Hi. I was wondering if there's an option to integrate assert failures and problem/code view.

I managed to hack it together using `problemMatchers` for tasks. 
See the details example here
https://github.com/hendrics/python-vscode-pytest-example

Also i am looking for an ability to add links to the Output view to jump to the code. 
There are open issues on the vscode to address it via matchers. 

So overall copy pasting the `tasks.json` around is not scalable and i am wondering
if there's scope to add it to this extension unless it is already implemented.  

## Environment data
VS Code version:  Version 1.12.2 (1.12.2)
Python Extension version:  Version 0.6.4 (4 May 2017)
Python Version:   2.7.11
OS and version:    macOS El Capitan

**Comment by DonJayamanne** [comment]
Does sound like a good suggestion, however what's interesting is that this hasn't been up voted by anyone. I'll check this feature with my colleagues and get back to you. There could be other edge cases that need to be considered, e.g. what if the unit tests pass, we'll then need to ensure the problems disappear.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#120
