### ISSUE TITLE
Virtualenv unable to find installed packages

### ISSUE THREAD

**Issue by GrumpyMetalGuy** [DonJayamanne/pythonVSCode#974]
## Environment data
VS Code version:  1.12.2
Python Extension version:  0.6.4
Python Version:   2.7
OS and version:    Win 10 Creator's Update

## Actual behavior

Following the instructions and creating a virtual env, then installing files using pip, I'm unable to import any of the packages that were installed. I've set the pythonPath in launch.json to be "pythonPath": "${env:VIRTUAL_ENV}/Scripts/python.exe" but I'm not sure if there are any other env variables that I need to set. (Reading the docs implies that all I need to do is set the pythonPath, so I suspect I'm missing something obvious here)

## Expected  behavior

Able to import packages correctly

## Steps to reproduce:  
-  
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${env:VIRTUAL_ENV}/Scripts/python.exe",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
```   

```
settings.json:
{
    "python.formatting.provider": "yapf",
    "python.pythonPath": "${env:VIRTUAL_ENV}/Scripts/python.exe"
}
```

## Logs
Output from ```Python``` output panel  
```
##########Linting Output - pylint##########
************* Module prototype.cocos_demo
1,0,convention,C0111:Missing module docstring
1,0,error,E0401:Unable to import 'cocos'
4,0,convention,C0111:Missing function docstring
1,0,warning,W0611:Unused import cocos

--------------------------------------------------------------------

Your code has been rated at -6.00/10 (previous run: -6.00/10, +0.00)
```   

Console output:
```
[Extension Host] Error (error) Error: spawn ${env:VIRTUAL_ENV}/Scripts/python.exe ENOENT
d.logExtensionHostMessage @ extensionHost.ts:285
(anonymous) @ extensionHost.ts:139
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

**Comment by DonJayamanne** [comment]
Please confirm you have pylint installed in the above virtual environment. I looks like you don't.

**Comment by GrumpyMetalGuy** [comment]
Yes, that was it indeed. Many thanks for the advice and the great plugin!
