### ISSUE TITLE
Oddity with wildcard import

### ISSUE THREAD

**Issue by arpruss** [DonJayamanne/pythonVSCode#975]
## Environment data
VS Code version: 1.12.2
Python Extension version:  0.6.4
Python Version: 3.6.1
OS and version: Windows 10   

## Actual behavior
I have two files. beta.py defines two empty classes, `alpha` and `beta`. 

gamma.py does `from beta import *` in the first line. With the cursor on the next line, autocomplete picks up the `alpha` symbol but not the `beta` one. However, if after `from beta import *` I type in any line of code, e.g., `print()`, then autocomplete will pick up both symbols in the next line. And then sometimes later it will stop picking up `beta` again. 

The whole behavior is really, really strange. If the file that I `import *` from defines a lot of stuff, then autocomplete picks up more and more symbols the more and more code there after the `import` line.

**Comment by arpruss** [comment]
Replacing `pythonFiles/{preview,release}/jedi/*` with the current github version of the jedi library fixes the problem.

**Comment by arpruss** [comment]
Problem gone in 0.6.4.

**Comment by arpruss** [comment]
Of course, one doesn't just want to plonk in the current version of the jedi library. For instance, replacing the jedi library with the latest breaks jedi.parser.utils, and hence causes problems with some hover docstrings. But at least it fixes wildcard import (which is more important for my purposes).

**Comment by DonJayamanne** [comment]
@arpruss Apologies for not getting back to you on this. As you may have noticed I have looked into this issue. Unfortunately at this stage its an upstream issue with Jedi. I could update Jedi to the latest version, however that introduces a whole load of other issues (i.e. breaks things that used to work).

Will review the latest version of Jedi once again.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#121
