### ISSUE TITLE
Annoying docstrings

### ISSUE THREAD

**Issue by arpruss** [DonJayamanne/pythonVSCode#977]
## Actual behavior
When I mouse-over a variable, I get information about the datatype. But when the variable is something like an int, it's annoying to get a tooltip with a paragraph of information about the int() constructor. It's distracting to constantly have such large tooltips show up.

**Comment by DonJayamanne** [comment]
Unfortunately, that's part of the functionality of vscode. To show hover docstring.

**Comment by gyermolenko** [comment]
@arpruss at least you can disable hover tooltips altogether with info from here [#19988](https://github.com/Microsoft/vscode/issues/19988)

**Comment by arpruss** [comment]
I removed all of the annoyance in a very hackish way. Around line 378 of pythonFiles/completion.py in the pythonVSCode extension, I replaced:
`                try:
                     docstring = definition.docstring()
                     rawdocstring = definition.docstring(raw=True)
                except Exception:
                    docstring = ''
                    rawdocstring = ''
`
with
`                try:
                    if definition.name.startswith("def ") or definition.name.startswith("class "):
                        docstring = definition.docstring()
                        rawdocstring = definition.docstring(raw=True)
                    else:
                        raise Exception()
                except Exception:
                    docstring = ''
                    rawdocstring = ''
`

This way, I get docstrings for defs and for defined classes, but not for built-ins like int and float. I still get a little hover note that says that the variable is an int or a float, but that's potentially helpful.

**Comment by arpruss** [comment]
Better yet (though still hackish): set the docstrings to empty if `definition.type == "instance" and module_path == ""`.
