### ISSUE TITLE
When this extension is enabled, output in the OUTPUT window is uncoloured

### ISSUE THREAD

**Issue by tamj0rd2** [DonJayamanne/pythonVSCode#978]
## Environment data
VS Code version:  1.12.2
Python Extension version:  0.6.4
Python Version:   3.4.4
OS and version:    Windows 10
Output Colorizer extension version: 0.1.1

## Actual behavior
When running a Task, all output in the OUTPUT window is uncoloured
![code_2017-05-23_09-14-27](https://cloud.githubusercontent.com/assets/20561445/26345327/7a61942c-3f9a-11e7-8148-08100b33e85a.png)

## Expected  behavior
When running a Task, output in the OUTPUT window should be coloured
![code_2017-05-23_09-13-26](https://cloud.githubusercontent.com/assets/20561445/26345331/7ea345da-3f9a-11e7-9f5f-8f4cd9b728d4.png)

## Steps to reproduce:  
-  Open the `tasks: run task` menu
-  Run my build task (which uses gulp)
-  Press `ctrl+shift+u` to open the OUTPUT window
-  All of the text is uncoloured

If I uninstall the Python extension and go through the above steps again, the OUTPUT is coloured as expected. It only stops working correctly when the Python extension is installed. I need to work with both Gulp and Python within the same project, and this is making reading my Gulp output very difficult.

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
N/A (don't have one)
```   
Your settings.json:   
```json
N/A (don't have one)
```   
## Logs
Output from ```Python``` output panel  
```
----------Generating Tags----------
ctags --options=C:\Users\tamj0rd2\.vscode\extensions\donjayamanne.python-0.6.4\resources\ctagOptions --languages=Python --exclude=**/site-packages/** -o c:\Users\tamj0rd2\coding\autotools3/.vscode/tags .
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
Overwriting extension <<.log>> to now point to mime <<text/x-code-output>>
(anonymous) @ mime.ts:59
```

Related issue: https://github.com/IBM-Bluemix/vscode-log-output-colorizer/issues/16

**Comment by DonJayamanne** [comment]
I have removed code that affected this. The next release of the extension will resolve this issue.
