### ISSUE TITLE
Cannot detect virtual environment when use command to select workspace interpreter

### ISSUE THREAD

**Issue by tangorboyz** [DonJayamanne/pythonVSCode#979]
## Environment data
VS Code version:  1.12.2
Python Extension version:  0.6.4
Python Version:   3.5.2
OS and version:    Ubuntu 16.04.2

## Actual behavior
Python virtual environment did not appear in select workspace interpreter list although virtual environment has been activated.
## Expected  behavior
Previous version of python plugin could detect python virtual environment when we use select workspace interpreter from visual studio command palette.
## Steps to reproduce:  
-  
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by garyxdh** [comment]
I met this issues also, have anyone solved it?

**Comment by appleyuchi** [comment]
I met this issues also,why this is closed?

**Comment by appleyuchi** [comment]
@DonJayamanne excuse me ,it still doesn't be fixed ,I have read some files in pythonVSCode,
and 
npm install
the function"select workspace interpreter"still fail to choose the right python virtual environment in ubuntu16.04.
please help~
