### ISSUE TITLE
Unable to update to Version 0.3.5

### ISSUE THREAD

**Issue by IgorKoltunov** [DonJayamanne/pythonVSCode#98]
Environment: Version 0.3.4 on vs code 1.0.0 portable on windows 7 pro

When I try to update the extension using `ext update` vs code command, I do see the extension as in need of update. However when I click the cloud icon to install it, the "installing" process never finishes. Perhaps this is an VS Code issue as I have not tried updating other extensions.

My workaround was to remove and re-install the extension and this worked. I also noticed it took a while to install it so it could also be my slow, fire-walled connection.

![image](https://cloud.githubusercontent.com/assets/13897248/14791313/32b4ef62-0aca-11e6-903c-694cce3e9935.png)

**Comment by DonJayamanne** [comment]
Sissy, but this would be a vs Code issue. Possible there was a delay in downloading the updated extension or similar.

**Comment by IgorKoltunov** [comment]
Thanks for taking a look! I agree with the closure.
