### ISSUE TITLE
Disable formatting?

### ISSUE THREAD

**Issue by janhancic** [DonJayamanne/pythonVSCode#989]
## Environment data
VS Code version:  1.13.0-insider
Python Extension version:  0.6.4
Python Version:   
OS and version:    

I came back to work today and whenever I save a python file I get a message "Formatter autopep8 is not installed".

I don't see any option to disable formatting or is there?

**Comment by DonJayamanne** [comment]
Disable the seeing 'format on save' in settings.json

**Comment by DonJayamanne** [comment]
Disable the setting 'format on save' in settings.json

**Comment by janhancic** [comment]
I had it disabled the whole time and it was still doing it.

I've updated VSCode-insiders just now and it seems to have stopped doing it now. Maybe it was just an interim bug. I'll report back if it starts happening again. Thanks.

**Comment by janhancic** [comment]
Can you re-open this please, it's happening still:

![image](https://cloud.githubusercontent.com/assets/356488/26625112/0babfd4a-45eb-11e7-99fb-a0bc82e568f2.png)

I haven't overridden the setting in my user or workspace setting file.

**Comment by DonJayamanne** [comment]
Will add that, thanks for the info

**Comment by gregwym** [comment]
Similar to this problem, I need to keep `editor.formatOnSave` to true for other file types except python. Shall we let `python.formatting.formatOnSave` override `editor.formatOnSave`?

**Comment by DonJayamanne** [comment]
The new solution is simple, if you do not want any formatting for format on save, then either turn it off globally (as that's what vs code does), or just configure ```none``` as the formatter for python in the settings.

I dont want to have ```python.foratting.formatOnSave overrirding``` the ```editor.formatOnSave```, as that just introduces some inconsistencies.
