### ISSUE TITLE
Rename Symbol not working for function names

### ISSUE THREAD

**Issue by mscreations** [DonJayamanne/pythonVSCode#991]
## Environment data
VS Code version:  1.12.2
Python Extension version:  0.6.4
Python Version:   3.6.1
OS and version:    macOS Sierra 10.12.4 

## Actual behavior
When activating the "Rename Symbol" feature, it asks for the replacement, but after typing a new name and pressing enter, nothing happens. There is a "progress bar" that runs across the top of the editor window that keeps running across the top.

## Expected  behavior
The function name should be renamed in all locations

## Steps to reproduce:  
-  Create a new python file like:
```
#!/usr/bin/env python3

""" Testing file """

def main():
    """ Main function """
    testvar = "some testing"

    print("Testing")
    print(testvar)

if __name__ == "__main__":
    main()

```
-  Try to Rename the main function

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
{
    "python.pythonPath": "python3",
    "python.linting.pylintPath": "/Library/Frameworks/Python.framework/Versions/3.6/bin/pylint"
}
```   
## Logs
Output from ```Python``` output panel  
```
Nothing appears
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
Nothing appears
```

**Comment by jakinov** [comment]
Have same issue on Windows.

**Comment by DonJayamanne** [comment]
Closing in favor of https://github.com/DonJayamanne/pythonVSCode/issues/824
