### ISSUE TITLE
Issue with autoFormatOnSave and yapf

### ISSUE THREAD

**Issue by dcramer** [DonJayamanne/pythonVSCode#992]
## Environment data
VS Code version:  1.12.2 (tried Insiders as well)
Python Extension version:  0.6.4
Python Version:   2.7.13
OS and version:    macOS Sierra 10.12.4

## Actual behavior
Upon save it reformats the file, and does not appear to behave the same as ``yapf -i file``.

For example, this content:

```python
from __future__ import absolute_import

from django.db import models
from django.utils import timezone

from sentry.db.models import (BoundedBigIntegerField, FlexibleForeignKey,
                              Model, sane_repr)

```

When I hit save, it generates invalid Python:

```python
from __future__ import absolute_import

from django.db import models
from django.utils import timezone

from sentry.db.models import (
    BoundedBigIntegerField, FlexibleForeignKey, Model, sane_repr
)
)
```

## Expected  behavior

The expected output should be:

```python
from __future__ import absolute_import

from django.db import models
from django.utils import timezone

from sentry.db.models import (
    BoundedBigIntegerField, FlexibleForeignKey, Model, sane_repr
)
```

## Steps to reproduce:  
-  add ``editor.formatOnSave`` to workspace settings
-  save the file

Even when it doesnt incorrectly format the file into invalid Python, it doesnt seem to respect the configuration within setup.cfg (i still get different output from yapf -i).

Here is the changeset which we identified this behavior in:

https://github.com/getsentry/sentry/commit/a2587aa38a40c283eb6780e34f9caefa452ccf77

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
{
    "files.exclude": {
        "**/*.pyc": true,
        "static": true,
        "node_modules": true,
        "src/sentry/static/dist": true,
        "env": true
    },
    "prettier.bracketSpacing": false,
    "prettier.singleQuote": true,
    "prettier.printWidth": 90,
    "eslint.options": {
        "configFile": ".eslintrc"
    },
    "[javascript]": {
        "editor.formatOnSave": true
    },
    "[json]": {
        "editor.formatOnSave": true
    },
    "editor.formatOnSave": true,
    "python.linting.pylintEnabled": false,
    "python.linting.flake8Enabled": true,
    "python.formatting.provider": "yapf",
    "python.pythonPath": "${env.WORKON_HOME}/sentry/bin/python"
}
```

**Comment by seanbrant** [comment]
@dcramer I was running into this as well and might have a temporary solution.

`"python.formatting.yapfArgs": ["--style", "${workspaceRoot}/setup.cfg"],`

**Comment by dcramer** [comment]
@seanbrant great idea! Will give this a try tomorrow and report back.

**Comment by yegorski** [comment]
As far as `autopep8` config is concerned, I got away with this in VS Code's `User Settings`:

`"python.formatting.autopep8Args": ["--max-line-length=120"]`

Now on my Mac's VS Code, pressing Option + Shift + F formats the files I want to format.

**Comment by DonJayamanne** [comment]
@yegorski, apologies for not having resolved this issue yet. Will look into this soon. I believe I know the problem (I'm creating a temporary file to perform the formatting, and in doing so, the config file isn't picked up)

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#124
