### ISSUE TITLE
Radon Cyclomatic Complexity

### ISSUE THREAD

**Issue by IgorNovozhilov** [DonJayamanne/pythonVSCode#993]
Hi!
I propose to add in the static analysis evaluation of cyclomatic complexity of methods.
https://radon.readthedocs.io/en/latest/intro.html#cyclomatic-complexity
https://radon.readthedocs.io/en/latest/commandline.html#the-cc-command

default rank:
F - Error
E - Warning
D - Hint
other - ignore

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#125
