### ISSUE TITLE
Auto complete not work if the current file is not a .py one

### ISSUE THREAD

**Issue by dianlujitao** [DonJayamanne/pythonVSCode#995]
## Environment data
VS Code version:  1.12.2
Python Extension version:  0.6.4
Python Version:   3.6.1
OS and version:    latest Arch Linux

## Actual behavior
If the current file is not a .py file, auto complete won't work
## Expected  behavior
Auto complete should work out of the box
## Steps to reproduce:  
-  Simply create a new file with Ctrl+N without saving it
-  Change language from plain text to python
-  Type sth., auto complete doesn't work but highlighting does

**Comment by DonJayamanne** [comment]
Fixed in https://github.com/DonJayamanne/pythonVSCode/issues/1194
Fix will be available in the next version (later this month).
